### ISSUE TITLE
Cannot coc-rename on gopls 

### ISSUE THREAD

**Issue by sluongng** [neoclide/coc.nvim#1052]
## Result from CocInfo

Rather CocOpenLog since triggering coc-rename did not change anything in CocInfo (yes i have set it to verbose)
```
2019-07-31T18:53:20.637 ERROR (pid:18265) [plugin] - Error: old and new names are the same: NewProofOfWork
    at client.sendRequest.then (/home/nb/.local/share/nvim/plugged/coc.nvim/build/index.js:77788:39)
```

## Describe the bug

Using gopls, the renaming function of coc does not open up a menu to type new name but just straight up print out error prompt

Using saibing (bingo) fork of gopls https://github.com/saibing/tools and rename worked (however after renaming using bingo fork, cannot navigate to definition, possibly another separate bug) 

## Reproduce the bug

**Note**, if you can't provide minimal vimrc that could reproduce the issue,
it's most likely we can't do anything to help.

- Create file `mini.vim` with：

  ```vim
  nmap <leader>rn <Plug>(coc-rename)
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

- Use gopls (provided by vim-go :GoInstallBinaries)

- Press <leader>rn on top of a function reference in a gofile

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/26684313/62231938-4f303780-b3c5-11e9-9f88-72fa89bc32d2.png)

**Comment by sluongng** [comment]
I do think that this is possibly caused by some conflict with `gopls` interface incompatible... but the error failed to describe the issue and instead tell us something else.

I suggest check on the error handling of rename feature so that it return the correct error.

Then we can troubleshoot what is wrong with coc.nvim vs gopls rename integration

**Comment by chemzqm** [comment]
What's the problem? The message seems quite cleat, what would you expect?

**Comment by avahe-kellenberger** [comment]
`the renaming function of coc does not open up a menu to type new name but just straight up print out error prompt`

Looks like it's immediately triggering the rename without allowing the user to set a new name.

**Comment by chemzqm** [comment]
> Looks like it's immediately triggering the rename without allowing the user to set a new name.

No, coc-rename request new name before server request.

It's problem of gopls.

**Comment by chemzqm** [comment]
If you think it's issue of coc.nvim, please provide full output of language server https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by sluongng** [comment]
> > Looks like it's immediately triggering the rename without allowing the user to set a new name.
> 
> No, coc-rename request new name before server request.
> 
> It's problem of gopls.

agree that problem is with gopls, but this issue was raised in concern over the error reporting of coc.nvim

If this is a gopls issue, the error should have said there is something wrong with the LSP spec integration. But in this case, the error is suggesting no such and make user a bit confusing.

**Comment by Avi-D-coder** [comment]
I'm having the same issue with Haskell-IDE-engine.

**Comment by AnatoleLucet** [comment]
I'm still having this issue.
```
## versions

vim version: NVIM v0.5.0-dev
node version: v14.5.0
coc.nvim version: 0.0.79-b77dc8336e
coc.nvim directory: /home/anatole/.vim/plugged/coc.nvim
term: st-256color
platform: linux

## Log of coc.nvim

2020-11-11T19:27:44.966 INFO (pid:106743) [services] - registered service "eslint"
2020-11-11T19:27:45.159 INFO (pid:106743) [services] - registered service "highlight"
2020-11-11T19:27:45.167 INFO (pid:106743) [language-client-index] - highlight started with 107447
2020-11-11T19:27:45.173 INFO (pid:106743) [services] - registered service "go"
2020-11-11T19:27:45.173 INFO (pid:106743) [services] - gopls state change: stopped => starting
2020-11-11T19:27:45.318 INFO (pid:106743) [services] - gopls state change: starting => running
2020-11-11T19:27:45.320 INFO (pid:106743) [services] - service go started
2020-11-11T19:27:45.351 INFO (pid:106743) [language-client-index] - cSpell started with 107486
2020-11-11T19:27:45.371 INFO (pid:106743) [plugin] - coc.nvim 0.0.79-b77dc8336e initialized with node: v14.5.0 after 1827ms
2020-11-11T19:27:51.190 ERROR (pid:106743) [commands] - Error: old and new names are the same: url
    at /home/anatole/.vim/plugged/coc.nvim/build/index.js:81077:47
    at async RenameManager.provideRenameEdits (/home/anatole/.vim/plugged/coc.nvim/build/index.js:78232:16)
    at async Languages.provideRenameEdits (/home/anatole/.vim/plugged/coc.nvim/build/index.js:76963:16)
    at async Handler.getWordEdit (/home/anatole/.vim/plugged/coc.nvim/build/index.js:93973:24)
    at async Plugin.cocAction (/home/anatole/.vim/plugged/coc.nvim/build/index.js:24009:16)
    at async Object.execute (/home/anatole/.vim/plugged/coc.nvim/build/index.js:24239:28)
    at async Handler.runCommand (/home/anatole/.vim/plugged/coc.nvim/build/index.js:94109:23)
    at async Plugin.cocAction (/home/anatole/.vim/plugged/coc.nvim/build/index.js:24009:16)
    at async NeovimClient.<anonymous> (/home/anatole/.vim/plugged/coc.nvim/build/index.js:11597:21)
```

**Comment by chemzqm** [comment]
Upgrade your gopls

**Comment by normen** [comment]
> Upgrade your gopls

To which version? I did `go get github/gopls` but there is no newer version?
