### ISSUE TITLE
coc.vim not work with gopls

### ISSUE THREAD

**Issue by zhangpengbackend** [neoclide/coc.nvim#1086]
macos 10.14  golang1.12.5 vim 8.1

2019-08-13T22:34:51.388 INFO (pid:61438) [services] - registed service "languageserver.golang"
2019-08-13T22:34:51.391 INFO (pid:61438) [services] - golang state change: stopped => starting
2019-08-13T22:34:51.397 INFO (pid:61438) [plugin] - coc 0.0.73-e9ef666cb5 initialized with node: v10.16.2
2019-08-13T22:34:51.403 INFO (pid:61438) [language-client-index] - languageserver.golang started with 61476
2019-08-13T22:34:51.513 ERROR (pid:61438) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/Users/zhangpeng/.vim/bundle/coc.nvim/build/index.js:38998:27)
    at Socket.readable.on (/Users/zhangpeng/.vim/bundle/coc.nvim/build/index.js:38983:18)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
2019-08-13T22:35:07.248 INFO (pid:61438) [completion-complete] - Results from: around,ultisnips
2019-08-13T22:35:47.763 INFO (pid:61438) [completion-complete] - Results from: around,ultisnips
2019-08-13T22:35:49.763 INFO (pid:61438) [completion-complete] - Results from: around
2019-08-13T22:35:58.523 INFO (pid:61438) [completion-complete] - Results from: around,ultisnips
2019-08-13T22:36:02.322 INFO (pid:61438) [completion-complete] - Results from: around
2019-08-13T22:36:04.964 INFO (pid:61438) [completion-complete] - Results from: around

**Comment by chemzqm** [comment]
It's problem of your gopls

**Comment by zhangpengbackend** [comment]
> It's problem of your gopls

Thank you. But how can i fix it? I installed gopls by go get

**Comment by zhangpengbackend** [comment]
> It's problem of your gopls

another error 

2019-08-13T23:00:25.646 ERROR (pid:93989) [server] - uncaughtException Error: Header must provide a Content-Length property.
