### ISSUE TITLE
Add ability to specify current filename environment variable in coc-settings.json

### ISSUE THREAD

**Issue by dementor5** [neoclide/coc.nvim#1200]
A have a problem with stylelint and stylelint-processor-styled-components.

To use it with lit-element components and simple css files i need to set in .stylelintrc.js IgnoreFIles:
```
module.exports = {
  extends: [
    'stylelint-config-htmlacademy',
    'stylelint-config-styled-components',
  ],
  processors: [
    [
      'stylelint-processor-styled-components',
      {
        moduleName: 'lit-element',
        importName: 'css',
        strict: true,
        ignoreFiles: [
          '**/*.css',
        ],
      },
    ],
  ],
};

```
But with this option stylelint-processor-styled-components use "picomatch" npm plugin to detect filetype by using the glob and i has got an error:

```
cat index.js | npx stylelint
TypeError: Expected input to be a string
    at Function.picomatch.test (/home/user/Projects/coc-stylelint-error-demonstartion/node_modules/picomatch/lib/picomatch.js:111:11)
    at matcher (/home/user/Projects/coc-stylelint-error-demonstartion/node_modules/picomatch/lib/picomatch.js:59:48)
    at micromatch (/home/user/Projects/coc-stylelint-error-demonstartion/node_modules/micromatch/index.js:49:21)
    at code (/home/user/Projects/coc-stylelint-error-demonstartion/node_modules/stylelint-processor-styled-components/src/index.js:33:27)
    at /home/user/Projects/coc-stylelint-error-demonstartion/node_modules/stylelint/lib/getPostcssResult.js:124:30
    at Array.forEach (<anonymous>)
    at /home/user/Projects/coc-stylelint-error-demonstartion/node_modules/stylelint/lib/getPostcssResult.js:123:32

```
This problem may be solved if i specify filename:
cat index.js | npx stylelint --stdin-filename test.js

Can you add support of %currentFIlename% environment to coc-settings.json?
It may solve this [problem](https://github.com/iamcco/coc-diagnostic/issues/8#issuecomment-534205961) with coc-diagnostic settings and this [problem](https://github.com/neoclide/coc-stylelint/issues/3) with coc-stylelint, if it specify for stylelint correct  --stdin-filename attribute value.
[There is a link to test project](https://github.com/dementor5/coc-stylelint-error-demonstartion)

**Comment by chemzqm** [comment]
No, it won't resolve the problem, the extension could get current filename by `await workspace.document()` resolve configuration with filename could cause issue when using async/await.

coc-diagnostic could support some kind of syntax for current filename.

**Comment by dementor5** [comment]
Ok, my idea is not optimal. workspace.document() may be a solution. Can you add --stdin-filename support for coc-stylelint?
