### ISSUE TITLE
Undefined process.env.VIMCONFIG causes coc not to start

### ISSUE THREAD

**Issue by Axioplase** [neoclide/coc.nvim#1223]
## Result from CocInfo

Buffer is empty

## Describe the bug

I run vim 8.0.1365 or neovim v0.4.2 and the following error happens:
```
2019-09-27T15:43:15.190 ERROR (pid:49394) [plugin] - TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1040:7)
    at Extensions.loadFileExtensions (/Users/me/.vim/vim-addons/github-neoclide-coc.nvim/build/index.js:57394:37)
    at Extensions.init (/Users/me/.vim/vim-addons/github-neoclide-coc.nvim/build/index.js:57088:20)
    at async Plugin.init (/Users/me/.vim/vim-addons/github-neoclide-coc.nvim/build/index.js:53987:13)
    at async NeovimClient.<anonymous> (/Users/me/.vim/vim-addons/github-neoclide-coc.nvim/build/index.js:1697:21)
```

This is the code in question:
```
    async loadFileExtensions() {
        if (global.hasOwnProperty('__TEST__'))
            return;
        let folder = path_1.default.join(process.env.VIMCONFIG, 'coc-extensions');
        if (!fs_1.default.existsSync(folder))
            return;
        let files = await fs_2.readdirAsync(folder);
        files = files.filter(f => f.endsWith('.js'));
        for (let file of files) {
            this.loadExtensionFile(path_1.default.join(folder, file));
        }
    }
```
It fails on the assignment of the variable "folder".

## Reproduce the bug

- Create file `mini.vim` with：

```vim

set runtimepath=~/.nvim/,$VIMRUNTIME

" I want Vim, not Vi
set nocompatible

" Don't want to type indention
set autoindent

" Only hide invisible buffers (keeps their editing state)
set hidden

fun! EnsureVamIsOnDisk(vam_install_path)
  " windows users may want to use http://mawercer.de/~marc/vam/index.php
  " to fetch VAM, VAM-known-repositories and the listed plugins
  " without having to install curl, 7-zip and git tools first
  " -> BUG [4] (git-less installation)
  let is_installed_c = "isdirectory(a:vam_install_path.'/vim-addon-manager/autoload')"
  if eval(is_installed_c)
    return 1
  else
    if 1 == confirm("Clone VAM into ".a:vam_install_path."?","&Y\n&N")
      " I'm sorry having to add this reminder. Eventually it'll pay off.
      call confirm("Remind yourself that most plugins ship with ".
                  \"documentation (README*, doc/*.txt). It is your ".
                  \"first source of knowledge. If you can't find ".
                  \"the info you're looking for in reasonable ".
                  \"time ask maintainers to improve documentation")
      call mkdir(a:vam_install_path, 'p')
      execute '!git clone --depth=1 git://github.com/MarcWeber/vim-addon-manager '.shellescape(a:vam_install_path, 1).'/vim-addon-manager'
      " VAM runs helptags automatically when you install or update 
      " plugins
      exec 'helptags '.fnameescape(a:vam_install_path.'/vim-addon-manager/doc')
    endif
    return eval(is_installed_c)
  endif
endfun

fun! SetupVAM()
  " VAM install location:
  let vam_install_path = expand('$HOME') . '/.vim/vim-addons'
  if !EnsureVamIsOnDisk(vam_install_path)
    echohl ErrorMsg | echomsg "No VAM found!" | echohl NONE
    return
  endif
  exec 'set runtimepath+='.vam_install_path.'/vim-addon-manager'

  " Tell VAM which plugins to fetch & load:
  call vam#ActivateAddons([
        \"github:neoclide/coc.nvim",
        \], {'auto_install' : 1})
endfun

call SetupVAM()
  ```

- Start (neo)vim with command: `vim -u mini.vim`

The error happens immediately.

## Screenshots (optional)

N/A

**Comment by chemzqm** [comment]
You're using outdated js with latest vim code
