### ISSUE TITLE
AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by furrycatherder** [neoclide/coc.nvim#1246]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.2
node version: v11.15.0
coc.nvim version: 0.0.74-e04013a8bd
term: xterm-256color
platform: linux

## Messages
[coc.nvim] error: Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "/run/user/1000/tmp.R14wNBKK7P/lib/python2.7/site-packages/site.py", line 73, in <module>
    __boot()
  File "/run/user/1000/tmp.R14wNBKK7P/lib/python2.7/site-packages/site.py", line 26, in __boot
    import imp  # Avoid import loop in Python 3
  File "/usr/lib/python3.7/imp.py", line 27, in <module>
    import tokenize
  File "/usr/lib/python3.7/tokenize.py", line 33, in <module>
    import re
  File "/usr/lib/python3.7/re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
[coc.nvim] error: Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "/run/user/1000/tmp.R14wNBKK7P/lib/python2.7/site-packages/site.py", line 73, in <module>
    __boot()
  File "/run/user/1000/tmp.R14wNBKK7P/lib/python2.7/site-packages/site.py", line 26, in __boot
    import imp  # Avoid import loop in Python 3
  File "/usr/lib/python3.7/imp.py", line 27, in <module>
    import tokenize
  File "/usr/lib/python3.7/tokenize.py", line 33, in <module>
    import re
  File "/usr/lib/python3.7/re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

match 1 of 16
match 1 of 16
match 1 of 2
match 1 of 2
Pattern not found
## Output channel: Python

Starting Jedi Python language engine.
##########Linting Output - pylint##########
```

## Describe the bug

```[coc.nvim] error: Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "/run/user/1000/tmp.R14wNBKK7P/lib/python2.7/site-packages/site.py", line 73, in <module>
    __boot()
  File "/run/user/1000/tmp.R14wNBKK7P/lib/python2.7/site-packages/site.py", line 26, in __boot
    import imp  # Avoid import loop in Python 3
  File "/usr/lib/python3.7/imp.py", line 27, in <module>
    import tokenize
  File "/usr/lib/python3.7/tokenize.py", line 33, in <module>
    import re
  File "/usr/lib/python3.7/re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
[coc.nvim] error: Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "/run/user/1000/tmp.R14wNBKK7P/lib/python2.7/site-packages/site.py", line 73, in <module>
    __boot()
  File "/run/user/1000/tmp.R14wNBKK7P/lib/python2.7/site-packages/site.py", line 26, in __boot
    import imp  # Avoid import loop in Python 3
  File "/usr/lib/python3.7/imp.py", line 27, in <module>
    import tokenize
  File "/usr/lib/python3.7/tokenize.py", line 33, in <module>
    import re
  File "/usr/lib/python3.7/re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

This message is displayed when opening a Python file with coc enabled.

## Reproduce the bug

`mini.vim`:

```
set nocompatible
set runtimepath^=~/.local/share/nvim/plug/coc.nvim
filetype plugin indent on
syntax on
set hidden
```

The same message is displayed as above.

**Comment by chemzqm** [comment]
Can't help, it's problem of your python.
