### ISSUE TITLE
Missing Content-Length header error with EmmyLua-LSP

### ISSUE THREAD

**Issue by wbthomason** [neoclide/coc.nvim#1327]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-136-g75ad55874
node +ersion: v12.13.0
coc.nvim version: 0.0.74
term: xterm-kitty
platform: linux

## Messages
[coc.nvim] error: Uncaught exception: Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/home/wil/dotfiles/neovim/.config/nvim/pack/minpac/opt/coc.nvim/node_modules/vscode-jsonrpc/lib/messageReader.js:163:27)
    at Socket.<anonymous> (/home/wil/dotfiles/neovim/.config/nvim/pack/minpac/opt/coc.nvim/node_modules/vscode-jsonrpc/lib/messageReader.js:148:18)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
[coc.nvim] error: Uncaught exception: Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/home/wil/dotfiles/neovim/.config/nvim/pack/minpac/opt/coc.nvim/node_modules/vscode-jsonrpc/lib/messageReader.js:163:27)
    at Socket.<anonymous> (/home/wil/dotfiles/neovim/.config/nvim/pack/minpac/opt/coc.nvim/node_modules/vscode-jsonrpc/lib/messageReader.js:148:18)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)

[coc.nvim] error: Uncaught exception: Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/home/wil/dotfiles/neovim/.config/nvim/pack/minpac/opt/coc.nvim/node_modules/vscode-jsonrpc/lib/messageReader.js:163:27)
    at Socket.<anonymous> (/home/wil/dotfiles/neovim/.config/nvim/pack/minpac/opt/coc.nvim/node_modules/vscode-jsonrpc/lib/messageReader.js:148:18)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
[coc.nvim] error: Uncaught exception: Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/home/wil/dotfiles/neovim/.config/nvim/pack/minpac/opt/coc.nvim/node_modules/vscode-jsonrpc/lib/messageReader.js:163:27)
    at Socket.<anonymous> (/home/wil/dotfiles/neovim/.config/nvim/pack/minpac/opt/coc.nvim/node_modules/vscode-jsonrpc/lib/messageReader.js:148:18)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23)
## Output channel: snippets


## Output channel: highlight

[Info  - 11:09:37 PM] Highlight server running in node v12.13.0
```

## Describe the bug

As shown in the error messages, attempting to use `coc.nvim` with https://github.com/EmmyLua/EmmyLua-LanguageServer causes errors complaining about a missing Content-Length header and a resulting lack of LSP functionality. I'm not 100% certain that this is a bug with `coc`; I reported it to EmmyLua first (https://github.com/EmmyLua/EmmyLua-LanguageServer/issues/21) and was told that the server works fine with VS Code and Sublime. This leads me to believe it may be an issue with `coc`.

## Reproduce the bug

- Build latest `EmmyLua-LS-all.jar` per instructions at https://github.com/EmmyLua/EmmyLua-LanguageServer
- Create file `mini.vim` with：
  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```
- Configure `coc.nvim` to have
```json
{
  "languageserver": {
    "lua": {
      "command": "java",
      "args": ["-cp", "/path/to/EmmyLua-LanguageServer/EmmyLua-LS/build/libs/EmmyLua-LS-all.jar", "com.tang.vscode.MainKt"],
      "filetypes": ["lua"],
      "rootPatterns": [".git/"]
    },
  }
}
```

- Start neovim with command: `nvim -u mini.vim somefile.lua`
- Operate nvim. 
- Note the errors in `:CocInfo` and the lack of LSP functionality.

**Comment by chemzqm** [comment]
It's bug of your language server
