### ISSUE TITLE
Crashing CQuery

### ISSUE THREAD

**Issue by dqian96** [neoclide/coc.nvim#1364]
## Result from CocInfo
```
## versions vim version: NVIM v0.3.8 node version: v10.16.0 coc.nvim version: 0.0.74-3a7f1335ae term: screen-256color platform: linux ## Messages"/data/users/dqian96/randomsource/randomcode/jobs/ranker/Table.h" 134L, 3583C
"JurassicMLPipelineLogger.cpp" 271L, 9259C
Error detected while processing /home/dqian96/.config/nvim/sessions/%data%users%dqian96%randomsource%randomcode%jobs%ranker:

## Output channel: languageserver.cquery
[0m[2m2019-11-22 17:13:38.653 (   0.001s) [     B656A780]        loguru.hpp:2049     0| [0m[1mLogging to '/tmp/cq.log', mode: 'w', verbosity: 9[0m
LIBCLANG FATAL ERROR: Invalid abbrev number
libclang: crash detected during parsing: {
  'source_filename' : '(null)'
  'command_line_args' : 

...

'/data/users/dqian96/randomsource/randomcode/jobs/ranker/JurassicMLPipelineLogger.cpp', '-resource-dir=/mnt/gvfs/third-party2/llvm-ab/adc95979ec77e9548e51d0b1106e81ba3ca59f19/20181009/centos7-native/c9f9104/lib/clang/8.0.20181009', '-fparse-all-comments', '-fspell-checking'
],
  'unsaved_files' : [('/data/users/dqian96/randomsource/randomcode/jobs/ranker/JurassicMLPipelineLogger.cpp', '...', 9259)],
  'options' : 911,
}
[0m[1m[91m
Loguru caught a signal: SIGSEGV
[0m
[Info  - 5:19:17 PM] Connection to server got closed. Server will restart.
[Error  - 5:19:17 PM] Request textDocument/completion failed.
Error: Connection got disposed.
    at Object.dispose (/home/dqian96/.local/share/nvim/plugged/coc.nvim/build/index.js:16192:25)
    at Object.dispose (/home/dqian96/.local/share/nvim/plugged/coc.nvim/build/index.js:54469:35)
    at LanguageClient.handleConnectionClosed (/home/dqian96/.local/share/nvim/plugged/coc.nvim/build/index.js:56590:42)
    at LanguageClient.handleConnectionClosed (/home/dqian96/.local/share/nvim/plugged/coc.nvim/build/index.js:54096:15)
    at closeHandler (/home/dqian96/.local/share/nvim/plugged/coc.nvim/build/index.js:56576:18)
    at CallbackList.invoke (/home/dqian96/.local/share/nvim/plugged/coc.nvim/build/index.js:16834:39)
    at Emitter.fire (/home/dqian96/.local/share/nvim/plugged/coc.nvim/build/index.js:16892:36)
    at closeHandler (/home/dqian96/.local/share/nvim/plugged/coc.nvim/build/index.js:15542:26)
    at CallbackList.invoke (/home/dqian96/.local/share/nvim/plugged/coc.nvim/build/index.js:16834:39)
    at Emitter.fire (/home/dqian96/.local/share/nvim/plugged/coc.nvim/build/index.js:16892:36)
    at StreamMessageReader.fireClose (/home/dqian96/.local/share/nvim/plugged/coc.nvim/build/index.js:16651:27)
    at Socket.readable.on (/home/dqian96/.local/share/nvim/plugged/coc.nvim/build/index.js:16691:46)
    at Socket.emit (events.js:203:15)
    at Pipe._handle.close (net.js:606:12)
[Error  - 5:19:17 PM] /usr/local/okpkg/nuclide/vscode-d/24/node_modules/cquery-bin/cquery-linux exited with code: null
[0m[2m2019-11-22 17:19:17.848 (   0.002s) [     101D8780]        loguru.hpp:2049     0| [0m[1mLogging to '/tmp/cq.log', mode: 'w', verbosity: 9[0m

```

## Describe the bug

I am using coc.nvim on a relatively large C++ codebase. I am using cquery as my lsp. Recently, I am no longer able to get any response from coc - no completion, linting, go-to definitions etc.

It seems that libclang is crashing during parsing.

I am using neovim v0.3.8 on Centos7.

## Reproduce the bug
- vimrc
 ```vim
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}

let g:coc_node_path = expand("/data/users/dqian96/source/xplat/third-party/node/bin/node")
let g:coc_filetype_map = {'cc': 'cpp'}
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> for trigger completion.
inoremap <silent><expr> <c-space> coc#refresh()

" Use <cr> for confirm completion, `<C-g>u` means break undo chain at current position.
" Coc only does snippet and additional edit on confirm.
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
```

- CoC config:
``` json
    "cquery": {
      "enable": true,
      "command": "/usr/local/stuff/stuff2/stuff3/node_modules/cquery-bin/cquery-linux",
      "args": ["--log-file=/tmp/cq.log"],
      "filetypes": ["c", "cpp"],
      "rootPatterns": ["compile_commands.json"],
      "initializationOptions": {
        "cacheDirectory": "/tmp/cquery",
        "index": {
          "blacklist": [".*/buck-out/.*", ".*/third-party-buck/.*", ".*/_build.*/.*"]
        },
        "completion":{
          "includeBlacklist": [".*/buck-out/.*", ".*/third-party-buck/.*", ".*/_build.*/.*"]
        },
        "diagnostics": {
           "blacklist": [".*/buck-out/.*", ".*/third-party-buck/.*", ".*/_build.*/.*"]
        },
        "discoverSystemIncludes": false,
        "showDocumentLinksOnIncludes": false,
        "codeLens": {
           "localVariables": false
        }
      }
    }
  },
```

**Comment by chemzqm** [comment]
Should be problem of your language server, we can't help.
