### ISSUE TITLE
getHover times out when using haskell language server and HIE

### ISSUE THREAD

**Issue by cdimitroulas** [neoclide/coc.nvim#1423]
## Result from CocInfo
Normal output:
```
## versions

vim version: NVIM v0.4.2
node version: v8.16.1
coc.nvim version: 0.0.74-36e476819f
term: screen-256color
platform: linux

## Messages

## Output channel: prettier


## Output channel: languageserver.haskell

2019-12-24 13:01:14.796549919 [ThreadId 4] - run entered for hie-wrapp
er(hie-wrapper) Version 1.0.0.0, Git revision 7e688322a40d91369bd032ea4
be977fa405dc41f (3496 commits) x86_64 ghc-8.
6.5
2019-12-24 1
3:01:14.82460706
6 [ThreadId 4] - Current 
directory:/home/cdimitr
oulas/code/cdimitroulas
/role-matching-config-in
-haskell
2019-12-24 13:01:
14.825105903 [Thread
Id 4] - Operating system:linu
x
2019
-12-24 13:01:14.826605312 [Threa
dId 
4] - 
Cabal-Helper dirs: ["/home/cdimitroulas/co
de/cdimitroulas/role-matching-co
nfig-in-haskell","/home/cdimi
troulas/code/cdimitroulas/
role-matching-config-in-h
askell/File.hs"]
2019-1
2-24 13:01:15.993923058 [ThreadId 4] - Cradle directory:/home/cdimitroulas/c
ode/cdimitroulas/role-matching
-config-in-haskell
2019
-12-24 13:01:15.9944593
79 [ThreadId 4] - Using st
ack GHC version
2019
-12-24 13:01:16.239176487 [ThreadId 4] - Project GHC version:
8.6.5
2019-12-2
4 13:01:16.239564951 [T
hreadId 4] - hie exe candidat
es :["hie-8.6.5","hie-8.6"
,"hie"]
2019
-12-24 13:01:16.240
354126 [ThreadId 4] - found h
ie exe at:/home/cdimitroul
as/.local/bin/hie-8.6.5
2019-12-24
 13:01:16.240817188 [
ThreadId 4] - args:[]
2019-12-24 13:
01:16.241080297 [Thr
eadId 4] - launching ....



2019-12-24 13:01:16.243150423 [ThreadId 4] - Run entered for HIE(hie-8.6.5) Version 1.0.0.0, Git revision 7e688322a40d91369bd032ea4be977fa405dc41f (3496 commits) x86_64 ghc-8.6.5
2019-12-24 13:01:16.243412418 [ThreadId 4] - Current directory:/home/cdimitroulas/code/cdimitroulas/role-matching-config-in-haskell
2019-12-24 13:01:16.243470398 [ThreadId 4] - args:[]
hie-8.6.5: ghc: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Using hie version: Version 1.0.0.0, Git revision 7e688322a40d91369bd032ea4be977fa405dc41f (3496 commits) x86_64 ghc-8.6.5
2019-12-24 13:01:16.273773224 [ThreadId 10] - Cabal-Helper dirs: ["/home/cdimitroulas/code/cdimitroulas/role-matching-config-in-haskell","/home/cdimitroulas/code/cdimitroulas/role-matching-config-in-haskell/File.hs"]
2019-12-24 13:01:17.439086047 [ThreadId 10] - Using stack GHC version
```

With verbose output:
```

## versions

vim version: NVIM v0.4.2
node version: v8.16.1
coc.nvim version: 0.0.74-36e476819f
term: screen-256color
platform: linux

## Messages"/run/user/1000/coc-nvim-13901.log" 14L, 1169C

## Output channel: prettier


## Output channel: languageserver.haskell
[Trace - 12:58:33] Sending request 'initialize - (0)'.
Params: {
    "processId": 13901,
    "rootPath": "/home/cdimitroulas/code/cdimitroulas/role-matching-config-in-haskell",
    "rootUri": "file:///home/cdimitroulas/code/cdimitroulas/role-matching-config-in-haskell",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    }
                }
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "codeAction": {
                "dynamicRegistration": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
            "documentLink": {
                "dynamicRegistration": true
            },
            "typeDefinition": {
                "dynamicRegistration": true
            },
            "implementation": {
                "dynamicRegistration": true
            },
            "declaration": {
                "dynamicRegistration": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            }
        }
    },
    "initializationOptions": {
        "languageServerHaskell": {
            "hlintOn": false
        }
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///home/cdimitroulas/code/cdimitroulas/role-matching-config-in-haskell",
            "name": "role-matching-config-in-haskell"
        }
    ]
}


2019-12-24 12:58:33.491390973 [ThreadId 4] - run entered for hie-wrapp
er(hie-wrapper) Version 1.0.0.0, Git revision 7e688322a40d91369bd032ea
4be977fa405dc41f (3496 commits) x86_64 ghc-8.6.5
2019-12-24 12:58:33.5
0297911 [ThreadId 4] - Current directory:/home/cdimitroulas/code/cdimit
roulas/role-matc
hing-config-in-has
kell
20
19-12-24 1
2:58:33
.520467168 [Th
readId 4] - 
Operating syst
em:linux
201
9-12-24 12:58:33.522
000953 [Thre
adId 4] - Cab
al-Helper dirs: ["/home/cdimitroulas/code/cdimi
troulas/role-matching-confi
g-in-haskell","/home/c
dimitroulas/code/cdimit
roulas/role-matching-c
onfig-in-haskell/File.
hs"]
2019-12-24
 12:58:34.687123234 [ThreadId 4] - Cradle directory:/home/cdimitroulas/c
ode/cdimitroulas/role-matc
hing-config-in-haskell
2019-12-
24 12:58:34.687564653 [ThreadId 4
] - Using stack GHC versi
on
2019-12
-24 12:58:34.932145596 [ThreadId 4] - Project GHC ve
rsion:8.6.5
2019-
12-24 12:58:34.93252
7726 [ThreadId 4] - h
ie exe candidates :["hi
e-8.6.5","hie-8.6","h
ie"]
2019-1
2-24 12:58:34.93323738
4 [ThreadId 4] - found hie e
xe at:/home/cdimitroulas/
.local/bin/hie-8.6.5
2019-12-24 
12:58:34.933666045 
[ThreadId 4] - args:[
]
2019-12-24 
12:58:34.933874421
 [ThreadId 4] - lau
nching ....



2019-12-24 12:58:34.936351149 [ThreadId 4] - Run entered for HIE(hie-8.6.5) Version 1.0.0.0, Git revision 7e688322a40d91369bd032ea4be977fa405dc41f (3496 commits) x86_64 ghc-8.6.5
2019-12-24 12:58:34.936695869 [ThreadId 4] - Current directory:/home/cdimitroulas/code/cdimitroulas/role-matching-config-in-haskell
2019-12-24 12:58:34.93679577 [ThreadId 4] - args:[]
hie-8.6.5: ghc: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
[Trace - 12:58:34] Received response 'initialize - (0)' in 1446ms.
Result: {
    "capabilities": {
        "typeDefinitionProvider": true,
        "foldingRangeProvider": false,
        "textDocumentSync": {
            "openClose": true,
            "change": 2,
            "willSave": false,
            "willSaveWaitUntil": false,
            "save": {
                "includeText": false
            }
        },
        "workspace": {},
        "implementationProvider": true,
        "documentRangeFormattingProvider": true,
        "documentHighlightProvider": true,
        "executeCommandProvider": {
            "commands": [
                "14032:applyrefact:applyOne",
                "14032:applyrefact:applyAll",
                "14032:applyrefact:lint",
                "14032:bios:check",
                "14032:generic:type",
                "14032:hsimport:import",
                "14032:package:add",
                "14032:pragmas:addPragma"
            ]
        },
        "renameProvider": false,
        "colorProvider": false,
        "definitionProvider": true,
        "hoverProvider": true,
        "codeActionProvider": true,
        "completionProvider": {
            "triggerCharacters": [
                "."
            ],
            "resolveProvider": true
        },
        "documentSymbolProvider": true,
        "documentFormattingProvider": true,
        "referencesProvider": true
    }
}


[Trace - 12:58:34] Sending notification 'initialized'.
Params: {}


[Trace - 12:58:34] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///home/cdimitroulas/code/cdimitroulas/role-matching-config-in-haskell/app/Main.hs",
        "languageId": "haskell",
        "version": 1,
        "text": "module Main where\n\nimport qualified Data.ByteString.Lazy as B\nimport Lib\nimport UpdateRoleMatchingConfiguration (parse)\n\njsonFile :: FilePath\njsonFile = \"test.json\"\n\ngetJSON :: IO B.ByteString\ngetJSON = B.readFile jsonFile\n\nresult = fmap parse getJSON\n\nmain = result\n"
    }
}


2019-12-24 12:58:34.968394208 [ThreadId 8] - Cabal-Helper dirs: ["/home/cdimitroulas/code/cdimitroulas/role-matching-config-in-haskell","/home/cdimitroulas/code/cdimitroulas/role-matching-config-in-haskell/File.hs"]
[Trace - 12:58:34] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "Using hie version: Version 1.0.0.0, Git revision 7e688322a40d91369bd032ea4be977fa405dc41f (3496 commits) x86_64 ghc-8.6.5"
}


Using hie version: Version 1.0.0.0, Git revision 7e688322a40d91369bd032ea4be977fa405dc41f (3496 commits) x86_64 ghc-8.6.5
2019-12-24 12:58:36.149385631 [ThreadId 8] - Using stack GHC version
[Trace - 12:58:52] Sending request 'textDocument/documentHighlight - (1)'.
Params: {
    "textDocument": {
        "uri": "file:///home/cdimitroulas/code/cdimitroulas/role-matching-config-in-haskell/app/Main.hs"
    },
    "position": {
        "line": 0,
        "character": 0
    }
}


[Trace - 12:58:53] Sending request 'textDocument/hover - (2)'.
Params: {
    "textDocument": {
        "uri": "file:///home/cdimitroulas/code/cdimitroulas/role-matching-config-in-haskell/app/Main.hs"
    },
    "position": {
        "line": 7,
        "character": 0
    }
}


[Trace - 12:58:58] Sending notification '$/cancelRequest'.
Params: {
    "id": 1
}


[Trace - 12:59:00] Sending request 'textDocument/documentHighlight - (3)'.
Params: {
    "textDocument": {
        "uri": "file:///home/cdimitroulas/code/cdimitroulas/role-matching-config-in-haskell/app/Main.hs"
    },
    "position": {
        "line": 7,
        "character": 0
    }
}
``` 

## Describe the bug
`getHover` always times out. Running `:CocOpenLog` shows the following:
```
2019-12-24T13:01:13.311 INFO (pid:14602) [services] - registered service "languageserver.haskell"
2019-12-24T13:01:13.324 INFO (pid:14602) [services] - registered service "eslint"
2019-12-24T13:01:13.419 INFO (pid:14602) [plugin] - coc 0.0.74-36e476819f initialized with node: v8.16.1
2019-12-24T13:01:14.781 INFO (pid:14602) [services] - haskell state change: stopped => starting
2019-12-24T13:01:14.795 INFO (pid:14602) [language-client-index] - languageserver.haskell started with 14639
2019-12-24T13:01:16.249 INFO (pid:14602) [services] - haskell state change: starting => running
2019-12-24T13:01:16.258 INFO (pid:14602) [services] - service languageserver.haskell started
2019-12-24T13:01:21.340 ERROR (pid:14602) [languages] - getHover timeout after 5s
2019-12-24T13:01:21.354 ERROR (pid:14602) [plugin] - Error: getHover timeout after 5s
    at Timeout.setTimeout [as _onTimeout] (/home/cdimitroulas/.vim/plugged/coc.nvim/build/index.js:49282:28)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

## Reproduce the bug
1. nvim config:
```
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

set number
set expandtab
set shiftwidth=2
set softtabstop=2
set nowrap " Do not wrap long lines
set backupcopy=yes " Set backupcopy so webpack-dev-server always notices file saves
let mapleader="," " Leader
au! BufNewFile,BufRead *.svelte set ft=html " Set svelte files to HTML syntax highlighting

" You will have bad experience for diagnostic messages when it's default 4000.
set updatetime=500
```

2. Open a minimal Haskell file like:
```hs
module Test where

import Data.Bool

Bool
```

3. Hover on `Bool` and run `:CocAction('getHover')`

4. Should receive a timeout.

Versions:
- `stack` - v2.1.3
- `ghci` - `v8.6.5`
- `haskell-ide-engine` - `8.6.5` (installed using `stack ./install.hs hie-8.6.5` && `stack ./install.hs build-data` in the haskell-ide-engine repo)

Coc config:
```
{
  "eslint.autoFixOnSave": true,
  "eslint.filetypes": ["javascript", "javascript.jsx", "javascriptreact", "typescript", "typescriptreact",  "typescript.tsx"],
  "languageserver": {
    "haskell": {
      "command": "hie-wrapper",
      "rootPatterns": ["stack.yaml", "cabal.config", "package.yaml"],
      "filetypes": ["hs", "lhs", "haskell"],
      "initializationOptions": {
        "languageServerHaskell": {
        }
      }
    }
  },
  "prettier.requireConfig": true
}
```

**Comment by fannheyward** [comment]
Timeout is always caused by language server. There is an error: `ghc: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)`. I don't know if this is works correctly.

**Comment by chemzqm** [comment]
Should be problem of your language server, you can see `textDocument/hover` request send as expected and no response.

**Comment by cdimitroulas** [comment]
OK, thanks for confirming. I will try to debug the language server itself :+1:
