### ISSUE TITLE
"Error on request (CocAutocmd): timeout after 30s" with coc-highlight on ":bd" and ":q" hangs vim

### ISSUE THREAD

**Issue by dezza** [neoclide/coc.nvim#1439]
## versions

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 26 2019 19:26:35)
node version: v12.14.0
coc.nvim version: 0.0.74
term: dumb
platform: linux

**NOTE: It's running on WSL (Windows Subsystem for Linux), Debian on Windows**

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
## Output channel: highlight

[Info  - 1:31:03 AM] Highlight server running in node v12.14.0

## Describe the bug
I just discovered a very annoying loop that slows down vim to halt.

This is tested with a clean .vimrc (none), coc.nvim and only happens with `coc-highlight` installed just open `vim` then repeatedly

`:h type`
 and close with 
`:bd`

3-4 times and the 3/4 time it hangs with:

`Error on request (CocAutocmd): timeout after 30s`

When it finally returns Vim seems fairly responsive until I quit vim with `:q` and it halts again and I again get:

`Error on request (CocAutocmd): timeout after 30s`

I tried to watch log meanwhile, didn't produce anything useful in `:CocOpenLog` with `COC_LOG_LEVEL=debug`, I also tried hooking up the inspector, this did not "follow" the execution without any breakpoints so I was clueless where to break or if this would work at all I didn't see errors though.

I found out it can only be reproduced with "coc-highlight" installed. This is with no vimrc and only "coc-highlight" installed, without "coc-highlight" cannot be reproduced.

As this did not reproduce when opening main help page `:h` but only `:h type` I can only assume maybe some extension is reacting to the content in `:h type`

As I know this problem is probably hard to reproduce I politely ask what might be running with `CocAutocmd` with extensions, when a buffer is closed or deleted, specifically with coc-highlight, could it be the **Output channel**? Maybe its something like a "NULL" situation where something is trying to reach the "buffer" just deleted with ":bd" ? Or a procedure running on every buffer exit, even :q ? Could this be OutputChannel?

_WHY even bother?_

Well, I kept discovering a "node" instance consuming considerable CPU and my Vim frozen at random occassions, so I tried to figure out what was causing this in-between writing and visiting ":h" files this made my vim unusable from time to time without knowing the cause. I could not reproduce those steps easily happening at random, so this is the next best thing as it's the shortest path to same error.

## Reproduce the bug
Clean vim (no .vimrc)
coc.nvim from git and coc-highlight installed
Enter `:h type` and exit with `:bd` approximately 3-4 times

**Comment by chemzqm** [comment]
Try disable https://github.com/neoclide/coc-highlight, it has performance issue on some situations.

**Comment by dezza** [comment]
No worries `coc-highlight` isn't that important to me. 👍 

To help the project another time, how do you suggest debugging a situation like this?

**Comment by chemzqm** [comment]
Added 2s timeout for request fro vim to node.

**Comment by hienqnguyen** [comment]
I'm not sure if this bit is at all useful.  I've also ran into this same behavior a few times.  I did `:CocInfo` and saw the below in the log:
```2021-12-23T16:09:05.501 INFO (pid:41607) [attach] - receive notification: highlight []
2021-12-23T16:09:06.359 INFO (pid:41607) [attach] - receive request: CocAutocmd [ 'BufWritePre', 1 ]
2021-12-23T16:09:08.361 WARN (pid:41607) [events] - Handler of BufWritePre blocked more than 2s: Error
    at dq.on (/Users/xxxxxxx/.vim/plugged/coc.nvim/build/index.js:133:216)
    at Wj.init (/Users/xxxxxxx/.vim/plugged/coc.nvim/build/index.js:186:11397)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async OP.init (/Users/xxxxxxx/.vim/plugged/coc.nvim/build/index.js:254:5233)
    at async /Users/xxxxxxx/.vim/plugged/coc.nvim/build/index.js:129:13430
2021-12-23T16:09:09.362 ERROR (pid:41607) [attach] - Request cost more than 3s CocAutocmd [ 'BufWritePre', 1 ]
2021-12-23T16:10:50.425 INFO (pid:41607) [attach] - receive request: doAutocmd [ 1, 1 ]
2021-12-23T16:11:50.845 INFO (pid:41607) [attach] - receive notification: highlight []
2021-12-23T16:12:38.868 INFO (pid:41607) [attach] - receive notification: highlight []
2021-12-23T16:12:45.643 INFO (pid:41607) [attach] - receive notification: highlight []
2021-12-23T16:12:47.255 WARN (pid:41607) [events] - Handler of BufCreate blocked more than 2s: Error
    at dq.on (/Users/xxxxxxx/.vim/plugged/coc.nvim/build/index.js:133:216)
    at Wj.init (/Users/xxxxxxx/.vim/plugged/coc.nvim/build/index.js:186:11107)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async OP.init (/Users/xxxxxxx/.vim/plugged/coc.nvim/build/index.js:254:5233)
    at async /Users/xxxxxxx/.vim/plugged/coc.nvim/build/index.js:129:13430
2021-12-23T16:12:47.255 WARN (pid:41607) [events] - Handler of BufEnter blocked more than 2s: Error
    at dq.on (/Users/xxxxxxx/.vim/plugged/coc.nvim/build/index.js:133:216)
    at new VersionStatus (/Users/xxxxxxx/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:10086:51)
    at new TypeScriptServiceClient (/Users/xxxxxxx/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:10278:26)
    at new TypeScriptServiceClientHost (/Users/xxxxxxx/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:11167:19)
    at TsserverService.start (/Users/xxxxxxx/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:11401:23)
    at Object.activate (/Users/xxxxxxx/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:11542:11)
    at Object.activate (/Users/xxxxxxx/.vim/plugged/coc.nvim/build/index.js:228:1333)
    at Qz.activate (/Users/xxxxxxx/.vim/plugged/coc.nvim/build/index.js:225:7266)
    at /Users/xxxxxxx/.vim/plugged/coc.nvim/build/index.js:227:283
    at new Promise (<anonymous>)
```
