### ISSUE TITLE
[coc.nvim] Error on 'highlight': highlights is not iterable

### ISSUE THREAD

**Issue by ssh352** [neoclide/coc.nvim#1461]
<img width="614" alt="Screen Shot 2020-01-13 at 2 27 52 PM" src="https://user-images.githubusercontent.com/41779116/72236281-22897880-3611-11ea-8e47-8732f10362dc.png">

I try to debug where this error comes from, any hints will be appreciated.

**Comment by ssh352** [comment]
" autocmd CursorHold  * silent call CocActionAsync('highlight') together with coc-r-lsp caused it. But I am not sure how. I document here just in case others see the same problem

**Comment by fannheyward** [comment]
Please provide a mini vimrc to reproduce this issue.

**Comment by yech1990** [comment]
I do have the same problem.

**Comment by chemzqm** [comment]
Please paste content from `:CocOpenLog`

**Comment by yech1990** [comment]
```bash
    1 2020-02-10T19:39:48.751 INFO (pid:95073) [services] - registered service "highlight"
    2 2020-02-10T19:39:48.971 INFO (pid:95073) [services] - registered service "r"
    3 2020-02-10T19:39:48.971 INFO (pid:95073) [services] - R Language Server state change: stopped => starting
    4 2020-02-10T19:39:49.000 INFO (pid:95073) [plugin] - coc 0.0.74-6700e7468d initialized with node: v13.8.0
    5 2020-02-10T19:39:49.014 INFO (pid:95073) [language-client-index] - highlight started with 95197
    6 2020-02-10T19:39:49.045 INFO (pid:95073) [language-client-index] - cSpell started with 95204
    7 2020-02-10T19:39:49.119 INFO (pid:95073) [services] - highlight server state change: starting => running
    8 2020-02-10T19:39:49.871 INFO (pid:95073) [services] - R Language Server state change: starting => running
    9 2020-02-10T19:39:49.875 INFO (pid:95073) [services] - service r started
   10 2020-02-10T19:39:50.335 ERROR (pid:95073) [plugin] - TypeError: highlights is not iterable
   11     at DocumentHighlighter.highlight (/home/yc/.cache/vim/dein/.cache/init.vim/.dein/build/index.js:65519:24)
   12     at async Handler.highlight (/home/yc/.cache/vim/dein/.cache/init.vim/.dein/build/index.js:64207:9)
   13     at async Plugin.cocAction (/home/yc/.cache/vim/dein/.cache/init.vim/.dein/build/index.js:32427:21)
   14     at async NeovimClient.<anonymous> (/home/yc/.cache/vim/dein/.cache/init.vim/.dein/build/index.js:10339:25)
   15 2020-02-10T19:39:50.744 ERROR (pid:95073) [plugin] - TypeError: highlights is not iterable
   16     at DocumentHighlighter.highlight (/home/yc/.cache/vim/dein/.cache/init.vim/.dein/build/index.js:65519:24)
   17     at async Handler.highlight (/home/yc/.cache/vim/dein/.cache/init.vim/.dein/build/index.js:64207:9)
   18     at async Plugin.cocAction (/home/yc/.cache/vim/dein/.cache/init.vim/.dein/build/index.js:32427:21)
   19     at async NeovimClient.<anonymous> (/home/yc/.cache/vim/dein/.cache/init.vim/.dein/build/index.js:10339:25)
```

**Comment by fannheyward** [comment]
Looks like this is only happened with R language server, try to upgrade R language server.

**Comment by yech1990** [comment]
upgrade R languageserver can not resolve this problem.

**Comment by yech1990** [comment]
I notice that this issue can only be reproduced when there is cursor movement action before the extensions are ready.

**Comment by oblitum** [comment]
I think it's kind of expected to get errors in that case. Is `autocmd CursorHold * silent call CocActionAsync('highlight')` being recommended anywhere? First time I'm seeing this usage. I'd not recommend it as it can cause your editor to be slow or consume resources.

**Comment by fannheyward** [comment]
@oblitum `autocmd CursorHold * silent call CocActionAsync('highlight')` is in README.

I'm using this autocmd but never encountered this error.

**Comment by oblitum** [comment]
Ah, ok then.
