### ISSUE TITLE
error when edit style in html

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#15]
<img width="1193" alt="2018-07-22 11 39 57" src="https://user-images.githubusercontent.com/5492542/43047347-963f1c42-8e08-11e8-8db8-ef9a63384793.png">

**Comment by iamcco** [comment]
```

[Error - 下午11:39:48] Error while validating file:///Users/aioiyuuko/test.html: Cannot read property 'hasOwnProperty' of null
TypeError: Cannot read property 'hasOwnProperty' of null
    at LintConfigurationSettings.get (/Users/aioiyuuko/.configrc/nvim/viml/plugins/coc.nvim/node_modules/vscode-css-languageservice/lib/umd/services/lintRules.js:59:27)
    at LintVisitor.addEntry (/Users/aioiyuuko/.configrc/nvim/viml/plugins/coc.nvim/node_modules/vscode-css-languageservice/lib/umd/services/lint.js:98:68)
    at LintVisitor.visitRuleSet (/Users/aioiyuuko/.configrc/nvim/viml/plugins/coc.nvim/node_modules/vscode-css-languageservice/lib/umd/services/lint.js:225:22)
    at LintVisitor.visitNode (/Users/aioiyuuko/.configrc/nvim/viml/plugins/coc.nvim/node_modules/vscode-css-languageservice/lib/umd/services/lint.js:132:33)
    at RuleSet.Node.accept (/Users/aioiyuuko/.configrc/nvim/viml/plugins/coc.nvim/node_modules/vscode-css-languageservice/lib/umd/parser/cssNodes.js:206:17)
    at Stylesheet.Node.accept (/Users/aioiyuuko/.configrc/nvim/viml/plugins/coc.nvim/node_modules/vscode-css-languageservice/lib/umd/parser/cssNodes.js:209:27)
    at Stylesheet.Node.acceptVisitor /Users/aioiyuuko/.configrc/nvim/viml/plugins/coc.nvim/node_modules/vscode-css-languageservice/lib/umd/parser/cssNodes.js:214:18)
    at Function.LintVisitor.entries (/Users/aioiyuuko/.configrc/nvim/viml/plugins/coc.nvim/node_modules/vscode-css-languageservice/lib/umd/services/lint.js:54:18)
    at CSSValidation.doValidation (/Users/aioiyuuko/.configrc/nvim/viml/plugins/coc.nvim/node_modules/vscode-css-languageservice/lib/umd/services/cssValidation.js:33:60)
    at Object.doValidation (/Users/aioiyuuko/.configrc/nvim/viml/plugins/coc.nvim/node_modules/vscode-html-languageserver-bin/modes/cssMode.js:22:39)


```

**Comment by chemzqm** [comment]
在看了，先设置
``` json
  "cssserver.wxss.validate": false,
  "cssserver.wxss.lint": false,
  "cssserver.css.validate": false,
  "cssserver.css.lint": false,
  "cssserver.scss.validate": false,
  "cssserver.scss.lint": false,
  "cssserver.less.validate": false,
  "cssserver.less.lint": false,

```
禁掉吧

**Comment by chemzqm** [comment]
修了 vscode-html-languageserver 这模块考虑没考虑设置为空的情况，现在加上 VSCode 的配置了。
