### ISSUE TITLE
UnhandledRejection on fresh install

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#151]
**Describe the bug**
`UnhandledRejection` on fresh install:

```
UnhandledRejection: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at Workspace.<anonymous> (/snapshot/coc.nvim/lib/workspace.js:343:36)
    at Generator.next (<anonymous>)
    at __awaiter (/snapshot/coc.nvim/node_modules/tslib/tslib.js:107:75)
    at new Promise (<anonymous>)
    at Object.__awaiter (/snapshot/coc.nvim/node_modules/tslib/tslib.js:103:16)
    at Workspace.getQuickfixItem (/snapshot/coc.nvim/lib/workspace.js:337:24)
    at Workspace.<anonymous> (/snapshot/coc.nvim/lib/workspace.js:1133:39)
    at Generator.next (<anonymous>)
    at __awaiter (/snapshot/coc.nvim/node_modules/tslib/tslib.js:107:75)
    at new Promise (<anonymous>)
```

**To Reproduce**
1. Just installed it, still unable to use it at all.
2. Error shows up on `:CocErrors`

**Expected behavior**
No errors to give it a try.

**Desktop (please complete the following information):**
 - Terminal: Termite
 - Version: v13
**Additional context**
ArchLinux

**Comment by chemzqm** [comment]
Looks like there's some errors with your `coc-settings.json`.
I would improve coc not throw when this happens.

**Comment by chemzqm** [comment]
Fixed on master branch.

**Comment by oblitum** [comment]
My config is solely this:

```json
"languageserver": {
  "clangd": {
    "command": "clangd",
    "filetypes": ["c", "cpp", "objc", "objcpp"],
    "triggerCharacters": ["."]
  }
}
```

**Comment by oblitum** [comment]
> Fixed on master branch.

OK, will try it.

**Comment by oblitum** [comment]
I've rebuilt, no errors anymore, but the plugin does nothing, this is my minimal `.vimrc`, I've created the `<c-space>` mapping alone to try force completion, but without success:

```vim
" VIM-PLUG {{{

" Automatic download {{{
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !mkdir -p ~/.vim/autoload
    silent !curl -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif
" }}}

call plug#begin('~/.vim/plugged')

" Plugins {{{
Plug 'tyrannicaltoucan/vim-deep-space'
Plug 'tpope/vim-sensible'
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}
" }}}

call plug#end()

" Plugin Preloading {{{
runtime! plugin/sensible.vim
" }}}

" }}}

" General {{{
let mapleader = ' '         " changes leader key
set noswapfile              " no swap files
set hidden                  " hide buffer without notice
set hlsearch                " highlight the last searched term
set virtualedit=all         " let us walk in limbo
set cpoptions+=$            " dollar sign while changing
set foldmethod=marker       " folds on marks
set nowrap                  " don't wrap lines
set clipboard=unnamedplus   " for simplified clipboard copy/paste
set noshowmode              " hide the default mode text (e.g. -- INSERT -- below the statusline)
set noshowcmd               " disable blinking command feedback in bottom-right corner
set vb t_vb=                " no visual bell
set pumheight=30            " limit popup menu height
set conceallevel=2          " hides concealed text
set expandtab tabstop=4 shiftwidth=4 softtabstop=4 " space for tabs by default
set t_ut=                   " fix 256 colors in tmux http://sunaku.github.io/vim-256color-bce.html
set spelllang=en,pt_br      " set default spelling languages
set updatetime=300          " set updatetime to shorter value
set mouse=a                 " enable mouse
set guicursor=              " disable cursor shape
set synmaxcol=250           " set max syntax highlighting column to sane level
if has('termguicolors')     " set true colors
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set termguicolors
endif
" }}}

" Colorscheme {{{
silent! colors deep-space
" }}}

inoremap <silent><expr> <c-space> coc#refresh()
```

My `coc-settings.json` is still [the same](#issuecomment-436876481). I know clangd is working because I've tried it with other plugins.

**Comment by oblitum** [comment]
I've accepted installing the suggested `coc-json` extension when I've open `:CocConfig` and it seems it's working as expected in the json file. Dunno why my C++ setup isn't working at all.

**Comment by oblitum** [comment]
Hmm, I'm getting diagnostics, but no completions when pressing `<c-space>`.

**Comment by oblitum** [comment]
Ah my bad, indeed my json was bad, I forgot to wrap it with `{}`... Thankfully the diagnostics pointed for a unexpected end-of-file, than I noticed :D
