### ISSUE TITLE
Lots of error messages periodically

### ISSUE THREAD

**Issue by yihuang** [neoclide/coc.nvim#1619]
Didn't remember what I did, but coc starts to output tons of error messages periodically,
I'm only using `coc-rls`.

```
2020-03-05T20:53:59.368 ERROR (pid:48145) [server] - uncaughtException Error: expected bser opcode 0 but got 8, in Buffer of length 1073741824 (638243144 readable) at offset 2247 buffer: {"type":"Buffer","data":[2,3,1,102,6,92,166,189,169,112,1,0,0,6,141,212,188,170,112,1,0,0,2,3,115,116,97,114,103,101,116,47]}
    at BunserBuf.raise (.../src/mynvim/bundle/coc/node_modules/fb-watchman/node_modules/bser/index.js:302:9)
    at BunserBuf.expectCode (.../src/mynvim/bundle/coc/node_modules/fb-watchman/node_modules/bser/index.js:312:10)
    at BunserBuf.process (.../src/mynvim/bundle/coc/node_modules/fb-watchman/node_modules/bser/index.js:268:10)
    at .../src/mynvim/bundle/coc/node_modules/fb-watchman/node_modules/bser/index.js:247:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by chemzqm** [comment]
Should be problem with your watchman

**Comment by yihuang** [comment]
> Should be problem with your watchman

I tried to remove coc and re-install, also removed `~/.config/coc`, is there anything else I can do?

**Comment by fannheyward** [comment]
It's watchman. How do you installed watchman? What `watchman --version`?

**Comment by yihuang** [comment]
It seems it doesn't happen again after I `brew upgrade yarn`.
