### ISSUE TITLE
specify the node version required

### ISSUE THREAD

**Issue by danielo515** [neoclide/coc.nvim#1626]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v8.15.0
coc.nvim version: 0.0.74-bcdd8cdfca
term: iTerm.app
platform: darwin

## Messages
"nvim/plugin/denite.vim" 11L, 280C written
function remote#host#UpdateRemotePlugins[6]..<SNR>195_RegistrationCommands[15]..remote#host#Require[10]..provider#node#Require[14]..provider#Poll, line 4
Vim(if):Error invoking 'poll' on channel 27:^@ch 27 was closed by the client
/Users/danielo/.nvm/versions/node/v8.15.0/lib/node_modules/neovim/node_modules/@msgpack/msgpack/dist/Decoder.js:85
        for await (const buffer of stream) {
            ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/danielo/.nvm/versions/node/v8.15.0/lib/node_modules/neovim/node_modules/@msgpack/msgpack/dist/decode.js:3:19)

function remote#host#UpdateRemotePlugins[6]..<SNR>195_RegistrationCommands[15]..remote#host#Require[10]..provider#node#Require[14]..provider#Poll, line 14
Failed to load node host. You can try to see what happened by starting nvim with $NVIM_NODE_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /Users/danielo/.local/share/nvim/rplugin.vim
## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /Users/danielo/.dotfiles
resolved root: /Users/danielo/.dotfiles
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/danielo/.dotfiles
resolved root: /Users/danielo/.dotfiles
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/danielo/.dotfiles
resolved root: /Users/danielo/.dotfiles
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/danielo/.dotfiles
> git ls-files -- nvim/plugin/coc.vim
> git --no-pager show :nvim/plugin/coc.vim
resolved root: /Users/danielo/.dotfiles
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/danielo/.dotfiles
resolved root: /Users/danielo/.dotfiles
> git symbolic-ref --short HEAD
> git ls-files -- nvim/plugin/coc.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :nvim/plugin/coc.vim
resolved root: /Users/danielo/.dotfiles
resolved root: /Users/danielo/.dotfiles
> git symbolic-ref --short HEAD
> git ls-files -- nvim/plugin/coc.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :nvim/plugin/coc.vim
resolved root: /Users/danielo/.dotfiles
resolved root: /Users/danielo/.dotfiles
> git symbolic-ref --short HEAD
> git ls-files -- nvim/plugin/coc.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :nvim/plugin/coc.vim
resolved root: /Users/danielo/.dotfiles
> git ls-files -- nvim/plugin/denite.vim
resolved root: /Users/danielo/.dotfiles
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/danielo/.dotfiles
resolved root: /Users/danielo/.dotfiles
> git symbolic-ref --short HEAD
> git ls-files -- nvim/plugin/denite.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/danielo/.dotfiles
resolved root: /Users/danielo/.dotfiles
> git symbolic-ref --short HEAD
> git ls-files -- nvim/plugin/denite.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/danielo/.dotfiles
> git ls-files -- nvim/plugin/denite.vim
resolved root: /Users/danielo/.dotfiles
resolved root: /Users/danielo/.dotfiles
> git symbolic-ref --short HEAD
> git ls-files -- nvim/plugin/denite.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/danielo/.dotfiles
> git ls-files -- nvim/plugin/denite.vim
resolved root: /Users/danielo/.dotfiles
> git ls-files -- nvim/plugin/denite.vim
resolved root: /Users/danielo/.dotfiles
resolved root: /Users/danielo/.dotfiles
> git symbolic-ref --short HEAD
> git ls-files -- nvim/plugin/denite.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/danielo/.dotfiles
> git ls-files -- nvim/plugin/denite.vim
resolved root: /Users/danielo/.dotfiles
resolved root: /Users/danielo/.dotfiles
> git symbolic-ref --short HEAD
> git ls-files -- nvim/plugin/denite.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/danielo/.dotfiles
resolved root: /Users/danielo/.dotfiles
> git symbolic-ref --short HEAD
> git ls-files -- nvim/plugin/denite.vim
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard

## Output channel: prettier


## Output channel: snippets


## Output channel: highlight

[Info  - 20:06:54] Highlight server running in node v8.15.0


```
## Describe the bug

Seems that the required node version is quite high because dependent libraries.
Just installed neovim globally (`npm i -g neovim`) denite and denite-extra, and got the above error when updating remote plugins.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：
TODO
  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by danielo515** [comment]
Upgrading to node 10 makes the problem vanish

**Comment by danielo515** [comment]
So you don't plan to update the docs right?

**Comment by fannheyward** [comment]
The wiki has been upgraded.

**Comment by danielo515** [comment]
Awesome!
