### ISSUE TITLE
[coc.nvim]Error on 'highlight': Cannot read property 'start' of null (For bash-language-server)

### ISSUE THREAD

**Issue by YasserKa** [neoclide/coc.nvim#1694]
`autocmd CursorHold * silent call CocActionAsync('highlight')`
Doesn't work well with https://github.com/bash-lsp/bash-language-server

Gif:
![2020-03-27_22:14:00](https://user-images.githubusercontent.com/16079479/77797019-01b1ba80-7079-11ea-9e4d-890d6b3e011d.gif)

:CocOpenLog
```
2020-03-27T22:20:52.180 INFO (pid:80933) [services] - service languageserver.bash started
2020-03-27T22:21:13.721 ERROR (pid:80933) [plugin] - TypeError: Cannot read property 'start' of null
    at /home/yasser/.local/share/nvim/plugged/coc.nvim/build/index.js:28791:28
    at Array.reduce (<anonymous>)
    at Document.matchAddRanges (/home/yasser/.local/share/nvim/plugged/coc.nvim/build/index.js:28790:30)
    at DocumentHighlighter.highlight (/home/yasser/.local/share/nvim/plugged/coc.nvim/build/index.js:70827:32)
    at async Handler.highlight (/home/yasser/.local/share/nvim/plugged/coc.nvim/build/index.js:69502:9)
    at async Plugin.cocAction (/home/yasser/.local/share/nvim/plugged/coc.nvim/build/index.js:35584:21)
    at async NeovimClient.<anonymous> (/home/yasser/.local/share/nvim/plugged/coc.nvim/build/index.js:10360:25)
```

I only noticed this problem with this server so far.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by YasserKa** [comment]
Correct, I tried https://github.com/autozimu/LanguageClient-neovim, and I encountered the same problem.
I thought that the client has to handle the errors that the server make at times when it doesn't make sense, but it's the server job not to make such outputs in the first place. The client doesn't have to do the heavy lifting.

**Comment by magnus-gross** [comment]
This problem also seems to only occur when using vim. When I use nvim, I cannot reproduce this.
