### ISSUE TITLE
[coc.nvim] error: TypeError: (intermediate value) is not iterable

### ISSUE THREAD

**Issue by muziqiushan** [neoclide/coc.nvim#1724]
It occurs when I call CocAction('jumpDefinition') or CocAction('jumpReference'), and switch between the  candidate list；

![image](https://user-images.githubusercontent.com/3956434/78620112-b20d9300-78b1-11ea-98e9-941dd25ebc7b.png)

**Comment by fannheyward** [comment]
What's your `:ConInfo` and `:CocOpenLog`?

**Comment by chemzqm** [comment]
Try upgrade to latest coc.nvim.

**Comment by diegosomar** [comment]
I have the same issue here. Perhaps, my info can clarify the error:

**:CocOpenLog**

```
2020-04-15T19:48:05.528 INFO (pid:58612) [plugin] - coc 0.0.78-8e132d7a1b initialized with node: v12.16.2
2020-04-15T19:48:17.409 INFO (pid:58612) [language-client-index] - phpls started with 58918
2020-04-15T19:48:36.650 ERROR (pid:58612) [events] - Handler Error on BufCreate Error: Timeout handler of "BufCreate" after: 2000ms
    at Timeout._onTimeout (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:15339:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
2020-04-15T19:48:36.651 ERROR (pid:58612) [events] - Handler Error on BufEnter Error: Timeout handler of "BufEnter" after: 2000ms
    at Timeout._onTimeout (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:15339:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
2020-04-15T19:48:36.672 ERROR (pid:58612) [events] - Handler Error on BufEnter Error: Timeout handler of "BufEnter" after: 2000ms
    at Timeout._onTimeout (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:15339:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
2020-04-15T19:48:36.672 ERROR (pid:58612) [events] - Handler Error on CursorMoved Error: Timeout handler of "CursorMoved" after: 2000ms
    at Timeout._onTimeout (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:15339:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

```

**:CocInfo**

```
## versions

vim version: NVIM v0.4.3
node version: v12.16.2
coc.nvim version: 0.0.78-8e132d7a1b
term: iTerm.app
platform: darwin

## Output channel: phpls

[Info  - 19:48:17] Initialising intelephense 1.3.11
[Info  - 19:48:17] Reading state from /Users/vimuser/.config/coc/extensions/coc-phpls-data/4a224cdd.
[Info  - 19:48:19] Initialised in 1107 ms
```
This error not happens always. I tried to create a minimal file to reproduce, but I can't.

In my Wordpress project, I have this line:

`get_the_excerpt( $post )`

After positioning cursor in the function `get_the_excerpt` and type `gd`, I got this error:

```
[coc.nvim] error: TypeError: (intermediate value) is not iterable
    at LocationList.previewLocation (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:63975:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.execute (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:63806:17)
    at async ListManager.doItemAction (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:59379:21)
    at async ListManager.doAction (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:58850:13)
    at async /Users/vimuser/.vim/plugged/coc.nvim/build/index.js:58734:17
```

After press any key, the error message is gone and the files which has this function declared are listed. When I try to choose a file, after few seconds, the error is shown again.

In this case, I have 2 files with the same function declared, because I the main project folder, I have 2 Wordpress instalations. I tried to create a small implementation, with the same function name declared in 2 different files, but works fine.

See my [init.vim](https://gist.github.com/diegosomar/bd2b4e626d4066526222fc8f71a83bee) file.

**Comment by chemzqm** [comment]
Try upgrade your coc.nvim.

**Comment by diegosomar** [comment]
Hello @chemzqm, tks your answer. I'm using latest release version, `0.0.78-8e132d7a1b`.
There's a branch or other way to get another version? I can test.

**Comment by chemzqm** [comment]
Try upgrade your coc.nvim to latest release branch.

**Comment by diegosomar** [comment]
In my init.vim:
`Plug 'neoclide/coc.nvim', {'branch': 'release'}`

I run `:PlugUpdate` and I got `Already up to date.`

Navigating to `~/.vim/plugged/coc.nvim`, in branch `release`, I run `git pull origin release` and I got:
```
 * branch            release    -> FETCH_HEAD
Already up to date.
```

To force download, I run `git pull origin release --force` and I got:
```
From https://github.com/neoclide/coc.nvim
 * branch            release    -> FETCH_HEAD
   ce8ab24..64b63ed  release    -> origin/release
Updating ce8ab24..64b63ed
Fast-forward
 autoload/coc/util.vim |  3 ---
 build/index.js        | 38 ++++++++++++++++++--------------------
 2 files changed, 18 insertions(+), 23 deletions(-)
```

After that, I go to nvim again and run `:CocRestart`. I'm going to the same file and type `gd` and have error again:

**Error after gd**
```
[coc.nvim] error: TypeError: (intermediate value) is not iterable
    at LocationList.previewLocation (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:63999:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.execute (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:63830:17)
    at async ListManager.doItemAction (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:59403:21)
    at async ListManager.doAction (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:58874:13)
    at async /Users/vimuser/.vim/plugged/coc.nvim/build/index.js:58764:13
```

**:CocOpenLog**
```
2020-04-16T09:35:57.332 INFO (pid:37779) [plugin] - coc 0.0.78-312c7c4482 initialized with node: v12.16.2
2020-04-16T09:36:06.909 INFO (pid:37779) [language-client-index] - phpls started with 38085
2020-04-16T09:36:11.246 WARN (pid:37779) [events] - Handler of BufCreate cost more than 1s async onBufCreate(buf) {
        let buffer = typeof buf === 'number' ? this.nvim.createBuffer(buf) : buf;
        let bufnr = buffer.id;
        if (this.creatingSources.has(bufnr))
            return;
        let document = this.getDocument(bufnr);
        let source = new vscode_languageserver_protocol_1.CancellationTokenSource();
        try {
            if (document)
                this.onBufUnload(bufnr, true).logError();
            document = new document_1.default(buffer, this._env, this.maxFileSize);
            let token = source.token;
            this.creatingSources.set(bufnr, source);
            let created = await document.init(this.nvim, token);
            if (!created)
                document = null;
        }
        catch (e) {
            logger.error('Error on create buffer:', e);
            document = null;
        }
        if (this.creatingSources.get(bufnr) == source) {
            source.dispose();
            this.creatingSources.delete(bufnr);
        }
        if (!document || !document.textDocument)
            return;
        this.buffers.set(bufnr, document);
        if (document.enabled) {
            document.onDocumentDetach(uri => {
                let doc = this.getDocument(uri);
                if (doc)
                    this.onBufUnload(doc.bufnr).logError();
            });
        }
        if (document.buftype == '' && document.schema == 'file') {
            let config = this.getConfiguration('workspace');
            let filetypes = config.get('ignoredFiletypes', []);
            if (filetypes.indexOf(document.filetype) == -1) {
                let root = this.resolveRoot(document);
                if (root) {
                    this.addWorkspaceFolder(root);
                    if (this.bufnr == buffer.id) {
                        this._root = root;
                    }
                }
            }
            this.configurations.checkFolderConfiguration(document.uri);
        }
        if (document.enabled) {
            this._onDidOpenDocument.fire(document.textDocument);
            document.onDocumentChange(e => this._onDidChangeDocument.fire(e));
        }
        logger.debug('buffer created', buffer.id);
    }
2020-04-16T09:36:11.248 WARN (pid:37779) [events] - Handler of BufEnter cost more than 1s async () => {
            if (this.timer)
                clearTimeout(this.timer);
            if (!this.enabled || !this.config.locationlist)
                return;
            let doc = await workspace_1.default.document;
            if (!doc || doc.buftype == 'quickfix')
                return;
            if (this.shouldValidate(doc)) {
                let refreshed = this.refreshBuffer(doc.uri);
                if (refreshed)
                    return;
            }
            let curr = await nvim.eval(`getloclist(win_getid(),{'title':1})`);
            if (curr.title && curr.title.indexOf('Diagnostics of coc') != -1) {
                await nvim.eval(`setloclist(win_getid(),[],'f')`);
            }
        }
2020-04-16T09:36:11.275 WARN (pid:37779) [events] - Handler of BufEnter cost more than 1s async () => {
            if (this.timer)
                clearTimeout(this.timer);
            if (!this.enabled || !this.config.locationlist)
                return;
            let doc = await workspace_1.default.document;
            if (!doc || doc.buftype == 'quickfix')
                return;
            if (this.shouldValidate(doc)) {
                let refreshed = this.refreshBuffer(doc.uri);
                if (refreshed)
                    return;
            }
            let curr = await nvim.eval(`getloclist(win_getid(),{'title':1})`);
            if (curr.title && curr.title.indexOf('Diagnostics of coc') != -1) {
                await nvim.eval(`setloclist(win_getid(),[],'f')`);
            }
        }
2020-04-16T09:36:11.275 WARN (pid:37779) [events] - Handler of CursorMoved cost more than 1s function(){
    context = this;
    args = arguments;
    timestamp = Date.now();
    var callNow = immediate && !timeout;
    if (!timeout) timeout = setTimeout(later, wait);
    if (callNow) {
      result = func.apply(context, args);
      context = args = null;
    }

    return result;
  }
```
**:CocInfo**
```
## versions

vim version: NVIM v0.4.3
node version: v12.16.2
coc.nvim version: 0.0.78-312c7c4482
term: iTerm.app
platform: darwin

## Output channel: snippets

[Info 09:35:57] Using ultisnips directories: UltiSnips /Users/vimuser/.dotfiles/ultisnips/snippets /Users/vimuser/.config/coc/ultisnips
[Info 09:35:57] Using ultisnips python command: pyx

## Output channel: phpls

[Info  - 09:36:07] Initialising intelephense 1.3.11
[Info  - 09:36:07] Reading state from /Users/vimuser/.config/coc/extensions/coc-phpls-data/4a224cdd.
[Info  - 09:36:08] Initialised in 1285 ms
```

**Comment by chemzqm** [comment]
It's fixed after `0.0.78-8e132d7a1b`

**Comment by diegosomar** [comment]
My new version: `coc.nvim version: 0.0.78-ea5787c525` . CocRestarted. Unfortunately, the problem remains.

**After type gd in the same function**

```
[coc.nvim] error: TypeError: (intermediate value) is not iterable
    at LocationList.previewLocation (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:63980:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.execute (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:63811:17)
    at async ListManager.doItemAction (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:59387:21)
    at async ListManager.doAction (/Users/vimuser/.vim/plugged/coc.nvim/build/index.js:58866:13)
    at async /Users/vimuser/.vim/plugged/coc.nvim/build/index.js:58759:13
```

**Comment by diegosomar** [comment]
@chemzqm Tks the fix! I runned `:PlugUpdate` and now I have `coc.nvim version: 0.0.78-237b0eb0f7` and `gd` in that functions works fine! Tk you again!
