### ISSUE TITLE
Using coc-prettier with pnpm throws error

### ISSUE THREAD

**Issue by mhmdanas** [neoclide/coc.nvim#1774]
## Result from CocInfo

```
2020-04-16T17:57:21.641 INFO (pid:14205) [services] - registered service "languageserver.purescript"
2020-04-16T17:57:21.644 INFO (pid:14205) [model-extension] - Using npm from: /Users/mhmdanas/.nvm/versions/node/v12.16.1/bin/pnpm
2020-04-16T17:57:21.644 INFO (pid:14205) [model-extension] - Loading info of coc-prettier.
2020-04-16T17:57:21.647 INFO (pid:14205) [model-fetch] - fetch: https://registry.npmjs.org/coc-prettier
2020-04-16T17:57:21.666 INFO (pid:14205) [plugin] - coc 0.0.78-fc983ce6dd initialized with node: v12.16.1
2020-04-16T17:57:22.358 INFO (pid:14205) [model-extension] - Downloading from https://registry.npmjs.org/coc-prettier/-/coc-prettier-1.1.12.tgz
2020-04-16T17:57:23.289 INFO (pid:14205) [model-extension] - Installing dependencies.
2020-04-16T17:57:23.973 INFO (pid:14205) [model-extension] - Moving to new folder.
2020-04-16T17:57:23.978 INFO (pid:14205) [model-extension] - Installed extension: coc-prettier
2020-04-16T17:57:23.993 ERROR (pid:14205) [extensions] - Error: Cannot find module 'prettier'
Require stack:
- /Users/mhmdanas/.config/coc/extensions/node_modules/coc-prettier/lib/index.js
- /Users/mhmdanas/.config/coc/extensions/node_modules/coc-prettier/lib/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at req (/Users/mhmdanas/.config/nvim/plugged/coc.nvim/build/index.js:50881:21)
    at Object.<anonymous> (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:5363:18)
    at __webpack_require__ (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:20:30)
    at Object.<anonymous> (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:5331:18)
    at __webpack_require__ (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:20:30)
    at Object.<anonymous> (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:97:54)
    at __webpack_require__ (/Users/mhmdanas/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:20:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mhmdanas/.config/coc/extensions/node_modules/coc-prettier/lib/index.js',
    '/Users/mhmdanas/.config/coc/extensions/node_modules/coc-prettier/lib/index.js'
  ]
}
```

## Describe the bug

I know that it says in the documentation that `npm.binPath` is for Yarn and npm only. However, I tried to make it work with pnpm. But it turned out that this causes issues with coc-prettier. Actually, I examined this a little, and it turns out that pnpm doesn't install any dependencies of the extensions. Running `pnpm i` inside the extensions folder fixes this issue.

I also tried removing the `--no-bin-links` option from this line and it fixed this issue on my machine: https://github.com/neoclide/coc.nvim/blob/012aef188d44f71f88d77f0292330255db5d1247/src/model/extension.ts#L86
However, it is probably there for a reason, so it might not be the correct solution.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Install pnpm (https://pnpm.js.org/en/installation)

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Run `:CocConfig` and add this line:
  ```json
  "npm.binPath": "PNPM_PATH"
  ```
  where `PNPM_PATH` is the output of `which pnpm` on Un*x and `where pnpm` on Windows

- Run `:CocInstall coc-prettier` and wait for it to finish

- Error appears at the bottom

**Comment by mhmdanas** [comment]
I think pnpm doesn't generate `node_modules` with the `--no-bin-links` option because it generates a hard link for each dependency.
