### ISSUE TITLE
[coc.nvim] Error: request error nvim_call_function - ERROR

### ISSUE THREAD

**Issue by mechanicles** [neoclide/coc.nvim#1789]
Suddenly after upgrading my plugins using `PlugUpdate`, I started to get this error

```
[coc.nvim] Error: request error nvim_call_function - ERROR
```

**CocInfo output:**

```
## versions

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  3 2020 21:29:07)
node version: v8.15.1
coc.nvim version: 0.0.78-70aac81740
term: iTerm.app
platform: darwin

## Output channel: explorer

Error: request error nvim_call_function - ERROR
    at transport.request (/Users/santosh/dotfiles/vim/plugged/coc.nvim/build/index.js:14273:32)
    at request_1.default (/Users/santosh/dotfiles/vim/plugged/coc.nvim/build/index.js:14729:13)
    at Request.callback (/Users/santosh/dotfiles/vim/plugged/coc.nvim/build/index.js:14897:20)
    at Connection.connection.on (/Users/santosh/dotfiles/vim/plugged/coc.nvim/build/index.js:14703:21)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Connection.parseData (/Users/santosh/dotfiles/vim/plugged/coc.nvim/build/index.js:14823:18)
    at Interface.Connection.rl.on (/Users/santosh/dotfiles/vim/plugged/coc.nvim/build/index.js:14793:18)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)

## Output channel: snippets

[Info 22:57:53] Using ultisnips directories: UltiSnips /Users/santosh/.config/coc/ultisnips
[Info 22:57:53] Using ultisnips python command: pyx
[Error 22:57:53] Convert regex error for: li(st)? (?<num>\d+)$
[Error 22:57:53] Convert regex error for: ol(st)? (?<num>\d+)$
```

<img width="644" alt="issue" src="https://user-images.githubusercontent.com/77895/79644950-d75fa280-81c9-11ea-8818-461cf035f1d6.png">

**Comment by mechanicles** [comment]
@chemzqm Hi, could you tell me what kind of error is this? I mean you might know when this error gets triggered. And according to it, I can modify my settings/plugins.

**Comment by chemzqm** [comment]
We need debug log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc.
* Restart your vim/neovim to make the issue happen.
* Open the log file by command `:call coc#client#open_log()`.
* Attach the log file or paste content from the log.

**Comment by mechanicles** [comment]
@chemzqm I just followed your steps. Added that line `let g:node_client_debug = 1` in my vimrc file. Restarted my mvim and called that command `call coc#client#open_log()` but nothing has appeared as a log. Please check following image,

<img width="957" alt="log" src="https://user-images.githubusercontent.com/77895/79689203-e2b9d900-8270-11ea-99ae-6294e1b317d6.png">

Also, I noticed that when I enter/go into Nerdtree window, then that error `[coc.nvim] Error: request error nvim_call_function - ERROR` gets appeared but not sure if Nerdtree is causing an issue. I will let you know.

**Comment by chemzqm** [comment]
Please upgrade to the latest release branch of coc.nvim.

**Comment by mechanicles** [comment]
Just upgraded and restarted my mvim (also followed your steps) but still the same error I get.

**Comment by mechanicles** [comment]
I also disabled my nerdtree plugin and disabled all its settings. Restarted my mvim but I get the same error too when I try to type code snippet related stuff.

**Comment by mechanicles** [comment]
@chemzqm After upgrading `coc.vim` plugin, I no longer getting this issue. Looks like in recent version, this issue might got fixed. Closing this issue for now. Thanks.

**Comment by ccppvv** [comment]
I'm sorry, but i came across almost the same problem again just a few days ago, except that my error is like below:

**Comment by ccppvv** [comment]
Update:

**Comment by chemzqm** [comment]
@ccppvv It was fixed with coc-yank, use latest coc.nvim also helps.

**Comment by data-stepper** [comment]
I am also getting this error. Below is the exact output of `:CocOpenLog` regarding the error:

```
2021-09-19T17:40:55.718 ERROR (pid:15682) [node-client] - request error on "nvim_call_function" [ 'coc#util#echo_line', [] ] Vim:E117: Unknown function: coc#util#echo_line Error
    at wF.request (/home/<my username>/.config/nvim/plugged/coc.nvim/build/index.js:30:34430)
    at wF.call (/home/<my username>/.config/nvim/plugged/coc.nvim/build/index.js:33:3671)
    at Timeout._onTimeout (/home/<my username>/.config/coc/extensions/node_modules/coc-python/lib/index.js:123358:39)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by eomiso** [comment]
I have upgraded the coc.nvim two days ago and I've been getting the same error since then. 
Is it possible there might have been a bug in the latest update?

```
2021-09-22T15:07:33.310 ERROR (pid:24230) [node-client] - request error on "nvim_call_function" [
  'coc#float#create_cursor_float',
  [
    0,
    0,
    [ "[sourcekitd] [E] cannot find 'slkfdjwielfj' in scope" ],
    {
      pumAlignTop: false,
      preferTop: false,
      offsetX: 0,
      title: '',
      close: 0,
      codes: [Array],
      highlights: [],
      modes: [Array],
      maxWidth: 80,
      autohide: 1
    }
  ]
] Vim(let):E5555: API call: Invalid key 'zindex' Error
    at wF.request (/Users/eomiso/.local/share/nvim/plugged/coc.nvim/build/index.js:30:34430)
    at wF.call (/Users/eomiso/.local/share/nvim/plugged/coc.nvim/build/index.js:33:3671)
    at tr.createPopup (/Users/eomiso/.local/share/nvim/plugged/coc.nvim/build/index.js:146:3515)
    at tr.show (/Users/eomiso/.local/share/nvim/plugged/coc.nvim/build/index.js:146:2644)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sU.echoMessage (/Users/eomiso/.local/share/nvim/plugged/coc.nvim/build/index.js:193:15141)
    at async Timeout.<anonymous> (/Users/eomiso/.local/share/nvim/plugged/coc.nvim/build/index.js:193:8423)
2021-09-22T15:07:33.311 ERROR (pid:24230) [node-client] - request error nvim_call_function - Vim(let):E5555: API call: Invalid key 'zindex' Error
    at wF.request (/Users/eomiso/.local/share/nvim/plugged/coc.nvim/build/index.js:30:34430)
    at wF.call (/Users/eomiso/.local/share/nvim/plugged/coc.nvim/build/index.js:33:3671)
    at tr.createPopup (/Users/eomiso/.local/share/nvim/plugged/coc.nvim/build/index.js:146:3515)
    at tr.show (/Users/eomiso/.local/share/nvim/plugged/coc.nvim/build/index.js:146:2644)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async sU.echoMessage (/Users/eomiso/.local/share/nvim/plugged/coc.nvim/build/index.js:193:15141)
    at async Timeout.<anonymous> (/Users/eomiso/.local/share/nvim/plugged/coc.nvim/build/index.js:193:8423)
```

**Comment by fannheyward** [comment]
@eomiso check https://github.com/neoclide/coc.nvim/issues/3380 and https://github.com/neoclide/coc.nvim/commit/2fb58dc009d020bf441788ebc9dc1bd21cdb73cc#commitcomment-56403511, make sure you're using nvim 0.5.0 stable release, 0.5.0-dev will have this issue.

**Comment by fannheyward** [comment]
@data-stepper you're using coc-python, which has be deprecated, try coc-pyright or coc-jedi, https://github.com/neoclide/coc-python#coc-python

**Comment by eomiso** [comment]
I'm using coc-python although it is depricated because of some of the features that are not included in other python coc extensions. Hope this be another useful info for @data-stepper.

I just removed the nvim and downloaded the stable release. It seems to be working fine after that.

This problem started after I upgraded my pluggins with :PlugUpdate. And I believe @fannheyward is right. I may have been using the dev version.
Or, I've been mingling with my nvim a lot lately and I could have nicked something. Hope this would work out for someone else as well.

**Comment by data-stepper** [comment]
Because of this error I switched from coc-python to coc-jedi (which is also pretty great btw). But coc-jedi seems to know less docstrings of imported modules (like tensorflow) which I really enjoyed.

If coc-python is working fine under a release other than mine, could you please explain more in depth how you got it working?

Is it just deleting all of nvim and installing everything from scratch?

**Comment by fannheyward** [comment]
@data-stepper you can use coc-python by building from source.

1. fork coc-python
2. delete the lines https://github.com/neoclide/coc-python/blob/master/src/formatters/baseFormatter.ts#L80-L84
3. install with vim-plug `Plug 'YOUR_GITHUB_NAME/coc-python', {'do': 'yarn install --frozen-lockfile'}`
4. or build in your local, and add `set runtimepath^=~/src/coc-python` in your vimrc.

**Comment by eomiso** [comment]
@data-stepper I didn't have to remove the plugins I installed. I just removed the nvim binary file that I've been using. And downloaded the release version 0.5.0. 
Just adding the path did the job since my init.vim and vim-plugins were still there on my computer.
BTW, coc-python I'm using was installed with :CocInstall command(this uses the yarn package manager I guess...?) Although it is deprecated, seems to be working fine for me.( I've been using coc-python for exactly the same reason as yours. Alternatives just don't suffice)

**Comment by orifmilod** [comment]
In my case there were some issues with `zindex` and simple search with `grep -R zindex . `pointed to `./.vim/plugged/coc.nvim/autoload/coc/float.vim` file. I commented out all the entries with `zindex` i.e. ` let config['zindex'] = 300` and it worked just fine. Hope that helps

**Comment by hesxenon** [comment]
had the same problem just now, did what @orifmilod did and it works again. Seems to be this setting of zindex
```
coc.nvim/autoload/coc/float.vim#322
```
```
## CocInfo
## versions

vim version: NVIM v0.5.0-ef3230f
node version: v16.10.0
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /home/hesxenon/.config/nvim/plugged/coc.nvim
term: termite
platform: linux

## Log of coc.nvim

2021-11-11T13:06:55.090 INFO (pid:235929) [services] - registered service "languageserver.rescript"
2021-11-11T13:06:55.258 INFO (pid:235929) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v16.10.0 after 236ms
2021-11-11T13:06:55.614 INFO (pid:235929) [services] - registered service "tsserver"
2021-11-11T13:06:57.412 INFO (pid:235929) [attach] - Request action: doHover []
2021-11-11T13:07:00.412 ERROR (pid:235929) [attach] - Request cost more than 3s doHover []
2021-11-11T13:07:00.836 ERROR (pid:235929) [node-client] - request error on "nvim_call_function" [
  'coc#float#create_cursor_float',
  [
    0,
    0,
    [ 'const storybookUrl: "http://localhost:6006"' ],
    {
      pumAlignTop: false,
      preferTop: false,
      offsetX: 0,
      title: '',
      close: 0,
      codes: [Array],
      highlights: [],
      modes: [Array],
      maxWidth: 80,
      autohide: 1
    }
  ]
] Vim(let):E5555: API call: Invalid key 'zindex' Error
    at wF.request (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:30:34430)
    at wF.call (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:33:3671)
    at tr.createPopup (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:146:3515)
    at tr.show (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:146:2644)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async mw.previewHover (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:254:636)
    at async mw.onHover (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:253:1115)
    at async Aw.cocAction (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:263:55784)
    at async wF.<anonymous> (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:263:57923)
2021-11-11T13:07:00.837 ERROR (pid:235929) [node-client] - request error nvim_call_function - Vim(let):E5555: API call: Invalid key 'zindex' Error
    at wF.request (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:30:34430)
    at wF.call (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:33:3671)
    at tr.createPopup (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:146:3515)
    at tr.show (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:146:2644)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async mw.previewHover (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:254:636)
    at async mw.onHover (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:253:1115)
    at async Aw.cocAction (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:263:55784)
    at async wF.<anonymous> (/home/hesxenon/.config/nvim/plugged/coc.nvim/build/index.js:263:57923)
2021-11-11T13:07:00.837 WARN (pid:235929) [plugin] - Slow action "doHover" cost 3425ms
2021-11-11T13:07:06.509 INFO (pid:235929) [attach] - receive notification: showInfo []
```

**Comment by quincyhill** [comment]
I switched from using an older nightly build from the AUR to the maniline 0.5.1 release build and that solved this issue. Goodluck
