### ISSUE TITLE
coc.nvim fails to start on master

### ISSUE THREAD

**Issue by kmoschcau** [neoclide/coc.nvim#1814]
## Result from CocInfo

Not possible, because coc does not start and produces the same error on running `:CocStart`.

## Describe the bug

Whenever I try to start coc, I get this error message:
```
[coc.nvim] error: internal/modules/cjs/loader.js:488                                                                                                                                                                                  
    throw e;
    ^
Error: Package exports for '/home/kmoschcau/.local/share/nvim/plugged/coc.nvim/node_modules/clipboardy' do not define a '.' subpath
    at applyExports (internal/modules/cjs/loader.js:485:15)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/kmoschcau/.local/share/nvim/plugged/coc.nvim/lib/list/prompt.js:6:46)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10) {
  code: 'MODULE_NOT_FOUND'
}

```

## Reproduce the bug

Run neovim with the provided minimal vimrc and you will get the error right at startup.
  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

## Additional remarks

~~This was tried on the master branch. I can not get either the newest tag or the release branch to compile, because both are missing a `tsconfig.json`.~~

**Comment by fannheyward** [comment]
`release` branch doesn't need to compile, it's already compiled.

**Comment by kmoschcau** [comment]
@fannheyward I either completely missed that in my head or did not read it in the readme. That's on me. The actual error is still there, though since I now have an alternative it does not really concern me anymore. If you can't reproduce it and nobody else seems affected by it, feel free to close this issue.

**Comment by chemzqm** [comment]
Use `yarn install` to install dependencies and build the file.
