### ISSUE TITLE
Can't open file on top of terminal buffer

### ISSUE THREAD

**Issue by TSFoster** [neoclide/coc.nvim#1825]
## versions

vim version: NVIM v0.4.3
node version: v14.0.0
coc.nvim version: 0.0.78-9febe802b3
term: iTerm.app
platform: darwin

## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /
fatal: not a git repository (or any of the parent directories): .git

## Output channel: snippets

[Info 16:27:53] Using ultisnips directories: UltiSnips /Users/toby/.config/coc/ultisnips
[Info 16:27:54] Using ultisnips python command: pyx

## Output channel: highlight

[Info  - 16:27:54] Highlight server running in node v14.0.0

## Describe the bug

I have a `BufEnter` autocmd for terminal buffers, to keep them in insert mode. It means that I can't action a CocList when a terminal buffer is the active buffer. This is the error I get:

```
[coc.nvim] error: Error: request error nvim_command - Vim(normal):Can't re-enter normal mode from terminal mode
    at /path/to/coc.nvim/build/index.js:14273:32
    at /path/to/coc.nvim/build/index.js:10919:13
    at NvimTransport.parseMessage (/path/to/coc.nvim/build/index.js:10860:17)
    at DecodeStream.<anonymous> (/path/to/coc.nvim/build/index.js:10830:18)
    at DecodeStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at DecodeStream.Readable.push (_stream_readable.js:213:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (/path/to/coc.nvim/build/index.js:13797:12)
```

There is a long discussion about this on neovim/neovim#4895, where people mention having similar problems with fzf. I don't know if it is relevant to this issue or not, sorry.

## Reproduce the bug

- Create file `mini.vim` with：
  
  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  
  augroup terminal_insert
    autocmd!
    autocmd BufEnter * if &buftype == 'terminal' && line('$') == line('w$') | :startinsert | endif
  augroup END
  ```
- Start neovim with command: `nvim -u mini.vim`
- `:term<CR>`
- `<C-\><C-n>`
- `:CocList files<CR>`
- Choose file, then `<CR>`

**Comment by TSFoster** [comment]
Amazing, thank you!
