### ISSUE TITLE
socketserver: errors when parsing coc-settings.json

### ISSUE THREAD

**Issue by DoctorApparatus** [neoclide/coc.nvim#1859]
Getting following error on startup of vim with this config:

removing the socket server segment results in no error again

[coc.nvim] error: Error on initialize: TypeError: Cannot read property 'forEach' of undefined
    at getDocumentSelector (/home/doctorapparatus/.vim/plugged/coc.nvim/build/index.js:54132:15)
    at ServiceManager.registLanguageClient (/home/doctorapparatus/.vim/plugged/coc.nvim/build/index.js:53948:50)
    at ServiceManager.createCustomServices (/home/doctorapparatus/.vim/plugged/coc.nvim/build/index.js:53867:18)
    at ServiceManager.init (/home/doctorapparatus/.vim/plugged/coc.nvim/build/index.js:53749:14)
    at Plugin.init (/home/doctorapparatus/.vim/plugged/coc.nvim/build/index.js:22355:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/doctorapparatus/.vim/plugged/coc.nvim/build/index.js:10398:13

{
        "languageserver": {
                "clangd": {
                        "command": "clangd",
                        "rootPatterns": ["compile_flags.txt", "compile_commands.json"],
                        "filetypes": ["c", "cpp", "objc", "objcpp"]
                },
                "bash": {
                        "command": "bash-language-server",
                        "args": ["start"],
                        "filetypes": ["sh,bash"],
                        "ignoredRootPaths": ["~"]
                },
                "socketserver": {
                        "host": "127.0.0.1",
                        "port": 8888
                }
        }
}

**Comment by chemzqm** [comment]
filetypes field needed
