### ISSUE TITLE
error: Error on initialize: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by jsholmes** [neoclide/coc.nvim#1861]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-dev
node version: v14.1.0
coc.nvim version: 0.0.78-57637bb44c
term: screen-256color
platform: linux

```

## Describe the bug

When I try to disable ccls in my user conf I get the following error:

```
[coc.nvim] error: Error on initialize: TypeError: Cannot read property 'forEach' of undefined
    at getDocumentSelector (/mnt/harmonix_vol2/soporifix_vol3/user/home/john/.dotfiles/vim/linux_plugins/coc.nvim/build/index.js:55555:15)
    at ServiceManager.registLanguageClient (/mnt/harmonix_vol2/soporifix_vol3/user/home/john/.dotfiles/vim/linux_plugins/coc.nvim/build/index.js:55372:50)
    at ServiceManager.createCustomServices (/mnt/harmonix_vol2/soporifix_vol3/user/home/john/.dotfiles/vim/linux_plugins/coc.nvim/build/index.js:55291:18)
    at ServiceManager.init (/mnt/harmonix_vol2/soporifix_vol3/user/home/john/.dotfiles/vim/linux_plugins/coc.nvim/build/index.js:55173:14)
    at Plugin.init (/mnt/harmonix_vol2/soporifix_vol3/user/home/john/.dotfiles/vim/linux_plugins/coc.nvim/build/index.js:22306:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NeovimClient.<anonymous> (/mnt/harmonix_vol2/soporifix_vol3/user/home/john/.dotfiles/vim/linux_plugins/coc.nvim/build/index.js:10365:21)
```

## Reproduce the bug

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

```
❯ cat /home/john/.config/nvim/coc-settings.json
{
    "languageserver": {
        "ccls": {
            "enable": false
        }
    },
}
```

**Comment by chemzqm** [comment]
Please follow wiki for configuration

**Comment by jsholmes** [comment]
can you be a bit clearer?  the problem I have here is that my workspace coc-settings.json enables ccls.  So I need to disable it in order to use clangd.

**Comment by jsholmes** [comment]
Figured out what this needs (a list of filetypes):

```
{
    "languageserver": {
        "ccls": {
            "enable": false,
            "filetypes": ["c"]
        }
    }
}
```

Note that this is not very well spelled out in the wiki.  @chemzqm I'd suggest you fix the software to display a useful diagnostic / suggestion message rather than a callstack.

**Comment by chemzqm** [comment]
There used to be but could be removed by accident.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
