### ISSUE TITLE
UnhandledRejection: diagnostic.message.split is not a function

### ISSUE THREAD

**Issue by frm** [neoclide/coc.nvim#1913]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-nightly
node version: v10.16.0
coc.nvim version: 0.0.78-5af5a806e2
term: iTerm.app
platform: darwin

## Output channel: languageserver.elixir

Started ElixirLS
Elixir version: "1.10.2 (compiled with Erlang/OTP 22)"
Erlang version: "22"

20:26:38.721 [warn]  Did not receive workspace/didChangeConfiguration notification after 5 seconds. Using default settings.
Compiling with Mix env test
[Info  - 8:26:41 PM] Compile took 551 milliseconds
[Info  - 8:26:41 PM] [ElixirLS Dialyzer] Checking for stale beam files
[Warn  - 8:26:44 PM] warning: Map.drop/2 with an Enumerable of keys that is not a list is deprecated.  Use a list of keys instead.
  (elixir 1.10.2) lib/map.ex:713: Map.drop/2
  (language_server 0.2.24) lib/language_server/dialyzer.ex:319: anonymous fn/7 in ElixirLS.LanguageServer.Dialyzer.compile/2
  (stdlib 3.11.2) timer.erl:166: :timer.tc/1
  (language_server 0.2.24) lib/language_server/dialyzer.ex:294: ElixirLS.LanguageServer.Dialyzer.compile/2

[Info  - 8:26:44 PM] [ElixirLS Dialyzer] Analyzing 0 modules: []
[Info  - 8:26:44 PM] [ElixirLS Dialyzer] Analysis finished in 37 milliseconds
[Info  - 8:26:44 PM] Dialyzer analysis is up to date
[Info  - 8:26:44 PM] [ElixirLS Dialyzer] Writing manifest...
[Info  - 8:26:48 PM] [ElixirLS Dialyzer] Done writing manifest.

```

## Describe the bug

I occasionally a split with the following error:

```
[coc.nvim] error: UnhandledRejection: diagnostic.message.split is not a function
TypeError: diagnostic.message.split is not a function
    at Object.getLocationListItem (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69551:34)
    at DiagnosticBuffer.setLocationlist (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69239:31)
    at sequence.addFunction (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69210:18)
    at promise.Promise (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69450:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is only using `elixir-ls` and, so far, the first time the error occurs is in the following conditions:

1. Create module A and save the file.
2. Create module B that uses functions from A and save the file.
3. Change A so that the used functions in B have a different name. Save the file again.

When the error is detected upon the save of A, the error split pops up. Afterwards it occurs every second.

Output from `:CocOpenLog`

```
2020-05-13T21:10:02.368 INFO (pid:24655) [services] - registered service "languageserver.elixir"
2020-05-13T21:10:02.372 INFO (pid:24655) [plugin] - coc 0.0.78-5af5a806e2 initialized with node: v10.16.0
2020-05-13T21:10:04.319 INFO (pid:24655) [services] - elixir state change: stopped => starting
2020-05-13T21:10:04.333 INFO (pid:24655) [language-client-index] - Language server "languageserver.elixir" started with 25052
2020-05-13T21:10:05.234 INFO (pid:24655) [services] - elixir state change: starting => running
2020-05-13T21:10:05.244 INFO (pid:24655) [services] - service languageserver.elixir started
2020-05-13T21:10:10.167 INFO (pid:24655) [willSaveHandler] - Will save cost: 20
2020-05-13T21:10:28.033 INFO (pid:24655) [willSaveHandler] - Will save cost: 44
# ...
# ...
# ...
2020-05-13T21:24:05.333 INFO (pid:24655) [completion-complete] - Results from: around,buffer
2020-05-13T21:24:13.139 INFO (pid:24655) [completion-complete] - Results from: around,buffer
2020-05-13T21:24:14.443 INFO (pid:24655) [completion-complete] - Results from: around,buffer
2020-05-13T21:24:18.018 INFO (pid:24655) [completion-complete] - Results from: around,buffer
2020-05-13T21:24:19.019 INFO (pid:24655) [willSaveHandler] - Will save cost: 8
2020-05-13T21:24:19.769 ERROR (pid:24655) [diagnostic-buffer] - TypeError: diagnostic.message.split is not a function
    at Object.getLocationListItem (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69551:34)
    at DiagnosticBuffer.setLocationlist (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69239:31)
    at sequence.addFunction (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69210:18)
    at promise.Promise (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69450:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-13T21:24:22.708 INFO (pid:24655) [willSaveHandler] - Will save cost: 9
2020-05-13T21:24:25.732 INFO (pid:24655) [completion-complete] - Results from: around,buffer,languageserver.elixir
2020-05-13T21:24:26.471 ERROR (pid:24655) [server] - unhandledRejection  Promise {
  <rejected> TypeError: diagnostic.message.split is not a function
      at Object.getLocationListItem (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69551:34)
      at DiagnosticBuffer.setLocationlist (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69239:31)
      at sequence.addFunction (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69210:18)
      at promise.Promise (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69450:56)
      at process._tickCallback (internal/process/next_tick.js:68:7) } TypeError: diagnostic.message.split is not a function
    at Object.getLocationListItem (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69551:34)
    at DiagnosticBuffer.setLocationlist (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69239:31)
    at sequence.addFunction (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69210:18)
    at promise.Promise (/Users/frm/.local/share/nvim/plugged/coc.nvim/build/index.js:69450:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

## Reproduce the bug

It happens only using `elixir-ls` and, so far, the first time the error occurs is in the following conditions:

1. Create module A and save the file.
2. Create module B that uses functions from A and save the file.
3. Change A so that the used functions in B have a different name. Save the file again.

When the error is detected upon the save of A, the error split pops up. Afterwards it occurs every second.

I'm not currently able to reproduce it on a `mini.vim` as it doesn't seem to be detecting the changes on module A and doesn't flag any issue in module B.

Might be worth mentioning this happens on nvim 0.5.0-nightly. Installed from `brew`: `neovim HEAD-55b62a9`

Last `mini.vim` used:

  ```vim
set nocompatible
set runtimepath^=/Users/frm/.local/share/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden

let g:elixirls = {
  \ 'path': printf('%s/%s', stdpath('data'), 'plugged/elixir-ls'),
  \ }

let g:elixirls.lsp = printf(
  \ '%s/%s',
  \ g:elixirls.path,
  \ 'release/language_server.sh')

call coc#config('languageserver', {
  \ 'elixir': {
  \   'command': g:elixirls.lsp,
  \   'filetypes': ['elixir', 'eelixir']
  \ }
  \})
```

For reference, [coc-settings.json](https://github.com/frm/dotfiles/blob/master/nvim/coc-settings.json).

## Screenshots

![image](https://user-images.githubusercontent.com/4325027/81857735-96557680-955a-11ea-8fd0-0ec86766fb24.png)

**Comment by frm** [comment]
Small update: can confirm this happens on neovim 0.4.3 as well.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

Could happen when diagnostic from language server doesn't have message, which is bug  of language server.
