### ISSUE TITLE
coc is broken after update

### ISSUE THREAD

**Issue by pavlosun** [neoclide/coc.nvim#1951]
I believe it is because of [this](https://github.com/neoclide/coc.nvim/commit/d7b30843755d6040f46d9d7d2fbc8f49fc366e1c)

LSP doesn't start. 

my log file shows:
```
2020-05-19T00:23:00.679 DEBUG (pid:11905) [workspace] - buffer created 1
2020-05-19T00:23:00.680 DEBUG (pid:11905) [events] - Event: BufEnter [ 1 ]
2020-05-19T00:23:00.682 DEBUG (pid:11905) [events] - Event: BufWinEnter [ 1, 1000 ]
2020-05-19T00:23:00.694 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.694 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.695 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.695 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.695 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.695 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.695 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.696 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.696 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.696 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.696 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.696 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.697 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.697 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.697 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.698 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.698 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.699 ERROR (pid:11905) [extensions] - TypeError: Cannot read property 'replace' of null
    at Promise (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:40875:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2020-05-19T00:23:00.703 ERROR (pid:11905) [extensions] - main file ./lib/index.js not found, you may need to build the project.
2020-05-19T00:23:00.722 INFO (pid:11905) [plugin] - coc.nvim 0.0.78-a5404ef5cd initialized with node: v10.20.1 after 51ms
2020-05-19T00:23:12.797 DEBUG (pid:11905) [events] - Event: CursorHold [ 1 ]
2020-05-19T00:23:13.996 DEBUG (pid:11905) [events] - Event: CursorHold [ 1 ]
2020-05-19T00:23:25.913 DEBUG (pid:11905) [events] - Event: GlobalChange [ 'coc_enabled', 1, 0 ]
2020-05-19T00:23:25.913 DEBUG (pid:11905) [events] - Event: BufUnload [ 1 ]
2020-05-19T00:23:25.914 DEBUG (pid:11905) [workspace] - buffer unload 1
2020-05-19T00:23:29.857 DEBUG (pid:11905) [events] - Event: GlobalChange [ 'coc_enabled', 0, 1 ]
2020-05-19T00:23:29.864 DEBUG (pid:11905) [workspace] - buffer created 1
2020-05-19T00:23:29.864 DEBUG (pid:11905) [events] - Event: BufEnter [ 1 ]
2020-05-19T00:23:29.866 DEBUG (pid:11905) [events] - Event: BufWinEnter [ 1, 1000 ]
2020-05-19T00:23:30.170 DEBUG (pid:11905) [events] - Event: CursorHold [ 1 ]
2020-05-19T00:23:44.493 DEBUG (pid:11905) [events] - Event: CursorHold [ 1 ]
2020-05-19T00:25:03.985 DEBUG (pid:11905) [events] - Event: FocusGained []
2020-05-19T00:25:05.401 DEBUG (pid:11905) [events] - Event: BufWinLeave [ 1, 1000 ]
2020-05-19T00:25:05.405 DEBUG (pid:11905) [events] - Event: BufUnload [ 1 ]
2020-05-19T00:25:05.405 DEBUG (pid:11905) [workspace] - buffer unload 1
2020-05-19T00:25:05.441 DEBUG (pid:11905) [events] - Event: VimLeave []
```
It was totally fine a minute ago, before the update.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
