### ISSUE TITLE
Unknown function: coc#util#valid_state

### ISSUE THREAD

**Issue by octavz** [neoclide/coc.nvim#1982]
## versions

vim version: NVIM v0.5.0-519-g74fed7d50
node version: v13.14.0
coc.nvim version: 0.0.78-030aef2f6d
term: xterm-256color
platform: linux

## Describe the bug

[coc.nvim] error: UnhandledRejection: request error nvim_eval - Vim:E117: Unknown function: coc#util#valid_state
Error: request error nvim_eval - Vim:E117: Unknown function: coc#util#valid_state
    at /home/user/.config/nvim/plugged/coc.nvim/build/index.js:14273:32
    at /home/user/.config/nvim/plugged/coc.nvim/build/index.js:10919:13
    at NvimTransport.parseMessage (/home/user/.config/nvim/plugged/coc.nvim/build/index.js:10860:17)
    at DecodeStream.<anonymous> (/home/user/.config/nvim/plugged/coc.nvim/build/index.js:10830:18)
    at DecodeStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at DecodeStream.Readable.push (_stream_readable.js:214:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)`
## Reproduce the bug

it just randomly appears at the bottom

**Comment by chemzqm** [comment]
Reinstall coc.nvim
