### ISSUE TITLE
Bug: Unable to successfully complete the post-install step.

### ISSUE THREAD

**Issue by megalithic** [neoclide/coc.nvim#2]
Hey there! I'd love to give this plugin a try.. BUT, I'm having issues getting the post-install step to complete successfully. Specifically, it's unable to complete the typescript compilation (build step) due to some type errors (in the cases failing for me, both, `id` and `listen` aren't members of `Buffer`).

**`init.vim` entry:**

```
Plug 'neoclide/coc.nvim', { 'do': 'npm install' }
```

This consistently fails to complete the post-install step (i've tried with both `npm install` and `yarn install`).

**Versions:**

node: 8.11.2
neovim-node-host: 4.1.0
neovim: 0.3.0
macos: 10.13.4
kitty: 0.11.1
tmux: 2.7

**Here is the npm debug log output:**

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/me/.n/bin/node',
1 verbose cli   '/Users/me/.n/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.1.0
3 info using node@v8.11.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle coc.nvim@0.0.1~prebuild: coc.nvim@0.0.1
6 info lifecycle coc.nvim@0.0.1~build: coc.nvim@0.0.1
7 verbose lifecycle coc.nvim@0.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle coc.nvim@0.0.1~build: PATH: /Users/me/.n/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/me/.dotfiles/nvim/plugged/coc.nvim/node_modules/.bin:/Users/me/.dotfiles/nvim/plugged/coc.nvim/node_modules/.bin:/Users/me/.config/yarn/link/node_modules/.bin:/Users/me/.dotfiles/nvim/plugged/coc.nvim/node_modules/.bin:/Users/me/.config/yarn/link/node_modules/.bin:/Users/me/.n/libexec/lib/node_modules/npm/bin/node-gyp-bin:/Users/me/.n/lib/node_modules/npm/bin/node-gyp-bin:/Users/me/.n/bin/node_modules/npm/bin/node-gyp-bin:/Users/me/.gem/ruby/2.3.1/bin:/Users/me/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bin:/Users/me/.rubies/ruby-2.3.1/bin:/Users/me/.avn/bin:/Users/me/.rbenv/shims:/Users/me/.avn/bin:/Users/me/.rbenv/shims:/Library/Frameworks/Python.framework/Versions/3.4/bin:/Users/me/.avn/bin:/Users/me/.rbenv/shims:./bin:./.bin:./vendor/bundle/bin:/Users/me/.rbenv/bin:/Users/me/bin:/Users/me/.bin:/Users/me/.dotfiles/bin:/Users/me/.rubies:/Users/me/.go/bin:/Users/me/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/local/lib/node_modules:/Users/me/.yarn/bin:/Users/me/.n/bin:/Users/me/.n/lib/node_modules:/Users/me/.config/yarn/global/node_modules/.bin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/imagemagick@6/bin:/usr/local/opt/qt@5.5/bin:/usr/local/opt/mysql@5.6/bin:/usr/local/opt/curl/bin:/usr/local/lib/python2.7/site-packages:/Users/me/Library/Python/3.6/lib/python/site-packages:/usr/bin:/usr/sbin:/bin:/sbin:/opt/X11/bin:/Users/me/.fzf/bin
9 verbose lifecycle coc.nvim@0.0.1~build: CWD: /Users/me/.dotfiles/nvim/plugged/coc.nvim
10 silly lifecycle coc.nvim@0.0.1~build: Args: [ '-c', 'tsc -p tsconfig.json' ]
11 silly lifecycle coc.nvim@0.0.1~build: Returned: code: 2  signal: null
12 info lifecycle coc.nvim@0.0.1~build: Failed to exec build script
13 verbose stack Error: coc.nvim@0.0.1 build: `tsc -p tsconfig.json`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/Users/me/.n/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/me/.n/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid coc.nvim@0.0.1
15 verbose cwd /Users/me/.dotfiles/nvim/plugged/coc.nvim
16 verbose Darwin 17.5.0
17 verbose argv "/Users/me/.n/bin/node" "/Users/me/.n/bin/npm" "run" "build"
18 verbose node v8.11.2
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 2
22 error coc.nvim@0.0.1 build: `tsc -p tsconfig.json`
22 error Exit status 2
23 error Failed at the coc.nvim@0.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Here's some of the `yarn build` stack trace:**

```
src/model/document.ts:98:39 - error TS2339: Property 'id' does not exist on type 'Buffer'.

98     let uri = getUri(fullpath, buffer.id)
                                         ~~


src/model/document.ts:129:35 - error TS2339: Property 'listen' does not exist on type 'Buffer'.

129     let unbindLines = this.buffer.listen('lines', (...args) => {
                                      ~~~~~~


src/model/document.ts:136:36 - error TS2339: Property 'listen' does not exist on type 'Buffer'.

136     let unbindChange = this.buffer.listen('changedtick', (buf:Buffer, tick:number) => {
                                       ~~~~~~


src/model/document.ts:137:15 - error TS2339: Property 'id' does not exist on type 'Buffer'.

137       if (buf.id !== this.buffer.id) return
                  ~~


src/model/document.ts:137:34 - error TS2339: Property 'id' does not exist on type 'Buffer'.

137       if (buf.id !== this.buffer.id) return
                                     ~~


src/model/document.ts:157:13 - error TS2339: Property 'id' does not exist on type 'Buffer'.

157     if (buf.id !== this.buffer.id) return
                ~~


src/model/document.ts:157:32 - error TS2339: Property 'id' does not exist on type 'Buffer'.

157     if (buf.id !== this.buffer.id) return
                                   ~~


src/model/document.ts:225:24 - error TS2339: Property 'id' does not exist on type 'Buffer'.

225     return this.buffer.id
                           ~~


src/model/document.ts:256:35 - error TS2339: Property 'id' does not exist on type 'Buffer'.

256     let buf = buffers.find(b => b.id == bufnr)
                                      ~~


src/workspace.ts:169:44 - error TS2339: Property 'id' does not exist on type 'Buffer'.

169     let document = this.getDocument(buffer.id)
                                               ~~


src/workspace.ts:242:26 - error TS2339: Property 'id' does not exist on type 'Buffer'.

242     const bufnr = buffer.id
                             ~~


src/workspace.ts:358:44 - error TS2339: Property 'id' does not exist on type 'Buffer'.

358     let document = this.getDocument(buffer.id)
                                               ~~


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! coc.nvim@0.0.1 build: `tsc -p tsconfig.json`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the coc.nvim@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2018-06-26T04_37_17_887Z-debug.log
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by chemzqm** [comment]
@megalithic https://github.com/neovim/node-client need to have a new release.
Sorry for the unconvince.

**Comment by chemzqm** [comment]
It's already merged https://github.com/neovim/node-client/commit/c1e940b04e163f6730f1ad2e6acd04519e6a7db1
 just need to publish a new release to npm.

**Comment by chemzqm** [comment]
BTW, coc currently only have some advanced language support for typescript (more language and LSP support is coming), so it might not fit your requirement.

**Comment by megalithic** [comment]
thanks for the info @chemzqm!

**Comment by megalithic** [comment]
@chemzqm might be worth adding a note to the `Troubleshooting` section to mention about the version of the neovim-node-host client needs to be updated past 4.1.0 to work with your plugin, which i still desperately want to try! :)

**Comment by megalithic** [comment]
@chemzqm I was able to complete the post-install process, yay! However, coc.nvim is never able to register with the plugins registry, e.g., it continually says there was a problem initializing and to run `:UpdateRemotePlugins` and restart. Running `:checkhealth` shows the following for coc.nvim:

```
health#coc#check
========================================================================
  - OK: Environment check passed
  - ERROR: service could not be initailized
    - ADVICE:
      - You may not have neovim package installed correctly,
      - check out https://github.com/neovim/node-client#debugging--troubleshooting
```

and the node-host health check shows:

```
## Node.js provider (optional)
  - INFO: Node.js: v8.11.3
  - INFO: Neovim node.js host: /Users/replicant/.n/bin/neovim-node-host
  - OK: Latest "neovim" npm package is installed: 4.2.0
```

**Comment by chemzqm** [comment]
Did you run `:UpdateRemotePlugins` after `npm install`? And what's the result?

**Comment by megalithic** [comment]
@chemzqm yes, repeatedly, with no specific error output, other than seeing that the plugin isn't registered with the node host. I know plugins can register with the node host because if I switch back to deoplete + nvim-typescript; nvim-typescript registers with the node host, and deoplete with the python3 host.

**Comment by chemzqm** [comment]
Check your `~/.local/share/nvim/rplugin.vim`, is that coc registered correctly?

According to https://github.com/neovim/node-client#debugging--troubleshooting, you can set `NVIM_NODE_LOG_LEVEL` to `error` and `NVIM_NODE_LOG_FILE` to a log file, and get the output from the log file.

**Comment by megalithic** [comment]
`~/.local/share/nvim/rplugin.vim` output:

```
" node plugins


" python3 plugins
call remote#host#RegisterPlugin('python3', '/Users/me/.dotfiles/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete', [
      \ {'sync': v:false, 'name': '_deoplete_init', 'type': 'function', 'opts': {}},
     \ ])


" ruby plugins


" python plugins
```

i'll see if i can't get logging to occur from the link you provided and will report back.

**Comment by chemzqm** [comment]
Looks like coc is not registed, the output of `:UpdateRemotePlugins` should contains:
<img width="443" alt="screen shot 2018-06-28 at 9 57 40 pm" src="https://user-images.githubusercontent.com/251450/42038751-4eb27196-7b1e-11e8-8a98-e366bd56e2c7.png">

**Comment by megalithic** [comment]
Exactly! However, we don't know why it's not able to register. I'm not getting any logging from your plugin or from the node client either. Are you able to remove your plugin completely and reinstall from GitHub without issues?

**Comment by chemzqm** [comment]
@megalithic just tried using node-client@4.2.0 from npm, no issue found.

**Comment by chemzqm** [comment]
There should be something in your log file, try set environment variable `NVIM_NODE_LOG_LEVEL` to `debug`
