### ISSUE TITLE
Error: Cannot find module 'promise.prototype.finally'

### ISSUE THREAD

**Issue by doronbehar** [neoclide/coc.nvim#2023]
## Result from CocInfo

Can't run `:CocInfo` since it's broken, but, I'm using:

- The latest release branch of coc.nvim
- `nvim --version` == 0.4.3
- `node --version` == 14.3.0

## Describe the bug

When I open Neovim, it gives me this error:

```
[coc.nvim] error: internal/modules/cjs/loader.js:1032
  throw err;
  ^
Error: Cannot find module 'promise.prototype.finally'
Require stack:
- /home/doron/.files/.config/nvim/bundle/coc/bin/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/doron/.files/.config/nvim/bundle/coc/bin/server.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/doron/.files/.config/nvim/bundle/coc/bin/server.js' ]
}
```

## Reproduce the bug

Start Neovim with nothing more then coc installed, using Node version 14.3.0 ?

**Comment by chemzqm** [comment]
Duplicate issue.

**Comment by rfclib** [comment]
@chemzqm Where is the coc.nvim folder located?

**Comment by doronbehar** [comment]
It depends on your plugin manager.

**Comment by greg218** [comment]
if you're using vim-plug, it would be in `~/.config/nvim/plugged`
