### ISSUE TITLE
Using clangd language server block my vim

### ISSUE THREAD

**Issue by YongSyu** [neoclide/coc.nvim#2051]
## Result from CocInfo

```
##versions 
vim version: VIM - Vi IMproved 8.2 8020900 
node version: v14.4.0coc.nvim version: 0.0.78-d5471449bf
term: Apple_Terminal 
platform: darwin   
```
## Describe the bug

when I edit .cc file, I will get some blocked for many time.

## Reproduce the log
```log
2020-06-09T17:28:33.110 DEBUG (pid:5801) [workspace] - buffer created 1
2020-06-09T17:28:33.111 DEBUG (pid:5801) [events] - Event: BufEnter [ 2 ]
2020-06-09T17:28:33.112 DEBUG (pid:5801) [events] - Event: BufWinEnter [ 2, 1001 ]
2020-06-09T17:28:33.138 INFO (pid:5801) [services] - registered service "highlight"
2020-06-09T17:28:33.139 DEBUG (pid:5801) [extensions] - activate: coc-highlight
2020-06-09T17:28:33.144 INFO (pid:5801) [language-client-index] - highlight started with 5805
2020-06-09T17:28:33.148 DEBUG (pid:5801) [extensions] - activate: coc-pairs
2020-06-09T17:28:33.161 DEBUG (pid:5801) [languages] - created service source snippets
2020-06-09T17:28:33.161 DEBUG (pid:5801) [languages] - created service source snippets-source
2020-06-09T17:28:33.163 DEBUG (pid:5801) [extensions] - activate: coc-snippets
2020-06-09T17:28:33.165 INFO (pid:5801) [plugin] - coc.nvim 0.0.78-d5471449bf initialized with node: v14.4.0 after 82ms
2020-06-09T17:28:46.431 DEBUG (pid:5801) [events] - Event: CursorHold [ 2 ]
2020-06-09T17:28:46.437 DEBUG (pid:5801) [workspace] - buffer created 2
2020-06-09T17:28:49.999 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 5, 1 ] ]
2020-06-09T17:28:50.582 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 6, 1 ] ]
2020-06-09T17:28:50.615 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 7, 1 ] ]
2020-06-09T17:28:50.649 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 8, 1 ] ]
2020-06-09T17:28:50.683 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 9, 1 ] ]
2020-06-09T17:28:50.720 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 10, 1 ] ]
2020-06-09T17:28:50.752 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 11, 1 ] ]
2020-06-09T17:28:50.785 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 12, 1 ] ]
2020-06-09T17:28:50.819 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 13, 1 ] ]
2020-06-09T17:28:50.854 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 14, 1 ] ]
2020-06-09T17:28:50.888 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 15, 1 ] ]
2020-06-09T17:28:50.922 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 16, 1 ] ]
2020-06-09T17:28:50.955 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 17, 1 ] ]
2020-06-09T17:28:50.990 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 18, 1 ] ]
2020-06-09T17:28:51.023 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 19, 1 ] ]
2020-06-09T17:28:51.057 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 20, 1 ] ]
2020-06-09T17:28:51.091 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 21, 1 ] ]
2020-06-09T17:28:51.124 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 22, 1 ] ]
2020-06-09T17:28:51.159 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 23, 1 ] ]
2020-06-09T17:28:51.192 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 24, 1 ] ]
2020-06-09T17:28:51.227 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 25, 1 ] ]
2020-06-09T17:28:51.428 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 26, 1 ] ]
2020-06-09T17:28:52.272 DEBUG (pid:5801) [events] - Event: CursorMoved [ 2, [ 27, 1 ] ]
2020-06-09T17:28:52.604 DEBUG (pid:5801) [events] - Event: BufUnload [ 1 ]
2020-06-09T17:28:52.605 DEBUG (pid:5801) [workspace] - buffer unload 1
2020-06-09T17:28:52.618 DEBUG (pid:5801) [events] - Event: BufCreate [ 3 ]
2020-06-09T17:28:52.619 DEBUG (pid:5801) [events] - Event: BufEnter [ 3 ]
2020-06-09T17:28:52.620 DEBUG (pid:5801) [events] - Event: BufWinEnter [ 3, 1002 ]
2020-06-09T17:28:52.622 DEBUG (pid:5801) [events] - Event: FileType [ 'tagbar', 3 ]
2020-06-09T17:28:52.743 DEBUG (pid:5801) [events] - Event: BufEnter [ 1 ]
2020-06-09T17:28:52.745 DEBUG (pid:5801) [events] - Event: FileType [ 'cpp', 1 ]
2020-06-09T17:28:52.746 DEBUG (pid:5801) [events] - Event: BufCreate [ 1 ]
2020-06-09T17:28:52.747 DEBUG (pid:5801) [events] - Event: BufEnter [ 1 ]
2020-06-09T17:28:54.624 WARN (pid:5801) [events] - Handler of BufCreate blocked more than 2s: Error
    at Events.on (/Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:16283:25)
    at Workspace.init (/Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:25320:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Plugin.init (/Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:23609:13)
    at async /Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:11375:13
2020-06-09T17:28:54.624 WARN (pid:5801) [events] - Handler of BufEnter blocked more than 2s: Error
    at Events.on (/Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:16283:25)
    at DiagnosticManager.init (/Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:24153:26)
    at Plugin.init (/Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:23615:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:11375:13
2020-06-09T17:28:54.748 WARN (pid:5801) [events] - Handler of BufEnter blocked more than 2s: Error
    at Events.on (/Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:16283:25)
    at DiagnosticManager.init (/Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:24153:26)
    at Plugin.init (/Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:23615:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:11375:13
2020-06-09T17:28:54.748 WARN (pid:5801) [events] - Handler of BufCreate blocked more than 2s: Error
    at Events.on (/Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:16283:25)
    at Workspace.init (/Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:25320:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Plugin.init (/Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:23609:13)
    at async /Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:11375:13
2020-06-09T17:28:54.748 WARN (pid:5801) [events] - Handler of BufEnter blocked more than 2s: Error
    at Events.on (/Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:16283:25)
    at DiagnosticManager.init (/Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:24153:26)
    at Plugin.init (/Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:23615:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/yongsyu-li/.vim/plugged/coc.nvim/build/index.js:11375:13
2020-06-09T17:29:01.105 DEBUG (pid:5801) [events] - Event: FileType [ 'qf', 4 ]
2020-06-09T17:29:01.106 DEBUG (pid:5801) [events] - Event: BufWinEnter [ 1, 1000 ]
2020-06-09T17:29:01.107 DEBUG (pid:5801) [events] - Event: CursorMoved [ 1, [ 1, 1 ] ]
2020-06-09T17:29:01.174 DEBUG (pid:5801) [workspace] - buffer created 3
```

**Comment by chemzqm** [comment]
Try minimal vimrc.
