### ISSUE TITLE
Coc unable to handle extensive amount of notifications

### ISSUE THREAD

**Issue by theniceboy** [neoclide/coc.nvim#2113]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-9a67b030d
node version: v12.18.1
coc.nvim version: 0.0.78-551353208d
coc.nvim directory: /Users/david/.config/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Output channel: explorer


## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /Users/david/Github/dugl-functions
> git ls-files -- functions/func/stats.js
> git --no-pager show :functions/func/stats.js
resolved root: /Users/david/Github/dugl-functions
> git ls-files -- functions/func/stats.js
> git --no-pager show :functions/func/stats.js

## Output channel: prettier


## Output channel: snippets

[Info 11:02:41 AM] Using ultisnips directories: /Users/david/.config/nvim/Ultisnips/ /Users/david/.config/nvim/plugged/vim-snippets/UltiSnips/ /Users/david/.config/coc/ultisnips
[Info 11:02:41 AM] Using ultisnips python command: pyx

## Output channel: eslint

[Info  - 11:02:41 AM] ESLint server running in node v12.18.1
[Info  - 11:02:42 AM] ESLint library loaded from: /usr/local/Cellar/node@12/12.18.1/lib/node_modules/eslint/lib/api.js

## Output channel: translator


## Output channel: tsserver

[Info  - 11:02:42 AM] Forking TSServer
PATH: /Users/david/prog/google-cloud-sdk/bin:/Users/david/prog/google-cloud-sdk/bin:/Users/david/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/david/prog/google-cloud-sdk/bin:/Users/david/.cargo/bin:/Users/david/.config/bin:/Users/david/.gem/ruby/2.6.0:/Users/david/go/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/Users/david/.linuxbrew/bin:/Users/david/.linuxbrew/sbin:/Users/david/.local/bin:/usr/local/Cellar/node/14.2.0/bin:/snap/bin:/usr/local/opt/node@12/bin:/Users/david/prog/flutter/bin:/Users/david/prog/flutter/bin/cache/dart-sdk/bin:/Users/david/.pub-cache/bin:/home/dugl/bin:/usr/local/go/bin:/Users/david/go:/Users/david/.config/bin:/Users/david/.gem/ruby/2.6.0:/usr/local/bin:/Users/david/go/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/Users/david/.linuxbrew/bin:/Users/david/.linuxbrew/sbin:/Users/david/.local/bin:/usr/local/Cellar/node/14.2.0/bin:/Users/david/.cargo/bin:/snap/bin:/usr/local/opt/node@12/bin:/Users/david/prog/flutter/bin:/Users/david/prog/flutter/bin/cache/dart-sdk/bin:/Users/david/.pub-cache/bin:/home/dugl/bin:/usr/local/go/bin:/Users/david/go:/home/dugl/bin:/Users/david/.config/bin:/Users/david/.gem/ruby/2.6.0:/usr/local/bin:/Users/david/go/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/Users/david/.linuxbrew/bin:/Users/david/.linuxbrew/sbin:/Users/david/.local/bin:/usr/local/Cellar/node/14.2.0/bin:/Users/david/.cargo/bin:/snap/bin:/usr/local/opt/node@12/bin:/Users/david/prog/flutter/bin:/Users/david/prog/flutter/bin/cache/dart-sdk/bin:/Users/david/.pub-cache/bin:/home/dugl/bin:/usr/local/go/bin:/Users/david/go:/home/dugl/bin 
[Info  - 11:02:42 AM] Started TSServer
{
  "path": "/Users/david/.config/coc/extensions/node_modules/coc-tsserver/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.9.5",
    "version": "3.9.5"
  }
}


```
## Describe the bug

Coc extensions (such as `coc-flutter`) that produce a lot of floating window notifications will cause error like this:
```
[coc.nvim]: UnhandledRejection: request error nvim_win_get_buf - Invalid window id: 3103
Error: request error nvim_win_get_buf - Invalid window id: 3103
    at /Users/david/.config/nvim/plugged/coc.nvim/build/index.js:15213:32
    at /Users/david/.config/nvim/plugged/coc.nvim/build/index.js:11878:13
    at NvimTransport.parseMessage (/Users/david/.config/nvim/plugged/coc.nvim/build/index.js:11819:17)
    at DecodeStream.<anonymous> (/Users/david/.config/nvim/plugged/coc.nvim/build/index.js:11789:18)
    at DecodeStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at DecodeStream.Readable.push (_stream_readable.js:212:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (/Users/david/.config/nvim/plugged/coc.nvim/build/index.js:14761:12)
UnhandledRejection: request error nvim_win_get_buf - Invalid window id: 3103
Error: request error nvim_win_get_buf - Invalid window id: 3103
    at /Users/david/.config/nvim/plugged/coc.nvim/build/index.js:15213:32
    at /Users/david/.config/nvim/plugged/coc.nvim/build/index.js:11878:13
    at NvimTransport.parseMessage (/Users/david/.config/nvim/plugged/coc.nvim/build/index.js:11819:17)
    at DecodeStream.<anonymous> (/Users/david/.config/nvim/plugged/coc.nvim/build/index.js:11789:18)
    at DecodeStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at DecodeStream.Readable.push (_stream_readable.js:212:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (/Users/david/.config/nvim/plugged/coc.nvim/build/index.js:14761:12)
UnhandledRejection: request error nvim_win_get_buf - Invalid window id: 3103
```

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Install `coc-flutter`
- Create a flutter project
- Make an overflow error, such as a ListView within a ListView
- Error messages pop out

## Screenshots (optional)

![Screen Shot 2020-06-26 at 3 17 13 PM](https://user-images.githubusercontent.com/8187501/85893069-1f013c80-b7c0-11ea-9bef-d2fac488362f.png)

**Comment by fannheyward** [comment]
cc @iamcco , can you check this ？

**Comment by chemzqm** [comment]
Please send your bug report to coc-flutter
