### ISSUE TITLE
internal/modules/cjs/loader.js:1032

### ISSUE THREAD

**Issue by cybaol** [neoclide/coc.nvim#2164]
my plugmanager is dein
after installing coc.nvim then restart nvim
mention followers:

**[coc.nvim]: internal/modules/cjs/loader.js:1032
  throw err;
  ^
Error: Cannot find module './constants'
Require stack:
- /home/kino/.cache/dein/.cache/init.vim/.dein/node_modules/semver/internal/re.js
- /home/kino/.cache/dein/.cache/init.vim/.dein/node_modules/semver/index.js
- /home/kino/.cache/dein/.cache/init.vim/.dein/bin/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/kino/.cache/dein/.cache/init.vim/.dein/node_modules/semver/internal/re.js:1:39)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/kino/.cache/dein/.cache/init.vim/.dein/node_modules/semver/internal/re.js',
    '/home/kino/.cache/dein/.cache/init.vim/.dein/node_modules/semver/index.js',
    '/home/kino/.cache/dein/.cache/init.vim/.dein/bin/server.js'
  ]
}**

**Comment by chemzqm** [comment]
Read wiki

**Comment by YuSuFApiwi** [comment]
1. Delete _package-lock.json_ file (not **_package.json_**) or _yarn.lock_ file from your project.

2. Remove the _node_modules_ from your project, follow below article instructions to remove the node modules from your project

`npm cache clean --force`
And
`npm install`
