### ISSUE TITLE
Node 14.2 Error [coc.nvim]: internal/validators.js:121

### ISSUE THREAD

**Issue by arrudaricardo** [neoclide/coc.nvim#2240]
## Result from CocInfo

coc.nvim service not started, checking environment...Service stopped for some unknown reason, try :CocStart

## Describe the bug

After update node to version 14.2.0 I'm getting the error : 

```
[coc.nvim]: internal/validators.js:121
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Object.join (path.js:1039:7)
    at getLogFile (/home/ric/.local/share/nvim/plugged/coc.nvim/build/index.js:3188:26)
    at Object.<anonymous> (/home/ric/.local/share/nvim/plugged/coc.nvim/build/index.js:3198:15)
    at __webpack_require__ (/home/ric/.local/share/nvim/plugged/coc.nvim/build/index.js:20:30)
    at Object.<anonymous> (/home/ric/.local/share/nvim/plugged/coc.nvim/build/index.js:109:16)
    at __webpack_require__ (/home/ric/.local/share/nvim/plugged/coc.nvim/build/index.js:20:30)
    at /home/ric/.local/share/nvim/plugged/coc.nvim/build/index.js:84:18
    at Object.<anonymous> (/home/ric/.local/share/nvim/plugged/coc.nvim/build/index.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:1176:30) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

It's work fine after going back to old node versions

## Reproduce the bug

update node.js to 14.2 and initialize vim

## Screenshots 

Node.js 14.2
![Untitled](https://user-images.githubusercontent.com/35773631/89957073-33e64200-dc3f-11ea-9dd5-b330100dbe28.png)

Node.js 12.18.3
![Untitled](https://user-images.githubusercontent.com/35773631/89957152-63954a00-dc3f-11ea-82cd-dfd03f7b454f.png)

**Comment by oblitum** [comment]
Try filling issue template and add minimal `init.vim`. I'm on node 14.7.0 and never saw this.

**Comment by arrudaricardo** [comment]
For anyway facing this issue, update node to a higher version than nodejs 14.2
