### ISSUE TITLE
Plugin initialized error: (E15) invalid expression: g:coc_user_config

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#226]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

```
E492: Not an editor command: CocInfo
```

**Describe the bug**

I get `Plugin initialized error: Error: request nvim_get_var - vim (E15) invalid expression: g:coc_user_config` when trying this configuration from `.vimrc`:

```vim
  call coc#config('coc.preferences', {
  \   'diagnostic.errorSign'  : '🕱',
  \   'diagnostic.warningSign': '☢',
  \   'diagnostic.infoSign'   : '',
  \   'diagnostic.hintSign'   : 'ﯦ',
  \   'snippetIndicator': ' ',
  \   'messageLevel': 'warning',
  \   'languageserver': {
  \     'ccls': {
  \       'command': 'ccls',
  \       'filetypes': ['c', 'cpp', 'objc', 'objcpp'],
  \       'rootPatterns': ['.ccls', 'compile_flags.txt', 'compile_commands.json'] + g:rooter_patterns,
  \       'initializationOptions': {
  \         'cacheDirectory': '/tmp/ccls'
  \       }
  \     },
  \     'golang': {
  \       'command': 'go-langserver',
  \       'filetypes': ['go'],
  \       'initializationOptions': {
  \         'gocodeCompletionEnabled': 1,
  \         'diagnosticsEnabled': 1,
  \         'lintTool': 'golint'
  \       }
  \     }
  \   }
  \ })
```

I'm not sure whether I'm following the example in docs correctly, I tried to resemble the changes as possible. This is the original working `coc-settings.json`:

```jsonc
{
  "coc.preferences.diagnostic.errorSign": "🕱",
  "coc.preferences.diagnostic.warningSign": "☢",
  "coc.preferences.diagnostic.infoSign": "",
  "coc.preferences.diagnostic.hintSign": "ﯦ",
  "coc.preferences.snippetIndicator": " ",
  "coc.preferences.messageLevel": "warning",
  "languageserver": {
    "ccls": {
      "command": "ccls",
      "filetypes": ["c", "cpp", "objc", "objcpp"],
      "initializationOptions": {
        "cacheDirectory": "/tmp/ccls"
      }
    },
    "golang": {
      "command": "go-langserver",
      "filetypes": ["go"],
      "initializationOptions": {
        "gocodeCompletionEnabled": true,
        "diagnosticsEnabled": true,
        "lintTool": "golint"
      }
    }
  }
}
````

This is the full error message:

```
[coc.nvim] Plugin initialized error: Error: request nvim_get_var - vim (E15) invalid expression: g:coc_user_config
[coc.nvim]     at transport.request (/home/francisco/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:33:28)
[coc.nvim]     at Transport.parseMessage (/home/francisco/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:107:13)
[coc.nvim]     at DecodeStream.Transport.decodeStream.on (/home/francisco/.vim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:41:18)
[coc.nvim]     at DecodeStream.emit (events.js:182:13)
[coc.nvim]     at addChunk (_stream_readable.js:287:12)
[coc.nvim]     at readableAddChunk (_stream_readable.js:268:11)
[coc.nvim]     at DecodeStream.Readable.push (_stream_readable.js:223:10)
[coc.nvim]     at DecodeStream.Transform.push (_stream_transform.js:151:32)
[coc.nvim]     at DecodeBuffer.DecodeStream.decoder.push (/home/francisco/.vim/plugged/coc.nvim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)
[coc.nvim]     at DecodeBuffer.flush (/home/francisco/.vim/plugged/coc.nvim/node_modules/msgpack-lite/lib/flex-buffer.js:57:12)

```

**To Reproduce**

Just setting up coc conf with `coc#config()`, without a `coc-settings.json` file present.

**Comment by oblitum** [comment]
Ops, I just noticed, the error shows up with Vim, since the API called is `nvim_get_var`. There's no error with NeoVim, but the configurations didn't apply.

**Comment by chemzqm** [comment]
It's bug of vim-node-rpc, it should return null when variable not found.

**Comment by oblitum** [comment]
Right, this error is showing up with Vim anytime, even with original `coc-settings.json` setup.

**Comment by oblitum** [comment]
Just stopped after `yarn global update`. I guess that part is fixed. I'll close this and open another issue in case I didn't figure out how to call `coc#config()` properly.

**Comment by chemzqm** [comment]
I've fixed vim-node-rpc to not throw this error.

**Comment by oblitum** [comment]
ah ok, thanks!
