### ISSUE TITLE
coc-java: coc-rename creates multiple undo steps

### ISSUE THREAD

**Issue by tbo** [neoclide/coc.nvim#229]
**Result from CocInfo**
```
## versions

vim version: NVIM v0.3.1
node version: v9.10.1
coc.nvim version: 0.0.36
term: xterm-256color
platform: darwin

## Error messages

## Output channel: java
[Info  - 10:32:03] JDT Language Server started
[object Object]
[Warn  - 10:32:13] Dec 5, 2018 10:32:13 AM The Java indexing could not index /Users/tbo/.m2/repository/org/glassfish/hk2/external/asm-all-repackaged/2.5.0-b42/asm-all-repackaged-2.5.0-b42.jar|module-info.class. This .class file doesn't follow the class file format specification. Please report this issue against the .class file vendor
null
org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:477)
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:180)
	at org.eclipse.jdt.internal.core.search.indexing.BinaryIndexer.indexDocument(BinaryIndexer.java:652)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.indexDocument(JavaSearchParticipant.java:73)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexDocument(IndexManager.java:546)
	at org.eclipse.jdt.internal.core.search.indexing.AddJarFileToIndex.execute(AddJarFileToIndex.java:244)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:401)
	at java.lang.Thread.run(Thread.java:748)
Caused in /Users/tbo/.m2/repository/org/glassfish/hk2/external/asm-all-repackaged/2.5.0-b42/asm-all-repackaged-2.5.0-b42.jar|module-info.class by: java.lang.ArrayIndexOutOfBoundsException: 32800
	at org.eclipse.jdt.internal.compiler.classfmt.ModuleInfo.readModuleAttribute(ModuleInfo.java:129)
	at org.eclipse.jdt.internal.compiler.classfmt.ModuleInfo.createModule(ModuleInfo.java:113)
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:440)
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:180)
	at org.eclipse.jdt.internal.core.search.indexing.BinaryIndexer.indexDocument(BinaryIndexer.java:652)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.indexDocument(JavaSearchParticipant.java:73)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexDocument(IndexManager.java:546)
	at org.eclipse.jdt.internal.core.search.indexing.AddJarFileToIndex.execute(AddJarFileToIndex.java:244)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:401)
	at java.lang.Thread.run(Thread.java:748)
```

**Describe the bug**

`coc-rename` for `coc-java` creates one undo step for each replaced symbol. This differs from its previous behavior. 

`coc-tsserver` works as expected.

**To Reproduce**

Replace any symbol, that occurs more than once.

**Comment by chemzqm** [comment]
The server doesn't merge edits of same document.

**Comment by nicobao** [comment]
> The server doesn't merge edits of same document.

I understand that it is a limitation from eclipse lsp - however, is there a way to undo the `coc-rename` command without having to get into each file one by one that were changed and use the "u" command?

**Comment by chemzqm** [comment]
`:h coc-refactor` the refactor window is what you need, it also support add lines.
