### ISSUE TITLE
coc process exits on cluster node, but not on cluster head-node

### ISSUE THREAD

**Issue by ipstone** [neoclide/coc.nvim#2291]
Hello,

Thanks for coc - it's so useful and easy to setup!

My coc setup works perfectly on local machine (mac/linux), as well as on our cluster login node. 

However, when I am running coc on a computation node (centOS 7), coc process kept crashing, it gives this msg in vim 8.2:
`client coc abnormal exit with: 1 `

and if running nvim 0.4.2:
```
[coc.nvim]: /cluster_name/home/ipstone/.ipdot/.vim/plugged/coc.nvim/build/index.js:8278                                                           throw err0                                                                                                                     ^                                                                                                                      
Error: EACCES: permission denied, mkdir '/run/user/1452'                                                                       
    at Object.mkdirSync (fs.js:773:3)                                                                                          
    at Object.mkdirsSync (/cluster_name/home/ipstone/.ipdot/.vim/plugged/coc.nvim/build/index.js:8264:9)                                  
    at RollingFileStream._renewWriteStream (/cluster_name/home/ipstone/.ipdot/.vim/plugged/coc.nvim/build/index.js:6819:8)                
    at new RollingFileWriteStream (/cluster_name/home/ipstone/.ipdot/.vim/plugged/coc.nvim/build/index.js:6668:10)                        
    at new RollingFileStream (/cluster_name/home/ipstone/.ipdot/.vim/plugged/coc.nvim/build/index.js:10467:5)                             
    at openTheStream (/cluster_name/home/ipstone/.ipdot/.vim/plugged/coc.nvim/build/index.js:6487:18)                                     
    at fileAppender (/cluster_name/home/ipstone/.ipdot/.vim/plugged/coc.nvim/build/index.js:6531:16)                                      
    at Object.configure (/cluster_name/home/ipstone/.ipdot/.vim/plugged/coc.nvim/build/index.js:6567:10)                                  
    at clustering.onlyOnMaster (/cluster_name/home/ipstone/.ipdot/.vim/plugged/coc.nvim/build/index.js:5885:27)                           
    at Object.onlyOnMaster (/cluster_name/home/ipstone/.ipdot/.vim/plugged/coc.nvim/build/index.js:6019:50)   
```

What might be the cause of this?  Thanks in advance!

ipstone

**Comment by fannheyward** [comment]
> permission denied, mkdir '/run/user/1452'  

Looks like the user doesn't has write permission on your computation node.

**Comment by ipstone** [comment]
@fannheyward  it's not the the case, the user has write permission , such as all other vim plugins work fine. Additionally, node processes such as those used in jupyter notebook also works fine.

There might be some user permission issue with processes running on cluster node ... but I don't understand that part: i.e. how an interactive cluster login/process are handled by the cluster ...

**Comment by fannheyward** [comment]
To be honest, I don't know what `cluster node` `computation node` means.

**Comment by ipstone** [comment]
@fannheyward Thanks for re-opening this: just some clarification: I am trying to use vim on a hpc - high performance cluster: which has multiple high performance server serving together as a cluster. 

Usually for these clusters: there is a machine for user to login (which is usually called head node), and other servers are serving as 'computation node': to run interactive sessions (shell) on the computation node need cluster job management to launch a terminal there.

I think the problem is rightly the file access issue, I am also asking for help to see what causes it. I will keep this issue open for a week, if can not solve it, I will close it then. 

Thank you again for your help!

**Comment by ipstone** [comment]
@fannheyward Why coc needs folder access for ` mkdir '/run/user/1452 ` - could this request using some other folders where user might have write access?

Regarding:
```
Error: EACCES: permission denied, mkdir '/run/user/1452'
```

**Comment by ipstone** [comment]
-- still couldn't find a solution

**Comment by chemzqm** [comment]
Try `:echo fnamemodify(tempname(), ':p:h')`, seems is your tmp directory.

**Comment by ipstone** [comment]
Running the command gives the following output: ```/scratch/lsftmp/17169013.tmpdir/vz5n67m```
ideas? Thanks
