### ISSUE TITLE
connection error for languageserver.godot

### ISSUE THREAD

**Issue by habamax** [neoclide/coc.nvim#2334]
Godot is a [game engine](https://godotengine.org/ ) that has language server implemented for a builtin gdscript language.

## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8021657
node version: v14.10.1
coc.nvim version: 0.0.79-4f40c16a15
coc.nvim directory: C:\Users\maksim.kim\vimfiles\pack\minpac\opt\coc.nvim
term: undefined
platform: win32

## Output channel: languageserver.godot

[Error  - 20:47:14] Starting client failed 
Error: Connection error for languageserver.godot: connect ECONNREFUSED 127.0.0.1:6008
    at Socket.<anonymous> (C:\Users\maksim.kim\vimfiles\pack\minpac\opt\coc.nvim\build\index.js:73049:24)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

## Describe the bug

Doesn't work for godot language server. Works with previous version.

## Reproduce the bug

1. start godot, open a game project
2. start vim and open one of the gdscript files from game project
3. `:CocInfo`

settings:

```

{
    "diagnostic.enableSign": false,
    "coc.source.around.firstMatch": false,
    "coc.source.buffer.firstMatch": false,

    "languageserver": {
        "godot": {
            "host": "127.0.0.1",
            "filetypes": ["gdscript"],
            "port": 6008
        }
    }
}
```

**Comment by habamax** [comment]
I have restarted my laptop, just in case... and now it works.
