### ISSUE TITLE
[ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#237]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

```
## versions

vim version: NVIM v0.3.1
node version: v11.3.0
coc.nvim version: 0.0.37
term: tmux-256color
platform: linux

## Error messages

## Output channel: languageserver.ccls
[Error  - 4:58:09 PM] Starting client failed
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.dirname (path.js:1265:5)
    at Object.resolveRoot (/home/francisco/.vim/plugged/coc.nvim/lib/util/fs.js:71:31)
    at LanguageClient.initialize (/home/francisco/.vim/plugged/coc.nvim/lib/language-client/client.js:1996:41)
    at resolveConnection.then.connection (/home/francisco/.vim/plugged/coc.nvim/lib/language-client/client.js:1962:25)

## Output channel: prettier
```

**Describe the bug**

Error message started to show up after latest commits by simply opening files, no change was made to configuration.

This is my configuration:

```
  call coc#config('coc.preferences', {
  \   'diagnostic.errorSign'  : '🕱',
  \   'diagnostic.warningSign': '☢',
  \   'diagnostic.infoSign'   : '',
  \   'diagnostic.hintSign'   : 'ﯦ',
  \   'snippetIndicator'      :' ',
  \   'messageLevel': 'warning'
  \ })
  call coc#config('languageserver', {
  \   'ccls': {
  \     'command': 'ccls',
  \     'filetypes': ['c', 'cpp', 'objc', 'objcpp'],
  \     'rootPatterns': ['.ccls', 'compile_flags.txt', 'compile_commands.json'] + get(g:, 'rooter_patterns', []),
  \     'initializationOptions': {
  \       'cacheDirectory': '/tmp/ccls'
  \     }
  \   },
  \   'golang': {
  \     'command': 'go-langserver',
  \     'filetypes': ['go'],
  \     'initializationOptions': {
  \       'gocodeCompletionEnabled': v:true,
  \       'diagnosticsEnabled': v:true,
  \       'lintTool': 'golint'
  \     }
  \   },
  \   'bash': {
  \     'command': 'bash-language-server',
  \     'filetypes': ['sh'],
  \     'args': ['start']
  \   }
  \ })
```

**To Reproduce**

1. Open a c++ file with language server configuration from `.vimrc`.
2. Error shows up in output channel.

**Comment by oblitum** [comment]
I also got the same error when trying to open a vim session (`vim -S`), where I just had vim help files open in it.

**Comment by oblitum** [comment]
For the session with just help files:

**To Reproduce**
Steps to reproduce the behavior:

1. Execute `vim` or `nvim`
2. Open two different help sections with `:h` in split
3. Save the session with `:mksession` (I use the Obsession plugin actually)
4. Close `vim` (or `nvim`)
5. Open `vim` (or `nvim`) with `vim -S` to load the session on startup

This error shows up and `:CocInfo` isn't available:

```
"/usr/share/nvim/runtime/doc/usr_41.txt" [RO] 2516L, 85920C
"/usr/share/nvim/runtime/doc/eval.txt" [RO] 10778L, 417749C
[coc.nvim] Plugin initialized error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.dirname (path.js:1265:5)
    at Object.resolveRoot (/home/francisco/.vim/plugged/coc.nvim/lib/util/fs.js:71:31)
    at Workspace.resolveRoot (/home/francisco/.vim/plugged/coc.nvim/lib/workspace.js:1035:25)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
E492: Not an editor command: CocInfo
```

**Comment by oblitum** [comment]
For some reason I can't reproduce the help session issue anymore, but former problem is still happening.

**Comment by oblitum** [comment]
Issue is exactly on commit 2e82898.
