### ISSUE TITLE
Error on BufWinLeave

### ISSUE THREAD

**Issue by stealthanthrax** [neoclide/coc.nvim#2390]
Whenever I change my buffer in neovim, I am getting the following error:

```
[coc.nvim]: Error on BufWinLeave: Cannot read property 'shown' of undefined
TypeError: Cannot read property 'shown' of undefined
    at /Users/sanskar/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:1:88942
    at /Users/sanskar/.config/nvim/autoload/plugged/coc.nvim/build/index.js:16565:45
    at new Promise (<anonymous>)
    at wrappedhandler (/Users/sanskar/.config/nvim/autoload/plugged/coc.nvim/build/index.js:16562:42)
    at /Users/sanskar/.config/nvim/autoload/plugged/coc.nvim/build/index.js:16539:49
    at Array.map (<anonymous>)
    at Events.fire (/Users/sanskar/.config/nvim/autoload/plugged/coc.nvim/build/index.js:16539:39)
    at NeovimClient.<anonymous> (/Users/sanskar/.config/nvim/autoload/plugged/coc.nvim/build/index.js:11580:40)
    at NeovimClient.emit (events.js:314:20)
    at NeovimClient.emitNotification (/Users/sanskar/.config/nvim/autoload/plugged/coc.nvim/build/index.js:11894:18)
```
which is very annoying.

I am a bit confused about which plugin may be causing this. I would be happy to share more info about my config. 

Need some help in fixing the above.

Thanks in advance.

**Comment by chemzqm** [comment]
Problem with your coc-explorer
