### ISSUE TITLE
[coc.nvim]: Error on initialize: Error: request error nvim_call_function - Vim(return):E684: List 索引超出范围: 0 

### ISSUE THREAD

**Issue by yygyyuyan** [neoclide/coc.nvim#2424]
## Result from CocInfo

:CocInfo 
No return

error
[coc.nvim]: Error on initialize: Error: request error nvim_call_function - Vim(return):E684: List 索引超出范围: 0
    at /home/pi/.config/nvim/plugged/coc.nvim/build/index.js:15462:32
    at /home/pi/.config/nvim/plugged/coc.nvim/build/index.js:12127:13
    at NvimTransport.parseMessage (/home/pi/.config/nvim/plugged/coc.nvim/build/index.js:12068:17)
    at DecodeStream.<anonymous> (/home/pi/.config/nvim/plugged/coc.nvim/build/index.js:12038:18)
    at DecodeStream.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at DecodeStream.Readable.push (_stream_readable.js:214:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (/home/pi/.config/nvim/plugged/coc.nvim/build/index.js:15010:12)
    at DecodeBuffer.flush (/home/pi/.config/nvim/plugged/coc.nvim/build/index.js:14000:12)
    at DecodeStream._transform (/home/pi/.config/nvim/plugged/coc.nvim/build/index.js:15016:16)
    at DecodeStream.Transform._read (_stream_transform.js:191:10)
    at DecodeStream.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)

:checkhealth
    1  
    2 health#coc#check
    3 ========================================================================
    4   - OK: Environment check passed
    5  
    6   - OK: Javascript bundle build/index.js found
    7   - OK: Service started
    8  
    9 health#nvim#check
   10 ========================================================================
   11 ## Configuration
   12   - OK: no issues found
   13  
   14 ## Performance
   15   - OK: Build type: Release
   16                   
   17 ## Remote Plugins
   18   - OK: Up to date
   19  
   20 ## terminal
   21   - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
   22   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
   23   - INFO: $VTE_VERSION='5402'
   24   - INFO: $COLORTERM='truecolor'
   25  
   26 health#provider#check
   27 ========================================================================
   28 ## Clipboard (optional)
   29   - OK: Clipboard tool found: xsel
   30  
   31 ## Python 2 provider (optional)
   32   - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
   33   - INFO: Executable: /usr/bin/python2
   34   - INFO: Python version: 2.7.16   
   35   - INFO: pynvim version: 0.4.2    
   36   - OK: Latest pynvim is installed.
   37  
   38 ## Python 3 provider (optional)
   39   - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
   40   - INFO: Executable: /usr/bin/python3
   41   - INFO: Python version: 3.7.3
   42   - INFO: pynvim version: 0.4.2
   43   - OK: Latest pynvim is installed.
   44  
   45 ## Ruby provider (optional)
   46   - INFO: Ruby: ruby 2.5.5p157 (2019-03-15 revision 67260) [arm-linux-gnueabihf]
   47   - INFO: Host: /usr/local/bin/neovim-ruby-host
   48   - OK: Latest "neovim" gem is installed: 0.8.1
   49  
   50 ## Node.js provider (optional)
   51   - INFO: Node.js: v12.19.0
   52   - INFO: Neovim node.js host: /usr/lib/node_modules/neovim/bin/cli.js
   53   - OK: Latest "neovim" npm/yarn package is installed: 4.9.0

`vim -u mini.vim` result
![屏幕截图 2020-10-08 205648](https://user-images.githubusercontent.com/49018276/95461444-d2292680-09a8-11eb-874c-15237650f2b2.png)

**Comment by chemzqm** [comment]
Try minimal vimrc.
Will improve error stack for remote request
