### ISSUE TITLE
Floating window does not open anymore (Unknown function coc#util#create_float_win)

### ISSUE THREAD

**Issue by yannham** [neoclide/coc.nvim#2481]
## Result from CocInfo

```

## versions

vim version: NVIM v0.4.4
node version: v12.19.0
coc.nvim version: 0.0.79
coc.nvim directory: /home/yago/.vim/bundle/coc.nvim
term: xterm-256color
platform: linux

## Output channel: git
Looking for git in: git
> git rev-parse --show-toplevel
resolved root of /home/yago/Taff/Tweag/Nickel/nickel/src/merge.rs: /home/yago/Taff/Tweag/Nickel/nickel
> git ls-files -- src/merge.rs
> git symbolic-ref --short HEAD
> git --no-pager show :src/merge.rs
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git diff src/merge.rs
> git symbolic-ref --short HEAD
> git ls-files -- src/merge.rs
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git symbolic-ref --short HEAD
> git ls-files -- src/merge.rs
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git --no-pager show :src/merge.rs
> git diff src/merge.rs
> git ls-files -- src/merge.rs
> git symbolic-ref --short HEAD
> git --no-pager show :src/merge.rs
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git diff src/merge.rs
> git symbolic-ref --short HEAD
> git ls-files -- src/merge.rs
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :src/merge.rs
> git diff src/merge.rs


## Output channel: snippets
[Info 11:22:28] Using ultisnips directories: UltiSnips /home/yago/.config/coc/ultisnips
[Info 11:22:28] Using ultisnips python command: pyx


## Output channel: Rust Analyzer Language Server Trace

```

## Describe the bug

Floating windows don't open anymore. If I try to go to the next diagnostic, or show information about a symbol, it just does nothing and fails silently. However, if I trigger auto-completion (auto-completion window shows up fine) and TAB on one symbol, which usually shows contextual information about this particular symbol in a floating window, then it fails explicitely with the following error message:

```
[coc.nvim]: UnhandledRejection: request error nvim_call_function - Vim:E117: Fonction inconnue : coc#util#create_float_win
Error: request error nvim_call_function - Vim:E117: Fonction inconnue : coc#util#create_float_win
    at /home/yago/.vim/bundle/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:40:32
    at /home/yago/.vim/bundle/coc.nvim/node_modules/@chemzqm/neovim/lib/transport/nvim.js:116:13
    at NvimTransport.parseMessage (/home/yago/.vim/bundle/coc.nvim/node_modules/@chemzqm/neovim/lib/transport/nvim.js:57:17)
    at DecodeStream.<anonymous> (/home/yago/.vim/bundle/coc.nvim/node_modules/@chemzqm/neovim/lib/transport/nvim.js:27:18)
    at DecodeStream.emit (events.js:314:20)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at DecodeStream.Readable.push (_stream_readable.js:214:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (/home/yago/.vim/bundle/coc.nvim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)
```
[**Note**: "Fonction inconnue" translates to "Unknown function"]
## Reproduce the bug

I'm using [coc-rust-analyzer](https://github.com/fannheyward/coc-rust-analyzer), but I also tested it with another language plugin [ocaml-lsp](https://github.com/ocaml/ocaml-lsp), and it happens too: I don't get the explicit error, but diagnostics and information on a specific symbol don't show up anymore. I can provide my full vimrc if necessary, but I don't really know how to trim it to a minimal example. So I guess:

1. Install a language server protocol (rust analyzer or ocaml lsp)
2. Type garbage in a source file to generate an error
3. Go to next diagnostic (`<Plug>(coc-diagnostic-next-error)`, and see that no floating window with the error appears, as it used to.

Alternative:

3. Show documentation (`:call show_documentation()`) on a symbol, the symbol is highlighted, but no information appear, as it used to.

## Screenshots (optional)

Triggering auto-completion (before the error):

![coc-nvim-before](https://user-images.githubusercontent.com/6530104/96571457-e08e1100-12cb-11eb-92e2-d09422c7b786.png)

TABbing on one specific entry causes the error:

![coc-nvim-after](https://user-images.githubusercontent.com/6530104/96571532-f996c200-12cb-11eb-8839-b18152f61f31.png)

**Comment by chemzqm** [comment]
You have latest vim code, but old javascript code, reinstall coc.nvim.
