### ISSUE TITLE
:CocStart Errors When in Deleted Folder

### ISSUE THREAD

**Issue by PhilRunninger** [neoclide/coc.nvim#2483]
## Result from CocInfo

`:CocInfo` fails when running the **Reproduce the bug** steps below:
```
coc.nvim service not started, checking environment...Service stopped for some unknown reason, try :CocStart
```

Under normal conditions, my `:CocInfo` produces the following:
```
## versions

vim version: NVIM v0.4.4
node version: v12.17.0
coc.nvim version: 0.0.79
coc.nvim directory: /Users/prunninger/.config/nvim/pack/bundle/opt/coc.nvim
term: iTerm.app
platform: darwin

## Output channel: explorer


## Output channel: snippets

[Info 9:05:40 AM] Using ultisnips directories: UltiSnips /Users/prunninger/.config/nvim/snippets
[Info 9:05:40 AM] Using ultisnips python command: pyx
```

## Describe the bug

`:CocStart` fails when Neovim is started from the command line in a directory that no longer exists. Admittedly, this is a very odd edge case. I discovered it when I deleted my shell's current working directory in Finder, and I started Neovim without `cd`ing to another directory.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

1. Create file `~/mini.vim` with：
    ```vim
    set nocompatible
    set runtimepath^=/path/to/coc.nvim
    filetype plugin indent on
    syntax on
    set hidden
    ```
1. Make a new folder and cd into it.
    ```
    ~ $ mkdir foo
    ~ $ cd foo
    ```
1. In another shell, remove the folder.
    ```
    ~/foo $ bash
    ~/foo $ cd ..
    ~ $ rmdir foo
    ~ $ exit
    ```
1. Start (neo)vim.
    ```
    ~/foo $ vim -u ~/mini.vim
    ```

Immediately, you will see the following error messages from the `:CocStart` command.
```
[coc.nvim]: internal/bootstrap/switches/does_own_process_state.js:128
  cachedCwd = rawMethods.cwd();
                         ^
Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:128:26)
    at process.cwd (/Users/prunninger/.config/nvim/pack/bundle/opt/coc.nvim/node_modules/graceful-fs/po
lyfills.js:10:19)
    at new Workspace (/Users/prunninger/.config/nvim/pack/bundle/opt/coc.nvim/lib/workspace.js:51:29)
    at Object.<anonymous> (/Users/prunninger/.config/nvim/pack/bundle/opt/coc.nvim/lib/workspace.js:184
3:19)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
Error on request (extensionStats): Vim(return):Error invoking 'extensionStats' on channel 3:
ch 3 was closed by the client
Press ENTER or type command to continue
Error detected while processing VimEnter Autocommands for "*":
E712: Argument of map() must be a List or Dictionary
```

**Comment by chemzqm** [comment]
It won't work when cwd is invalid.
