### ISSUE TITLE
ConnectionError: Connection is disposed - when updating plugins

### ISSUE THREAD

**Issue by mellery451** [neoclide/coc.nvim#2527]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-07fde6c39
node version: v15.0.1
coc.nvim version: 0.0.79-c330912985
coc.nvim directory: /home/mellery/.config/nvim/bundle/coc.nvim
term: tmux-256color
platform: linux

## Log of coc.nvim

2020-10-27T10:21:31.302 WARN (pid:25438) [attach] - Plugin not ready when received "registNotification" [ 'cquery', '$cquery/publishSemanticHighlighting' ]
2020-10-27T10:21:31.304 WARN (pid:25438) [attach] - Plugin not ready when received "registNotification" [ 'cquery', '$cquery/setInactiveRegions' ]
2020-10-27T10:21:31.304 WARN (pid:25438) [attach] - Plugin not ready when received "registNotification" [ 'ccls', '$ccls/publishSemanticHighlight' ]
2020-10-27T10:21:31.305 WARN (pid:25438) [attach] - Plugin not ready when received "registNotification" [ 'ccls', '$ccls/publishSkippedRanges' ]
2020-10-27T10:21:31.469 INFO (pid:25438) [services] - registered service "languageserver.dockerfile"
2020-10-27T10:21:31.478 INFO (pid:25438) [services] - registered service "highlight"
2020-10-27T10:21:31.504 INFO (pid:25438) [plugin] - coc.nvim 0.0.79-c330912985 initialized with node: v15.0.1 after 203ms
2020-10-27T10:21:31.510 INFO (pid:25438) [language-client-index] - highlight started with 25460
2020-10-27T10:21:37.094 INFO (pid:25438) [services] - registered service "json"
2020-10-27T10:21:37.095 INFO (pid:25438) [services] - Json language server state change: stopped => starting
2020-10-27T10:21:37.101 INFO (pid:25438) [services] - registered service "sh"
2020-10-27T10:21:37.101 INFO (pid:25438) [services] - bash-language-server state change: stopped => starting
2020-10-27T10:21:37.128 INFO (pid:25438) [language-client-index] - json started with 25581
2020-10-27T10:21:37.135 INFO (pid:25438) [language-client-index] - Language server "sh" started with 25582
2020-10-27T10:21:37.202 INFO (pid:25438) [services] - Json language server state change: starting => running
2020-10-27T10:21:37.204 INFO (pid:25438) [services] - service json started
2020-10-27T10:21:45.063 INFO (pid:25438) [services] - bash-language-server state change: starting => running
2020-10-27T10:21:45.064 INFO (pid:25438) [services] - service sh started
```

## Describe the bug

Whenever I update my plugins (using PlugUpdate from vim-plug), I get a "ConnectionError: Connection is disposed" error from coc.nvim (see screenshot below for stacktrace)

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim
" this bootstraps/installs vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/bundle')

Plug 'clangd/coc-clangd', {'do': 'yarn install --frozen-lockfile'}
Plug 'voldikss/coc-cmake', {'do': 'yarn install --frozen-lockfile'}
Plug 'neoclide/coc-highlight', {'do': 'yarn install --frozen-lockfile'}
Plug 'neoclide/coc-json', {'do': 'yarn install --frozen-lockfile'}
Plug 'neoclide/coc-python', {'do': 'yarn install --frozen-lockfile'}
Plug 'neoclide/coc-tsserver', {'do': 'yarn install --frozen-lockfile'}
Plug 'josa42/coc-sh', {'do': 'yarn install --frozen-lockfile'}
Plug 'neoclide/coc-snippets', {'do': 'yarn install --frozen-lockfile'}
Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

filetype on
filetype plugin on
filetype indent on

syntax on
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

- run `:PlugInstall` and then `:PlugUpdate`

## Screenshots (optional)

![Screen Shot 2020-10-27 at 10 20 44 AM](https://user-images.githubusercontent.com/463430/97338895-22c0d080-183f-11eb-9930-856df40f40eb.png)

**Comment by esetnik** [comment]
@chemzqm I still have the same issue in the latest master.

```
[coc.nvim]: ConnectionError: Connection is disposed.
    at throwIfClosedOrDisposed (/Users/ethan/.vim/plugged/coc.nvim/node_modules/vscode-jsonrpc/lib/main.js:677:19)
    at Object.sendNotification (/Users/ethan/.vim/plugged/coc.nvim/node_modules/vscode-jsonrpc/lib/main.js:724:13)
    at /Users/ethan/.vim/plugged/coc.nvim/node_modules/vscode-jsonrpc/lib/main.js:851:32
    at CallbackList.invoke (/Users/ethan/.vim/plugged/coc.nvim/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/Users/ethan/.vim/plugged/coc.nvim/node_modules/vscode-jsonrpc/lib/events.js:121:36)
    at MutableToken.cancel (/Users/ethan/.vim/plugged/coc.nvim/node_modules/vscode-jsonrpc/lib/cancellation.js:39:31)
    at CancellationTokenSource.cancel (/Users/ethan/.vim/plugged/coc.nvim/node_modules/vscode-jsonrpc/lib/cancellation.js:80:25)
    at Highlighter.cancel (/Users/ethan/.vim/plugged/coc.nvim/lib/handler/highlighter.js:138:30)
    at Highlighter.doHighlight (/Users/ethan/.vim/plugged/coc.nvim/lib/handler/highlighter.js:42:18)
    at Highlighter.<anonymous> (/Users/ethan/.vim/plugged/coc.nvim/lib/handler/highlighter.js:23:18)
    at Timeout.later [as _onTimeout] (/Users/ethan/.vim/plugged/coc.nvim/node_modules/debounce/index.js:27:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 2
}
Press ENTER or type command to continue
```

**Comment by chemzqm** [comment]
Remove autocmd for highlight in your vimrc, or simply ignore it.

**Comment by james1236** [comment]
This might fix it: https://github.com/neoclide/coc-java/issues/99#issuecomment-663856695
