### ISSUE TITLE
Plugins updater breaks and cannot install any plugin

### ISSUE THREAD

**Issue by ecosse3** [neoclide/coc.nvim#2580]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-nightly
node version: v14.8.0
coc.nvim version: 0.0.79
coc.nvim directory: /Users/lukasz.kurpiewski/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2020-11-09T14:03:15.177 WARN (pid:59366) [attach] - Plugin not ready when received "documentSymbols" []
2020-11-09T14:03:15.186 ERROR (pid:59366) [attach] - Request error: documentSymbols [] TypeError: Cannot read property 'getDocumentSymbols' of undefined
    at /Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/plugin.js:270:39
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Plugin.cocAction (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/plugin.js:456:16)
    at async NeovimClient.<anonymous> (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/attach.js:93:27)
2020-11-09T14:03:15.266 INFO (pid:59366) [plugin] - coc.nvim 0.0.79 initialized with node: v14.8.0 after 78ms
2020-11-09T14:03:15.294 INFO (pid:59366) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-09T14:03:15.309 INFO (pid:59366) [model-installer] - Get info from https://registry.npmjs.org/
2020-11-09T14:03:15.328 INFO (pid:59366) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-09T14:03:15.328 INFO (pid:59366) [model-installer] - Get info from https://registry.npmjs.org/
2020-11-09T14:03:15.329 INFO (pid:59366) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-09T14:03:15.330 INFO (pid:59366) [model-installer] - Get info from https://registry.npmjs.org/
2020-11-09T14:03:15.455 INFO (pid:59366) [model-installer] - Fetched info of coc-json {
  'dist.tarball': 'https://registry.npmjs.org/coc-json/-/coc-json-1.3.2.tgz',
  'engines.coc': '>= 0.0.79',
  version: '1.3.2',
  name: 'coc-json'
}
2020-11-09T14:03:15.458 INFO (pid:59366) [model-installer] - Downloading from https://registry.npmjs.org/coc-json/-/coc-json-1.3.2.tgz
2020-11-09T14:03:15.489 INFO (pid:59366) [model-installer] - Fetched info of coc-explorer {
  'dist.tarball': 'https://registry.npmjs.org/coc-explorer/-/coc-explorer-0.10.0.tgz',
  'engines.coc': '^0.0.75',
  version: '0.10.0',
  name: 'coc-explorer'
}
2020-11-09T14:03:15.491 INFO (pid:59366) [model-installer] - Downloading from https://registry.npmjs.org/coc-explorer/-/coc-explorer-0.10.0.tgz
2020-11-09T14:03:15.580 INFO (pid:59366) [model-installer] - Download progress 100.0%
2020-11-09T14:03:15.581 INFO (pid:59366) [model-download] - Download completed: https://registry.npmjs.org/coc-json/-/coc-json-1.3.2.tgz
2020-11-09T14:03:15.582 INFO (pid:59366) [model-download] - Downloaded https://registry.npmjs.org/coc-json/-/coc-json-1.3.2.tgz => /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-json-Fita09
2020-11-09T14:03:15.615 INFO (pid:59366) [model-installer] - Download progress 100.0%
2020-11-09T14:03:15.617 INFO (pid:59366) [model-download] - Download completed: https://registry.npmjs.org/coc-explorer/-/coc-explorer-0.10.0.tgz
2020-11-09T14:03:15.618 INFO (pid:59366) [model-download] - Downloaded https://registry.npmjs.org/coc-explorer/-/coc-explorer-0.10.0.tgz => /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-explorer-19sAzy
2020-11-09T14:03:15.687 INFO (pid:59366) [model-installer] - Extension download at /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-json-Fita09
2020-11-09T14:03:15.706 ERROR (pid:59366) [extensions] - Error on install coc-json SyntaxError: Unexpected token } in JSON at position 463
    at JSON.parse (<anonymous>)
    at Installer.doInstall (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:147:24)
    at async Installer.install (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:56:9)
2020-11-09T14:03:15.706 INFO (pid:59366) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-09T14:03:15.707 INFO (pid:59366) [model-installer] - Get info from https://registry.npmjs.org/
2020-11-09T14:03:15.721 INFO (pid:59366) [model-installer] - Extension download at /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-explorer-19sAzy
2020-11-09T14:03:15.723 INFO (pid:59366) [model-installer] - Installing dependencies by: /usr/local/bin/npm install --ignore-scripts --no-lockfile --production --legacy-peer-deps.
2020-11-09T14:03:15.780 INFO (pid:59366) [model-installer] - Fetched info of coc-tslint-plugin {
  'dist.tarball': 'https://registry.npmjs.org/coc-tslint-plugin/-/coc-tslint-plugin-1.1.1.tgz',
  'engines.coc': '^0.0.64',
  version: '1.1.1',
  name: 'coc-tslint-plugin'
}
2020-11-09T14:03:15.780 INFO (pid:59366) [model-installer] - Downloading from https://registry.npmjs.org/coc-tslint-plugin/-/coc-tslint-plugin-1.1.1.tgz
2020-11-09T14:03:15.864 INFO (pid:59366) [model-installer] - Download progress 100.0%
2020-11-09T14:03:15.865 INFO (pid:59366) [model-download] - Download completed: https://registry.npmjs.org/coc-tslint-plugin/-/coc-tslint-plugin-1.1.1.tgz
2020-11-09T14:03:15.865 INFO (pid:59366) [model-download] - Downloaded https://registry.npmjs.org/coc-tslint-plugin/-/coc-tslint-plugin-1.1.1.tgz => /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-tslint-plugin-fxILhR
2020-11-09T14:03:15.965 INFO (pid:59366) [model-installer] - Extension download at /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-tslint-plugin-fxILhR
2020-11-09T14:03:15.966 INFO (pid:59366) [model-installer] - Installing dependencies by: /usr/local/bin/npm install --ignore-scripts --no-lockfile --production --legacy-peer-deps.
2020-11-09T14:03:16.377 INFO (pid:59366) [model-installer] - Fetched info of coc-tsserver {
  'dist.tarball': 'https://registry.npmjs.org/coc-tsserver/-/coc-tsserver-1.6.0.tgz',
  'engines.coc': '^0.0.78',
  version: '1.6.0',
  name: 'coc-tsserver'
}
2020-11-09T14:03:16.378 INFO (pid:59366) [model-installer] - Downloading from https://registry.npmjs.org/coc-tsserver/-/coc-tsserver-1.6.0.tgz
2020-11-09T14:03:16.774 INFO (pid:59366) [model-installer] - Download progress 100.0%
2020-11-09T14:03:16.774 INFO (pid:59366) [model-download] - Download completed: https://registry.npmjs.org/coc-tsserver/-/coc-tsserver-1.6.0.tgz
2020-11-09T14:03:16.775 INFO (pid:59366) [model-download] - Downloaded https://registry.npmjs.org/coc-tsserver/-/coc-tsserver-1.6.0.tgz => /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-tsserver-FvW37v
2020-11-09T14:03:16.878 INFO (pid:59366) [model-installer] - Extension download at /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-tsserver-FvW37v
2020-11-09T14:03:16.878 INFO (pid:59366) [model-installer] - Installing dependencies by: /usr/local/bin/npm install --ignore-scripts --no-lockfile --production --legacy-peer-deps.
2020-11-09T14:03:23.573 INFO (pid:59366) [model-installer] - [npm] added 14 packages from 11 contributors and audited 488 packages in 6.862s
2020-11-09T14:03:23.762 INFO (pid:59366) [model-installer] - [npm] found 0 vulnerabilities
2020-11-09T14:03:23.762 INFO (pid:59366) [model-installer] - [npm] 
2020-11-09T14:03:23.819 ERROR (pid:59366) [extensions] - Error on install coc-tslint-plugin SyntaxError: Unexpected token } in JSON at position 463
    at JSON.parse (<anonymous>)
    at Installer.doInstall (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:147:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Installer.install (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:56:9)
2020-11-09T14:03:23.819 INFO (pid:59366) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-09T14:03:23.820 INFO (pid:59366) [model-installer] - Get info from https://registry.npmjs.org/
2020-11-09T14:03:23.910 INFO (pid:59366) [model-installer] - Fetched info of coc-eslint {
  'dist.tarball': 'https://registry.npmjs.org/coc-eslint/-/coc-eslint-1.3.2.tgz',
  'engines.coc': '^0.0.64',
  version: '1.3.2',
  name: 'coc-eslint'
}
2020-11-09T14:03:23.911 INFO (pid:59366) [model-installer] - Downloading from https://registry.npmjs.org/coc-eslint/-/coc-eslint-1.3.2.tgz
2020-11-09T14:03:24.008 INFO (pid:59366) [model-installer] - Download progress 100.0%
2020-11-09T14:03:24.008 INFO (pid:59366) [model-download] - Download completed: https://registry.npmjs.org/coc-eslint/-/coc-eslint-1.3.2.tgz
2020-11-09T14:03:24.009 INFO (pid:59366) [model-download] - Downloaded https://registry.npmjs.org/coc-eslint/-/coc-eslint-1.3.2.tgz => /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-eslint-YD4AN3
2020-11-09T14:03:24.113 INFO (pid:59366) [model-installer] - Extension download at /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-eslint-YD4AN3
2020-11-09T14:03:24.114 ERROR (pid:59366) [extensions] - Error on install coc-eslint SyntaxError: Unexpected token } in JSON at position 463
    at JSON.parse (<anonymous>)
    at Installer.doInstall (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:147:24)
    at async Installer.install (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:56:9)
2020-11-09T14:03:24.114 INFO (pid:59366) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-09T14:03:24.115 INFO (pid:59366) [model-installer] - Get info from https://registry.npmjs.org/
2020-11-09T14:03:24.203 INFO (pid:59366) [model-installer] - Fetched info of coc-emmet {
  'dist.tarball': 'https://registry.npmjs.org/coc-emmet/-/coc-emmet-1.1.6.tgz',
  'engines.coc': '^0.0.29',
  version: '1.1.6',
  name: 'coc-emmet'
}
2020-11-09T14:03:24.204 INFO (pid:59366) [model-installer] - Downloading from https://registry.npmjs.org/coc-emmet/-/coc-emmet-1.1.6.tgz
2020-11-09T14:03:24.278 INFO (pid:59366) [model-installer] - Download progress 100.0%
2020-11-09T14:03:24.278 INFO (pid:59366) [model-download] - Download completed: https://registry.npmjs.org/coc-emmet/-/coc-emmet-1.1.6.tgz
2020-11-09T14:03:24.279 INFO (pid:59366) [model-download] - Downloaded https://registry.npmjs.org/coc-emmet/-/coc-emmet-1.1.6.tgz => /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-emmet-D15Isa
2020-11-09T14:03:24.381 INFO (pid:59366) [model-installer] - Extension download at /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-emmet-D15Isa
2020-11-09T14:03:24.382 INFO (pid:59366) [model-installer] - Installing dependencies by: /usr/local/bin/npm install --ignore-scripts --no-lockfile --production --legacy-peer-deps.
2020-11-09T14:03:24.733 INFO (pid:59366) [model-installer] - [npm] added 1 package from 1 contributor and audited 481 packages in 7.094s
2020-11-09T14:03:24.859 INFO (pid:59366) [model-installer] - [npm] found 0 vulnerabilities
2020-11-09T14:03:24.860 INFO (pid:59366) [model-installer] - [npm] 
2020-11-09T14:03:24.921 ERROR (pid:59366) [extensions] - Error on install coc-tsserver SyntaxError: Unexpected token } in JSON at position 463
    at JSON.parse (<anonymous>)
    at Installer.doInstall (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:147:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Installer.install (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:56:9)
2020-11-09T14:03:24.921 INFO (pid:59366) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-09T14:03:24.922 INFO (pid:59366) [model-installer] - Get info from https://registry.npmjs.org/
2020-11-09T14:03:25.024 INFO (pid:59366) [model-installer] - Fetched info of coc-prettier {
  'dist.tarball': 'https://registry.npmjs.org/coc-prettier/-/coc-prettier-1.1.18.tgz',
  'engines.coc': '>= 0.0.30',
  version: '1.1.18',
  name: 'coc-prettier'
}
2020-11-09T14:03:25.024 INFO (pid:59366) [model-installer] - Downloading from https://registry.npmjs.org/coc-prettier/-/coc-prettier-1.1.18.tgz
2020-11-09T14:03:25.137 INFO (pid:59366) [model-installer] - Download progress 100.0%
2020-11-09T14:03:25.137 INFO (pid:59366) [model-download] - Download completed: https://registry.npmjs.org/coc-prettier/-/coc-prettier-1.1.18.tgz
2020-11-09T14:03:25.138 INFO (pid:59366) [model-download] - Downloaded https://registry.npmjs.org/coc-prettier/-/coc-prettier-1.1.18.tgz => /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-prettier-4hXWxN
2020-11-09T14:03:25.239 INFO (pid:59366) [model-installer] - Extension download at /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-prettier-4hXWxN
2020-11-09T14:03:25.255 INFO (pid:59366) [model-installer] - Installing dependencies by: /usr/local/bin/npm install --ignore-scripts --no-lockfile --production --legacy-peer-deps.
2020-11-09T14:03:29.726 INFO (pid:59366) [model-installer] - [npm] added 64 packages from 17 contributors and audited 1089 packages in 13.246s
2020-11-09T14:03:30.062 INFO (pid:59366) [model-installer] - [npm] 
2020-11-09T14:03:30.062 INFO (pid:59366) [model-installer] - [npm] 5 packages are looking for funding
2020-11-09T14:03:30.062 INFO (pid:59366) [model-installer] - [npm]   run `npm fund` for details
2020-11-09T14:03:30.062 INFO (pid:59366) [model-installer] - [npm] 
2020-11-09T14:03:30.063 INFO (pid:59366) [model-installer] - [npm] found 0 vulnerabilities
2020-11-09T14:03:30.063 INFO (pid:59366) [model-installer] - [npm] 
2020-11-09T14:03:30.124 ERROR (pid:59366) [extensions] - Error on install coc-explorer SyntaxError: Unexpected token } in JSON at position 463
    at JSON.parse (<anonymous>)
    at Installer.doInstall (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:147:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Installer.install (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:56:9)
2020-11-09T14:03:30.125 INFO (pid:59366) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-09T14:03:30.125 INFO (pid:59366) [model-installer] - Get info from https://registry.npmjs.org/
2020-11-09T14:03:30.220 INFO (pid:59366) [model-installer] - Fetched info of coc-angular {
  'dist.tarball': 'https://registry.npmjs.org/coc-angular/-/coc-angular-0.1000.7.tgz',
  'engines.coc': '^0.0.74',
  version: '0.1000.7',
  name: 'coc-angular'
}
2020-11-09T14:03:30.221 INFO (pid:59366) [model-installer] - Downloading from https://registry.npmjs.org/coc-angular/-/coc-angular-0.1000.7.tgz
2020-11-09T14:03:30.287 INFO (pid:59366) [model-installer] - Download progress 100.0%
2020-11-09T14:03:30.287 INFO (pid:59366) [model-download] - Download completed: https://registry.npmjs.org/coc-angular/-/coc-angular-0.1000.7.tgz
2020-11-09T14:03:30.289 INFO (pid:59366) [model-download] - Downloaded https://registry.npmjs.org/coc-angular/-/coc-angular-0.1000.7.tgz => /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-angular-HuctVP
2020-11-09T14:03:30.391 INFO (pid:59366) [model-installer] - Extension download at /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-angular-HuctVP
2020-11-09T14:03:30.405 INFO (pid:59366) [model-installer] - Installing dependencies by: /usr/local/bin/npm install --ignore-scripts --no-lockfile --production --legacy-peer-deps.
2020-11-09T14:03:33.027 INFO (pid:59366) [model-installer] - [npm] added 4 packages from 2 contributors and audited 489 packages in 7.854s
2020-11-09T14:03:33.146 INFO (pid:59366) [model-installer] - [npm] found 0 vulnerabilities
2020-11-09T14:03:33.146 INFO (pid:59366) [model-installer] - [npm] 
2020-11-09T14:03:33.205 ERROR (pid:59366) [extensions] - Error on install coc-emmet SyntaxError: Unexpected token } in JSON at position 463
    at JSON.parse (<anonymous>)
    at Installer.doInstall (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:147:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Installer.install (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:56:9)
2020-11-09T14:03:33.206 INFO (pid:59366) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-09T14:03:33.207 INFO (pid:59366) [model-installer] - Get info from https://registry.npmjs.org/
2020-11-09T14:03:33.299 INFO (pid:59366) [model-installer] - Fetched info of coc-snippets {
  'dist.tarball': 'https://registry.npmjs.org/coc-snippets/-/coc-snippets-2.2.5.tgz',
  'engines.coc': '^0.0.61',
  version: '2.2.5',
  name: 'coc-snippets'
}
2020-11-09T14:03:33.299 INFO (pid:59366) [model-installer] - Downloading from https://registry.npmjs.org/coc-snippets/-/coc-snippets-2.2.5.tgz
2020-11-09T14:03:33.429 INFO (pid:59366) [model-installer] - Download progress 100.0%
2020-11-09T14:03:33.429 INFO (pid:59366) [model-download] - Download completed: https://registry.npmjs.org/coc-snippets/-/coc-snippets-2.2.5.tgz
2020-11-09T14:03:33.430 INFO (pid:59366) [model-download] - Downloaded https://registry.npmjs.org/coc-snippets/-/coc-snippets-2.2.5.tgz => /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-snippets-QuzaYK
2020-11-09T14:03:33.533 INFO (pid:59366) [model-installer] - Extension download at /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-snippets-QuzaYK
2020-11-09T14:03:33.533 ERROR (pid:59366) [extensions] - Error on install coc-snippets SyntaxError: Unexpected token } in JSON at position 463
    at JSON.parse (<anonymous>)
    at Installer.doInstall (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:147:24)
    at async Installer.install (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:56:9)
2020-11-09T14:03:33.534 INFO (pid:59366) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-09T14:03:33.534 INFO (pid:59366) [model-installer] - Get info from https://registry.npmjs.org/
2020-11-09T14:03:33.614 INFO (pid:59366) [model-installer] - Fetched info of coc-styled-components {
  'dist.tarball': 'https://registry.npmjs.org/coc-styled-components/-/coc-styled-components-0.3.0.tgz',
  'engines.coc': '^0.0.70',
  version: '0.3.0',
  name: 'coc-styled-components'
}
2020-11-09T14:03:33.615 INFO (pid:59366) [model-installer] - Downloading from https://registry.npmjs.org/coc-styled-components/-/coc-styled-components-0.3.0.tgz
2020-11-09T14:03:33.698 INFO (pid:59366) [model-installer] - Download progress 100.0%
2020-11-09T14:03:33.698 INFO (pid:59366) [model-download] - Download completed: https://registry.npmjs.org/coc-styled-components/-/coc-styled-components-0.3.0.tgz
2020-11-09T14:03:33.698 INFO (pid:59366) [model-download] - Downloaded https://registry.npmjs.org/coc-styled-components/-/coc-styled-components-0.3.0.tgz => /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-styled-components-HJoa29
2020-11-09T14:03:33.804 INFO (pid:59366) [model-installer] - Extension download at /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-styled-components-HJoa29
2020-11-09T14:03:33.805 INFO (pid:59366) [model-installer] - Installing dependencies by: /usr/local/bin/npm install --ignore-scripts --no-lockfile --production --legacy-peer-deps.
2020-11-09T14:03:38.970 INFO (pid:59366) [model-installer] - [npm] added 8 packages from 5 contributors and audited 473 packages in 7.788s
2020-11-09T14:03:39.102 INFO (pid:59366) [model-installer] - [npm] found 0 vulnerabilities
2020-11-09T14:03:39.103 INFO (pid:59366) [model-installer] - [npm] 
2020-11-09T14:03:39.155 ERROR (pid:59366) [extensions] - Error on install coc-angular SyntaxError: Unexpected token } in JSON at position 463
    at JSON.parse (<anonymous>)
    at Installer.doInstall (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:147:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Installer.install (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:56:9)
2020-11-09T14:03:39.155 INFO (pid:59366) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-09T14:03:39.156 INFO (pid:59366) [model-installer] - Get info from https://registry.npmjs.org/
2020-11-09T14:03:39.254 INFO (pid:59366) [model-installer] - Fetched info of coc-css {
  'dist.tarball': 'https://registry.npmjs.org/coc-css/-/coc-css-1.2.6.tgz',
  'engines.coc': '^0.0.78',
  version: '1.2.6',
  name: 'coc-css'
}
2020-11-09T14:03:39.254 INFO (pid:59366) [model-installer] - Downloading from https://registry.npmjs.org/coc-css/-/coc-css-1.2.6.tgz
2020-11-09T14:03:39.356 INFO (pid:59366) [model-installer] - Download progress 100.0%
2020-11-09T14:03:39.357 INFO (pid:59366) [model-download] - Download completed: https://registry.npmjs.org/coc-css/-/coc-css-1.2.6.tgz
2020-11-09T14:03:39.358 INFO (pid:59366) [model-download] - Downloaded https://registry.npmjs.org/coc-css/-/coc-css-1.2.6.tgz => /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-css-qM4jnT
2020-11-09T14:03:39.458 INFO (pid:59366) [model-installer] - Extension download at /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-css-qM4jnT
2020-11-09T14:03:39.459 ERROR (pid:59366) [extensions] - Error on install coc-css SyntaxError: Unexpected token } in JSON at position 463
    at JSON.parse (<anonymous>)
    at Installer.doInstall (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:147:24)
    at async Installer.install (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:56:9)
2020-11-09T14:03:39.459 INFO (pid:59366) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-09T14:03:39.460 INFO (pid:59366) [model-installer] - Get info from https://registry.npmjs.org/
2020-11-09T14:03:39.525 INFO (pid:59366) [model-installer] - Fetched info of coc-html {
  'dist.tarball': 'https://registry.npmjs.org/coc-html/-/coc-html-1.3.1.tgz',
  'engines.coc': '^0.0.15',
  version: '1.3.1',
  name: 'coc-html'
}
2020-11-09T14:03:39.526 INFO (pid:59366) [model-installer] - Downloading from https://registry.npmjs.org/coc-html/-/coc-html-1.3.1.tgz
2020-11-09T14:03:39.679 INFO (pid:59366) [model-installer] - Download progress 100.0%
2020-11-09T14:03:39.680 INFO (pid:59366) [model-download] - Download completed: https://registry.npmjs.org/coc-html/-/coc-html-1.3.1.tgz
2020-11-09T14:03:39.680 INFO (pid:59366) [model-download] - Downloaded https://registry.npmjs.org/coc-html/-/coc-html-1.3.1.tgz => /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-html-pjpuZg
2020-11-09T14:03:39.784 INFO (pid:59366) [model-installer] - Extension download at /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-html-pjpuZg
2020-11-09T14:03:39.784 INFO (pid:59366) [model-installer] - Installing dependencies by: /usr/local/bin/npm install --ignore-scripts --no-lockfile --production --legacy-peer-deps.
2020-11-09T14:03:41.544 INFO (pid:59366) [model-installer] - [npm] added 668 packages from 421 contributors and audited 897 packages in 15.455s
2020-11-09T14:03:41.741 INFO (pid:59366) [model-installer] - [npm] 
2020-11-09T14:03:41.741 INFO (pid:59366) [model-installer] - [npm] 50 packages are looking for funding
2020-11-09T14:03:41.741 INFO (pid:59366) [model-installer] - [npm]   run `npm fund` for details
2020-11-09T14:03:41.741 INFO (pid:59366) [model-installer] - [npm] 
2020-11-09T14:03:41.741 INFO (pid:59366) [model-installer] - [npm] found 2 low severity vulnerabilities
2020-11-09T14:03:41.741 INFO (pid:59366) [model-installer] - [npm]   run `npm audit fix` to fix them, or `npm audit` for details
2020-11-09T14:03:41.805 ERROR (pid:59366) [extensions] - Error on install coc-prettier SyntaxError: Unexpected token } in JSON at position 463
    at JSON.parse (<anonymous>)
    at Installer.doInstall (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:147:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Installer.install (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:56:9)
2020-11-09T14:03:41.805 INFO (pid:59366) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-09T14:03:41.806 INFO (pid:59366) [model-installer] - Get info from https://registry.npmjs.org/
2020-11-09T14:03:41.816 INFO (pid:59366) [model-installer] - [npm] added 11 packages from 3 contributors and audited 480 packages in 6.956s
2020-11-09T14:03:41.882 INFO (pid:59366) [model-installer] - Fetched info of coc-ultisnips {
  'dist.tarball': 'https://registry.npmjs.org/coc-ultisnips/-/coc-ultisnips-1.2.3.tgz',
  'engines.coc': '>=0.0.57',
  version: '1.2.3',
  name: 'coc-ultisnips'
}
2020-11-09T14:03:41.882 INFO (pid:59366) [model-installer] - Downloading from https://registry.npmjs.org/coc-ultisnips/-/coc-ultisnips-1.2.3.tgz
2020-11-09T14:03:41.938 INFO (pid:59366) [model-installer] - [npm] found 0 vulnerabilities
2020-11-09T14:03:41.939 INFO (pid:59366) [model-installer] - [npm] 
2020-11-09T14:03:41.980 ERROR (pid:59366) [extensions] - Error on install coc-styled-components SyntaxError: Unexpected token } in JSON at position 463
    at JSON.parse (<anonymous>)
    at Installer.doInstall (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:147:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Installer.install (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:56:9)
2020-11-09T14:03:42.043 INFO (pid:59366) [model-installer] - Download progress 53.1%
2020-11-09T14:03:42.043 INFO (pid:59366) [model-installer] - Download progress 100.0%
2020-11-09T14:03:42.044 INFO (pid:59366) [model-download] - Download completed: https://registry.npmjs.org/coc-ultisnips/-/coc-ultisnips-1.2.3.tgz
2020-11-09T14:03:42.044 INFO (pid:59366) [model-download] - Downloaded https://registry.npmjs.org/coc-ultisnips/-/coc-ultisnips-1.2.3.tgz => /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-ultisnips-mGJIBn
2020-11-09T14:03:42.146 INFO (pid:59366) [model-installer] - Extension download at /var/folders/0y/kv46mbw534q4q_xhy05tbbnr0000gn/T/nvimFdgr6f/coc-ultisnips-mGJIBn
2020-11-09T14:03:42.156 ERROR (pid:59366) [extensions] - Error on install coc-ultisnips SyntaxError: Unexpected token } in JSON at position 463
    at JSON.parse (<anonymous>)
    at Installer.doInstall (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:147:24)
    at async Installer.install (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:56:9)
2020-11-09T14:03:45.208 INFO (pid:59366) [model-installer] - [npm] added 1 package from 1 contributor and audited 289 packages in 4.484s
2020-11-09T14:03:45.277 INFO (pid:59366) [model-installer] - [npm] found 0 vulnerabilities
2020-11-09T14:03:45.277 INFO (pid:59366) [model-installer] - [npm] 
2020-11-09T14:03:45.305 ERROR (pid:59366) [extensions] - Error on install coc-html SyntaxError: Unexpected token } in JSON at position 463
    at JSON.parse (<anonymous>)
    at Installer.doInstall (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:147:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Installer.install (/Users/lukasz.kurpiewski/.vim/plugged/coc.nvim/lib/model/installer.js:56:9)
```

## Describe the bug

After last update of coc (with :PlugUpdate) when coc tried to automatically update plugins it breaks and any of plugins doesn't work. CocUpdate breaks too. Tried to change coc.nvim with release branch and crashes too.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

Done.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/17691791/98544895-ece70780-2294-11eb-8d5d-cbb6256590b4.png)

**Comment by chemzqm** [comment]
Check the file `echo coc#util#extension_root()."/package.json"`
