### ISSUE TITLE
Vim(let):E5555: API call: 'width' key must be a positive Integer Error

### ISSUE THREAD

**Issue by niceloaf** [neoclide/coc.nvim#2581]
### versions

vim version: NVIM v0.4.4
node version: v14.14.0
coc.nvim version: 0.0.79-bd91ae4254
coc.nvim directory: /home/lunz/.config/nvim/installed/coc.nvim
term: xterm-kitty
platform: linux

### Log of coc.nvim

2020-11-10T09:03:37.410 INFO (pid:12241) [plugin] - coc.nvim 0.0.79-bd91ae4254 initialized with node: v14.14.0 after 166ms
2020-11-10T09:03:47.620 INFO (pid:12241) [completion-complete] - Results from: around
2020-11-10T09:03:49.811 INFO (pid:12241) [completion-complete] - Results from: around,OmniSharp
2020-11-10T09:03:50.214 ERROR (pid:12241) [node-client] - request error on "nvim_call_function" [
  'coc#float#create_pum_float',
  [
    0,
    0,
    [],
    { codes: [], highlights: [], maxWidth: 80, pumbounding: [Object] }
  ]
] Vim(let):E5555: API call: 'width' key must be a positive Integer Error
    at NeovimClient.request (/home/lunz/.config/nvim/installed/coc.nvim/build/index.js:15462:21)
    at NeovimClient.call (/home/lunz/.config/nvim/installed/coc.nvim/build/index.js:16333:21)
    at Floating.showDocumentationFloating (/home/lunz/.config/nvim/installed/coc.nvim/build/index.js:92449:30)
    at Floating.show (/home/lunz/.config/nvim/installed/coc.nvim/build/index.js:92443:20)
    at Completion.onPumChange (/home/lunz/.config/nvim/installed/coc.nvim/build/index.js:47763:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-11-10T09:03:50.218 ERROR (pid:12241) [server] - unhandledRejection  Promise {
  <rejected> Error
      at NeovimClient.request (/home/lunz/.config/nvim/installed/coc.nvim/build/index.js:15462:21)
      at NeovimClient.call (/home/lunz/.config/nvim/installed/coc.nvim/build/index.js:16333:21)
      at Floating.showDocumentationFloating (/home/lunz/.config/nvim/installed/coc.nvim/build/index.js:92449:30)
      at Floating.show (/home/lunz/.config/nvim/installed/coc.nvim/build/index.js:92443:20)
      at Completion.onPumChange (/home/lunz/.config/nvim/installed/coc.nvim/build/index.js:47763:33)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
} Error
    at NeovimClient.request (/home/lunz/.config/nvim/installed/coc.nvim/build/index.js:15462:21)
    at NeovimClient.call (/home/lunz/.config/nvim/installed/coc.nvim/build/index.js:16333:21)
    at Floating.showDocumentationFloating (/home/lunz/.config/nvim/installed/coc.nvim/build/index.js:92449:30)
    at Floating.show (/home/lunz/.config/nvim/installed/coc.nvim/build/index.js:92443:20)
    at Completion.onPumChange (/home/lunz/.config/nvim/installed/coc.nvim/build/index.js:47763:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

## Describe the bug

Whenever the completion selects an entry, this error pops up . Which is really weird because this seems to happen on .cs files. I have found a somewhat [similar issue](https://github.com/neoclide/coc.nvim/issues/1934) regarding this. This time, it's the width.

## Reproduce the bug

- [Simple config, put it in your .config folder](https://filebin.net/agp2r292r084s2t8)
- Run :PlugInstall
- Open a .cs file, select yes to install omnisharp server
- Restart neovim
- Wait for the server to load
- Write ```using```(test puposes), then select any entry by tabbing or arrow keys

## Screenshots (optional)
My normal neovim setup

![setup.jpg](https://i.imgur.com/K8hIeVQ.png)

**Comment by niceloaf** [comment]
Haha close issue even though it hasnt been fixed yet go BRRRRRRRRRRRRRRRRR

**Comment by niceloaf** [comment]
Can confirm, the bug is still there. Do I have to compile coc?

**Comment by chemzqm** [comment]
Please provide the value of pumbounding

**Comment by niceloaf** [comment]
Here:
9:04:07 AM DEBUG [transport] - request to nvim: 22,nvim_call_function,[
  "coc#float#create_pum_float",
  [
    0,
    0,
    [],
    {
      "codes": [],
      "highlights": [],
      "maxWidth": 80,
      "pumbounding": {
        "col": 38,
        "row": 2,
        "height": 6,
        "width": 25,
        "scrollbar": false
      }
    }
  ]
]
9:04:07 AM DEBUG [transport] - response of nvim: 22,6ms,null,[
  0,
  "Vim(let):E5555: API call: 'width' key must be a positive Integer"
]
9:04:07 AM DEBUG [transport] - receive notification: [
  "nvim_buf_lines_event",
  [
    "[nvim_buf_1]",
    12,
    0,
    1,
    [
      "uin"
    ],
    false
  ]
]

**Comment by chemzqm** [comment]
Fixed
