### ISSUE TITLE
CocYank/request error on "nvim_buf_set_lines"

### ISSUE THREAD

**Issue by Dav1dch** [neoclide/coc.nvim#2587]
## versions
```
vim version: NVIM v0.5.0-812-gd17e50879
node version: v15.0.1
coc.nvim version: 0.0.79-bd91ae4254
coc.nvim directory: /home/david/.local/share/nvim/plugged/coc.nvim
term: st-256color
platform: linux

## Log of coc.nvim

2020-11-11T14:10:40.137 INFO (pid:111621) [services] - registered service "eslint"
2020-11-11T14:10:40.578 INFO (pid:111621) [plugin] - coc.nvim 0.0.79-bd91ae4254 initialized with node: v15.0.1 after 578ms
2020-11-11T14:10:43.482 ERROR (pid:111621) [node-client] - request error on "nvim_buf_set_lines" [ 0, 0, false, [ 'request error on "nvim_buf_set_lines"' ] ] Invalid buffer id: 3 Error
    at Buffer.request (/home/david/.local/share/nvim/plugged/coc.nvim/build/index.js:15462:21)
    at Buffer.setLines (/home/david/.local/share/nvim/plugged/coc.nvim/build/index.js:15247:28)
    at Document.applyEdits (/home/david/.local/share/nvim/plugged/coc.nvim/build/index.js:41328:31)
    at YankList.<anonymous> (/home/david/.config/coc/extensions/node_modules/coc-yank/lib/index.js:2130:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/david/.config/coc/extensions/node_modules/coc-yank/lib/index.js:2078:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
2020-11-11T14:10:49.068 INFO (pid:111621) [services] - registered service "vimlsp"
2020-11-11T14:10:49.069 INFO (pid:111621) [services] - vim language server state change: stopped => starting
2020-11-11T14:10:49.079 INFO (pid:111621) [language-client-index] - vimlsp started with 111703
2020-11-11T14:10:49.253 INFO (pid:111621) [services] - vim language server state change: starting => running
2020-11-11T14:10:49.257 INFO (pid:111621) [services] - service vimlsp started
2020-11-11T14:10:50.653 INFO (pid:111621) [completion-complete] - Results from: vimlsp-1
```

## Describe the bug
When i use coc-yank to paste my history it occurs errors

## Reproduce the bug
- use this short cut or type command
`nnoremap <silent> <space>y  :<C-u>CocList -A --normal yank<cr>`
- and then hit return
```[coc.nvim]: Error
    at Buffer.request (/home/david/.local/share/nvim/plugged/coc.nvim/build/index.js:15462:21)
    at Buffer.setLines (/home/david/.local/share/nvim/plugged/coc.nvim/build/index.js:15247:28)
    at Document.applyEdits (/home/david/.local/share/nvim/plugged/coc.nvim/build/index.js:41328:31)
    at YankList.<anonymous> (/home/david/.config/coc/extensions/node_modules/coc-yank/lib/index.js:2130:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/david/.config/coc/extensions/node_modules/coc-yank/lib/index.js:2078:58)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

## Screenshots (optional)

![DeepinScreenshot_select-area_20201111135823](https://user-images.githubusercontent.com/37657807/98776485-f8b80280-2429-11eb-90c9-e1beeab30ee4.png)

**Comment by chemzqm** [comment]
Seems you have triggered action of yank list for some reason, try minimal vimrc.

**Comment by fannheyward** [comment]
Reproduced on latest master.

**Comment by Dav1dch** [comment]
It still the same error in minimal vimrc



---Original---
