### ISSUE TITLE
Broken on MacVim 

### ISSUE THREAD

**Issue by hjanuschka** [neoclide/coc.nvim#260]
v0.0.39 is broken for me

```
using macvim 
nvim_get_api_info
Uncaught exception: TypeError: Invalid data, chunk must be a string or buffer, not object
    at WriteStream.Socket.write (net.js:701:11)
    at Transport.parseMessage (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:116:31)
    at DecodeStream.events_1.EventEmitter.constructor.decodeStream.on (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:41:18)
    at emitOne (events.js:116:13)
    at DecodeStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at DecodeStream.Readable.push (_stream_readable.js:208:10)
    at DecodeStream.Transform.push (_stream_transform.js:147:32)
    at DecodeBuffer.__dirname.DecodeStream.decoder.push (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)
```

also shows:
<img width="907" alt="bildschirmfoto 2018-12-12 um 10 05 44" src="https://user-images.githubusercontent.com/2891702/49858555-867db400-fdf5-11e8-857a-ca95c8465738.png">

however no idea, how to get the full message

> revert to v0.0.37 and it works!

**Comment by chemzqm** [comment]
That's the full message.
But it works fine on my MacVim, maybe try upgrade your `vim-node-rpc` module.
The error could happen if the stream is not working on object mode, but it should never happen
``` js
var DEFAULT_OPTIONS = {objectMode: true};

function EncodeStream(options) {
  if (!(this instanceof EncodeStream)) return new EncodeStream(options);
  if (options) {
    options.objectMode = true;
  } else {
    options = DEFAULT_OPTIONS;
  }
  Transform.call(this, options);

  var stream = this;
  var encoder = this.encoder = new EncodeBuffer(options);
  encoder.push = function(chunk) {
    stream.push(chunk);
  };
}
```

**Comment by chemzqm** [comment]
Try lastest release，the client have upgraded.

**Comment by hjanuschka** [comment]
i still cant get this to work.

upgraded the vim-node-rpc, and the plugin itself to current master



the exception:


```
2019-01-21T09:05:43.045 INFO (pid:77927) [plugin] - coc initialized with node: v8.9.0
2019-01-21T09:05:44.811 ERROR (pid:77927) [server] - unhandledRejection  Promise {
  <rejected> Error: exited with 1
    at child_process_1.exec (/snapshot/coc.nvim/lib/util/index.js:118:24)
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5) } Error: exited with 1
    at child_process_1.exec (/snapshot/coc.nvim/lib/util/index.js:118:24)
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by chemzqm** [comment]
Another possible reason is when you start macvim as app, the $PATH is not the same in your terminal, so yarn could be not working.
