### ISSUE TITLE
coc-rename broke when typing too fast

### ISSUE THREAD

**Issue by AnatoleLucet** [neoclide/coc.nvim#2618]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-dev
node version: v14.15.0
coc.nvim version: 0.0.79-e1803998fd
coc.nvim directory: /home/anatole/.vim/plugged/coc.nvim
term: st-256color
platform: linux

## Log of coc.nvim

2020-11-18T11:09:22.547 WARN (pid:356911) [attach] - Plugin not ready when received "documentSymbols" []
2020-11-18T11:09:22.550 ERROR (pid:356911) [attach] - Request error: documentSymbols [] TypeError: Cannot read property 'getDocumentSymbols' of undefined
    at /home/anatole/.vim/plugged/coc.nvim/build/index.js:23823:39
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Plugin.cocAction (/home/anatole/.vim/plugged/coc.nvim/build/index.js:24009:16)
    at async NeovimClient.<anonymous> (/home/anatole/.vim/plugged/coc.nvim/build/index.js:11622:27)
2020-11-18T11:09:22.865 WARN (pid:356911) [attach] - Plugin not ready when received "documentSymbols" []
2020-11-18T11:09:22.866 ERROR (pid:356911) [attach] - Request error: documentSymbols [] TypeError: Cannot read property 'getDocumentSymbols' of undefined
    at /home/anatole/.vim/plugged/coc.nvim/build/index.js:23823:39
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Plugin.cocAction (/home/anatole/.vim/plugged/coc.nvim/build/index.js:24009:16)
    at async NeovimClient.<anonymous> (/home/anatole/.vim/plugged/coc.nvim/build/index.js:11622:27)
2020-11-18T11:09:23.095 INFO (pid:356911) [services] - registered service "eslint"
2020-11-18T11:09:23.096 INFO (pid:356911) [services] - eslint langserver state change: stopped => starting
2020-11-18T11:09:23.358 INFO (pid:356911) [language-client-index] - eslint started with 357000
2020-11-18T11:09:23.405 INFO (pid:356911) [services] - registered service "highlight"
2020-11-18T11:09:23.815 INFO (pid:356911) [language-client-index] - highlight started with 357010
2020-11-18T11:09:23.834 INFO (pid:356911) [services] - eslint langserver state change: starting => running
2020-11-18T11:09:23.842 INFO (pid:356911) [services] - service eslint started
2020-11-18T11:09:24.007 INFO (pid:356911) [language-client-index] - cSpell started with 357019
2020-11-18T11:09:24.067 INFO (pid:356911) [services] - registered service "tsserver"
2020-11-18T11:09:24.135 INFO (pid:356911) [plugin] - coc.nvim 0.0.79-e1803998fd initialized with node: v14.15.0 after 1605ms
2020-11-18T11:09:24.197 INFO (pid:356911) [services] - service tsserver started
2020-11-18T11:09:24.660 INFO (pid:356911) [watchman] - watchman watching project: /home/anatole/work/marjane/site-web-refonte-react
2020-11-18T11:09:35.357 INFO (pid:356911) [completion-complete] - Results from: snippets
```

## Describe the bug

When I use coc-rename and type too fast, the rename is canceled.

## Reproduce the bug

Write fast when using coc-rename.

## Screenshots (optional)

![Peek 2020-11-18 11-08](https://user-images.githubusercontent.com/35486736/99516705-c9a41280-298e-11eb-933b-05b291e6ce1e.gif)

**Comment by chemzqm** [comment]
It happens sometimes.

**Comment by chemzqm** [comment]
Fixed, mostly.
Neovim could be sending lines from old changes, don't know how to avoid it.
