### ISSUE TITLE
shell use proxy CocUpdate error

### ISSUE THREAD

**Issue by 10ve** [neoclide/coc.nvim#2622]
## Result from CocInfo

```## versions

vim version: NVIM v0.4.4
node version: v15.2.1
coc.nvim version: 0.0.79-1e1f452a03
coc.nvim directory: /Users/yang/.config/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2020-11-19T16:49:53.202 INFO (pid:16702) [plugin] - coc.nvim 0.0.79-1e1f452a03 initialized with node: v15.2.1 after 55ms
2020-11-19T16:50:00.100 INFO (pid:16702) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-19T16:50:00.103 INFO (pid:16702) [model-installer] - Get info from https://registry.npm.taobao.org/
2020-11-19T16:50:00.106 INFO (pid:16702) [model-fetch] - Using proxy http://127.0.0.1:10800 from system environment for registry.npm.taobao.org:
2020-11-19T16:50:00.109 ERROR (pid:16702) [model-fetch] - Fetch error for https://registry.npm.taobao.org/coc-json: {
  method: 'GET',
  hostname: 'registry.npm.taobao.org',
  port: 443,
  path: '/coc-json',
  agent: HttpsProxyAgent {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    timeout: null,
    maxFreeSockets: 1,
    maxSockets: 1,
    sockets: {},
    requests: {},
    secureProxy: false,
    proxy: {
      host: '127.0.0.1',
      port: 10800,
      auth: null,
      rejectUnauthorized: true
    },
    [Symbol(kCapture)]: false
  },
  rejectUnauthorized: true,
  maxRedirects: 3,
  headers: {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64)',
    'Accept-Encoding': 'gzip, deflate',
    'Proxy-Authorization': null
  },
  timeout: 10000
} TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:277:15)
    at new ClientRequest (node:_http_client:155:11)
    at Object.request (node:https:313:10)
    at RedirectableRequest._performRequest (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:50710:24)
    at new RedirectableRequest (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:50529:8)
    at Object.wrappedProtocol.request (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:50906:14)
    at /Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:74926:25
    at new Promise (<anonymous>)
    at request (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:74919:12)
    at Object.fetch [as default] (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:75021:12)
    at Installer.getInfo (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:49437:40)
    at Installer.update (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:49329:31) {
  code: 'ERR_INVALID_PROTOCOL'
}
2020-11-19T16:50:00.111 INFO (pid:16702) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-19T16:50:00.112 INFO (pid:16702) [model-installer] - Get info from https://registry.npm.taobao.org/
2020-11-19T16:50:00.113 INFO (pid:16702) [model-fetch] - Using proxy http://127.0.0.1:10800 from system environment for registry.npm.taobao.org:
2020-11-19T16:50:00.113 ERROR (pid:16702) [model-fetch] - Fetch error for https://registry.npm.taobao.org/coc-tsserver: {
  method: 'GET',
  hostname: 'registry.npm.taobao.org',
  port: 443,
  path: '/coc-tsserver',
  agent: HttpsProxyAgent {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    timeout: null,
    maxFreeSockets: 1,
    maxSockets: 1,
    sockets: {},
    requests: {},
    secureProxy: false,
    proxy: {
      host: '127.0.0.1',
      port: 10800,
      auth: null,
      rejectUnauthorized: true
    },
    [Symbol(kCapture)]: false
  },
  rejectUnauthorized: true,
  maxRedirects: 3,
  headers: {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64)',
    'Accept-Encoding': 'gzip, deflate',
    'Proxy-Authorization': null
  },
  timeout: 10000
} TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:277:15)
    at new ClientRequest (node:_http_client:155:11)
    at Object.request (node:https:313:10)
    at RedirectableRequest._performRequest (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:50710:24)
    at new RedirectableRequest (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:50529:8)
    at Object.wrappedProtocol.request (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:50906:14)
    at /Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:74926:25
    at new Promise (<anonymous>)
    at request (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:74919:12)
    at Object.fetch [as default] (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:75021:12)
    at Installer.getInfo (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:49437:40)
    at Installer.update (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:49329:31) {
  code: 'ERR_INVALID_PROTOCOL'
}

vim version: NVIM v0.4.4
node version: v15.2.1
coc.nvim version: 0.0.79-1e1f452a03
coc.nvim directory: /Users/yang/.config/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2020-11-19T16:49:53.202 INFO (pid:16702) [plugin] - coc.nvim 0.0.79-1e1f452a03 initialized with node: v15.2.1 after 55ms
2020-11-19T16:50:00.100 INFO (pid:16702) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-19T16:50:00.103 INFO (pid:16702) [model-installer] - Get info from https://registry.npm.taobao.org/
2020-11-19T16:50:00.106 INFO (pid:16702) [model-fetch] - Using proxy http://127.0.0.1:10800 from system environment for registry.npm.taobao.org:
2020-11-19T16:50:00.109 ERROR (pid:16702) [model-fetch] - Fetch error for https://registry.npm.taobao.org/coc-json: {
  method: 'GET',
  hostname: 'registry.npm.taobao.org',
  port: 443,
  path: '/coc-json',
  agent: HttpsProxyAgent {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    timeout: null,
    maxFreeSockets: 1,
    maxSockets: 1,
    sockets: {},
    requests: {},
    secureProxy: false,
    proxy: {
      host: '127.0.0.1',
      port: 10800,
      auth: null,
      rejectUnauthorized: true
    },
    [Symbol(kCapture)]: false
  },
  rejectUnauthorized: true,
  maxRedirects: 3,
  headers: {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64)',
    'Accept-Encoding': 'gzip, deflate',
    'Proxy-Authorization': null
  },
  timeout: 10000
} TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:277:15)
    at new ClientRequest (node:_http_client:155:11)
    at Object.request (node:https:313:10)
    at RedirectableRequest._performRequest (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:50710:24)
    at new RedirectableRequest (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:50529:8)
    at Object.wrappedProtocol.request (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:50906:14)
    at /Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:74926:25
    at new Promise (<anonymous>)
    at request (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:74919:12)
    at Object.fetch [as default] (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:75021:12)
    at Installer.getInfo (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:49437:40)
    at Installer.update (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:49329:31) {
  code: 'ERR_INVALID_PROTOCOL'
}
2020-11-19T16:50:00.111 INFO (pid:16702) [model-installer] - Using npm from: /usr/local/bin/npm
2020-11-19T16:50:00.112 INFO (pid:16702) [model-installer] - Get info from https://registry.npm.taobao.org/
2020-11-19T16:50:00.113 INFO (pid:16702) [model-fetch] - Using proxy http://127.0.0.1:10800 from system environment for registry.npm.taobao.org:
2020-11-19T16:50:00.113 ERROR (pid:16702) [model-fetch] - Fetch error for https://registry.npm.taobao.org/coc-tsserver: {
  method: 'GET',
  hostname: 'registry.npm.taobao.org',
  port: 443,
  path: '/coc-tsserver',
  agent: HttpsProxyAgent {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    timeout: null,
    maxFreeSockets: 1,
    maxSockets: 1,
    sockets: {},
    requests: {},
    secureProxy: false,
    proxy: {
      host: '127.0.0.1',
      port: 10800,
      auth: null,
      rejectUnauthorized: true
    },
    [Symbol(kCapture)]: false
  },
  rejectUnauthorized: true,
  maxRedirects: 3,
  headers: {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64)',
    'Accept-Encoding': 'gzip, deflate',
    'Proxy-Authorization': null
  },
  timeout: 10000
} TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:277:15)
    at new ClientRequest (node:_http_client:155:11)
    at Object.request (node:https:313:10)
    at RedirectableRequest._performRequest (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:50710:24)
    at new RedirectableRequest (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:50529:8)
    at Object.wrappedProtocol.request (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:50906:14)
    at /Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:74926:25
    at new Promise (<anonymous>)
    at request (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:74919:12)
    at Object.fetch [as default] (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:75021:12)
    at Installer.getInfo (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:49437:40)
    at Installer.update (/Users/yang/.config/nvim/plugged/coc.nvim/build/index.js:49329:31) {
  code: 'ERR_INVALID_PROTOCOL'
}

```

## Describe the bug

shell use proxy then 
An error occurredneovim while CocUpdate/Install 

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```
- export https_proxy=http://127.0.0.1:port http_proxy=http://127.0.0.1:port all_proxy=socks5://127.0.0.1:port

- Start (neo)vim with command: `vim -u mini.vim`

- :CocUpdate

-  ✗ coc-json Request failed using proxy 127.0.0.1: Protocol "https:" not supported. Expected "http:"

## Screenshots (optional)

<img width="931" alt="截屏2020-11-19 下午4 56 22" src="https://user-images.githubusercontent.com/11514850/99643882-30f1bd80-2a88-11eb-9957-bf7bca550055.png">

**Comment by chemzqm** [comment]
Use node < 15 or wait for https-proxy-agent update
