### ISSUE TITLE
Extension installation not working behind a proxy in CoC, but works with npm.

### ISSUE THREAD

**Issue by JSamir** [neoclide/coc.nvim#2628]
## Describe the bug

Using CocInstall results in the error in the log below. Using npm I can install the same extension without problems.

By googling `ERR_INVALID_PROTOCOL` it seems that the problem arises from the fact that the proxy has http protocol but the registry is https.

I tried to change the registry to http, but that just moves to issue to a later step and the installation still fails.

It also does not make a difference if I specify the proxy in coc-settings.json (it's being picked up from the environment in the logs below).

## versions

vim version: NVIM v0.5.0-828-g0a95549d6
node version: v15.2.1
coc.nvim version: 0.0.79-d4b169684f
coc.nvim directory: /home/samir/.local/share/nvim/plugged/coc.nvim
term: alacritty
platform: linux

## Log of coc.nvim

2020-11-20T14:50:19.022 INFO (pid:7599) [plugin] - coc.nvim 0.0.79-d4b169684f initialized with node: v15.2.1 after 36ms
2020-11-20T14:50:27.224 INFO (pid:7599) [model-installer] - Using npm from: /usr/bin/npm
2020-11-20T14:50:27.230 INFO (pid:7599) [model-installer] - Get info from https://registry.npmjs.org/
2020-11-20T14:50:27.235 INFO (pid:7599) [model-fetch] - Using proxy http://proxy.domain.com:8080/ from system environment for registry.npmjs.org:
2020-11-20T14:50:27.241 ERROR (pid:7599) [model-fetch] - Fetch error for https://registry.npmjs.org/coc-java: {
  method: 'GET',
  hostname: 'registry.npmjs.org',
  port: 443,
  path: '/coc-java',
  agent: HttpsProxyAgent {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    timeout: null,
    maxFreeSockets: 1,
    maxSockets: 1,
    sockets: {},
    requests: {},
    secureProxy: false,
    proxy: {
      host: 'proxy.domain.com',
      port: 8080,
      auth: null,
      rejectUnauthorized: true
    },
    [Symbol(kCapture)]: false
  },
  rejectUnauthorized: true,
  maxRedirects: 3,
  headers: {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64)',
    'Accept-Encoding': 'gzip, deflate',
    'Proxy-Authorization': null
  },
  timeout: 10000
} TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:277:15)
    at new ClientRequest (node:_http_client:155:11)
    at Object.request (node:https:313:10)
    at RedirectableRequest._performRequest (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:50698:24)
    at new RedirectableRequest (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:50517:8)
    at Object.wrappedProtocol.request (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:50894:14)
    at /home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:74914:25
    at new Promise (<anonymous>)
    at request (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:74907:12)
    at Object.fetch [as default] (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:75009:12)
    at Installer.getInfo (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:49425:40)
    at Installer.install (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:49293:31)
    at fn (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:48343:30)
    at run (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:22000:13)
    at /home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:22004:13
    at new Promise (<anonymous>) {
  code: 'ERR_INVALID_PROTOCOL'
}
2020-11-20T14:50:27.242 ERROR (pid:7599) [extensions] - Error on install coc-java Error: Request failed using proxy proxy.domain.com: Protocol "https:" not supported. Expected "http:"
    at /home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:75013:19
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Installer.getInfo (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:49425:19)
    at async Installer.install (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:49293:20)

vim version: NVIM v0.5.0-828-g0a95549d6
node version: v15.2.1
coc.nvim version: 0.0.79-d4b169684f
coc.nvim directory: /home/samir/.local/share/nvim/plugged/coc.nvim
term: alacritty
platform: linux

## Log of coc.nvim

2020-11-20T14:50:19.022 INFO (pid:7599) [plugin] - coc.nvim 0.0.79-d4b169684f initialized with node: v15.2.1 after 36ms
2020-11-20T14:50:27.224 INFO (pid:7599) [model-installer] - Using npm from: /usr/bin/npm
2020-11-20T14:50:27.230 INFO (pid:7599) [model-installer] - Get info from https://registry.npmjs.org/
2020-11-20T14:50:27.235 INFO (pid:7599) [model-fetch] - Using proxy http://proxy.domain.com:8080/ from system environment for registry.npmjs.org:
2020-11-20T14:50:27.241 ERROR (pid:7599) [model-fetch] - Fetch error for https://registry.npmjs.org/coc-java: {
  method: 'GET',
  hostname: 'registry.npmjs.org',
  port: 443,
  path: '/coc-java',
  agent: HttpsProxyAgent {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    timeout: null,
    maxFreeSockets: 1,
    maxSockets: 1,
    sockets: {},
    requests: {},
    secureProxy: false,
    proxy: {
      host: 'proxy.domain.com',
      port: 8080,
      auth: null,
      rejectUnauthorized: true
    },
    [Symbol(kCapture)]: false
  },
  rejectUnauthorized: true,
  maxRedirects: 3,
  headers: {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64)',
    'Accept-Encoding': 'gzip, deflate',
    'Proxy-Authorization': null
  },
  timeout: 10000
} TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:277:15)
    at new ClientRequest (node:_http_client:155:11)
    at Object.request (node:https:313:10)
    at RedirectableRequest._performRequest (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:50698:24)
    at new RedirectableRequest (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:50517:8)
    at Object.wrappedProtocol.request (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:50894:14)
    at /home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:74914:25
    at new Promise (<anonymous>)
    at request (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:74907:12)
    at Object.fetch [as default] (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:75009:12)
    at Installer.getInfo (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:49425:40)
    at Installer.install (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:49293:31)
    at fn (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:48343:30)
    at run (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:22000:13)
    at /home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:22004:13
    at new Promise (<anonymous>) {
  code: 'ERR_INVALID_PROTOCOL'
}
2020-11-20T14:50:27.242 ERROR (pid:7599) [extensions] - Error on install coc-java Error: Request failed using proxy proxy.domain.com: Protocol "https:" not supported. Expected "http:"
    at /home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:75013:19
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Installer.getInfo (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:49425:19)
    at async Installer.install (/home/samir/.local/share/nvim/plugged/coc.nvim/build/index.js:49293:20)

**Comment by chemzqm** [comment]
Use node 14 or wait for fix of http-proxy-agent

**Comment by JSamir** [comment]
@chemzqm Thanks, that did the trick.

Now coc-java fails to download jdtls, any idea what I can do? It does not look like coc-java is using the proxy (neither from the environment nor from coc-settings.json).

2020-11-20T15:59:18.445 INFO (pid:9307) [coc-java] - Using java from /home/samir/.sdkman/candidates/java/8.0.272-zulu, version: 8
2020-11-20T15:59:18.456 INFO (pid:9307) [plugin] - coc.nvim 0.0.79-d4b169684f initialized with node: v14.15.0 after 228ms
2020-11-20T15:59:18.578 ERROR (pid:9307) [extension:coc-java] - GotError [RequestError]: getaddrinfo EAI_AGAIN download.eclipse.org
    at ClientRequest.<anonymous> (/home/samir/.config/coc/extensions/node_modules/coc-java/lib/index.js:12312:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/home/samir/.config/coc/extensions/node_modules/coc-java/lib/index.js:14177:11)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EAI_AGAIN',
  host: 'download.eclipse.org',
  hostname: 'download.eclipse.org',
  method: 'GET',
  path: '/jdtls/snapshots/jdt-language-server-latest.tar.gz',
  socketPath: undefined,
  protocol: 'http:',
  url: 'http://download.eclipse.org/jdtls/snapshots/jdt-language-server-latest.tar.gz',
  gotOptions: {
    path: '/jdtls/snapshots/jdt-language-server-latest.tar.gz',
    protocol: 'http:',
    slashes: true,
    auth: null,
    host: 'download.eclipse.org',
    port: null,
    hostname: 'download.eclipse.org',
    hash: null,
    search: null,
    query: null,
    pathname: '/jdtls/snapshots/jdt-language-server-latest.tar.gz',
    href: 'http://download.eclipse.org/jdtls/snapshots/jdt-language-server-latest.tar.gz',
    retry: {
      retries: [Function (anonymous)],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: true,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    encoding: null,
    method: 'GET'
  }
}

**Comment by JSamir** [comment]
It seems that there is a separate issue with coc-java, in which the correctly set proxy in coc.nvim is not handled properly.

In short, coc-java expects the proxy set in coc-settings.json to be without the `http://` prefix, which is actually invalid as reported by coc-json using the schema file for the settings.

See also https://github.com/neoclide/coc-java/issues/101
