### ISSUE TITLE
coc crash when language server sends \n

### ISSUE THREAD

**Issue by kerkmann** [neoclide/coc.nvim#2633]
Some language server (like rust RLS) are sendin a `\n` at the end of an import action.

Before I fixed it, the line was `Line 17: Add 'use std::io::BufReader;\n'            [-]`, which crashed the plugin.
![image](https://user-images.githubusercontent.com/1492139/99870336-a5387800-2bd2-11eb-914f-a17517240b58.png)

Replacing the \n solves the problem.
A dirty quick fix for line 15248 in index.js is solving this problem. :)
```javascript
return this[method](`${this.prefix}set_lines`, [
    _start,
    end,
    indexing,
    lines.map(function(x) { return x.replace("\n", ""); } ),
]);
```

The error log is
```
2020-11-21T08:26:15.196 DEBUG (pid:307619) [events] - Event: FileType [ 'cocactions', 5 ]
2020-11-21T08:26:15.223 ERROR (pid:307619) [node-client] - request error on "nvim_buf_set_lines" [ 0,
  1,
  true,
  [ ' Line 17: Add `use std::io::BufReader;\n`                [-] ',
    ' Import `std::io::BufReader`                     [quickfix] ',
    ' Qualify as `std::io::BufReader`                 [quickfix] ',
    ' Extract into variable                   [refactor.extract] ' ] ] String cannot contain newlines Error
    at Buffer.request (/home/kerkmann/.local/share/nvim/plugged/coc.nvim/build/index.js:15467:21)
    at Buffer.setLines (/home/kerkmann/.local/share/nvim/plugged/coc.nvim/build/index.js:15244:28)
    at t.Actions.<anonymous> (/home/kerkmann/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:27065)
    at Generator.next (<anonymous>)
    at s (/home/kerkmann/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:23685)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Has someone a better solution? :)

**Comment by chemzqm** [comment]
Upgrade your coc-actions.
