### ISSUE TITLE
CocOpenLog shows Error: LSPs not working

### ISSUE THREAD

**Issue by mattysweeps** [neoclide/coc.nvim#2646]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8022035
node version: v14.2.0
coc.nvim version: 0.0.79
coc.nvim directory: /usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim
term: tmux
platform: linux

## Output channel: git

Looking for git in: git
```

## Describe the bug

Coc does not seem to be working. Running CocOpenLog shows the following error. This error occurs multiple times.

```
2020-11-23T23:19:37.720 ERROR (pid:672388) [workspace] - Error on create buffer: TypeError: Cannot read property 'coc_enabled' of undefined
    at Document.getVar (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/model/document.js:638:33)
    at Document.get shouldAttach [as shouldAttach] (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/model/document.js:53:19)
    at Document.init (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/model/document.js:138:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Workspace.onBufCreate (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/workspace.js:1555:27)
    at async Workspace.checkBuffer (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/workspace.js:1672:13)
    at async Workspace.checkCurrentBuffer (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/workspace.js:1609:9)
```

## Reproduce the bug

Happens when I open different files with different language servers.
- Tested `gopls` and `docker-langserver`.
- Tested with the mini.vim file:

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

**Comment by mattysweeps** [comment]
Used git bisect, looks like a00ef222437822c37703d57ce5ef33299e5ac5b6 is the problem

```
$ git bisect good
a00ef222437822c37703d57ce5ef33299e5ac5b6 is the first bad commit
commit a00ef222437822c37703d57ce5ef33299e5ac5b6
Author: Qiming Zhao <chemzqm@gmail.com>
Date:   Mon Nov 9 21:37:02 2020 +0800

    fix(document): get lines on initialize

 autoload/coc/api.vim  |  2 +-
 autoload/coc/util.vim |  7 ++++++-
 src/model/document.ts | 30 ++++++++++++++++++++----------
 src/types.ts          | 14 --------------
 src/workspace.ts      |  7 +++----
 5 files changed, 30 insertions(+), 30 deletions(-)
```

**Comment by mattysweeps** [comment]
I'm still experiencing the error on 7875e8b4ba962c310771850816773401460d4a73 .

```
2020-11-24T15:41:28.472 ERROR (pid:1783140) [workspace] - Error on create buffer: TypeError: Cannot read property 'coc_enabled' of undefined
    at Document.getVar (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/model/document.js:638:33)
    at Document.get shouldAttach [as shouldAttach] (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/model/document.js:53:19)
    at Document.init (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/model/document.js:138:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Workspace.onBufCreate (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/workspace.js:1555:27)
2020-11-24T15:41:28.777 ERROR (pid:1783140) [workspace] - Error on create buffer: TypeError: Cannot read property 'coc_enabled' of undefined
    at Document.getVar (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/model/document.js:638:33)
    at Document.get shouldAttach [as shouldAttach] (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/model/document.js:53:19)
    at Document.init (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/model/document.js:138:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Workspace.onBufCreate (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/workspace.js:1555:27)
    at async Workspace.checkBuffer (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/workspace.js:1672:13)
    at async Workspace.checkCurrentBuffer (/usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim/lib/workspace.js:1609:9)
```

```
## versions

vim version: VIM - Vi IMproved 8.2 8022035
node version: v14.2.0
coc.nvim version: 0.0.79
coc.nvim directory: /usr/local/google/home/mattysweeps/.bash/config/90-vim/vimrc/plugged/coc.nvim
term: dumb
platform: linux

## Output channel: git

Looking for git in: git

```

**Comment by chemzqm** [comment]
You're not using release branch

**Comment by mattysweeps** [comment]
Ah, whoops. Now it's working. Thank you!
