### ISSUE TITLE
Ran [PlugInstall] in Neovim and it FAILED

### ISSUE THREAD

**Issue by syphonmechanic** [neoclide/coc.nvim#2651]
**[WSL Ubuntu]**

[coc.nvim]: internal/validators.js:121                                                                                                                  throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Object.join (path.js:1039:7)
    at getLogFile (/home/syphonthemechanic/.config/nvim/plugged/coc.nvim/build/index.js:3195:26)
    at Object.<anonymous> (/home/syphonthemechanic/.config/nvim/plugged/coc.nvim/build/index.js:3205:15)
    at __webpack_require__ (/home/syphonthemechanic/.config/nvim/plugged/coc.nvim/build/index.js:20:30)
    at Object.<anonymous> (/home/syphonthemechanic/.config/nvim/plugged/coc.nvim/build/index.js:109:16)
    at __webpack_require__ (/home/syphonthemechanic/.config/nvim/plugged/coc.nvim/build/index.js:20:30)
    at /home/syphonthemechanic/.config/nvim/plugged/coc.nvim/build/index.js:84:18
    at Object.<anonymous> (/home/syphonthemechanic/.config/nvim/plugged/coc.nvim/build/index.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:1200:30) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by chemzqm** [comment]
It was fixed on latest release branch of coc.nvim.
