### ISSUE TITLE
nvim is not responding during parsing include/indexing files using clangd

### ISSUE THREAD

**Issue by pavlosun** [neoclide/coc.nvim#2652]
## Result from CocInfo
vim version: NVIM v0.4.4
node version: v12.19.0
coc.nvim version: 0.0.79-0b82465e6a
coc.nvim directory: /home/pavlo/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2020-11-24T22:12:13.569 INFO (pid:15842) [services] - registered service "highlight"
2020-11-24T22:12:13.760 INFO (pid:15842) [language-client-index] - highlight started with 15854
2020-11-24T22:12:13.770 INFO (pid:15842) [plugin] - coc.nvim 0.0.79-0b82465e6a initialized with node: v12.19.0 after 601ms
2020-11-24T22:12:14.004 ERROR (pid:15842) [node-client] - request error on "nvim_command" [
  "exe 'pyxfile '.fnameescape('/tmp/nvim3MkTeV/coc.nvim-15842/coc-ultisnips-0aR7034Qnf.py')"
] Vim(return):Error invoking 'python_execute_file' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "/tmp/nvim3MkTeV/coc.nvim-15842/coc-ultisnips-0aR7034Qnf.py", line 272, in <module>
    basename = snip.basename
NameError: name 'snip' is not defined Error
    at NeovimClient.request (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:15467:21)
    at NeovimClient.command (/home/pavlo/.config/nvim/plugged/coc.nvim/build/index.js:16392:21)
    at UltiSnippetsProvider.executePythonCode (/home/pavlo/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:8990:45)
    at UltiSnippetsProvider.init (/home/pavlo/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:8668:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async ProviderManager.init (/home/pavlo/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:6141:9)
2020-11-24T22:12:19.710 INFO (pid:15842) [services] - registered service "clangd"
2020-11-24T22:12:19.711 INFO (pid:15842) [services] - clangd state change: stopped => starting
2020-11-24T22:12:19.716 INFO (pid:15842) [language-client-index] - Language server "clangd" started with 15867
2020-11-24T22:12:19.756 INFO (pid:15842) [services] - clangd state change: starting => running
2020-11-24T22:12:19.773 INFO (pid:15842) [services] - service clangd started
2020-11-24T22:12:23.180 ERROR (pid:15842) [attach] - Request cost more than 3s highlight []
2020-11-24T22:13:24.538 ERROR (pid:15842) [attach] - Request cost more than 3s highlight []

## Describe the bug
My project is c++. I use clangd. When I open a new file I see a message: `clangd: parsing includes`. During this, my nvim is not responding to any key.  I use `coc-clangd`.
The relevant part form `coc-settings.json` is:
```
	"coc.preferences.extensionUpdateCheck": "daily",
	"coc.preferences.currentFunctionSymbolAutoUpdate": true,
	"coc.preferences.formatOnInsertLeave": true,

	"clangd.compilationDatabasePath": "./builddir",
	"clangd.semanticHighlighting": false,
	"clangd.arguments": [
		"--compile-commands-dir=./builddir",
		"--background-index",
		"--completion-style=detailed",
		"-j=4"
	],
```
I already have 
```
set hidden
set updatetime=300
```
in my `init.vim`  file. 

I am not sure if this problem because of `coc.nvim`. Could be `coc-clangd`. 
Any advice?

**Comment by chemzqm** [comment]
Try minimal vimrc, looks like you're using CocAction which is blocked

**Comment by pavlosun** [comment]
I use the config file provided by [here](https://github.com/neoclide/coc.nvim#example-vim-configuration). After renaming all functions `CocAction` to `CocActionAsync` the problem resolved. Does it make sense to update the suggested config file?

**Comment by chemzqm** [comment]
It was updated.

**Comment by pavlosun** [comment]
thanks
