### ISSUE TITLE
 Error on active extension coc-tabnine: TypeError: (intermediate value).trim is not a function

### ISSUE THREAD

**Issue by nzlov** [neoclide/coc.nvim#2663]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.4
node version: v14.15.1
coc.nvim version: 0.0.79-6fe357fc97
coc.nvim directory: /Users/nzlov/.config/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2020-11-28T23:00:41.507 INFO (pid:16495) [services] - registered service "highlight"
2020-11-28T23:00:41.596 INFO (pid:16495) [model-fetch] - Using proxy http://127.0.0.1:1087/ from system environment for update.tabnine.com:
2020-11-28T23:00:41.607 INFO (pid:16495) [language-client-index] - highlight started with 16497
2020-11-28T23:00:43.688 WARN (pid:16495) [attach] - Plugin not ready when received "openLog" []
2020-11-28T23:00:44.000 WARN (pid:16495) [attach] - Plugin not ready when received "highlight" []
2020-11-28T23:00:45.399 ERROR (pid:16495) [extensions] - Error on active extension coc-tabnine: TypeError: (intermediate value).trim is not a function
    at Function.<anonymous> (/Users/nzlov/.config/coc/extensions/node_modules/coc-tabnine/lib/index.js:420:92)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/nzlov/.config/coc/extensions/node_modules/coc-tabnine/lib/index.js:95:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) TypeError: (intermediate value).trim is not a function
    at Function.<anonymous> (/Users/nzlov/.config/coc/extensions/node_modules/coc-tabnine/lib/index.js:420:92)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/nzlov/.config/coc/extensions/node_modules/coc-tabnine/lib/index.js:95:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-11-28T23:00:45.405 INFO (pid:16495) [plugin] - coc.nvim 0.0.79-6fe357fc97 initialized with node: v14.15.1 after 4030ms
```

**Comment by nzlov** [comment]
@chemzqm why? ?
[https://github.com/neoclide/coc-tabnine/issues/50](https://github.com/neoclide/coc-tabnine/issues/50)
