### ISSUE TITLE
LanguageClient report error when using ccls on RaspberryPi 3B

### ISSUE THREAD

**Issue by vimers** [neoclide/coc.nvim#2681]
## Result from CocInfo

```log
## versions

vim version: VIM - Vi IMproved 8.2 8021522
node version: v10.21.0
coc.nvim version: 0.0.79-67cc18bcbf
coc.nvim directory: /home/pi/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2020-12-05T12:21:52.526 WARN (pid:945) [attach] - Plugin not ready when received "showInfo" []
2020-12-05T12:21:52.989 INFO (pid:945) [services] - registered service "languageserver.ccls"
2020-12-05T12:21:53.020 INFO (pid:945) [services] - ccls state change: stopped => starting
2020-12-05T12:21:54.665 INFO (pid:945) [language-client-index] - Language server "languageserver.ccls" started with 966
2020-12-05T12:21:55.571 INFO (pid:945) [plugin] - coc.nvim 0.0.79-67cc18bcbf initialized with node: v10.21.0 after 3126ms
```

## Describe the bug
AutoComplete with coc-python can be used normally.
C/CPP autocomplete can't be used when using ccls as language server

ccls setting:
```json
{
          "languageserver": {
                  "ccls": {
                          "command": "ccls",
                          "args": ["-log-file=/tmp/ccls.log", "-v=2"],
                          "filetypes": ["c", "cpp", "objc", "objcpp"],
                          "rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
                          "initializationOptions": {
                                  "cache": {
                                          "directory": "/tmp/ccls"
                                  }
                          }
                  }
          }
}

```

CocOpenLog shows:
```log
2020-12-05T12:21:52.526 WARN (pid:945) [attach] - Plugin not ready when received "showInfo" []
2020-12-05T12:21:52.989 INFO (pid:945) [services] - registered service "languageserver.ccls"
2020-12-05T12:21:53.020 INFO (pid:945) [services] - ccls state change: stopped => starting
2020-12-05T12:21:54.665 INFO (pid:945) [language-client-index] - Language server "languageserver.ccls" started with 966
2020-12-05T12:21:55.571 INFO (pid:945) [plugin] - coc.nvim 0.0.79-67cc18bcbf initialized with node: v10.21.0 after 3126ms
2020-12-05T12:21:59.177 INFO (pid:945) [services] - ccls state change: starting => running
2020-12-05T12:21:59.277 INFO (pid:945) [services] - service languageserver.ccls started
2020-12-05T12:21:59.337 INFO (pid:945) [services] - ccls state change: running => stopped
2020-12-05T12:21:59.338 INFO (pid:945) [services] - ccls state change: stopped => starting
2020-12-05T12:21:59.352 INFO (pid:945) [language-client-index] - Language server "languageserver.ccls" started with 992
2020-12-05T12:21:59.457 INFO (pid:945) [services] - ccls state change: starting => running
2020-12-05T12:21:59.501 INFO (pid:945) [services] - ccls state change: running => stopped
2020-12-05T12:21:59.501 INFO (pid:945) [services] - ccls state change: stopped => starting
2020-12-05T12:21:59.514 INFO (pid:945) [language-client-index] - Language server "languageserver.ccls" started with 1012
2020-12-05T12:21:59.616 INFO (pid:945) [services] - ccls state change: starting => running
2020-12-05T12:21:59.688 INFO (pid:945) [services] - ccls state change: running => stopped
2020-12-05T12:21:59.688 INFO (pid:945) [services] - ccls state change: stopped => starting
2020-12-05T12:21:59.701 INFO (pid:945) [language-client-index] - Language server "languageserver.ccls" started with 1032
2020-12-05T12:21:59.804 INFO (pid:945) [services] - ccls state change: starting => running
2020-12-05T12:21:59.839 ERROR (pid:945) [language-client-client] - connection error: Error [ERR_STREAM_DESTROYED]: Cannot call write afte
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at StreamMessageWriter.write (/home/pi/.vim/plugged/coc.nvim/build/index.js:18415:27)
    at reply (/home/pi/.vim/plugged/coc.nvim/build/index.js:17053:27)
    at promise.then (/home/pi/.vim/plugged/coc.nvim/build/index.js:17116:25)
    at process._tickCallback (internal/process/next_tick.js:68:7) undefined
2020-12-05T12:21:59.845 INFO (pid:945) [services] - ccls state change: running => stopped
2020-12-05T12:21:59.848 ERROR (pid:945) [language-client-client] - connection error: Error [ERR_STREAM_DESTROYED]: Cannot call write afte
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at StreamMessageWriter.write (/home/pi/.vim/plugged/coc.nvim/build/index.js:18417:27)
    at reply (/home/pi/.vim/plugged/coc.nvim/build/index.js:17053:27)
    at promise.then (/home/pi/.vim/plugged/coc.nvim/build/index.js:17116:25)
    at process._tickCallback (internal/process/next_tick.js:68:7) undefined
2020-12-05T12:21:59.851 ERROR (pid:945) [language-client-client] - connection error: Error [ERR_STREAM_DESTROYED]: Cannot call write afte
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at StreamMessageWriter.write (/home/pi/.vim/plugged/coc.nvim/build/index.js:18415:27)
    at Promise (/home/pi/.vim/plugged/coc.nvim/build/index.js:17563:35)
    at new Promise (<anonymous>)
    at Object.sendRequest (/home/pi/.vim/plugged/coc.nvim/build/index.js:17553:26)
    at Object.shutdown (/home/pi/.vim/plugged/coc.nvim/build/index.js:79844:36)
    at _onStop.resolveConnection.then.connection (/home/pi/.vim/plugged/coc.nvim/build/index.js:82050:31)
    at process._tickCallback (internal/process/next_tick.js:68:7) undefined
2020-12-05T12:21:59.852 ERROR (pid:945) [language-client-client] - connection error: Error [ERR_STREAM_DESTROYED]: Cannot call write afte
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at StreamMessageWriter.write (/home/pi/.vim/plugged/coc.nvim/build/index.js:18417:27)
    at Promise (/home/pi/.vim/plugged/coc.nvim/build/index.js:17563:35)
    at new Promise (<anonymous>)
    at Object.sendRequest (/home/pi/.vim/plugged/coc.nvim/build/index.js:17553:26)
    at Object.shutdown (/home/pi/.vim/plugged/coc.nvim/build/index.js:79844:36)
    at _onStop.resolveConnection.then.connection (/home/pi/.vim/plugged/coc.nvim/build/index.js:82050:31)
    at process._tickCallback (internal/process/next_tick.js:68:7) undefined
```

ccls server log:
```log
12:26:24 stdin            pipeline.cc:555 V(2) receive RequestMessage: 0 initialize
12:26:24 ccls           initialize.cc:271 I initialize in directory /home/pi with uri file:///home/pi
12:26:24 ccls           initialize.cc:294 I initializationOptions: {"compilationDatabaseCommand":"","compilationDatabaseDirectory":"","cache":{"directory":"/tmp/ccls","format":"binary","hierarchicalPath":false,"retainInMemory":2},"capabilities":{"documentOnTypeFormattingProvider":{"firstTriggerCharacter":"}","moreTriggerCharacter":[]},"foldingRangeProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}}},"clang":{"excludeArgs":[],"extraArgs":[],"pathMappings":[],"resourceDir":""},"client":{"diagnosticsRelatedInformation":true,"hierarchicalDocumentSymbolSupport":true,"linkSupport":true,"snippetSupport":true},"codeLens":{"localVariables":true},"completion":{"caseSensitivity":2,"detailedLabel":true,"dropOldRequests":true,"duplicateOptional":true,"filterAndSort":true,"include":{"blacklist":[],"maxPathSize":30,"suffixWhitelist":[".h",".hpp",".hh",".inc"],"whitelist":[]},"maxNum":100},"diagnostics":{"blacklist":[],"onChange":1000,"onOpen":0,"onSave":0,"spellChecking":true,"whitelist":[]},"highlight":{"largeFileSize":2097152,"lsRanges":false,"blacklist":[],"whitelist":[]},"index":{"blacklist":[],"comments":2,"initialNoLinkage":false,"initialBlacklist":[],"initialWhitelist":[],"maxInitializerLines":5,"multiVersion":0,"multiVersionBlacklist":[],"multiVersionWhitelist":[],"name":{"suppressUnwrittenScope":false},"onChange":false,"parametersInDeclarations":true,"threads":0,"trackDependency":2,"whitelist":[]},"request":{"timeout":5000},"session":{"maxNum":10},"workspaceSymbol":{"caseSensitivity":1,"maxNum":1000,"sort":true},"xref":{"maxNum":2000}}
12:26:24 ccls           initialize.cc:323 I use -resource-dir=/snap/ccls/current//usr/lib/llvm-7/lib/clang/7.0.0
12:26:24 ccls             pipeline.cc:819 V(2) respond to RequestMessage: 0
12:26:24 ccls           initialize.cc:356 I workspace folder: /home/pi/
12:26:24 ccls           initialize.cc:381 I start 4 indexers
12:26:24 ccls           initialize.cc:389 I dispatch initial index requests
12:26:24 ccls             pipeline.cc:477 I loaded project. Refresh semantic highlight for all working file.
12:26:24 stdin            pipeline.cc:557 V(2) receive NotificationMessage initialized
12:26:24 ccls             pipeline.cc:790 V(2) RequestMessage: client/registerCapability
12:26:24 stdin            pipeline.cc:557 V(2) receive NotificationMessage textDocument/didOpen

```

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
The stdio stream destroyed for some reason, try avoid start vim for your user home.

**Comment by vimers** [comment]
> The stdio stream destroyed for some reason, try avoid start vim from user home.

move the source file to subdir also report the sample error.

How can i get the detail log that shows why stdio stream was destroyed?

**Comment by chemzqm** [comment]
Checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Service state `running` means the initialize request is send to server as expected, but the server stopped for some reason.

**Comment by oblitum** [comment]
I really don't recommend you to run ccls or clangd on RPi3. Doesn't it have just 1GB of RAM available to user? You can overflow by accident pretty easily depending on the code base, and then it'll completely freeze.

**Comment by chemzqm** [comment]
I've improved error handler for child process of language client eaa21472
