### ISSUE TITLE
'textDocument/definition' only supprts Location[]?

### ISSUE THREAD

**Issue by tcx4c70** [neoclide/coc.nvim#2713]
## Result from CocInfo

```
undefined## versions

vim version: VIM - Vi IMproved 8.2 8022072
node version: v14.14.0
coc.nvim version: 0.0.79
coc.nvim directory: /home/tcx4c70/.vim/bundle/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2020-12-13T21:53:41.291 INFO (pid:355052) [services] - registered service "languageserver.ccls"
2020-12-13T21:53:41.297 INFO (pid:355052) [services] - ccls state change: stopped => starting
2020-12-13T21:53:41.299 INFO (pid:355052) [plugin] - coc.nvim 0.0.79 initialized with node: v14.14.0 after 60ms
2020-12-13T21:53:41.380 INFO (pid:355052) [language-client-index] - Language server "languageserver.ccls" started with 355156
2020-12-13T21:53:41.581 INFO (pid:355052) [services] - ccls state change: starting => running
2020-12-13T21:53:41.594 INFO (pid:355052) [services] - service languageserver.ccls started
2020-12-13T21:56:18.915 ERROR (pid:355052) [attach] - Request error: getTagList [] TypeError: Cannot read property 'start' of undefined
    at /home/tcx4c70/.vim/bundle/coc.nvim/lib/handler/index.js:594:50
    at Array.map (<anonymous>)
    at Handler.getTagList (/home/tcx4c70/.vim/bundle/coc.nvim/lib/handler/index.js:589:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/tcx4c70/.vim/bundle/coc.nvim/lib/plugin.js:36:50
    at async Plugin.cocAction (/home/tcx4c70/.vim/bundle/coc.nvim/lib/plugin.js:461:16)
    at async NeovimClient.<anonymous> (/home/tcx4c70/.vim/bundle/coc.nvim/lib/attach.js:90:27)
```

## Describe the bug

Hi, I love coc.nvim and I usually use ccls as the language server for C.  My mose used functions are completion and going to the definition.  However, I found that `CocTagFunc` and `<Plug>(coc-definition)` don't work any more in my C projects recently (they still work well in other language projects).

It says that the result of `textDocument/definition` is `Location | Location[] | LocationLink[] | null` in [the specification of lsp](https://microsoft.github.io/language-server-protocol/specification).  But I found that `getTagList()` can only handle `Location[] | null` while ccls will return `LocationLink[]` sometimes (or newer ccls will?).  Maybe it's the reason why `CocTagFunc` and `<Plug>(coc-definition)` cann't find `start` property and report an error?

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  call coc#config("languageserver", {'ccls': {
      \   "command": "ccls",
      \   "trace.server": "verbose",
      \   "filetypes": ["c", "cpp", "objc", "objcpp"],
      \   "rootPatterns": [".ccls", "compile_commands.json", ".vim/", ".git/", ".hg/"],
      \   "initializationOptions": {
      \     "clang": {
      \       "excludeArgs": ["-m*", "-Wa*"]
      \     },
      \     "diagnostics": {
      \       "onChange": 10,
      \     },
      \     "highlight": {
      \       "lsRanges": v:true,
      \     },
      \   }
      \ }})

  if exists('&tagfunc')
    set tagfunc=CocTagFunc
  endif
  ```

- Start (neo)vim with command: `vim -u mini.vim path/to/c/file` (I've generated a compile_commands.json)

- Move cursor to any function, then press `ctrl+]`.

- It'll show some error message like:
  ```
  Error on request (getTagList): Cannot read property 'start' of undefined
  E987: invalid return value from tagfunc
  ```

- The result of `:CocCommand workspace.showOutput`:
  ```
  [Trace - 9:56:18 PM] Sending request 'textDocument/definition - (1)'.
  Params: {
      "textDocument": {
          "uri": "file:///mnt/data/src/os/qemu/target/arm/cpu.c"
      },
      "position": {
          "line": 419,
          "character": 12
      }
  }


  [Trace - 9:56:18 PM] Received response 'textDocument/definition - (1)' in 4ms.
  Result: [
      {
          "targetUri": "file:///mnt/data/src/os/qemu/target/arm/internals.h",
          "targetRange": {
              "start": {
                  "line": 519,
                  "character": 0
              },
              "end": {
                  "line": 519,
                  "character": 42
              }
          },
          "targetSelectionRange": {
              "start": {
                  "line": 519,
                  "character": 5
              },
              "end": {
                  "line": 519,
                  "character": 29
              }
          }
      }
  ]
  ```

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
