### ISSUE TITLE
Error after updating: "TypeError: Cannot read property 'coc_enabled' of undefined"

### ISSUE THREAD

**Issue by sashaafm** [neoclide/coc.nvim#2717]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8022100
node version: v15.3.0
coc.nvim version: 0.0.79
coc.nvim directory: /Users/sashaafm/.vim/bundle/coc.nvim
term: iTerm.app
platform: darwin
```

## Describe the bug

None of my language servers (`elixir-ls` and `elm-language-server`) seem to work and CoC seems to have errors in its log.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

Vim operates normally here.

## :CocOpenLog

I've executed `:CocOpenLog` with debug level

```
2020-12-15T11:30:17.982 ERROR (pid:48704) [workspace] - Error on create buffer: TypeError: Cannot read property 'coc_enabled' of undefined
    at Document.getVar (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:636:33)
    at Document.get shouldAttach [as shouldAttach] (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:53:19)
    at Document.init (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:138:18)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Workspace.onBufCreate (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1546:27)
    at async Promise.all (index 0)
    at async Workspace.attach (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1457:9)
    at async Workspace.init (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:144:9)
    at async Plugin.init (/Users/sashaafm/.vim/bundle/coc.nvim/lib/plugin.js:380:13)
    at async /Users/sashaafm/.vim/bundle/coc.nvim/lib/attach.js:113:13
2020-12-15T11:30:17.985 DEBUG (pid:48704) [events] - Event: BufEnter [ 1 ]
2020-12-15T11:30:17.986 DEBUG (pid:48704) [events] - Event: BufWinEnter [ 1, 1000 ]
2020-12-15T11:30:18.009 INFO (pid:48704) [services] - registered service "languageserver.elmLS"
2020-12-15T11:30:18.009 INFO (pid:48704) [services] - registered service "languageserver.elixirLS"
2020-12-15T11:30:18.009 INFO (pid:48704) [services] - registered service "languageserver.kotlin"
2020-12-15T11:30:18.012 INFO (pid:48704) [plugin] - coc.nvim 0.0.79 initialized with node: v15.3.0 after 62ms
2020-12-15T11:30:18.097 DEBUG (pid:48704) [events] - Event: TermOpen [ 2 ]
2020-12-15T11:30:18.168 DEBUG (pid:48704) [events] - Event: FileType [ 'fzf', 2 ]
2020-12-15T11:30:18.231 DEBUG (pid:48704) [events] - Event: TextChanged [ 2, 1 ]
2020-12-15T11:30:18.275 ERROR (pid:48704) [workspace] - Error on create buffer: TypeError: Cannot read property 'coc_enabled' of undefined
    at Document.getVar (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:636:33)
    at Document.get shouldAttach [as shouldAttach] (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:53:19)
    at Document.init (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:138:18)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Workspace.onBufCreate (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1546:27)
2020-12-15T11:30:19.501 DEBUG (pid:48704) [events] - Event: WinLeave [ 1001 ]
2020-12-15T11:30:19.501 DEBUG (pid:48704) [events] - Event: WinEnter [ 1000 ]
2020-12-15T11:30:19.512 DEBUG (pid:48704) [events] - Event: BufEnter [ 1 ]
2020-12-15T11:30:19.514 DEBUG (pid:48704) [events] - Event: BufWinLeave [ 2, -1 ]
2020-12-15T11:30:19.514 DEBUG (pid:48704) [events] - Event: BufUnload [ 2 ]
2020-12-15T11:30:19.515 DEBUG (pid:48704) [workspace] - buffer unload 2
2020-12-15T11:30:19.516 DEBUG (pid:48704) [events] - Event: BufUnload [ 1 ]
2020-12-15T11:30:19.516 DEBUG (pid:48704) [workspace] - buffer unload 1
2020-12-15T11:30:19.569 DEBUG (pid:48704) [events] - Event: FileType [ 'elixir', 1 ]
2020-12-15T11:30:19.580 DEBUG (pid:48704) [events] - Event: BufCreate [ 1 ]
2020-12-15T11:30:19.582 DEBUG (pid:48704) [events] - Event: BufEnter [ 1 ]
2020-12-15T11:30:19.586 DEBUG (pid:48704) [events] - Event: BufWinEnter [ 1, 1000 ]
2020-12-15T11:30:19.660 ERROR (pid:48704) [workspace] - Error on create buffer: TypeError: Cannot read property 'coc_enabled' of undefined
    at Document.getVar (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:636:33)
    at Document.get shouldAttach [as shouldAttach] (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:53:19)
    at Document.init (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:138:18)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Workspace.onBufCreate (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1546:27)
2020-12-15T11:30:19.660 DEBUG (pid:48704) [events] - Event: CursorMoved [ 1, [ 11, 7 ] ]
2020-12-15T11:30:19.664 ERROR (pid:48704) [workspace] - Error on create buffer: TypeError: Cannot read property 'coc_enabled' of undefined
    at Document.getVar (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:636:33)
    at Document.get shouldAttach [as shouldAttach] (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:53:19)
    at Document.init (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:138:18)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Workspace.onBufCreate (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1546:27)
    at async Workspace.checkBuffer (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1663:13)
    at async Workspace.checkCurrentBuffer (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1600:9)
2020-12-15T11:30:19.915 DEBUG (pid:48704) [events] - Event: CursorHold [ 1 ]
2020-12-15T11:30:19.920 ERROR (pid:48704) [workspace] - Error on create buffer: TypeError: Cannot read property 'coc_enabled' of undefined
    at Document.getVar (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:636:33)
    at Document.get shouldAttach [as shouldAttach] (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:53:19)
    at Document.init (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:138:18)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Workspace.onBufCreate (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1546:27)
    at async Workspace.checkBuffer (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1663:13)
    at async Workspace.checkCurrentBuffer (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1600:9)
2020-12-15T11:30:22.496 DEBUG (pid:48704) [events] - Event: CursorHold [ 1 ]
2020-12-15T11:30:22.502 ERROR (pid:48704) [workspace] - Error on create buffer: TypeError: Cannot read property 'coc_enabled' of undefined
    at Document.getVar (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:636:33)
    at Document.get shouldAttach [as shouldAttach] (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:53:19)
    at Document.init (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:138:18)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Workspace.onBufCreate (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1546:27)
    at async Workspace.checkBuffer (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1663:13)
    at async Workspace.checkCurrentBuffer (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1600:9)
2020-12-15T11:32:34.046 DEBUG (pid:48704) [events] - Event: CursorHold [ 1 ]
2020-12-15T11:32:34.052 ERROR (pid:48704) [workspace] - Error on create buffer: TypeError: Cannot read property 'coc_enabled' of undefined
    at Document.getVar (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:636:33)
    at Document.get shouldAttach [as shouldAttach] (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:53:19)
    at Document.init (/Users/sashaafm/.vim/bundle/coc.nvim/lib/model/document.js:138:18)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Workspace.onBufCreate (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1546:27)
    at async Workspace.checkBuffer (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1663:13)
    at async Workspace.checkCurrentBuffer (/Users/sashaafm/.vim/bundle/coc.nvim/lib/workspace.js:1600:9)
```

I don't know what more info to give. It seems like it just stopped working.

**Comment by chemzqm** [comment]
Please use latest release branch of coc.nvim.

**Comment by sashaafm** [comment]
@chemzqm sorry I didn't include it in my report, but I'm using the latest release branch:
```
Plugin 'neoclide/coc.nvim', {'branch': 'release'}
```

I'll try uninstalling and installing again.

**Comment by chemzqm** [comment]
> coc.nvim version: 0.0.79

Means you're not.
