### ISSUE TITLE
coc-java: auto completion creates invalid symbols

### ISSUE THREAD

**Issue by tbo** [neoclide/coc.nvim#274]
**Result from CocInfo**

```
## versions

vim version: NVIM v0.3.1
node version: v9.10.1
coc.nvim version: 0.0.39
term: xterm-256color
platform: darwin

## Error messages

## Output channel: java
[Info  - 15:59:49] JDT Language Server started
[object Object]
[Warn  - 16:00:39] Dec 14, 2018 4:00:39 PM The Java indexing could not index /Users/tbo/.m2/repository/org/glassfish/hk2/external/asm-all-repackaged/2.5.0-b42/asm-all-repackaged-2.5.0-b42.jar|module-info.class. This .class file doesn't follow the class file format specification. Please report this issue against the .class file vendor
null
org.eclipse.jdt.internal.compiler.classfmt.ClassFormatException
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:477)
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:180)
	at org.eclipse.jdt.internal.core.search.indexing.BinaryIndexer.indexDocument(BinaryIndexer.java:652)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.indexDocument(JavaSearchParticipant.java:73)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexDocument(IndexManager.java:546)
	at org.eclipse.jdt.internal.core.search.indexing.AddJarFileToIndex.execute(AddJarFileToIndex.java:244)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:401)
	at java.lang.Thread.run(Thread.java:748)
Caused in /Users/tbo/.m2/repository/org/glassfish/hk2/external/asm-all-repackaged/2.5.0-b42/asm-all-repackaged-2.5.0-b42.jar|module-info.class by: java.lang.ArrayIndexOutOfBoundsException: 32800
	at org.eclipse.jdt.internal.compiler.classfmt.ModuleInfo.readModuleAttribute(ModuleInfo.java:129)
	at org.eclipse.jdt.internal.compiler.classfmt.ModuleInfo.createModule(ModuleInfo.java:113)
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:440)
	at org.eclipse.jdt.internal.compiler.classfmt.ClassFileReader.<init>(ClassFileReader.java:180)
	at org.eclipse.jdt.internal.core.search.indexing.BinaryIndexer.indexDocument(BinaryIndexer.java:652)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.indexDocument(JavaSearchParticipant.java:73)
	at org.eclipse.jdt.internal.core.search.indexing.IndexManager.indexDocument(IndexManager.java:546)
	at org.eclipse.jdt.internal.core.search.indexing.AddJarFileToIndex.execute(AddJarFileToIndex.java:244)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:401)
	at java.lang.Thread.run(Thread.java:748)
```

**Describe the bug**

Auto-completion for any symbol is apparently triggered twice (see screenshot).
`coc-tsserver` works as expected. So it seems to be an `coc-java` specific problem.

This issue appeared with release v0.0.39 and is also reproducible on `master`.

**To Reproduce**

Try to auto-complete any symbol with `coc-java`.

**Screenshots**

![kapture 2018-12-14 at 16 04 27](https://user-images.githubusercontent.com/264745/50010925-04d78300-ffbb-11e8-9510-a0948d8fdc59.gif)

**Comment by chemzqm** [comment]
I don't have this issue, try set `"java.trace.server": "verbose",` and paste output from output channel.

**Comment by oblitum** [comment]
I've seen this kind of issue before on other servers, but not consistently, depending on typing speed.

Related option: https://github.com/neoclide/coc.nvim/blob/master/data/schema.json#L224-L227.

**Comment by chemzqm** [comment]
@oblitum it's not same issue, `fixInsertedWord` only works with none snippet.

**Comment by oblitum** [comment]
@chemzqm ok

**Comment by tbo** [comment]
@chemzqm Here is the debug output as requested: [coc-debug.txt](https://github.com/neoclide/coc.nvim/files/2680854/coc-debug.txt)

**Comment by chemzqm** [comment]
I got the problem.
You're using up and down for select complete item, this time it's impossible for coc to do resolve on select change, so it does resolve on complete done, but the language server doesn't use the changed content send on complete done, it use the line on `doComplete` to calculate the textEdit.

**Comment by tbo** [comment]
@chemzqm Thanks!
