### ISSUE TITLE
coc.nvim stop working after first word typed (newest neovim nightly)

### ISSUE THREAD

**Issue by ecosse3** [neoclide/coc.nvim#2758]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-dev+950-g5ce328df4
node version: v14.15.3
coc.nvim version: 0.0.80-e8257bea7c
coc.nvim directory: /home/ecosse/.vim/plugged/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2020-12-23T02:05:24.876 INFO (pid:1297440) [services] - registered service "eslint"
2020-12-23T02:05:25.251 INFO (pid:1297440) [plugin] - coc.nvim 0.0.80-e8257bea7c initialized with node: v14.15.3 after 505ms
2020-12-23T02:05:26.322 INFO (pid:1297440) [attach] - receive notification: showInfo []
```

**_Log seems okay but after typing this error occurs: (output of :CocOpenLog after coc stopped working)_**

```
2020-12-23T01:57:56.920 INFO (pid:1261971) [services] - registered service "eslint"
2020-12-23T01:57:57.272 INFO (pid:1261971) [plugin] - coc.nvim 0.0.80-e8257bea7c initialized with node: v14.15.3 after 488ms
2020-12-23T01:57:57.851 INFO (pid:1261971) [attach] - receive notification: highlight []
2020-12-23T01:57:58.278 INFO (pid:1261971) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufWipeout', 1 ]
2020-12-23T01:57:58.279 INFO (pid:1261971) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufWipeout', 1 ]
2020-12-23T01:57:58.424 INFO (pid:1261971) [services] - eslint langserver state change: stopped => starting
2020-12-23T01:57:58.647 INFO (pid:1261971) [language-client-index] - eslint started with 1262179
2020-12-23T01:57:58.684 INFO (pid:1261971) [services] - registered service "tsserver"
2020-12-23T01:57:58.700 INFO (pid:1261971) [services] - eslint langserver state change: starting => running
2020-12-23T01:57:58.706 INFO (pid:1261971) [services] - service eslint started
2020-12-23T01:57:59.220 INFO (pid:1261971) [attach] - receive notification: highlight []
2020-12-23T01:58:02.463 INFO (pid:1261971) [attach] - receive notification: openLog []
2020-12-23T01:58:02.893 INFO (pid:1261971) [attach] - receive notification: highlight []
2020-12-23T01:58:08.522 INFO (pid:1261971) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufDelete', 3 ]
2020-12-23T01:58:08.522 INFO (pid:1261971) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufDelete', 3 ]
2020-12-23T01:58:08.537 INFO (pid:1261971) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocDiagnosticChange' ]
2020-12-23T01:58:08.915 INFO (pid:1261971) [attach] - receive notification: highlight []
2020-12-23T01:58:11.135 INFO (pid:1261971) [attach] - receive notification: highlight []
2020-12-23T01:58:12.463 INFO (pid:1261971) [completion-complete] - Results from: snippets,around,yank,tabnine
2020-12-23T01:58:14.163 ERROR (pid:1261971) [extensions] - TypeError: diagnostics is not iterable
    at DiagnosticBuffer.setDiagnosticInfo (/home/ecosse/.vim/plugged/coc.nvim/build/index.js:46016:32)
    at DiagnosticBuffer._refresh (/home/ecosse/.vim/plugged/coc.nvim/build/index.js:45972:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-12-23T01:58:14.164 ERROR (pid:1261971) [node-client] - resumeNotification not called within same tick: Error
    at NeovimClient.pauseNotification (/home/ecosse/.vim/plugged/coc.nvim/build/index.js:11914:21)
    at DiagnosticBuffer._refresh (/home/ecosse/.vim/plugged/coc.nvim/build/index.js:45971:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-12-23T01:58:14.619 INFO (pid:1261971) [attach] - receive notification: doAutocmd [
  2,
  {
    regcontents: [ '    let' ],
    visual: false,
    inclusive: false,
    regname: '',
    operator: 'd',
    regtype: 'V'
  },
  2,
  1000
]
2020-12-23T01:58:15.189 INFO (pid:1261971) [attach] - receive notification: doAutocmd [
  2,
  {
    regcontents: [ '' ],
    visual: false,
    inclusive: false,
    regname: '',
    operator: 'd',
    regtype: 'V'
  },
  2,
  1000
]
2020-12-23T01:58:15.347 INFO (pid:1261971) [attach] - receive request: CocAutocmd [ 'BufWritePre', 2 ]
2020-12-23T01:58:16.956 ERROR (pid:1261971) [node-client] - resumeNotification not called within same tick: Error
    at NeovimClient.pauseNotification (/home/ecosse/.vim/plugged/coc.nvim/build/index.js:11914:21)
    at Completion.stop (/home/ecosse/.vim/plugged/coc.nvim/build/index.js:48413:14)
    at Completion.onInsertLeave (/home/ecosse/.vim/plugged/coc.nvim/build/index.js:48296:14)
    at /home/ecosse/.vim/plugged/coc.nvim/build/index.js:16533:45
    at new Promise (<anonymous>)
    at wrappedhandler (/home/ecosse/.vim/plugged/coc.nvim/build/index.js:16530:42)
    at /home/ecosse/.vim/plugged/coc.nvim/build/index.js:16507:49
    at Array.map (<anonymous>)
    at Events.fire (/home/ecosse/.vim/plugged/coc.nvim/build/index.js:16507:39)
    at NeovimClient.<anonymous> (/home/ecosse/.vim/plugged/coc.nvim/build/index.js:11514:40)
    at NeovimClient.emit (events.js:315:20)
    at NeovimClient.emitNotification (/home/ecosse/.vim/plugged/coc.nvim/build/index.js:11829:18)
    at NeovimClient.handleNotification (/home/ecosse/.vim/plugged/coc.nvim/build/index.js:11833:14)
    at NvimTransport.emit (events.js:315:20)
    at NvimTransport.parseMessage (/home/ecosse/.vim/plugged/coc.nvim/build/index.js:12019:18)
    at DecodeStream.<anonymous> (/home/ecosse/.vim/plugged/coc.nvim/build/index.js:11982:18)
```

## Describe the bug

I updated neovim today and after I type something first the autocomplete menu displays but after few seconds coc.nvim stops working completely.

## Reproduce the bug

  ```vim
set nocompatible
set runtimepath^=/home/ecosse/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
  ```

- Start (neo)vim with the command: `vim -u mini.vim`

- Operate vim.

**Done. It's reproducible with this mini.vim**

**Comment by chemzqm** [comment]
Wired, use release branch should avoid this bug.
