### ISSUE TITLE
doHover failed with Invalid key 'style' Error

### ISSUE THREAD

**Issue by damnever** [neoclide/coc.nvim#2791]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.0-1036-g5a96161e8
node version: v14.4.0
coc.nvim version: 0.0.80-c47ed1d31a
coc.nvim directory: /Users/damnever/dotfiles/vim/plugins/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2021-01-03T13:40:37.390 INFO (pid:78012) [services] - registered service "languageserver.golang"
2021-01-03T13:40:37.395 INFO (pid:78012) [services] - golang state change: stopped => starting
2021-01-03T13:40:37.396 INFO (pid:78012) [services] - registered service "languageserver.python"
2021-01-03T13:40:37.396 INFO (pid:78012) [services] - registered service "languageserver.bash"
2021-01-03T13:40:37.396 INFO (pid:78012) [services] - registered service "languageserver.clangd"
2021-01-03T13:40:37.428 INFO (pid:78012) [language-client-index] - Language server "languageserver.golang" started with 78014
2021-01-03T13:40:37.552 INFO (pid:78012) [plugin] - coc.nvim 0.0.80-c47ed1d31a initialized with node: v14.4.0 after 235ms
2021-01-03T13:40:37.554 INFO (pid:78012) [services] - golang state change: starting => running
2021-01-03T13:40:37.563 INFO (pid:78012) [services] - service languageserver.golang started
2021-01-03T13:41:05.285 INFO (pid:78012) [attach] - receive request: doHover []
2021-01-03T13:41:05.329 ERROR (pid:78012) [node-client] - request error on "nvim_call_function" [
  'coc#float#create_cursor_float',
  [
    0,
    0,
    [
      'var net.DefaultResolver *net.Resolver',
      '',
      'net.DefaultResolver on pkg.go.dev',
      '',
      'DefaultResolver is the resolver used by the package-level Lookup',
      'functions and by Dialers without a specified Resolver.',
      '',
      'net.DefaultResolver on pkg.go.dev: https://pkg.go.dev/net?utm_source=gopls#DefaultResolver'
    ],
    {
      pumAlignTop: false,
      preferTop: false,
      offsetX: 0,
      title: '',
      close: 0,
      codes: [Array],
      highlights: [Array],
      modes: [Array],
      autohide: 1
    }
  ]
] Vim(let):E5555: API call: Invalid key 'style' Error
    at $L.request (/Users/damnever/dotfiles/vim/plugins/coc.nvim/build/index.js:15:35632)
    at $L.call (/Users/damnever/dotfiles/vim/plugins/coc.nvim/build/index.js:17:6259)
    at Zx.createPopup (/Users/damnever/dotfiles/vim/plugins/coc.nvim/build/index.js:153:3372)
    at Zx.show (/Users/damnever/dotfiles/vim/plugins/coc.nvim/build/index.js:153:2526)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async AP.previewHover (/Users/damnever/dotfiles/vim/plugins/coc.nvim/build/index.js:248:13847)
    at async AP.onHover (/Users/damnever/dotfiles/vim/plugins/coc.nvim/build/index.js:248:2792)
    at async LP.cocAction (/Users/damnever/dotfiles/vim/plugins/coc.nvim/build/index.js:250:6394)
    at async $L.<anonymous> (/Users/damnever/dotfiles/vim/plugins/coc.nvim/build/index.js:129:13030)
2021-01-03T13:41:05.330 ERROR (pid:78012) [model-float] - Error on create popup: request error nvim_call_function - Vim(let):E5555: API call: Invalid key 'style'
2021-01-03T13:41:16.378 INFO (pid:78012) [attach] - receive notification: showInfo []
```

```
$ gopls version
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.6.2-0.20210101214203-2dba1e4ea05c h1:B6U2ZZ/B9vIlUpBfUAdX3Z/1LnTQNhItQZtq1PJb8y8=
```

## Describe the bug

Float window doesn't close automatically.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/Users/damnever/.vim/plugins/coc.nvim/
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim xxx.go`
  - `:call CocAction("doHover")`
  - move the cursor to another function, float window stands on the same spot
  - `:call CocAction("doHover")`
  - move the cursor
  - two float windows still standing on the same spot

**Comment by damnever** [comment]
My bad... old neovim hasn't been clean up..
