### ISSUE TITLE
[coc.nvim] Server languageserver.ccls failed to start: launching server "languageserver.ccls" using command ccls failed

### ISSUE THREAD

**Issue by theck17** [neoclide/coc.nvim#2804]
I open a file and it prompts me with a message:
[coc.nvim] Server languageserver.ccls failed to start: launching server "languageserver.ccls" using command ccls failed

## versions

vim version: NVIM v0.4.4
node version: v14.15.3
coc.nvim version: 0.0.80-a112e6621b
coc.nvim directory: /Users/ck/.config/nvim/plugged/coc.nvim
term: Apple_Terminal
platform: darwin

## Log of coc.nvim
i enter CocInfo

2021-01-10T17:18:36.975 INFO (pid:72926) [services] - registered service "languageserver.lua"
2021-01-10T17:18:36.977 INFO (pid:72926) [services] - registered service "languageserver.swift"
2021-01-10T17:18:36.978 INFO (pid:72926) [services] - registered service "languageserver.golang"
2021-01-10T17:18:36.978 INFO (pid:72926) [services] - registered service "languageserver.bash"
2021-01-10T17:18:36.978 INFO (pid:72926) [services] - registered service "languageserver.ccls"
2021-01-10T17:18:36.980 INFO (pid:72926) [services] - ccls state change: stopped => starting
2021-01-10T17:18:37.063 INFO (pid:72926) [services] - ccls state change: starting => stopped
2021-01-10T17:18:37.079 ERROR (pid:72926) [services] - Server languageserver.ccls failed to start: Launching server "languageserver.ccls" using command ccls failed.
2021-01-10T17:18:37.079 ERROR (pid:72926) [language-client-index] - Error: spawn ccls ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ccls',
  path: 'ccls',
  spawnargs: []
}
2021-01-10T17:18:37.123 INFO (pid:72926) [services] - registered service "diagnostic-languageserver"
2021-01-10T17:18:37.361 INFO (pid:72926) [coc-git] - Looking for git in: git
2021-01-10T17:18:37.401 INFO (pid:72926) [services] - registered service "highlight"
2021-01-10T17:18:37.706 INFO (pid:72926) [services] - registered service "jedi"
2021-01-10T17:18:37.757 WARN (pid:72926) [attach] - Plugin not ready when received "highlight" []
2021-01-10T17:18:37.871 INFO (pid:72926) [language-client-index] - highlight started with 73104
2021-01-10T17:18:37.943 ERROR (pid:72926) [extensions] - Error on active extension coc-translator: Error: ENOENT: no such file or directory, stat '/Users/ck/.config/coc/extensions/coc-translator-data' [Error: ENOENT: no such file or directory, stat '/Users/ck/.config/coc/extensions/coc-translator-data'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/ck/.config/coc/extensions/coc-translator-data'
}
2021-01-10T17:18:37.964 INFO (pid:72926) [plugin] - coc.nvim 0.0.80-a112e6621b initialized with node: v14.15.3 after 1093ms
2021-01-10T17:18:38.005 INFO (pid:72926) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocGitStatusChange' ]
2021-01-10T17:18:38.740 INFO (pid:72926) [attach] - receive notification: highlight []
2021-01-10T17:18:39.579 INFO (pid:72926) [attach] - receive notification: highlight []
2021-01-10T17:18:44.662 INFO (pid:72926) [attach] - receive notification: showInfo []

this is my init.vim
```vim
" if hidden is not set, TextEdit might fail.
set hidden
" Some servers have issues with backup files, see #649
set nobackup
set nowritebackup
 
" You will have bad experience for diagnostic messages when it's default 4000.
set updatetime=300
 
" don't give |ins-completion-menu| messages.
set shortmess+=c
 
" always show signcolumns
set signcolumn=yes
 
" Use tab for trigger completion with characters ahead and navigate.
" Use command ':verbose imap <tab>' to make sure tab is not mapped by other plugin.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
 
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
 
" Use <c-space> to trigger completion.
inoremap <silent><expr> <c-space> coc#refresh()
 
" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current position.
" Coc only does snippet and additional edit on confirm.
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
" Or use `complete_info` if your vim support it, like:
" inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
 
" Use `[g` and `]g` to navigate diagnostics
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)
" Remap keys for gotos
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
 
" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>
 
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
 
" Highlight symbol under cursor on CursorHold
autocmd CursorHold * silent call CocActionAsync('highlight')
 
" Remap for rename current word
nmap <leader>rn <Plug>(coc-rename)
 
" Remap for format selected region
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)
 
augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end
 
" Remap for do codeAction of selected region, ex: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)
 
" Remap for do codeAction of current line
nmap <leader>ac  <Plug>(coc-codeaction)
" Fix autofix problem of current line
nmap <leader>qf  <Plug>(coc-fix-current)
 
" Create mappings for function text object, requires document symbols feature of languageserver.
xmap if <Plug>(coc-funcobj-i)
xmap af <Plug>(coc-funcobj-a)
omap if <Plug>(coc-funcobj-i)
omap af <Plug>(coc-funcobj-a)
 
" Use `:Format` to format current buffer
command! -nargs=0 Format :call CocAction('format')
 
" Use `:Fold` to fold current buffer
command! -nargs=? Fold :call     CocAction('fold', <f-args>)
 
" use `:OR` for organize import of current buffer
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

let g:coc_global_extensions = [
 \ 'coc-css',
 \ 'coc-clangd',
 \ 'coc-cmake',
 \ 'coc-emmet',
 \ 'coc-git',
 \ 'coc-highlight',
 \ 'coc-jedi',
 \ 'coc-sh',
 \ 'coc-vimlsp',
 \ 'coc-clangd',
 \ 'coc-syntax',
 \ 'coc-pairs',
 \ 'coc-diagnostic',
 \ 'coc-explorer',
 \ 'coc-flutter-tools',
 \ 'coc-gitignore',
 \ 'coc-html',
 \ 'coc-json',
 \ 'coc-lists',
 \ 'coc-prettier',
 \ 'coc-pyright',
 \ 'coc-python',
 \ 'coc-snippets',
 \ 'coc-sourcekit',
 \ 'coc-stylelint',
 \ 'coc-syntax',
 \ 'coc-tasks',
 \ 'coc-translator',
 \ 'coc-tslint-plugin',
 \ 'coc-tsserver',
 \ 'coc-vetur',
 \ 'coc-vimlsp',
 \ 'coc-yaml',
 \ 'coc-yank']
```

**Comment by fannheyward** [comment]
> spawn ccls ENOENT

The ccls binary is not exist.
