### ISSUE TITLE
Neovim 0.5 coc-explorer bug

### ISSUE THREAD

**Issue by AdamBD** [neoclide/coc.nvim#2842]
Running into this bug when trying to use neovim 0.5 and coc-explorer: 

[coc.nvim] TypeError: Cannot use 'in' operator to search for 'getDimension' in undefined

**Comment by AdamBD** [comment]
Also seeing this error in CocInfo:

```
2021-01-23T17:51:08.160 INFO (pid:19638) [attach] - receive request: doAutocmd [ 1 ]
2021-01-23T17:51:08.163 ERROR (pid:19638) [node-client] - request error on "nvim_call_function" [ 'coc#util#clear_pos_matches', [ '^HighlightedyankRegion' ] ] Vim:E117: Unknown function: coc#util#clear_pos_matches Error
    at tM.request (/Users/ABD/.local/share/nvim/plugged/coc.nvim/build/index.js:20:34439)
    at tM.call (/Users/ABD/.local/share/nvim/plugged/coc.nvim/build/index.js:22:6259)
    at Object.<anonymous> (/Users/ABD/.config/coc/extensions/node_modules/coc-yank/lib/index.js:133:53)
    at Generator.next (<anonymous>)
    at /Users/ABD/.config/coc/extensions/node_modules/coc-yank/lib/index.js:98:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/ABD/.config/coc/extensions/node_modules/coc-yank/lib/index.js:94:12)
    at callback (/Users/ABD/.config/coc/extensions/node_modules/coc-yank/lib/index.js:131:29)
    at /Users/ABD/.local/share/nvim/plugged/coc.nvim/build/index.js:253:3056
    at LP.cocAction (/Users/ABD/.local/share/nvim/plugged/coc.nvim/build/index.js:254:6374)
2021-01-23T17:51:27.230 INFO (pid:19638) [attach] - receive notification: showInfo []
```

**Comment by GopherJ** [comment]
I think you may need to do some updates because I'm using neovim-0.5 and coc-explorer but I don't have this issue.

**Comment by chemzqm** [comment]
Upgrade your coc-explorer
