### ISSUE TITLE
Cannot install coc.nvim (0.8.0?) in windows 10

### ISSUE THREAD

**Issue by mke21** [neoclide/coc.nvim#2846]
While having used coc 0.7 before on a different win10 installation, I don't seem to be able to use it now with 0.8.0. It just refuses to work. 
## Describe the bug

So the plugin 0.8.0 does not seem to work, I can install an ealier version, but then the language servers cannot be installed as they require 0.8.0. First I got a message that index.js could not be found, that went away with using {'branch': 'master', 'do': 'yarn install --frozen-lockfile'} in the Plug entry as shown below. But it still refuses to work.

## Result from CocInfo

```
Error: javascript bundle not found, please compile code of coc.nvim by esbuild.
```

## My system and what I tried
System is Windows 10 64 bits
I use node v12.18.1.
NeoVim 4.4

part of my vimrc
```
  - OK: Environment check passed
  - WARNING: pyx command not work, some extensions may fail to work, checkout ":help |pythonx|"
  - ERROR: Javascript entry not found, please compile coc.nvim by esbuild.
  - ERROR: service could not be initialized
    - ADVICE:
      - Use command ":messages" to get error messages.
      - Open a issue at https://github.com/neoclide/coc.nvim/issues for feedback.
```
I use Plug to install things, and have tried the following Plug code in vimrc:
```
" first try
" Plug  'neoclide/coc.nvim'  
" second try
" Plug 'neoclide/coc.nvim', {'branch': 'release'}
" third try
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}
```
Checkhealth gives:
```
  - OK: Environment check passed
  - WARNING: pyx command not work, some extensions may fail to work, checkout ":help |pythonx|"
  - ERROR: Javascript entry not found, please compile coc.nvim by esbuild.
  - ERROR: service could not be initialized
    - ADVICE:
      - Use command ":messages" to get error messages.
      - Open a issue at https://github.com/neoclide/coc.nvim/issues for feedback.
```

call coc#util#install() gives:
```
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
$ node esbuild.js
 > node_modules/log4js/lib/log4js.js: error: File could not be loaded: env-ns:node_modules\log4js\lib\appenders
 ```
Building in the directory gives:
```
cd AppData\Local\nvim\plugged\coc.nvim
yarn install
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ node esbuild.js
 > node_modules/log4js/lib/log4js.js: error: File could not be loaded: env-ns:node_modules\log4js\lib\appenders
    27 │ const appenders = require("./appenders");
       ╵                           ~~~~~~~~~~~~~

1 error
Error: Build failed with 1 error:
node_modules/log4js/lib/log4js.js:27:26: error: File could not be loaded: env-ns:node_modules\log4js\lib\appenders
    at failureErrorWithLog (C:\Users\mke\AppData\Local\nvim\plugged\coc.nvim\node_modules\esbuild\lib\main.js:947:15)
    at buildResponseToResult (C:\Users\mke\AppData\Local\nvim\plugged\coc.nvim\node_modules\esbuild\lib\main.js:762:32)
    at C:\Users\mke\AppData\Local\nvim\plugged\coc.nvim\node_modules\esbuild\lib\main.js:814:20
    at handleIncomingPacket (C:\Users\mke\AppData\Local\nvim\plugged\coc.nvim\node_modules\esbuild\lib\main.js:562:9)
    at Socket.readFromStdout (C:\Users\mke\AppData\Local\nvim\plugged\coc.nvim\node_modules\esbuild\lib\main.js:478:7)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23) {
  errors: [
    {
      location: [Object],
      text: 'File could not be loaded: env-ns:node_modules\\log4js\\lib\\appenders'
    }
  ],
  warnings: []
}
Done in 0.55s.
```

# Question
So what is missing that it refuses to work? I'm guessing it's node.js configuration, but I've no idea what to do.

**Comment by chemzqm** [comment]
Use release branch to avoid compile.

**Comment by chemzqm** [comment]
I've made a fix, might works now.

**Comment by mke21** [comment]
Thanks, problem solved indeed.
