### ISSUE TITLE
TypeError: Object of type PosixPath is not JSON serializable when upgrading Jedi to v0.18.0 and try to go to definition

### ISSUE THREAD

**Issue by ahmednafies** [neoclide/coc.nvim#2847]
[coc.nvim] Jedi error: Traceback (most recent call last):
  File "completion.py", line 670, in watch
    response = self._process_request(rq)
  File "completion.py", line 614, in _process_request
    return json.dumps({"id": request["id"], "results": defs})
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable

## Describe the bug
TypeError: Object of type PosixPath is not JSON serializable when upgrading Jedi to v0.18.0

everything works fine with Jedi v0.17.2

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
set encoding=utf-8
set number
set noswapfile
set clipboard=unnamed
set spell
set spelllang=en
set spellfile=$HOME/.config/nvim/spell/en.utf-8.add

let mapleader=" "
let NERDTreeShowHidden=1
let g:indent_guides_enable_on_vim_startup = 1

source ~/.config/nvim/ftplugin/fzf-sessions.vim
source ~/.config/nvim/customterm/custom-term.vim

function! OpenTerm()
    term
    set nu!
endfunction

filetype plugin on

call plug#begin('~/.local/share/nvim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'morhetz/gruvbox'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdcommenter'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'ryanoasis/vim-devicons'
Plug 'airblade/vim-gitgutter'
Plug 'Yggdroot/indentLine'
Plug 'vim-syntastic/syntastic'
Plug 'hashivim/vim-terraform'
Plug 'sheerun/vim-polyglot'
Plug 'HerringtonDarkholme/yats.vim' 
Plug 'plasticboy/vim-markdown'
Plug 'rking/ag.vim'
Plug 'liuchengxu/eleline.vim'
Plug 'tpope/vim-fugitive'
Plug 'JamshedVesuna/vim-markdown-preview'
Plug 'kylef/apiblueprint.vim'
Plug 'heavenshell/vim-pydocstring', { 'do': 'make install' }
Plug 'machakann/vim-highlightedyank'
Plug 'junegunn/fzf'
Plug 'dominickng/fzf-session.vim'
call plug#end()

" general config
colorscheme gruvbox
syntax on

au BufNewFile,BufRead *.js,*.jsx,*.html,*.json,*.css,*.j2,*jinja2,*.md,*.tmpl set tabstop=2 softtabstop=2 shiftwidth=2 expandtab
au BufNewFile,BufRead *.vim,*.tmpl set tabstop=4 softtabstop=4 shiftwidth=4

" Indent line config
let g:indentLine_setColors = 200
let g:indentLine_char_list = ['|', '¬¶', '‚îÜ', '‚îä']

" syntastic config
let g:syntastic_python_python_exec = 'python3'

" coc config
let g:coc_global_extensions = [
  \ 'coc-python',
  \ 'coc-go',
  \ 'coc-tsserver',
  \ 'coc-html',
  \ 'coc-yaml',
  \ 'coc-snippets',
  \ 'coc-pairs',
  \ 'coc-eslint',
  \ 'coc-prettier', 
  \ 'coc-json', 
  \ ]

command! -nargs=0 Prettier :CocCommand prettier.formatFile
command! -nargs=0 Isort :CocCommand python.sortImports

nmap <silent><leader>d <Plug>(coc-definition)
nmap <silent><leader>e  <Plug>(coc-type-definition)
nmap <silent><leader>i <Plug>(coc-implementation)
nmap <silent><leader>r <Plug>(coc-references)
  ```
- Install the latest jedi
`pip install jedi`

- add coc-settings.json

```
{
  "coc.preferences.rootPatterns": [".git"],
  "python.linting.pylintEnabled": false,
  "python.linting.flake8Enabled": true,
  "python.linting.enabled": true,
  "tabnine.priority": 85,
  "python.jediEnabled": true,
  "python.autoUpdateLanguageServer": false,
  "python.formatting.provider":"black",
  "coc.preferences.formatOnSaveFiletypes": ["python"]
}

```
- Start (neo)vim with command: `vim -u mini.vim`

- Go to definition

**Comment by chemzqm** [comment]
coc-python not maintained any more

**Comment by SkyLeach** [comment]
> 
> 
> coc-python not maintained any more

Those of you who wind up here should know that [coc-pyright](https://github.com/fannheyward/coc-pyright) replaces the coc-python functionality and adds new features.
