### ISSUE TITLE
Quickfix (<Plug>(coc-fix-current) does not work anymore

### ISSUE THREAD

**Issue by petertriho** [neoclide/coc.nvim#2920]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-dev+nightly-415-g0c7610cf9
node version: v14.15.4
coc.nvim version: 0.0.80-8e7635b6a0
coc.nvim directory: /Users/peter/.local/share/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2021-02-26T08:52:34.095 INFO (pid:41770) [services] - registered service "diagnostic-languageserver"
2021-02-26T08:52:34.252 INFO (pid:41770) [language-client-index] - eslint started with 41905
2021-02-26T08:52:34.345 INFO (pid:41770) [coc-git] - Looking for git in: git
2021-02-26T08:52:34.392 INFO (pid:41770) [services] - registered service "highlight"
2021-02-26T08:52:34.515 INFO (pid:41770) [language-client-index] - highlight started with 41908
2021-02-26T08:52:34.916 INFO (pid:41770) [coc-tabnine] - Using tabnine from /Users/peter/.config/coc/extensions/coc-tabnine-data/binaries/3.3.68/x86_64-apple-darwin/TabNine
2021-02-26T08:52:35.053 INFO (pid:41770) [plugin] - coc.nvim 0.0.80-8e7635b6a0 initialized with node: v14.15.4 after 1128ms
2021-02-26T08:52:35.095 INFO (pid:41770) [services] - registered service "tsserver"
2021-02-26T08:52:35.328 INFO (pid:41770) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocGitStatusChange' ]
2021-02-26T08:52:36.282 INFO (pid:41770) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocGitStatusChange' ]
2021-02-26T08:52:38.788 INFO (pid:41770) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocDiagnosticChange' ]
2021-02-26T08:52:39.107 INFO (pid:41770) [attach] - receive notification: highlight []
2021-02-26T08:52:39.108 INFO (pid:41770) [attach] - receive notification: runCommand [ 'git.refresh' ]
2021-02-26T08:52:39.702 INFO (pid:41770) [attach] - receive notification: doQuickfix []
2021-02-26T08:52:39.705 ERROR (pid:41770) [attach] - Notification error: doQuickfix [] Error: Mode 'n' not supported
    at Uj.getSelectedRange (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:185:18801)
    at FP.getCurrentCodeActions (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:246:8615)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async FP.doQuickfix (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:246:8696)
    at async OP.cocAction (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:247:11173)
    at async eM.<anonymous> (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:129:12652)
2021-02-26T08:52:40.008 INFO (pid:41770) [attach] - receive notification: highlight []
2021-02-26T08:52:40.009 INFO (pid:41770) [attach] - receive notification: runCommand [ 'git.refresh' ]
2021-02-26T08:52:42.061 INFO (pid:41770) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocDiagnosticChange' ]
2021-02-26T08:52:46.552 INFO (pid:41770) [attach] - receive notification: highlight []
2021-02-26T08:52:46.552 INFO (pid:41770) [attach] - receive notification: runCommand [ 'git.refresh' ]
2021-02-26T08:52:48.529 INFO (pid:41770) [attach] - receive notification: highlight []
2021-02-26T08:52:48.529 INFO (pid:41770) [attach] - receive notification: runCommand [ 'git.refresh' ]
2021-02-26T08:52:50.832 INFO (pid:41770) [attach] - receive notification: doQuickfix []
2021-02-26T08:52:50.834 ERROR (pid:41770) [attach] - Notification error: doQuickfix [] Error: Mode 'n' not supported
    at Uj.getSelectedRange (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:185:18801)
    at FP.getCurrentCodeActions (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:246:8615)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async FP.doQuickfix (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:246:8696)
    at async OP.cocAction (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:247:11173)
    at async eM.<anonymous> (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:129:12652)
2021-02-26T08:52:51.140 INFO (pid:41770) [attach] - receive notification: highlight []
2021-02-26T08:52:51.140 INFO (pid:41770) [attach] - receive notification: runCommand [ 'git.refresh' ]
2021-02-26T08:53:38.726 INFO (pid:41770) [attach] - receive notification: highlight []
2021-02-26T08:53:38.727 INFO (pid:41770) [attach] - receive notification: runCommand [ 'git.refresh' ]
2021-02-26T08:53:39.167 INFO (pid:41770) [attach] - receive notification: doQuickfix []
2021-02-26T08:53:39.169 ERROR (pid:41770) [attach] - Notification error: doQuickfix [] Error: Mode 'n' not supported
    at Uj.getSelectedRange (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:185:18801)
    at FP.getCurrentCodeActions (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:246:8615)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async FP.doQuickfix (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:246:8696)
    at async OP.cocAction (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:247:11173)
    at async eM.<anonymous> (/Users/peter/.local/share/nvim/plugged/coc.nvim/build/index.js:129:12652)
2021-02-26T08:53:39.474 INFO (pid:41770) [attach] - receive notification: highlight []
2021-02-26T08:53:39.474 INFO (pid:41770) [attach] - receive notification: runCommand [ 'git.refresh' ]
2021-02-26T08:53:41.528 INFO (pid:41770) [attach] - receive notification: showInfo []
```

## Describe the bug

Cannot get quick fix to work. Was previously working, action/fix still shows up on coc-codeaction

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  nmap <leader>qf  <Plug>(coc-fix-current)
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.
- Try to do quickfox with <leader>qf

**Comment by petertriho** [comment]
Thanks, that fixed it!
