### ISSUE TITLE
Internal Javascript Error on Startup

### ISSUE THREAD

**Issue by John2143** [neoclide/coc.nvim#2947]
## Result from CocInfo

(N/A, crash on startup)

## Describe the bug

Coc.nvim does not start, and this is in `:messages` on startup

```
[coc.nvim] error: node:internal/validators:129
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:329:5)
    at validateString (node:internal/validators:129:11)
    at Object.normalize (node:path:1045:5)
    at Uj.createConfigurations (/Users/jschmidt/.config/nvim/plugged/coc.nvim/build/index.js:192:2079)
    at new Uj (/Users/jschmidt/.config/nvim/plugged/coc.nvim/build/index.js:185:9634)
    at Object.<anonymous> (/Users/jschmidt/.config/nvim/plugged/coc.nvim/build/index.js:194:1812)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}
client coc abnormal exit with: 1
```

## Reproduce the bug

mini.vim:

```
set nocompatible
filetype off

set rtp^=/coc/nvim/path/
```

nvim build info
```
$ vim --version
NVIM v0.5.0-dev+1123-g3fbff98cf

$ nvm use node
Now using node v15.11.0 (npm v7.6.0)

$ uname -a
Darwin ------- 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```

`vim -u mini.vim`

## Screenshots (optional)

https://asciinema.org/a/lcvmO8cRmF7zL4FDZMYF9ueQS

**Comment by chemzqm** [comment]
It's already fixed, please upgrade to the latest release branch of coc.nvim.
