### ISSUE TITLE
'TypeError: filetypes.includes is not a function' shows up while saving files

### ISSUE THREAD

**Issue by ingjieye** [neoclide/coc.nvim#2960]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.4
node version: v14.16.0
coc.nvim version: 0.0.80-c90a07eec8
coc.nvim directory: /Users/bernard/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2021-03-11T10:57:00.455 INFO (pid:87202) [services] - registered service "languageserver.ccls"
2021-03-11T10:57:00.458 INFO (pid:87202) [plugin] - coc.nvim 0.0.80-c90a07eec8 initialized with node: v14.16.0 after 47ms
2021-03-11T10:57:00.661 INFO (pid:87202) [attach] - receive notification: highlight []
2021-03-11T10:57:00.913 INFO (pid:87202) [attach] - receive notification: highlight []
2021-03-11T10:57:01.173 INFO (pid:87202) [attach] - receive notification: showSignatureHelp []
2021-03-11T10:57:01.442 INFO (pid:87202) [attach] - receive request: CocAutocmd [ 'BufWritePre', 1 ]
2021-03-11T10:58:20.702 INFO (pid:87202) [attach] - receive notification: highlight []
2021-03-11T10:58:23.557 INFO (pid:87202) [attach] - receive notification: showInfo []
```

## Describe the bug

```
[coc.nvim]: TypeError: filetypes.includes is not a function
    at /Users/bernard/.vim/plugged/coc.nvim/build/index.js:97524:27
    at CallbackList.invoke (/Users/bernard/.vim/plugged/coc.nvim/build/index.js:18205:39)
    at Emitter.fire (/Users/bernard/.vim/plugged/coc.nvim/build/index.js:18264:36)
    at Workspace.onBufWritePre (/Users/bernard/.vim/plugged/coc.nvim/build/index.js:33220:34)
```

Will shows up on nvim when saving files (Tested with release v0.0.79 and v0.0.80)
On release v0.0.78 doesn't have this issue.

## Reproduce the bug

- Create file `mini.vim` with：

```vim
set nocompatible
set runtimepath^=/path/to/coc.nvim
filetype plugin indent on
syntax on
set hidden
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
  ```

- Start (neo)vim with command: `vim -u mini.vim`
- Edit a file
- Save it

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/13421169/110729580-ef189d00-8259-11eb-88e2-d1177954fb7c.png)

**Comment by chemzqm** [comment]
It's already fixed, please upgrade to the latest release branch of coc.nvim.

**Comment by chemzqm** [comment]
You may have bad configuration with `coc.preferences.formatOnSaveFiletypes`

**Comment by ingjieye** [comment]
> You may have bad configuration with `coc.preferences.formatOnSaveFiletypes`

Thanks, I have an empty 'coc.preferences.formatOnSaveFiletypes' on my coc-settings.json.

Fixed it by removing 'coc.preferences.formatOnSaveFiletypes' options
