### ISSUE TITLE
[coc.nvim] code action provider not found!

### ISSUE THREAD

**Issue by dadiorchen** [neoclide/coc.nvim#2990]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v12.20.1
coc.nvim version: 0.0.80-d129f0f97e
coc.nvim directory: /Users/deanchen/.local/share/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2021-03-27T07:09:27.602 INFO (pid:54610) [services] - registered service "highlight"
2021-03-27T07:09:27.789 INFO (pid:54610) [plugin] - coc.nvim 0.0.80-d129f0f97e initialized with node: v12.20.1 after 341ms
2021-03-27T07:09:27.795 INFO (pid:54610) [language-client-index] - highlight started with 54611
2021-03-27T07:09:27.806 INFO (pid:54610) [language-client-index] - cSpell started with 54612
2021-03-27T07:09:31.456 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:09:31.466 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:09:40.060 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:09:40.150 INFO (pid:54610) [watchman] - watchman watching project: /Users/deanchen/work/corebuis
2021-03-27T07:09:40.209 INFO (pid:54610) [services] - registered service "tsserver"
2021-03-27T07:09:44.028 INFO (pid:54610) [attach] - receive notification: runCommand [ 'actions.open', 'line' ]
2021-03-27T07:09:46.849 INFO (pid:54610) [attach] - receive notification: runCommand [ 'actions.open', 'char' ]
2021-03-27T07:09:59.736 INFO (pid:54610) [attach] - receive notification: runCommand [ 'actions.open', 'char' ]
2021-03-27T07:10:11.028 INFO (pid:54610) [attach] - receive notification: codeAction [ '' ]
2021-03-27T07:10:33.859 INFO (pid:54610) [attach] - receive notification: codeAction [ '' ]
2021-03-27T07:10:48.350 INFO (pid:54610) [attach] - receive notification: codeAction [ '' ]
2021-03-27T07:11:08.097 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:11:09.075 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:11:12.594 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:11:14.598 WARN (pid:54610) [events] - Handler of BufEnter blocked more than 2s: Error
    at dq.on (/Users/deanchen/.local/share/nvim/plugged/coc.nvim/build/index.js:132:216)
    at new VersionStatus (/Users/deanchen/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:10086:51)
    at new TypeScriptServiceClient (/Users/deanchen/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:10278:26)
    at new TypeScriptServiceClientHost (/Users/deanchen/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:11174:19)
    at TsserverService.start (/Users/deanchen/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:11408:23)
    at Object.activate (/Users/deanchen/.config/coc/extensions/node_modules/coc-tsserver/lib/index.js:11549:11)
    at Object.activate (/Users/deanchen/.local/share/nvim/plugged/coc.nvim/build/index.js:223:1329)
    at Xz.activate (/Users/deanchen/.local/share/nvim/plugged/coc.nvim/build/index.js:220:7226)
    at /Users/deanchen/.local/share/nvim/plugged/coc.nvim/build/index.js:222:283
    at new Promise (<anonymous>)
2021-03-27T07:11:15.086 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:11:22.306 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:11:24.132 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:11:40.276 INFO (pid:54610) [attach] - receive notification: runCommand [ 'actions.open', 'char' ]
2021-03-27T07:12:03.535 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:12:05.858 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:12:24.611 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:12:40.487 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:12:48.924 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:12:49.304 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:13:01.169 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:13:42.192 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:13:43.199 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:13:44.796 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:13:47.540 INFO (pid:54610) [attach] - receive notification: runCommand [ 'actions.open', 'char' ]
2021-03-27T07:13:52.445 INFO (pid:54610) [attach] - receive notification: codeAction [ '' ]
2021-03-27T07:13:57.636 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:14:50.788 INFO (pid:54610) [attach] - receive notification: runCommand [ 'actions.open', 'char' ]
2021-03-27T07:14:55.346 INFO (pid:54610) [attach] - receive notification: runCommand [ 'actions.open', 'char' ]
2021-03-27T07:15:02.240 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:15:04.290 INFO (pid:54610) [attach] - receive notification: runCommand [ 'actions.open', 'char' ]
2021-03-27T07:15:15.085 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:18:45.056 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:18:47.538 INFO (pid:54610) [attach] - receive notification: runCommand [ 'actions.open', 'char' ]
2021-03-27T07:19:58.121 INFO (pid:54610) [attach] - receive notification: doAutocmd [ 1 ]
2021-03-27T07:20:01.058 INFO (pid:54610) [attach] - receive notification: showInfo []
```

## Describe the bug

When cursor is no a warning/error, failed to open the action menu

## Reproduce the bug

- Operate vim.

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/5744708/112702085-5591f200-8ecd-11eb-83b6-0a9b074298d5.png)

**Comment by chemzqm** [comment]
It's expected that There is no code action provider for current file
