### ISSUE TITLE
coc stopped close float window after "yyp"

### ISSUE THREAD

**Issue by liujoey** [neoclide/coc.nvim#3024]
## Result from CocInfo
2021-04-12T13:18:19.651 INFO (pid:37288) [services] - registered service "highlight"
2021-04-12T13:18:19.745 INFO (pid:37288) [language-client-index] - highlight started with 37289
2021-04-12T13:18:19.755 INFO (pid:37288) [plugin] - coc.nvim 0.0.80-2cece2600a initialized with node: v14.6.0 after 195ms
2021-04-12T13:18:21.405 INFO (pid:37288) [attach] - receive notification: doAutocmd [ 1 ]
2021-04-12T13:18:21.562 INFO (pid:37288) [services] - registered service "clangd"
2021-04-12T13:18:21.563 INFO (pid:37288) [services] - clangd state change: stopped => starting
2021-04-12T13:18:21.566 INFO (pid:37288) [language-client-index] - Language server "clangd" started with 37305
2021-04-12T13:18:21.591 INFO (pid:37288) [services] - clangd state change: starting => running
2021-04-12T13:18:21.594 INFO (pid:37288) [services] - service clangd started
2021-04-12T13:18:30.194 INFO (pid:37288) [attach] - receive notification: openLog []
2021-04-12T13:18:30.249 INFO (pid:37288) [attach] - receive notification: doAutocmd [ 1 ]
2021-04-12T13:18:33.120 INFO (pid:37288) [attach] - receive notification: doAutocmd [ 1 ]
2021-04-12T13:18:35.444 INFO (pid:37288) [attach] - receive notification: doAutocmd [
  2,
  {
    regcontents: [ '  std::vector<uint8_t> compressor_step_ID;' ],
    visual: false,
    inclusive: false,
    regname: '',
    operator: 'y',
    regtype: 'V'
  },
  2
]
2021-04-12T13:18:35.451 ERROR (pid:37288) [plugin] - Error on autocmd TextYankPost TypeError: doc.matchAddRanges is not a function
    at Object.<anonymous> (/Users/joey/.config/coc/extensions/node_modules/coc-yank/lib/index.js:182:35)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/joey/.config/coc/extensions/node_modules/coc-yank/lib/index.js:95:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-04-12T13:18:35.452 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at Object.<anonymous> (/Users/joey/.config/coc/extensions/node_modules/coc-yank/lib/index.js:181:26)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/joey/.config/coc/extensions/node_modules/coc-yank/lib/index.js:95:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-04-12T13:18:35.671 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at bD._append (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:157:161)
    at bD.append (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:157:345)
    at Pv.appendOutput (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:210:21177)
    at Socket.<anonymous> (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:210:20154)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
2021-04-12T13:18:35.753 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at kD.setStatusText (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:159:3338)
    at Timeout._onTimeout (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:159:2660)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)
2021-04-12T13:18:36.179 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at bD._append (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:157:161)
    at bD.append (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:157:345)
    at Pv.appendOutput (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:210:21177)
    at Socket.<anonymous> (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:210:20154)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
2021-04-12T13:18:36.179 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at bD._append (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:157:161)
    at bD.append (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:157:345)
    at Pv.appendOutput (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:210:21177)
    at Socket.<anonymous> (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:210:20154)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
2021-04-12T13:18:36.235 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at bD._append (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:157:161)
    at bD.append (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:157:345)
    at Pv.appendOutput (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:210:21177)
    at Socket.<anonymous> (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:210:20154)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
2021-04-12T13:18:36.235 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at bD._append (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:157:161)
    at bD.append (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:157:345)
    at Pv.appendOutput (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:210:21177)
    at Socket.<anonymous> (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:210:20154)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
2021-04-12T13:18:36.264 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at kD.setStatusText (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:159:3338)
    at Timeout._onTimeout (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:159:2660)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)
2021-04-12T13:18:36.542 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at C0._refresh (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:197:1738)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-04-12T13:18:38.078 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at C0.clear (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:197:4585)
    at C0.dispose (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:197:5006)
    at p0.delete (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:185:4143)
    at /Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:185:3531
    at kM.invoke (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:11229)
    at Xc.fire (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:11963)
    at Uj.onBufUnload (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:192:4155)
    at Uj.onBufCreate (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:192:2602)
    at /Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:132:283
2021-04-12T13:18:38.083 INFO (pid:37288) [attach] - receive notification: doAutocmd [ 1 ]
2021-04-12T13:18:38.193 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at kD.setStatusText (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:159:3338)
    at Timeout._onTimeout (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:159:2660)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)
2021-04-12T13:19:00.952 INFO (pid:37288) [attach] - receive notification: doAutocmd [ 1 ]
2021-04-12T13:19:04.478 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at vD.close (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:153:3866)
    at Qj.echoMessage (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:197:13622)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Timeout.<anonymous> (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:197:7746)
2021-04-12T13:19:05.314 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at vD.close (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:153:3866)
    at Qj.echoMessage (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:197:13622)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Timeout.<anonymous> (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:197:7746)
2021-04-12T13:19:06.186 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at vD.close (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:153:3866)
    at Qj.echoMessage (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:197:13622)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Timeout.<anonymous> (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:197:7746)
2021-04-12T13:19:07.175 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at C0.clear (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:197:4585)
    at C0.dispose (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:197:5006)
    at p0.delete (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:185:4143)
    at /Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:185:3531
    at kM.invoke (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:11229)
    at Xc.fire (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:11963)
    at Uj.onBufUnload (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:192:4155)
    at Uj.onBufCreate (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:192:2602)
    at /Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:132:283
2021-04-12T13:19:07.177 ERROR (pid:37288) [node-client] - resumeNotification not called within same tick: Error
    at tM.pauseNotification (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:23:4591)
    at vD.close (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:153:3866)
    at /Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:153:1313
    at /Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:132:283
    at new Promise (<anonymous>)
    at a (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:132:235)
    at /Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:131:2806
    at Array.map (<anonymous>)
    at dq.fire (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:131:2799)
    at tM.<anonymous> (/Users/joey/.config/nvim/plugged/coc.nvim/build/index.js:129:12382)
2021-04-12T13:19:07.182 INFO (pid:37288) [attach] - receive notification: doAutocmd [ 1 ]

## Describe the bug

Editing cpp code:
struct CompressorParameterSet : public gen_info {
  std::vector<uint8_t> compressor_step_ID;
}

Cursor on the line with compressor_step_ID, then yyp to duplicate the line, clangd report "Duplicate member 'compressor_step_ID', CocOpenLog show a lot errors at this point.
Continue editing to rename the var name of the pasted line, float window doesn't close. Use "c-w o" to close the float window.
From now on, coc doesn't show autocomplete anymore, any future float window will not close. Have to quit and restart nvim.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- open empty cpp code
- create a structure
struct test {
	int asdf;
	int asdf;
}
Move cursor to the second asdf to show the float window
Now move cursor, float window won't hide, autocomplete stop working. CocOpenLog shows above errors.

**Comment by liujoey** [comment]
Just realized this is a coc-yank issue, after I update coc-yank extension, problem solved.
