### ISSUE TITLE
refactor variable results in UnhandledRejection, maybe changes to the same line aren't being merged correctly?

### ISSUE THREAD

**Issue by trevorwhitney** [neoclide/coc.nvim#3037]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.4
node version: v12.18.2
coc.nvim version: 0.0.80-f0e38d6ed8
coc.nvim directory: /home/twhitney/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2021-04-19T10:13:29.515 INFO (pid:4066564) [plugin] - coc.nvim 0.0.80-f0e38d6ed8 initialized with node: v12.18.2 after 46ms
2021-04-19T10:13:29.519 INFO (pid:4066564) [services] - registered service "go"
2021-04-19T10:13:29.520 INFO (pid:4066564) [services] - gopls state change: stopped => starting
2021-04-19T10:13:30.591 INFO (pid:4066564) [services] - gopls state change: starting => running
2021-04-19T10:13:30.596 INFO (pid:4066564) [services] - service go started
2021-04-19T10:13:35.879 INFO (pid:4066564) [attach] - receive request: commandList [ 'sho', 'CocCommand sho', 14 ]
2021-04-19T10:13:37.159 INFO (pid:4066564) [attach] - receive request: commandList [ 'wo', 'CocCommand wo', 13 ]
2021-04-19T10:13:39.696 INFO (pid:4066564) [attach] - receive notification: runCommand [ 'workspace.showOutput' ]
2021-04-19T10:13:39.699 INFO (pid:4066564) [attach] - receive request: CocAutocmd [ 'BufReadCmd', 'output', 'output:///go' ]
2021-04-19T10:13:52.362 INFO (pid:4066564) [attach] - receive notification: codeAction [ 'v' ]
2021-04-19T10:13:54.661 ERROR (pid:4066564) [workspace] - Error: Overlapping edit
    at Object.applyEdits2 [as applyEdits] (/home/twhitney/.vim/plugged/coc.nvim/build/index.js:39273:15)
    at Document.applyEdits (/home/twhitney/.vim/plugged/coc.nvim/build/index.js:41920:32)
    at Workspace.applyEdit (/home/twhitney/.vim/plugged/coc.nvim/build/index.js:43330:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-04-19T10:13:54.665 ERROR (pid:4066564) [server] - unhandledRejection  Promise {
  <rejected> ResponseError2
      at handleResponse (/home/twhitney/.vim/plugged/coc.nvim/build/index.js:13742:38)
      at processMessageQueue (/home/twhitney/.vim/plugged/coc.nvim/build/index.js:13597:11)
      at Immediate.<anonymous> (/home/twhitney/.vim/plugged/coc.nvim/build/index.js:13583:9)
      at processImmediate (internal/timers.js:456:21) {
    code: 0,
    data: undefined
  }
} ResponseError2
    at handleResponse (/home/twhitney/.vim/plugged/coc.nvim/build/index.js:13742:38)
    at processMessageQueue (/home/twhitney/.vim/plugged/coc.nvim/build/index.js:13597:11)
    at Immediate.<anonymous> (/home/twhitney/.vim/plugged/coc.nvim/build/index.js:13583:9)
    at processImmediate (internal/timers.js:456:21) {
  code: 0,
  data: undefined
}
2021-04-19T10:14:06.525 INFO (pid:4066564) [attach] - receive notification: showInfo []
```

## Describe the bug

It appears that the merging of changes to the same line is broken. In this example, the language server (`gopls`) issued an a `workspace/applyEdit` request with 2 `documentChanges` operating on the same line. This caused coc.nvim to report an overlapping edits error, and did not apply the chages.

```
[Trace - 10:13:54 AM] Sending request 'workspace/executeCommand - (2)'.
Params: {
    "command": "gopls.apply_fix",
    "arguments": [
        {
            "Fix": "extract_variable",
            "URI": "file:///home/twhitney/go-example/main.go",
            "Range": {
                "start": {
                    "line": 7,
                    "character": 2
                },
                "end": {
                    "line": 7,
                    "character": 34
                }
            }
        }
    ]
}


[Trace - 10:13:54 AM] Received request 'workspace/applyEdit - (5)'.
Params: {
    "edit": {
        "documentChanges": [
            {
                "textDocument": {
                    "version": 1,
                    "uri": "file:///home/twhitney/go-example/main.go"
                },
                "edits": [
                    {
                        "range": {
                            "start": {
                                "line": 7,
                                "character": 2
                            },
                            "end": {
                                "line": 7,
                                "character": 34
                            }
                        },
                        "newText": "x0"
                    }
                ]
            },
            {
                "textDocument": {
                    "version": 1,
                    "uri": "file:///home/twhitney/go-example/main.go"
                },
                "edits": [
                    {
                        "range": {
                            "start": {
                                "line": 7,
                                "character": 2
                            },
                            "end": {
                                "line": 7,
                                "character": 2
                            }
                        },
                        "newText": "x0 := fmt.Sprintf(\"hello %s\", \"steve\")\n  "
                    }
                ]
            }
        ]
    }
}


[Trace - 10:13:54 AM] Sending response 'workspace/applyEdit - (5)'. Processing request took 4ms
Result: {
    "applied": false
}


[Trace - 10:13:54 AM] Received response 'workspace/executeCommand - (2)' in 7ms. Request failed:  (0).
[Error  - 10:13:54 AM] Request workspace/executeCommand failed.
  Message: 
  Code: 0 
```

## Reproduce the bug

- copy the contents of this [gist](https://gist.github.com/trevorwhitney/b8541b41e8d0ce86fd726c7bee26ebdc) to local files
- open `main.go` with the mini vim config: `nvim -u mini.vim main.go`
- highlight the text `fmt.Sprintf("hello %s", "trevor")`, and executed the command: `:'<,'>call CocActionAsync("codeAction", visualmode())`
- Choose the option to "Extract Variable"
- Should get an UnhandeledRejection error (that appears to result from an OverlappingEdit error?)

Expected Behavior: the variable is extracted. VScode gets the same response from the language server but handles it correctly without error, so I don't believe it's an issue with `gopls`.

**Comment by fannheyward** [comment]
Caused by https://github.com/neoclide/coc.nvim/issues/2203, will dig into this.

**Comment by fannheyward** [comment]
@chemzqm I've revert 5699963, both this and #2203 are solved. Maybe coc should not merge the edits.
