### ISSUE TITLE
How to complete function arguments?

### ISSUE THREAD

**Issue by theFool32** [neoclide/coc.nvim#308]
It seems no function argument completion or suggestion when using ccls and MPLS.
Any configuration to work like vscode or ncm2-jedi?

Thanks.

**Comment by theFool32** [comment]
Sorry for late response due to vacation.

ccls works after `<c-y>`, how about the way like in vscode: complete the function name, then give suggestion after type `()`

And MPLS seems broken today. :cry: 
```
## versions

vim version: NVIM v0.3.1
node version: v8.9.0
coc.nvim version: 0.0.43
term: screen-256color
platform: linux

## Error messages
UnhandledRejection: Object reference not set to an instance of an object.
Error: Object reference not set to an instance of an object.
    at handleResponse (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.setImmediate [as _onImmediate] (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
## Output channel: languageserver.MPLS
```

```
:messages

[coc.nvim] Specified argument was out of the range of valid values.
[coc.nvim] Error output from languageserver.MPLS: Server initialization failed.
  Message: Specified argument was out of the range of valid values.
  Code: -32000
   at System.ReadOnlySpan`1..ctor(Void* pointer, Int32 length)
   at Interop.Sys.DirectoryEntry.GetName(Span`1 buffer)
   at System.IO.Enumeration.FileSystemEntry.get_FileName()
   at System.IO.Enumeration.FileSystemEnumerableFactory.<>c__DisplayClass3_0.<UserFiles>b__1(FileSystemEntr
y& entry)
   at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator.ShouldIncludeEntry(FileSystemEntry& e
ntry)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Analysis.Infrastructure.PathUtils.EnumerateFiles(String root, String pattern, B
oolean recurse, Boolean fullPaths)+MoveNext() in /home/lijie/old/proj/dev/python-language-server/src/Analys
is/Engine/Impl/Infrastructure/PathUtils.cs:line 289
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.ReloadModulePaths(IEnumerable`1& rootPaths) in /home/li
jie/old/proj/dev/python-language-server/src/Analysis/Engine/Impl/PythonAnalyzer.cs:line 132
   at Microsoft.Python.LanguageServer.Implementation.Server.DoInitializeAsync(InitializeParams params, Canc
ellationToken token) in /home/lijie/old/proj/dev/python-language-server/src/LanguageServer/Impl/Implementat
ion/Server.cs:line 391
   at Microsoft.Python.LanguageServer.Implementation.Server.Initialize(InitializeParams params, Cancellatio
nToken cancellationToken) in /home/lijie/old/proj/dev/python-language-server/src/LanguageServer/Impl/Implem
entation/Server.cs:line 165
   at Microsoft.Python.LanguageServer.Implementation.LanguageServer.Initialize(JToken token, CancellationTo
ken cancellationToken) in /home/lijie/old/proj/dev/python-language-server/src/LanguageServer/Impl/LanguageS
erver.Lifetime.cs:line 49
[coc.nvim] Server MPLS failed to start: Specified argument was out of the range of valid values.
[vim-node-coc]: UnhandledRejection: Object reference not set to an instance of an object.
Error: Object reference not set to an instance of an object.
    at handleResponse (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.setImmediate [as _onImmediate] (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/main.js
:247:13)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by chemzqm** [comment]
> ccls works after `<c-y>`,

Checkout https://github.com/neoclide/coc.nvim/wiki/Using-snippets

> how about the way like in vscode: complete the function name, then give suggestion after type ()

Function signature help should just works, it should be echoed in cmdline but could be overwrite by other echo message. Consider upgrade to neovim 0.3.2 for better experience.
