### ISSUE TITLE
Some language servers don't work at home directory

### ISSUE THREAD

**Issue by zuoxinyu** [neoclide/coc.nvim#3102]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v14.4.0
coc.nvim version: 0.0.80-971c5f81b4
coc.nvim directory: /Users/someone/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2021-05-23T01:30:12.953 INFO (pid:15976) [services] - registered service "languageserver.golang"
2021-05-23T01:30:12.956 INFO (pid:15976) [services] - registered service "languageserver.ccls"
2021-05-23T01:30:12.956 INFO (pid:15976) [services] - registered service "languageserver.dockerfile"
2021-05-23T01:30:12.956 INFO (pid:15976) [services] - registered service "languageserver.bash"
2021-05-23T01:30:12.956 INFO (pid:15976) [services] - registered service "languageserver.vue"
2021-05-23T01:30:12.956 INFO (pid:15976) [services] - registered service "languageserver.cmake"
2021-05-23T01:30:12.956 INFO (pid:15976) [services] - registered service "languageserver.vimls"
2021-05-23T01:30:13.161 INFO (pid:15976) [coc-git] - Looking for git in: git
2021-05-23T01:30:13.240 INFO (pid:15976) [services] - registered service "highlight"
2021-05-23T01:30:13.431 INFO (pid:15976) [language-client-index] - highlight started with 15998
2021-05-23T01:30:13.660 INFO (pid:15976) [plugin] - coc.nvim 0.0.80-971c5f81b4 initialized with node: v14.4.0 after 841ms
2021-05-23T01:30:13.662 INFO (pid:15976) [attach] - receive notification: runCommand [ 'explorer.internal.didVimEvent', 'CocGitStatusChange' ]
2021-05-23T01:30:14.617 INFO (pid:15976) [attach] - receive notification: runCommand [ 'explorer.internal.didVimEvent', 'BufWipeout', 2 ]
2021-05-23T01:30:14.626 INFO (pid:15976) [attach] - receive notification: runCommand [ 'explorer.internal.didVimEvent', 'BufDelete', 1 ]
2021-05-23T01:30:14.626 INFO (pid:15976) [attach] - receive notification: runCommand [ 'explorer.internal.didVimEvent', 'BufWipeout', 1 ]
2021-05-23T01:30:14.750 INFO (pid:15976) [attach] - receive notification: runCommand [ 'explorer.internal.didVimEvent', 'CocDiagnosticChange' ]
2021-05-23T01:30:14.871 INFO (pid:15976) [attach] - receive notification: runCommand [ 'explorer.internal.didVimEvent', 'CocGitStatusChange' ]
2021-05-23T01:30:14.938 INFO (pid:15976) [services] - registered service "json"
2021-05-23T01:30:14.939 INFO (pid:15976) [services] - Json language server state change: stopped => starting
2021-05-23T01:30:14.948 INFO (pid:15976) [language-client-index] - json started with 16032
2021-05-23T01:30:16.294 INFO (pid:15976) [attach] - receive request: doHover []
2021-05-23T01:30:16.296 ERROR (pid:15976) [attach] - Request error: doHover [] Error: hover provider not found for current buffer, your language server doesn't support it.
    at MP.checkProvier (/Users/someone/.vim/plugged/coc.nvim/build/index.js:246:1043)
    at MP.onHover (/Users/someone/.vim/plugged/coc.nvim/build/index.js:246:2725)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async qP.cocAction (/Users/someone/.vim/plugged/coc.nvim/build/index.js:247:11564)
    at async nM.<anonymous> (/Users/someone/.vim/plugged/coc.nvim/build/index.js:129:13118)
2021-05-23T01:30:17.479 INFO (pid:15976) [attach] - receive notification: highlight []
2021-05-23T01:30:23.542 INFO (pid:15976) [attach] - receive notification: showInfo []

```
## Describe the bug

After weekly updating, found `coc-json` and `vim-language-server` not working at my home dir. Even my home dir contains a `.git` directory.

And found this commit: [feat(language-client): avoid homedir as rootPath](https://github.com/neoclide/coc.nvim/commit/7904a9e7dff16354ba91644647b4871722879743) modified the original behavior.

Some LSPs like `vim-language-server` or `coc-json` should work at home directory intentionally.

There should be a configuration entry in `coc-settings.json` to make those LSP clients be able to scan the home dir, or maybe just revert this commit.

## Reproduce the bug
1. Update `coc.nvim` to latest
2. Install the `coc-json` extension if there is not
3. Type `:CocConfig` to edit the `coc-settings.json`, 
4. Keep in normal mode, move cursor to any key, and press `K` to invoke `CocAction('dohover`)`

**Comment by chemzqm** [comment]
We need support rootPath to be `null`, instead of avoid start language server.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by oblitum** [comment]
@chemzqm it seems 39c14a3 has addressed the topic at https://github.com/sumneko/lua-language-server/issues/480 properly? If so, I think possibly some language server setup entries in the wiki may need clean up removing suggested `"ignoredRootPaths"` which isn't necessary anymore.

**Comment by oblitum** [comment]
I've updated the wiki accordingly.

**Comment by chemzqm** [comment]
Yes, thank you.
