### ISSUE TITLE
Completion stopped working after update

### ISSUE THREAD

**Issue by kabasakalis** [neoclide/coc.nvim#311]
## versions

vim version: NVIM v0.3.1
node version: v8.9.0
coc.nvim version: 0.0.43
term: undefined
platform: win32
 

## Log:
```
2018-12-31T02:15:48.987 INFO (pid:66576) [model-complete] - Results from: snippets,java,around
2018-12-31T02:15:48.997 ERROR (pid:66576) [completion] - Error: request nvim_call_function - Vim:E119: Not enough arguments for function: coc#_do_complete
    at events_1.EventEmitter.constructor.(anonymous function).Promise.transport.request (C:\snapshot\coc.nvim\node_modules\@chemzqm\neovim\lib\api\Base.js:33:28)
    at Transport.parseMessage (C:\snapshot\coc.nvim\node_modules\@chemzqm\neovim\lib\utils\transport.js:108:17)
    at DecodeStream.events_1.EventEmitter.constructor.decodeStream.on (C:\snapshot\coc.nvim\node_modules\@chemzqm\neovim\lib\utils\transport.js:41:18)
    at emitOne (events.js:116:13)
    at DecodeStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at DecodeStream.Readable.push (_stream_readable.js:208:10)
    at DecodeStream.Transform.push (_stream_transform.js:147:32)
    at DecodeBuffer.__dirname.DecodeStream.decoder.push (C:\snapshot\coc.nvim\node_modules\@chemzqm\neovim\node_modules\msgpack-lite\lib\decode-stream.js:24:12)
2018-12-31T02:15:49.325 INFO (pid:66576) [model-complete] - Results from: snippets,java,around
```
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
Not including CocInfo as it's huge.

**Describe the bug**
Completion stopped working after coc.vim update. No completion whatsoever.
Thanks in advance.

**Comment by chemzqm** [comment]
Run `:call coc#util#install()` to download latest release.

**Comment by kabasakalis** [comment]
Thank you, I got back to a working completion. But I want to give you some information, because I did it manually.
First, `yarn install` tells me about a package not supported for windows, but it says
optional so I hope it's not a problem.
```
spiros@DESKTOP-QPB6GAK C:\Users\spiros\.cache\vimfiles\repos\github.com\neoclide\coc.nvim
# yarn install
yarn install v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
**info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.**
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ yarn clean && yarn build
yarn run v1.12.3
$ rimraf lib build
Done in 0.56s.
yarn run v1.12.3
$ tsc -p tsconfig.json
Done in 12.03s.
Done in 22.91s.
```

 I ran `:call coc#util#install()` as you instructed and got 
`client coc not running` in neovim command line, so I decided to run manually `install.cmd`, and
got this:
```
spiros@DESKTOP-QPB6GAK C:\Users\spiros\.cache\vimfiles\repos\github.com\neoclide
\coc.nvim                                                                       
# install.cmd                                                                   
Determining latest release                                                      
                                                                                
                                                                                
    Directory:                                                                  
    C:\Users\spiros\.cache\vimfiles\repos\github.com\neoclide\coc.nvim          
                                                                                
                                                                                
Mode                LastWriteTime         Length Name                           
----                -------------         ------ ----                           
d-----       31/12/2018     09:20                build                          
Dowloading latest release                                                       
Stop-Process : Cannot find a process with the name "coc-win". Verify the        
process name and call the cmdlet again.                                         
At line:1 char:654                                                              
+ ... ke-WebRequest $download -Out $zip;;Stop-Process -Name coc-win;Remove- ... 
+                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~             
    + CategoryInfo          : ObjectNotFound: (coc-win:String) [Stop-Process],  
    ProcessCommandException                                                     
    + FullyQualifiedErrorId : NoProcessFoundForGivenName,Microsoft.PowerShell.  
   Commands.StopProcessCommand                                                  
 ```                                      
But; the zipped `coc-win.exe` was already in root folder of coc.vim, so I just copied it to `bin` folder
and completion works ok now. I know  this process should be automatic but   `:call coc#util#install()` did not work for me. Maybe you can add instructions for manual installation of  `coc-win.exe`.
Thank you for your help.
