### ISSUE TITLE
Coc does not detect Clangd Implementation provider

### ISSUE THREAD

**Issue by Erudyx** [neoclide/coc.nvim#3112]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.3
node version: v10.19.0
coc.nvim version: 0.0.80-971c5f81b4
coc.nvim directory: /home/.../.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2021-05-26T21:31:59.841 INFO (pid:4083) [services] - registered service "languageserver.clangd"
2021-05-26T21:31:59.843 INFO (pid:4083) [services] - registered service "languageserver.haskell"
2021-05-26T21:31:59.845 INFO (pid:4083) [plugin] - coc.nvim 0.0.80-971c5f81b4 initialized with node: v10.19.0 after 38ms
2021-05-26T21:32:03.924 INFO (pid:4083) [services] - clangd state change: stopped => starting
2021-05-26T21:32:03.928 INFO (pid:4083) [language-client-index] - Language server "languageserver.clangd" started with 4109
2021-05-26T21:32:03.943 INFO (pid:4083) [services] - clangd state change: starting => running
2021-05-26T21:32:03.950 INFO (pid:4083) [services] - service languageserver.clangd started
2021-05-26T21:32:08.199 INFO (pid:4083) [attach] - receive notification: jumpImplementation []
2021-05-26T21:32:08.201 ERROR (pid:4083) [attach] - Notification error: jumpImplementation [] Error: implementation provider not found for current buffer, your language server doesn't support it.
    at MP.checkProvier (/home/erudyx/.config/nvim/plugged/coc.nvim/build/index.js:246:1043)
    at MP.gotoImplementation (/home/erudyx/.config/nvim/plugged/coc.nvim/build/index.js:246:5267)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2021-05-26T21:32:16.612 INFO (pid:4083) [attach] - receive notification: showInfo []
```

## Describe the bug

When trying to use "Jump to implementation" feature, coc throw an error like there is no "implementation server" on my language server ([there is](https://github.com/clangd/clangd/issues/789))

## Reproduce the bug

Using neovim with Clangd and coc.vim:

coc-settings.json:
  ```json
{
    "languageserver": {
        "clangd": {
            "command": "clangd",
            "args": [
                "--background-index",
                "-clang-tidy",
                "--suggest-missing-includes",
                "--header-insertion=iwyu"
            ],
            "rootPatterns": [
                "compile_flags.txt",
                "compile_commands.json",
                ".vim/",
                ".git/",
                ".hg/"
            ],
            "filetypes": [
                "c",
                "cpp",
                "objc",
                "objcpp"
            ]
        }
   }
}

  ```
init.vim:

```vim
nmap <silent> gi <Plug>(coc-implementation)
```

- Open a c file with neovim:
- the file should have a main, and another function called "test" for the example. main should call `test`.
- place the curser over the call of `test` in `main`, and in normal mode, press ``gi``

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by fannheyward** [comment]
<img width="302" alt="截屏2021-05-28 上午11 23 01" src="https://user-images.githubusercontent.com/345274/119924942-13f1f600-bfa7-11eb-8dfb-cd72d50fd15f.png">

 From the issue implementation was added support in clangd 12, but it doesn't work, same as VSCode + clangd.

**Comment by mingyuejingque** [comment]
please try using clangd-13, It works OK.
