### ISSUE TITLE
[coc.nvim]: Error on notification "jumpDefinition": current buffer xxx not attached

### ISSUE THREAD

**Issue by ssh352** [neoclide/coc.nvim#3122]
## versions

vim version: NVIM v0.4.4
node version: v16.2.0
coc.nvim version: 0.0.80-825a54d780
coc.nvim directory: /Users/zhang/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2021-06-03T13:48:27.687 INFO (pid:62557) [attach] - receive request: detach []
2021-06-03T13:48:27.689 WARN (pid:62557) [attach] - Plugin not ready when received "detach" []
2021-06-03T13:48:29.098 WARN (pid:62557) [attach] - Plugin not ready when received "registNotification" [ 'cquery', '$cquery/publishSemanticHighlighting' ]
2021-06-03T13:48:29.099 WARN (pid:62557) [attach] - Plugin not ready when received "registNotification" [ 'cquery', '$cquery/setInactiveRegions' ]
2021-06-03T13:48:29.099 WARN (pid:62557) [attach] - Plugin not ready when received "registNotification" [ 'ccls', '$ccls/publishSemanticHighlight' ]
2021-06-03T13:48:29.099 WARN (pid:62557) [attach] - Plugin not ready when received "registNotification" [ 'ccls', '$ccls/publishSkippedRanges' ]
2021-06-03T13:48:29.312 INFO (pid:62557) [services] - registered service "languageserver.ccls"
2021-06-03T13:48:29.512 INFO (pid:62557) [services] - registered service "highlight"
2021-06-03T13:48:29.548 INFO (pid:62557) [language-client-index] - highlight started with 62560
2021-06-03T13:48:29.638 INFO (pid:62557) [coc-java] - Using java from /Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home, version: 11
2021-06-03T13:48:29.711 INFO (pid:62557) [plugin] - coc.nvim 0.0.80-825a54d780 initialized with node: v16.2.0 after 596ms
2021-06-03T13:48:29.732 INFO (pid:62557) [coc-java] - JDT Language Server starting at /Users/zhang
2021-06-03T13:48:29.733 INFO (pid:62557) [services] - registered service "java"
2021-06-03T13:48:29.738 INFO (pid:62557) [language-client-index] - Language server "java" started with 62561
2021-06-03T13:48:29.739 INFO (pid:62557) [attach] - receive notification: registNotification [ 'cquery', '$cquery/publishSemanticHighlighting' ]
2021-06-03T13:48:29.739 INFO (pid:62557) [attach] - receive notification: registNotification [ 'cquery', '$cquery/setInactiveRegions' ]
2021-06-03T13:48:29.740 INFO (pid:62557) [attach] - receive notification: registNotification [ 'ccls', '$ccls/publishSemanticHighlight' ]
2021-06-03T13:48:29.740 INFO (pid:62557) [attach] - receive notification: registNotification [ 'ccls', '$ccls/publishSkippedRanges' ]
2021-06-03T13:48:34.009 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:48:34.779 INFO (pid:62557) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufDelete', 375 ]
2021-06-03T13:48:34.781 INFO (pid:62557) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufDelete', 375 ]
2021-06-03T13:48:36.168 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:48:37.474 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:48:38.063 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:48:38.845 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:48:42.030 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:48:42.950 INFO (pid:62557) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocDiagnosticChange' ]
2021-06-03T13:48:43.142 INFO (pid:62557) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocDiagnosticChange' ]
2021-06-03T13:48:44.775 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:48:45.712 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:48:49.049 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:48:49.581 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:48:50.299 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:48:50.683 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:48:51.279 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:12.561 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:13.450 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:14.801 INFO (pid:62557) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocDiagnosticChange' ]
2021-06-03T13:49:15.164 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:16.176 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:16.641 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:18.347 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:19.308 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:19.751 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:21.754 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:24.035 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:25.157 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:29.764 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:30.665 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:32.026 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:33.499 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:34.309 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:34.957 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:35.642 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:49:36.386 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:39.897 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:41.489 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:42.050 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:42.703 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:43.169 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:43.631 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:44.778 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:47.600 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:49.551 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:50.101 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:50.658 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:51.179 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:51.877 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:52.744 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:53.539 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:54.172 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:54.684 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:55.311 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:56.123 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:56.609 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:57.418 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:57.850 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:51:59.372 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:05.670 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:07.426 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:08.635 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:09.045 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:11.801 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:12.229 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:13.130 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:13.625 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:14.146 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:15.059 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:16.572 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:17.176 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:17.607 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:18.085 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:29.655 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:30.156 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:30.909 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:31.395 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:32.907 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:37.099 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:37.462 INFO (pid:62557) [attach] - receive notification: jumpDefinition []
2021-06-03T13:52:37.464 ERROR (pid:62557) [attach] - Notification error: jumpDefinition [] Error: current buffer 191 not attached
    at MP.getCurrentState (/Users/zhang/.vim/plugged/coc.nvim/build/index.js:247:562)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MP.gotoDefinition (/Users/zhang/.vim/plugged/coc.nvim/build/index.js:246:3682)
    at async qP.cocAction (/Users/zhang/.vim/plugged/coc.nvim/build/index.js:247:11564)
    at async nM.<anonymous> (/Users/zhang/.vim/plugged/coc.nvim/build/index.js:129:12652)
2021-06-03T13:52:37.771 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:52:58.463 INFO (pid:62557) [attach] - receive request: fillDiagnostics [ 191 ]
2021-06-03T13:52:58.885 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:53:02.674 INFO (pid:62557) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufDelete', 376 ]
2021-06-03T13:53:02.675 INFO (pid:62557) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufDelete', 376 ]
2021-06-03T13:53:02.678 INFO (pid:62557) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_1', 'BufWipeout', 376 ]
2021-06-03T13:53:02.678 INFO (pid:62557) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'BufWipeout', 376 ]
2021-06-03T13:53:03.138 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:53:37.683 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:53:38.419 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:53:38.743 INFO (pid:62557) [attach] - receive notification: jumpDefinition []
2021-06-03T13:53:38.744 ERROR (pid:62557) [attach] - Notification error: jumpDefinition [] Error: current buffer 191 not attached
    at MP.getCurrentState (/Users/zhang/.vim/plugged/coc.nvim/build/index.js:247:562)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MP.gotoDefinition (/Users/zhang/.vim/plugged/coc.nvim/build/index.js:246:3682)
    at async qP.cocAction (/Users/zhang/.vim/plugged/coc.nvim/build/index.js:247:11564)
    at async nM.<anonymous> (/Users/zhang/.vim/plugged/coc.nvim/build/index.js:129:12652)
2021-06-03T13:53:39.051 INFO (pid:62557) [attach] - receive notification: highlight []
2021-06-03T13:54:47.109 INFO (pid:62557) [attach] - receive notification: showInfo []

## Describe the bug

working on a java project, gd got the following error

[coc.nvim]: Error on notification "jumpDefinition": current buffer 191 not attached

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
Debug https://github.com/neoclide/coc.nvim/blob/master/src/model/document.ts#L102

**Comment by AaronM04** [comment]
I am still getting this issue, this time with coc-python. What is the solution?

**Comment by ssh352** [comment]
no solution yet.
