### ISSUE TITLE
server languageserver.ccls failed to start

### ISSUE THREAD

**Issue by laoshaw** [neoclide/coc.nvim#3124]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.1 8012269
node version: v14.17.0
coc.nvim version: 0.0.80-825a54d780
coc.nvim directory: /home/test/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2021-06-03T16:11:30.904 INFO (pid:121495) [services] - registered service "languageserver.ccls"
2021-06-03T16:11:30.909 INFO (pid:121495) [services] - ccls state change: stopped => starting
2021-06-03T16:11:30.910 INFO (pid:121495) [services] - registered service "languageserver.lua"
2021-06-03T16:11:30.910 INFO (pid:121495) [services] - registered service "languageserver.golang"
2021-06-03T16:11:30.948 INFO (pid:121495) [plugin] - coc.nvim 0.0.80-825a54d780 initialized with node: v14.17.0 after 122ms
2021-06-03T16:11:30.955 INFO (pid:121495) [language-client-index] - Language server "languageserver.ccls" started with 121514
2021-06-03T16:11:31.004 INFO (pid:121495) [services] - ccls state change: starting => stopped
2021-06-03T16:11:31.005 ERROR (pid:121495) [services] - Server languageserver.ccls failed to start: Uh [Error]: invalid params of initialize: expected array for /workspaceFolders
    at Ry (/home/test/.vim/plugged/coc.nvim/build/index.js:27:224)
    at In (/home/test/.vim/plugged/coc.nvim/build/index.js:26:12534)
    at Immediate.<anonymous> (/home/test/.vim/plugged/coc.nvim/build/index.js:26:12384)
    at processImmediate (internal/timers.js:462:21) {
  code: -32602,
  data: undefined
}
2021-06-03T16:11:33.965 INFO (pid:121495) [attach] - receive notification: showInfo []

```

## Describe the bug

I saw below red error msg inside vim for a few use cases.

1. when I `cd ~ && vim x.cpp`
2. when I do `cd some-path && vim /tmp/x.cpp`
3. however for many directories I can do `cd some-path && vim x.cpp` without errors at all.

![1](https://user-images.githubusercontent.com/18351761/120713705-e534bd80-c487-11eb-96c0-7726592753dc.png)

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

Use the above minimal .vim file and the result is the same. 

## Screenshots (optional)
same-as-above

**Comment by chemzqm** [comment]
Your configuration is broken

**Comment by laoshaw** [comment]
I used the minimal setting right at https://github.com/neoclide/coc.nvim/wiki/Language-servers#ccobjective-c

```
"languageserver": {
  "ccls": {
    "command": "ccls",
    "filetypes": ["c", "cc", "cpp", "c++", "objc", "objcpp"],
    "rootPatterns": [".ccls", "compile_commands.json", ".git/", ".hg/"],
    "initializationOptions": {
        "cache": {
          "directory": "/tmp/ccls"
        }
      }
  }
}
```

use the default clangd on the same page does work well, I have been using ccls with coc.nvim for quite a while and now I will have to switch to clangd 
it worked well in the past for more than one year.

**Comment by chemzqm** [comment]
Upgrade your ccls, it should support workspaceFolders as null

**Comment by laoshaw** [comment]
just upgraded ccls to the newest release 20210330, using the minimal coc-settings.json above, the same error exists.

**Comment by chemzqm** [comment]
ccls should fix this error since workspaceFolders could be null https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize, or avoid start edit your c files from your home folder since it could be too big.
