### ISSUE TITLE
forcing ccls to work in certain filetypes

### ISSUE THREAD

**Issue by HearseDev** [neoclide/coc.nvim#3132]
## Result from CocInfo
```
  undefined## versions                                                                                                            │  #include <af:WW>
                                                                                                                                  │~
  vim version: NVIM v0.4.4                                                                                                        │~
  node version: v14.16.0                                                                                                          │~
  coc.nvim version: 0.0.80-69e029ed9e                                                                                             │~
  coc.nvim directory: /Users/hearse/.config/nvim/autoload/plugged/coc.nvim                                                       │~
  term: Apple_Terminal                                                                                                            │~
  platform: darwin                                                                                                                │~
                                                                                                                                  │~
  ## Log of coc.nvim                                                                                                              │~
                                                                                                                                  │~
  2021-06-04T14:54:49.471 INFO (pid:8279) [services] - registered service "languageserver.ccls"                                   │~
  2021-06-04T14:54:49.476 INFO (pid:8279) [services] - ccls state change: stopped => starting                                     │~
  2021-06-04T14:54:49.479 INFO (pid:8279) [plugin] - coc.nvim 0.0.80-69e029ed9e initialized with node: v14.16.0 after 68ms        │~
  2021-06-04T14:54:49.485 INFO (pid:8279) [language-client-index] - Language server "languageserver.ccls" started with 8282       │~
  2021-06-04T14:54:49.512 INFO (pid:8279) [services] - ccls state change: starting => running                                     │~
  2021-06-04T14:54:49.520 INFO (pid:8279) [services] - service languageserver.ccls started                                        │~
  2021-06-04T14:54:50.171 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:55:15.589 INFO (pid:8279) [attach] - receive notification: showInfo []                                            │~
  2021-06-04T14:55:15.600 INFO (pid:8279) [attach] - receive request: CocAutocmd [ 'BufReadCmd', 'output', 'output:///info' ]     │~
  2021-06-04T14:55:16.133 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:55:54.453 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:55:54.454 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:55:55.277 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:55:55.761 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:55:55.972 INFO (pid:8279) [attach] - receive notification: rangeSelect [ '', true ]                               │~
  2021-06-04T14:55:55.975 ERROR (pid:8279) [attach] - Notification error: rangeSelect [ '', true ] Error: selectionRange provider │~
      at MP.checkProvier (/Users/hearse/.config/nvim/autoload/plugged/coc.nvim/build/index.js:246:1043)                          │~
      at MP.selectRange (/Users/hearse/.config/nvim/autoload/plugged/coc.nvim/build/index.js:246:13925)                          │~
      at processTicksAndRejections (internal/process/task_queues.js:93:5)                                                         │~
      at async qP.cocAction (/Users/hearse/.config/nvim/autoload/plugged/coc.nvim/build/index.js:247:11564)                      │~
      at async nM.<anonymous> (/Users/hearse/.config/nvim/autoload/plugged/coc.nvim/build/index.js:129:12652)                    │~
  2021-06-04T14:55:56.279 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:55:59.007 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:56:00.609 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:56:01.635 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:56:03.362 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:56:03.824 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:56:05.086 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:56:06.269 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:56:06.923 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:56:20.413 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:56:21.047 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:56:21.800 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:56:22.141 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:56:24.129 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:57:18.491 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:57:20.156 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:57:22.775 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:57:24.628 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
  2021-06-04T14:57:27.900 INFO (pid:8279) [attach] - receive notification: highlight []                                           │~
 V-LINE  info                                                                                    unix | utf-8 | log    1%    1:20   tweak.xm                                        100%    1:15 
:vertical resize +100 
-- VISUAL LINE --recording @q                                                                                                                                                         1      
```

## Describe the bug

When trying to make .xm files work as cpp and using ccls. I get ```source languageserver.ccls timeout after 5000ms``` at the bottom. ccls works fine for regular c family files such as .cpp. I get no snippets and no code completion.

I have latest ccls installed from brew and latest coc. 

## Reproduce the bug

install ccls from brew
install Nvim from brew
install coc from vim-Plug

in my init.vim I have added these 2 commands to make .xm files work: 
```
autocmd BufNewFile,BufRead *.xm set filetype=cpp
let g:coc_filetype_map = {
      \ 'xm': 'cpp',
      \ }
```
I have more commands in my init.vim but they are just source for my keybindings and my vim-plug plugin commands
This config works fine for regular c family files

My CocConfig: 
```
{                                               
    "languageserver": {     
    "ccls": {       
      "command": "ccls",
      "filetypes": ["c", "cc", "cpp", "c++", "objc", "objcpp"],
      "rootPatterns": [".ccls", "compile_commands.json", ".git/", ".hg/"],
      "initializationOptions": {
          "cache": {                                                             
            "directory": "/tmp/ccls"                 
          }         
        }
    }                                        
  }         
  } 
```
I tried to be thorough as possible, let me know if any additional information is needed 
## Screenshots
as you can see on the bottom it is saying `source languageserver.ccls timeout after 5000ms` and Nvim is recognizing the file as `c++`. This doesn't happen in .cpp files and other c family filetypes
![Screen Shot 2021-06-04 at 3 09 52 PM](https://user-images.githubusercontent.com/28695977/120867599-19bb7e80-c547-11eb-917c-c4f646acc169.png)

**Comment by oblitum** [comment]
You don't need to set `g:coc_file_map` because you already set filetype to cpp, and coc is filetype based, not file extension based, so that's redundant.

**Comment by oblitum** [comment]
Little off-topic but do you have a reason to use ccls in special? Because clangd has been improved a lot lately, which almost deprecate most usages for ccls, and provides much more functionality. There's also a nice coc-clangd extension which is pretty trivial to install.

**Comment by HearseDev** [comment]
> Little off-topic but do you have a reason to use ccls in special? Because clangd has been improved a lot lately, which almost deprecate most usages for ccls, and provides much more functionality. There's also a nice coc-clangd extension which is pretty trivial to install.

removed my cocconfig for ccls and installed coc-clangd worked perfectly for regular cpp files but this is what I get for .xm files 
![Screen Shot 2021-06-04 at 3 40 35 PM](https://user-images.githubusercontent.com/28695977/120869455-5e491900-c54b-11eb-947f-88de61d31917.png)

**Comment by oblitum** [comment]
@HearseDev it's a clangd issue, please report upstream on clangd repository. I also replicate it. As for snippets, after opening sample.xm and `:set ft=cpp`, the snippets from coc-snippets are working fine, the only thing that isn't working is the clangd lsp server.

**Comment by oblitum** [comment]
You may search google about "fe_expected_compiler_job" and you'll see bugs reported for other editors.

**Comment by oblitum** [comment]
@HearseDev maybe, but I don't have any ideas. I'd still report on clangd issue tracker, they should be generally fast on picking it up. I've looked some issues with related reports and it seems on master it's gone for them. If you're not using latest clangd, you may give it a try on that. coc-clangd can download and install a lasted clangd that can be more up-to-date than system one, you may check on that on clangd's README.
