### ISSUE TITLE
[coc.nvim] Error on rename: The number of affected files exceeds the max limit 50

### ISSUE THREAD

**Issue by ilyachur** [neoclide/coc.nvim#3144]
## Result from CocInfo

```
undefined## versions

vim version: VIM - Vi IMproved 8.2 8022681
node version: v16.3.0
coc.nvim version: 0.0.80-b427b2ccfa
coc.nvim directory: /tmp/project/dotfiles/.vim/plugged/coc.nvim
term: dumb
platform: darwin

## Log of coc.nvim

2021-06-15T20:16:43.689 WARN (pid:54563) [attach] - Plugin not ready when received "registNotification" [ 'cquery', '$cquery/publishSemanticHighlighting' ]
2021-06-15T20:16:43.691 WARN (pid:54563) [attach] - Plugin not ready when received "registNotification" [ 'cquery', '$cquery/setInactiveRegions' ]
2021-06-15T20:16:43.691 WARN (pid:54563) [attach] - Plugin not ready when received "registNotification" [ 'ccls', '$ccls/publishSemanticHighlight' ]
2021-06-15T20:16:43.691 WARN (pid:54563) [attach] - Plugin not ready when received "registNotification" [ 'ccls', '$ccls/publishSkippedRanges' ]
2021-06-15T20:16:43.832 INFO (pid:54563) [services] - registered service "clangd"
2021-06-15T20:16:44.815 INFO (pid:54563) [plugin] - coc.nvim 0.0.80-b427b2ccfa initialized with node: v16.3.0 after 1122ms
2021-06-15T20:16:44.816 INFO (pid:54563) [attach] - receive notification: registNotification [ 'cquery', '$cquery/publishSemanticHighlighting' ]
2021-06-15T20:16:44.818 INFO (pid:54563) [attach] - receive notification: registNotification [ 'cquery', '$cquery/setInactiveRegions' ]
2021-06-15T20:16:44.818 INFO (pid:54563) [attach] - receive notification: registNotification [ 'ccls', '$ccls/publishSemanticHighlight' ]
2021-06-15T20:16:44.818 INFO (pid:54563) [attach] - receive notification: registNotification [ 'ccls', '$ccls/publishSkippedRanges' ]
2021-06-15T20:16:56.526 INFO (pid:54563) [services] - clangd state change: stopped => starting
2021-06-15T20:16:56.532 INFO (pid:54563) [language-client-index] - Language server "clangd" started with 55278
2021-06-15T20:16:56.565 INFO (pid:54563) [services] - clangd state change: starting => running
2021-06-15T20:16:56.571 INFO (pid:54563) [services] - service clangd started
2021-06-15T20:16:59.623 INFO (pid:54563) [attach] - receive notification: rename []
2021-06-15T20:17:09.951 INFO (pid:54563) [attach] - receive request: CocAutocmd [ 'BufWritePre', 2 ]
2021-06-15T20:20:43.314 INFO (pid:54563) [attach] - receive notification: highlight []
2021-06-15T20:24:05.027 INFO (pid:54563) [attach] - receive notification: rename []
2021-06-15T20:24:05.910 ERROR (pid:54563) [Handler] - Error: The number of affected files exceeds the max limit 50
    at /tmp/project/dotfiles/.vim/plugged/coc.nvim/build/index.js:209:31520
    at async My.provideRenameEdits (/tmp/project/dotfiles/.vim/plugged/coc.nvim/build/index.js:207:24351)
    at async mz.provideRenameEdits (/tmp/project/dotfiles/.vim/plugged/coc.nvim/build/index.js:208:3518)
    at async pw.rename (/tmp/project/dotfiles/.vim/plugged/coc.nvim/build/index.js:255:7445)
    at async dw.cocAction (/tmp/project/dotfiles/.vim/plugged/coc.nvim/build/index.js:256:11749)
    at async gq.<anonymous> (/tmp/project/dotfiles/.vim/plugged/coc.nvim/build/index.js:256:13205)
2021-06-15T20:24:09.950 INFO (pid:54563) [attach] - receive notification: highlight []
2021-06-15T20:30:40.846 INFO (pid:54563) [attach] - receive request: fillDiagnostics [ 2 ]
2021-06-15T20:30:44.885 INFO (pid:54563) [attach] - receive notification: highlight []
2021-06-15T20:31:04.203 INFO (pid:54563) [attach] - receive notification: showInfo []
2021-06-15T20:31:04.215 INFO (pid:54563) [attach] - receive request: CocAutocmd [ 'BufReadCmd', 'output', 'output:///info' ]
2021-06-15T20:31:08.248 INFO (pid:54563) [attach] - receive notification: highlight []
2021-06-15T20:31:34.132 INFO (pid:54563) [attach] - receive notification: highlight []
2021-06-15T20:32:24.747 INFO (pid:54563) [attach] - receive notification: rename []
2021-06-15T20:32:26.069 ERROR (pid:54563) [Handler] - Error: The number of affected files exceeds the max limit 50
    at /tmp/project/dotfiles/.vim/plugged/coc.nvim/build/index.js:209:31520
    at async My.provideRenameEdits (/tmp/project/dotfiles/.vim/plugged/coc.nvim/build/index.js:207:24351)
    at async mz.provideRenameEdits (/tmp/project/dotfiles/.vim/plugged/coc.nvim/build/index.js:208:3518)
    at async pw.rename (/tmp/project/dotfiles/.vim/plugged/coc.nvim/build/index.js:255:7445)
    at async dw.cocAction (/tmp/project/dotfiles/.vim/plugged/coc.nvim/build/index.js:256:11749)
    at async gq.<anonymous> (/tmp/project/dotfiles/.vim/plugged/coc.nvim/build/index.js:256:13205)
2021-06-15T20:32:34.467 INFO (pid:54563) [attach] - receive notification: showInfo []
```

## Describe the bug

When I try to rename class in my C++ project I got the next error message:
```
[coc.nvim] Error on rename: The number of affected files exceeds the max limit 50
```
It happened because I wanted to change the base class which is used in whole project.

## Reproduce the bug

I think it can be reproduced on any big opensource project if try to rename some common class.
Can I change the `max limit`? Maybe do I miss something from the `coc` documentation?

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
