### ISSUE TITLE
Server languageserver.ccls failed to start: Error: Connection to server got closed.

### ISSUE THREAD

**Issue by jakkarn** [neoclide/coc.nvim#3159]
## Problem
Upon opening a c++ file `.cc`, coc fails in starting the languageserver.ccls.

## CocInfo
```
## versions
  
  vim version: NVIM v0.4.4
  node version: v14.17.1
  coc.nvim version: 0.0.80-91c1114046
  coc.nvim directory: /home/jemapelle/.config/nvim/plugged/coc.nvim
  term: xterm-256color
  platform: linux
  
  ## Log of coc.nvim
  
  2021-06-23T16:52:00.793 INFO (pid:14296) [services] - registered service "languageserver.ccls"
  2021-06-23T16:52:00.798 INFO (pid:14296) [services] - ccls state change: stopped => starting
  2021-06-23T16:52:00.800 INFO (pid:14296) [plugin] - coc.nvim 0.0.80-91c1114046 initialized with node: v14.17.1 after 57ms
  2021-06-23T16:52:00.805 INFO (pid:14296) [language-client-index] - Language server "languageserver.ccls" started with 14307
  2021-06-23T16:52:00.860 INFO (pid:14296) [services] - ccls state change: starting => stopped
  2021-06-23T16:52:00.860 INFO (pid:14296) [services] - ccls state change: stopped => starting
  2021-06-23T16:52:00.863 INFO (pid:14296) [language-client-index] - Language server "languageserver.ccls" started with 14328
  2021-06-23T16:52:00.892 INFO (pid:14296) [services] - ccls state change: starting => stopped
  2021-06-23T16:52:00.892 INFO (pid:14296) [services] - ccls state change: stopped => starting
  2021-06-23T16:52:00.899 INFO (pid:14296) [language-client-index] - Language server "languageserver.ccls" started with 14354
  2021-06-23T16:52:00.939 INFO (pid:14296) [services] - ccls state change: starting => stopped
  2021-06-23T16:52:00.940 INFO (pid:14296) [services] - ccls state change: stopped => starting
  2021-06-23T16:52:00.944 INFO (pid:14296) [language-client-index] - Language server "languageserver.ccls" started with 14382
  2021-06-23T16:52:00.975 INFO (pid:14296) [services] - ccls state change: starting => stopped
  2021-06-23T16:52:00.976 ERROR (pid:14296) [services] - Server languageserver.ccls failed to start: Error: Connection to server got closed. Server will not be restarted.
      at kb.handleConnectionClosed (/home/jemapelle/.config/nvim/plugged/coc.nvim/build/index.js:214:967)
      at kb.handleConnectionClosed (/home/jemapelle/.config/nvim/plugged/coc.nvim/build/index.js:214:28648)
      at t (/home/jemapelle/.config/nvim/plugged/coc.nvim/build/index.js:214:386)
      at zq.invoke (/home/jemapelle/.config/nvim/plugged/coc.nvim/build/index.js:33:9670)
      at hp.fire (/home/jemapelle/.config/nvim/plugged/coc.nvim/build/index.js:33:10436)
      at xr (/home/jemapelle/.config/nvim/plugged/coc.nvim/build/index.js:34:10897)
      at zq.invoke (/home/jemapelle/.config/nvim/plugged/coc.nvim/build/index.js:33:9670)
      at hp.fire (/home/jemapelle/.config/nvim/plugged/coc.nvim/build/index.js:33:10436)
      at I0.fireClose (/home/jemapelle/.config/nvim/plugged/coc.nvim/build/index.js:33:12716)
      at Socket.<anonymous> (/home/jemapelle/.config/nvim/plugged/coc.nvim/build/index.js:33:14275)
  2021-06-23T16:52:03.882 INFO (pid:14296) [attach] - receive notification: showInfo []
```

# Reproduce
1. install neovim 0.4.4
2. install nodejs 14.17.1
3. install ccls via `sudo snap install ccls --classic`
4. add minimalistic CocConfig for ccls:
```json
  {
    "languageserver": {
      "ccls": {
        "command": "ccls",
        "filetypes": ["c", "cc", "cpp", "c++", "objc", "objcpp"],
        "rootPatterns": [".ccls", "compile_commands.json", ".git/", ".hg/"],
        "initializationOptions": {
            "cache": {
              "directory": "/tmp/ccls"
            }
          }
      }
    }
  }
```
5. add a init.vim at default stdpath with
```
source $HOME/.config/nvim/plugs/plugins.vim
source $HOME/.config/nvim/modules/coc.vim
```
plugins.vim (vim-plug):
```
call plug#begin()
Plug 'neoclide/coc.nvim' ", {'branch': 'release'}
call plug#end()
```
coc.vim contains an copy of the example configuration from the github repo.
PlugInstall succeeded.

6. create an empty folder in home directory and run `nvim main.cc`

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
