### ISSUE TITLE
Global temporary log files cause permission errors for multiple users

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc.nvim#317]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

```
## versions

vim version: NVIM v0.3.2
node version: v11.6.0
coc.nvim version: 0.0.45
term: tmux-256color
platform: linux

## Error messages
log4js.fileAppender - Writing to file /tmp/coc-nvim.log, error happened  { [Error: EACCES: permission denied, open '/tmp/coc-nvim.log']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/tmp/coc-nvim.log' }
log4js.fileAppender - Writing to file /tmp/coc-nvim.log, error happened  Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at WriteStream.Writable.write (_stream_writable.js:299:11)
    at RollingFileStream.BaseRollingFileStream._writeTheChunk (/mnt/ssd/.vim/plugged/coc.nvim/node_modules/streamroller/lib/BaseRollingFileStream.js:50:25)
    at RollingFileStream.BaseRollingFileStream._write (/mnt/ssd/.vim/plugged/coc.nvim/node_modules/streamroller/lib/BaseRollingFileStream.js:72:10)
    at doWrite (/mnt/ssd/.vim/plugged/coc.nvim/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/mnt/ssd/.vim/plugged/coc.nvim/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at RollingFileStream.Writable.write (/mnt/ssd/.vim/plugged/coc.nvim/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at app (/mnt/ssd/.vim/plugged/coc.nvim/node_modules/log4js/lib/appenders/file.js:55:12)
    at categoryAppenders.forEach (/mnt/ssd/.vim/plugged/coc.nvim/node_modules/log4js/lib/log4js.js:42:5)
## Output channel: prettier
```

**Describe the bug**

coc.nvim creates global log files on `/tmp` with write permissions just for the user that first starts (neo)vim, subsequent users will get permission errors while those files reside in `/tmp`. 

**To Reproduce**

1. Start with a clean `/tmp` directory
2. Start (neo)vim as one user and close it
3. Start (neo)vim as another user in the machine

**Solution**

coc.nvim needs to create temporary log files following at least `mktemp` rules for the file names to be random with a prefix and/or suffix. If they're created on global `/tmp` (good for avoiding the disk), both write and read permissions should be set for the owner (`umask 077`), currently any user can read the logs, but just the owner can write to it.

**Comment by oblitum** [comment]
Another thing is that I'd simply wish to turn off the logs through a setting that isn't an environment variable. Even with `NVIM_COC_LOG_LEVEL=OFF`, an empty log file is generated.

**Comment by towo** [comment]
This is not fixed with tmpfs, as the permissions on tmpfs are not the only thing that affects write support. Two things:

1. Maybe intersperse the user and PID into the log file, so you can have `/tmp/coc-nvim.towo-12345.log`, which is unique and still writable in case it isn't in almost all cases.
2. Consider checking for `$XDG_RUNTIME_DIR` which is set on most systemd-based systems and offers a per-user temporary directory that gets reset on reboot.

**Comment by jon-grangien-gaia** [comment]
This is breaking the plugin for me on Windows
