### ISSUE TITLE
UnhandledRejection: write EPIPE

### ISSUE THREAD

**Issue by fiplox** [neoclide/coc.nvim#3178]
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.4
node version: v12.21.0
coc.nvim version: 0.0.80-674b1e91f5
coc.nvim directory: /home/user/.vim/plugged/coc.nvim
term: st-256color
platform: linux

## Log of coc.nvim

2021-06-28T20:26:28.696 INFO (pid:187016) [services] - registered service "languageserver.ccls"
2021-06-28T20:26:28.745 INFO (pid:187016) [plugin] - coc.nvim 0.0.80-674b1e91f5 initialized with node: v12.21.0 after 141ms
2021-06-28T20:26:28.753 INFO (pid:187016) [services] - registered service "go"
2021-06-28T20:26:28.753 INFO (pid:187016) [services] - gopls state change: stopped => starting
2021-06-28T20:26:28.774 ERROR (pid:187016) [language-client-client] - connection error: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:788:11)
    at Socket._write (net.js:800:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at /home/user/.vim/plugged/coc.nvim/build/index.js:33:3107
    at new Promise (<anonymous>)
    at bq.write (/home/user/.vim/plugged/coc.nvim/build/index.js:33:3028) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
} undefined
2021-06-28T20:26:28.805 INFO (pid:187016) [services] - gopls state change: starting => stopped
2021-06-28T20:26:28.807 ERROR (pid:187016) [language-client-client] - connection error: Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:788:11)
    at Socket._write (net.js:800:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at /home/user/.vim/plugged/coc.nvim/build/index.js:33:3107
    at new Promise (<anonymous>)
    at bq.write (/home/user/.vim/plugged/coc.nvim/build/index.js:33:3028) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
} {
  jsonrpc: '2.0',
  id: 0,
  method: 'initialize',
  params: {
    processId: 187016,
    rootPath: '/tmp/vim-go776adfa90d077322f5cb6d0f820358e5800fd33abb6441d92165a57d3d565e47',
    rootUri: 'file:///tmp/vim-go776adfa90d077322f5cb6d0f820358e5800fd33abb6441d92165a57d3d565e47',
    capabilities: {
      workspace: [Object],
      textDocument: [Object],
      window: [Object],
      general: [Object]
    },
    initializationOptions: undefined,
    trace: 'off',
    workspaceFolders: [ [Object] ],
    locale: 'en_US',
    clientInfo: { name: 'coc.nvim', version: '0.0.80' }
  }
}
2021-06-28T20:26:28.809 ERROR (pid:187016) [server] - unhandledRejection  Promise {
  <rejected> Error: write EPIPE
      at afterWriteDispatched (internal/stream_base_commons.js:156:25)
      at writeGeneric (internal/stream_base_commons.js:147:3)
      at Socket._writeGeneric (net.js:788:11)
      at Socket._write (net.js:800:8)
      at doWrite (_stream_writable.js:403:12)
      at writeOrBuffer (_stream_writable.js:387:5)
      at Socket.Writable.write (_stream_writable.js:318:11)
      at /home/user/.vim/plugged/coc.nvim/build/index.js:33:3107
      at new Promise (<anonymous>)
      at bq.write (/home/user/.vim/plugged/coc.nvim/build/index.js:33:3028) {
    errno: 'EPIPE',
    code: 'EPIPE',
    syscall: 'write'
  }
} Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:788:11)
    at Socket._write (net.js:800:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at /home/user/.vim/plugged/coc.nvim/build/index.js:33:3107
    at new Promise (<anonymous>)
    at bq.write (/home/user/.vim/plugged/coc.nvim/build/index.js:33:3028) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
2021-06-28T20:26:28.813 ERROR (pid:187016) [language-client-client] - connection error: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at /home/user/.vim/plugged/coc.nvim/build/index.js:33:3107
    at new Promise (<anonymous>)
    at bq.write (/home/user/.vim/plugged/coc.nvim/build/index.js:33:3028)
    at A0.doWrite (/home/user/.vim/plugged/coc.nvim/build/index.js:34:1698)
    at /home/user/.vim/plugged/coc.nvim/build/index.js:34:1597 {
  code: 'ERR_STREAM_DESTROYED'
} undefined
2021-06-28T20:26:28.813 ERROR (pid:187016) [language-client-client] - connection error: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at /home/user/.vim/plugged/coc.nvim/build/index.js:33:3107
    at new Promise (<anonymous>)
    at bq.write (/home/user/.vim/plugged/coc.nvim/build/index.js:33:3028)
    at A0.doWrite (/home/user/.vim/plugged/coc.nvim/build/index.js:34:1698)
    at /home/user/.vim/plugged/coc.nvim/build/index.js:34:1597 {
  code: 'ERR_STREAM_DESTROYED'
} { jsonrpc: '2.0', id: 1, method: 'shutdown', params: undefined }
2021-06-28T20:26:28.814 ERROR (pid:187016) [server] - unhandledRejection  Promise {
  <rejected> Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
      at doWrite (_stream_writable.js:399:19)
      at writeOrBuffer (_stream_writable.js:387:5)
      at Socket.Writable.write (_stream_writable.js:318:11)
      at /home/user/.vim/plugged/coc.nvim/build/index.js:33:3107
      at new Promise (<anonymous>)
      at bq.write (/home/user/.vim/plugged/coc.nvim/build/index.js:33:3028)
      at A0.doWrite (/home/user/.vim/plugged/coc.nvim/build/index.js:34:1698)
      at /home/user/.vim/plugged/coc.nvim/build/index.js:34:1597 {
    code: 'ERR_STREAM_DESTROYED'
  }
} Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at /home/user/.vim/plugged/coc.nvim/build/index.js:33:3107
    at new Promise (<anonymous>)
    at bq.write (/home/user/.vim/plugged/coc.nvim/build/index.js:33:3028)
    at A0.doWrite (/home/user/.vim/plugged/coc.nvim/build/index.js:34:1698)
    at /home/user/.vim/plugged/coc.nvim/build/index.js:34:1597 {
  code: 'ERR_STREAM_DESTROYED'
}
2021-06-28T20:27:12.469 INFO (pid:187016) [attach] - receive notification: showInfo []


```

## Describe the bug

When I try to install coc-go extension or open a .go file with, it pops me errors (can be found in logs).

## Reproduce the bug

I'm not sure how to reproduce it, on Arch everything worked well, but recently I installed debian 11 and got this. It is some kind of permission issue, but I don't know where to look. I tried to install coc-go while logged with root, and everything went good and worked.

I tried with a minimal `init.vim`, still the same

  ```vim
set nocompatible
filetype plugin indent on
syntax on
set hidden
set nobackup
set nowritebackup
set shortmess+=c

call plug#begin('~/.vim/plugged')

Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

  ```

**Comment by chemzqm** [comment]
Should be issue with coc-go or your golsp.
