### ISSUE TITLE
How to jump to definition in new or existing tab

### ISSUE THREAD

**Issue by Char-Aznable** [neoclide/coc.nvim#318]
**Is your feature request related to a problem? Please describe.**
Currently I'm using `nmap <silent> gd <Plug>(coc-definition)` to jump to definition when navigating c++ files. The problem is that it closes the current file when jumping to new files.

**Describe the solution you'd like**
I want the jumping-to-definition command switching to an existing buffer in another tab if the target buffer is available; otherwise load the target file in new tab and jump to the line there. This is similar to youcompleteme's `g:ycm_goto_buffer_command`

**Describe alternatives you've considered**
N/A

**Additional context**
I'm totally new to this plugin and any help is appreciated.

**Comment by chemzqm** [comment]
To change all location jump behavior, set `"coc.preferences.jumpCommand": "drop"`

For definition only, use `:call CocAction('jumpDefinition', 'drop')`

**Comment by Char-Aznable** [comment]
Also, can you add support for `tab drop` as a `openResourceCommand` so that I don't have to set all the go-to commands individuall?

**Comment by chemzqm** [comment]
>  How do I configure the default quickfix action? I'm not using denite btw.

Seems vim doesn't support that, coc will use inputlist as default list other than quickfix in next release.

> I tried setting "coc.preferences.jumpCommand": "tab drop" but it has no effect at all.

I've tried it could work, but the cursor position could be wrong.

**Comment by Char-Aznable** [comment]
I double checked that `"coc.preferences.jumpCommand": "tab drop"` doesn't have the intended effect on my machine. But `:call CocAction('jumpDefinition', 'tab drop')` does give the wrong cursor position. Can this be easily fix?

**Comment by chemzqm** [comment]
> doesn't have the intended effect on my machine.

What does that means? Still open buffer in current window?
If you want `"coc.preferences.jumpCommand"` take effect, you should use `:call CocAction('jumpDefinition')` (no second argument)

**Comment by Char-Aznable** [comment]
Oh, I see. I thought `jumpCommand` affects `<Plug>(coc-definition)` too, which is what I used. Anyway, it does give the wrong cursor position.

**Comment by Char-Aznable** [comment]
@chemzqm Now the default `<Plug>(coc-definition)` or `:call CocAction('jumpDefinition', 'edit')` gives the wrong cursor position after I pull the master...

**Comment by chemzqm** [comment]
I can't reproduce that, possible conflict with other plugin.

**Comment by Char-Aznable** [comment]
No, I can reproduce the error with a minimal config. Here's a reproducing example:

```c++
#include <iostream>

int main() {
  std::size_t i = 0;
}
```
With cursor on `size_t` and go to definition there, I get `/home/linuxbrew/.linuxbrew/include/c++/5.5.0/x86_64-unknown-linux-gnu/bits/c++config.h" 1780L, 51573C` on vim and it hangs there unless I press some key then it opens up the `c++config.h` but the cursor is on the first line, which is wrong -- `std::size_t` is defined on line 199 of that file.

The cquery log since the go-to-def command:
```
(  12.929s) [stdin        ]            lsp.cc:25    | RecordPath: client=/home/aznb/mycodes/scbmc/test.cpp, normalized=/home/aznb/mycodes/scbmc/test.cpp
(  12.929s) [querydb      ]            lsp.cc:35    | No cached URI for /home/linuxbrew/.linuxbrew/include/c++/5.5.0/x86_64-unknown-linux-gnu/bits/c++config.h
(  12.929s) [stdout       ]          timer.cc:41    | [e2e] Running textDocument/definition took 0.287ms
(  12.940s) [stdin        ]            lsp.cc:25    | RecordPath: client=/home/aznb/mycodes/scbmc/test.cpp, normalized=/home/aznb/mycodes/scbmc/test.cpp
(  12.940s) [querydb      ] clang_complete.cc:791   | Dropped preloaded-based code completion session for /home/aznb/mycodes/scbmc/test.cpp
(  12.940s) [stdout       ]          timer.cc:41    | [e2e] Running textDocument/didClose took 0.139ms
(  13.084s) [stdin        ]            lsp.cc:25    | RecordPath: client=/home/linuxbrew/.linuxbrew/include/c++/5.5.0/x86_64-unknown-linux-gnu/bits/c++config.h, normalized=/home/linuxbrew/.linuxbrew/include/c++/5.5.0/x86_64-unknown-linux-gnu/bits/c++config.h
(  13.084s) [querydb      ]          utils.cc:298   | Reading /tmp/cquery/@@home@aznb@mycodes@scbmc/@home@linuxbrew@.linuxbrew@include@c++@5.5.0@x86_64-unknown-linux-gnu@bits@c++config.h
(  13.085s) [querydb      ]          timer.cc:41    | [querydb] Loading cached index file for DidOpen (blocks CodeLens) took 1.1129ms
(  13.085s) [querydb      ] clang_complete.cc:856   | Flushed completion sessions for /home/linuxbrew/.linuxbrew/include/c++/5.5.0/x86_64-unknown-linux-gnu/bits/c++config.h
(  13.085s) [indexer4     ]          utils.cc:298   | Reading /tmp/cquery/@@home@aznb@mycodes@scbmc/@home@linuxbrew@.linuxbrew@include@c++@5.5.0@x86_64-unknown-linux-gnu@bits@c++config.h
(  13.086s) [comp-preload ] clang_complete.cc:410   | Creating completion session with arguments /home/linuxbrew/.linuxbrew/opt/llvm/bin/clang++ -working-directory=/home/aznb/mycodes/scbmc/build_clang -I/home/aznb/mycodes/scbmc/../thrust -I/home/aznb/mycodes/scbmc -I/home/aznb/mycodes/kokkos/core/src -I/home/aznb/mycodes/kokkos/containers/src -I/home/aznb/mycodes/kokkos/algorithms/src -I/home/aznb/mycodes/scbmc/build_clang/kokkos -I/home/linuxbrew/.linuxbrew/Cellar/boost/1.68.0_clang/include/boost-1_68 -I/home/aznb/mycodes/generic -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_OMP -Ofast -ffast-math --std=c++17 -fopenmp=libomp --gcc-toolchain=/home/linuxbrew/.linuxbrew -std=c++17 /home/linuxbrew/.linuxbrew/include/c++/5.5.0/x86_64-unknown-linux-gnu/bits/c++config.h -resource-dir=/home/linuxbrew/.linuxbrew/Cellar/llvm/7.0.1/lib/clang/7.0.1 -Wno-unknown-warning-option -fparse-all-comments -isystem/home/linuxbrew/.linuxbrew/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/../../../../include/c++/5.5.0 -isystem/home/linuxbrew/.linuxbrew/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/../../../../include/c++/5.5.0/x86_64-unknown-linux-gnu -isystem/home/linuxbrew/.linuxbrew/lib/gcc/x86_64-unknown-linux-gnu/5.5.0/../../../../include/c++/5.5.0/backward -isystem/usr/local/include -isystem/home/linuxbrew/.linuxbrew/Cellar/llvm/7.0.1/lib/clang/7.0.1/include -isystem/usr/include/x86_64-linux-gnu -isystem/home/linuxbrew/.linuxbrew/include -isystem/usr/include -fspell-checking
(  13.086s) [indexer4     ]          utils.cc:298   | Reading /tmp/cquery/@@home@aznb@mycodes@scbmc/@home@linuxbrew@.linuxbrew@include@c++@5.5.0@x86_64-unknown-linux-gnu@bits@c++config.h.json
(  13.102s) [indexer4     ]import_pipeline.cc:313   | Parsing /home/linuxbrew/.linuxbrew/include/c++/5.5.0/x86_64-unknown-linux-gnu/bits/c++config.h

```

Here are my config with a "minimal" vimrc and cquery 

coc-setting.json:
```
{
"coc.preferences.autoTrigger": "always",
"coc.preferences.triggerAfterInsertEnter": false,
"coc.preferences.timeout": 2000,
"coc.preferences.noselect": true,
"coc.preferences.formatOnType": false,
"coc.preferences.diagnostic.enable": true,
"coc.preferences.diagnostic.signOffset": 1000,
"coc.preferences.diagnostic.errorSign": ">>",
"coc.preferences.diagnostic.warningSign": "⚠",
"coc.preferences.diagnostic.infoSign": ">>",
"coc.preferences.diagnostic.hintSign": ">>",
"coc.preferences.jumpCommand": "edit",

"languageserver": {
  "cquery": {
    "command": "cquery",
    "args": ["--log-file=/tmp/cq.log"],
    "filetypes": ["c", "cpp"],
    "rootPatterns": ["compile_flags.txt", "compile_commands.json", ".vim/", ".git/", ".hg/"],
    "initializationOptions": {
      "cacheDirectory": "/tmp/cquery"
    }
  }
}
}

```
.vimrc:
```
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'do': 'yarn install'}
if has_key(g:plugs, "coc.nvim")
  " use <tab> for trigger completion and navigate to next complete item
  function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~ '\s'
  endfunction
  
  inoremap <silent><expr> <TAB>
        \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ coc#refresh()
  "use tab and shift-tab to navigate completion list
  inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
  inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
  "Use <enter> to confirm complete
  inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
  "To force coc select complete item before confirm, use:
  inoremap <expr> <cr> pumvisible() ? coc#_select_confirm() : "\<C-g>u\<CR>"
  "Close preview window when completion is done.
  autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif
  " Use `[c` and `]c` for navigate diagnostics
  nmap <silent> [c <Plug>(coc-diagnostic-prev)
  nmap <silent> ]c <Plug>(coc-diagnostic-next)
  
  " Remap keys for gotos
  "nmap <silent> gd :call CocAction('jumpDefinition', 'tab drop')<CR>
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)
  
  " Use K for show documentation in preview window
  nnoremap <silent> K :call <SID>show_documentation()<CR>
  
  function! s:show_documentation()
    if &filetype == 'vim'
      execute 'h '.expand('<cword>')
    else
      call CocAction('doHover')
    endif
  endfunction
  
  " Highlight symbol under cursor on CursorHold
  autocmd CursorHold * silent call CocActionAsync('highlight')
  
  " Remap for rename current word
  nmap <leader>rn <Plug>(coc-rename)
  
  " Remap for format selected region
  vmap <leader>f  <Plug>(coc-format-selected)
  nmap <leader>f  <Plug>(coc-format-selected)
  
  augroup mygroup
    autocmd!
    " Setup formatexpr specified filetype(s).
    autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
    " Update signature help on jump placeholder
    autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
  augroup end
  
  " Remap for do codeAction of selected region, ex: `<leader>aap` for current paragraph
  vmap <leader>a  <Plug>(coc-codeaction-selected)
  nmap <leader>a  <Plug>(coc-codeaction-selected)
  
  " Remap for do codeAction of current line
  nmap <leader>ac  <Plug>(coc-codeaction)
  " Fix autofix problem of current line
  nmap <leader>qf  <Plug>(coc-fix-current)
  
  " Use `:Format` for format current buffer
  command! -nargs=0 Format :call CocAction('format')
  
  " Use `:Fold` for fold current buffer
  command! -nargs=? Fold :call     CocAction('fold', <f-args>)
endif "end of coc.nvim

" Add all your plugins here 

" All of your Plugins must be added before the following line
call plug#end()
```
and my vim version:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 24 2018 14:20:10)
Included patches: 1-543
Compiled by Homebrew
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    +tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           +python/dyn        +viminfo
+conceal           +linebreak         +python3/dyn       +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               +ruby              +writebackup
+dialog_con_gui    +menu              +scrollbind        +X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       +xim
+dnd               +mouse             +startuptime       +xpm
-ebcdic            +mouseshape        +statusline        +xsmp_interact
+emacs_tags        +mouse_dec         -sun_workshop      +xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary        
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/home/linuxbrew/.linuxbrew/Cellar/vim/8.1.0543/share/vim
"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/home/linuxbrew/.linuxbrew/Cellar/gtk+/2.24.32_2/include/gtk-2.0 -I/home/linuxbrew/.linuxbrew/Cellar/gtk+/2.24.32_2/lib/gtk-2.0/include -I/home/linuxbrew/.linuxbrew/Cellar/pango/1.42.4/include/pango-1.0 -I/home/linuxbrew/.linuxbrew/Cellar/atk/2.30.0/include/atk-1.0 -I/home/linuxbrew/.linuxbrew/Cellar/cairo/1.16.0/include/cairo -I/home/linuxbrew/.linuxbrew/Cellar/pixman/0.34.0_1/include/pixman-1 -I/home/linuxbrew/.linuxbrew/Cellar/libpng/1.6.35/include/libpng16 -I/home/linuxbrew/.linuxbrew/Cellar/zlib/1.2.11/include -I/home/linuxbrew/.linuxbrew/Cellar/libxcb/1.13/include -I/home/linuxbrew/.linuxbrew/Cellar/libxrender/0.9.10/include -I/home/linuxbrew/.linuxbrew/Cellar/renderproto/0.11.1/include -I/home/linuxbrew/.linuxbrew/Cellar/libxext/1.3.3/include -I/home/linuxbrew/.linuxbrew/Cellar/libx11/1.6.6/include -I/home/linuxbrew/.linuxbrew/Cellar/libxcb/1.13/include -I/home/linuxbrew/.linuxbrew/Cellar/libxau/1.0.8/include -I/home/linuxbrew/.linuxbrew/Cellar/libxdmcp/1.1.2/include -I/home/linuxbrew/.linuxbrew/Cellar/xproto/7.0.31/include -I/home/linuxbrew/.linuxbrew/Cellar/kbproto/1.0.7/include -I/home/linuxbrew/.linuxbrew/Cellar/xextproto/7.3.0/include -I/home/linuxbrew/.linuxbrew/Cellar/gdk-pixbuf/2.38.0_1/include/gdk-pixbuf-2.0 -I/home/linuxbrew/.linuxbrew/Cellar/pango/1.42.4/include/pango-1.0 -I/home/linuxbrew/.linuxbrew/Cellar/harfbuzz/2.1.3/include/harfbuzz -I/home/linuxbrew/.linuxbrew/Cellar/graphite2/1.3.12/include -I/home/linuxbrew/.linuxbrew/Cellar/pango/1.42.4/include/pango-1.0 -I/home/linuxbrew/.linuxbrew/Cellar/fribidi/1.0.5/include/fribidi -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.58.1/include/glib-2.0 -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.58.1/lib/glib-2.0/include -I/home/linuxbrew/.linuxbrew/Cellar/pcre/8.42/include -I/home/linuxbrew/.linuxbrew/Cellar/fontconfig/2.13.1/include -I/home/linuxbrew/.linuxbrew/Cellar/util-linux/2.32.1_2/include/uuid -I/home/linuxbrew/.linuxbrew/Cellar/expat/2.2.6/include -I/home/linuxbrew/.linuxbrew/opt/freetype/include/freetype2   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc -L/home/linuxbrew/.linuxbrew/Cellar/gtk+/2.24.32_2/lib -L/home/linuxbrew/.linuxbrew/Cellar/pango/1.42.4/lib -L/home/linuxbrew/.linuxbrew/Cellar/atk/2.30.0/lib -L/home/linuxbrew/.linuxbrew/Cellar/cairo/1.16.0/lib -L/home/linuxbrew/.linuxbrew/Cellar/gdk-pixbuf/2.38.0_1/lib -L/home/linuxbrew/.linuxbrew/Cellar/glib/2.58.1/lib -L/home/linuxbrew/.linuxbrew/Cellar/pango/1.42.4/lib -L/home/linuxbrew/.linuxbrew/Cellar/glib/2.58.1/lib -L/home/linuxbrew/.linuxbrew/Cellar/fontconfig/2.13.1/lib -L/home/linuxbrew/.linuxbrew/opt/freetype/lib  -L. -fstack-protector -rdynamic -Wl,-export-dynamic -L/home/linuxbrew/.linuxbrew/opt/libyaml/lib  -Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/libyaml/lib -L/home/linuxbrew/.linuxbrew/opt/openssl/lib  -Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/openssl/lib -L/home/linuxbrew/.linuxbrew/opt/readline/lib  -Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/readline/lib -Wl,-E -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/x86_64-linux-thread-multi/CORE   -L/home/linuxbrew/.linuxbrew/lib -Wl,--as-needed -o vim   -L/home/linuxbrew/.linuxbrew/Cellar/gtk+/2.24.32_2/lib -L/home/linuxbrew/.linuxbrew/Cellar/pango/1.42.4/lib -L/home/linuxbrew/.linuxbrew/Cellar/atk/2.30.0/lib -L/home/linuxbrew/.linuxbrew/Cellar/cairo/1.16.0/lib -L/home/linuxbrew/.linuxbrew/Cellar/gdk-pixbuf/2.38.0_1/lib -L/home/linuxbrew/.linuxbrew/Cellar/glib/2.58.1/lib -L/home/linuxbrew/.linuxbrew/Cellar/pango/1.42.4/lib -L/home/linuxbrew/.linuxbrew/Cellar/glib/2.58.1/lib -L/home/linuxbrew/.linuxbrew/Cellar/fontconfig/2.13.1/lib -L/home/linuxbrew/.linuxbrew/opt/freetype/lib -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lelf -lnsl    -lncurses -ldl   -Wl,-E -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/x86_64-linux-thread-multi/CORE  -fstack-protector-strong -L/usr/local/lib  -L/home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/x86_64-linux-thread-multi/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc   -L/home/linuxbrew/.linuxbrew/Cellar/tcl-tk/8.6.8_1/lib -ltcl8.6 -ldl -lz -lpthread -lieee -lm -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/ruby/2.5.3_2/lib -L/home/linuxbrew/.linuxbrew/Cellar/ruby/2.5.3_2/lib -lruby -lpthread -ldl -lcrypt -lm     

```

**Comment by chemzqm** [comment]
Can't reproduce.
You need to check to jump location from language server by use output channel: https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by Char-Aznable** [comment]
@chemzqm It doesn't seem to be related to LSP server because the vim status points to the right cursor location as shown in my previous comments. It looks like the plugin is resetting it somehow

**Comment by Char-Aznable** [comment]
@chemzqm Now I'm getting these error and go-to-definition doesn't go anywhere at all:
```
2019-01-09T10:10:14.939 INFO (pid:9868) [plugin] - coc initialized with node: v11.6.0
2019-01-09T10:17:29.711 INFO (pid:11124) [plugin] - coc initialized with node: v11.6.0
2019-01-09T10:17:33.290 INFO (pid:11211) [services] - cquery state change: stopped => starting
2019-01-09T10:17:33.314 INFO (pid:11211) [services] - cquery state change: starting => running
2019-01-09T10:17:33.322 INFO (pid:11211) [services] - service languageserver.cquery started
2019-01-09T10:17:33.323 INFO (pid:11211) [plugin] - coc initialized with node: v11.6.0
2019-01-09T10:17:38.355 INFO (pid:11286) [services] - cquery state change: stopped => starting
2019-01-09T10:17:38.379 INFO (pid:11286) [services] - cquery state change: starting => running
2019-01-09T10:17:38.387 INFO (pid:11286) [services] - service languageserver.cquery started
2019-01-09T10:17:38.388 INFO (pid:11286) [plugin] - coc initialized with node: v11.6.0
2019-01-09T10:17:46.799 ERROR (pid:11286) [plugin] - Error: getDocumentHighLight timeout after 3s
    at Timeout.setTimeout [as _onTimeout] (/home/aznb/.vim/plugged/coc.nvim/lib/languages.js:62:28)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
2019-01-09T10:17:50.413 ERROR (pid:11286) [plugin] - Error: getDefinition timeout after 3s
    at Timeout.setTimeout [as _onTimeout] (/home/aznb/.vim/plugged/coc.nvim/lib/languages.js:62:28)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
2019-01-09T10:17:57.932 ERROR (pid:11286) [plugin] - Error: getDefinition timeout after 3s
    at Timeout.setTimeout [as _onTimeout] (/home/aznb/.vim/plugged/coc.nvim/lib/languages.js:62:28)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
2019-01-09T10:18:02.529 ERROR (pid:11286) [plugin] - Error: getDocumentHighLight timeout after 3s
    at Timeout.setTimeout [as _onTimeout] (/home/aznb/.vim/plugged/coc.nvim/lib/languages.js:62:28)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
2019-01-09T10:18:18.267 ERROR (pid:11286) [plugin] - Error: getDefinition timeout after 3s
    at Timeout.setTimeout [as _onTimeout] (/home/aznb/.vim/plugged/coc.nvim/lib/languages.js:62:28)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)

```

**Comment by Char-Aznable** [comment]
I also tried adding the options in https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel to coc-setting.json:
```
{
"coc.preferences.autoTrigger": "always",
"coc.preferences.triggerAfterInsertEnter": false,
"coc.preferences.timeout": 2000,
"coc.preferences.noselect": true,
"coc.preferences.formatOnType": false,
"coc.preferences.jumpCommand": "edit",
"coc.preferences.diagnostic.enable": true,
"coc.preferences.diagnostic.signOffset": 1000,
"coc.preferences.diagnostic.errorSign": ">>",
"coc.preferences.diagnostic.warningSign": "⚠",
"coc.preferences.diagnostic.infoSign": ">>",
"coc.preferences.diagnostic.hintSign": ">>",
"tsserver.trace.server": "verbose",

"languageserver": {
  "cquery": {
    "command": "cquery",
    "args": ["--log-file=/tmp/cq.log"],
    "filetypes": ["c", "cpp"],
    "trace.server": "verbose",
    "rootPatterns": ["compile_flags.txt", "compile_commands.json", ".vim/", ".git/", ".hg/"],
    "initializationOptions": {
      "cacheDirectory": "/tmp/cquery"
    }
  }
}
}

```

However, I got the warning that "Property tsserver.trace.server" is not allowed and I don't get any additional info in the log

**Comment by Char-Aznable** [comment]
OK. Now the go-to-definition do give the right cursor position but only after another random key stroke. What happens now is it opens the file and hangs and then go to the definition after any key stroke.

**Comment by chemzqm** [comment]
It's vim's problem you should use something like `set shortmess=aFc` to prevent the block of vim.

**Comment by Char-Aznable** [comment]
Hmm, `shortmess` doesn't help at all. I have used other lsp client and they worked before. Not sure what's causing the pause

**Comment by HOnatToprak** [comment]
I wrote that not for tabs but windows. Maybe It helps.

```
nmap <silent> gd :call Split_or_jump()<CR>
function! Split_or_jump() abort
	let current_window_id = winnr()
	let current_buffer_id = bufnr('%')
	execute ":call CocAction('jumpDefinition', 'drop')"
	let definition_window_id = winnr()
	let definition_buffer_id = bufnr('%')
	if current_window_id == definition_window_id
		execute ':b '.current_buffer_id
		execute ':vs #'.definition_buffer_id
	endif
endfunction
```

**Comment by fredrivett** [comment]
For those wanting a vertical split, you can use `"coc.preferences.jumpCommand": "vsplit"` (in your `coc-settings.json` — use `:CocConfig` to open).

**Comment by bergercookie** [comment]
> For those wanting a vertical split, you can use `"coc.preferences.jumpCommand": "vsplit"` (in your `coc-settings.json` — use `:CocConfig` to open).

Not sure when this was added but you can jump-to-definition in a new tab  by adding this instead:
```json
"coc.preferences.jumpCommand": "tabe",
```
