### ISSUE TITLE
UnhandledRejection during code completion of Rust

### ISSUE THREAD

**Issue by arunanshub** [neoclide/coc.nvim#3202]
## Result from CocInfo

```log
## versions

vim version: NVIM v0.4.4
node version: v16.3.0
coc.nvim version: 0.0.80-37132cfc36
coc.nvim directory: /home/arunanshub/.config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2021-07-08T18:21:56.257 INFO (pid:433994) [services] - registered service "rust-analyzer"
2021-07-08T18:21:56.259 INFO (pid:433994) [services] - Rust Analyzer Language Server state change: stopped => starting
2021-07-08T18:21:56.273 INFO (pid:433994) [plugin] - coc.nvim 0.0.80-37132cfc36 initialized with node: v16.3.0 after 122ms
2021-07-08T18:21:56.279 INFO (pid:433994) [language-client-index] - Language server "rust-analyzer" started with 434058
2021-07-08T18:21:56.292 INFO (pid:433994) [services] - Rust Analyzer Language Server state change: starting => running
2021-07-08T18:21:56.298 INFO (pid:433994) [services] - service rust-analyzer started
2021-07-08T18:22:02.771 INFO (pid:433994) [attach] - receive notification: highlight []
2021-07-08T18:22:03.580 ERROR (pid:433994) [node-client] - request error on "nvim_call_function" [
  'coc#highlight#get_highlights',
  [
    tN {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      transport: [fN],
      data: 1,
      client: [SN],
      prefix: 'nvim_buf_',
      [Symbol(kCapture)]: false
    },
    'semanticTokens'
  ]
] Get highlights requires neovim 0.5.0 or vim support prop_list Error
    at SN.request (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:29:34621)
    at SN.call (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:31:6260)
    at yD.doHighlight (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:253:10006)
    at async /home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:253:13220
2021-07-08T18:22:03.582 ERROR (pid:433994) [server] - unhandledRejection  Promise {
  <rejected> Error
      at SN.request (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:29:34621)
      at SN.call (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:31:6260)
      at yD.doHighlight (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:253:10006)
      at async /home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:253:13220
} Error
    at SN.request (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:29:34621)
    at SN.call (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:31:6260)
    at yD.doHighlight (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:253:10006)
    at async /home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:253:13220
2021-07-08T18:23:03.364 ERROR (pid:433994) [node-client] - request error on "nvim_call_function" [
  'coc#highlight#get_highlights',
  [
    tN {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      transport: [fN],
      data: 1,
      client: [SN],
      prefix: 'nvim_buf_',
      [Symbol(kCapture)]: false
    },
    'semanticTokens'
  ]
] Get highlights requires neovim 0.5.0 or vim support prop_list Error
    at SN.request (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:29:34621)
    at SN.call (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:31:6260)
    at yD.doHighlight (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:253:10006)
    at async /home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:253:13220
2021-07-08T18:23:03.365 ERROR (pid:433994) [server] - unhandledRejection  Promise {
  <rejected> Error
      at SN.request (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:29:34621)
      at SN.call (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:31:6260)
      at yD.doHighlight (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:253:10006)
      at async /home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:253:13220
} Error
    at SN.request (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:29:34621)
    at SN.call (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:31:6260)
    at yD.doHighlight (/home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:253:10006)
    at async /home/arunanshub/.config/nvim/plugged/coc.nvim/build/index.js:253:13220
2021-07-08T18:23:05.181 INFO (pid:433994) [attach] - receive notification: highlight []
2021-07-08T18:23:07.604 INFO (pid:433994) [attach] - receive notification: showInfo []
```

## Describe the bug

As in the image below, an UnhandledRejection is raised whenever code completion for Rust via `coc-rust-analyzer` is involved.
This does NOT happen in any other extensions like Python, Markdown etc.

## Reproduce the bug

- Mini `init.vim` file for bug reproduction:

```vim
" plug-vim installation
let s:plug_dir = join([stdpath("config"), "autoload", "plug.vim"], "/")
if empty(glob(s:plug_dir)) || empty(glob(stdpath("config") . "/plugged"))
    silent exec "!curl -fLo" s:plug_dir
        \ "--create-dirs"
        \ "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    autocmd VimEnter * PlugInstall
endif

" install plugins
call plug#begin()
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

" use rust-analyzer
let g:coc_global_extensions = [
    \ 'coc-rust-analyzer',
\ ]

" =================================================
" DEFAULT CONFIG FROM
"  https://github.com/neoclide/coc.nvim#example-vim-configuration
" =================================================
let g:pyindent_open_paren = 'shiftwidth()' " Fix python indentation
set nocompatible
set notimeout nottimeout
set cursorline
set smartcase number expandtab
set softtabstop=4 shiftwidth=4
if has("termguicolors")
    set termguicolors
endif

" Set internal encoding of vim, not needed on neovim, since coc.nvim using some
" unicode characters in the file autoload/float.vim
set encoding=utf-8

" TextEdit might fail if hidden is not set.
set hidden

" Some servers have issues with backup files, see #649.
set nobackup
set nowritebackup

" Give more space for displaying messages.
set cmdheight=2

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved.
if has("nvim-0.5.0") || has("patch-8.1.1564")
  " Recently vim can merge signcolumn and number column into one
  set signcolumn=number
else
  set signcolumn=yes
endif

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion.
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" Make <CR> auto-select the first completion item and notify coc.nvim to
" format on enter, <cr> could be remapped by other vim plugin
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" Formatting selected code.
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)

" Remap keys for applying codeAction to the current buffer.
nmap <leader>ac  <Plug>(coc-codeaction)
" Apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)

" Map function and class text objects
" NOTE: Requires 'textDocument.documentSymbol' support from the language server.
xmap if <Plug>(coc-funcobj-i)
omap if <Plug>(coc-funcobj-i)
xmap af <Plug>(coc-funcobj-a)
omap af <Plug>(coc-funcobj-a)
xmap ic <Plug>(coc-classobj-i)
omap ic <Plug>(coc-classobj-i)
xmap ac <Plug>(coc-classobj-a)
omap ac <Plug>(coc-classobj-a)

" Remap <C-f> and <C-b> for scroll float windows/popups.
if has('nvim-0.4.0') || has('patch-8.2.0750')
  nnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
  nnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
  inoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : "\<Right>"
  inoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : "\<Left>"
  vnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
  vnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
endif

" Use CTRL-S for selections ranges.
" Requires 'textDocument/selectionRange' support of language server.
nmap <silent> <C-s> <Plug>(coc-range-select)
xmap <silent> <C-s> <Plug>(coc-range-select)

" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocAction('format')

" Add `:Fold` command to fold current buffer.
command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

" Add (Neo)Vim's native statusline support.
" NOTE: Please see `:h coc-status` for integrations with external plugins that
" provide custom statusline: lightline.vim, vim-airline.
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

" Mappings for CoCList
" Show all diagnostics.
nnoremap <silent><nowait> <space>a  :<C-u>CocList diagnostics<cr>
" Manage extensions.
nnoremap <silent><nowait> <space>e  :<C-u>CocList extensions<cr>
" Show commands.
nnoremap <silent><nowait> <space>c  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>
" Do default action for next item.
nnoremap <silent><nowait> <space>j  :<C-u>CocNext<CR>
" Do default action for previous item.
nnoremap <silent><nowait> <space>k  :<C-u>CocPrev<CR>
" Resume latest coc list.
nnoremap <silent><nowait> <space>p  :<C-u>CocListResume<CR>
```

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/48434243/124927079-d9569100-e01b-11eb-83c5-22506473fd84.png)

**Comment by arunanshub** [comment]
Downgraded:
- `coc-rust-analyzer` to `0.46.0`, `0.45.0`.
- `rust-analyzer` to `2021-06-28`, `2021-06-21`.

The problem still persists. And I'm not sure who's at fault? 😕

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
