### ISSUE TITLE
Failed to run CocCommand on CocNvimInit autocmd

### ISSUE THREAD

**Issue by sainnhe** [neoclide/coc.nvim#3203]
## Result from CocInfo

```
## versions

vim version: NVIM v0.6.0-dev+26-g9c7e04eb3
node version: v16.4.2
coc.nvim version: 0.0.80-f43bee3e4b
coc.nvim directory: /home/sainnhe/.local/share/nvim/plugins/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2021-07-09T09:29:05.496 INFO (pid:219061) [services] - registered service "diagnostic-languageserver"
2021-07-09T09:29:05.578 INFO (pid:219061) [coc-git] - Looking for git in: git
2021-07-09T09:29:05.593 INFO (pid:219061) [services] - registered service "highlight"
2021-07-09T09:29:05.834 INFO (pid:219061) [plugin] - coc.nvim 0.0.80-f43bee3e4b initialized with node: v16.4.2 after 443ms
2021-07-09T09:29:05.836 INFO (pid:219061) [attach] - receive notification: runCommand [ 'explorer' ]
2021-07-09T09:29:05.853 ERROR (pid:219061) [attach] - Notification error: runCommand [ 'explorer' ] Error: Command: explorer not found
    at CommandManager.executeCommand (/home/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:65362:17)
    at Commands.runCommand (/home/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:66899:44)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Plugin.cocAction (/home/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:70131:19)
    at async NeovimClient2.<anonymous> (/home/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:70240:15)
2021-07-09T09:29:05.887 INFO (pid:219061) [services] - registered service "vimlsp"
2021-07-09T09:29:05.887 INFO (pid:219061) [services] - vim language server state change: stopped => starting
2021-07-09T09:29:06.118 INFO (pid:219061) [services] - vim language server state change: starting => running
2021-07-09T09:29:06.120 INFO (pid:219061) [services] - service vimlsp started
2021-07-09T09:29:06.257 INFO (pid:219061) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocGitStatusChange' ]
2021-07-09T09:29:08.857 INFO (pid:219061) [attach] - receive notification: showInfo []
```

## Describe the bug

Since commit f43bee3e4b6b705eab32417acdf39d857b2dce8e, I can't create autocmd to run `CocCommand` via `CocNvimInit` event.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim
set nocompatible
set runtimepath^=/path/to/coc.nvim
filetype plugin indent on
syntax on
set hidden

let g:coc_data_home = fnamemodify(stdpath('data'), ':p') . 'coc'
let g:coc_global_extensions = ['coc-explorer']

augroup CocCustom
  autocmd!
  autocmd User CocNvimInit CocCommand explorer
augroup END
```

- Start (neo)vim with command: `nvim -u mini.vim`

- An error is reported: `[coc.nvim]: Error on "runCommand": Command: explorer not found`

**Comment by chemzqm** [comment]
Because `CocNvimInit` doesn't wait for extensions ready any more (some extensions could take too long time), the extension needs adds `onCommand` event in `activationEvents` of packages.json or register the command without synchronize during activate.

You can use a timer to hack
