### ISSUE TITLE
doHover doesn't work in Man pages using NeoVim 0.5.0

### ISSUE THREAD

**Issue by Frederick888** [neoclide/coc.nvim#3244]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0
node version: v16.5.0
coc.nvim version: 0.0.80-9fd90ad761
coc.nvim directory: /Users/fzhang/.vim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2021-07-27T12:35:02.351 INFO (pid:80420) [services] - registered service "languageserver.ccls"
2021-07-27T12:35:02.353 INFO (pid:80420) [services] - registered service "languageserver.dockerfile"
2021-07-27T12:35:02.353 INFO (pid:80420) [services] - registered service "languageserver.bash"
2021-07-27T12:35:02.353 INFO (pid:80420) [services] - registered service "languageserver.cmake"
2021-07-27T12:35:02.353 INFO (pid:80420) [services] - registered service "languageserver.sql"
2021-07-27T12:35:02.371 INFO (pid:80420) [services] - registered service "diagnostic-languageserver"
2021-07-27T12:35:02.466 INFO (pid:80420) [coc-git] - Looking for git in: git
2021-07-27T12:35:02.581 INFO (pid:80420) [plugin] - coc.nvim 0.0.80-9fd90ad761 initialized with node: v16.5.0 after 334ms
2021-07-27T12:35:04.244 INFO (pid:80420) [attach] - receive notification: doAutocmd [ 2 ]
2021-07-27T12:35:04.259 INFO (pid:80420) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocDiagnosticChange' ]
2021-07-27T12:35:06.823 INFO (pid:80420) [attach] - receive notification: doHover []
2021-07-27T12:35:06.824 ERROR (pid:80420) [attach] - Notification error: doHover [] Error: current buffer 2 not attached
    at _D.getCurrentState (/Users/fzhang/.vim/plugged/coc.nvim/build/index.js:254:29267)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async cD.onHover (/Users/fzhang/.vim/plugged/coc.nvim/build/index.js:245:470)
    at async TD.cocAction (/Users/fzhang/.vim/plugged/coc.nvim/build/index.js:254:42180)
    at async _N.<anonymous> (/Users/fzhang/.vim/plugged/coc.nvim/build/index.js:254:43786)
2021-07-27T12:36:06.908 INFO (pid:80420) [attach] - receive notification: showInfo []
```

## Describe the bug

The `nnoremap <silent> K :call <SID>show_documentation()<CR>` in README.md, which uses `doHover`, doesn't work in manual pages using NeoVim 0.5.0. Instead of jumping to the manpage under cursor, it shows `[coc.nvim]: Error on "doHover": current buffer 2 not attached`.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set runtimepath^=~/.vim runtimepath+=~/.vim/after
  let &packpath = &runtimepath

  " vim-plug
  call plug#begin()

  Plug 'neoclide/coc.nvim', {'branch': 'release'}

  call plug#end()

  let mapleader = ','
  let maplocalleader = ';'

  "" ==== Start Coc Configurations ====

  " Some servers have issues with backup files, see #649
  set nobackup
  set nowritebackup

  " Better display for messages
  set cmdheight=2

  " You will have bad experience for diagnostic messages when it's default 4000.
  set updatetime=300

  " Don't give |ins-completion-menu| messages.
  set shortmess+=c

  " Use K to show documentation in preview window
  nnoremap <silent> K :call <SID>show_documentation()<CR>
  function! s:show_documentation()
    " if (index(['vim','help'], &filetype) >= 0)
    "   execute 'h ' . expand('<cword>')
    " elseif (coc#rpc#ready())
      call CocActionAsync('doHover')
    " else
    "   execute '!' . &keywordprg . " " . expand('<cword>')
    " endif
  endfunction

  " ==== End Coc Configurations ====
  ```

- Start neovim with command: `vim -u mini.vim`

- `:Man git`
- Move cursor to e.g. `gittutorial(7)`
- <kbd>K</kbd>

The same setup works using NeoVim 0.4.4.

**Comment by chemzqm** [comment]
It's expected for `nofile` buffer, checkout `:h coc-action-ensureDocument`
