### ISSUE TITLE
Sometimes, the float window for warning/error message can't close automaticlly.

### ISSUE THREAD

**Issue by zoumi** [neoclide/coc.nvim#3245]
## Result from CocInfo
run :CocInfo didn't show me anything in gvim.

## Describe the bug
The float window for warning/error message can't close automaticlly after I moving away the cursor.

## Reproduce the bug

It happens "sometimes", I don't know how to reproduce.

## Screenshots (optional)
![Snipaste_2021-07-27_16-55-44](https://user-images.githubusercontent.com/5162901/127127894-281fd42e-34ad-4bb8-b60f-a5f57f56b556.jpg)

my gvim version:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 18 2021 22:02:48)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-3182
Compiled by appveyor@APPVYR-WIN
```

**Comment by chemzqm** [comment]
Try trigger CursorHold

**Comment by zoumi** [comment]
I modify the function coc#float#check_related() to
```vim
" Close related windows if target window is not visible.
function! coc#float#check_related() abort
  let invalids = []
  let ids = coc#float#get_float_win_list(1)
  echomsg "ids" . string(ids)
  for id in ids
    let target = getwinvar(id, 'target_winid', 0)
    if (target && index(ids, target) == -1) || getwinvar(id, 'kind', '') == 'pum'
      call add(invalids, id)
    endif
  endfor
  if !s:popup_list_api
    let s:popup_list = filter(ids, "index(invalids, v:val) == -1")
  endif
  echomsg "invalids" . string(invalids)
  for id in invalids
    call coc#float#close(id)
  endfor
endfunction
```
When this bug is triggered, I trigger the CursorHold manually, and get this output:
ids[1016]
invalids[]

**Comment by zoumi** [comment]
There is no window with id 1016 exists.

**Comment by zoumi** [comment]
coc-nvim.log may help.

```
2021-07-29T11:29:01.942 INFO (pid:3728) [plugin] - coc.nvim 0.0.80-19ead882b9 initialized with node: v14.17.0 after 289ms
2021-07-29T11:29:01.972 INFO (pid:3728) [services] - registered service "clangd"
2021-07-29T11:29:01.972 INFO (pid:3728) [services] - clangd state change: stopped => starting
2021-07-29T11:29:01.985 INFO (pid:3728) [language-client-index] - Language server "clangd" started with 1648
2021-07-29T11:29:02.027 INFO (pid:3728) [services] - clangd state change: starting => running
2021-07-29T11:29:02.032 INFO (pid:3728) [services] - service clangd started
2021-07-29T11:29:04.283 ERROR (pid:3728) [semanticTokens-buffer] - Error on semanticTokens highlight: Error: Range#create called with invalid arguments[631, 101, 631, 4294967312]
    at Object.e [as create] (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:60:17158)
    at bD.doHighlight (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:253:11010)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-07-29T11:29:04.283 ERROR (pid:3728) [node-client] - resumeNotification not called within same tick: Error
    at EN.pauseNotification (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:32:4591)
    at bD.doHighlight (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:253:10822)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-07-29T11:29:05.064 ERROR (pid:3728) [node-client] - resumeNotification not called within same tick: Error
    at EN.pauseNotification (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:32:4591)
    at Zi.close (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:139:4162)
    at D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:139:1790
    at D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:66:3680
    at new Promise (<anonymous>)
    at a (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:66:3632)
    at D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:66:3331
    at Array.map (<anonymous>)
    at Z2.fire (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:66:3324)
    at EN.<anonymous> (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:253:42035)
2021-07-29T11:29:07.328 INFO (pid:3728) [completion-complete] - Results from: snippets,around,clangd,tag
2021-07-29T11:29:09.418 ERROR (pid:3728) [node-client] - resumeNotification not called within same tick: Error
    at EN.pauseNotification (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:32:4591)
    at GX.stop (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:230:37415)
    at GX.onInsertLeave (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:230:35250)
    at D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:66:3680
    at new Promise (<anonymous>)
    at a (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:66:3632)
    at D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:66:3331
    at Array.map (<anonymous>)
    at Z2.fire (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:66:3324)
    at EN.<anonymous> (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:253:42035)
2021-07-29T11:29:09.947 ERROR (pid:3728) [node-client] - resumeNotification not called within same tick: Error
    at EN.pauseNotification (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:32:4591)
    at nT._refresh (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:186:3131)
```

**Comment by zoumi** [comment]
I'm doubt coc.nvim can't work when computer has no access to the Internet.
Sometimes,the autocomplete broken when I'm offline.

**Comment by chemzqm** [comment]
You can debug it or check the log
