### ISSUE TITLE
Installing an extension results in an error: " E118: Too many arguments for function: coc#util#install "

### ISSUE THREAD

**Issue by cpdean** [neoclide/coc.nvim#327]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

```
## versions

vim version: NVIM v0.3.1
node version: v8.9.0
coc.nvim version: 0.0.46
term: screen-256color
platform: linux

## Error messages
UnhandledRejection: request nvim_call_function - Vim:E117: Unknown function: coc#util#echo_line
Error: request nvim_call_function - Vim:E117: Unknown function: coc#util#echo_line
    at events_1.EventEmitter.constructor.(anonymous function).Promise.transport.request (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:33:28)
    at Transport.parseMessage (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:127:17)
    at DecodeStream.events_1.EventEmitter.constructor.decodeStream.on (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:43:18)
    at emitOne (events.js:116:13)
    at DecodeStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at DecodeStream.Readable.push (_stream_readable.js:208:10)
    at DecodeStream.Transform.push (_stream_transform.js:147:32)
    at DecodeBuffer.__dirname.DecodeStream.decoder.push (/snapshot/coc.nvim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)
UnhandledRejection: request nvim_call_function - Vim:E117: Unknown function: coc#util#echo_line
Error: request nvim_call_function - Vim:E117: Unknown function: coc#util#echo_line
    at events_1.EventEmitter.constructor.(anonymous function).Promise.transport.request (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:33:28)
    at Transport.parseMessage (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:127:17)
    at DecodeStream.events_1.EventEmitter.constructor.decodeStream.on (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:43:18)
    at emitOne (events.js:116:13)
    at DecodeStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at DecodeStream.Readable.push (_stream_readable.js:208:10)
    at DecodeStream.Transform.push (_stream_transform.js:147:32)
    at DecodeBuffer.__dirname.DecodeStream.decoder.push (/snapshot/coc.nvim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)
UnhandledRejection: request nvim_call_function - Vim:E117: Unknown function: coc#util#echo_line
Error: request nvim_call_function - Vim:E117: Unknown function: coc#util#echo_line
    at events_1.EventEmitter.constructor.(anonymous function).Promise.transport.request (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:33:28)
    at Transport.parseMessage (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:127:17)
    at DecodeStream.events_1.EventEmitter.constructor.decodeStream.on (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:43:18)
    at emitOne (events.js:116:13)
    at DecodeStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at DecodeStream.Readable.push (_stream_readable.js:208:10)
    at DecodeStream.Transform.push (_stream_transform.js:147:32)
    at DecodeBuffer.__dirname.DecodeStream.decoder.push (/snapshot/coc.nvim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)
UnhandledRejection: request nvim_call_function - Vim:E117: Unknown function: coc#util#echo_line
Error: request nvim_call_function - Vim:E117: Unknown function: coc#util#echo_line
    at events_1.EventEmitter.constructor.(anonymous function).Promise.transport.request (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:33:28)
    at Transport.parseMessage (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:127:17)
    at DecodeStream.events_1.EventEmitter.constructor.decodeStream.on (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:43:18)
    at emitOne (events.js:116:13)
    at DecodeStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at DecodeStream.Readable.push (_stream_readable.js:208:10)
    at DecodeStream.Transform.push (_stream_transform.js:147:32)
    at DecodeBuffer.__dirname.DecodeStream.decoder.push (/snapshot/coc.nvim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)
```

**Describe the bug**
After installing coc.vim, the `:CocInstall` command throws the following error:

```
Error detected while processing function <SNR>22_OnExit[6]..<lambda>4:
line    1:
E118: Too many arguments for function: coc#util#install
Press ENTER or type command to continue
Error detected while processing function <SNR>22_OnExit[6]..<lambda>4:
line    1:
E15: Invalid expression: coc#util#install(a:names)
```

When troubleshooting the issue locally, I attempted to downgrade my version of coc.vim by going to an older git tag (`0.0.41`) since i see a copy of it in `extra_plugins`, installed by vim-plug, but my `:CocInfo` still reports i am using 46.

**To Reproduce**

1. Open nvim.
2. Run `:CocInstall coc-rls`

**Comment by cpdean** [comment]
I figured out how to correctly pin my coc version in vim-plug, but I still kept getting the same error.

Then I noticed `:CocInfo` says that i have node 8.  I don't use nodejs anymore so I don't know if this is really old or not, but wikipedia tells me they're on node 11.

I'm on ubuntu 18.04, and so I guess the way you install nodejs is with snap:

```
sudo snap install node --classic --channel=8
sudo refresh node --channel=11
```

Now I have node 11.

uninstalling and reinstalling coc gives me an error on install, but running the `:CocInstall coc-json coc-rls` now runs without error.

CocInfo still claims I have node 8 though... what is going on here?

```
## versions

vim version: NVIM v0.3.1
node version: v8.9.0
coc.nvim version: 0.0.41
term: screen-256color
platform: linux

## Error messages
```

**Comment by chemzqm** [comment]
Node 8.9.0 is used for binary release of coc, it's expected.
Run `yarn install` to build from source code in folder of coc.nvim.

>  Vim:E117: Unknown function: coc#util#echo_line

The problem looks like you're using old vim files but newer version of binary release, probably your git pull failed.
Remove folder of coc.nvim and reinstall it again.
