### ISSUE TITLE
ESlint crash when open empty js, vue files in /tmp

### ISSUE THREAD

**Issue by deathmaz** [neoclide/coc.nvim#33]
**Describe the bug**
When i create new js or vue file in /tmp and open it, i get 
```
[Info  - 12:20:16 PM] ESLint library loaded from: /home/maz/.config/yarn/global/node_modules/eslint/lib/api.js
[Error - 12:20:16 PM] ESLint stack trace:
[Error - 12:20:16 PM] Error: Cannot find module 'babel-eslint'
    at ModuleResolver.resolve (/home/maz/.config/yarn/global/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at loadFromDisk (/home/maz/.config/yarn/global/node_modules/eslint/lib/config/config-file.js:514:42)
    at Object.load (/home/maz/.config/yarn/global/node_modules/eslint/lib/config/config-file.js:564:20)
    at Config.getPersonalConfig (/home/maz/.config/yarn/global/node_modules/eslint/lib/config.js:154:37)
    at Config.getLocalConfigHierarchy (/home/maz/.config/yarn/global/node_modules/eslint/lib/config.js:248:41)
    at Config.getConfigHierarchy (/home/maz/.config/yarn/global/node_modules/eslint/lib/config.js:179:43)
    at Config.getConfigVector (/home/maz/.config/yarn/global/node_modules/eslint/lib/config.js:286:21)
    at Config.getConfig (/home/maz/.config/yarn/global/node_modules/eslint/lib/config.js:329:29)
    at processText (/home/maz/.config/yarn/global/node_modules/eslint/lib/cli-engine.js:162:33)
    at CLIEngine.executeOnText (/home/maz/.config/yarn/global/node_modules/eslint/lib/cli-engine.js:596:17)
```

 
**To Reproduce**
1. `cd /tmp`;
2. `nvim test.js`;

**Expected behavior**
There shouldn't be any errors from coc.nvim when i `nvim new-file`

**Screenshots**
I recoreded the issue with asciinema - https://asciinema.org/a/mnsHRJBXXyulWuLJ7mFCTEIvE

**Desktop (please complete the following information):**
Terminal: tilda
Version: 1.4.1-1
tmux 2.7-1
NVIM v0.3.1
Kernel: 4.14.57-1-MANJARO x86_64 bits: 64 Desktop: Xfce 4.12.4 Distro: Manjaro Linux

**Comment by chemzqm** [comment]
That's because the global eslint can't resolve `babel-eslint` module.
You can either install babel-eslint to global directory of yarn by:
```
yarn global add babel-eslint
```
or remove `babel-eslint` configuration from global eslint configuration file, like: `~/.eslintrc`
