### ISSUE TITLE
Initialize Haskell Language Server Failed

### ISSUE THREAD

**Issue by kands-code** [neoclide/coc.nvim#3305]
## versions

vim version: NVIM v0.5.0
node version: v16.7.0
coc.nvim version: 0.0.80-6b774412d1
coc.nvim directory: /home/kands/.local/share/nvim/site/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2021-08-23T11:58:07.808 WARN (pid:9756) [attach] - Plugin not ready when received "highlight" []
2021-08-23T11:58:07.935 INFO (pid:9756) [services] - registered service "languageserver.haskell"
2021-08-23T11:58:07.939 INFO (pid:9756) [services] - haskell state change: stopped => starting
2021-08-23T11:58:07.940 INFO (pid:9756) [services] - registered service "languageserver.racket"
2021-08-23T11:58:07.940 INFO (pid:9756) [services] - registered service "languageserver.lua"
2021-08-23T11:58:08.048 INFO (pid:9756) [plugin] - coc.nvim 0.0.80-6b774412d1 initialized with node: v16.7.0 after 228ms
2021-08-23T11:58:08.055 INFO (pid:9756) [language-client-index] - Language server "languageserver.haskell" started with 9767
2021-08-23T11:58:09.326 INFO (pid:9756) [services] - haskell state change: starting => stopped
2021-08-23T11:58:09.326 INFO (pid:9756) [services] - haskell state change: stopped => starting
2021-08-23T11:58:09.332 INFO (pid:9756) [language-client-index] - Language server "languageserver.haskell" started with 9795
2021-08-23T11:58:10.574 INFO (pid:9756) [services] - haskell state change: starting => stopped
2021-08-23T11:58:10.574 INFO (pid:9756) [services] - haskell state change: stopped => starting
2021-08-23T11:58:10.580 INFO (pid:9756) [language-client-index] - Language server "languageserver.haskell" started with 9822
2021-08-23T11:58:11.895 INFO (pid:9756) [services] - haskell state change: starting => stopped
2021-08-23T11:58:11.895 INFO (pid:9756) [services] - haskell state change: stopped => starting
2021-08-23T11:58:11.903 INFO (pid:9756) [language-client-index] - Language server "languageserver.haskell" started with 9849
2021-08-23T11:58:13.199 INFO (pid:9756) [services] - haskell state change: starting => stopped
2021-08-23T11:58:13.200 ERROR (pid:9756) [services] - Server languageserver.haskell failed to start: Error: Connection to server got closed. Server will not be restarted.
    at Fh.handleConnectionClosed (/home/kands/.local/share/nvim/site/plugged/coc.nvim/build/index.js:224:967)
    at Fh.handleConnectionClosed (/home/kands/.local/share/nvim/site/plugged/coc.nvim/build/index.js:224:28612)
    at t (/home/kands/.local/share/nvim/site/plugged/coc.nvim/build/index.js:224:386)
    at fq.invoke (/home/kands/.local/share/nvim/site/plugged/coc.nvim/build/index.js:35:9670)
    at Ed.fire (/home/kands/.local/share/nvim/site/plugged/coc.nvim/build/index.js:35:10436)
    at xi (/home/kands/.local/share/nvim/site/plugged/coc.nvim/build/index.js:36:10897)
    at fq.invoke (/home/kands/.local/share/nvim/site/plugged/coc.nvim/build/index.js:35:9670)
    at Ed.fire (/home/kands/.local/share/nvim/site/plugged/coc.nvim/build/index.js:35:10436)
    at rE.fireClose (/home/kands/.local/share/nvim/site/plugged/coc.nvim/build/index.js:36:525)
    at Socket.<anonymous> (/home/kands/.local/share/nvim/site/plugged/coc.nvim/build/index.js:36:1307)
2021-08-23T11:58:25.652 INFO (pid:9756) [attach] - receive notification: showInfo []

## Describe the bug

Can't initialize hls (haskell-language-server) correctly in a haskell project, **but single file is fine**.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim
let mapleader=" "
set number
set relativenumber
set cursorline
syntax on
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on
set autoindent
set cindent
set wrap
call plug#begin('~/.local/share/nvim/site/plugged')
Plug 'vim-airline/vim-airline'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
let g:coc_global_extensions = [
    \'coc-json',
    \'coc-vimlsp',
    \'coc-syntax',
    \'coc-toml',
    \'coc-yaml',
    \'coc-sh',
    \'coc-tsserver',
    \'coc-explorer'
\]
set hidden
set updatetime=100
set shortmess+=c
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

- The relative configuration of coc
```json
{
    "languageserver": {
        "haskell": {
            "command": "haskell-language-server-wrapper",
            "args": [
                "--lsp"
            ],
            "rootPatterns": [
                "*.cabal",
                "stack.yaml",
                "cabal.project",
                "package.yaml",
                "hie.yaml"
            ],
            "filetypes": [
                "haskell",
                "lhaskell"
            ]
        }
    }
}
```

## Screenshots (optional)

![图片](https://user-images.githubusercontent.com/59006329/130390576-882c9037-1c92-45d5-bb5f-153b0e91998f.png)

## extra

Some additional information

```
stack --numeric-version
2.7.1

cabal --version
cabal-install version 3.2.0.0
compiled using version 3.2.1.0 of the Cabal library

ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.5

haskell-language-server-wrapper --version
haskell-language-server version: 1.2.0.0 (GHC: 8.10.5) (PATH: /usr/bin/haskell-language-server-wrapper)

uname -a
Linux ksc 5.13.12-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 18 Aug 2021 20:49:05 +0000 x86_64 GNU/Linux
```

system: ArchLinux

**Comment by kands-code** [comment]
stack, cabal-install and ghc are installed from archlinux official repo

**Comment by chemzqm** [comment]
> 2021-08-23T11:58:13.199 INFO (pid:9756) [services] - haskell state change: starting => stopped

We don't know the reason, you have to  check the log of your language server.
