### ISSUE TITLE
CocInstall failed for coc-volar

### ISSUE THREAD

**Issue by duongdominhchau** [neoclide/coc.nvim#3322]
## Result from CocInfo

```
vim version: NVIM v0.5.0
node version: v16.8.0
coc.nvim version: 0.0.80-c90a07eec8
coc.nvim directory: /usr/share/nvim/runtime/pack/coc/start/coc.nvim
term: xterm
platform: linux

## Log of coc.nvim

2021-08-29T09:34:09.082 INFO (pid:11753) [services] - registered service "css"
2021-08-29T09:34:09.084 INFO (pid:11753) [services] - Css language server state change: stopped => starting
2021-08-29T09:34:09.103 INFO (pid:11753) [services] - registered service "highlight"
2021-08-29T09:34:09.340 INFO (pid:11753) [services] - registered service "stylelintplus"
2021-08-29T09:34:09.340 INFO (pid:11753) [services] - stylelint language server state change: stopped => starting
2021-08-29T09:34:09.342 INFO (pid:11753) [plugin] - coc.nvim 0.0.80-c90a07eec8 initialized with node: v16.8.0 after 368ms
2021-08-29T09:34:09.349 INFO (pid:11753) [language-client-index] - css started with 11764
2021-08-29T09:34:09.360 INFO (pid:11753) [language-client-index] - highlight started with 11770
2021-08-29T09:34:09.368 INFO (pid:11753) [language-client-index] - stylelintplus started with 11771
2021-08-29T09:34:09.526 INFO (pid:11753) [services] - Css language server state change: starting => running
2021-08-29T09:34:09.531 INFO (pid:11753) [services] - service css started
2021-08-29T09:34:09.649 INFO (pid:11753) [services] - stylelint language server state change: starting => running
2021-08-29T09:34:09.650 INFO (pid:11753) [services] - service stylelintplus started
2021-08-29T09:34:33.966 INFO (pid:11753) [attach] - receive notification: installExtensions [ '@yaegassy/coc-volar' ]
2021-08-29T09:34:34.015 INFO (pid:11753) [model-installer] - Using npm from: /usr/bin/npm
2021-08-29T09:34:34.020 INFO (pid:11753) [model-installer] - Get info from https://registry.npmjs.org/
2021-08-29T09:34:35.071 ERROR (pid:11753) [extensions] - Error on install @yaegassy/coc-volar TypeError: Cannot read property 'yaegassy/coc-volar' of undefined
    at Installer.getInfo (/usr/share/nvim/runtime/pack/coc/start/coc.nvim/build/index.js:50139:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Installer.install (/usr/share/nvim/runtime/pack/coc/start/coc.nvim/build/index.js:50004:20)
2021-08-29T09:34:35.426 INFO (pid:11753) [attach] - receive notification: highlight []
2021-08-29T09:34:38.279 INFO (pid:11753) [attach] - receive notification: showInfo []
2021-08-29T09:34:38.307 INFO (pid:11753) [attach] - receive request: CocAutocmd [ 'BufReadCmd', 'output', 'output:///info' ]
2021-08-29T09:34:38.845 INFO (pid:11753) [attach] - receive notification: highlight []
2021-08-29T09:34:43.871 INFO (pid:11753) [attach] - receive notification: showInfo []
2021-08-29T09:34:44.416 INFO (pid:11753) [attach] - receive notification: highlight []
2021-08-29T09:34:47.594 INFO (pid:11753) [attach] - receive notification: highlight []
2021-08-29T09:34:50.032 INFO (pid:11753) [attach] - receive notification: highlight []
2021-08-29T09:34:52.064 INFO (pid:11753) [attach] - receive notification: showInfo []
```

## Describe the bug

`:CocInstall @yaegassy/coc-volar` fails with the message `Cannot read property 'yaegassy/coc-volar' of undefined`

## Reproduce the bug

- Install `coc` as a directory inside `/usr/share/nvim/runtime/pack`
- Create file `mini.vim` with：
  ```vim
  set nocompatible
  filetype plugin indent on
  syntax on
  set hidden
  ```
- Start (neo)vim with command: `vim -u mini.vim`
- Type `:CocInstall @yaegassy/coc-volar`, the error will be printed.

**Comment by yaegassy** [comment]
@duongdominhchau It seems that you are using a very very old version of coc.nvim.

Update coc.nvim itself to the latest version and try again.

**Comment by duongdominhchau** [comment]
Thank you, I tried with latest commit and it works now.
