### ISSUE TITLE
Can't start coc-omnisharp: [coc.nvim]: Uncaught exception: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by ProgrammingLife** [neoclide/coc.nvim#3324]
## Result from CocInfo
```
vim version: NVIM v0.5.0-dev+1122-g8f4b9b8b7
node version: v14.17.0
coc.nvim version: 0.0.80-3086844413
coc.nvim directory: /home/denis/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim
2021-08-30T10:15:27.094 INFO (pid:10408) [services] - registered service "languageserver.godot"
2021-08-30T10:15:27.096 INFO (pid:10408) [services] - registered service "languageserver.clojure-lsp"
2021-08-30T10:15:27.164 INFO (pid:10408) [plugin] - coc.nvim 0.0.80-3086844413 initialized with node: v14.17.0 after 161ms
2021-08-30T10:15:27.180 INFO (pid:10408) [language-client-index] - Language server "cs" started with 10420
2021-08-30T10:15:29.996 INFO (pid:10408) [attach] - receive notification: highlight []
2021-08-30T10:15:32.862 INFO (pid:10408) [attach] - receive notification: highlight []
2021-08-30T10:15:34.055 ERROR (pid:10408) [server] - uncaughtException Error: Header must provide a Content-Length property.
    at nC.onData (/home/denis/.vim/plugged/coc.nvim/build/index.js:35:14451)
    at Socket.<anonymous> (/home/denis/.vim/plugged/coc.nvim/build/index.js:35:14181)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

```

## Describe the bug
I opened cshap files many times without any problem. But in 30 minutes after that I opened cs file again and it shows me that error message. I didn't update any of my configs. It started happening out of nowhere, with no change in configuration.
It happens only with omnisharp. With typescript files all wok fine.

## Reproduce the bug
```
nvim test.cs
vim test.cs
```

## Attempts to fix it:
- Removed ~/.vim/plugged
- Removed ~/.config/coc directory and reinstall omnisharp with: `CocInstall coc-omnisharp`
- dotnet clean
It didn't solve an issue for me.

- Create file `mini.vim` with：

The same problem still exists with the mini.vim config.

## Screenshots (optional)
n/a

**Comment by ProgrammingLife** [comment]
I've fixed this with some strange solution. As it was happen with the Unity project I've done this:
`rm MyUnityProject/obj/Debug/*`
There are two project .cache-files.
After that my coc-omnisharp seems to be working now but how much time it will work - I don't know.

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by ProgrammingLife** [comment]
Faced with this problem again and it worked only after doing the exact order of these steps:

1. `dotnet clean *.sln && rm obj/Debug/*`
2. Open project in Unity
3. `nvim Assets/Scripts/*.cs`

Step 2 is very important. It should run right after the step 1.
