### ISSUE TITLE
Error when saving files when calling the function coc#util#echo_line

### ISSUE THREAD

**Issue by fraco-oxza** [neoclide/coc.nvim#3364]
### versions
vim version: NVIM v0.5.0
node version: v16.9.0
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /root/.local/share/nvim/plugged/coc.nvim
term: xterm
platform: linux 

### Log of coc.nvim 
2021-09-09T22:09:57.371 INFO (pid:137) [services] - registered service "languageserver.terraform"
2021-09-09T22:09:57.413 INFO (pid:137) [services] - registered service "languageserver.ccls"
2021-09-09T22:09:58.724 INFO (pid:137) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v16.9.0 after 1529ms
2021-09-09T22:10:01.650 INFO (pid:137) [attach] - receive notification: showInfo []

## Describe the bug

When saving some files, for example .py, it throws the following error:

```
[coc.nvim]: UnhandledRejection: request error nvim_call_function - Vim:E117: Unknown function: coc#util#
echo_line                                                                                      
Error
    at wF.request (/root/.local/share/nvim/plugged/coc.nvim/build/index.js:30:34430)
    at wF.call (/root/.local/share/nvim/plugged/coc.nvim/build/index.js:33:3671)
    at Timeout._onTimeout (/root/.config/coc/extensions/node_modules/coc-python/lib/index.js:123358:39)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```
the files are saved as expected, the only problem that I persist is is a warning

## Reproduce the bug

I do not have the knowledge to do my vim configuration in a file, therefore I will leave a docker image with everything ready to reproduce the problem. they should just run:
```bash
nvim app.py
```
wait for python to finish loading and save it with :w, in a few seconds the error appears

you can load it with
```
docker load < nvim_coc_issue.tar.gz
docker run -it nvim_coc_issue
```
[docker image](https://api.audymus.ml/static/nvim_coc_issue.tar.gz)

**Comment by oblitum** [comment]
coc-python has been deprecated and the repository is now archived. You should either migrate to coc-pyright or coc-jedi (or some other one). Read the warning at: https://github.com/neoclide/coc-python#coc-python.
