### ISSUE TITLE
coc.nvim coc-pyright server doesn't work

### ISSUE THREAD

**Issue by r2ri2** [neoclide/coc.nvim#3379]
## versions

vim version: NVIM v0.5.0
node version: v16.9.1
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: C:\Users\r2ri2\.nvim-data\plugged\coc.nvim
term: vtpcon
platform: win32

## Log of coc.nvim

2021-09-14T23:43:43.158 INFO (pid:4940) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v16.9.1 after 171ms
2021-09-14T23:43:47.641 INFO (pid:4940) [services] - registered service "pyright"
2021-09-14T23:43:47.642 INFO (pid:4940) [services] - Pyright Server state change: stopped => starting
2021-09-14T23:43:48.320 INFO (pid:4940) [services] - Pyright Server state change: starting => stopped
2021-09-14T23:43:48.320 INFO (pid:4940) [services] - Pyright Server state change: stopped => starting
2021-09-14T23:43:49.002 INFO (pid:4940) [services] - Pyright Server state change: starting => stopped
2021-09-14T23:43:49.002 INFO (pid:4940) [services] - Pyright Server state change: stopped => starting
2021-09-14T23:43:49.685 INFO (pid:4940) [services] - Pyright Server state change: starting => stopped
2021-09-14T23:43:49.685 INFO (pid:4940) [services] - Pyright Server state change: stopped => starting
2021-09-14T23:43:50.405 INFO (pid:4940) [services] - Pyright Server state change: starting => stopped
2021-09-14T23:43:50.405 ERROR (pid:4940) [services] - Server pyright failed to start: Error: Connection to server got closed. Server will not be restarted.
    at np.handleConnectionClosed (C:\Users\r2ri2\.nvim-data\plugged\coc.nvim\build\index.js:223:967)
    at np.handleConnectionClosed (C:\Users\r2ri2\.nvim-data\plugged\coc.nvim\build\index.js:223:28612)
    at t (C:\Users\r2ri2\.nvim-data\plugged\coc.nvim\build\index.js:223:386)
    at tM.invoke (C:\Users\r2ri2\.nvim-data\plugged\coc.nvim\build\index.js:35:9670)
    at sd.fire (C:\Users\r2ri2\.nvim-data\plugged\coc.nvim\build\index.js:35:10436)
    at bi (C:\Users\r2ri2\.nvim-data\plugged\coc.nvim\build\index.js:36:10897)
    at tM.invoke (C:\Users\r2ri2\.nvim-data\plugged\coc.nvim\build\index.js:35:9670)
    at sd.fire (C:\Users\r2ri2\.nvim-data\plugged\coc.nvim\build\index.js:35:10436)
    at _M.fireClose (C:\Users\r2ri2\.nvim-data\plugged\coc.nvim\build\index.js:35:12716)
    at ChildProcess.<anonymous> (C:\Users\r2ri2\.nvim-data\plugged\coc.nvim\build\index.js:62:11975)
2021-09-14T23:44:19.288 INFO (pid:4940) [attach] - receive notification: showInfo []

## Describe the bug

I cant make coc.vim python servers work in python files properly.
- I first installed normally the coc.vim extension 
![image](https://user-images.githubusercontent.com/84429399/133363766-b8bc0275-c6b8-4621-95bd-23f69d0dcaf8.png)

- Second y used CocInstall coc-pyright command to avoid edit the coc-settings.json

- I tried with coc-python disabling coc-pyright, but i doesn't work either.

## Reproduce the bug

- mini.vim

set
![image](https://user-images.githubusercontent.com/84429399/133365008-f1666fd5-1439-416b-8965-52ecb7fe12ab.png)

CocInfo
![image](https://user-images.githubusercontent.com/84429399/133364899-263ef018-0084-431b-af1c-acf483e38add.png)

error
![image](https://user-images.githubusercontent.com/84429399/133364167-474bf848-c78f-4e1c-8794-65ab95ae7932.png)

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/84429399/133364617-426dd6c5-576c-4506-8075-aed301061396.png)

![image](https://user-images.githubusercontent.com/84429399/133364462-6aef48c8-4d39-4257-a728-d49166058bf0.png)

coc-settings.json file is empty
![image](https://user-images.githubusercontent.com/84429399/133364478-c9d07391-8a4c-4199-9212-a5c747ca91a1.png)

![image](https://user-images.githubusercontent.com/84429399/133361788-4f847f1b-3c1d-46c7-9238-91c22cccf768.png)

**Comment by fannheyward** [comment]
What's the output of `:CocCommand workspace.showOutput Pyright`?

**Comment by r2ri2** [comment]
![image](https://user-images.githubusercontent.com/84429399/133368883-3b2e6e9c-8f91-4251-9644-9fbbb9cdcd80.png)
![image](https://user-images.githubusercontent.com/84429399/133369164-e6c3b0f2-b020-4a29-b45c-f1b0e1f502ea.png)

**Comment by yaegassy** [comment]
@r2ri2 Do you use any other coc extensions? For example, if you install `coc-tsserver`, will it work in your environment?

**Install**:

```
:CocInstall coc-tsserver
```

**Edit**:

```
nvim index.ts
```

**Comment by fannheyward** [comment]
@r2ri2 your coc-pyright was not successfully installed, try `:CocUninstall coc-pyright` and reinstall again.

**Comment by r2ri2** [comment]
@yaegassy 
## it works with ts apparently 
![image](https://user-images.githubusercontent.com/84429399/133372385-bb28bf49-0925-4213-84dc-1c890ef94a73.png)
![image](https://user-images.githubusercontent.com/84429399/133372531-855498a9-453c-405c-868d-42bb4405f99a.png)

@fannheyward
## the same :( 
![image](https://user-images.githubusercontent.com/84429399/133372606-791d43d5-23da-4faf-bc72-e3d54b870d29.png)
![image](https://user-images.githubusercontent.com/84429399/133372669-cfd03dc5-de55-488f-8d3a-81347548e0fa.png)
![image](https://user-images.githubusercontent.com/84429399/133372798-1d8b1979-7da5-4398-8e4d-efd31361ad6d.png)
![image](https://user-images.githubusercontent.com/84429399/133372832-e43226e8-b9ef-4d75-af70-80f0a82a6399.png)
![image](https://user-images.githubusercontent.com/84429399/133372880-3fbf0d6c-c49a-4b9d-964e-08cfd425a40b.png)

**Comment by fannheyward** [comment]
Make a project in another place, not `C:\Users\r2ri2\AppData\Local\nvim`, and try again. Looks like it's a permission error.

**Comment by r2ri2** [comment]
@fannheyward 

### This is in another disk and folder, but it looks to be the same.

![image](https://user-images.githubusercontent.com/84429399/133374611-03f3c269-aadb-41d0-8bae-44e09f2e476a.png)
![image](https://user-images.githubusercontent.com/84429399/133374662-757cef12-d9b9-4641-a02c-8123ca5f7ba1.png)

**Comment by fannheyward** [comment]
@r2ri2 move to https://github.com/fannheyward/coc-pyright/issues/623 because it's not related coc.nvim.
