### ISSUE TITLE
[vim-node-coc]: Plugin initialized error: DatabaseError: Can't Load Database 

### ISSUE THREAD

**Issue by faurehu** [neoclide/coc.nvim#339]
**Result from CocInfo**
I get `Not an editor command: CocInfo`

**Describe the bug**

I was using coc only for completion until it stopped autocompleting, I think it took me a while to realise it wasn't working and longer to make some time to look into it. I couldn't figure out what was wrong so I decided to delete the package and reinstall it using VimPlug.

When I start nvim with coc enabled I get the following error message as I launch:

```
[vim-node-coc]: Plugin initialized error: DatabaseError: Can't Load Database                                                                                                                                                
    at JsonDB.load (/snapshot/coc.nvim/node_modules/node-json-db/dist/JsonDB.js:307:21)                                                                                                                                     
    at JsonDB.retrieveData (/snapshot/coc.nvim/node_modules/node-json-db/dist/JsonDB.js:82:10)                                                                                                                              
    at JsonDB.getData (/snapshot/coc.nvim/node_modules/node-json-db/dist/JsonDB.js:162:17)                                                                                                                                  
    at JsonDB.exists (/snapshot/coc.nvim/node_modules/node-json-db/dist/JsonDB.js:172:12)                                                                                                                                   
    at Extensions.isDisabled (/snapshot/coc.nvim/lib/extensions.js:197:19)                                                                                                                                                  
    at Extensions.getExtensionState (/snapshot/coc.nvim/lib/extensions.js:136:29)                                                                                                                                           
    at __dirname.globalExtensionStats.names.map.name (/snapshot/coc.nvim/lib/extensions.js:527:29)                                                                                                                          
    at Array.map (<anonymous>)                                                                                                                                                                                              
    at Extensions.globalExtensionStats (/snapshot/coc.nvim/lib/extensions.js:523:22)                                                                                                                                        
    at Extensions.init (/snapshot/coc.nvim/lib/extensions.js:46:26)    
```

**Comment by chemzqm** [comment]
Should be file permission issue, try remove the file by `rm ~/.config/coc/db.json`

**Comment by faurehu** [comment]
This was it, many thanks.
