### ISSUE TITLE
ccls and other language servers crash

### ISSUE THREAD

**Issue by AxizY** [neoclide/coc.nvim#3398]
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0
node version: v14.17.6
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /Users/name/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2021-09-25T13:27:29.946 ERROR (pid:3540) [extensions] - Error on load /Users/name/.config/coc/extensions/node_modules/coc-ccls Error: main file ./lib/extension.js not found, you may need to build the project.
    at k5.checkDirectory (/Users/name/.vim/plugged/coc.nvim/build/index.js:237:3949)
    at /Users/name/.vim/plugged/coc.nvim/build/index.js:234:8707
    at new Promise (<anonymous>)
    at /Users/name/.vim/plugged/coc.nvim/build/index.js:234:8627
    at Array.map (<anonymous>)
    at k5.globalExtensionStats (/Users/name/.vim/plugged/coc.nvim/build/index.js:234:8620)
    at k5.init (/Users/name/.vim/plugged/coc.nvim/build/index.js:233:46196)
    at Aw.init (/Users/name/.vim/plugged/coc.nvim/build/index.js:263:54923)
    at /Users/name/.vim/plugged/coc.nvim/build/index.js:263:58323
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-09-25T13:27:30.023 INFO (pid:3540) [services] - registered service "languageserver.ccls"
2021-09-25T13:27:30.028 INFO (pid:3540) [services] - ccls state change: stopped => starting
2021-09-25T13:27:30.030 INFO (pid:3540) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v14.17.6 after 87ms
2021-09-25T13:27:30.038 INFO (pid:3540) [services] - ccls state change: starting => stopped
2021-09-25T13:27:30.060 ERROR (pid:3540) [services] - Server languageserver.ccls failed to start: Launching server "languageserver.ccls" using command ccls failed.
2021-09-25T13:27:30.061 ERROR (pid:3540) [language-client-index] - Error: spawn ccls ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ccls',
  path: 'ccls',
  spawnargs: []
}
2021-09-25T13:27:30.370 INFO (pid:3540) [attach] - receive notification: highlight []
2021-09-25T13:27:52.014 INFO (pid:3540) [attach] - receive notification: showInfo []


```

## Describe the bug

Upon opening any file and when running `:CocList`, I get a red warning
`[coc.nvim] Unable to load global extension at /Users/name/.config/coc/extensions/node_modules/coc-ccls: main file ./lib/extension.js not found, you may need to build the project.`

Whenever opening a c++ file, I also get:
`[coc.nvim] Server languageserver.ccls failed to start: Launching server "languageserver.ccls" using command ccls failed.`

Running `:checkhealth` outputs
```
health#lsp#check
========================================================================
  - ERROR: Failed to run healthcheck for "lsp" plugin. Exception:
    function health#check[21]..health#lsp#check, line 2
    Vim(lua):E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/lsp/health.lua:9: attempt to call field 'get_level' (a nil value)
```

I also get similar errors when using pyright

## Reproduce the bug
init.vim:

  ```vim
set number
filetype plugin indent on
syntax on
set tabstop=4
set autoindent
set expandtab
set nowrap

call plug#begin('~/.vim/plugged')

Plug 'jaredgorski/spacecamp'
Plug 'junegunn/seoul256.vim'
Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

source ~/.config/nvim/plug-config/coc.vim
let g:node_client_debug = 1

colo spacecamp
```

My coc config:
```json
{
"languageserver": {
  "ccls": {
    "command": "ccls",
    "filetypes": ["c", "cc", "cpp", "c++", "objc", "objcpp"],
    "rootPatterns": [".ccls", "compile_commands.json", ".git/", ".hg/"],
    "trace.server": "verbose",
    "initializationOptions": {
        "cache": {
          "directory": "/tmp/ccls"
        }
      }
  }
}        
}
```

**Comment by fannheyward** [comment]
1. you have `coc-ccls` installed but it's not successful installed, how do you install `coc-ccls`?
2. you should not use `coc-ccls` and language server ccls in coc-settings.json at the same time.

**Comment by AxizY** [comment]
I was able to fix it by running `brew install ccls`, it just seemed I didn't have it installed.
