### ISSUE TITLE
After upgrading the VIM version, we got the following error

### ISSUE THREAD

**Issue by stark-jarvis** [neoclide/coc.nvim#3406]
client coc abnormal exit with: -1
client coc stopped!
[coc.nvim] Error on execute python script: request error nvim_command - Vim(pyxfile):SyntaxError: invalid syntax   

## versions

vim version: VIM - Vi IMproved 8.2 8023455
node version: v10.16.0
coc.nvim version: 0.0.80-825a54d780
coc.nvim directory: /Users/weiko/.vim/autoload/plugged/coc.nvim
term: dumb
platform: darwin

## Log of coc.nvim

2021-09-30T09:43:42.493 INFO (pid:1838) [extensions] - Skipped load vim plugin from "/Users/weiko/.config/coc/extensions/node_modules/coc-snippets", "coc-snippets" already global extension.
2021-09-30T09:43:42.570 INFO (pid:1838) [coc-git] - Looking for git in: git
2021-09-30T09:43:42.898 INFO (pid:1838) [plugin] - coc.nvim 0.0.80-825a54d780 initialized with node: v10.16.0 after 432ms
2021-09-30T09:43:42.919 INFO (pid:1838) [services] - registered service "tsserver"
2021-09-30T09:43:43.148 ERROR (pid:1838) [node-client] - request error on "nvim_command" [ 'exe \'pyxfile \'.fnameescape(\'/var/folders/pp/g7qfxwwj2p5bgwcpsyg8w13r0000gn/T/vg8Ya8s/coc.nvim-1838/coc-ultisnips-IqIOEuAZcv.py\')' ] Vim(pyxfile):SyntaxError: invalid syntax Error
    at nM.request (/Users/weiko/.vim/autoload/plugged/coc.nvim/build/index.js:20:34604)
    at nM.command (/Users/weiko/.vim/autoload/plugged/coc.nvim/build/index.js:22:6887)
    at UltiSnippetsProvider.executePythonCode (/Users/weiko/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:2511:40)
    at UltiSnippetsProvider.init (/Users/weiko/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:2202:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2021-09-30T09:44:33.606 INFO (pid:1838) [attach] - receive notification: showInfo []

**Comment by fannheyward** [comment]
Your vim didn't have Python support, while cog-snippets will run Python to do some snippets parsing work. Make sure your vim supports Python, or add `"snippets.ultisnips.usePythonx": false` in your coc-settings.json to disable the Python parse.

**Comment by chemzqm** [comment]
Seems the generated python file have syntax error `coc-ultisnips-IqIOEuAZcv.py`

**Comment by erlonbie** [comment]
Sorry for commenting in a closed issue, but I'm facing this issue.

adding ` "snippets.ultisnips.usePythonx": false ` did not solve for me.

If write ` vim --version ` on the terminal, It tells me +python/dyn and +python3/dyn. 

If I type the command (inside vim) `:pyx import sys; print(sys.version)`, shows 2.7.18 (default, `some date`)

Should it be python 3?

**Comment by chemzqm** [comment]
@erlonbie some of your snippets might require python3 to work.

**Comment by erlonbie** [comment]
@chemzqm thanks for the reply!

I solved it by reinstalling vim with python3 support. For some reason uninstalling vim and reinstalling with a package manager (pacman) did not solve the problem. I had to go clone official vim repo and building from source with some commands that I found in a blogpost (I don't know if I can post the link it here).
