### ISSUE TITLE
Rename "Not allowed in a popup window"

### ISSUE THREAD

**Issue by hejops** [neoclide/coc.nvim#3448]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8023441
node version: v16.11.1
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /home/user/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2021-10-28T18:54:17.511 INFO (pid:328886) [services] - registered service "languageserver.bash"
2021-10-28T18:54:17.556 INFO (pid:328886) [services] - registered service "diagnostic-languageserver"
2021-10-28T18:54:17.557 INFO (pid:328886) [services] - diagnostic language service state change: stopped => starting
2021-10-28T18:54:17.852 INFO (pid:328886) [services] - registered service "pyright"
2021-10-28T18:54:17.852 INFO (pid:328886) [services] - Pyright Server state change: stopped => starting
2021-10-28T18:54:17.859 INFO (pid:328886) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v16.11.1 after 461ms
2021-10-28T18:54:18.004 INFO (pid:328886) [services] - diagnostic language service state change: starting => running
2021-10-28T18:54:18.009 INFO (pid:328886) [services] - service diagnostic-languageserver started
2021-10-28T18:54:18.115 INFO (pid:328886) [services] - Pyright Server state change: starting => running
2021-10-28T18:54:18.121 INFO (pid:328886) [services] - service pyright started
2021-10-28T18:54:18.947 INFO (pid:328886) [attach] - receive notification: highlight []
2021-10-28T18:54:23.270 INFO (pid:328886) [attach] - receive notification: rename []
2021-10-28T18:54:23.280 ERROR (pid:328886) [node-client] - request error on "nvim_call_function" [ 'coc#float#create_prompt_win', [ 'New name', 'rawlines', {} ] ] Vim(wincmd):E994: Not allowed in a popup window Error
    at wF.request (/home/user/.vim/plugged/coc.nvim/build/index.js:30:34430)
    at wF.call (/home/user/.vim/plugged/coc.nvim/build/index.js:33:3671)
    at Xj.requestInput (/home/user/.vim/plugged/coc.nvim/build/index.js:191:1898)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Sw.rename (/home/user/.vim/plugged/coc.nvim/build/index.js:263:7829)
    at async Aw.cocAction (/home/user/.vim/plugged/coc.nvim/build/index.js:263:55784)
    at async wF.<anonymous> (/home/user/.vim/plugged/coc.nvim/build/index.js:263:57390)
2021-10-28T18:54:23.281 ERROR (pid:328886) [window] - Error on requestInput: Error
    at wF.request (/home/user/.vim/plugged/coc.nvim/build/index.js:30:34430)
    at wF.call (/home/user/.vim/plugged/coc.nvim/build/index.js:33:3671)
    at Xj.requestInput (/home/user/.vim/plugged/coc.nvim/build/index.js:191:1898)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Sw.rename (/home/user/.vim/plugged/coc.nvim/build/index.js:263:7829)
    at async Aw.cocAction (/home/user/.vim/plugged/coc.nvim/build/index.js:263:55784)
    at async wF.<anonymous> (/home/user/.vim/plugged/coc.nvim/build/index.js:263:57390)
2021-10-28T18:54:24.303 INFO (pid:328886) [attach] - receive notification: highlight []
```

## Describe the bug

In a python file, I call coc-rename from a keybind as follows,

```
nmap R <Plug>(coc-rename)
```

input a new name in a popup window, but the new name is not applied.

Oddly enough, when editing the same python file using the minimal config file provided (as below), the rename works as expected (also in a popup window).

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

I suppose this is due to some setting I use, but I'm not sure where in my configs to look. How can I figure out the cause of this behaviour?

**Comment by fannheyward** [comment]
Try to bisect your configs, maybe other plugins related.

**Comment by hejops** [comment]
In case anyone has this issue, it turns out it was due to some conflict with a plugin called `roman/golden-ratio`.
