### ISSUE TITLE
CocList xxx show nothing

### ISSUE THREAD

**Issue by zoumi** [neoclide/coc.nvim#3570]
## Result from CocInfo
:CocInfo didn't work.

coc log
```
2022-01-14T15:18:47.624 INFO (pid:12560) [attach] - receive notification: openList [ 'commands' ]

2022-01-14T15:18:47.865 ERROR (pid:12560) [node-client] - resumeNotification not called within same tick: Error
    at pF.pauseNotification (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:34:4907)
    at xy.doHighlight (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:227:11160)
    at D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:221:1554
    at JF.invoke (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:35:9670)
    at td.fire (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:35:10436)
    at my.drawItems (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:220:21859)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:221:2051

2022-01-14T15:18:47.865 ERROR (pid:12560) [node-client] - resumeNotification not called within same tick: Error
    at pF.pauseNotification (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:34:4907)
    at my.setLines (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:220:22261)
    at my.drawItems (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:220:21935)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:221:2051

2022-01-14T15:18:47.865 ERROR (pid:12560) [node-client] - resumeNotification not called within same tick: Error
    at pF.pauseNotification (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:34:4907)
    at by.updateStatus (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:227:1538)
    at D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:221:1435
    at JF.invoke (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:35:9670)
    at td.fire (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:35:10436)
    at my.drawItems (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:220:21974)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:221:2051

2022-01-14T15:18:56.653 INFO (pid:12560) [attach] - receive notification: openList [ 'commands' ]

2022-01-14T15:18:56.866 ERROR (pid:12560) [node-client] - resumeNotification not called within same tick: Error
    at pF.pauseNotification (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:34:4907)
    at xy.doHighlight (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:227:11160)
    at D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:221:1554
    at JF.invoke (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:35:9670)
    at td.fire (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:35:10436)
    at my.drawItems (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:220:21859)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:221:2051

2022-01-14T15:18:56.866 ERROR (pid:12560) [node-client] - resumeNotification not called within same tick: Error
    at pF.pauseNotification (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:34:4907)
    at my.setLines (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:220:22261)
    at my.drawItems (D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:220:21935)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async D:\programs\vim\vimfiles\bundle\coc.nvim\build\index.js:221:2051
```

## Describe the bug

:CocList commads show nothing

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

## Screenshots (optional)

Gvim verison:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 18 2021 22:02:48)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-3182
Compiled by appveyor@APPVYR-WIN
Huge version with GUI.  Features included (+) or not (-):
...
```

**Comment by chemzqm** [comment]
Try lastest release branch.
