### ISSUE TITLE
Errors occur in filetype where "let b:coc_suggest_disable = 1" is set

### ISSUE THREAD

**Issue by yaegassy** [neoclide/coc.nvim#3587]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.0-dev+908-g431915fe6
node version: v16.13.1
coc.nvim version: 0.0.80-e2ced8502b
coc.nvim directory: /private/tmp/coc.nvim
term: iTerm.app
platform: darwin
```

## Describe the bug

Errors occur in filetype where `let b:coc_suggest_disable = 1` is set.

```
[coc.nvim]: UnhandledRejection: Cannot read properties of null (reading 'input')
TypeError: Cannot read properties of null (reading 'input')
    at Completion.triggerCompletion (/private/tmp/coc.nvim/build/index.js:61024:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Timeout._onTimeout (/private/tmp/coc.nvim/build/index.js:60979:13)
```

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/tmp/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden

  autocmd FileType markdown let b:coc_suggest_disable = 1
  ```

- Start (neo)vim with command: `nvim -u mini.vim`

- `:e README.md`

## Screenshots (mp4)

https://user-images.githubusercontent.com/188642/150260318-ab81c344-3220-4fc9-94bd-acd33c9be2b3.mp4

**Comment by lorentzforces** [comment]
Also encountered this today. Issue was not present as of commit a9dee8531de92d2a90c66e6a0494f20855035a8a on `release`.
