### ISSUE TITLE
[coc.nvim] UnhandledRejection: TypeError: Cannot read properties of null (reading 'uri')

### ISSUE THREAD

**Issue by michael-odonovan** [neoclide/coc.nvim#3602]
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

## versions
vim version: NVIM v0.6.1
node version: v16.13.0
coc.nvim version: 0.0.80-452671ce30
coc.nvim directory: /home/mike/.config/nvim/plugins-storage/coc.nvim
term: screen-256color
platform: linux

## Log of coc.nvim
2022-01-27T10:50:03.774 INFO (pid:14546) [services] - registered service "stylelintplus"
2022-01-27T10:50:03.779 INFO (pid:14546) [plugin] - coc.nvim initialized with node: v16.13.0 after 816ms
2022-01-27T10:50:05.543 INFO (pid:14546) [services] - registered service "tsserver"
2022-01-27T10:50:07.420 ERROR (pid:14546) [server] - unhandledRejection  Promise {
  <rejected> TypeError: Cannot read properties of null (reading 'uri')
      at findApplicableStatus (/home/mike/.config/coc/extensions/node_modules/coc-eslint/lib/index.js:4821:75)
      at updateStatusBarAndDiagnostics (/home/mike/.config/coc/extensions/node_modules/coc-eslint/lib/index.js:4851:35)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
} TypeError: Cannot read properties of null (reading 'uri')
    at findApplicableStatus (/home/mike/.config/coc/extensions/node_modules/coc-eslint/lib/index.js:4821:75)
    at updateStatusBarAndDiagnostics (/home/mike/.config/coc/extensions/node_modules/coc-eslint/lib/index.js:4851:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-01-27T10:50:16.869 INFO (pid:14546) [completion-complete] - 2 results from: around,buffer
2022-01-27T10:52:49.177 ERROR (pid:14546) [server] - unhandledRejection  Promise {

## Describe the bug

This error stops me from opening terminals and new windows.

[coc.nvim] UnhandledRejection: TypeError: Cannot read properties of null (reading 'uri')

## Reproduce the bug
I can't reproduce the bug with the mini.vim
However when I comment out coc.vim plugin and it isn't loaded into my normal init.vim, the bug goes away.

Any help much appreciated.

**Comment by fannheyward** [comment]
`:CocUpdate` to upgrade your coc-eslint please, looks like you're using an old coc-eslint release.
