### ISSUE TITLE
preview window  show the last selected item, not the current selected

### ISSUE THREAD

**Issue by Fmajor** [neoclide/coc.nvim#3618]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8020814
node version: v14.16.1
coc.nvim version: 0.0.80-698ec197cd
coc.nvim directory: /home/random/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2022-02-03T18:37:32.687 WARN (pid:32536) [language-client-client] - disableCompletion in the client options is deprecated. use disabledFeatures instead. Error
    at new dD (/home/random/.vim/plugged/coc.nvim/build/index.js:216:39188)
    at new Xh (/home/random/.vim/plugged/coc.nvim/build/index.js:222:27963)
    at Object.activate (/home/random/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:23470:18)
    at /home/random/.vim/plugged/coc.nvim/build/index.js:236:1411
    at new Promise (<anonymous>)
    at Object.activate (/home/random/.vim/plugged/coc.nvim/build/index.js:236:1369)
    at A5.activate (/home/random/.vim/plugged/coc.nvim/build/index.js:233:7436)
    at /home/random/.vim/plugged/coc.nvim/build/index.js:235:283
    at new Promise (<anonymous>)
    at s (/home/random/.vim/plugged/coc.nvim/build/index.js:235:45)
2022-02-03T18:37:32.702 WARN (pid:32536) [language-client-client] - disableDiagnostics in the client options is deprecated. use disabledFeatures instead. Error
    at new dD (/home/random/.vim/plugged/coc.nvim/build/index.js:216:39188)
    at new Xh (/home/random/.vim/plugged/coc.nvim/build/index.js:222:27963)
    at Object.activate (/home/random/.config/coc/extensions/node_modules/coc-pyright/lib/index.js:23470:18)
    at /home/random/.vim/plugged/coc.nvim/build/index.js:236:1411
    at new Promise (<anonymous>)
    at Object.activate (/home/random/.vim/plugged/coc.nvim/build/index.js:236:1369)
    at A5.activate (/home/random/.vim/plugged/coc.nvim/build/index.js:233:7436)
    at /home/random/.vim/plugged/coc.nvim/build/index.js:235:283
    at new Promise (<anonymous>)
    at s (/home/random/.vim/plugged/coc.nvim/build/index.js:235:45)
2022-02-03T18:37:32.704 INFO (pid:32536) [services] - registered service "pyright"
2022-02-03T18:37:32.705 INFO (pid:32536) [services] - Pyright Server state change: stopped => starting
2022-02-03T18:37:32.716 INFO (pid:32536) [plugin] - coc.nvim initialized with node: v14.16.1 after 165ms
2022-02-03T18:37:32.847 INFO (pid:32536) [services] - Pyright Server state change: starting => running
2022-02-03T18:37:32.851 INFO (pid:32536) [services] - service pyright started
2022-02-03T18:37:37.779 INFO (pid:32536) [completion-complete] - 2 results from: around,pyright
2022-02-03T18:37:37.937 INFO (pid:32536) [completion-complete] - 2 results from: around,pyright
2022-02-03T18:37:38.067 INFO (pid:32536) [completion-complete] - 2 results from: around,pyright
2022-02-03T18:37:40.969 INFO (pid:32536) [completion-complete] - 2 results from: around,pyright
2022-02-03T18:37:41.029 INFO (pid:32536) [completion-complete] - 2 results from: around,pyright
2022-02-03T18:37:41.155 INFO (pid:32536) [completion-complete] - 2 results from: around,pyright
2022-02-03T18:39:38.936 INFO (pid:32536) [completion-complete] - 2 results from: around,pyright
2022-02-03T18:39:38.993 INFO (pid:32536) [completion-complete] - 2 results from: around,pyright
2022-02-03T18:39:39.230 INFO (pid:32536) [completion-complete] - 2 results from: around,pyright
2022-02-03T18:42:24.476 INFO (pid:32536) [attach] - receive notification: showInfo []

```

## Describe the bug
preview window  show the last selected item, not the current selected, see screenshot

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.
- see descriptions below screenshots

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/1620897/152329082-c18c0c9c-39f4-410d-9418-5ef546488d2a.png)
when i select `func3`, it preview nothing
when i select `func2`, it preview `func3`
when i select `func1`, it preview `func2`
when i select `func2` again, it preview `func1`

**Comment by chemzqm** [comment]
It's wired.

**Comment by Fmajor** [comment]
It works!
thanks a lot for the quick response!
