### ISSUE TITLE
Wrong type for argument 2 when calling nvim_exec_lua, expecting Array

### ISSUE THREAD

**Issue by daveyarwood** [neoclide/coc.nvim#3645]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.0-dev
node version: v15.14.0
coc.nvim version: 0.0.80-72aeffd7ab
coc.nvim directory: /home/dave/.vim/bundle/coc.nvim
term: tmux-256color
platform: linux

## Log of coc.nvim

2022-02-14T13:53:53.874 INFO (pid:735860) [services] - registered service "languageserver.clojure-lsp"
2022-02-14T13:53:53.879 INFO (pid:735860) [services] - clojure-lsp state change: stopped => starting
2022-02-14T13:53:53.880 INFO (pid:735860) [services] - registered service "languageserver.elmLS"
2022-02-14T13:53:53.884 INFO (pid:735860) [coc-conjure] - CoC conjure enabled!
2022-02-14T13:53:53.899 INFO (pid:735860) [services] - registered service "diagnostic-languageserver"
2022-02-14T13:53:53.904 INFO (pid:735860) [plugin] - coc.nvim initialized with node: v15.14.0 after 284ms
2022-02-14T13:53:53.912 INFO (pid:735860) [language-client-index] - Language server "languageserver.clojure-lsp" started with 735938
2022-02-14T13:54:07.629 INFO (pid:735860) [services] - clojure-lsp state change: starting => running
2022-02-14T13:54:07.640 INFO (pid:735860) [services] - service languageserver.clojure-lsp started
2022-02-14T13:54:14.081 ERROR (pid:735860) [node-client] - request error on "nvim_exec_lua" [ "return require('conjure.eval')['completions-promise'](...)", 'n' ] Wrong type for argument 2 when calling nvim_exec_lua, expecting Array Error
    at $A.request (/home/dave/.vim/bundle/coc.nvim/build/index.js:29:43279)
    at $A.lua (/home/dave/.vim/bundle/coc.nvim/build/index.js:32:3346)
    at lua (/home/dave/.config/coc/extensions/node_modules/coc-conjure/index.js:5:15)
    at completions (/home/dave/.config/coc/extensions/node_modules/coc-conjure/index.js:15:19)
    at Kr.doComplete (/home/dave/.config/coc/extensions/node_modules/coc-conjure/index.js:34:27)
    at Kr.doComplete (/home/dave/.vim/bundle/coc.nvim/build/index.js:239:6889)
    at /home/dave/.vim/bundle/coc.nvim/build/index.js:240:7874
    at new Promise (<anonymous>)
    at Tw.completeSource (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:7492)
    at async Promise.all (index 3)
2022-02-14T13:54:14.082 ERROR (pid:735860) [node-client] - Complete conjure error: request error nvim_exec_lua - Wrong type for argument 2 when calling nvim_exec_lua, expecting Array Error
    at $A.echoError (/home/dave/.vim/bundle/coc.nvim/build/index.js:33:1744)
    at Tw.completeSource (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:8648)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Promise.all (index 3)
    at async Tw.completeSources (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:7027)
    at async Tw.doComplete (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:11431)
    at async fG._doComplete (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:19709)
    at async fG.startCompletion (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:17642)
    at async fG.triggerCompletion (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:22224)
    at async Timeout._onTimeout (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:20985)
2022-02-14T13:54:14.082 ERROR (pid:735860) [completion-complete] - Complete error: conjure Error
    at $A.request (/home/dave/.vim/bundle/coc.nvim/build/index.js:29:43279)
    at $A.lua (/home/dave/.vim/bundle/coc.nvim/build/index.js:32:3346)
    at lua (/home/dave/.config/coc/extensions/node_modules/coc-conjure/index.js:5:15)
    at completions (/home/dave/.config/coc/extensions/node_modules/coc-conjure/index.js:15:19)
    at Kr.doComplete (/home/dave/.config/coc/extensions/node_modules/coc-conjure/index.js:34:27)
    at Kr.doComplete (/home/dave/.vim/bundle/coc.nvim/build/index.js:239:6889)
    at /home/dave/.vim/bundle/coc.nvim/build/index.js:240:7874
    at new Promise (<anonymous>)
    at Tw.completeSource (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:7492)
    at async Promise.all (index 3)
2022-02-14T13:54:15.141 INFO (pid:735860) [completion-complete] - 2 results from: around,languageserver.clojure-lsp
2022-02-14T13:54:15.530 INFO (pid:735860) [attach] - receive notification: highlight []
2022-02-14T13:54:18.964 INFO (pid:735860) [attach] - receive notification: highlight []
2022-02-14T13:54:22.972 INFO (pid:735860) [attach] - receive notification: highlight []
2022-02-14T13:54:23.414 INFO (pid:735860) [attach] - receive notification: highlight []
2022-02-14T13:54:25.534 INFO (pid:735860) [attach] - receive notification: highlight []
2022-02-14T13:54:38.617 INFO (pid:735860) [attach] - receive notification: highlight []
2022-02-14T13:54:39.313 INFO (pid:735860) [attach] - receive notification: highlight []
2022-02-14T13:54:41.780 INFO (pid:735860) [attach] - receive notification: highlight []
2022-02-14T13:54:42.877 ERROR (pid:735860) [node-client] - request error on "nvim_exec_lua" [ "return require('conjure.eval')['completions-promise'](...)", 'ao' ] Wrong type for argument 2 when calling nvim_exec_lua, expecting Array Error
    at $A.request (/home/dave/.vim/bundle/coc.nvim/build/index.js:29:43279)
    at $A.lua (/home/dave/.vim/bundle/coc.nvim/build/index.js:32:3346)
    at lua (/home/dave/.config/coc/extensions/node_modules/coc-conjure/index.js:5:15)
    at completions (/home/dave/.config/coc/extensions/node_modules/coc-conjure/index.js:15:19)
    at Kr.doComplete (/home/dave/.config/coc/extensions/node_modules/coc-conjure/index.js:34:27)
    at Kr.doComplete (/home/dave/.vim/bundle/coc.nvim/build/index.js:239:6889)
    at /home/dave/.vim/bundle/coc.nvim/build/index.js:240:7874
    at new Promise (<anonymous>)
    at Tw.completeSource (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:7492)
    at async Promise.all (index 3)
2022-02-14T13:54:42.878 ERROR (pid:735860) [node-client] - Complete conjure error: request error nvim_exec_lua - Wrong type for argument 2 when calling nvim_exec_lua, expecting Array Error
    at $A.echoError (/home/dave/.vim/bundle/coc.nvim/build/index.js:33:1744)
    at Tw.completeSource (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:8648)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Promise.all (index 3)
    at async Tw.completeSources (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:7027)
    at async Tw.doComplete (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:11431)
    at async fG._doComplete (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:19709)
    at async fG.startCompletion (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:17642)
    at async fG.triggerCompletion (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:22224)
    at async Timeout._onTimeout (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:20985)
2022-02-14T13:54:42.878 ERROR (pid:735860) [completion-complete] - Complete error: conjure Error
    at $A.request (/home/dave/.vim/bundle/coc.nvim/build/index.js:29:43279)
    at $A.lua (/home/dave/.vim/bundle/coc.nvim/build/index.js:32:3346)
    at lua (/home/dave/.config/coc/extensions/node_modules/coc-conjure/index.js:5:15)
    at completions (/home/dave/.config/coc/extensions/node_modules/coc-conjure/index.js:15:19)
    at Kr.doComplete (/home/dave/.config/coc/extensions/node_modules/coc-conjure/index.js:34:27)
    at Kr.doComplete (/home/dave/.vim/bundle/coc.nvim/build/index.js:239:6889)
    at /home/dave/.vim/bundle/coc.nvim/build/index.js:240:7874
    at new Promise (<anonymous>)
    at Tw.completeSource (/home/dave/.vim/bundle/coc.nvim/build/index.js:240:7492)
    at async Promise.all (index 3)
2022-02-14T13:54:43.869 INFO (pid:735860) [completion-complete] - 2 results from: around,languageserver.clojure-lsp
2022-02-14T13:54:44.672 INFO (pid:735860) [attach] - receive notification: highlight []
2022-02-14T13:54:46.685 WARN (pid:735860) [events] - Handler of CursorHold blocked more than 2s: Error
    at vq.on (/home/dave/.vim/bundle/coc.nvim/build/index.js:67:4123)
    at Ow.listen (/home/dave/.vim/bundle/coc.nvim/build/index.js:249:11341)
    at new Ow (/home/dave/.vim/bundle/coc.nvim/build/index.js:249:11209)
    at new sx (/home/dave/.vim/bundle/coc.nvim/build/index.js:265:21939)
    at ox.init (/home/dave/.vim/bundle/coc.nvim/build/index.js:265:34044)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /home/dave/.vim/bundle/coc.nvim/build/index.js:265:37306
2022-02-14T13:56:21.967 INFO (pid:735860) [attach] - receive notification: showInfo []
```

## Describe the bug

After recent updates, I've started seeing this error message pop up repeatedly as I type into any Clojure buffer:

```
Complete conjure error: request error nvim_exec_lua - Wrong type for argument 2 when calling nvim_exec_lua, expecting Array
```

I'm guessing this is some breaking change in the Neovim API?

I am using the unstable branch of Neovim, version `0.7.0~ubuntu1+git202202120047-e3c09cb9e-dd05b3569-7e71277fb~ubuntu20.04.1`

Related: https://github.com/Olical/conjure/issues/316  The author of Conjure says:

> Seems like there was probably a time when you could pass a string or something to `nvim_exec_lua` and it'd automatically wrap it in an array but that time has passed.

## Reproduce the bug

I don't have time to provide a minimal vimrc for this issue. Please don't close it! I think the info above is sufficient to find and fix the bug, as it appears to be a simple case of providing the wrong type of arguments to a Neovim API call (probably a breaking change on Neovim's part). The stacktrace shows where the problem is in the coc source code.

Setup:

* Be running the latest Neovim unstable
* Have Conjure and coc installed, with Conjure configured as a completion source.
* Update to the (as of right now) latest commit of coc, 07a5052858cd1415ec7a343c4980b3c59d275fca
* Open any Clojure file.
* Enter insert mode and start typing anything.

**Comment by daveyarwood** [comment]
This could be related to https://github.com/jlesquembre/coc-conjure/issues/16

**Comment by daveyarwood** [comment]
Yep, that was totally it. After upgrading coc-conjure, the problem went away :tada:

**Comment by chemzqm** [comment]
I see there was a break change introduce with node client of coc.nvim.

**Comment by chemzqm** [comment]
Should be fixed now.
