### ISSUE TITLE
cannot disable completion source for filetype

### ISSUE THREAD

**Issue by ihasdapie** [neoclide/coc.nvim#3659]
> `CocInfo` output at end of issue

## Describe the bug

I'm trying to disable some completion sources for certain filetypes, namely `python-import` for python files. In the past I was able to do this with  `g:coc_sources_disabled_map` , however, support for that was dropped in https://github.com/neoclide/coc.nvim/commit/7f2dd00637ef5adde7f89249e857c5e15e1504df and replaced with `b:coc_disabled_sources`. I tried using this by putting `let b:coc_disabled_sources = ['python-import']` in `ftplugin/python.vim` but that had no effect (nor did setting the variable manually for a python buffer and restarting `coc`) This was the case for other sources e.g. 'file' or 'around'; not just python-import.  In my opinion the old option of `g:coc_sources_disabled_map` was a lot more ergonomic for most users' use cases and is not adequately replaced by `b:coc_disabled_sources`. 

Can I get some insight on how I can disable a source for a filetype?

## Reproduce the bug

- Use suggest minimal `vimrc`
- Have `coc-pyright` installed
- Try to disable a coc completion source using `b:coc_disabled_sources`
- Observe that the completion source has not been disabled in both `CocList sources` and through just typing and seeing the completions pop up.

## Result from CocInfo

```
## versions

vim version: NVIM v0.7.0-dev+913-ge07a4b97f
node version: v14.15.0
coc.nvim version: 0.0.80-7019b69e88
coc.nvim directory: /home/ihasdapie/.config/nvim/plugged/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2022-02-20T18:13:28.720 INFO (pid:230144) [services] - registered service "languageserver.svls"
2022-02-20T18:13:28.739 WARN (pid:230144) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at new t.Actions (/home/ihasdapie/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:8301)
    at Object.t.activate (/home/ihasdapie/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:15288)
2022-02-20T18:13:28.885 INFO (pid:230144) [services] - registered service "highlight"
2022-02-20T18:13:29.009 INFO (pid:230144) [plugin] - coc.nvim initialized with node: v14.15.0 after 452ms
2022-02-20T18:13:29.057 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.073 INFO (pid:230144) [services] - registered service "vimlsp"
2022-02-20T18:13:29.073 INFO (pid:230144) [services] - vim language server state change: stopped => starting
2022-02-20T18:13:29.217 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.307 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.308 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.309 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.391 INFO (pid:230144) [services] - vim language server state change: starting => running
2022-02-20T18:13:29.395 INFO (pid:230144) [services] - service vimlsp started
2022-02-20T18:13:29.433 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.447 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.476 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.505 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.534 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.563 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.596 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.620 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.649 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.677 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.707 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.736 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.764 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.835 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.905 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:29.943 INFO (pid:230144) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-02-20T18:13:35.797 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:36.098 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:36.127 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:36.155 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:36.185 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:36.213 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:36.241 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:36.270 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:36.299 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:36.567 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:36.855 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:36.856 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:36.871 INFO (pid:230144) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-02-20T18:13:37.494 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:37.566 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:37.574 INFO (pid:230144) [completion-complete] - 0 results from: 
2022-02-20T18:13:37.886 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:37.893 INFO (pid:230144) [completion-complete] - 0 results from: 
2022-02-20T18:13:38.077 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:38.190 INFO (pid:230144) [completion-complete] - 1 results from: snippets
2022-02-20T18:13:38.261 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:38.325 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:38.389 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:38.437 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:38.544 INFO (pid:230144) [completion-complete] - 1 results from: snippets
2022-02-20T18:13:38.925 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:39.037 INFO (pid:230144) [completion-complete] - 1 results from: snippets
2022-02-20T18:13:39.509 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:39.741 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:39.852 INFO (pid:230144) [completion-complete] - 2 results from: snippets,vimlsp
2022-02-20T18:13:39.878 INFO (pid:230144) [completion-complete] - 2 results from: snippets,vimlsp
2022-02-20T18:13:40.021 INFO (pid:230144) [completion-complete] - 2 results from: snippets,vimlsp
2022-02-20T18:13:40.023 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:40.157 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:40.266 INFO (pid:230144) [completion-complete] - 1 results from: snippets
2022-02-20T18:13:40.285 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:40.394 INFO (pid:230144) [completion-complete] - 1 results from: snippets
2022-02-20T18:13:40.453 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:40.561 INFO (pid:230144) [completion-complete] - 1 results from: snippets
2022-02-20T18:13:40.648 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:40.648 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:13:40.661 INFO (pid:230144) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-02-20T18:13:41.150 INFO (pid:230144) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-02-20T18:14:15.472 INFO (pid:230144) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_coc_helper_1',
  'BufWipeout',
  4
]
2022-02-20T18:14:15.473 INFO (pid:230144) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'BufWipeout',
  4
]
2022-02-20T18:14:15.662 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:15.962 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:15.992 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:16.020 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:16.049 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:16.078 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:16.106 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:16.135 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:16.165 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:16.194 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:16.302 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:16.462 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:16.606 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:17.118 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:17.278 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:17.421 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:17.566 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:17.710 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:17.862 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:18.006 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:18.478 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:18.926 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:19.088 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:19.089 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:19.201 INFO (pid:230144) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-02-20T18:14:20.238 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:20.590 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:20.599 INFO (pid:230144) [completion-complete] - 0 results from: 
2022-02-20T18:14:20.848 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:20.849 INFO (pid:230144) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-20T18:14:21.350 INFO (pid:230144) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-02-20T18:16:57.710 INFO (pid:230144) [attach] - receive notification: showInfo []
```

**Comment by yaegassy** [comment]
@ihasdapie This may not be the essential issue of this issue, but it is about `python-import` source in `coc-pyright`.

If you want to disable `python-import`, there is a dedicated configuration option.

**coc-settings.json**:

```jsonc
{
  "pyright.completion.importSupport": false
}
```

Set it up if you need it at this stage.

**Comment by chemzqm** [comment]
Use `:echo b:coc_disabled_sources` in your buffer and you check verbose log `:h :CocOpenLog`

**Comment by ihasdapie** [comment]
The verbose log is below and I've also attached a screenshot with the output of `echo b:coc_disabled_sources` showing that it is set properly while coc is still using the `python-import` completion source

```
2022-02-21T12:31:41.198 INFO (pid:546313) [services] - registered service "languageserver.svls"
2022-02-21T12:31:41.215 WARN (pid:546313) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at new t.Actions (/home/ihasdapie/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:8301)
    at Object.t.activate (/home/ihasdapie/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:15288)
2022-02-21T12:31:41.388 INFO (pid:546313) [services] - registered service "highlight"
2022-02-21T12:31:41.654 INFO (pid:546313) [services] - registered service "pyright"
2022-02-21T12:31:41.655 INFO (pid:546313) [services] - Pyright Server state change: stopped => starting
2022-02-21T12:31:41.717 INFO (pid:546313) [plugin] - coc.nvim initialized with node: v14.15.0 after 669ms
2022-02-21T12:31:41.994 INFO (pid:546313) [services] - Pyright Server state change: starting => running
2022-02-21T12:31:41.997 INFO (pid:546313) [services] - service pyright started
2022-02-21T12:31:42.862 INFO (pid:546313) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-02-21T12:31:43.776 INFO (pid:546313) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-02-21T12:31:50.971 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:31:50.980 INFO (pid:546313) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_coc_helper_1',
  'BufWipeout',
  4
]
2022-02-21T12:31:50.981 INFO (pid:546313) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'BufWipeout',
  4
]
2022-02-21T12:31:50.981 INFO (pid:546313) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_coc_helper_1',
  'BufDelete',
  4
]
2022-02-21T12:31:50.981 INFO (pid:546313) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'BufDelete',
  4
]
2022-02-21T12:31:51.013 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:31:51.037 ERROR (pid:546313) [node-client] - Error event from nvim: 0 Vim:E117: Unknown function: coc#highlight#clear_win_matches
2022-02-21T12:31:51.859 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:31:52.451 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:31:52.457 ERROR (pid:546313) [node-client] - Error event from nvim: 0 Vim:E117: Unknown function: coc#highlight#clear_win_matches
2022-02-21T12:31:55.868 INFO (pid:546313) [attach] - receive notification: openLog []
2022-02-21T12:31:55.873 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:31:55.907 ERROR (pid:546313) [node-client] - Error event from nvim: 0 Vim:E117: Unknown function: coc#highlight#clear_win_matches
2022-02-21T12:31:55.930 INFO (pid:546313) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-02-21T12:31:56.924 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:31:56.937 ERROR (pid:546313) [node-client] - Error event from nvim: 0 Vim:E117: Unknown function: coc#highlight#clear_win_matches
2022-02-21T12:31:57.509 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:31:57.551 ERROR (pid:546313) [node-client] - Error event from nvim: 0 Vim:E117: Unknown function: coc#highlight#clear_win_matches
2022-02-21T12:31:57.574 INFO (pid:546313) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-02-21T12:31:58.010 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:31:58.026 ERROR (pid:546313) [node-client] - Error event from nvim: 0 Vim:E117: Unknown function: coc#highlight#clear_win_matches
2022-02-21T12:31:58.701 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:31:58.725 ERROR (pid:546313) [node-client] - Error event from nvim: 0 Vim:E117: Unknown function: coc#highlight#clear_win_matches
2022-02-21T12:32:01.059 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:01.274 INFO (pid:546313) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-02-21T12:32:01.360 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:01.389 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:01.417 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:01.446 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:01.475 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:01.578 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:01.734 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:01.880 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:03.242 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:03.417 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:03.450 INFO (pid:546313) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-02-21T12:32:03.939 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:04.239 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:04.268 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:04.986 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:05.288 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:05.316 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:05.344 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:05.373 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:05.401 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:05.606 INFO (pid:546313) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-02-21T12:32:10.500 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:10.709 INFO (pid:546313) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-02-21T12:32:10.800 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:10.831 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:10.858 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:10.886 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:10.915 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:10.944 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:10.975 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.003 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.031 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.059 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.088 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.246 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.546 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.576 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.605 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.635 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.662 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.690 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.719 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.748 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.777 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.806 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:11.836 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:14.384 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:14.624 INFO (pid:546313) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-02-21T12:32:14.688 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:14.719 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:14.743 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:14.772 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:14.801 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:15.067 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:15.368 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:15.397 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:15.426 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:15.455 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:15.484 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:15.891 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]
2022-02-21T12:32:17.550 INFO (pid:546313) [attach] - receive notification: doAutocmd [ 1 ]

```


![image](https://user-images.githubusercontent.com/54821716/155003492-13aa34b1-9ba8-47d3-a865-767e2baf03ea.png)

**Comment by chemzqm** [comment]
Use `let $NVIM_COC_LOG_LEVEL = 'trace'` in your vimrc.
