### ISSUE TITLE
renameCurrentWord doesn't work with gopls's rename

### ISSUE THREAD

**Issue by sazary** [neoclide/coc.nvim#3669]
## Describe the bug

I'm using [`coc-go`](https://github.com/josa42/coc-go) to use `gopls` with `coc.nvim`, and while `gopls` supports renaming, `coc.nvim` can't use it and uses a simple, document-wide rename of the symbol.  

## Reproduce the bug

 - Install `coc-go` extension
 - Set the config described in the documents of `gopls` for `coc.nvim`:
```
  "languageserver": {
    "golang": {
      "trace.server": "verbose",
      "command": "gopls",
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"],
      "initializationOptions": {
        "usePlaceholders": true
      }
    }
  },
```
 - Move cursor to a word and enter `CocCommand document.renameCurrentWord`
 - An error is shown in the bottom bar: `[coc.nvim] Rename provider not found, extract word ranges from current buffer`
 - This error is logged in `coc-go`'s trace log: 
```
[Error  - 3:38:55 PM] Request textDocument/rename failed.
  Message: old and new names are the same: Subscriber
  Code: 0 
```

## Result from CocInfo

```
## versions

vim version: NVIM v0.5.1
node version: v16.3.0
coc.nvim version: 0.0.80-c7d7756089
coc.nvim directory: /home/sazary/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2022-02-25T15:31:10.417 INFO (pid:2040480) [configurations] - Add folder configuration from cwd: /home/sazary/code/go/websocket/.vim/coc-settings.json
2022-02-25T15:31:10.419 INFO (pid:2040480) [configurations] - Change folder configuration from cwd to: /home/sazary/code/go/websocket/.vim/coc-settings.json
2022-02-25T15:31:11.076 INFO (pid:2040480) [services] - registered service "languageserver.golang"
2022-02-25T15:31:11.080 INFO (pid:2040480) [services] - golang state change: stopped => starting
2022-02-25T15:31:11.096 WARN (pid:2040480) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at new t.Actions (/home/sazary/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:8301)
    at Object.t.activate (/home/sazary/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:15288)
2022-02-25T15:31:11.142 INFO (pid:2040480) [services] - registered service "diagnostic-languageserver"
2022-02-25T15:31:11.181 INFO (pid:2040480) [services] - registered service "highlight"
2022-02-25T15:31:11.204 INFO (pid:2040480) [services] - registered service "json"
2022-02-25T15:31:11.204 INFO (pid:2040480) [services] - Json language server state change: stopped => starting
2022-02-25T15:31:11.709 INFO (pid:2040480) [coc-tabnine] - Using tabnine from /home/sazary/.config/coc/extensions/coc-tabnine-data/binaries/4.1.3/x86_64-unknown-linux-musl/TabNine
2022-02-25T15:31:11.815 INFO (pid:2040480) [plugin] - coc.nvim initialized with node: v16.3.0 after 879ms
2022-02-25T15:31:11.825 INFO (pid:2040480) [language-client-index] - Language server "languageserver.golang" started with 2040501
2022-02-25T15:31:11.911 INFO (pid:2040480) [services] - registered service "go"
2022-02-25T15:31:11.912 INFO (pid:2040480) [services] - gopls state change: stopped => starting
2022-02-25T15:31:11.922 WARN (pid:2040480) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at Object.t.initStatusBar (/home/sazary/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:155873)
    at Object.t.activate (/home/sazary/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23099)
2022-02-25T15:31:11.968 INFO (pid:2040480) [services] - golang state change: starting => running
2022-02-25T15:31:11.975 INFO (pid:2040480) [services] - service languageserver.golang started
2022-02-25T15:31:11.988 INFO (pid:2040480) [services] - Json language server state change: starting => running
2022-02-25T15:31:11.997 INFO (pid:2040480) [services] - service json started
2022-02-25T15:31:12.130 INFO (pid:2040480) [services] - gopls state change: starting => running
2022-02-25T15:31:12.132 INFO (pid:2040480) [services] - service go started
2022-02-25T15:31:16.580 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:18.226 INFO (pid:2040480) [attach] - receive notification: codeActionRange [ 20, 20 ]
2022-02-25T15:31:18.688 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:19.692 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:20.036 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:23.897 INFO (pid:2040480) [attach] - receive notification: openList [ 'commands' ]
2022-02-25T15:31:23.985 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:31:29.413 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:31:30.015 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:32.016 INFO (pid:2040480) [attach] - receive notification: doKeymap [ 'aa7e7c30-9632-11ec-b184-3f6173748d29', '', '{esc}' ]
2022-02-25T15:31:32.339 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:32.972 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:33.588 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:31:36.717 INFO (pid:2040480) [attach] - receive notification: openLog []
2022-02-25T15:31:36.801 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:31:37.401 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:38.944 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:41.053 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:41.493 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:42.458 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:42.995 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:43.129 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:31:43.730 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:44.861 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:45.521 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:46.205 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:31:46.806 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:31:59.232 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:32:06.818 INFO (pid:2040480) [attach] - Request action: listNames []
2022-02-25T15:32:07.489 INFO (pid:2040480) [attach] - receive notification: openList [ 'extensions' ]
2022-02-25T15:32:07.615 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:32:11.675 WARN (pid:2040480) [events] - Handler of "InputChar" blocked more than 2s: Error
    at d$.on (/home/sazary/.vim/plugged/coc.nvim/build/index.js:70:2727)
    at GG.init (/home/sazary/.vim/plugged/coc.nvim/build/index.js:239:32315)
    at kx.init (/home/sazary/.vim/plugged/coc.nvim/build/index.js:269:33724)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/sazary/.vim/plugged/coc.nvim/build/index.js:269:36905
2022-02-25T15:32:21.658 WARN (pid:2040480) [events] - Handler of "InputChar" blocked more than 2s: Error
    at d$.on (/home/sazary/.vim/plugged/coc.nvim/build/index.js:70:2727)
    at GG.init (/home/sazary/.vim/plugged/coc.nvim/build/index.js:239:32315)
    at kx.init (/home/sazary/.vim/plugged/coc.nvim/build/index.js:269:33724)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/sazary/.vim/plugged/coc.nvim/build/index.js:269:36905
2022-02-25T15:32:28.611 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:32:29.261 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:32:39.331 INFO (pid:2040480) [attach] - receive notification: openList [ 'commands' ]
2022-02-25T15:32:39.395 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:32:41.740 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:32:43.677 WARN (pid:2040480) [events] - Handler of "InputChar" blocked more than 2s: Error
    at d$.on (/home/sazary/.vim/plugged/coc.nvim/build/index.js:70:2727)
    at GG.init (/home/sazary/.vim/plugged/coc.nvim/build/index.js:239:32315)
    at kx.init (/home/sazary/.vim/plugged/coc.nvim/build/index.js:269:33724)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/sazary/.vim/plugged/coc.nvim/build/index.js:269:36905
2022-02-25T15:32:45.947 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:32:46.549 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:32:47.755 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:32:48.217 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:32:56.092 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:32:56.613 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:32:57.900 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:32:59.470 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:00.677 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:01.899 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:02.769 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:03.788 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:09.158 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:09.693 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:14.987 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:16.648 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:17.629 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:18.087 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:18.526 INFO (pid:2040480) [attach] - receive notification: doAutocmd [
  1,
  {
    regcontents: [ 'module lookup disabled by GOPROXY=off' ],
    visual: false,
    inclusive: true,
    regname: '',
    operator: 'y',
    regtype: 'v'
  },
  33,
  1033
]
2022-02-25T15:33:19.128 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:40.065 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:40.530 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:41.649 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:42.870 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:44.023 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:44.629 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:33:51.095 INFO (pid:2040480) [attach] - receive notification: doAutocmd [
  1,
  {
    regcontents: [ '/home/sazary/.config/coc/extensions/coc-go-data/bin/gopls' ],
    visual: false,
    inclusive: false,
    regname: '',
    operator: 'y',
    regtype: 'v'
  },
  33,
  1033
]
2022-02-25T15:33:51.404 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:06.411 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:08.811 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:10.099 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:11.469 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:11.937 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:34:12.537 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:12.935 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:13.293 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:14.375 INFO (pid:2040480) [completion-complete] - 1 results from: json
2022-02-25T15:34:17.130 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:17.880 INFO (pid:2040480) [attach] - receive notification: doAutocmd [
  1,
  {
    regcontents: [ '        ""' ],
    visual: false,
    inclusive: false,
    regname: '',
    operator: 'd',
    regtype: 'V'
  },
  5,
  1003
]
2022-02-25T15:34:18.721 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:19.595 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:21.211 INFO (pid:2040480) [completion-complete] - 1 results from: json
2022-02-25T15:34:23.085 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:23.174 INFO (pid:2040480) [attach] - receive notification: doAutocmd [
  1,
  {
    regcontents: [ '      "com"', '      "command": "gopls",' ],
    visual: false,
    inclusive: false,
    regname: '',
    operator: 'd',
    regtype: 'V'
  },
  5,
  1003
]
2022-02-25T15:34:24.181 INFO (pid:2040480) [completion-complete] - 1 results from: json
2022-02-25T15:34:32.231 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:34.578 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:35.837 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:37.053 WARN (pid:2040480) [extension:coc-prettier] - jsxBracketSameLine is deprecated.
2022-02-25T15:34:37.589 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:34:38.182 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:34:38.549 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:12.840 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:13.296 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:13.845 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:14.917 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:15.610 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:17.028 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:18.124 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:21.663 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:22.083 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:22.563 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:24.384 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:26.353 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:27.118 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:29.040 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:31.306 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:32.543 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:42.252 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:44.758 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:46.282 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:47.007 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:53.480 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:54.305 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:55.493 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:35:57.378 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:35:59.599 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:36:00.157 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:36:02.529 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:38:42.111 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:38:43.078 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:38:43.871 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:38:44.218 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:38:45.305 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:38:47.857 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:38:48.445 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:38:49.353 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:38:51.622 INFO (pid:2040480) [attach] - receive notification: openList [ 'commands' ]
2022-02-25T15:38:51.720 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:38:55.166 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:38:55.770 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:38:57.648 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:38:58.360 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:39:05.441 INFO (pid:2040480) [attach] - receive notification: doKeymap [ 'b42e1460-9633-11ec-b184-3f6173748d29', '', '{esc}' ]
2022-02-25T15:39:06.159 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:39:58.827 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:40:02.414 INFO (pid:2040480) [attach] - receive notification: doAutocmd [
  1,
  {
    regcontents: [ 'Request textDocument/rename failed.', '' ],
    visual: true,
    inclusive: false,
    regname: '',
    operator: 'y',
    regtype: 'v'
  },
  33,
  1033
]
2022-02-25T15:40:02.792 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:40:30.288 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:40:32.017 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:40:32.373 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:40:32.761 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:40:33.016 INFO (pid:2040480) [attach] - receive notification: doAutocmd [
  1,
  {
    regcontents: [ 'old and new names are the same: Subscriber' ],
    visual: false,
    inclusive: true,
    regname: '',
    operator: 'y',
    regtype: 'v'
  },
  33,
  1033
]
2022-02-25T15:40:33.343 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:40:34.445 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:40:40.567 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:40:40.989 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:40:42.532 INFO (pid:2040480) [attach] - receive notification: doAutocmd [
  1,
  {
    regcontents: [
      '',
      '[Error  - 3:38:55 PM] Request textDocument/rename failed.',
      '  Message: old and new names are the same: Subscriber',
      '  Code: 0 ',
      ''
    ],
    visual: false,
    inclusive: true,
    regname: '',
    operator: 'y',
    regtype: 'V'
  },
  33,
  1033
]
2022-02-25T15:40:42.853 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:41:28.528 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:41:29.129 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:41:32.413 INFO (pid:2040480) [attach] - Request action: commandList [ 'ren', 'CocCommand ren', 14 ]
2022-02-25T15:41:32.838 INFO (pid:2040480) [attach] - Request action: commandList [ 'ren', 'CocCommand ren', 14 ]
2022-02-25T15:41:33.014 INFO (pid:2040480) [attach] - Request action: commandList [ 'ren', 'CocCommand ren', 14 ]
2022-02-25T15:41:33.604 INFO (pid:2040480) [attach] - Request action: commandList [ '', 'CocCommand ', 11 ]
2022-02-25T15:41:45.733 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:41:46.186 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:41:46.350 INFO (pid:2040480) [attach] - receive notification: openList [ 'commands' ]
2022-02-25T15:41:46.447 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:41:48.777 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:41:49.379 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:41:53.128 INFO (pid:2040480) [attach] - Request action: commandList [ 'docu', 'CocCommand docu', 15 ]
2022-02-25T15:41:55.769 INFO (pid:2040480) [attach] - receive notification: runCommand [ 'document.renameCurrentWord' ]
2022-02-25T15:41:56.139 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:41:58.147 INFO (pid:2040480) [attach] - receive notification: doKeymap [ '1fd5e4e0-9634-11ec-b184-3f6173748d29', '', '{esc}' ]
2022-02-25T15:41:58.966 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:42:31.963 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:42:33.229 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:42:34.050 INFO (pid:2040480) [attach] - receive notification: highlight []
2022-02-25T15:42:35.567 INFO (pid:2040480) [attach] - receive notification: doAutocmd [ 2 ]
2022-02-25T15:42:38.645 INFO (pid:2040480) [attach] - receive notification: showInfo []
```

**Comment by sazary** [comment]
that was... fast
