### ISSUE TITLE
Diagnostic shown over code when align right is true

### ISSUE THREAD

**Issue by LoyalPotato** [neoclide/coc.nvim#3707]
## Result from CocInfo

```
 ## versions
      
      vim version: NVIM v0.6.1
      node version: v16.14.0
      coc.nvim version: 0.0.80-ccd0b050e0
      coc.nvim directory: /Users/dbazilio/.vim/plugged/coc.nvim
      term: iTerm.app
      platform: darwin
      
      ## Log of coc.nvim
     
     2022-03-15T22:01:00.959 INFO (pid:27777) [plugin] - coc.nvim initialized with node: v16.14.0 after 96ms
     2022-03-15T22:01:02.453 ERROR (pid:27777) [node-client] - request error on "nvim_call_function" [ 'coc#util#get_editoroption', [ 1004 ] ] Vim(let):E5555: API call: Invalid window id: 1004 Error
         at O1.request (/Users/dbazilio/.vim/plugged/coc.nvim/build/index.js:29:43511)
         at O1.call (/Users/dbazilio/.vim/plugged/coc.nvim/build/index.js:34:3815)
         at oy.createTextEditor (/Users/dbazilio/.vim/plugged/coc.nvim/build/index.js:191:65757)
         at /Users/dbazilio/.vim/plugged/coc.nvim/build/index.js:191:65640
         at /Users/dbazilio/.vim/plugged/coc.nvim/build/index.js:72:3029
         at new Promise (<anonymous>)
         at a (/Users/dbazilio/.vim/plugged/coc.nvim/build/index.js:72:2981)
         at /Users/dbazilio/.vim/plugged/coc.nvim/build/index.js:72:2670
         at Array.map (<anonymous>)
         at yq.fire (/Users/dbazilio/.vim/plugged/coc.nvim/build/index.js:72:2663)
     2022-03-15T22:01:02.454 ERROR (pid:27777) [events] - Error on event: BufWinEnter Error: request error on nvim_call_function - Vim(let):E5555: API call: Invalid window id: 1004
         at oy.createTextEditor (/Users/dbazilio/.vim/plugged/coc.nvim/build/index.js:191:65757)
         at /Users/dbazilio/.vim/plugged/coc.nvim/build/index.js:191:65640
         at /Users/dbazilio/.vim/plugged/coc.nvim/build/index.js:72:3029
         at new Promise (<anonymous>)
         at a (/Users/dbazilio/.vim/plugged/coc.nvim/build/index.js:72:2981)
         at /Users/dbazilio/.vim/plugged/coc.nvim/build/index.js:72:2670
         at Array.map (<anonymous>)
         at yq.fire (/Users/dbazilio/.vim/plugged/coc.nvim/build/index.js:72:2663)
     2022-03-15T22:01:02.523 INFO (pid:27777) [services] - registered service "eslint"
     2022-03-15T22:01:02.526 INFO (pid:27777) [services] - ESLint state change: stopped => starting
     2022-03-15T22:01:02.576 INFO (pid:27777) [services] - registered service "tsserver"
     2022-03-15T22:01:02.637 INFO (pid:27777) [services] - service tsserver started
     2022-03-15T22:01:02.662 INFO (pid:27777) [core-watchman] - watchman watching project: /Users/dbazilio/Documents/Work/lhz-extension
     2022-03-15T22:01:02.775 INFO (pid:27777) [services] - ESLint state change: starting => running
      2022-03-15T22:01:02.782 INFO (pid:27777) [services] - service eslint started
     2022-03-15T22:14:23.810 INFO (pid:27777) [attach] - receive notification: showInfo []
```

## Describe the bug

These are the current configs I have in my coc-settings.json

```json
{
    // Show inline errors
    "diagnostic.virtualText": true,
    "diagnostic.autoRefresh": true,
    "diagnostic.infoSign": "",
    "diagnostic.errorSign": "",
    "diagnostic.hintSign": "",
    "diagnostic.warningSign": "",
    // Trying out configs
    "diagnostic.enableSign": true, 
    "diagnostic.enableHighlightLineNumber": true,
    "diagnostic.messageTarget": "float",
    "diagnostic.virtualTextAlignRight": false,
    "diagnostic.virtualTextCurrentLineOnly": false,
    "diagnostic.messageDelay": 10,
    "codeLens.enable": true,

    // coc-tsserver
    "typescript.check.npmIsInstalled": true,
    "typescript.preferences.quoteStyle": "double",
    "tsserver.disableAutomaticTypeAcquisition": false, // Defaut is false, but just in case. In here because of nvm

    "javascript.preferences.quoteStyle": "double"

    // coc-eslint

}
```
If I have `diagnostic.virtualTextAlignRight` set to true, the diagnostic will overlap with the code and be over it.
You can check the screenshots to see the behaviour with the config changed to true or false.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Copy the configs and make sure `diagnostic.virtualTextAlignRight` is set to true.
- Create file with a big enough error that spans the entire width of the window.
- Error should overlap the code underneath

## Screenshots (optional)

With `diagnostic.virtualTextAlignRight` enabled

<img width="713" alt="image" src="https://user-images.githubusercontent.com/10759876/158479714-5d4d3a21-ace2-4308-b3d5-c0e902dad462.png">

With `diagnostic.virtualTextAlignRight` disabled

<img width="816" alt="image" src="https://user-images.githubusercontent.com/10759876/158479784-33b10120-5009-48a7-a01a-15e2722fde84.png">

**Comment by chemzqm** [comment]
It's removed, not possible to fix since the buffer can have multiple windows and the window coordinate can be changed.
