### ISSUE TITLE
Cannot format document after 8ff0de75ccd95c7c990c113bf1eef07e3dd61603

### ISSUE THREAD

**Issue by xuanduc987** [neoclide/coc.nvim#3742]
## Result from CocInfo

<details>

```
## versions

vim version: NVIM v0.6.1
node version: v14.19.0
coc.nvim version: 0.0.80-1fffa716 2022-04-04 12:52:23 +0800
coc.nvim directory: /Users/<redacted>/.config/vim-jetpack/pack/jetpack/opt/_
term: tmux
platform: darwin

## Log of coc.nvim

2022-04-04T21:49:24.049 INFO (pid:56894) [services] - registered service "languageserver.nix"
2022-04-04T21:49:24.051 INFO (pid:56894) [services] - registered service "languageserver.graphql"
2022-04-04T21:49:24.051 INFO (pid:56894) [services] - registered service "languageserver.efm"
2022-04-04T21:49:24.055 INFO (pid:56894) [services] - efm state change: stopped => starting
2022-04-04T21:49:24.103 INFO (pid:56894) [services] - registered service "tsserver"
2022-04-04T21:49:24.112 INFO (pid:56894) [plugin] - coc.nvim initialized with node: v14.19.0 after 154ms
2022-04-04T21:49:24.149 INFO (pid:56894) [services] - service tsserver started
2022-04-04T21:49:24.158 INFO (pid:56894) [language-client-index] - Language server "languageserver.efm" started with 56899
2022-04-04T21:49:24.174 INFO (pid:56894) [services] - efm state change: starting => running
2022-04-04T21:49:24.176 INFO (pid:56894) [services] - service languageserver.efm started
2022-04-04T21:49:24.500 INFO (pid:56894) [core-watchman] - watchman watching project: /Users/<redacted>/ghq/github.com/<redacted>
2022-04-04T21:49:26.355 INFO (pid:56894) [attach] - receive notification: format []
2022-04-04T21:49:26.956 ERROR (pid:56894) [attach] - Notification error: format [] Error: Overlapping edit
    at AY (/Users/<redacted>/.config/vim-jetpack/pack/jetpack/opt/_/build/index.js:173:283)
    at Ib.applyEdits (/Users/<redacted>/.config/vim-jetpack/pack/jetpack/opt/_/build/index.js:180:2736)
    at Sx.documentFormat (/Users/<redacted>/.config/vim-jetpack/pack/jetpack/opt/_/build/index.js:268:20480)
    at async Sx.formatCurrentBuffer (/Users/<redacted>/.config/vim-jetpack/pack/jetpack/opt/_/build/index.js:268:20006)
    at async $x.cocAction (/Users/<redacted>/.config/vim-jetpack/pack/jetpack/opt/_/build/index.js:286:34311)
    at async iA.<anonymous> (/Users/<redacted>/.config/vim-jetpack/pack/jetpack/opt/_/build/index.js:286:35830)
2022-04-04T21:49:29.307 INFO (pid:56894) [attach] - receive notification: showInfo []
```

</details>

## Describe the bug

Seems like after 8ff0de75ccd95c7c990c113bf1eef07e3dd61603 coc.nvim will reject overlapping edits.

efm-languageserver (https://github.com/mattn/efm-langserver/blob/ce8317fd818e5ec346e612951f7df377025f82a0/langserver/diff.go#L32-L57) and go-lsp (https://github.com/golang/tools/blob/153e30b3c7fa2996154a94565eaedf3fcdf9e514/internal/lsp/diff/myers/diff.go#L19-L36) use myers diff to generate format textedits.

For example
```
aaa
```
->
```
bbb
```

Will generate 2 textedit, one for deleting `aaa` and one for inserting `bbb`, obviously these two are overlapping.

## Reproduce the bug

- using efm-languageserver and call command editor.action.formatDocument
- See errors

**Comment by chemzqm** [comment]
No, they're not overlay

**Comment by chemzqm** [comment]
Hm, they should not work before as well.

**Comment by chemzqm** [comment]
I've tried preview version, same error.
