### ISSUE TITLE
Multiple users sharing coc installation on same machine

### ISSUE THREAD

**Issue by reportaman** [neoclide/coc.nvim#3763]
## Result from CocInfo

```
## versions
``:CocInfo`` run from second user's nvim
vim version: NVIM v0.7.0-dev+1319-gb81c310d4
node version: v17.8.0
coc.nvim version: 0.0.80-3437d1a19d
coc.nvim directory: /Users/amanmehra/.vim/plugged/coc.nvim
term: tmux-256color
platform: darwin

## Log of coc.nvim

2022-04-15T02:44:26.718 ERROR (pid:40554) [extensions] - Error on load /Users/amanmehra/.config/coc/extensions/node_modules/coc-clangd Error: package.json not found
    at Extensions.checkDirectory (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:63250:19)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62879:29
    at new Promise (<anonymous>)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:81
    at Array.map (<anonymous>)
    at Extensions.globalExtensionStats (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:68)
    at Extensions.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62403:32)
    at Plugin.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72690:32)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72881:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-04-15T02:44:26.721 ERROR (pid:40554) [extensions] - Error on load /Users/amanmehra/.config/coc/extensions/node_modules/coc-perl Error: package.json not found
    at Extensions.checkDirectory (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:63250:19)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62879:29
    at new Promise (<anonymous>)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:81
    at Array.map (<anonymous>)
    at Extensions.globalExtensionStats (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:68)
    at Extensions.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62403:32)
    at Plugin.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72690:32)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72881:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-04-15T02:44:26.722 ERROR (pid:40554) [extensions] - Error on load /Users/amanmehra/.config/coc/extensions/node_modules/coc-pyright Error: package.json not found
    at Extensions.checkDirectory (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:63250:19)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62879:29
    at new Promise (<anonymous>)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:81
    at Array.map (<anonymous>)
    at Extensions.globalExtensionStats (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:68)
    at Extensions.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62403:32)
    at Plugin.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72690:32)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72881:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-04-15T02:44:26.722 ERROR (pid:40554) [extensions] - Error on load /Users/amanmehra/.config/coc/extensions/node_modules/coc-rust-analyzer Error: package.json not found
    at Extensions.checkDirectory (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:63250:19)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62879:29
    at new Promise (<anonymous>)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:81
    at Array.map (<anonymous>)
    at Extensions.globalExtensionStats (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:68)
    at Extensions.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62403:32)
    at Plugin.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72690:32)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72881:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-04-15T02:44:26.722 ERROR (pid:40554) [extensions] - Error on load /Users/amanmehra/.config/coc/extensions/node_modules/coc-snippets Error: package.json not found
    at Extensions.checkDirectory (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:63250:19)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62879:29
    at new Promise (<anonymous>)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:81
    at Array.map (<anonymous>)
    at Extensions.globalExtensionStats (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:68)
    at Extensions.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62403:32)
    at Plugin.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72690:32)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72881:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-04-15T02:44:26.722 ERROR (pid:40554) [extensions] - Error on load /Users/amanmehra/.config/coc/extensions/node_modules/coc-solargraph Error: package.json not found
    at Extensions.checkDirectory (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:63250:19)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62879:29
    at new Promise (<anonymous>)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:81
    at Array.map (<anonymous>)
    at Extensions.globalExtensionStats (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:68)
    at Extensions.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62403:32)
    at Plugin.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72690:32)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72881:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-04-15T02:44:26.723 ERROR (pid:40554) [extensions] - Error on load /Users/amanmehra/.config/coc/extensions/node_modules/coc-vimlsp Error: package.json not found
    at Extensions.checkDirectory (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:63250:19)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62879:29
    at new Promise (<anonymous>)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:81
    at Array.map (<anonymous>)
    at Extensions.globalExtensionStats (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:68)
    at Extensions.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62403:32)
    at Plugin.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72690:32)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72881:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-04-15T02:44:26.723 ERROR (pid:40554) [extensions] - Error on load /Users/amanmehra/.config/coc/extensions/node_modules/coc-vimtex Error: package.json not found
    at Extensions.checkDirectory (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:63250:19)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62879:29
    at new Promise (<anonymous>)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:81
    at Array.map (<anonymous>)
    at Extensions.globalExtensionStats (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62875:68)
    at Extensions.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:62403:32)
    at Plugin.init (/Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72690:32)
    at /Users/amanmehra/.vim/plugged/coc.nvim/build/index.js:72881:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-04-15T02:44:26.742 DEBUG (pid:40554) [core-documents] - buffer created 1 true untitled:1
2022-04-15T02:44:26.744 DEBUG (pid:40554) [core-editors] - editor created winid & bufnr & tabnr:  1000 1 1
2022-04-15T02:44:26.758 INFO (pid:40554) [plugin] - coc.nvim initialized with node: v17.8.0 after 41ms
2022-04-15T02:44:34.406 INFO (pid:40554) [attach] - receive notification: showInfo []
```

## Describe the bug

I created a second user account on my Mac laptop. Instead of installing multiple copies of software and maintaining multiple config files, I have symlinked all config files from the second account to point to config files of first account. In case of coc, this is covered by symlink to ~/.config directory.

Everything works well except coc giving these errors when launching nvim from second account:

```
[coc.nvim] Unable to load global extension at /Users/amanmehra/.config/coc/extensions/node_modules/coc-clangd: package.json not found
[coc.nvim] Unable to load global extension at /Users/amanmehra/.config/coc/extensions/node_modules/coc-perl: package.json not found
[coc.nvim] Unable to load global extension at /Users/amanmehra/.config/coc/extensions/node_modules/coc-pyright: package.json not found
[coc.nvim] Unable to load global extension at /Users/amanmehra/.config/coc/extensions/node_modules/coc-rust-analyzer: package.json not found
[coc.nvim] Unable to load global extension at /Users/amanmehra/.config/coc/extensions/node_modules/coc-snippets: package.json not found
[coc.nvim] Unable to load global extension at /Users/amanmehra/.config/coc/extensions/node_modules/coc-solargraph: package.json not found
[coc.nvim] Unable to load global extension at /Users/amanmehra/.config/coc/extensions/node_modules/coc-vimlsp: package.json not found
[coc.nvim] Unable to load global extension at /Users/amanmehra/.config/coc/extensions/node_modules/coc-vimtex: package.json not found
```
 

## Reproduce the bug

1. create a second user on your computer. 
2. login as seconduser 
3. ``cd /Users/seconduser``
4. ``ln -s /Users/firstuser/.config .config`` (coc was installed in first user's directories)
5. Open nvim, run ``:messages`` to see the [coc.nvim] messages.

**Comment by fannheyward** [comment]
macOS's file permission will not allow you to use first user's file as second user.

**Comment by chemzqm** [comment]
Seems you have to fix the permission of files, or use g:coc_data_home variable.

**Comment by reportaman** [comment]
@chemzqm @fannheyward Doing ``chmod -R g+x .`` in first user's ~/.coc/extensions directory made the warnings go away. Not sure if this will produce some functionally incorrectness though. The reason it worked is on macOS every user has the primary group ``staff``.
