### ISSUE TITLE
Can't install coc-sh properly

### ISSUE THREAD

**Issue by EmilySeville7cfg** [neoclide/coc.nvim#3771]
## Environment

Vim: VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 01 2022 09:16:32)
OS: Ubuntu 20.04.4 LTS

## Steps to reproduce

- Create `/home/emilyseville7cfg/.vim/pack/lsp/start` and go to this directory
- Clone plugin repo via `git clone --branch=release https://github.com/neoclide/coc.nvim.git`
- Install NodeJS via `snap install --classic node`
- Do `:CocInstall coc-sh` in Vim
- Obtain: `[coc.nvim] Server sh failed to start: Error: Connection to server got closed. Server will not be restarted.`

## Logs

```log
1   2022-04-21T19:29:14.375 INFO (pid:20462) [services] - registered service "sh"
  1 2022-04-21T19:29:14.378 INFO (pid:20462) [services] - bash-language-server state change: stopped => starting
  2 2022-04-21T19:29:14.379 INFO (pid:20462) [plugin] - coc.nvim initialized with node: v16.14.0 after 120ms
  3 2022-04-21T19:29:14.399 INFO (pid:20462) [language-client-index] - Language server "sh" started with 20500
  4 2022-04-21T19:29:14.483 INFO (pid:20462) [services] - bash-language-server state change: starting => stopped
  5 2022-04-21T19:29:14.484 INFO (pid:20462) [services] - bash-language-server state change: stopped => starting
  6 2022-04-21T19:29:14.492 INFO (pid:20462) [language-client-index] - Language server "sh" started with 20529
  7 2022-04-21T19:29:14.546 INFO (pid:20462) [services] - bash-language-server state change: starting => stopped
  8 2022-04-21T19:29:14.546 INFO (pid:20462) [services] - bash-language-server state change: stopped => starting
  9 2022-04-21T19:29:14.555 INFO (pid:20462) [language-client-index] - Language server "sh" started with 20554
 10 2022-04-21T19:29:14.631 INFO (pid:20462) [services] - bash-language-server state change: starting => stopped
 11 2022-04-21T19:29:14.631 INFO (pid:20462) [services] - bash-language-server state change: stopped => starting
 12 2022-04-21T19:29:14.642 INFO (pid:20462) [language-client-index] - Language server "sh" started with 20584
 13 2022-04-21T19:29:14.733 INFO (pid:20462) [services] - bash-language-server state change: starting => stopped
 14 2022-04-21T19:29:14.734 ERROR (pid:20462) [services] - Server sh failed to start: Error: Connection to server got closed. Server will not be r    estarted.
 15     at Pf.handleConnectionClosed (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:224:1006)
 16     at Pf.handleConnectionClosed (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:224:29270)
 17     at t (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:224:386)
 18     at qA.invoke (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:36:9670)
 19     at kd.fire (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:36:10436)
 20     at Ci (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:37:10897)
 21     at qA.invoke (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:36:9670)
 22     at kd.fire (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:36:10436)
 23     at oT.fireClose (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:36:12716)
 24     at Socket.<anonymous> (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:36:14275)
 25 2022-04-21T19:29:25.008 INFO (pid:20462) [attach] - receive notification: openLog []
```

## Configs

My `~/.vimrc`:

```vim
colorscheme pablo
set number relativenumber
set tabstop=4
set expandtab
```

My `coc-settings.json` is empty.

What am I missing? I want enable a Bash intellisence.

**Comment by fannheyward** [comment]
Make sure you've install `coc-sh` successfully, the extension is installed into `~/.config/coc/extensions/node_modules/coc-sh`,

**Comment by EmilySeville7cfg** [comment]
`[coc.nvim] Server sh failed to start: Error: Connection to server got closed. Server will not be restarted` was shown just after `coc-sh` installation via `:CocInstall coc-sh`

**Comment by fannheyward** [comment]
<img width="449" alt="截屏2022-04-21 16 47 59" src="https://user-images.githubusercontent.com/345274/164417189-6a653d2d-a3f0-4dfd-b5a1-e76e293f44b2.png">

`:CocInstall coc-sh` result, can't reproduce this.

**Comment by EmilySeville7cfg** [comment]
![image](https://user-images.githubusercontent.com/42812113/164423801-0dbec25f-d485-43bf-a592-9328bc83fd17.png)

I also obtain this result, but when I try to run smth like `vim script.sh`:

![image](https://user-images.githubusercontent.com/42812113/164424222-225536b0-ae03-4a07-97c5-fa2506420479.png)

**Comment by fannheyward** [comment]
`:CocOpenLog`.

**Comment by EmilySeville7cfg** [comment]
```log
1   2022-04-21T19:29:14.375 INFO (pid:20462) [services] - registered service "sh"
  1 2022-04-21T19:29:14.378 INFO (pid:20462) [services] - bash-language-server state change: stopped => starting
  2 2022-04-21T19:29:14.379 INFO (pid:20462) [plugin] - coc.nvim initialized with node: v16.14.0 after 120ms
  3 2022-04-21T19:29:14.399 INFO (pid:20462) [language-client-index] - Language server "sh" started with 20500
  4 2022-04-21T19:29:14.483 INFO (pid:20462) [services] - bash-language-server state change: starting => stopped
  5 2022-04-21T19:29:14.484 INFO (pid:20462) [services] - bash-language-server state change: stopped => starting
  6 2022-04-21T19:29:14.492 INFO (pid:20462) [language-client-index] - Language server "sh" started with 20529
  7 2022-04-21T19:29:14.546 INFO (pid:20462) [services] - bash-language-server state change: starting => stopped
  8 2022-04-21T19:29:14.546 INFO (pid:20462) [services] - bash-language-server state change: stopped => starting
  9 2022-04-21T19:29:14.555 INFO (pid:20462) [language-client-index] - Language server "sh" started with 20554
 10 2022-04-21T19:29:14.631 INFO (pid:20462) [services] - bash-language-server state change: starting => stopped
 11 2022-04-21T19:29:14.631 INFO (pid:20462) [services] - bash-language-server state change: stopped => starting
 12 2022-04-21T19:29:14.642 INFO (pid:20462) [language-client-index] - Language server "sh" started with 20584
 13 2022-04-21T19:29:14.733 INFO (pid:20462) [services] - bash-language-server state change: starting => stopped
 14 2022-04-21T19:29:14.734 ERROR (pid:20462) [services] - Server sh failed to start: Error: Connection to server got closed. Server will not be r    estarted.
 15     at Pf.handleConnectionClosed (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:224:1006)
 16     at Pf.handleConnectionClosed (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:224:29270)
 17     at t (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:224:386)
 18     at qA.invoke (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:36:9670)
 19     at kd.fire (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:36:10436)
 20     at Ci (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:37:10897)
 21     at qA.invoke (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:36:9670)
 22     at kd.fire (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:36:10436)
 23     at oT.fireClose (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:36:12716)
 24     at Socket.<anonymous> (/home/emilyseville7cfg/.vim/pack/lsp/start/coc.nvim/build/index.js:36:14275)
 25 2022-04-21T19:29:25.008 INFO (pid:20462) [attach] - receive notification: openLog []
```

**Comment by fannheyward** [comment]
`bash-language-server` can't start for some unknown reasons, can't reproduce this in my env.

**Comment by chemzqm** [comment]
You need check log or debug your language server, nothing else we can do.
