### ISSUE TITLE
[coc.nvim]: UnhandledRejection: Request cancelled because the document was modified

### ISSUE THREAD

**Issue by garsky** [neoclide/coc.nvim#3788]
when i used the pairs plugins {}, this error occured, i could reproduce 100%

[coc.nvim]: UnhandledRejection: Request cancelled because the document was modified
Error: Request cancelled because the document was modified
    at handleResponse (/home/potter/.vim/bundle/coc.nvim/build/index.js:13663:40)
    at processMessageQueue (/home/potter/.vim/bundle/coc.nvim/build/index.js:13501:13)
    at Immediate.<anonymous> (/home/potter/.vim/bundle/coc.nvim/build/index.js:13487:11)
    at processImmediate (internal/timers.js:464:21)

CocInfo:`## versions

vim version: NVIM v0.6.1
node version: v14.17.1
coc.nvim version: 0.0.80-master
coc.nvim directory: /home/potter/.vim/bundle/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2022-04-28T00:18:22.672 INFO (pid:23749) [configurations] - Add folder configuration from cwd: /home/potter/.vim/bundle/coc.nvim/.vim/coc-settings.json
2022-04-28T00:18:22.674 INFO (pid:23749) [configurations] - Change folder configuration from cwd to: /home/potter/.vim/bundle/coc.nvim/.vim/coc-settings.json
2022-04-28T00:18:22.813 WARN (pid:23749) [attach] - Plugin not ready when received "highlight" []
2022-04-28T00:18:23.022 INFO (pid:23749) [services] - registered service "highlight"
2022-04-28T00:18:23.094 INFO (pid:23749) [plugin] - coc.nvim initialized with node: v14.17.1 after 261ms
2022-04-28T00:18:23.108 INFO (pid:23749) [services] - registered service "clangd"
2022-04-28T00:18:23.109 INFO (pid:23749) [services] - clangd state change: stopped => starting
2022-04-28T00:18:23.136 INFO (pid:23749) [language-client-index] - Language server "clangd" started with 23771
2022-04-28T00:18:23.193 INFO (pid:23749) [services] - clangd state change: starting => running
2022-04-28T00:18:23.197 INFO (pid:23749) [services] - service clangd started
2022-04-28T00:18:24.426 INFO (pid:23749) [attach] - receive notification: highlight []
2022-04-28T00:18:24.731 INFO (pid:23749) [attach] - receive notification: highlight []
2022-04-28T00:18:25.954 INFO (pid:23749) [attach] - receive notification: highlight []
2022-04-28T00:18:26.569 INFO (pid:23749) [attach] - receive notification: highlight []
2022-04-28T00:18:28.692 INFO (pid:23749) [attach] - Request action: doKeymap [ 'iKA==0' ]
2022-04-28T00:18:28.720 WARN (pid:23749) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2022-04-28T00:18:30.288 INFO (pid:23749) [attach] - Request action: doKeymap [ 'iKQ==0' ]
2022-04-28T00:18:32.136 INFO (pid:23749) [attach] - Request action: doKeymap [ 'iew==0' ]
2022-04-28T00:18:32.151 WARN (pid:23749) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2022-04-28T00:18:33.103 ERROR (pid:23749) [server] - unhandledRejection  Promise {
  <rejected> ResponseError2: Request cancelled because the document was modified
      at handleResponse (/home/potter/.vim/bundle/coc.nvim/build/index.js:13663:40)
      at processMessageQueue (/home/potter/.vim/bundle/coc.nvim/build/index.js:13501:13)
      at Immediate.<anonymous> (/home/potter/.vim/bundle/coc.nvim/build/index.js:13487:11)
      at processImmediate (internal/timers.js:464:21) {
    code: -32801,
    data: undefined
  }
} ResponseError2: Request cancelled because the document was modified
    at handleResponse (/home/potter/.vim/bundle/coc.nvim/build/index.js:13663:40)
    at processMessageQueue (/home/potter/.vim/bundle/coc.nvim/build/index.js:13501:13)
    at Immediate.<anonymous> (/home/potter/.vim/bundle/coc.nvim/build/index.js:13487:11)
    at processImmediate (internal/timers.js:464:21) {
  code: -32801,
  data: undefined
}
2022-04-28T00:24:13.240 INFO (pid:23749) [attach] - receive notification: highlight []
2022-04-28T00:24:13.517 INFO (pid:23749) [attach] - receive notification: highlight []
2022-04-28T00:24:13.869 ERROR (pid:23749) [server] - unhandledRejection  Promise {
  <rejected> ResponseError2: Request cancelled because the document was modified
      at handleResponse (/home/potter/.vim/bundle/coc.nvim/build/index.js:13663:40)
      at processMessageQueue (/home/potter/.vim/bundle/coc.nvim/build/index.js:13501:13)
      at Immediate.<anonymous> (/home/potter/.vim/bundle/coc.nvim/build/index.js:13487:11)
      at processImmediate (internal/timers.js:464:21) {
    code: -32801,
    data: undefined
  }
} ResponseError2: Request cancelled because the document was modified
    at handleResponse (/home/potter/.vim/bundle/coc.nvim/build/index.js:13663:40)
    at processMessageQueue (/home/potter/.vim/bundle/coc.nvim/build/index.js:13501:13)
    at Immediate.<anonymous> (/home/potter/.vim/bundle/coc.nvim/build/index.js:13487:11)
    at processImmediate (internal/timers.js:464:21) {
  code: -32801,
  data: undefined
}
2022-04-28T00:24:20.977 INFO (pid:23749) [attach] - receive notification: showInfo []

`

**Comment by daquexian** [comment]
I got the same error when editing cpp files

**Comment by chemzqm** [comment]
Please describe how to reproduce

**Comment by garsky** [comment]
> Please describe how to reproduce

1.  install the coc.nvim plugin
below plugins were installed
kien/ctrlp.vim; scrooloose/nerdtree; preservim/nerdcommenter; itchyny/lightline.vim;

2.  yarn build and yarn install
$ yarn install
yarn install v1.22.18
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
$ node esbuild.js
Done in 4.03s.

$ yarn build
yarn run v1.22.18
$ node esbuild.js
Done in 0.26s.

3. all of coc vimscript as below:
let g:coc_global_extensions = [
     \'coc-vimlsp',
     \'coc-clangd',
   \ ]

4. nvim oepn a new c file 
` {
    2     dskfjslj
    3 }
    4 {
    5     skldfjsklj
    6 }
    7
    8 {
    9     sldfjkj
   10 }`

5. touch u to redo, and the error is shown
[coc.nvim]: UnhandledRejection: Request cancelled because the document was modified
Error: Request cancelled because the document was modified
    at handleResponse (/home/potter/.vim/bundle/coc.nvim/build/index.js:13663:40)
    at processMessageQueue (/home/potter/.vim/bundle/coc.nvim/build/index.js:13501:13)
    at Immediate.<anonymous> (/home/potter/.vim/bundle/coc.nvim/build/index.js:13487:11)
    at processImmediate (internal/timers.js:464:21)

**Comment by garsky** [comment]
**Coc plugins as below:**

coc-snippets 
coc-pairs
coc-marketplace
coc-lists
coc-highlight
coc-clangd
coc-vimlsp
coc-tsserver
coc-python
coc-json

**Comment by chemzqm** [comment]
Still not able to reproduce, please provide verbose output of clangd by `:CocCommand workspace.showOutput clangd`

**Comment by chemzqm** [comment]
Caused by inlay hints request from https://github.com/clangd/coc-clangd/blob/master/src/inlay-hints.ts#L176
it should handle error by `client.handleFailedRequest` https://github.com/neoclide/coc.nvim/blob/master/src/language-client/client.ts#L4399 to avoid such error.

**Comment by fannheyward** [comment]
Try coc-clangd v0.21.4.

**Comment by garsky** [comment]
> Try coc-clangd v0.21.4.

thanks, issue resolved by latest plugins
