### ISSUE TITLE
[coc.nvim] The "sh" (or language-server-bash) crashed 4 times in the last 3 minutes. Reinstall of language server + coc.nvim does not fix

### ISSUE THREAD

**Issue by isak102** [neoclide/coc.nvim#3800]
## Result from CocInfo

```
vim version: NVIM v0.7.0                                                                                
node version: v18.1.0                                                                                  
coc.nvim version: 0.0.80-3a26df0a 2022-05-04 04:30:27 +0800                                             
coc.nvim directory: /home/isak102/.local/share/nvim/plugged/coc.nvim                                    
term: alacritty                                                                                        
platform: linux   
```

## Describe the bug

All bash language servers crash upon launching a .sh file in nvim. I have uninstalled coc multiple times, I have tried both bash-language-server and coc-sh and uninstalled and reinstalled them all a bunch of times and it doesnt work. After around 3 seconds of opening a .sh file I get the error message `[coc.nvim] The "sh" server crashed 4 times in the last 3 minutes. The server will not be restarted`. The other language servers work fine for example python and C, but no bash language server seem to work properly. 

This is the output of CocOpenLog:
```
2022-05-05T23:25:55.374 INFO (pid:567005) [services] - registered service "sh"
2022-05-05T23:25:55.386 INFO (pid:567005) [services] - bash-language-server state change: stopped => starting
2022-05-05T23:25:55.389 INFO (pid:567005) [plugin] - coc.nvim initialized with node: v18.1.0 after 79ms
2022-05-05T23:25:55.396 INFO (pid:567005) [language-client-index] - Language server "sh" started with 567017
2022-05-05T23:25:55.815 INFO (pid:567005) [services] - bash-language-server state change: starting => stopped
2022-05-05T23:25:55.816 INFO (pid:567005) [services] - bash-language-server state change: stopped => starting
2022-05-05T23:25:55.822 INFO (pid:567005) [language-client-index] - Language server "sh" started with 567047
2022-05-05T23:25:56.262 INFO (pid:567005) [services] - bash-language-server state change: starting => stopped
2022-05-05T23:25:56.262 INFO (pid:567005) [services] - bash-language-server state change: stopped => starting
2022-05-05T23:25:56.268 INFO (pid:567005) [language-client-index] - Language server "sh" started with 567054
2022-05-05T23:25:56.677 INFO (pid:567005) [services] - bash-language-server state change: starting => stopped
2022-05-05T23:25:56.678 INFO (pid:567005) [services] - bash-language-server state change: stopped => starting
2022-05-05T23:25:56.684 INFO (pid:567005) [language-client-index] - Language server "sh" started with 567065
2022-05-05T23:25:57.095 INFO (pid:567005) [services] - bash-language-server state change: starting => stopped
2022-05-05T23:25:57.096 ERROR (pid:567005) [services] - Server sh failed to start: Error: Connection to server got closed. Server will not be restarted.
    at jf.handleConnectionClosed (/home/isak102/.local/share/nvim/plugged/coc.nvim/build/index.js:224:1006)
    at jf.handleConnectionClosed (/home/isak102/.local/share/nvim/plugged/coc.nvim/build/index.js:224:29178)
    at t (/home/isak102/.local/share/nvim/plugged/coc.nvim/build/index.js:224:386)
    at tN.invoke (/home/isak102/.local/share/nvim/plugged/coc.nvim/build/index.js:36:9670)
    at Id.fire (/home/isak102/.local/share/nvim/plugged/coc.nvim/build/index.js:36:10436)
    at Ci (/home/isak102/.local/share/nvim/plugged/coc.nvim/build/index.js:37:10897)
    at tN.invoke (/home/isak102/.local/share/nvim/plugged/coc.nvim/build/index.js:36:9670)
    at Id.fire (/home/isak102/.local/share/nvim/plugged/coc.nvim/build/index.js:36:10436)
    at yT.fireClose (/home/isak102/.local/share/nvim/plugged/coc.nvim/build/index.js:36:12716)
    at Socket.<anonymous> (/home/isak102/.local/share/nvim/plugged/coc.nvim/build/index.js:36:14275)
2022-05-05T23:27:44.945 INFO (pid:567005) [attach] - receive notification: openLog []
```
This is the output of `CocCommand workspaces`
```
[Warn  - 11:28:30 PM] Ignored rootPath /home/isak102 of client "sh"
[Warn  - 11:28:30 PM] No valid workspaceFolder exists
node:internal/deps/undici/undici:4816
            throw new TypeError("Failed to parse URL from " + input, { cause: err });
                  ^

TypeError: Failed to parse URL from /home/isak102/.config/coc/extensions/node_modules/coc-sh/node_modules/web-tree-sitter/tree-sitter.wasm
    at new Request (node:internal/deps/undici/undici:4816:19)
    at Agent2.fetch2 (node:internal/deps/undici/undici:5544:29)
    ... 4 lines matching cause stack trace ...
    at /home/isak102/.config/coc/extensions/node_modules/coc-sh/node_modules/web-tree-sitter/tree-sitter.js:1:144
    at Object.<anonymous> (/home/isak102/.config/coc/extensions/node_modules/coc-sh/node_modules/web-tree-sitter/tree-sitter.js:1:170)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:377:5)
      at URL.onParseError (node:internal/url:563:9)
      at new URL (node:internal/url:643:5)
      at new Request (node:internal/deps/undici/undici:4814:25)
      at Agent2.fetch2 (node:internal/deps/undici/undici:5544:29)
      at Object.fetch (node:internal/deps/undici/undici:6372:20)
      at fetch (node:internal/bootstrap/pre_execution:199:25)
      at /home/isak102/.config/coc/extensions/node_modules/coc-sh/node_modules/web-tree-sitter/tree-sitter.js:1:15041
      at /home/isak102/.config/coc/extensions/node_modules/coc-sh/node_modules/web-tree-sitter/tree-sitter.js:1:15262
      at /home/isak102/.config/coc/extensions/node_modules/coc-sh/node_modules/web-tree-sitter/tree-sitter.js:1:144 {
    input: '/home/isak102/.config/coc/extensions/node_modules/coc-sh/node_modules/web-tree-sitter/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}
```

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim test.sh -u mini.vim`

- Operate vim. The bash language server crashes after around 3 seconds of use

**Comment by chemzqm** [comment]
Should be issue with your vic-sh

**Comment by isak102** [comment]
> Should be issue with your coc-sh and language server You have to debug language server for exact reason

I find it weird that it happens on both coc-sh and bash-language-server.. Could you give me a hint of what is the problem? I am completely lost on how to fix this..

The output of `:CocCommand workspace.showOuptut` looks like this:
```
node:internal/deps/undici/undici:4816
            throw new TypeError("Failed to parse URL from " + input, { cause: err });
                  ^

TypeError: Failed to parse URL from /usr/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.wasm
    at new Request (node:internal/deps/undici/undici:4816:19)
    at Agent2.fetch2 (node:internal/deps/undici/undici:5544:29)
    ... 4 lines matching cause stack trace ...
    at /usr/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:144
    at Object.<anonymous> (/usr/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:170)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:377:5)
      at URL.onParseError (node:internal/url:563:9)
      at new URL (node:internal/url:643:5)
      at new Request (node:internal/deps/undici/undici:4814:25)
      at Agent2.fetch2 (node:internal/deps/undici/undici:5544:29)
      at Object.fetch (node:internal/deps/undici/undici:6372:20)
      at fetch (node:internal/bootstrap/pre_execution:199:25)
      at /usr/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:15041
      at /usr/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:15262
      at /usr/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.js:1:144 {
    input: '/usr/lib/node_modules/bash-language-server/node_modules/web-tree-sitter/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}
```

**Comment by chemzqm** [comment]
I don't know, it's error from your bash-language-server
