### ISSUE TITLE
[coc.nvim] Server languageserver.ccls failed to start: Error: invalid params of initialize: expected array for /worksp aceFolders

### ISSUE THREAD

**Issue by xiaobaiseven** [neoclide/coc.nvim#3805]
Probably a bug in nodejs 18.1 then. There was an error writing .c file when i upgraded nodejs-18.1.0. This is the output of :CocInfo:

## versions

vim version: NVIM v0.7.0
node version: v18.1.0
coc.nvim version: 0.0.80-e529cd8c 2022-05-07 21:04:20 +0800
coc.nvim directory: /home/dora/.config/nvim/plugged/coc.nvim
term: st-256color
platform: linux

## Log of coc.nvim

2022-05-08T02:40:41.191 INFO (pid:10571) [services] - registered service "languageserver.lua"
2022-05-08T02:40:41.192 INFO (pid:10571) [services] - registered service "languageserver.swift"
2022-05-08T02:40:41.192 INFO (pid:10571) [services] - registered service "languageserver.golang"
2022-05-08T02:40:41.192 INFO (pid:10571) [services] - registered service "languageserver.bash"
2022-05-08T02:40:41.192 INFO (pid:10571) [services] - registered service "languageserver.racket"
2022-05-08T02:40:41.192 INFO (pid:10571) [services] - registered service "languageserver.ccls"
2022-05-08T02:40:41.204 INFO (pid:10571) [services] - ccls state change: stopped => starting
2022-05-08T02:40:41.213 WARN (pid:10571) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead.
    at new t.Actions (/home/dora/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:8301)
    at t.activate (/home/dora/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:15288)
2022-05-08T02:40:41.224 INFO (pid:10571) [services] - registered service "diagnostic-languageserver"
2022-05-08T02:40:41.421 INFO (pid:10571) [plugin] - coc.nvim initialized with node: v18.1.0 after 299ms
2022-05-08T02:40:41.431 INFO (pid:10571) [language-client-index] - Language server "languageserver.ccls" started with
10586
2022-05-08T02:40:41.444 INFO (pid:10571) [attach] - receive notification: highlight []
2022-05-08T02:40:41.450 INFO (pid:10571) [services] - ccls state change: starting => stopped
2022-05-08T02:40:41.450 ERROR (pid:10571) [services] - Server languageserver.ccls failed to start: Em [Error]: invalid params of initialize: expected array for /workspaceFolders
    at ou (/home/dora/.config/nvim/plugged/coc.nvim/build/index.js:38:224)
    at ap (/home/dora/.config/nvim/plugged/coc.nvim/build/index.js:37:11261)
    at Immediate.<anonymous> (/home/dora/.config/nvim/plugged/coc.nvim/build/index.js:37:11111)
    at process.processImmediate (node:internal/timers:471:21) {
  code: -32602,
  data: undefined
}
2022-05-08T02:40:55.140 INFO (pid:10571) [attach] - receive notification: showInfo []

**Comment by chemzqm** [comment]
Upgrade your ccls
