### ISSUE TITLE
"await client.stop()" outputs an error.

### ISSUE THREAD

**Issue by yaegassy** [neoclide/coc.nvim#3812]
## Result from CocInfo

```
vim version: NVIM v0.8.0-dev+159-gf6be28c61
node version: v16.14.2
coc.nvim version: 0.0.80-5cf5117 2022-05-10 18:54:25 +0800
coc.nvim directory: /Users/yaegassy/.local/share/nvim/plugged/coc.nvim
term: tmux
platform: darwin
```

## Describe the bug

`await client.stop()` outputs an error.

```
[coc.nvim]: UnhandledRejection: write after end
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (node:internal/errors:371:5)
    at _write (node:internal/streams/writable:319:11)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at /Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:11928:25
    at new Promise (<anonymous>)
    at WritableStreamWrapper.write (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:11919:16)
    at StreamMessageWriter2.doWrite (/Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12829:31)
    at /Users/yaegassy/.local/share/nvim/plugged/coc.nvim/build/index.js:12820:25
```

## Reproduce the bug

There is an extension called `coc-pylsp` (`@yaegassy/coc-pylsp`). <https://github.com/yaegassy/coc-pylsp>

Someone wanted to use `python-lsp-server` (pylsp) with coc.nvim, but was having trouble because there is no dedicated extension for it. So I prepared this extension.

There is a command prepared by `commands.registerCommand`. I was getting an error in this one. <https://github.com/yaegassy/coc-pylsp/blob/master/src/index.ts#L97>

## Screenshots (optional)

<img width="915" alt="coc-client-stop-error" src="https://user-images.githubusercontent.com/188642/167748300-8834a9a7-4c5f-47a2-bea3-4d7be625b5dd.png">

**Comment by fannheyward** [comment]
Reproduced with coc-rust-analyzer to stop LS.

**Comment by chemzqm** [comment]
Don't know how to catch that error, it's caused by https://github.com/neoclide/coc.nvim/blob/5cf5117b9fbbd32d4e4bab2116c36685fee0d881/src/language-client/client.ts#L3869

**Comment by fannheyward** [comment]
> connection.end()

The first time I came this error was working with LSP 3.16 https://github.com/neoclide/coc.nvim/pull/2756#issuecomment-753887861

The `end()` was added in vscode-language-node from 3.16, when I added this, it caused the crash. From LSP https://microsoft.github.io//language-server-protocol/specifications/lsp/3.17/specification/#shutdown, the client only needs to do `shutdown` - `exit`, so I removed the `end()` in 3.16 PR.

**Comment by yaegassy** [comment]
There is also a command in `coc-volar` to restart LS using `client.stop()`, but no error seems to occur there. <https://github.com/yaegassy/coc-volar/blob/master/src/common.ts#L165-L169>

Other than that, I have not checked this in depth, but maybe it is not a problem with Node.js LS...
