### ISSUE TITLE
Scratch/Unlisted Buffer Exception w/ vim-ccls & vim-lsp-cxx-highlight 

### ISSUE THREAD

**Issue by hexdd** [neoclide/coc.nvim#3818]
## Bug Description

I'm using the `ccls` language server with some additional plugins:`vim-ccls` and `vim-lsp-cxx-highlight`.  When I have both of these plugins installed I get these exceptions stacks popping up when I issue a `:CclsCallHierarchy`, then an `o` (bound to `yggdrasil-toggle-node`) to open the call hierarchy against a function symbol:

```
[coc.nvim]: UnhandledRejection: request error nvim_call_function - buffer does not exist!
Error
    at NeovimClient2.request (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:10144:21)
    at NeovimClient2.call (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:11361:21)
    at /home/davez/.config/nvim/plugged/coc.nvim/build/index.js:53476:40
    at handleNotification (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13926:17)
    at processMessageQueue (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13700:13)
    at Immediate._onImmediate (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13688:11)
    at processImmediate (internal/timers.js:464:21)
UnhandledRejection: request error nvim_call_function - buffer does not exist!
```

 This doesn't result in an exception until I have `vim-lsp-cxx-highlight` in play.  But there's some evidence in the log for `ccls` (see below) that it's stemming from `vim-ccls` use of a "Scratch", unlisted (??), buffer .  I'm just using my imagination here, but I think somehow this buffer is being  passed into `ccls` for parsing, even though it's not the correct buffer type per the `filetypes` list in `coc-settings.json`.

## :CocCommand document.echoFiletype for this vim-ccls viewport

This split created by `:CclsCallHierarchy` reports from `:CocCommand document.echoFiletype` as:  `yggdrasil`, not any of the `filetypes` have in `coc-settings.json`. 

## coc-settings.json

I *think* that this must have something to do with requests somehow getting past the filter in `coc.settings`

```
{
  "list.maxPreviewHeight" : 30,
  "languageserver": {
    "ccls": {
      "command": "ccls",
      "args": ["--log-file=/tmp/ccls.log", "-v=1"],
      "filetypes": ["c", "cc", "cpp", "c++", "objc", "objcpp"],
      "trace.server": "verbose",
      "rootPatterns": [".ccls", "compile_commands.json"],
      "initializationOptions": {
         "cache": {
           "directory": "/tmp/ccls"
         },
         "client": {
          "snippetSupport": true
         },
         "highlight": {
           "lsRanges": true
         },
         "clang": {
           "excludeArgs": [
             "-mabi=lp64"
           ]
         }
      }
    },
    "bash": {
      "command": "bash-language-server",
      "args": ["start"],
      "filetypes": ["sh"],
      "ignoredRootPaths": ["~"]
    }
  }
}
```

## Result from ccls.log

With or without `vim-lsp-cxx-highlight`, these messages still appear in the `ccls` log, with the highlight plugin it results in the exception:

```
00:50:06 indexer2         pipeline.cc:298 I load cache for /home/davez/src/busybox-1.31.1-dunfell/util-linux/taskset.c
00:50:06 indexer5         pipeline.cc:298 I load cache for /home/davez/src/busybox-1.31.1-dunfell/networking/nslookup.c
00:50:06 indexer15        pipeline.cc:298 I load cache for /home/davez/src/busybox-1.31.1-dunfell/networking/tls_aes.c
00:50:06 indexer6         pipeline.cc:298 I load cache for /home/davez/src/busybox-1.31.1-dunfell/loginutils/deluser.c
00:50:06 ccls             pipeline.cc:493 I loaded project. Refresh semantic highlight for all working file.
00:50:21 ccls                  lsp.cc:93  W Received potentially bad URI (not starting with file://): untitled:2
00:50:21 ccls                  lsp.cc:93  W Received potentially bad URI (not starting with file://): untitled:2
00:50:21 indexer0         pipeline.cc:386 I delete untitled:2
  clang untitled:2 -working-directory=/home/davez/src/busybox-1.31.1-dunfell/
00:50:21 preamble     sema_manager.cc:770 I create session for untitled:2
  clang untitled:2 -working-directory=/home/davez/src/busybox-1.31.1-dunfell/
00:50:21 ccls                  lsp.cc:93  W Received potentially bad URI (not starting with file://): untitled:2
```

## Full :CocOpenLog Result

```
undefined## versions

vim version: NVIM v0.6.1
node version: v14.19.2
coc.nvim version: 0.0.80-3e27015cfb
coc.nvim directory: /home/davez/.config/nvim/plugged/coc.nvim
term: tmux
platform: linux

2022-05-14T00:23:11.653 WARN (pid:443636) [attach] - Plugin not ready when received "registNotification" [ 'cquery', '$cquery/publishSemanticHighlighting' ]
2022-05-14T00:23:11.657 WARN (pid:443636) [attach] - Plugin not ready when received "registNotification" [ 'cquery', '$cquery/setInactiveRegions' ]
2022-05-14T00:23:11.657 WARN (pid:443636) [attach] - Plugin not ready when received "registNotification" [ 'ccls', '$ccls/publishSemanticHighlight' ]
2022-05-14T00:23:11.657 WARN (pid:443636) [attach] - Plugin not ready when received "registNotification" [ 'ccls', '$ccls/publishSkippedRanges' ]
2022-05-14T00:23:11.766 INFO (pid:443636) [services] - registered service "languageserver.ccls"
2022-05-14T00:23:11.770 INFO (pid:443636) [services] - ccls state change: stopped => starting
2022-05-14T00:23:11.770 INFO (pid:443636) [services] - registered service "languageserver.bash"
2022-05-14T00:23:11.772 INFO (pid:443636) [plugin] - coc.nvim 0.0.80-3e27015cfb initialized with node: v14.19.2 after 107ms
2022-05-14T00:23:11.777 INFO (pid:443636) [language-client-index] - Language server "languageserver.ccls" started with 443647
2022-05-14T00:23:11.791 INFO (pid:443636) [attach] - receive notification: registNotification [ 'cquery', '$cquery/publishSemanticHighlighting' ]
2022-05-14T00:23:11.791 INFO (pid:443636) [attach] - receive notification: registNotification [ 'cquery', '$cquery/setInactiveRegions' ]
2022-05-14T00:23:11.791 INFO (pid:443636) [attach] - receive notification: registNotification [ 'ccls', '$ccls/publishSemanticHighlight' ]
2022-05-14T00:23:11.791 INFO (pid:443636) [attach] - receive notification: registNotification [ 'ccls', '$ccls/publishSkippedRanges' ]
2022-05-14T00:23:11.808 INFO (pid:443636) [services] - ccls state change: starting => running
2022-05-14T00:23:11.818 INFO (pid:443636) [services] - service languageserver.ccls started
2022-05-14T00:23:19.338 INFO (pid:443636) [attach] - Request action: sendRequest [
  'ccls',
  '$ccls/call',
  {
    levels: 1,
    callee: false,
    hierarchy: true,
    textDocument: {
      uri: 'file:///home/davez/src/busybox-1.31.1-dunfell/networking/ifupdown.c'
    },
    position: { character: 18, line: 399 }
  }
]
2022-05-14T00:23:20.996 INFO (pid:443636) [attach] - Request action: sendRequest [
  'ccls',
  '$ccls/call',
  {
    id: '16917244761161301233',
    levels: 1,
    callee: false,
    hierarchy: true
  }
]
2022-05-14T00:23:21.020 ERROR (pid:443636) [node-client] - request error on "nvim_call_function" [
  'coc#do_notify',
  [
    'ccls',
    '$ccls/publishSkippedRanges',
    { uri: 'file://untitled:2', skippedRanges: [] }
  ]
] buffer does not exist! Error
    at NeovimClient2.request (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:10144:21)
    at NeovimClient2.call (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:11361:21)
    at /home/davez/.config/nvim/plugged/coc.nvim/build/index.js:53476:40
    at handleNotification (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13926:17)
    at processMessageQueue (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13700:13)
    at Immediate._onImmediate (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13688:11)
    at processImmediate (internal/timers.js:464:21)
2022-05-14T00:23:21.021 ERROR (pid:443636) [server] - unhandledRejection  Promise {
  <rejected> Error
      at NeovimClient2.request (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:10144:21)
      at NeovimClient2.call (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:11361:21)
      at /home/davez/.config/nvim/plugged/coc.nvim/build/index.js:53476:40
      at handleNotification (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13926:17)
      at processMessageQueue (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13700:13)
      at Immediate._onImmediate (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13688:11)
      at processImmediate (internal/timers.js:464:21)
} Error
    at NeovimClient2.request (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:10144:21)
    at NeovimClient2.call (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:11361:21)
    at /home/davez/.config/nvim/plugged/coc.nvim/build/index.js:53476:40
    at handleNotification (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13926:17)
    at processMessageQueue (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13700:13)
    at Immediate._onImmediate (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13688:11)
    at processImmediate (internal/timers.js:464:21)
2022-05-14T00:23:21.022 ERROR (pid:443636) [node-client] - request error on "nvim_call_function" [
  'coc#do_notify',
  [
    'ccls',
    '$ccls/publishSemanticHighlight',
    { uri: 'file://untitled:2', symbols: [] }
  ]
] buffer does not exist! Error
    at NeovimClient2.request (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:10144:21)
    at NeovimClient2.call (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:11361:21)
    at /home/davez/.config/nvim/plugged/coc.nvim/build/index.js:53476:40
    at handleNotification (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13926:17)
    at processMessageQueue (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13700:13)
    at Immediate._onImmediate (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13688:11)
    at processImmediate (internal/timers.js:464:21)
2022-05-14T00:23:21.022 ERROR (pid:443636) [server] - unhandledRejection  Promise {
  <rejected> Error
      at NeovimClient2.request (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:10144:21)
      at NeovimClient2.call (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:11361:21)
      at /home/davez/.config/nvim/plugged/coc.nvim/build/index.js:53476:40
      at handleNotification (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13926:17)
      at processMessageQueue (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13700:13)
      at Immediate._onImmediate (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13688:11)
      at processImmediate (internal/timers.js:464:21)
} Error
    at NeovimClient2.request (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:10144:21)
    at NeovimClient2.call (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:11361:21)
    at /home/davez/.config/nvim/plugged/coc.nvim/build/index.js:53476:40
    at handleNotification (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13926:17)
    at processMessageQueue (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13700:13)
    at Immediate._onImmediate (/home/davez/.config/nvim/plugged/coc.nvim/build/index.js:13688:11)
    at processImmediate (internal/timers.js:464:21)
2022-05-14T00:23:41.270 INFO (pid:443636) [attach] - receive notification: showInfo []
2022-05-14T00:23:58.287 INFO (pid:443636) [attach] - receive notification: showInfo []

```

## Reproduce the bug

This assumes you have the aforementioned plugins installed. I already had them in available with `vim-plug`.  At that point you can use a minimal `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/home/davez/.config/nvim/plugged/coc.nvim,/home/davez/.config/nvim/plugged/vim-ccls,/home/davez/.config/nvim/plugged/vim-lsp-cxx-highlight
  " set runtimepath^=/home/davez/.config/nvim/plugged/coc.nvim,/home/davez/.config/nvim/plugged/vim-ccls
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

- Do a `:CclsCallHierarchy` agains any c function

- While the cursor is on a symbol with a triangle, hit `o` to expand it... exception occurs. 

## Error Report to vim-lsp-cxx-highlight

This issue was reported to `vim-lsp-cxx-highlight` project, but because there are multiple plugins involved I'm not sure which is the culprit.  But I suspect it's stemming from `coc.nvim`. Here's that ticket for reference:

https://github.com/jackguo380/vim-lsp-cxx-highlight/issues/48

**Comment by chemzqm** [comment]
Some of your vim plugin can't handle `uri: 'file://untitled:2'` for untitled buffer, it should be fixed.
