### ISSUE TITLE
TypeError issue with Flutter

### ISSUE THREAD

**Issue by andromedabushturkey** [neoclide/coc.nvim#3820]
I've been having this issue where I can just type in the word 'const' in my code in nvim and this error appears. 

> Complete error: flutter TypeError: Cannot read properties of null (reading 'isIncomplete')

here is the output of :CocInfo

> 2022-05-15T21:08:08.496 INFO (pid:70669) [plugin] - coc.nvim initialized with node: v16.15.0 after 146ms
2022-05-15T21:08:10.598 INFO (pid:70669) [services] - registered service "flutter"
2022-05-15T21:08:10.599 INFO (pid:70669) [services] - flutter analysis server state change: stopped => starting
2022-05-15T21:08:10.605 INFO (pid:70669) [language-client-index] - Language server "flutter" started with 70688
2022-05-15T21:08:10.844 INFO (pid:70669) [services] - flutter analysis server state change: starting => running
2022-05-15T21:08:10.845 INFO (pid:70669) [services] - service flutter started
2022-05-15T21:08:10.974 INFO (pid:70669) [attach] - receive notification: doAutocmd [ 1 ]
2022-05-15T21:08:29.551 ERROR (pid:70669) [node-client] - TypeError: Cannot read properties of null (reading 'isIncomplete') Error
    at SA.echoError (/home/user1/.config/nvim/plugged/coc.nvim/build/index.js:35:1869)
    at Tx.completeSource (/home/user1/.config/nvim/plugged/coc.nvim/build/index.js:266:32983)
    at async Promise.all (index 0)
    at async Tx.completeSources (/home/user1/.config/nvim/plugged/coc.nvim/build/index.js:266:31773)
    at async Tx.completeInComplete (/home/user1/.config/nvim/plugged/coc.nvim/build/index.js:266:33491)
    at async Tx.filterResults (/home/user1/.config/nvim/plugged/coc.nvim/build/index.js:266:35126)
    at async Zee.filterResults (/home/user1/.config/nvim/plugged/coc.nvim/build/index.js:266:50091)
    at async /home/user1/.config/nvim/plugged/coc.nvim/build/index.js:266:42903
2022-05-15T21:08:29.551 ERROR (pid:70669) [completion-complete] - Complete error: flutter TypeError: Cannot read properties of null (reading 'isIncomplete')
    at Object.wp [as provideCompletionItem] (/home/user1/.config/coc/extensions/node_modules/coc-flutter/out/index.js:45:522)
    at async ox.doComplete (/home/user1/.config/nvim/plugged/coc.nvim/build/index.js:262:9848)
2022-05-15T21:08:30.580 WARN (pid:70669) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2022-05-15T21:08:33.132 ERROR (pid:70669) [node-client] - TypeError: Cannot read properties of null (reading 'isIncomplete') Error
    at SA.echoError (/home/user1/.config/nvim/plugged/coc.nvim/build/index.js:35:1869)
    at Tx.completeSource (/home/user1/.config/nvim/plugged/coc.nvim/build/index.js:266:32983)
    at async Promise.all (index 0)
    at async Tx.completeSources (/home/user1/.config/nvim/plugged/coc.nvim/build/index.js:266:31773)
    at async Tx.completeInComplete (/home/user1/.config/nvim/plugged/coc.nvim/build/index.js:266:33491)
    at async Tx.filterResults (/home/user1/.config/nvim/plugged/coc.nvim/build/index.js:266:35126)
    at async Zee.filterResults (/home/user1/.config/nvim/plugged/coc.nvim/build/index.js:266:50091)
    at async Zee.onTextChangedP (/home/user1/.config/nvim/plugged/coc.nvim/build/index.js:266:44401)
2022-05-15T21:08:33.133 ERROR (pid:70669) [completion-complete] - Complete error: flutter TypeError: Cannot read properties of null (reading 'isIncomplete')
    at Object.wp [as provideCompletionItem] (/home/user1/.config/coc/extensions/node_modules/coc-flutter/out/index.js:45:522)
    at async ox.doComplete (/home/user1/.config/nvim/plugged/coc.nvim/build/index.js:262:9848)

I don't really know where to start. Any ideas?

Cheers!!

**Comment by fannheyward** [comment]
It's `coc-flutter`'s issue, cc @iamcco.

**Comment by IndexXuan** [comment]
https://github.com/iamcco/coc-flutter/pull/154

**Comment by andromedabushturkey** [comment]
Indeed this is the wrong place. Don't know why I posted this here. Sorry about that and thank you.

Have a good week. Cheers.
