### ISSUE TITLE
[coc.nvim] TypeError: t.words is not iterable

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc.nvim#3821]
## Describe the bug

```
[coc.nvim] TypeError: t.words is not iterable
[coc.nvim] TypeError: e.words is not iterable
```

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim
" $ uname -r
" 5.16.15-arch1-1
" $ has nvim
" ✔ nvim 0.6.1
" $ has python
" ✔ python 3.10.2
" $ cat test.vim
set runtimepath=$VIMRUNTIME
set runtimepath+=~/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release
set runtimepath+=~/.local/share/nvim/repos/github.com/honza/vim-snippets
let g:coc_snippet_next = '<Tab>'
let g:coc_snippet_prev = '<S-Tab>'
let g:coc_config_home = '.'
inoremap <silent> <TAB> <C-R>=coc#rpc#request('doKeymap', ['snippets-expand-jump', ''])<CR>
" $ cat coc-settings.json
" $ vi -u test.vim test.vim +9
```

- Operate vim, such as `fvfvsv`

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/32936898/168514493-f67225e4-3eb8-4310-b0cf-a44a6f42a6b3.png)

**Comment by fannheyward** [comment]
What's the output of `:CocInfo` and `:CocOpenLog`?

**Comment by Freed-Wu** [comment]
```
:CocInfo
## versions

vim version: NVIM v0.7.0
node version: v18.1.0
coc.nvim version: 0.0.80-949dfbfa 2022-05-15 16:13:13 +0800
coc.nvim directory: /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release
term: tmux
platform: linux

## Log of coc.nvim

2022-05-16T11:44:29.384 INFO (pid:2373811) [coc-git] - Looking for git in: git
2022-05-16T11:44:29.398 INFO (pid:2373811) [services] - registered service "highlight"
2022-05-16T11:44:29.559 INFO (pid:2373811) [coc-tabnine] - Using tabnine from /home/wzy/.config/coc/extensions/coc-tabnine-data/binaries/4.4.8/x86_64-unknown-linux-musl/TabNine
2022-05-16T11:44:29.683 INFO (pid:2373811) [plugin] - coc.nvim initialized with node: v18.1.0 after 769ms
2022-05-16T11:44:29.687 WARN (pid:2373811) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead.
    at t.initStatusBar (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:155873)
    at t.activate (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23099)
2022-05-16T11:44:41.685 INFO (pid:2373811) [attach] - receive notification: showInfo []
:CocOpenLog
2022-05-16T11:44:29.384 INFO (pid:2373811) [coc-git] - Looking for git in: git
2022-05-16T11:44:29.398 INFO (pid:2373811) [services] - registered service "highlight"
2022-05-16T11:44:29.559 INFO (pid:2373811) [coc-tabnine] - Using tabnine from /home/wzy/.config/coc/extensions/coc-tabnine-data/binaries/4.4.8/x86_64-unknown-linux-musl/TabNine
2022-05-16T11:44:29.683 INFO (pid:2373811) [plugin] - coc.nvim initialized with node: v18.1.0 after 769ms
2022-05-16T11:44:29.687 WARN (pid:2373811) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead.
    at t.initStatusBar (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:155873)
    at t.activate (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23099)
2022-05-16T11:44:41.685 INFO (pid:2373811) [attach] - receive notification: showInfo []
2022-05-16T11:44:41.688 INFO (pid:2373811) [attach] - receive notification: doAutocmd [ 2 ]
2022-05-16T11:44:45.629 INFO (pid:2373811) [attach] - receive notification: doAutocmd [
  3,
  {
    regcontents: [                                                                                                                                                    '## versions',
      '',
      'vim version: NVIM v0.7.0',
      'node version: v18.1.0',
      'coc.nvim version: 0.0.80-949dfbfa 2022-05-15 16:13:13 +0800',
      'coc.nvim directory: /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release',
      'term: tmux',
      'platform: linux',
      '',
      '## Log of coc.nvim',
      '',
      '2022-05-16T11:44:29.384 INFO (pid:2373811) [coc-git] - Looking for git in: git',
      '2022-05-16T11:44:29.398 INFO (pid:2373811) [services] - registered service "highlight"',
      '2022-05-16T11:44:29.559 INFO (pid:2373811) [coc-tabnine] - Using tabnine from /home/wzy/.config/coc/extensions/coc-tabnine-data/binaries/4.4.8/x86_64-unknown-linux-musl/TabNine',
      '2022-05-16T11:44:29.683 INFO (pid:2373811) [plugin] - coc.nvim initialized with node: v18.1.0 after 769ms',
      '2022-05-16T11:44:29.687 WARN (pid:2373811) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. ',
      '    at t.initStatusBar (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:155873)',
      '    at t.activate (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23099)',
      '2022-05-16T11:44:41.685 INFO (pid:2373811) [attach] - receive notification: showInfo []',
      ''
    ],
    visual: true,
    inclusive: true,
    regname: '',
    operator: 'y',
    regtype: 'V'
  },
  2,
  1001
]
2022-05-16T11:45:47.444 INFO (pid:2373811) [attach] - receive notification: openLog []
2022-05-16T11:45:47.448 INFO (pid:2373811) [attach] - receive notification: doAutocmd [ 2 ]
```

**Comment by fannheyward** [comment]
Post the logs after you reproduce your issue.

**Comment by Freed-Wu** [comment]
```
:CocOpenLog

2022-05-16T11:57:46.840 INFO (pid:2423972) [coc-git] - Looking for git in: git
2022-05-16T11:57:46.855 INFO (pid:2423972) [services] - registered service "highlight"
2022-05-16T11:57:47.015 INFO (pid:2423972) [coc-tabnine] - Using tabnine from /home/wzy/.config/coc/extensions/coc-tabnine-data/binaries/4.4.8/x86_64-unknown-linux-musl/TabNine
2022-05-16T11:57:47.142 INFO (pid:2423972) [plugin] - coc.nvim initialized with node: v18.1.0 after 793ms
2022-05-16T11:57:47.148 WARN (pid:2423972) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead.
    at t.initStatusBar (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:155873)
    at t.activate (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23099)
2022-05-16T11:57:47.214 INFO (pid:2423972) [services] - registered service "vimlsp"
2022-05-16T11:57:47.215 INFO (pid:2423972) [services] - vim language server state change: stopped => starting
2022-05-16T11:57:47.370 INFO (pid:2423972) [services] - vim language server state change: starting => running
2022-05-16T11:57:47.372 INFO (pid:2423972) [services] - service vimlsp started
2022-05-16T11:57:49.695 INFO (pid:2423972) [attach] - receive notification: doAutocmd [
  3,
  {
    regcontents: [ 'v' ],
    visual: false,
    inclusive: false,
    regname: '',
    operator: 'c',
    regtype: 'v'
  },
  1,
  1000
]
2022-05-16T11:57:50.035 ERROR (pid:2423972) [node-client] - TypeError: t.words is not iterable Error
    at SA.echoError (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:35:1869)
    at Tx.completeSource (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32983)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 6)
    at async Tx.completeSources (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31773)
    at async Tx.doComplete (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31244)
    at async Zee.startCompletion (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:42932)
    at async Zee.triggerCompletion (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:46707)
    at async Zee.onTextChangedI (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:45437)
2022-05-16T11:57:50.036 ERROR (pid:2423972) [completion-complete] - Complete error: coc-dash-complete TypeError: t.words is not iterable
    at /home/wzy/.config/coc/extensions/node_modules/coc-dash-complete/lib/index.js:1:1264
    at Array.forEach (<anonymous>)
    at i.gatherWords (/home/wzy/.config/coc/extensions/node_modules/coc-dash-complete/lib/index.js:1:1218)
    at i.provideCompletionItems (/home/wzy/.config/coc/extensions/node_modules/coc-dash-complete/lib/index.js:1:1030)
    at ox.doComplete (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:262:9884)
    at /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32390
    at new Promise (<anonymous>)
    at Tx.completeSource (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32352)
    at /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31821
    at Array.map (<anonymous>)
2022-05-16T11:57:50.036 ERROR (pid:2423972) [node-client] - TypeError: e.words is not iterable Error
    at SA.echoError (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:35:1869)
    at Tx.completeSource (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32983)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 7)
    at async Tx.completeSources (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31773)
    at async Tx.doComplete (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31244)
    at async Zee.startCompletion (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:42932)
    at async Zee.triggerCompletion (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:46707)
    at async Zee.onTextChangedI (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:45437)
2022-05-16T11:57:50.036 ERROR (pid:2423972) [completion-complete] - Complete error: coc-dot-complete TypeError: e.words is not iterable
    at /home/wzy/.config/coc/extensions/node_modules/coc-dot-complete/lib/index.js:1:1261
    at Array.forEach (<anonymous>)
    at i.gatherWords (/home/wzy/.config/coc/extensions/node_modules/coc-dot-complete/lib/index.js:1:1215)
    at i.provideCompletionItems (/home/wzy/.config/coc/extensions/node_modules/coc-dot-complete/lib/index.js:1:1027)
    at ox.doComplete (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:262:9884)
    at /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32390
    at new Promise (<anonymous>)
    at Tx.completeSource (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32352)
    at /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31821
    at Array.map (<anonymous>)
2022-05-16T11:57:50.036 ERROR (pid:2423972) [node-client] - TypeError: e.words is not iterable Error
    at SA.echoError (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:35:1869)
    at Tx.completeSource (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32983)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 8)
    at async Tx.completeSources (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31773)
    at async Tx.doComplete (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31244)
    at async Zee.startCompletion (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:42932)
    at async Zee.triggerCompletion (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:46707)
    at async Zee.onTextChangedI (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:45437)
2022-05-16T11:57:50.036 ERROR (pid:2423972) [completion-complete] - Complete error: coc-just-complete TypeError: e.words is not iterable
    at /home/wzy/.config/coc/extensions/node_modules/coc-just-complete/lib/index.js:1:1341
    at Array.forEach (<anonymous>)
    at i.gatherWords (/home/wzy/.config/coc/extensions/node_modules/coc-just-complete/lib/index.js:1:1295)
    at i.provideCompletionItems (/home/wzy/.config/coc/extensions/node_modules/coc-just-complete/lib/index.js:1:1097)
    at ox.doComplete (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:262:9884)
    at /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32390
    at new Promise (<anonymous>)
    at Tx.completeSource (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32352)
    at /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31821
    at Array.map (<anonymous>)
2022-05-16T11:58:00.774 INFO (pid:2423972) [attach] - receive notification: openLog []
2022-05-16T11:58:00.777 INFO (pid:2423972) [attach] - receive notification: doAutocmd [ 2 ]
:CocInfo

## versions

vim version: NVIM v0.7.0
node version: v18.1.0
coc.nvim version: 0.0.80-949dfbfa 2022-05-15 16:13:13 +0800
coc.nvim directory: /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release
term: tmux
platform: linux

## Log of coc.nvim

2022-05-16T11:57:46.840 INFO (pid:2423972) [coc-git] - Looking for git in: git
2022-05-16T11:57:46.855 INFO (pid:2423972) [services] - registered service "highlight"
2022-05-16T11:57:47.015 INFO (pid:2423972) [coc-tabnine] - Using tabnine from /home/wzy/.config/coc/extensions/coc-tabnine-data/binaries/4.4.8/x86_64-unknown-linux-musl/TabNine
2022-05-16T11:57:47.142 INFO (pid:2423972) [plugin] - coc.nvim initialized with node: v18.1.0 after 793ms
2022-05-16T11:57:47.148 WARN (pid:2423972) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead.
    at t.initStatusBar (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:155873)
    at t.activate (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23099)
2022-05-16T11:57:47.214 INFO (pid:2423972) [services] - registered service "vimlsp"
2022-05-16T11:57:47.215 INFO (pid:2423972) [services] - vim language server state change: stopped => starting
2022-05-16T11:57:47.370 INFO (pid:2423972) [services] - vim language server state change: starting => running
2022-05-16T11:57:47.372 INFO (pid:2423972) [services] - service vimlsp started
2022-05-16T11:57:49.695 INFO (pid:2423972) [attach] - receive notification: doAutocmd [
  3,
  {
    regcontents: [ 'v' ],
    visual: false,
    inclusive: false,
    regname: '',
    operator: 'c',
    regtype: 'v'
  },
  1,
  1000
]
2022-05-16T11:57:50.035 ERROR (pid:2423972) [node-client] - TypeError: t.words is not iterable Error
    at SA.echoError (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:35:1869)
    at Tx.completeSource (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32983)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async Promise.all (index 6)
    at async Tx.completeSources (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31773)
    at async Tx.doComplete (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31244)
    at async Zee.startCompletion (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:42932)
    at async Zee.triggerCompletion (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:46707)
    at async Zee.onTextChangedI (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:45437)
2022-05-16T11:57:50.036 ERROR (pid:2423972) [completion-complete] - Complete error: coc-dash-complete TypeError: t.words is not iterable
    at /home/wzy/.config/coc/extensions/node_modules/coc-dash-complete/lib/index.js:1:1264
    at Array.forEach (<anonymous>)
    at i.gatherWords (/home/wzy/.config/coc/extensions/node_modules/coc-dash-complete/lib/index.js:1:1218)
    at i.provideCompletionItems (/home/wzy/.config/coc/extensions/node_modules/coc-dash-complete/lib/index.js:1:1030)
    at ox.doComplete (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:262:9884)
    at /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32390
    at new Promise (<anonymous>)
    at Tx.completeSource (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32352)
    at /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31821
    at Array.map (<anonymous>)
2022-05-16T11:57:50.036 ERROR (pid:2423972) [node-client] - TypeError: e.words is not iterable Error
    at SA.echoError (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:35:1869)
    at Tx.completeSource (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32983)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 7)
    at async Tx.completeSources (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31773)
    at async Tx.doComplete (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31244)
    at async Zee.startCompletion (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:42932)
    at async Zee.triggerCompletion (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:46707)
    at async Zee.onTextChangedI (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:45437)
2022-05-16T11:57:50.036 ERROR (pid:2423972) [completion-complete] - Complete error: coc-dot-complete TypeError: e.words is not iterable
    at /home/wzy/.config/coc/extensions/node_modules/coc-dot-complete/lib/index.js:1:1261
    at Array.forEach (<anonymous>)
    at i.gatherWords (/home/wzy/.config/coc/extensions/node_modules/coc-dot-complete/lib/index.js:1:1215)
    at i.provideCompletionItems (/home/wzy/.config/coc/extensions/node_modules/coc-dot-complete/lib/index.js:1:1027)
    at ox.doComplete (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:262:9884)
    at /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32390
    at new Promise (<anonymous>)
    at Tx.completeSource (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32352)
    at /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31821
    at Array.map (<anonymous>)
2022-05-16T11:57:50.036 ERROR (pid:2423972) [node-client] - TypeError: e.words is not iterable Error
    at SA.echoError (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:35:1869)
    at Tx.completeSource (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32983)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 8)
    at async Tx.completeSources (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31773)
    at async Tx.doComplete (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31244)
    at async Zee.startCompletion (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:42932)
    at async Zee.triggerCompletion (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:46707)
    at async Zee.onTextChangedI (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:45437)
2022-05-16T11:57:50.036 ERROR (pid:2423972) [completion-complete] - Complete error: coc-just-complete TypeError: e.words is not iterable
    at /home/wzy/.config/coc/extensions/node_modules/coc-just-complete/lib/index.js:1:1341
    at Array.forEach (<anonymous>)
    at i.gatherWords (/home/wzy/.config/coc/extensions/node_modules/coc-just-complete/lib/index.js:1:1295)
    at i.provideCompletionItems (/home/wzy/.config/coc/extensions/node_modules/coc-just-complete/lib/index.js:1:1097)
    at ox.doComplete (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:262:9884)
    at /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32390
    at new Promise (<anonymous>)
    at Tx.completeSource (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:32352)
    at /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:31821
    at Array.map (<anonymous>)
2022-05-16T11:58:00.774 INFO (pid:2423972) [attach] - receive notification: openLog []
2022-05-16T11:58:00.777 INFO (pid:2423972) [attach] - receive notification: doAutocmd [ 2 ]
2022-05-16T11:59:19.837 INFO (pid:2423972) [attach] - receive notification: showInfo []
```

**Comment by fannheyward** [comment]
The error is came from `coc-dash-complete` and `coc-just-complete`.

**Comment by chemzqm** [comment]
Seems the result signature unexpected changed.

**Comment by chemzqm** [comment]
The language server happens to return null for completion request, make it empty array on that case.
