### ISSUE TITLE
Bash-language-server closed will not be restarted

### ISSUE THREAD

**Issue by AhmadFudl** [neoclide/coc.nvim#3836]
## versions

vim version: NVIM v0.7.0
node version: v18.2.0
coc.nvim version: 0.0.80-29e5cee6 2022-05-22 06:38:34 +0800
coc.nvim directory: /Users/fudl/.config/nvim/plugged/coc.nvim
term: alacritty
platform: darwin

## Log of coc.nvim

2022-05-22T02:58:06.425 INFO (pid:1131) [services] - registered service "languageserver.bash"
2022-05-22T02:58:06.430 INFO (pid:1131) [services] - bash state change: stopped => starting
2022-05-22T02:58:06.440 INFO (pid:1131) [plugin] - coc.nvim initialized with node: v18.2.0 after 92ms
2022-05-22T02:58:06.444 INFO (pid:1131) [language-client-index] - Language server "languageserver.bash" started with 1136
2022-05-22T02:58:06.515 INFO (pid:1131) [services] - registered service "clangd"
2022-05-22T02:58:06.714 INFO (pid:1131) [services] - bash state change: starting => stopped
2022-05-22T02:58:06.714 INFO (pid:1131) [services] - bash state change: stopped => starting
2022-05-22T02:58:06.715 INFO (pid:1131) [language-client-index] - Language server "languageserver.bash" started with 1140
2022-05-22T02:58:06.968 INFO (pid:1131) [services] - bash state change: starting => stopped
2022-05-22T02:58:06.968 INFO (pid:1131) [services] - bash state change: stopped => starting
2022-05-22T02:58:06.970 INFO (pid:1131) [language-client-index] - Language server "languageserver.bash" started with 1144
2022-05-22T02:58:07.223 INFO (pid:1131) [services] - bash state change: starting => stopped
2022-05-22T02:58:07.223 INFO (pid:1131) [services] - bash state change: stopped => starting
2022-05-22T02:58:07.224 INFO (pid:1131) [language-client-index] - Language server "languageserver.bash" started with 1148
2022-05-22T02:58:07.479 INFO (pid:1131) [services] - bash state change: starting => stopped
2022-05-22T02:58:07.479 ERROR (pid:1131) [services] - Server languageserver.bash failed to start: Error: Connection to server got closed. Server will not be restarted.
    at Bf.handleConnectionClosed (/Users/fudl/.config/nvim/plugged/coc.nvim/build/index.js:223:1006)
    at Bf.handleConnectionClosed (/Users/fudl/.config/nvim/plugged/coc.nvim/build/index.js:223:28544)
    at t (/Users/fudl/.config/nvim/plugged/coc.nvim/build/index.js:223:386)
    at cN.invoke (/Users/fudl/.config/nvim/plugged/coc.nvim/build/index.js:36:9670)
    at Md.fire (/Users/fudl/.config/nvim/plugged/coc.nvim/build/index.js:36:10436)
    at xi (/Users/fudl/.config/nvim/plugged/coc.nvim/build/index.js:37:10897)
    at cN.invoke (/Users/fudl/.config/nvim/plugged/coc.nvim/build/index.js:36:9670)
    at Md.fire (/Users/fudl/.config/nvim/plugged/coc.nvim/build/index.js:36:10436)
    at TS.fireClose (/Users/fudl/.config/nvim/plugged/coc.nvim/build/index.js:37:525)
    at Socket.<anonymous> (/Users/fudl/.config/nvim/plugged/coc.nvim/build/index.js:37:1307)
2022-05-22T02:58:53.583 INFO (pid:1131) [attach] - receive notification: checkJsonExtension []
2022-05-22T02:58:53.615 INFO (pid:1131) [services] - registered service "json"
2022-05-22T02:58:53.615 INFO (pid:1131) [services] - Json language server state change: stopped => starting
2022-05-22T02:58:53.717 INFO (pid:1131) [services] - Json language server state change: starting => running
2022-05-22T02:58:53.721 INFO (pid:1131) [services] - service json started
2022-05-22T03:02:53.322 INFO (pid:1131) [attach] - receive notification: showInfo []

## Describe the bug

I open a .sh file a error appears saying the server closed and will not be restarted

[coc.nvim] Server languageserver.bash failed to start: Error: Connection to server got closed. Server will not be restarted.

## Reproduce the bug

`npm i -g bash-language-server`
add 
`  "languageserver": {
    "bash": {
      "command": "bash-language-server",
      "args": ["start"],
      "filetypes": ["sh"],
      "ignoredRootPaths": ["~"]
    }
  }`
to coc-settings.json
open a .sh file

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by chemzqm** [comment]
The language server have issue with node v18.2.0, try to upgrade your language server or downgrade node.

**Comment by yaegassy** [comment]
A new version of bash-language-server has been released. <https://www.npmjs.com/package/bash-language-server/v/3.0.3>

Node.js version 18 may now be supported. <https://github.com/bash-lsp/bash-language-server/pull/404>

Upgrade `bash-language-server` and give it a try!
