### ISSUE TITLE
Vim(highlight):E421: Color name or number not recognized:

### ISSUE THREAD

**Issue by rolandjon** [neoclide/coc.nvim#3927]
## versions

vim version: VIM - Vi IMproved 8.2 8024929
node version: v12.18.1
coc.nvim version: 0.0.81-2522eee5 2022-06-14 19:03:29 +0800
coc.nvim directory: /home/rland/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2022-07-20T19:59:53.000 INFO (pid:69524) [services] - registered service "languageserver.ccls"
2022-07-20T19:59:53.054 INFO (pid:69524) [services] - registered service "highlight"
2022-07-20T19:59:53.068 INFO (pid:69524) [plugin] - coc.nvim initialized with node: v12.18.1 after 142ms
2022-07-20T19:59:53.070 INFO (pid:69524) [attach] - receive notification: highlight []
2022-07-20T19:59:53.111 ERROR (pid:69524) [node-client] - call_atomic request error VimException(String) on "nvim_command" [
  'highlight default CocExplorerNormalColor_Internal ctermfg=NaN guifg=#00000E'
] Vim(highlight):E421: Color name or number not recognized: ctermfg=NaN guifg=#00000E on function coc#api#call[4]..23[6]..29, line 5 Error
    at AM.resumeNotification (/home/rland/.vim/plugged/coc.nvim/build/index.js:32:1302)
    at HM.resumeNotification (/home/rland/.vim/plugged/coc.nvim/build/index.js:35:5485)
    at /home/rland/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:317:21631
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Pc.watchColorScheme (/home/rland/.config/coc/extensions/node_modules/coc-explorer/lib/index.js:317:5424)
2022-07-20T19:59:58.030 INFO (pid:69524) [attach] - receive notification: showInfo []

## Describe the bug

The following error will be reported every time VIM is started：
----
![222](https://user-images.githubusercontent.com/8503374/179977709-5e72bff4-12f7-422b-b809-42d830d2d6dd.png)
----

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
> highlight default CocExplorerNormalColor_Internal ctermfg=NaN guifg=#00000E

The `ctermfg` is `NaN`, an invalid value. cc @weirongxu, can you take a look at this?

**Comment by weirongxu** [comment]
I have tried to avoid the wrong color on [v0.24.4](https://github.com/weirongxu/coc-explorer/releases/tag/v0.24.4), please try to update the coc-explorer

**Comment by rolandjon** [comment]
> Hi @rolandjon , may I know what theme you are using? It should be a bug in parsing some highlights, I want to try to reproduce it.

Sorry for not getting back to you sooner,I am currently using the desert theme.
>I have tried to avoid the wrong color on [v0.24.4](https://github.com/weirongxu/coc-explorer/releases/tag/v0.24.4), please try to upgrade the coc-explorer

This definitely fixed the issue, thanks for the great work -)
