### ISSUE TITLE
Second item is selected by default in suggestion popup despite suggest.selection = `first`

### ISSUE THREAD

**Issue by Frederick888** [neoclide/coc.nvim#3981]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.2
node version: v18.7.0
coc.nvim version: 0.0.82-ebe19461 2022-08-02 04:07:00 +0800
coc.nvim directory: /Users/frederick.zhang/.vim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2022-08-02T11:01:34.929 INFO (pid:90712) [configurations] - Add folder configuration from cwd: /Users/frederick.zhang/Programming/Go/hello_world/.vim/coc-settings.json
2022-08-02T11:01:34.931 INFO (pid:90712) [configurations] - Change folder configuration from cwd to: /Users/frederick.zhang/Programming/Go/hello_world/.vim/coc-settings.json
2022-08-02T11:01:35.089 INFO (pid:90712) [services] - registered service "languageserver.bash"
2022-08-02T11:01:35.089 INFO (pid:90712) [services] - registered service "languageserver.ccls"
2022-08-02T11:01:35.089 INFO (pid:90712) [services] - registered service "languageserver.cmake"
2022-08-02T11:01:35.089 INFO (pid:90712) [services] - registered service "languageserver.dockerfile"
2022-08-02T11:01:35.089 INFO (pid:90712) [services] - registered service "languageserver.jsonnet"
2022-08-02T11:01:35.090 INFO (pid:90712) [services] - registered service "languageserver.sql"
2022-08-02T11:01:35.136 INFO (pid:90712) [services] - registered service "diagnostic-languageserver"
2022-08-02T11:01:35.137 INFO (pid:90712) [services] - diagnostic language service state change: stopped => starting
2022-08-02T11:01:35.332 INFO (pid:90712) [plugin] - coc.nvim initialized with node: v18.7.0 after 333ms
2022-08-02T11:01:35.341 WARN (pid:90712) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at t.initStatusBar (/Users/frederick.zhang/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:155873)
    at t.activate (/Users/frederick.zhang/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23099)
2022-08-02T11:01:35.476 INFO (pid:90712) [services] - diagnostic language service state change: starting => running
2022-08-02T11:01:35.478 INFO (pid:90712) [services] - service diagnostic-languageserver started
2022-08-02T11:01:35.485 INFO (pid:90712) [services] - registered service "go"
2022-08-02T11:01:35.485 INFO (pid:90712) [services] - gopls state change: stopped => starting
2022-08-02T11:01:37.518 INFO (pid:90712) [services] - gopls state change: starting => running
2022-08-02T11:01:37.521 INFO (pid:90712) [services] - service go started
2022-08-02T11:01:44.075 INFO (pid:90712) [attach] - receive notification: doAutocmd [
  2,
  {
    regcontents: [ '\tfmt.' ],
    visual: false,
    inclusive: false,
    regname: '',
    operator: 'd',
    regtype: 'V'
  },
  1,
  1000
]
2022-08-02T11:01:44.732 INFO (pid:90712) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-08-02T11:01:48.052 INFO (pid:90712) [attach] - receive notification: showInfo []

```

## Describe the bug

Second item is selected by default in suggestion popup despite suggest.selection = `first` ~~(which iirc is the default value but tested with it in my config anyway)~~.

It seems to be a new issue in v0.0.82. be514c7 was good

## Reproduce the bug

- Create file `mini.vim` with:

  ```vim
  set runtimepath^=~/.vim runtimepath+=~/.vim/after
  let &packpath = &runtimepath

  call plug#begin('~/.vim/plugged')
  Plug 'neoclide/coc.nvim', { 'branch': 'release' }
  call plug#end()

  if has('mac')
    let g:coc_node_path = '/usr/local/bin/node'
  else
    let g:coc_node_path = '/usr/bin/node'
  endif

  set nobackup
  set nowritebackup
  set cmdheight=2
  set updatetime=300
  ```

- Create file `hello_world.go` with:
  ```
  package main
  
  import (
  	"fmt"
  )
  
  func main() {
  	fmt.Printf("%v\n", 1)
  }
  ```

- Start (neo)vim with command: `nvim -u mini.vim hello_world.go`

- In main(), type `fmt.` and wait for suggestion popup
- Second item is selected instead of first one.

## Screenshots (optional)

<img width="911" alt="image" src="https://user-images.githubusercontent.com/4507647/182269067-fcb0e597-e7b8-481c-8ef6-3db256d01693.png">

**Comment by Chase-Lambert** [comment]
I'm seeing the same except it's not always just the second option. For example when I am in a Go file and write `fmt.|` hitting <TAB> will start at `Formatter` which is the 4th option down.

The second problem I am seeing after this update is that my options are not getting highlighted at all as I TAB down through the options.

**Comment by fannheyward** [comment]
`gopls` returns `Errorf` with `preselect = true`, that's why `Errorf` is selected even it's on second option. You can use `"suggest.enablePreselect": false` to disable `preselect`.

**Comment by Frederick888** [comment]
@fannheyward Oh I see. Thank you. Btw would it make sense put preselected item at the beginning regardless of `suggest.defaultSortMethod` when `suggest.enablePreselect` is enabled?

**Comment by chemzqm** [comment]
No, I don't think it's needed.

**Comment by Aex12** [comment]
> `gopls` returns `Errorf` with `preselect = true`, that's why `Errorf` is selected even it's on second option. You can use `"suggest.enablePreselect": false` to disable `preselect`.

I have the same problem using javascript. It always select the second option on TAB. <CR> correctly select the first option.

I've tried setting my coc-settings.json to suggest.selection=first and suggest.enablePreselect=false, but the issue persists. The second option is always selected on TAB.

@Frederick888 did you managed to find a solution to this ?

**Comment by Frederick888** [comment]
@Aex12 I don't have this ~~issue~~ feature any more after setting `suggest.enablePreselect=false`. And I actually don't have `suggest.selection=first` in my config. Also tested JavaScript with `coc-tsserver` without issues.

What you are experiencing might be different. I suggest you try my minimal vimrc first.

**Comment by Aex12** [comment]
@Frederick888 I've tried with the minimal vim configuration, but the problem persists. I've also tried removing `suggest.selection=first`, but the behavior doesn't change. TAB still select always the second option. What version are you using?

Mine is
```
vim version: NVIM v0.7.2
node version: v16.16.0
coc.nvim version: 0.0.82-9bec5321
```
running on a Macbook Pro M1.

This was working as expected a few weeks ago, until I updated today.

**Comment by Frederick888** [comment]
@Aex12 

I'm running these on Arch:

```
vim version: NVIM v0.7.2
node version: v18.7.0
coc.nvim version: 0.0.82-9bec5321 2022-08-02 22:52:26 +0800
```

Also used on an Intel mac today without issue (Node from Homebrew).

If you updated coc today perhaps check `git reflog` and do a `git bisect` to see if it's related to v0.0.82 release?

**Comment by Aex12** [comment]
@Frederick888 effectively, 0.0.82 introduced the bug for me:

1d3c525e2d6af0c07ed19fa7a5016ffc6a9e8421 is the first bad commit

**Comment by Frederick888** [comment]
> It always select the second option on TAB. <CR> correctly select the first option.

My issue actually didn't involve TAB or <CR>. I just typed in `fmt.` then waited for the popup menu to show up (and it automatically selected the 'preselected' item set by LSP server). I think this is because I have `"suggest.noselect": false`.

FWIW I tested below minimal vimrc with `"suggest.noselect": true` in JavaScript but still didn't experience this issue

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', { 'branch': 'release' }
call plug#end()

set nocompatible
set updatetime=300
set cmdheight=2

" Use tab for trigger completion with characters ahead and navigate.
" Insert <tab> when previous text is space, refresh completion if not.
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1):
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction

" Use <c-space> to trigger completion.
if has('nvim')
  inoremap <expr> <silent> <c-space> coc#refresh()
else
  inoremap <expr> <silent> <c-@> coc#refresh()
endif

inoremap <expr> <CR> coc#pum#visible() ? coc#_select_confirm() : "\<CR>"
```

I have no idea then... I guess you can post your logs and wait for the maintainers to respond :shrug:

**Comment by Aex12** [comment]
>  I think this is because I have "suggest.noselect": false.
I didn't knew about this option. I set it to true, and now TAB correctly select the first item, but \<CR\> doesn't complete the first option unless I press tab before, but that is a minor concern for me as I never use it to autocomplete.

Thanks a lot @Frederick888 you saved my day.
