### ISSUE TITLE
filetype don't detect when open buffer that named `deno:/*` using `CocTagFunc`.

### ISSUE THREAD

**Issue by skanehira** [neoclide/coc.nvim#4026]
## Result from CocInfo

<details>
<summary>:CocInfo</summary>

## versions

vim version: NVIM v0.7.0
node version: v18.6.0
coc.nvim version: 0.0.82-9302171e 2022-08-07 21:24:35 +0800
coc.nvim directory: /Users/skanehira/.cache/dein/nvim/repos/github.com/neoclide/coc.nvim_master
term: tmux
platform: darwin

## Log of coc.nvim

2022-08-09T13:09:19.049 INFO (pid:56397) [configurations] - Add folder configuration from cwd: /Users/skanehira/dev/github.com/skanehira/k8s.vim/.vim/coc-settings.json
2022-08-09T13:09:19.050 INFO (pid:56397) [configurations] - Change folder configuration from cwd to: /Users/skanehira/dev/github.com/skanehira/k8s.vim/.vim/coc-settings.json
2022-08-09T13:09:19.223 INFO (pid:56397) [services] - registered service "languageserver.golangci-lint-languageserver"
2022-08-09T13:09:19.223 INFO (pid:56397) [services] - registered service "languageserver.efm"
2022-08-09T13:09:19.223 INFO (pid:56397) [services] - registered service "languageserver.terraform"
2022-08-09T13:09:19.238 INFO (pid:56397) [services] - registered service "diagnostic-languageserver"
2022-08-09T13:09:19.252 WARN (pid:56397) [workspace] - workspace.createOutputChannel is deprecated, please use window.createOutputChannel instead. 
    at Object.<anonymous> (/Users/skanehira/.config/coc/extensions/node_modules/coc-graphql/lib/index.js:135:49)
    at Generator.next (<anonymous>)
2022-08-09T13:09:19.253 INFO (pid:56397) [services] - registered service "graphql"
2022-08-09T13:09:19.327 INFO (pid:56397) [plugin] - coc.nvim initialized with node: v18.6.0 after 185ms
2022-08-09T13:09:19.649 INFO (pid:56397) [services] - registered service "eslint"
2022-08-09T13:09:19.650 INFO (pid:56397) [services] - ESLint state change: stopped => starting
2022-08-09T13:09:19.670 INFO (pid:56397) [services] - registered service "tsserver"
2022-08-09T13:09:19.693 INFO (pid:56397) [language-client-index] - Language server "deno" started with 56576
2022-08-09T13:09:19.791 INFO (pid:56397) [services] - ESLint state change: starting => running
2022-08-09T13:09:19.794 INFO (pid:56397) [services] - service eslint started
2022-08-09T13:09:21.710 INFO (pid:56397) [attach] - receive notification: jumpDefinition []
2022-08-09T13:09:21.712 ERROR (pid:56397) [node-client] - Error on notification "jumpDefinition": definition provider not found for current buffer, your language server doesn't support it. Error
    at NeovimClient2.echoError (/Users/skanehira/.cache/dein/nvim/repos/github.com/neoclide/coc.nvim_master/build/index.js:11322:41)
    at NeovimClient2.<anonymous> (/Users/skanehira/.cache/dein/nvim/repos/github.com/neoclide/coc.nvim_master/build/index.js:77840:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-08-09T13:09:21.712 ERROR (pid:56397) [attach] - Error: definition provider not found for current buffer, your language server doesn't support it.
    at Handler.checkProvier (/Users/skanehira/.cache/dein/nvim/repos/github.com/neoclide/coc.nvim_master/build/index.js:77445:13)
    at LocationsHandler.request (/Users/skanehira/.cache/dein/nvim/repos/github.com/neoclide/coc.nvim_master/build/index.js:73663:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LocationsHandler.gotoDefinition (/Users/skanehira/.cache/dein/nvim/repos/github.com/neoclide/coc.nvim_master/build/index.js:73705:22)
    at async Plugin.cocAction (/Users/skanehira/.cache/dein/nvim/repos/github.com/neoclide/coc.nvim_master/build/index.js:77736:15)
    at async NeovimClient2.<anonymous> (/Users/skanehira/.cache/dein/nvim/repos/github.com/neoclide/coc.nvim_master/build/index.js:77838:11)
2022-08-09T13:09:23.339 INFO (pid:56397) [attach] - receive notification: jumpDefinition []
2022-08-09T13:09:23.913 WARN (pid:56397) [plugin] - Slow action "jumpDefinition" cost 574ms
2022-08-09T13:09:26.878 INFO (pid:56397) [attach] - receive notification: showInfo []

</details>

## Describe the bug
filetype don't detect when open buffer that named `deno:/*` using `CocTagFunc`.
But when I use `<Plug>(coc-definition)` to open `deno:/*` then filetype was detected.

## Reproduce the bug
- Create file `mini.vim` with:

  ```vim
  set nocompatible
  set runtimepath^=/tmp/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  set tagfunc=CocTagFunc
  ```

- Install coc-deno
  ```vim
  :CocInstall coc-deno
  ```

- Create deno workspace with:
  ```sh
  mkdir -p test/.vim
  cat <<EOS > test/.vim/coc-settings.json
  {
    "deno.enable": true,
    "deno.lint": true,
    "deno.unstable": true
  }
  EOS
  
  cat <<EOS > test/main.ts
  console.log("foo");
  EOS
  ```
- Start (neo)vim with command: `vim -u mini.vim`

- Open `console`'s definition using `<C-]>`

## Screenshots (optional)

![deno-ft-not-detect](https://user-images.githubusercontent.com/7888591/183564171-11afc2ac-6f4a-4d36-aafb-3d723b811e4d.gif)

**Comment by chemzqm** [comment]
You need create autocmd in your vimrc, coc.nvim doesn't detect filetype
