### ISSUE TITLE
Colorcolumn highlight in hover floating window

### ISSUE THREAD

**Issue by ytian81** [neoclide/coc.nvim#4033]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.2
node version: v17.9.0
coc.nvim version: 0.0.82-d8561387 2022-08-07 04:42:37 +0800
coc.nvim directory: /home/yang.tian/.vim/plugged/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2022-08-09T11:36:44.212 INFO (pid:9857) [coc-git] - Looking for git in: git
2022-08-09T11:36:44.226 INFO (pid:9857) [services] - registered service "highlight"
2022-08-09T11:36:44.300 INFO (pid:9857) [plugin] - coc.nvim initialized with node: v17.9.0 after 247ms
2022-08-09T11:36:44.311 INFO (pid:9857) [services] - registered service "clangd"
2022-08-09T11:36:44.312 INFO (pid:9857) [services] - clangd state change: stopped => starting
2022-08-09T11:36:44.344 INFO (pid:9857) [language-client-index] - Language server "clangd" started with 9888
2022-08-09T11:36:44.355 INFO (pid:9857) [services] - clangd state change: starting => running
2022-08-09T11:36:44.361 INFO (pid:9857) [services] - service clangd started
2022-08-09T11:36:44.370 WARN (pid:9857) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead.
    at Object.t.initStatusBar (/home/yang.tian/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:155873)
    at Object.t.activate (/home/yang.tian/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23099)
2022-08-09T11:36:47.459 INFO (pid:9857) [attach] - Request action: hasProvider [ 'hover' ]
2022-08-09T11:36:47.461 INFO (pid:9857) [attach] - receive notification: doHover []
2022-08-09T11:38:11.193 INFO (pid:9857) [attach] - receive notification: showInfo []
```

## Describe the bug

If there is a long comment above a variable, CoC hover floating window will `colorcolumn` highlight. Mind the red background in the hover floating window.
![image](https://user-images.githubusercontent.com/14842664/183737083-cf5f7026-0581-4931-9a82-b4a1a510fca6.png)

Comment out `set colorcolumn=+1` in the mini.vim will resolve the issue.
## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：
```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'gruvbox-community/gruvbox'
call plug#end()

" Use K to show documentation in preview window.
nnoremap <silent> K :call ShowDocumentation()<CR>
function! ShowDocumentation()
  if CocAction('hasProvider', 'hover')
    call CocActionAsync('doHover')
  else
    call feedkeys('K', 'in')
  endif
endfunction
function! MyHighlights() abort
    highlight link CocFloatDividingLine Error
endfunction
augroup ColorSchemeOverWrite
    autocmd!
    autocmd ColorScheme * call MyHighlights()
augroup END

colorscheme gruvbox
set termguicolors

set textwidth=100
set colorcolumn=+1
highlight ColorColumn ctermbg=red guibg=red
highlight link CocFloatDividingLine Comment
```

```c++
#include <iostream>
#include <vector>

int main(int argc, char *argv[]) {

  // Lorem Ipsum is simply dummy text of the printing and typesetting industry.
  // Lorem Ipsum has been the industry's standard dummy text ever since the
  // 1500s, when an unknown printer took a galley of type and scrambled it to
  // make a type specimen book. It has survived not only five centuries, but
  // also the leap into electronic typesetting, remaining essentially unchanged.
  // It was popularised in the 1960s with the release of Letraset sheets
  // containing Lorem Ipsum passages, and more recently with desktop publishing
  // software like Aldus PageMaker including versions of Lorem Ipsum.
  std::vector<int> x;

  x.push_back(1);

  return 0;
}
```

- Start (neo)vim with command: `vim -u mini.vim main.cpp`

- Operate vim.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
