### ISSUE TITLE
UnhandledRejection: hints is not iterable

### ISSUE THREAD

**Issue by jackielii** [neoclide/coc.nvim#4061]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.2
node version: v14.20.0
coc.nvim version: 0.0.82-master
coc.nvim directory: /Users/jackieli/.config/nvim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2022-08-16T11:58:42.477 INFO (pid:86075) [services] - registered service "languageserver.ccls"
2022-08-16T11:58:42.479 INFO (pid:86075) [services] - registered service "languageserver.kotlin"
2022-08-16T11:58:42.479 INFO (pid:86075) [services] - registered service "languageserver.dockerfile"
2022-08-16T11:58:42.479 INFO (pid:86075) [services] - registered service "languageserver.bash"
2022-08-16T11:58:42.490 INFO (pid:86075) [services] - registered service "diagnostic-languageserver"
2022-08-16T11:58:42.539 INFO (pid:86075) [coc-git] - Looking for git in: git
2022-08-16T11:58:42.556 INFO (pid:86075) [services] - registered service "highlight"
2022-08-16T11:58:42.727 INFO (pid:86075) [plugin] - coc.nvim initialized with node: v14.20.0 after 328ms
2022-08-16T11:58:42.811 WARN (pid:86075) [language-client-client] - disableWorkspaceFolders in the client options is deprecated. use disabledFeatures instead. 
    at new LanguageClient (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:52048:9)
    at registerGopls (/Users/jackieli/personal/coc-go/lib/extension.js:75:20)
2022-08-16T11:58:42.811 INFO (pid:86075) [services] - registered service "go"
2022-08-16T11:58:42.811 INFO (pid:86075) [services] - gopls state change: stopped => starting
2022-08-16T11:58:43.072 INFO (pid:86075) [services] - gopls state change: starting => running
2022-08-16T11:58:43.073 INFO (pid:86075) [services] - service go started
2022-08-16T11:58:44.443 ERROR (pid:86075) [server] - unhandledRejection  Promise {
  <rejected> TypeError: hints is not iterable
      at /Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37983:30
      at async Promise.all (index 0)
      at async InlayHintManger.provideInlayHints (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37978:9)
      at async InlayHintBuffer.renderRange (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:77292:22)
      at async /Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:77353:13
} TypeError: hints is not iterable
    at /Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37983:30
    at async Promise.all (index 0)
    at async InlayHintManger.provideInlayHints (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37978:9)
    at async InlayHintBuffer.renderRange (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:77292:22)
    at async /Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:77353:13
2022-08-16T11:58:47.132 INFO (pid:86075) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-08-16T11:58:47.644 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:58:48.639 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:58:52.323 INFO (pid:86075) [attach] - receive notification: doAutocmd [ 1 ]
2022-08-16T11:58:52.583 ERROR (pid:86075) [server] - unhandledRejection  Promise {
  <rejected> TypeError: hints is not iterable
      at /Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37983:30
      at async Promise.all (index 0)
      at async InlayHintManger.provideInlayHints (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37978:9)
      at async InlayHintBuffer.renderRange (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:77292:22)
} TypeError: hints is not iterable
    at /Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37983:30
    at async Promise.all (index 0)
    at async InlayHintManger.provideInlayHints (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37978:9)
    at async InlayHintBuffer.renderRange (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:77292:22)
2022-08-16T11:58:53.649 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:58:55.996 INFO (pid:86075) [attach] - receive notification: doAutocmd [ 1 ]
2022-08-16T11:58:56.252 ERROR (pid:86075) [server] - unhandledRejection  Promise {
  <rejected> TypeError: hints is not iterable
      at /Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37983:30
      at async Promise.all (index 0)
      at async InlayHintManger.provideInlayHints (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37978:9)
      at async InlayHintBuffer.renderRange (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:77292:22)
} TypeError: hints is not iterable
    at /Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37983:30
    at async Promise.all (index 0)
    at async InlayHintManger.provideInlayHints (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37978:9)
    at async InlayHintBuffer.renderRange (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:77292:22)
2022-08-16T11:59:05.361 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:59:07.463 INFO (pid:86075) [attach] - receive notification: doAutocmd [ 1 ]
2022-08-16T11:59:07.463 INFO (pid:86075) [attach] - receive notification: checkJsonExtension []
2022-08-16T11:59:07.516 INFO (pid:86075) [services] - registered service "json"
2022-08-16T11:59:07.516 INFO (pid:86075) [services] - Json language server state change: stopped => starting
2022-08-16T11:59:07.538 INFO (pid:86075) [services] - registered service "tsserver"
2022-08-16T11:59:07.596 INFO (pid:86075) [services] - Json language server state change: starting => running
2022-08-16T11:59:07.598 INFO (pid:86075) [services] - service json started
2022-08-16T11:59:07.930 INFO (pid:86075) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-08-16T11:59:13.013 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:59:16.505 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:59:17.118 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:59:18.616 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:59:19.756 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:59:20.566 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:59:21.401 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:59:21.947 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:59:24.047 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:59:25.924 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:59:26.267 INFO (pid:86075) [attach] - receive notification: doHover []
2022-08-16T11:59:26.635 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:59:39.501 INFO (pid:86075) [attach] - receive notification: startCompletion [
  {
    word: '',
    bufnr: 69,
    col: 2,
    disabled: [],
    filepath: '/Users/jackieli/.config/nvim/coc-settings.json',
    indentkeys: '',
    blacklist: [],
    line: '  ',
    filetype: 'jsonc',
    linenr: 31,
    input: '',
    colnr: 3,
    changedtick: 17
  }
]
2022-08-16T11:59:40.774 INFO (pid:86075) [attach] - Request action: doKeymap [ 'iPGJzPg==0' ]
2022-08-16T11:59:47.881 INFO (pid:86075) [attach] - receive notification: doAutocmd [
  2,
  {
    regcontents: [ '  hints' ],
    visual: false,
    inclusive: false,
    regname: '',
    operator: 'd',
    regtype: 'V'
  },
  69,
  1000
]
2022-08-16T11:59:48.203 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:59:48.548 INFO (pid:86075) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-08-16T11:59:49.022 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T11:59:50.699 INFO (pid:86075) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_coc_helper_1',
  'BufDelete',
  69
]
2022-08-16T11:59:50.699 INFO (pid:86075) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'BufDelete',
  69
]
2022-08-16T11:59:50.710 INFO (pid:86075) [attach] - receive notification: doAutocmd [ 1 ]
2022-08-16T11:59:51.111 ERROR (pid:86075) [server] - unhandledRejection  Promise {
  <rejected> TypeError: hints is not iterable
      at /Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37983:30
      at async Promise.all (index 0)
      at async InlayHintManger.provideInlayHints (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37978:9)
      at async InlayHintBuffer.renderRange (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:77292:22)
} TypeError: hints is not iterable
    at /Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37983:30
    at async Promise.all (index 0)
    at async InlayHintManger.provideInlayHints (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37978:9)
    at async InlayHintBuffer.renderRange (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:77292:22)
2022-08-16T12:00:04.941 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T12:00:05.653 INFO (pid:86075) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_coc_helper_1',
  'BufDelete',
  60
]
2022-08-16T12:00:05.657 INFO (pid:86075) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'BufDelete',
  60
]
2022-08-16T12:00:05.659 INFO (pid:86075) [attach] - receive notification: doAutocmd [ 1 ]
2022-08-16T12:00:06.058 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T12:00:07.994 INFO (pid:86075) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_coc_helper_1',
  'BufDelete',
  68
]
2022-08-16T12:00:07.994 INFO (pid:86075) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'BufDelete',
  68
]
2022-08-16T12:00:08.048 INFO (pid:86075) [attach] - receive notification: doAutocmd [ 1 ]
2022-08-16T12:00:08.681 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T12:00:26.940 INFO (pid:86075) [attach] - receive notification: doAutocmd [ 1 ]
2022-08-16T12:00:28.391 INFO (pid:86075) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_coc_helper_1',
  'BufWipeout',
  86
]
2022-08-16T12:00:28.391 INFO (pid:86075) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'BufWipeout',
  86
]
2022-08-16T12:00:28.403 INFO (pid:86075) [attach] - receive notification: doAutocmd [ 1 ]
2022-08-16T12:00:28.442 INFO (pid:86075) [attach] - receive notification: doAutocmd [ 1 ]
2022-08-16T12:00:28.912 ERROR (pid:86075) [server] - unhandledRejection  Promise {
  <rejected> TypeError: hints is not iterable
      at /Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37983:30
      at async Promise.all (index 0)
      at async InlayHintManger.provideInlayHints (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37978:9)
      at async InlayHintBuffer.renderRange (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:77292:22)
} TypeError: hints is not iterable
    at /Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37983:30
    at async Promise.all (index 0)
    at async InlayHintManger.provideInlayHints (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37978:9)
    at async InlayHintBuffer.renderRange (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:77292:22)
2022-08-16T12:01:30.745 INFO (pid:86075) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'CocDiagnosticChange'
]
2022-08-16T12:01:31.080 INFO (pid:86075) [attach] - receive notification: highlight []
2022-08-16T12:01:33.181 INFO (pid:86075) [attach] - receive notification: showInfo []

```

## Describe the bug

Open a file which LSP ignores, then exception shows:

```
[coc.nvim]: UnhandledRejection: hints is not iterable
TypeError: hints is not iterable
    at /Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37983:30
    at async Promise.all (index 0)
    at async InlayHintManger.provideInlayHints (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:37978:9)
    at async InlayHintBuffer.renderRange (/Users/jackieli/.config/nvim/plugged/coc.nvim/build/index.js:77292:22)
```

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- CocConfig has:
   ```
     "go.goplsOptions": {
        "buildFlags": ["-tags=wireinject"],
   ```
- open file called `wire_gen.go` which has build flags in comment:

  ```
  // Code generated by Wire. DO NOT EDIT.
  
  //go:generate go run github.com/google/wire/cmd/wire
  //go:build !wireinject
  // +build !wireinject
  
  ```
- error appears

**Comment by fannheyward** [comment]
This should already be fixed in https://github.com/neoclide/coc.nvim/pull/4023
