### ISSUE TITLE
Unknown function: coc#pum#visible

### ISSUE THREAD

**Issue by Vthechamp22** [neoclide/coc.nvim#4066]
When I try to use the sample configuration provided in the README and remap ctrl + tab to trigger completion, whenever I press Tab, it leads to an error: `E117: Unknown function: coc#pum#visible`

## Result from CocInfo

```
## versions

vim version: NVIM v0.6.1
node version: v16.16.0
coc.nvim version: 0.0.81-2522eee5 2022-06-14 19:03:29 +0800
coc.nvim directory: ~/.local/share/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2022-08-17T22:33:41.027 WARN (pid:2376907) [workspace] - workspace.createOutputChannel is deprecated, please use window.createOutputChannel instead. 
    at new Logger (~/.config/coc/extensions/node_modules/coc-discord/lib/utils/logger.js:10:44)
    at Object.<anonymous> (~/.config/coc/extensions/node_modules/coc-discord/lib/index.js:16:16)
2022-08-17T22:33:41.062 INFO (pid:2376907) [services] - registered service "eslint"
2022-08-17T22:33:41.063 INFO (pid:2376907) [services] - ESLint state change: stopped => starting
2022-08-17T22:33:41.067 INFO (pid:2376907) [services] - registered service "html"
2022-08-17T22:33:41.067 INFO (pid:2376907) [services] - HTML language server state change: stopped => starting
2022-08-17T22:33:41.096 INFO (pid:2376907) [plugin] - coc.nvim initialized with node: v16.16.0 after 190ms
2022-08-17T22:33:41.172 INFO (pid:2376907) [services] - ESLint state change: starting => running
2022-08-17T22:33:41.177 INFO (pid:2376907) [services] - service eslint started
2022-08-17T22:33:41.392 INFO (pid:2376907) [services] - HTML language server state change: starting => running
2022-08-17T22:33:41.397 INFO (pid:2376907) [services] - service html started
2022-08-17T22:34:50.195 WARN (pid:2376907) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2022-08-17T22:34:50.426 INFO (pid:2376907) [snippets-session] - Jump to final placeholder, cancelling snippet session
2022-08-17T22:37:29.142 INFO (pid:2376907) [attach] - Request action: doAutocmd [ 1, 1 ]
2022-08-17T23:25:04.890 INFO (pid:2376907) [attach] - receive notification: showInfo []

```

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim
call plug#begin()
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

" Some servers have issues with backup files, see #649.
set nobackup
set nowritebackup

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved.
set signcolumn=yes

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
      \ coc#pum#visible() ? coc#pum#next(1):
      \ CheckBackspace() ? "\<Tab>" :
      \ coc#refresh()
inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

" Make <CR> to accept selected completion item or notify coc.nvim to format
" <C-g>u breaks current undo, please make your own choice.
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction


if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif
  ```

- Start neovim with command: `nvim -u mini.vim`

- Operate vim.

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/61617820/185209498-8417cf49-1496-4d6f-9f78-1ef513c7f8c1.png)
(Typing print and then pressing Tab)

**Comment by chemzqm** [comment]
Uograde your coc.nvim
