### ISSUE TITLE
<PageDown> cannot be mapped in coc's popup menu

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc.nvim#4153]
## Result from CocInfo

```

## versions

vim version: NVIM v0.7.2
node version: v18.7.0
coc.nvim version: 0.0.82-b797c032 2022-09-04 21:59:01 +0800
coc.nvim directory: /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release
term: tmux
platform: linux

## Log of coc.nvim

2022-09-05T22:17:45.473 ERROR (pid:378449) [configurations] - Invalid configuration "suggest.detailMaxLength" from coc-clangd, overwrite defaults is fobidden.
2022-09-05T22:17:45.474 ERROR (pid:378449) [configurations] - Invalid configuration "diagnostic.format" from coc-clangd, overwrite defaults is fobidden.
2022-09-05T22:17:45.955 INFO (pid:378449) [coc-git] - Looking for git in: git
2022-09-05T22:17:45.968 INFO (pid:378449) [services] - registered service "highlight"
2022-09-05T22:17:46.127 INFO (pid:378449) [coc-tabnine] - Using tabnine from /home/wzy/.config/coc/extensions/coc-tabnine-data/binaries/4.4.139/x86_64-unknown-linux-musl/TabNine
2022-09-05T22:17:46.238 INFO (pid:378449) [plugin] - coc.nvim initialized with node: v18.7.0 after 841ms
2022-09-05T22:17:46.243 WARN (pid:378449) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at t.initStatusBar (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:155873)
    at t.activate (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23099)
2022-09-05T22:21:24.425 INFO (pid:378449) [attach] - receive notification: showInfo []
```

## Describe the bug

`inoremap <Down> <PageDown>` cannot work.

## Reproduce the bug

- Create file `mini.vim` with：

```vim
" $ uname -r
" 5.18.15-arch1-1
" $ cat test.vim
set runtimepath=$VIMRUNTIME
set runtimepath+=~/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release
inoremap <Up> <PageUp>
inoremap <Down> <PageDown>
let g:coc_config_home = '.'
" $ cat coc-settings.json
" $ vi -u test.vim
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

1. `ia`

![Screenshot from 2022-09-05 22-18-19](https://user-images.githubusercontent.com/32936898/188469874-58eb39f4-ab5e-4e16-a23f-f7844ebb4d50.png)

2. `<Down>`, nothing happened.

Expected behaviour: work like `<PageDown>`.

However, in `<C-X><C-F>`'s popup menu, it can work.

**Comment by chemzqm** [comment]
You have to use functions from coc.nvim, see `:h coc-completion-default` for examples
