### ISSUE TITLE
Pending response rejected since connection got disposed

### ISSUE THREAD

**Issue by zaiqiang-dong** [neoclide/coc.nvim#4157]
versions
vim version: NVIM v0.6.1
node version: v16.14.2
coc.nvim version: 0.0.82-824cd1d3 2022-08-31 23:31:31 +0800
coc.nvim directory: /home/zaiqdong/.config/nvim/pluged/coc.nvim
term: st-256color
platform: linux

Log of coc.nvim
2022-09-02T20:59:40.822 ERROR (pid:2888307) [configurations] - Invalid configuration "suggest.detailMaxLength" from coc-clangd, overwrite defaults is fobidden.
2022-09-02T20:59:40.823 ERROR (pid:2888307) [configurations] - Invalid configuration "diagnostic.format" from coc-clangd, overwrite defaults is fobidden.
2022-09-02T20:59:40.871 INFO (pid:2888307) [coc-git] - Looking for git in: git
2022-09-02T20:59:40.947 INFO (pid:2888307) [plugin] - coc.nvim initialized with node: v16.14.2 after 149ms
2022-09-02T20:59:40.965 INFO (pid:2888307) [model-installer] - Using npm from: /usr/local/bin/npm
2022-09-02T20:59:40.967 INFO (pid:2888307) [model-installer] - Get info from http://registry.npm.taobao.org/
2022-09-02T20:59:41.653 INFO (pid:2888307) [model-installer] - Fetched info of coc-java {
'dist.tarball': 'https://registry.npmmirror.com/coc-java/-/coc-java-1.5.5.tgz',
'engines.coc': '>=0.0.79',
version: '1.5.5',
name: 'coc-java'
}
2022-09-02T20:59:41.654 INFO (pid:2888307) [model-installer] - Downloading from https://registry.npmmirror.com/coc-java/-/coc-java-1.5.5.tgz
2022-09-02T20:59:41.986 INFO (pid:2888307) [model-installer] - Download progress 4.3%
2022-09-02T20:59:42.006 INFO (pid:2888307) [model-installer] - Download progress 8.7%
2022-09-02T20:59:42.020 INFO (pid:2888307) [model-installer] - Download progress 13.2%
2022-09-02T20:59:42.026 INFO (pid:2888307) [model-installer] - Download progress 17.7%
2022-09-02T20:59:42.043 INFO (pid:2888307) [model-installer] - Download progress 22.2%
2022-09-02T20:59:42.060 INFO (pid:2888307) [model-installer] - Download progress 26.7%
2022-09-02T20:59:42.077 INFO (pid:2888307) [model-installer] - Download progress 31.2%
2022-09-02T20:59:42.094 INFO (pid:2888307) [model-installer] - Download progress 35.7%
2022-09-02T20:59:42.110 INFO (pid:2888307) [model-installer] - Download progress 40.2%
2022-09-02T20:59:42.127 INFO (pid:2888307) [model-installer] - Download progress 44.7%
2022-09-02T20:59:42.145 INFO (pid:2888307) [model-installer] - Download progress 49.2%
2022-09-02T20:59:42.162 INFO (pid:2888307) [model-installer] - Download progress 53.7%
2022-09-02T20:59:42.179 INFO (pid:2888307) [model-installer] - Download progress 58.2%
2022-09-02T20:59:42.196 INFO (pid:2888307) [model-installer] - Download progress 62.8%
2022-09-02T20:59:42.213 INFO (pid:2888307) [model-installer] - Download progress 67.3%
2022-09-02T20:59:42.231 INFO (pid:2888307) [model-installer] - Download progress 71.8%
2022-09-02T20:59:42.248 INFO (pid:2888307) [model-installer] - Download progress 76.3%
2022-09-02T20:59:42.264 INFO (pid:2888307) [model-installer] - Download progress 80.8%
2022-09-02T20:59:42.281 INFO (pid:2888307) [model-installer] - Download progress 85.3%
2022-09-02T20:59:42.298 INFO (pid:2888307) [model-installer] - Download progress 89.8%
2022-09-02T20:59:42.315 INFO (pid:2888307) [model-installer] - Download progress 94.3%
2022-09-02T20:59:42.332 INFO (pid:2888307) [model-installer] - Download progress 98.8%
2022-09-02T20:59:42.341 INFO (pid:2888307) [model-installer] - Download progress 100.0%
2022-09-02T20:59:42.343 INFO (pid:2888307) [model-download] - Download completed: https://registry.npmmirror.com/coc-java/-/coc-java-1.5.5.tgz
2022-09-02T20:59:42.347 INFO (pid:2888307) [model-download] - Downloaded https://registry.npmmirror.com/coc-java/-/coc-java-1.5.5.tgz => /tmp/nvimS8DyJc/coc-java-AE5aMr
2022-09-02T20:59:42.449 INFO (pid:2888307) [model-installer] - Extension download at /tmp/nvimS8DyJc/coc-java-AE5aMr
2022-09-02T20:59:42.460 INFO (pid:2888307) [model-installer] - Update package.json at /home/zaiqdong/.config/coc/extensions/package.json
2022-09-02T20:59:42.461 INFO (pid:2888307) [model-installer] - Installed extension coc-java@1.5.5 at /home/zaiqdong/.config/coc/extensions/node_modules/coc-java
2022-09-02T20:59:42.590 INFO (pid:2888307) [coc-java] - Using java from /usr/lib/jvm/java-11-openjdk-amd64, version: 11
2022-09-02T20:59:42.612 INFO (pid:2888307) [extension:coc-java] - Starting Java server with: /usr/lib/jvm/java-11-openjdk-amd64/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf-8 -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar /home/zaiqdong/.config/coc/extensions/coc-java-data/server/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -configuration /home/zaiqdong/.config/coc/extensions/coc-java-data/server/config_linux -data /home/zaiqdong/.config/coc/extensions/coc-java-data/jdt_ws_1432982d62a4132e2d40eddeddf15a4e
2022-09-02T20:59:42.615 INFO (pid:2888307) [coc-java] - JDT Language Server starting at /home/zaiqdong/work/data/mona/apps/LINUX/android/packages/services/Car
2022-09-02T20:59:42.615 INFO (pid:2888307) [services] - registered service "java"
2022-09-02T20:59:42.621 INFO (pid:2888307) [language-client-index] - Language server "java" started with 2888438
2022-09-02T20:59:43.386 ERROR (pid:2888307) [server] - unhandledRejection Promise {
xy [Error]: Pending response rejected since connection got disposed
at Object.dispose (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:54:4562)
at Object.dispose (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:219:85794)
at jf.handleConnectionClosed (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:224:10872)
at jf.handleConnectionClosed (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:228:3578)
at t (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:224:10524)
at mq.invoke (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:14460)
at fg.fire (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:15230)
at Re (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:28:6501)
at mq.invoke (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:14460)
at fg.fire (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:15230) {
code: -32097,
data: undefined
}
} xy [Error]: Pending response rejected since connection got disposed
at Object.dispose (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:54:4562)
at Object.dispose (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:219:85794)
at jf.handleConnectionClosed (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:224:10872)
at jf.handleConnectionClosed (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:228:3578)
at t (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:224:10524)
at mq.invoke (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:14460)
at fg.fire (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:15230)
at Re (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:28:6501)
at mq.invoke (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:14460)
at fg.fire (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:15230) {
code: -32097,
data: undefined
}
2022-09-02T20:59:43.391 INFO (pid:2888307) [language-client-index] - Language server "java" started with 2888539
2022-09-02T20:59:43.981 ERROR (pid:2888307) [server] - unhandledRejection Promise {
xy [Error]: Pending response rejected since connection got disposed
at Object.dispose (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:54:4562)
at Object.dispose (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:219:85794)
at jf.handleConnectionClosed (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:224:10872)
at jf.handleConnectionClosed (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:228:3578)
at t (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:224:10524)
at mq.invoke (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:14460)
at fg.fire (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:15230)
at Re (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:28:6501)
at mq.invoke (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:14460)
at fg.fire (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:15230) {
code: -32097,
data: undefined
},
dispose: [Function (anonymous)]
} xy [Error]: Pending response rejected since connection got disposed
at Object.dispose (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:54:4562)
at Object.dispose (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:219:85794)
at jf.handleConnectionClosed (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:224:10872)
at jf.handleConnectionClosed (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:228:3578)
at t (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:224:10524)
at mq.invoke (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:14460)
at fg.fire (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:15230)
at Re (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:28:6501)
at mq.invoke (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:14460)
at fg.fire (/home/zaiqdong/.config/nvim/pluged/coc.nvim/build/index.js:27:15230) {
code: -32097,
data: undefined
}
2022-09-02T20:59:43.986 INFO (pid:2888307) [language-client-index] - Language server "java" started with 2888582
2022-09-02T20:59:44.589 INFO (pid:2888307) [language-client-index] - Language server "java" started with 2888666
2022-09-02T21:01:41.890 INFO (pid:2888307) [attach] - receive notification: showInfo []

**Comment by chemzqm** [comment]
Try different java version
