### ISSUE TITLE
user supplied settings are not part of `initialize` JSON RPC call but only later sent

### ISSUE THREAD

**Issue by christianparpart** [neoclide/coc.nvim#4163]
## versions

vim version: NVIM v0.8.0-dev-1007-gdb2e5f46f5
node version: v14.18.2
coc.nvim version: 0.0.82-824cd1d3 2022-08-31 23:31:31 +0800
coc.nvim directory: /home/christianparpart/.local/share/nvim/site/pack/packer/start/coc.nvim
term: contour
platform: linux

## Log of coc.nvim

2022-09-07T16:42:44.686 WARN (pid:663606) [attach] - Plugin not ready when received "highlight" []
2022-09-07T16:42:44.712 ERROR (pid:663606) [configurations] - Invalid configuration "suggest.detailMaxLength" from coc-clangd, overwrite defaults is fobidden.
2022-09-07T16:42:44.712 ERROR (pid:663606) [configurations] - Invalid configuration "diagnostic.format" from coc-clangd, overwrite defaults is fobidden.
2022-09-07T16:42:44.741 INFO (pid:663606) [services] - registered service "languageserver.solidity"
2022-09-07T16:42:44.743 INFO (pid:663606) [services] - solidity state change: stopped => starting
2022-09-07T16:42:44.753 INFO (pid:663606) [services] - registered service "highlight"
2022-09-07T16:42:44.763 INFO (pid:663606) [plugin] - coc.nvim initialized with node: v14.18.2 after 70ms
2022-09-07T16:42:44.772 INFO (pid:663606) [language-client-index] - Language server "languageserver.solidity" started with 663647
2022-09-07T16:42:44.829 INFO (pid:663606) [services] - solidity state change: starting => running
2022-09-07T16:42:44.834 INFO (pid:663606) [services] - service languageserver.solidity started
2022-09-07T16:42:44.851 WARN (pid:663606) [language-client-client] - disableCompletion in the client options is deprecated. use disabledFeatures instead. 
    at new _D (/home/christianparpart/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:219:86877)
    at new jf (/home/christianparpart/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:228:3061)
2022-09-07T16:42:44.851 WARN (pid:663606) [language-client-client] - disableDiagnostics in the client options is deprecated. use disabledFeatures instead. 
    at new _D (/home/christianparpart/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:219:86877)
    at new jf (/home/christianparpart/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:228:3061)
2022-09-07T16:42:44.852 INFO (pid:663606) [services] - registered service "clangd"
2022-09-07T16:42:45.145 ERROR (pid:663606) [extension:coc-clangd] - Can't glibc version from ldd --version output: ldd (GNU libc) 2.35
2022-09-07T16:42:45.164 INFO (pid:663606) [extension:coc-clangd] - clangd  --version output:  clangd version 14.0.5 (Fedora 14.0.5-1.fc36)
Features: linux
Platform: x86_64-unknown-linux-gnu; target=x86_64-redhat-linux-gnu

2022-09-07T16:42:45.166 INFO (pid:663606) [extension:coc-clangd] - Checking for clangd update: available= 14.0.3  installed= 14.0.5
2022-09-07T16:52:08.201 INFO (pid:663606) [attach] - receive notification: showInfo []

## Describe the bug

The JSON RPC call `initialize` does allow passing the user supplied settings object as parameter. When you provide custom settings they are NOT being sent as part of the `initialize` request but only later when initialization is done there will be a `didChangeConfiguration` JSON RPC call. While this may work, it will potentially change the semantics of the underlying LSP to communicate with. Just imagine the user provides custom options to not do something that the LSP server would do otherwise. Now the server initializes, no custom settings passed (even though the user supplied them), and the LSP server therefore does what the user explicitly stated not to do. Only after that a `didChangeConfiguration` will be sent. That's actually too late.

## Reproduce the bug

Just look at the I/O trace for your favour LSP server and you will notice that the `initialize` call does not carry the custom settings. But a secondary call to `didChangeCofiguration` will do (too late though).

## post-notes from me

I know that the language server protocol does allow passing custom settings in both ways. But if the settings are known ahead of time, they have never factually changed. And that will alter the meaning on the server side. I hope my point is clear enough. :)

**Comment by chemzqm** [comment]
> The JSON RPC call initialize does allow passing the user supplied settings object as parameter.

Do you mean `initializationOptions` on `initialize`?
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize
It's not configuration.

**Comment by christianparpart** [comment]
> Do you mean `initializationOptions` on `initialize`?

Pardon me, but I could not quite find a more detailed explanation of those two options in the spec. If they're different. what exactly is the difference then? `initializationOptions` is "User provided initialization options", whereas in `didChangeConfiguration` they way "The actual changed settings". It is interesting to see that what I provide in coc.nvim's lsp config, it's blindingly passed over. I may very well misinterpret here something, but how does the user then provide custom configuration to the LSP server? To me it did look like the same settings object (for initialie's sub-param  as well as didChangeConfiguration's params). If they differ, I'd like to understand the HOW then. Also, if they differ, how do you mutate the one at initializationOptions then in the context of coc.nvim?

**Comment by chemzqm** [comment]
initializationOptions only send on server initialization, no mutation

**Comment by christianparpart** [comment]
> initializationOptions only send on server initialization, no mutation

my question was rather what that field than actually means, semantically. I assumed they're both the same.
