### ISSUE TITLE
Custom popup window highlight not working anymore and method not found

### ISSUE THREAD

**Issue by sebiwi** [neoclide/coc.nvim#4167]
## Result from CocInfo

```
  ## versions

  vim version: VIM - Vi IMproved 9.0 9000350
  node version: v16.13.1
  coc.nvim version: 0.0.82-b9c208ef 2022-09-07 15:41:25 +0800
  coc.nvim directory: /Users/stuff/vim/plugged/coc.nvim
  term: tmux
  platform: darwin

  ## Log of coc.nvim

  2022-09-08T16:18:27.255 INFO (pid:24000) [services] - registered service "languageserver.terraform"
  2022-09-08T16:18:27.258 INFO (pid:24000) [services] - terraform state change: stopped => starting
  2022-09-08T16:18:27.258 INFO (pid:24000) [services] - registered service "languageserver.golang"
  2022-09-08T16:18:27.265 INFO (pid:24000) [plugin] - coc.nvim initialized with node: v16.13.1 after 45ms
  2022-09-08T16:18:27.270 INFO (pid:24000) [language-client-index] - Language server "languageserver.terraform" started with 24002
  2022-09-08T16:18:28.149 INFO (pid:24000) [attach] - receive notification: highlight []
  2022-09-08T16:18:29.310 INFO (pid:24000) [services] - terraform state change: starting => running
  2022-09-08T16:18:29.312 INFO (pid:24000) [services] - service languageserver.terraform started
  2022-09-08T16:18:30.545 INFO (pid:24000) [attach] - receive notification: startCompletion [
    {
      word: 're',
      bufnr: 1,
      col: 0,
      disabled: [],
      filepath: 'redacted',
      indentkeys: '',
      blacklist: [],
      line: 're',
      filetype: 'terraform',
      linenr: 912,
      input: 're',
      colnr: 3,
      changedtick: 6
    }
  ]
  2022-09-08T16:18:33.349 INFO (pid:24000) [attach] - receive notification: showSignatureHelp []
  2022-09-08T16:18:33.379 ERROR (pid:24000) [node-client] - Error on notification "showSignatureHelp": method not found Error
      at LH.echoError (/Users/sebiwi/stuff/dotfiles/vim/plugged/coc.nvim/build/index.js:26:1869)
      at LH.<anonymous> (/Users/sebiwi/stuff/dotfiles/vim/plugged/coc.nvim/build/index.js:293:20970)
  2022-09-08T16:18:33.379 ERROR (pid:24000) [attach] - xy [Error]: method not found
      at je (/Users/sebiwi/stuff/dotfiles/vim/plugged/coc.nvim/build/index.js:29:233)
      at Wi (/Users/sebiwi/stuff/dotfiles/vim/plugged/coc.nvim/build/index.js:28:6872)
      at Immediate.<anonymous> (/Users/sebiwi/stuff/dotfiles/vim/plugged/coc.nvim/build/index.js:28:6719)
      at processImmediate (node:internal/timers:464:21) {
    code: -32601,
    data: 'textDocument/signatureHelp'
  }
  2022-09-08T16:19:40.572 WARN (pid:24000) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
  2022-09-08T16:19:42.173 INFO (pid:24000) [snippets-session] - Unable to find changed placeholder, cancel snippet session
  2022-09-08T16:19:42.211 INFO (pid:24000) [attach] - receive notification: highlight []
  2022-09-08T16:19:44.507 INFO (pid:24000) [attach] - receive notification: showInfo []
```
## Describe the bug

After upgrading coc.nvim to version 0.0.82-b9c208ef, the custom popup window highlight is not working anymore. The "incsearch" feature within the popup window is not visible anymore. I didn't change any highlight settings.

This may be related to terraform-lsp but Imalso get the following error message each time I try autocompleting:

`[coc.nvim] Error on notification "showSignatureHelp": method not found`

## Reproduce the bug

- Create file `mini.vim` (basic conf plus example coc configuration from the readme) with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  " Default coc.nvim configuration from the README.md file
  " Some servers have issues with backup files, see #649.
  set nobackup
  set nowritebackup

  " Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
  " delays and poor user experience.
  set updatetime=300

  " Always show the signcolumn, otherwise it would shift the text each time
  " diagnostics appear/become resolved.
  set signcolumn=yes

  " Use tab for trigger completion with characters ahead and navigate.
  " NOTE: There's always complete item selected by default, you may want to enable
  " no select by `"suggest.noselect": true` in your configuration file.
  " NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
  " other plugin before putting this into your config.
  inoremap <silent><expr> <TAB>
        \ coc#pum#visible() ? coc#pum#next(1) :
        \ CheckBackspace() ? "\<Tab>" :
        \ coc#refresh()
  inoremap <expr><S-TAB> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

  " Make <CR> to accept selected completion item or notify coc.nvim to format
  " <C-g>u breaks current undo, please make your own choice.
  inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                                \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

  function! CheckBackspace() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
  endfunction

  " Use <c-space> to trigger completion.
  if has('nvim')
    inoremap <silent><expr> <c-space> coc#refresh()
  else
    inoremap <silent><expr> <c-@> coc#refresh()
  endif

  " Use `[g` and `]g` to navigate diagnostics
  " Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
  nmap <silent> [g <Plug>(coc-diagnostic-prev)
  nmap <silent> ]g <Plug>(coc-diagnostic-next)

  " GoTo code navigation.
  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)

  " Use K to show documentation in preview window.
  nnoremap <silent> K :call ShowDocumentation()<CR>

  function! ShowDocumentation()
    if CocAction('hasProvider', 'hover')
      call CocActionAsync('doHover')
    else
      call feedkeys('K', 'in')
    endif
  endfunction

  " Highlight the symbol and its references when holding the cursor.
  autocmd CursorHold * silent call CocActionAsync('highlight')

  " Symbol renaming.
  nmap <leader>rn <Plug>(coc-rename)

  " Formatting selected code.
  xmap <leader>f  <Plug>(coc-format-selected)
  nmap <leader>f  <Plug>(coc-format-selected)

  augroup mygroup
    autocmd!
    " Setup formatexpr specified filetype(s).
    autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
    " Update signature help on jump placeholder.
    autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
  augroup end

  " Applying codeAction to the selected region.
  " Example: `<leader>aap` for current paragraph
  xmap <leader>a  <Plug>(coc-codeaction-selected)
  nmap <leader>a  <Plug>(coc-codeaction-selected)

  " Remap keys for applying codeAction to the current buffer.
  nmap <leader>ac  <Plug>(coc-codeaction)
  " Apply AutoFix to problem on the current line.
  nmap <leader>qf  <Plug>(coc-fix-current)

  " Run the Code Lens action on the current line.
  nmap <leader>cl  <Plug>(coc-codelens-action)

  " Map function and class text objects
  " NOTE: Requires 'textDocument.documentSymbol' support from the language server.
  xmap if <Plug>(coc-funcobj-i)
  omap if <Plug>(coc-funcobj-i)
  xmap af <Plug>(coc-funcobj-a)
  omap af <Plug>(coc-funcobj-a)
  xmap ic <Plug>(coc-classobj-i)
  omap ic <Plug>(coc-classobj-i)
  xmap ac <Plug>(coc-classobj-a)
  omap ac <Plug>(coc-classobj-a)

  " Remap <C-f> and <C-b> for scroll float windows/popups.
  if has('nvim-0.4.0') || has('patch-8.2.0750')
    nnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
    nnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
    inoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : "\<Right>"
    inoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : "\<Left>"
    vnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
    vnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
  endif

  " Use CTRL-S for selections ranges.
  " Requires 'textDocument/selectionRange' support of language server.
  nmap <silent> <C-s> <Plug>(coc-range-select)
  xmap <silent> <C-s> <Plug>(coc-range-select)

  " Add `:Format` command to format current buffer.
  command! -nargs=0 Format :call CocActionAsync('format')

  " Add `:Fold` command to fold current buffer.
  command! -nargs=? Fold :call     CocAction('fold', <f-args>)

  " Add `:OR` command for organize imports of the current buffer.
  command! -nargs=0 OR   :call     CocActionAsync('runCommand', 'editor.action.organizeImport')

  " Add (Neo)Vim's native statusline support.
  " NOTE: Please see `:h coc-status` for integrations with external plugins that
  " provide custom statusline: lightline.vim, vim-airline.
  set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

  " Mappings for CoCList
  " Show all diagnostics.
  nnoremap <silent><nowait> <space>a  :<C-u>CocList diagnostics<cr>
  " Manage extensions.
  nnoremap <silent><nowait> <space>e  :<C-u>CocList extensions<cr>
  " Show commands.
  nnoremap <silent><nowait> <space>c  :<C-u>CocList commands<cr>
  " Find symbol of current document.
  nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
  " Search workspace symbols.
  nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>
  " Do default action for next item.
  nnoremap <silent><nowait> <space>j  :<C-u>CocNext<CR>
  " Do default action for previous item.
  nnoremap <silent><nowait> <space>k  :<C-u>CocPrev<CR>
  " Resume latest coc list.
  nnoremap <silent><nowait> <space>p  :<C-u>CocListResume<CR>


  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Trigger autocompletion with C-space
- Autocomplete with any of the options

## Screenshots (optional)
![Screenshot 2022-09-08 at 16 26 08](https://user-images.githubusercontent.com/1782142/189148635-3fff2cc4-e43d-4d07-a62c-3eb2cb53839f.png)

![Screenshot 2022-09-08 at 16 26 19](https://user-images.githubusercontent.com/1782142/189148664-94213648-624d-48f9-b0bc-b90948cb3055.png)

**Comment by chemzqm** [comment]
Try `:verbose hi CocPumSearch`

**Comment by chemzqm** [comment]
> [coc.nvim] Error on notification "showSignatureHelp": method not found

Should be bug with your LS.

**Comment by sebiwi** [comment]
Thanks @chemzqm, I found the settings regarding the highlighting and fixed it.

You're also right about the other error being an LS problem, I'll try to get that fixed out with them.

Thanks for your help!
