### ISSUE TITLE
Different behaviour between coc's completion and vim's completion

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc.nvim#4174]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.2
node version: v18.8.0
coc.nvim version: 0.0.82-b797c032 2022-09-04 21:59:01 +0800
coc.nvim directory: /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release
term: tmux
platform: linux

## Log of coc.nvim

2022-09-09T22:23:02.577 ERROR (pid:914858) [configurations] - Invalid configuration "suggest.detailMaxLength" from coc-clangd, overwrite defaults is fobidden.
2022-09-09T22:23:02.577 ERROR (pid:914858) [configurations] - Invalid configuration "diagnostic.format" from coc-clangd, overwrite defaults is fobidden.
2022-09-09T22:23:03.034 INFO (pid:914858) [coc-git] - Looking for git in: git
2022-09-09T22:23:03.048 INFO (pid:914858) [services] - registered service "highlight"
2022-09-09T22:23:03.190 INFO (pid:914858) [coc-tabnine] - Using tabnine from /home/wzy/.config/coc/extensions/coc-tabnine-data/binaries/4.4.139/x86_64-unknown-linux-musl/TabNine
2022-09-09T22:23:03.285 INFO (pid:914858) [plugin] - coc.nvim initialized with node: v18.8.0 after 739ms
2022-09-09T22:23:03.289 WARN (pid:914858) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at t.initStatusBar (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:155873)
    at t.activate (/home/wzy/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23099)
2022-09-09T22:24:11.111 INFO (pid:914858) [attach] - receive notification: showInfo []
```

## Describe the bug

different behaviour between coc's completion and vim's completion

## Reproduce the bug

```vim
" $ uname -r
" 5.19.7-arch1-1
" $ cat test.vim
set runtimepath=$VIMRUNTIME
set runtimepath+=~/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release
let g:coc_config_home = '.'
colorscheme shine
" $ cat coc-settings.json
" $ vi -u test.vim
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

1. press `<C-X><C-F>`:

![Screenshot from 2022-09-09 22-23-12](https://user-images.githubusercontent.com/32936898/189373218-5c72af94-3d67-4906-8b52-63b35f7c7a7e.png)

2. press `/`
![Screenshot from 2022-09-09 22-22-57](https://user-images.githubusercontent.com/32936898/189373264-fea60d71-5f16-4b17-a210-55045d0069da.png)

## Expected Result

When press `/`, should be same with `<C-X><C-F>`
![Screenshot from 2022-09-09 22-26-24](https://user-images.githubusercontent.com/32936898/189373287-3fca4e1f-cbfd-4537-bb6f-5b927ce75ed1.png)

**Comment by chemzqm** [comment]
You have to use vim's completion or create a source yourself if you need file name completion from cwd

**Comment by Freed-Wu** [comment]
No, :smile: my meaning is the expected behaviour is the first result of completion should be inputted automatically, just like vim's default behaviour. That is when user press `/`, the first completion is `/bin`, the current line should be `/bin` not original `/`

**Comment by chemzqm** [comment]
> the first result of completion should be inputted automatically

That's not possible for auto completion.

**Comment by Freed-Wu** [comment]
It is not possible for coc.nvim? `<C-X><C-F>` can do it. So I feel weird :smile:

**Comment by chemzqm** [comment]
Yes, coc.nvim provide auto completion only.
