### ISSUE TITLE
In case you didn't know neovim has switched to custom popup menu from 0.0.82

### ISSUE THREAD

**Issue by MathiasKandelborg** [neoclide/coc.nvim#4187]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.2
node version: v16.15.0
coc.nvim version: 0.0.82-cea9dc26 2022-09-13 00:19:54 +0800
coc.nvim directory: /home/mathias/.config/nvim/plugged/coc.nvim
term: st-256color
platform: linux

## Log of coc.nvim

2022-09-12T22:39:26.456 WARN (pid:167674) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at new t.Actions (/home/mathias/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:8301)
    at Object.t.activate (/home/mathias/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:15288)
2022-09-12T22:39:26.569 INFO (pid:167674) [coc-git] - Looking for git in: git
2022-09-12T22:39:26.726 INFO (pid:167674) [plugin] - coc.nvim initialized with node: v16.15.0 after 441ms
2022-09-12T22:39:26.765 INFO (pid:167674) [services] - registered service "go"
2022-09-12T22:39:26.766 INFO (pid:167674) [services] - LanguageClient gopls state change: stopped => starting
2022-09-12T22:39:26.786 INFO (pid:167674) [core-watchman] - watchman watching project: /home/mathias/Programming/web/go/server-mit-hjerte
2022-09-12T22:39:26.872 INFO (pid:167674) [services] - LanguageClient gopls state change: starting => running
2022-09-12T22:39:26.878 INFO (pid:167674) [services] - service go started
2022-09-12T22:39:27.652 INFO (pid:167674) [attach] - receive notification: highlight []
2022-09-12T22:39:52.064 INFO (pid:167674) [attach] - receive notification: showInfo []
```

## Describe the bug

A noisy popup every time I start neovim.

## Reproduce the bug

1. Open vim

----

Listen, it completely disrupts my workflow and it gets in the way. I have to wait several seconds before I can start writing. How do I disable it? I don't need to change any settings. Just get it out of my editor, it's so invasive and makes absolutely no sense. I don't care for your justifications, if it's that big of a deal, you make a new version, otherwise you don't need to bother me every time I freaking open my editor. Absolutely the worst experience I've ever had surrounding any OSS project I've EVER used. Do you have a paid plan or something? Why are you getting in my face?

**Comment by MathiasKandelborg** [comment]
This is not a troll, but I'm extremely annoyed at the 50th popup this night. I could probably have a better tone.

You could also not employ 2000's era spam tactics to give trivial information.

**Comment by akoerner** [comment]
Is there any way to disable this warning pop-up? It is not clear from the documentation.

**Comment by fannheyward** [comment]
@akoerner what's your coc configutations?

**Comment by chemzqm** [comment]
@akoerner Update coc.nvim to latest release, that notification is removed.

**Comment by akoerner1** [comment]
@chemzqm Thanks for your response.  Updating again solved this issue.

**Comment by akoerner1** [comment]
@fannheyward Thanks for the response.  Updating again solved the issue.
