### ISSUE TITLE
Help with suggested functions on MPLS

### ISSUE THREAD

**Issue by esn89** [neoclide/coc.nvim#419]
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
```
## versions

vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.52
term: xterm-kitty
platform: darwin

## Error messages
```

**Describe the bug**
I am using MPLS now and I think I got it working.  In my autocomplete, I see entries that end in [LS].  This means that the language server is working, right?

Second, I have seen a strange behavior.  In my code when I make a list:

`list2 = [1, 2, 3]`
and I type:    
`list2.`, I expect an autocomplete list to pop up showing some operations I can do such as:  append(), delete(), 
https://i.imgur.com/ILdOJwE.png

However, when I do `import math`

and I type:
`math.`, I *DO* see operations like cosx(), tan(), cos() all ending with [LS]:
https://i.imgur.com/swPqGO4.png

Any ideas why this is?

My :CocConfig is as follows:
```
		"MPLS": {
		      "command": "dotnet",
		      "args": ["exec", "/Users/esn89/python-language-server/output/bin/Debug/Microsoft.Python.LanguageServer.dll"],
		      "filetypes": ["python"],
		      "initializationOptions": {
			      "interpreter": {
				      "properties": {
					      "InterpreterPath": "/usr/local/bin/python",
					      "UseDefaultDatabase": true,
					      "Version": "2.7.15"
				      }
			      }
		      }
		}
```

**To Reproduce**

Build MPLS release branch as per these instructions:

https://github.com/Microsoft/python-language-server/blob/master/CONTRIBUTING.md

**Screenshots**

See above.

**Bonus** 
Here is my :CocOpenLog
```
2019-02-10T08:57:00.502 INFO (pid:1665) [plugin] - coc initialized with node: v8.9.0
2019-02-10T08:58:01.015 INFO (pid:1913) [services] - MPLS state change: stopped => starting
2019-02-10T08:58:01.168 INFO (pid:1913) [plugin] - coc initialized with node: v8.9.0
2019-02-10T08:58:14.097 INFO (pid:1913) [services] - MPLS state change: starting => running
2019-02-10T08:58:14.098 INFO (pid:1913) [services] - service languageserver.MPLS started
2019-02-10T08:58:38.158 DEBUG (pid:2156) [workspace] - buffer created 1
2019-02-10T08:58:38.160 DEBUG (pid:2156) [events] - Event: BufEnter [ 1 ]
2019-02-10T08:58:38.181 DEBUG (pid:2156) [events] - Event: BufWinEnter [ 1, 1000 ]
2019-02-10T08:58:38.186 DEBUG (pid:2156) [services] - starting service: MPLS
2019-02-10T08:58:38.187 INFO (pid:2156) [services] - MPLS state change: stopped => starting
2019-02-10T08:58:38.313 INFO (pid:2156) [plugin] - coc initialized with node: v8.9.0
2019-02-10T08:58:38.638 DEBUG (pid:2156) [events] - Event: CursorHold [ 1 ]
2019-02-10T08:58:47.350 INFO (pid:2156) [services] - MPLS state change: starting => running
2019-02-10T08:58:47.351 DEBUG (pid:2156) [languages] - created service source languageserver.MPLS
2019-02-10T08:58:47.352 INFO (pid:2156) [services] - service languageserver.MPLS started
2019-02-10T09:17:38.375 DEBUG (pid:2156) [events] - Event: FocusGained []
2019-02-10T09:17:38.724 DEBUG (pid:2156) [events] - Event: CursorMoved [ 1 ]
2019-02-10T09:17:39.216 DEBUG (pid:2156) [events] - Event: CursorHold [ 1 ]
2019-02-10T09:17:41.119 DEBUG (pid:2156) [events] - Event: BufWinLeave [ 1, 1000 ]
2019-02-10T09:17:41.119 DEBUG (pid:2156) [events] - Event: BufUnload [ 1 ]
2019-02-10T09:17:41.120 DEBUG (pid:2156) [workspace] - buffer unload 1
```

**Comment by chemzqm** [comment]
I can't start with `"UseDefaultDatabase": true,`, so I changed to 
`"DatabasePath": "/Users/chemzqm/.vscode/extensions/ms-python.python-2019.1.0/languageServer.0.1.78",`, it works and doesn't have the problem you have.

**Comment by esn89** [comment]
Thanks.  By the way, what is the DatabasePath?  And what should I be passing in?

It looks like you have vscode installed. .... I do not haha

**Comment by chemzqm** [comment]
You can change it to any filepath which parent folder is existed.

**Comment by esn89** [comment]
Thanks @chemzqm 

I am trying to understand this though, so DatabasePath is a binary which I need?   Cuz my parent folder which contains all this is in:

`/Users/esn89/Documents/Projects/python-language-server`
and the languageserver .dll is here:
`/Users/esn89/Documents/Projects/python-language-server/output/bin/Debug/Microsoft.Python.LanguageServer.dll`

I would like to know why I cannot find something similar to yours:   `languageServer.0.1.78`

**Comment by chemzqm** [comment]
It's just directory that contains data, any exists directory would be fine.

**Comment by esn89** [comment]
---small update ---

I was wondering if this could be a potential problem.  It says that the trigger completion is the 'p' key.  Or am I misinterpreting?
```
2019-02-11T10:35:41.760 DEBUG (pid:2912) [events] - Event: CursorMovedI []
2019-02-11T10:35:41.760 DEBUG (pid:2912) [events] - Event: TextChangedI [ 1 ]
2019-02-11T10:35:41.803 DEBUG (pid:2912) [completion] - trigger completion with { word: 'p',
  bufnr: 1,
  col: 0,
  synname: '',
  filepath: '/Users/esn89/testplot.py',
  line: 'p',
  filetype: 'python',
  linenr: 8,
  input: 'p',
  colnr: 2,
  triggerCharacter: 'p' }
2019-02-11T10:35:41.806 DEBUG (pid:2912) [completion-complete] - Complete source "file" takes 1ms
2019-02-11T10:35:41.806 DEBUG (pid:2912) [completion-complete] - Complete source "around" takes 0ms
```

**Comment by esn89** [comment]
Update:   

I tried it with just an existing directory, however, it still does not work.
Now
`import math`
`math.  `  is broken, no suggestions.

I even made sure to use the same version of MPLS as you: `HEAD detached at 2019.1`

**Comment by chemzqm** [comment]
> It says that the trigger completion is the 'p' key. Or am I misinterpreting?

Because you type `p` which trigger completion, so what's the problem?

**Comment by esn89** [comment]
I am sorry sir for not being clear.

Let me show you an image, hopefully it is more clear:
https://i.imgur.com/QIUGUvw.png

I have 'plt.' and I am hoping that the MPLS will show me a list of possible functions to complete it with.  But it does not

**Comment by chemzqm** [comment]
Use output channel https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel to get the server communication.

**Comment by chemzqm** [comment]
Seems matplotlib is a big library, it need sometime to parse it.

**Comment by esn89** [comment]
Ah ha, I have ran this:
:CocCommand workspace.showOutput

and this is the only thing it says:
```
Microsoft Python Language Server version 1.0.0.0
Initializing for /usr/local/bin/python2
```

And nothing else.

**Comment by chemzqm** [comment]
You need to change `trace.server` to `verbose`

**Comment by esn89** [comment]
Thank you.  I changed it and now I have this:

```
[Trace - 11:06:41] Sending request 'initialize - (0)'.
Params: {
    "processId": 9455,
    "rootPath": "/Users/esn89",
    "rootUri": "file:///Users/esn89",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional"
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    }
                }
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                }
            },
            "codeAction": {
                "dynamicRegistration": true,
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                }
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true
            },
            "documentLink": {
                "dynamicRegistration": true
            },
            "typeDefinition": {
                "dynamicRegistration": true
            },
            "implementation": {
                "dynamicRegistration": true
            },
            "declaration": {
                "dynamicRegistration": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            }
        }
    },
    "initializationOptions": {
        "interpreter": {
            "properties": {
                "InterpreterPath": "/usr/local/bin/python2",
                "DatabasePath": "/Users/esn89/Documents/Projects/python-language-server",
                "Version": "2.7.15"
            }
        }
    },
    "trace": "verbose",
    "workspaceFolders": null
}



[Trace - 11:06:46] Received notification 'window/logMessage'.
Params: {
    "type": 0,
    "message": "Microsoft Python Language Server version 1.0.0.0"
}


Microsoft Python Language Server version 1.0.0.0
[Trace - 11:06:46] Received notification 'window/logMessage'.
Params: {
    "type": 0,
    "message": "Initializing for /usr/local/bin/python2"
}


Initializing for /usr/local/bin/python2
```

**Comment by chemzqm** [comment]
<img width="488" alt="screen shot 2019-02-11 at 6 19 08 pm" src="https://user-images.githubusercontent.com/251450/52557180-a3505b00-2e29-11e9-808e-127af1e28b09.png">
It doesn't work even with VSCode.

**Comment by esn89** [comment]
I see.  This is concerning then, because it does not seem to work with simple libraries like `import math` and with lists in python too.

Is this the same for you?

**Comment by chemzqm** [comment]
`import math` works for me.

**Comment by esn89** [comment]
>:/

This sucks.  Can I have your mpls :CocConfig?  and the init.vim config relating to Coc.nvim please?

**Comment by chemzqm** [comment]
It gives me some completion suggest, but not complete, I changed to use same initialize configuration as VSCode:
``` json
      "initializationOptions": {
        "interpreter": {
          "properties": {
            "InterpreterPath": "/usr/local/bin/python3",
            "Version": "3.7",
            "DatabasePath": "/Users/chemzqm/.vscode/extensions/ms-python.python-2019.1.0/languageServer.0.1.99"
          }
        },
        "displayOptions": {
          "preferredFormat": "markdown",
          "trimDocumentationLines": false,
          "maxDocumentationLineLength": 0,
          "trimDocumentationText": false,
          "maxDocumentationTextLength": 0
        },
        "searchPaths": [
          "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip;/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7;/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload;/Users/chemzqm/Library/Python/3.7/lib/python/site-packages;/usr/local/lib/python3.7/site-packages;/usr/local/lib/python3.7/site-packages/pylint-2.3.0-py3.7.egg;",
          "/usr/local/bin"
        ],
        "excludeFiles": [
          "**/Lib/**",
          "**/site-packages/**",
          "**/node_modules",
          "**/bower_components",
          "**/.git",
          "**/.svn",
          "**/.hg",
          "**/CVS",
          "**/.DS_Store",
          "**/.git/objects/**",
          "**/.git/subtree-cache/**",
          "**/node_modules/**",
          ".vscode/*.py",
          "**/site-packages/**/*.py"
        ],
        "testEnvironment": false,
        "analysisUpdates": true,
        "traceLogging": true,
        "asyncStartup": true
      }
``` 
and then I have same complete items as VSCode.

**Comment by chemzqm** [comment]
I get it work by:
```
    "MPLS": {
      "command": "dotnet",
      "args": [
        "exec",
        "/Users/chemzqm/lib/python-language-server/output/bin/Debug/Microsoft.Python.LanguageServer.dll"
      ],
      "trace.server": "verbose",
      "filetypes": ["python"],
      "initializationOptions": {
        "interpreter": {
          "properties": {
            "InterpreterPath": "/usr/local/bin/python3",
            "Version": "3.7",
            "DatabasePath": "/Users/chemzqm/lib/python-language-server/output/bin/Debug"
          }
        },
        "searchPaths": [
          "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python37.zip;/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7;/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload;/Users/chemzqm/Library/Python/3.7/lib/python/site-packages;/usr/local/lib/python3.7/site-packages;/usr/local/lib/python3.7/site-packages/pylint-2.3.0-py3.7.egg;",
          "/usr/local/bin"
        ],
        "testEnvironment": false,
        "analysisUpdates": true,
        "traceLogging": true,
        "asyncStartup": true
      }
    }
```
Notice the `DatabasePath` here.

**Comment by esn89** [comment]
Thank you.

So I have set it up similar to yours:

```
		"MPLS": {
		      "command": "dotnet",
		      "args": ["exec", "/Users/esn89/Documents/Projects/python-language-server/output/bin/Debug/Microsoft.Python.LanguageServer.dll"],
		      "filetypes": ["python"],
		      "trace.server": "verbose",
		      "initializationOptions": {
			      "interpreter": {
				      "properties": {
					      "InterpreterPath": "/usr/local/bin/python3",
					      "DatabasePath": "/Users/esn89/Documents/Projects/python-language-server/output/bin/Debug",
					      "Version": "3.7.2"
				      }
			      },
			      "displayOptions": {
		 	      "preferredFormat": "markdown",
			      "trimDocumentationLines": false,
			      "maxDocumentationLineLength": 0,
			      "trimDocumentationText": false,
			      "maxDocumentationTextLength": 0
        		},
			"searchPaths": [
			  "/usr/local/bin"
			],
			      "testEnvironment": false,
			      "analysisUpdates": true,
			      "traceLogging": true,
			      "asyncStartup": true
		      }
		}
```
But received this in :CocOpenLog
```
2019-02-11T13:07:21.809 DEBUG (pid:19655) [workspace] - buffer unload 1
2019-02-11T13:07:21.810 ERROR (pid:19655) [server] - unhandledRejection  Promise {
  <rejected> Error: request nvim_buf_set_lines - Vim:E523: Not allowed here
    at events_1.EventEmitter.constructor.(anonymous function).Promise.transport.request (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:33:28)
    at Transport.parseMessage (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:134:17)
    at DecodeStream.events_1.EventEmitter.constructor.decodeStream.on (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:43:18)
    at emitOne (events.js:116:13)
    at DecodeStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at DecodeStream.Readable.push (_stream_readable.js:208:10)
    at DecodeStream.Transform.push (_stream_transform.js:147:32)
    at DecodeBuffer.__dirname.DecodeStream.decoder.push (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/node_modules/msgpack-lite/lib/decode-stream.js:24:12) } Error: request nvim_buf_set_lines - Vim:E523: Not allowed here
    at events_1.EventEmitter.constructor.(anonymous function).Promise.transport.request (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:33:28)
    at Transport.parseMessage (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:134:17)
    at DecodeStream.events_1.EventEmitter.constructor.decodeStream.on (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:43:18)
    at emitOne (events.js:116:13)
    at DecodeStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at DecodeStream.Readable.push (_stream_readable.js:208:10)
    at DecodeStream.Transform.push (_stream_transform.js:147:32)
    at DecodeBuffer.__dirname.DecodeStream.decoder.push (/snapshot/coc.nvim/node_modules/@chemzqm/neovim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)
2019-02-11T13:07:21.885 DEBUG (pid:19655) [events] - Event: BufEnter [ 2 ]
```

**Comment by chemzqm** [comment]
I can't reproduce the error.

**Comment by esn89** [comment]
Okay, I reinstalled everything and the error has gone away.

I just want to confirm with you, for MPLS, if I want to see the suggestions, i need to press C-x, C-o correct?  And the suggestions will not show up automatically if I do not press it?

**Comment by chemzqm** [comment]
> i need to press C-x, C-o correct? And the suggestions will not show up automatically if I do not press it?
No, `<C-x><C-o>` trigger omni completion, it's not related to coc.nvim.

**Comment by vn-ki** [comment]
Butting in this issue because it is about MPLS. I am using the config @chemzqm posted above. I can confirm that config solves the problem mentioned in this issue (i.e. not completing `list.<stuff>`)

But I'm not able to get diagnosis from mpls. Any thoughts @chemzqm .

**Comment by esn89** [comment]
Nice, I am still getting the MPLS timeout after 500ms despite trying again :/

**Comment by vn-ki** [comment]
@esn89 Try setting your `searchPaths` as the result of `';'.join(sys.path)`(execute this in the interpreter).

**Comment by esn89** [comment]
WOW!!!  @vn-ki  Thanks a million.  I have it working now thanks to you.

I can also help you confirm that by using your sys.path for searchPaths and using @chemzqm's config, I am not getting diagnostics as well.  For example 2 lines after function declaration, and spacing issues and whitespaces around the '=' when I do things like:   variable1="foo".

**Comment by chemzqm** [comment]
Diagnostics need settings passed to language server, which're disabled by default, that's also how it works with VSCode.

**Comment by esn89** [comment]
Do you have an example of a config to enable diagnostics?

**Comment by esn89** [comment]
@vn-ki have you been getting any timeouts with MPLS?

**Comment by chemzqm** [comment]
Try out https://github.com/neoclide/coc-python.
