### ISSUE TITLE
SyncAutocmd causes crash

### ISSUE THREAD

**Issue by tbo** [neoclide/coc.nvim#421]
**Result from CocInfo**
```
## versions

vim version: NVIM v0.3.2
node version: v8.9.0
coc.nvim version: 0.0.53
term: xterm-256color
platform: darwin

## Error messages

## Output channel: java
[Info  - 12:06:13] JDT Language Server started
[object Object]
[Error  - 12:06:18] Feb 11, 2019 12:06:18 PM 
null
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.ListLineTracker.getLineOffset(ListLineTracker.java:197)
	at org.eclipse.jface.text.AbstractLineTracker.getLineOffset(AbstractLineTracker.java:160)
	at org.eclipse.jface.text.AbstractDocument.getLineOffset(AbstractDocument.java:876)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.convertRange(WorkspaceDiagnosticsHandler.java:328)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.toDiagnostic(WorkspaceDiagnosticsHandler.java:308)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.lambda$3(WorkspaceDiagnosticsHandler.java:293)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.toDiagnosticsArray(WorkspaceDiagnosticsHandler.java:295)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.visit(WorkspaceDiagnosticsHandler.java:145)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:67)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:51)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceDiagnosticsHandler.resourceChanged(WorkspaceDiagnosticsHandler.java:83)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:290)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:153)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:379)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1502)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:169)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Describe the bug**

After updating to v0.0.53 coc.nvim crashes after a few seconds of interaction with the following error message:

```
Error detected while processing function <SNR>35_SyncAutocmd[3]..coc#rpc#request[2]..<SNR>38_request:
line    7:
Invalid channel: 3
Error detected while processing function <SNR>35_SyncAutocmd:
line    3:
E171: Missing :endif
[coc] server connection lost
```

**To Reproduce**

I'm not sure, what is triggering this. But it happens rather quickly. I tested the jdt- and the tsserver extension.

**Comment by chemzqm** [comment]
Try install binary or build from source again.

**Comment by tbo** [comment]
I tried both, but the issue persists.

**Comment by chemzqm** [comment]
It could happen if your node process was killed.

**Comment by tbo** [comment]
Looks like it. The coc.nvim node process had a different process id after the issue occured.

**Comment by chemzqm** [comment]
It requires network access sometime, so could be killed by your firewall.

**Comment by tbo** [comment]
> so could be killed by your firewall.
Firewalls don't actively kill other processes, they just deny network access. It is up to the client application if it handles such a case or dies.

I downgraded to v0.0.52 and don't experience any issues. So I assume, that it was introduced with the new release.

**Comment by chemzqm** [comment]
Please confirm how to trigger this issue, is it happens with coc-tsserver?

**Comment by tbo** [comment]
I tested it with coc-java and coc-tsserver. The behavior is the same:

![kapture 2019-02-11 at 16 39 13](https://user-images.githubusercontent.com/264745/52574093-cbd15880-2e1b-11e9-8b3b-15b77aed48cf.gif)

I switched into insert mode and typed `c`. I get the feeling, that it is triggered by auto completion.

**Comment by chemzqm** [comment]
I've tried nvim 0.3.2 with coc.nvim 0.0.53 release, still can't reproduce the problem,

**Comment by tbo** [comment]
What a shame. I will check which commit in v0.0.53 introduced this. Maybe it will help us figuring out, what is causing this issue.

**Comment by sainnhe** [comment]
The same problem, bad commit: [fix(workspace): fix CursorHoldI not triggered, fix #414](https://github.com/neoclide/coc.nvim/commit/b97341fb6402809e7587bd47238aba779a191f34)

**Comment by chemzqm** [comment]
@sainnhe Thanks，I've fixed the  trigger for CursorHoldI.

**Comment by sainnhe** [comment]
@chemzqm Tested in my machine, coc works fine now, thanks!

**Comment by tbo** [comment]
I can confirm this. v0.0.54 fixed the issue for me.
Thanks!
