### ISSUE TITLE
Restarting server failed with coc-sumneko-lua

### ISSUE THREAD

**Issue by gennaro-tedesco** [neoclide/coc.nvim#4225]
## Result from CocInfo

```
## versions

vim version: NVIM v0.7.2
node version: v18.9.0
coc.nvim version: 0.0.82-488d6ae7 2022-09-22 01:50:53 +0800
coc.nvim directory: ~/.config/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2022-09-23T06:19:14.849 INFO (pid:40514) [plugin] - coc.nvim initialized with node: v18.9.0 after 26ms
2022-09-23T06:19:19.696 INFO (pid:40514) [attach] - receive notification: showInfo []
```

## Reproduce the bug

- Create file mini.vim with：

```
set nocompatible
set runtimepath^=./coc.nvim
filetype plugin indent on
syntax on
set hidden

" coc-sumneko-lua also has issue
let g:coc_global_extensions = ['coc-sumneko-lua']
```

- `nvim -u mini.vim test.lua` shows the aforementioned exception

## Describe the bug

Cross-posting from [coc-sumneko-lua](https://github.com/xiyaowong/coc-sumneko-lua/issues/32): I apologise if this is not the right place to report (if so feel free to close). The other repository seems un-maintained.

Since the release [v3.5.6](https://github.com/sumneko/vscode-lua/releases/tag/v3.5.6) of `vscode-lua` I get the following errors opening any lua file:
```
[coc.nvim] Restarting server failed
```

## Further info

On further inspection, by using `:CocOpenLog` I see the following log message for the exception:

```
2022-09-21T01:58:58.127 INFO (pid:12856) [services] - registered service "sumneko-lua"
2022-09-21T01:58:58.130 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:58:58.130 INFO (pid:12856) [plugin] - coc.nvim initialized with node: v18.9.0 after 142ms
2022-09-21T01:58:58.140 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12865
2022-09-21T01:58:58.167 ERROR (pid:12856) [language-client] - Sending request failed.
2022-09-21T01:58:58.168 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:58:58.168 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:58:58.169 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:58:58.170 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:58:58.170 ERROR (pid:12856) [extensions-manager] - Error on active extension coc-sumneko-lua: Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:58:58.170 ERROR (pid:12856) [extensions-manager] - Error on activate coc-sumneko-lua Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:58:58.171 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:58:58.173 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12866
2022-09-21T01:58:58.178 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:58:58.179 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:58:58.179 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:58:58.179 ERROR (pid:12856) [services] - Server sumneko-lua failed to start: Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:58:58.180 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:58:58.181 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12868
2022-09-21T01:58:58.186 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:58:58.187 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:58:58.187 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:58:58.188 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:58:58.189 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12869
2022-09-21T01:58:58.194 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:58:58.195 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:59:01.591 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:01.749 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:01.838 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:01.957 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:02.355 INFO (pid:12856) [attach] - receive notification: openList [ 'commands' ]
2022-09-21T01:59:14.438 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:14.596 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:14.675 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:14.764 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:14.989 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:15.491 INFO (pid:12856) [attach] - receive notification: openList [ 'commands' ]
2022-09-21T01:59:22.814 INFO (pid:12856) [services] - registered service "sumneko-lua"
2022-09-21T01:59:22.814 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:59:22.816 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12876
2022-09-21T01:59:22.821 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:59:22.821 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:59:22.821 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:59:22.821 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:59:22.822 ERROR (pid:12856) [list-session] - Error on action run Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:59:22.822 ERROR (pid:12856) [node-client] - Pending response rejected since connection got disposed Error: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
2022-09-21T01:59:22.822 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:59:22.824 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12877
2022-09-21T01:59:22.828 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:59:22.829 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:59:22.829 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:59:22.829 ERROR (pid:12856) [services] - Server sumneko-lua failed to start: Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:59:22.829 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:59:22.831 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12878
2022-09-21T01:59:22.836 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:59:22.836 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:59:22.836 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:59:22.837 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:59:22.838 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12879
2022-09-21T01:59:22.844 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:59:22.845 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:59:28.547 INFO (pid:12856) [attach] - receive notification: openLog []
```

**Comment by chemzqm** [comment]
Seems problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel
I tried latest coc-sumneko-lua, no crash, you may need check log of the language server.

**Comment by gennaro-tedesco** [comment]
Debugging the language server as you suggested shows that the server isn't running - I will clarify with their owners/authors, I suppose we can close this issue since it isn't related to CoC. Thank you for taking the time to look into it!
