### ISSUE TITLE
LSP error with glsl-language-server on Raspberry Pi

### ISSUE THREAD

**Issue by wstevick** [neoclide/coc.nvim#4239]
I'm trying to get coc.nvim set up to edit glsl fiels. Here are my versions for everything, copied from ```:CocInfo```

```
vim version: NVIM v0.7.0  
node version: v17.5.0                                                                                                                                         
coc.nvim version: 0.0.82-88189afa 2022-09-27 22:30:34 +0800  
coc.nvim directory: /home/pi/.config/nvim/plugged/coc.nvim  
term: xterm-256color  
platform: linux
```

I'm using [glsl-language-server](https://github.com/svenstaro/glsl-language-server) version 0.3.7, built from source. My configuration for that in ```coc-settings.json``` is
```json
"languageserver": {
    "glslls": {
        "command": "/home/pi/glsl-language-server/build/glslls",
        "filetypes": [
            "glsl"
        ],
        "args": [
            "--stdin"                                                                                                                                     
        ]
    }
}
```
Whenever I try opening a .glsl file, it gives me this error
```
[coc.nvim]: UnhandledRejection: i.reduce is not a function
TypeError: i.reduce is not a function
    at Hv.register (/home/pi/.config/nvim/plugged/coc.nvim/build/index.js:200:22718)
    at Zee.registerSignatureHelpProvider (/home/pi/.config/nvim/plugged/coc.nvim/build/index.js:258:19912)
    at L_.registerLanguageProvider (/home/pi/.config/nvim/plugged/coc.nvim/build/index.js:213:76234)
    at L_.register (/home/pi/.config/nvim/plugged/coc.nvim/build/index.js:213:23196)
    at L_.initialize (/home/pi/.config/nvim/plugged/coc.nvim/build/index.js:213:75936)
    at cf.initializeFeatures (/home/pi/.config/nvim/plugged/coc.nvim/build/index.js:218:16707)
    at cf.doInitialize (/home/pi/.config/nvim/plugged/coc.nvim/build/index.js:218:7973)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async cf._start (/home/pi/.config/nvim/plugged/coc.nvim/build/index.js:218:2852)
    at async Object.start (/home/pi/.config/nvim/plugged/coc.nvim/build/index.js:223:5067)
```

I have no experience whatsoever debugging JavaScript, and I have no idea what might be causing this problem.

**Comment by wstevick** [comment]
I set the trace thing to verbose, and ran the command. A window showed up asking for extensions, watchmen, or snippets. Extensions just has one line about another thing I tried ([coc-cl](https://github.com/UltiRequiem/coc-cl), if you're curious), watchmen was empty, and snippets has this
```
[Info  - 22:58:57.560] Using ultisnips directories:                                   
[
  "UltiSnips",      
  "/home/pi/.config/coc/ultisnips"      
]      
[Info  - 22:58:57.597] Loading textmate snippets from filetypes: glsl
```

**Comment by chemzqm** [comment]
Add `"trace.server": "verbose"` to your language server configuration section first.

**Comment by wstevick** [comment]
I did. Here's my new ```coc-settings.json```. (All of it this time, in case something else is causing problems.)
```json
{      
    "coc.preferences.formatOnSaveFiletypes": [      
        "*"      
    ],      
    "pylsp.builtin.enableInstallPylsIsort": true,      
    "pylsp.builtin.enableInstallPythonLspBlack": true,      
    "pylsp.commandPath": "/home/pi/.lsp-servs/python",      
    "pylsp.builtin.pythonPath": "/home/pi/.pyenv/versions/3.10.2/bin/python3",      
    "pylsp.builtin.installExtrasArgs": [],      
    "pylsp.plugins.mccabe.enabled": false,      
    "pylsp.plugins.pyflakes.enabled": false,      
    "pylsp.plugins.pycodestyle.enabled": false,      
    "pylsp.plugins.flake8.enabled": true,      
    "pylsp.configurationSources": [      
        "flake8"      
    ],      
    "languageserver": {      
        "glslls": {      
            "trace.server": "verbose",                                                                                                                        
            "command": "/home/pi/glsl-language-server/build/glslls",      
            "filetypes": [      
                "glsl"      
            ],      
            "args": [      
                "--stdin"      
            ]      
        }      
    }      
}
```

**Comment by fannheyward** [comment]
Your configurations are correct, please post verbose logs.

**Comment by wstevick** [comment]
Thanks.
