### ISSUE TITLE
Error on event: TextChangedI TypeError: res.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by hexh250786313** [neoclide/coc.nvim#4244]
## Env

- neovim 0.7.2 the release

## Description

Coc throw an error `res.hasOwnProperty is not a function` when suggest fired

## mini.vim

```vim
set nocompatible
set runtimepath^=/path/to/coc.nvim/
filetype plugin indent on
syntax on
set hidden

let g:coc_global_extensions = ['coc-tsserver']

let g:coc_user_config = {
    \   "suggest.autoTrigger": "always"
    \ }
```

## Reproduce

1. Edit a ts / js file (but it doesn't happen at all js or ts file) like `coc.nvim/src/model/chars.ts`: `nvim --clean -u ./mini.vim /path/to/coc.nvim/src/model/chars.ts`
2. Input `console.log` at line 5
3. Result of `:CocOpenLog`:
   ```
   2022-09-29T15:09:04.505 ERROR (pid:342740) [events] - Error on event: TextChangedI TypeError: res.hasOwnProperty is not a function
    at add (/home/hexh/workspace/coc.nvim/build/index.js:30318:27)
    at Chars.computeWordRanges (/home/hexh/workspace/coc.nvim/build/index.js:30329:17)
    at Workspace.computeWordRanges (/home/hexh/workspace/coc.nvim/build/index.js:37362:32)
    at Function.create (/home/hexh/workspace/coc.nvim/build/index.js:69804:64)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Complete.completeSources (/home/hexh/workspace/coc.nvim/build/index.js:69978:5)
    at async Complete.doComplete (/home/hexh/workspace/coc.nvim/build/index.js:69937:5)
    at async Completion.startCompletion (/home/hexh/workspace/coc.nvim/build/index.js:70773:23)
    at async Completion.triggerCompletion (/home/hexh/workspace/coc.nvim/build/index.js:70882:5)
   ```

**Comment by hexh250786313** [comment]
https://github.com/neoclide/coc.nvim/blob/0d5b924e6af7c57c1a4ae3a953426fb207388f06/src/model/chars.ts#L136

Changing it to below line seems help:

```typescript
let arr = Object.prototype.hasOwnProperty.call(res, word) ? res[word] : []
```
