### ISSUE TITLE
C-N Not working on the Neovim

### ISSUE THREAD

**Issue by weneghawi** [neoclide/coc.nvim#4247]
## versions

vim version: NVIM v0.7.2
node version: v18.9.0
coc.nvim version: 0.0.82-01ddea57 2022-09-15 14:20:57 +0800
coc.nvim directory: /Users/i521907/.vim/bundle/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2022-09-29T09:43:58.746 INFO (pid:16636) [plugin] - coc.nvim initialized with node: v18.9.0 after 283ms
2022-09-29T09:43:58.821 WARN (pid:16636) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at t.initStatusBar (/Users/i521907/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:155873)
    at t.activate (/Users/i521907/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23099)
2022-09-29T09:44:00.347 INFO (pid:16636) [attach] - receive notification: showInfo []
## Describe the bug
Currently with new neovim after updating the coc-server I cannot do Control-N (to go to the next floaterm item) while Control-P works

## Reproduce the bug
inoremap <silent><expr> <TAB>
      \ pumvisible() ? coc#_select_confirm() :
      \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()

## Screenshots (optional)
N/A

**Comment by chemzqm** [comment]
Use coc#pumvisible instead of pumvisible

**Comment by npearson72** [comment]
@chemzqm 

```
E117: Unknown function: coc#pumvisible
```

```
inoremap <silent><expr><tab> coc#pumvisible() ? "\<c-n>" : "\<tab>"
inoremap <silent><expr><s-tab> coc#pumvisible() ? "\<c-p>" : "\<s-tab>"
inoremap <silent><expr><c-j> coc#pumvisible() ? "\<c-y>" : "\<c-j>"
```

Any ideas?
