### ISSUE TITLE
Tab no longer selects first auto-complete suggestion

### ISSUE THREAD

**Issue by Krzmbrzl** [neoclide/coc.nvim#4283]
## Result from CocInfo

```
## versions

vim version: NVIM v0.8.0-v0.8.0
node version: v16.14.2
coc.nvim version: 0.0.82-f39f5f69 2022-10-07 23:24:25 +0800
coc.nvim directory: /home/robert/.vim/bundle/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2022-10-12T18:48:04.522 ERROR (pid:9746) [configurations] - Invalid configuration "suggest.detailMaxLength" from coc-clangd, overwrite defaults is forbidden.
2022-10-12T18:48:04.523 ERROR (pid:9746) [configurations] - Invalid configuration "diagnostic.format" from coc-clangd, overwrite defaults is forbidden.
2022-10-12T18:48:04.599 INFO (pid:9746) [services] - registered service "languageserver.fortran"
2022-10-12T18:48:04.682 INFO (pid:9746) [services] - registered service "highlight"
2022-10-12T18:48:04.696 INFO (pid:9746) [plugin] - coc.nvim initialized with node: v16.14.2 after 197ms
2022-10-12T18:48:04.697 INFO (pid:9746) [attach] - receive notification: highlight []
2022-10-12T18:48:04.718 WARN (pid:9746) [language-client-client] - disableCompletion in the client options is deprecated. use disabledFeatures instead. 
at new $x (/home/robert/.vim/bundle/coc.nvim/build/index.js:213:91301)
at new ad (/home/robert/.vim/bundle/coc.nvim/build/index.js:222:3055)
2022-10-12T18:48:04.718 WARN (pid:9746) [language-client-client] - disableDiagnostics in the client options is deprecated. use disabledFeatures instead. 
at new $x (/home/robert/.vim/bundle/coc.nvim/build/index.js:213:91301)
at new ad (/home/robert/.vim/bundle/coc.nvim/build/index.js:222:3055)
2022-10-12T18:48:04.719 INFO (pid:9746) [services] - registered service "clangd"
2022-10-12T18:48:04.719 INFO (pid:9746) [services] - LanguageClient clangd state change: stopped => starting
2022-10-12T18:48:04.722 INFO (pid:9746) [language-client-index] - Language server "clangd" started with 9768
2022-10-12T18:48:04.765 INFO (pid:9746) [services] - LanguageClient highlight server state change: starting => running
2022-10-12T18:48:04.768 INFO (pid:9746) [services] - LanguageClient clangd state change: starting => running
2022-10-12T18:48:04.771 INFO (pid:9746) [services] - service clangd started
2022-10-12T18:48:09.932 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:10.282 INFO (pid:9746) [attach] - receive notification: highlight []
2022-10-12T18:48:11.881 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:12.214 INFO (pid:9746) [attach] - receive notification: highlight []
2022-10-12T18:48:12.315 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:12.490 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:12.668 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:12.828 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:12.988 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:13.297 INFO (pid:9746) [attach] - receive notification: highlight []
2022-10-12T18:48:13.755 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:14.066 INFO (pid:9746) [attach] - receive notification: highlight []
2022-10-12T18:48:14.268 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:14.602 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:14.907 INFO (pid:9746) [attach] - receive notification: highlight []
2022-10-12T18:48:15.295 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:15.563 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:15.565 WARN (pid:9746) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2022-10-12T18:48:15.834 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:15.898 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:16.011 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:16.122 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:16.330 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:16.395 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:16.458 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:16.522 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:16.778 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:16.780 WARN (pid:9746) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2022-10-12T18:48:17.947 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:17.994 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:18.330 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:18.650 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:18.794 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:19.050 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:19.661 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:19.661 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:20.069 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:20.385 INFO (pid:9746) [attach] - receive notification: highlight []
2022-10-12T18:48:21.370 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:21.676 INFO (pid:9746) [attach] - receive notification: highlight []
2022-10-12T18:48:21.970 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:22.010 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:22.050 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:22.090 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:22.131 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:22.171 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:22.211 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:22.251 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:22.291 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:22.597 INFO (pid:9746) [attach] - receive notification: highlight []
2022-10-12T18:48:22.922 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:23.229 INFO (pid:9746) [attach] - receive notification: highlight []
2022-10-12T18:48:23.523 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:23.562 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:23.602 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:23.643 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:23.683 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:23.723 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:23.946 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:24.106 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:24.266 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:24.410 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:24.586 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:24.746 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:24.906 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:25.067 INFO (pid:9746) [attach] - receive notification: doAutocmd [ 1 ]
2022-10-12T18:48:25.373 INFO (pid:9746) [attach] - receive notification: highlight []
...
```

## Describe the bug

When editing a C++ source file, the auto-complete popup appears during writing. When wanting to select the first entry in that popup window, I used to be able to press Tab once. If I do the same now, it's the second suggestion that is selected instead and I have to use Shift+Tab to select the first entry instead.

## Reproduce the bug

- Create file `mini.vim` with：

```vim
 set nocompatible
filetype off    
set hidden

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'neoclide/coc.nvim'

call vundle#end()        
filetype plugin indent on
syntax on

let g:coc_global_extensions = ['coc-clangd']

" Use tab for trigger completion with characters ahead and navigate.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion.
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

  ```

- Start neovim with command: `nvim -u mini.vim test.cpp`

- Add the following contents
```cpp
int main() {
	int aloa;
	int alob;

	al
}
```
- Put cursor behind `al`
- Press Ctrl+Space to trigger completion
- Observe multiple entries in suggestion window
- Use Tab
- Observe second entry to be selected instead of first

**Comment by duguosheng** [comment]
I have the same question.

**Comment by fannheyward** [comment]
Enable `suggest.noselect` in your coc-settings.json.

- https://github.com/neoclide/coc.nvim/issues/4202
- https://github.com/neoclide/coc.nvim/issues/4166
- https://github.com/neoclide/coc.nvim/issues/4086

**Comment by Krzmbrzl** [comment]
Thank you very much :+1:

**Comment by cjappl** [comment]
Thanks for the fix @fannheyward ! 

Can you give some context as to why this change was made? It seems like a big change to backwards compatibility that may be disruptive to users. Would it be good to make it default to "true", and users could change it to false if they wanted to?

**Comment by fannheyward** [comment]
@cjappl check the release notes: https://github.com/neoclide/coc.nvim/releases/tag/v0.0.82

**Comment by cjappl** [comment]
Thanks for the context!

**Comment by chemzqm** [comment]
On recent coc.nvim, it will fix the key-mappings for you https://github.com/neoclide/coc.nvim/blob/master/autoload/coc/ui.vim#L9
