### ISSUE TITLE
[coc.nvim] Initialize failed, Cannot create property 'uri' on number '0'

### ISSUE THREAD

**Issue by fcying** [neoclide/coc.nvim#43]
**Describe the bug**
When I open vim, it jump a error
```
[coc.nvim] Initialize failed, Cannot create property 'uri' on number '0'
```

**To Reproduce**
```
1. Install npm, install yarn
2. vim && :PlugInstall 
3. auto install vim-node-rpc, exit vim
4. vim enter
```

**Expected behavior**
work fine.

**Desktop (please complete the following information):**
 - Terminal: [xshell]
 - Version: [6]
 - vim 8.1-1-229

**Comment by chemzqm** [comment]
Have no idea what happened, could you paste the content from 
```
node -e 'console.log(path.join(os.tmpdir(), "coc-nvim.log"))'
```
here?

**Comment by fcying** [comment]
```
node -e 'console.log(path.join(os.tmpdir(), "coc-nvim.log"))'
/tmp/coc-nvim.log
```
cat /tmp/coc-nvim.log           
```
2018-08-06T16:36:27.101 ERROR (pid:99637) [sources] - Native source include error: Directory '/**/coc.nvim/lib/source/include_resolve' was not included into executable at compilation stage. Please recompile adding it as asset or script.
2018-08-06T16:36:27.159 INFO (pid:99637) [services] - Created services: cssserver,eslint,html,json,pyls,tslint,tsserver,vetur,wxml
2018-08-06T16:36:27.162 ERROR (pid:99637) [index] - TypeError: Cannot create property 'uri' on number '0'
    at Workspace.<anonymous> (/snapshot/coc.nvim/lib/workspace.js:333:30)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/coc.nvim/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2018-08-06T16:41:55.654 ERROR (pid:100583) [sources] - Native source include error: Directory '/**/coc.nvim/lib/source/include_resolve' was not included into executable at compilation stage. Please recompile adding it as asset or script.
2018-08-06T16:41:55.713 INFO (pid:100583) [services] - Created services: cssserver,eslint,html,json,pyls,tslint,tsserver,vetur,wxml
2018-08-06T16:41:55.715 INFO (pid:100583) [index] - Coc initialized
```

**Comment by chemzqm** [comment]
I have changed the vim API, but the old binary still use old API, so error happens.

**Comment by fcying** [comment]
How do I need to change it? Or just wait for the vim master update?

**Comment by chemzqm** [comment]
A new release is available, `:PlugUpdate` should fix this issue.

**Comment by fcying** [comment]
it can work now.

BTW: How can I install vim-node-rpc by myself? it need `sudo`

**Comment by chemzqm** [comment]
@fcying `sudo npm i -g vim-node-rpc`, I've improved the logic to add `sudo` for linux user.
