### ISSUE TITLE
E118: Too many arguments for function: getcurpos

### ISSUE THREAD

**Issue by arash83** [neoclide/coc.nvim#4319]
## versions

vim version: NVIM v0.6.1
node version: v19.0.0
coc.nvim version: 0.0.82-e51d6b1 2022-10-22 21:18:11 +0800
coc.nvim directory: /home/dev/.local/nvim/plugins/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2022-10-22T15:58:42.359 INFO (pid:4604) [services] - registered service "languageserver.ccls"
2022-10-22T15:58:42.365 INFO (pid:4604) [services] - LanguageClient ccls state change: stopped => starting
2022-10-22T15:58:42.386 INFO (pid:4604) [plugin] - coc.nvim initialized with node: v19.0.0 after 96ms
2022-10-22T15:58:42.393 INFO (pid:4604) [language-client-index] - Language server "languageserver.ccls" started with 4615
2022-10-22T15:58:42.414 INFO (pid:4604) [services] - LanguageClient ccls state change: starting => running
2022-10-22T15:58:42.420 INFO (pid:4604) [services] - service languageserver.ccls started
2022-10-22T15:58:50.140 ERROR (pid:4604) [node-client] - request error on "nvim_call_function" [ 'coc#util#diagnostic_info', [ 1, false ] ] Vim(return):E118: Too many arguments for function: getcurpos Error
    at NeovimClient2.request (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:8368:21)
    at NeovimClient2.call (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:9648:21)
    at DiagnosticBuffer.getDiagnosticInfo (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:70066:27)
    at DiagnosticBuffer.update (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:69945:31)
    at /home/dev/.local/nvim/plugins/coc.nvim/build/index.js:70569:22
    at CallbackList.invoke (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:11213:35)
    at Emitter47.fire (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:11264:34)
    at DiagnosticCollection.set (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:70374:40)
    at LanguageClient.setDiagnostics (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:55404:29)
    at LanguageClient.handleDiagnostics (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:55104:16)
2022-10-22T15:58:50.142 ERROR (pid:4604) [server] - unhandledRejection  Promise {
  <rejected> Error: request error on nvim_call_function - Vim(return):E118: Too many arguments for function: getcurpos
      at DiagnosticBuffer.getDiagnosticInfo (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:70066:27)
      at DiagnosticBuffer.update (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:69945:31)
      at /home/dev/.local/nvim/plugins/coc.nvim/build/index.js:70569:22
      at CallbackList.invoke (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:11213:35)
      at Emitter47.fire (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:11264:34)
      at DiagnosticCollection.set (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:70374:40)
      at LanguageClient.setDiagnostics (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:55404:29)
      at LanguageClient.handleDiagnostics (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:55104:16)
} Error: request error on nvim_call_function - Vim(return):E118: Too many arguments for function: getcurpos
    at DiagnosticBuffer.getDiagnosticInfo (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:70066:27)
    at DiagnosticBuffer.update (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:69945:31)
    at /home/dev/.local/nvim/plugins/coc.nvim/build/index.js:70569:22
    at CallbackList.invoke (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:11213:35)
    at Emitter47.fire (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:11264:34)
    at DiagnosticCollection.set (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:70374:40)
    at LanguageClient.setDiagnostics (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:55404:29)
    at LanguageClient.handleDiagnostics (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:55104:16)
2022-10-22T15:58:51.742 ERROR (pid:4604) [node-client] - request error on "nvim_call_function" [ 'coc#util#diagnostic_info', [ 1, true ] ] Vim(return):E118: Too many arguments for function: getcurpos Error
    at NeovimClient2.request (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:8368:21)
    at NeovimClient2.call (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:9648:21)
    at DiagnosticBuffer.getDiagnosticInfo (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:70066:27)
    at DiagnosticBuffer._refresh (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:70219:31)
    at Timeout._onTimeout (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:69796:23)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
2022-10-22T15:58:51.744 ERROR (pid:4604) [server] - unhandledRejection  Promise {
  <rejected> Error: request error on nvim_call_function - Vim(return):E118: Too many arguments for function: getcurpos
      at DiagnosticBuffer.getDiagnosticInfo (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:70066:27)
      at DiagnosticBuffer._refresh (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:70219:31)
      at Timeout._onTimeout (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:69796:23)
      at listOnTimeout (node:internal/timers:564:17)
      at process.processTimers (node:internal/timers:507:7)
} Error: request error on nvim_call_function - Vim(return):E118: Too many arguments for function: getcurpos
    at DiagnosticBuffer.getDiagnosticInfo (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:70066:27)
    at DiagnosticBuffer._refresh (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:70219:31)
    at Timeout._onTimeout (/home/dev/.local/nvim/plugins/coc.nvim/build/index.js:69796:23)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
2022-10-22T15:58:53.512 INFO (pid:4604) [attach] - receive notification: showInfo []

## Describe the bug
I have just reinstalled my computer with Linux Mint 21 and I am trying to setup coc.nvim. Code completion works it is but its the diagnostic part that errors.

:checkhealth does not show any errors errors.

I have tried both clangd and ccls language server and get the same error.

I get an error when the diagnostic_info is triggered.

## Reproduce the bug

- Create file `mini.vim` with：
- 

  ```vim
call plug#begin('~/.local/nvim/plugins')

Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}

call plug#end()
  ```

- Start (neo)vim with command: `nvim -u mini.vim bug.cpp`

- Type a syntax error intt a;
- New Line
- And Press escape

## Screenshots (optional)

![bug](https://user-images.githubusercontent.com/18328454/197344276-c2da9aa0-f84a-4da8-8f96-f8aac79c2c0f.png)

**Comment by arash83** [comment]
Installed NVIM v0.7.2 and issue was resolved!
