### ISSUE TITLE
clojure-lsp fails to start initialize in recent CoC release

### ISSUE THREAD

**Issue by pfernandez** [neoclide/coc.nvim#4329]
## versions

vim version: VIM - Vi IMproved 9.0 9000800
node version: v18.11.0
coc.nvim version: 0.0.82-a3d271d8 2022-10-27 16:26:01 +0800
coc.nvim directory: /Users/paul/.dotfiles/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2022-10-28T15:26:51.925 WARN (pid:71528) [attach] - Plugin not ready when received "updateConfig" [ 'suggest', { snippetsSupport: true } ]
2022-10-28T15:26:51.996 INFO (pid:71528) [plugin] - coc.nvim initialized with node: v18.11.0 after 51ms
2022-10-28T15:26:52.166 INFO (pid:71528) [extension-installer] - Fetched info of coc-clojure {
  'dist.tarball': 'https://registry.npmjs.org/coc-clojure/-/coc-clojure-0.0.9.tgz',
  'engines.coc': '^0.0.81',
  version: '0.0.9',
  name: 'coc-clojure'
}
2022-10-28T15:26:52.176 INFO (pid:71528) [extension-installer] - Fetched info of coc-css {
  'dist.tarball': 'https://registry.npmjs.org/coc-css/-/coc-css-1.3.0.tgz',
  'engines.coc': '^0.0.80',
  version: '1.3.0',
  name: 'coc-css'
}
2022-10-28T15:26:52.181 INFO (pid:71528) [extension-installer] - Fetched info of coc-eslint {
  'dist.tarball': 'https://registry.npmjs.org/coc-eslint/-/coc-eslint-1.5.8.tgz',
  'engines.coc': '^0.0.80',
  version: '1.5.8',
  name: 'coc-eslint'
}
2022-10-28T15:26:52.307 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-eslint/-/coc-eslint-1.5.8.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-eslint/-/coc-eslint-1.5.8.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:26:52.310 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-eslint/-/coc-eslint-1.5.8.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-eslint-2b462c48-8030-4af1-b68c-7606347c786a
2022-10-28T15:26:52.313 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-css/-/coc-css-1.3.0.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-css/-/coc-css-1.3.0.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:26:52.314 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-css/-/coc-css-1.3.0.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-css-a7ecd0f3-3e7b-4b92-8468-c00516a083ad
2022-10-28T15:26:52.374 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-clojure/-/coc-clojure-0.0.9.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-clojure/-/coc-clojure-0.0.9.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:26:52.375 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-clojure/-/coc-clojure-0.0.9.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-clojure-6f81bf0d-3584-415c-ba19-54e75d4f413b
2022-10-28T15:26:52.595 INFO (pid:71528) [extension-installer] - Fetched info of coc-highlight {
  'dist.tarball': 'https://registry.npmjs.org/coc-highlight/-/coc-highlight-2.0.3.tgz',
  'engines.coc': '^0.0.82',
  version: '2.0.3',
  name: 'coc-highlight'
}
2022-10-28T15:26:52.612 INFO (pid:71528) [extension-installer] - Fetched info of coc-git {
  'dist.tarball': 'https://registry.npmjs.org/coc-git/-/coc-git-2.5.3.tgz',
  'engines.coc': '^0.0.80',
  version: '2.5.3',
  name: 'coc-git'
}
2022-10-28T15:26:52.700 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-highlight/-/coc-highlight-2.0.3.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-highlight/-/coc-highlight-2.0.3.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:26:52.701 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-highlight/-/coc-highlight-2.0.3.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-highlight-1e3a7574-86c8-4844-a7a5-44ad64d3fe7a
2022-10-28T15:26:52.720 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-git/-/coc-git-2.5.3.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-git/-/coc-git-2.5.3.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:26:52.720 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-git/-/coc-git-2.5.3.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-git-53526b3f-98cd-4b7c-9abf-6e7c2a22542d
2022-10-28T15:26:52.846 INFO (pid:71528) [coc-git] - Looking for git in: git
2022-10-28T15:26:52.960 INFO (pid:71528) [extension-installer] - Fetched info of coc-html {
  'dist.tarball': 'https://registry.npmjs.org/coc-html/-/coc-html-1.7.0.tgz',
  'engines.coc': '^0.0.80',
  version: '1.7.0',
  name: 'coc-html'
}
2022-10-28T15:26:52.982 INFO (pid:71528) [extension-installer] - Fetched info of coc-json {
  'dist.tarball': 'https://registry.npmjs.org/coc-json/-/coc-json-1.7.0.tgz',
  'engines.coc': '>= 0.0.80',
  version: '1.7.0',
  name: 'coc-json'
}
2022-10-28T15:26:53.082 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-json/-/coc-json-1.7.0.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-json/-/coc-json-1.7.0.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:26:53.084 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-json/-/coc-json-1.7.0.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-json-8e399c5c-1df0-484e-a55a-e99aa2494c03
2022-10-28T15:26:53.086 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-html/-/coc-html-1.7.0.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-html/-/coc-html-1.7.0.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:26:53.087 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-html/-/coc-html-1.7.0.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-html-bfbfe534-8856-495f-bf28-81da054f6fab
2022-10-28T15:26:53.317 INFO (pid:71528) [extension-installer] - Fetched info of coc-java {
  'dist.tarball': 'https://registry.npmjs.org/coc-java/-/coc-java-1.5.5.tgz',
  'engines.coc': '>=0.0.79',
  version: '1.5.5',
  name: 'coc-java'
}
2022-10-28T15:26:53.443 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-java/-/coc-java-1.5.5.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-java/-/coc-java-1.5.5.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:26:53.444 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-java/-/coc-java-1.5.5.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-java-4daeff9e-caae-40a1-ab3d-4164feedc311
2022-10-28T15:26:53.676 INFO (pid:71528) [extension-installer] - Fetched info of coc-markdown-preview-enhanced {
  'dist.tarball': 'https://registry.npmjs.org/coc-markdown-preview-enhanced/-/coc-markdown-preview-enhanced-0.4.3.tgz',
  'engines.coc': '^0.0.80',
  version: '0.4.3',
  name: 'coc-markdown-preview-enhanced'
}
2022-10-28T15:26:53.768 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-markdown-preview-enhanced/-/coc-markdown-preview-enhanced-0.4.3.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-markdown-preview-enhanced/-/coc-markdown-preview-enhanced-0.4.3.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:26:53.768 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-markdown-preview-enhanced/-/coc-markdown-preview-enhanced-0.4.3.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-markdown-preview-enhanced-012a31f5-bdcd-4331-b29e-7e37ef52a5f9
2022-10-28T15:26:54.313 INFO (pid:71528) [extension-installer] - Fetched info of coc-phpls {
  'dist.tarball': 'https://registry.npmjs.org/coc-phpls/-/coc-phpls-2.2.2.tgz',
  'engines.coc': '^0.0.66',
  version: '2.2.2',
  name: 'coc-phpls'
}
2022-10-28T15:26:54.407 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-phpls/-/coc-phpls-2.2.2.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-phpls/-/coc-phpls-2.2.2.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:26:54.408 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-phpls/-/coc-phpls-2.2.2.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-phpls-124e1c48-2517-45e2-b3fa-f61418a7e225
2022-10-28T15:26:54.629 INFO (pid:71528) [extension-installer] - Fetched info of coc-prettier {
  'dist.tarball': 'https://registry.npmjs.org/coc-prettier/-/coc-prettier-9.3.1.tgz',
  'engines.coc': '>= 0.0.80',
  version: '9.3.1',
  name: 'coc-prettier'
}
2022-10-28T15:26:54.723 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-prettier/-/coc-prettier-9.3.1.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-prettier/-/coc-prettier-9.3.1.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:26:54.723 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-prettier/-/coc-prettier-9.3.1.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-prettier-1bf8e5b5-43c9-486c-ba17-9a316b4a174d
2022-10-28T15:26:56.206 INFO (pid:71528) [extension-installer] - Fetched info of coc-sh {
  'dist.tarball': 'https://registry.npmjs.org/coc-sh/-/coc-sh-0.7.0.tgz',
  'engines.coc': '^0.0.81',
  version: '0.7.0',
  name: 'coc-sh'
}
2022-10-28T15:26:56.290 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-sh/-/coc-sh-0.7.0.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-sh/-/coc-sh-0.7.0.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:26:56.292 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-sh/-/coc-sh-0.7.0.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-sh-029970cf-5369-4e7a-8360-524da7027586
2022-10-28T15:26:58.508 INFO (pid:71528) [extension-installer] - Fetched info of coc-sql {
  'dist.tarball': 'https://registry.npmjs.org/coc-sql/-/coc-sql-0.10.5.tgz',
  'engines.coc': '^0.0.80',
  version: '0.10.5',
  name: 'coc-sql'
}
2022-10-28T15:26:58.655 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-sql/-/coc-sql-0.10.5.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-sql/-/coc-sql-0.10.5.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:26:58.657 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-sql/-/coc-sql-0.10.5.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-sql-15ee85d8-a451-409b-97ce-09a59dbc02b3
2022-10-28T15:26:59.492 INFO (pid:71528) [extension-installer] - Fetched info of coc-tsserver {
  'dist.tarball': 'https://registry.npmjs.org/coc-tsserver/-/coc-tsserver-1.11.12.tgz',
  'engines.coc': '^0.0.82',
  version: '1.11.12',
  name: 'coc-tsserver'
}
2022-10-28T15:26:59.500 INFO (pid:71528) [extension-installer] - Fetched info of coc-vimlsp {
  'dist.tarball': 'https://registry.npmjs.org/coc-vimlsp/-/coc-vimlsp-0.12.8.tgz',
  'engines.coc': '^0.0.62',
  version: '0.12.8',
  name: 'coc-vimlsp'
}
2022-10-28T15:26:59.592 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-tsserver/-/coc-tsserver-1.11.12.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-tsserver/-/coc-tsserver-1.11.12.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:26:59.595 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-tsserver/-/coc-tsserver-1.11.12.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-tsserver-26d33f10-603d-4c50-b5c5-e6f504758832
2022-10-28T15:26:59.628 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-vimlsp/-/coc-vimlsp-0.12.8.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-vimlsp/-/coc-vimlsp-0.12.8.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:26:59.629 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-vimlsp/-/coc-vimlsp-0.12.8.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-vimlsp-aa42d037-9b82-42b8-b10d-616d214c51c4
2022-10-28T15:26:59.895 INFO (pid:71528) [extension-installer] - Fetched info of coc-webview {
  'dist.tarball': 'https://registry.npmjs.org/coc-webview/-/coc-webview-0.11.2.tgz',
  'engines.coc': '^0.0.80',
  version: '0.11.2',
  name: 'coc-webview'
}
2022-10-28T15:27:00.055 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-webview/-/coc-webview-0.11.2.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-webview/-/coc-webview-0.11.2.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:27:00.057 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-webview/-/coc-webview-0.11.2.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-webview-8c3dbeb8-afea-42f4-9b50-5ca24e3bb883
2022-10-28T15:27:00.342 INFO (pid:71528) [extension-installer] - Fetched info of coc-yaml {
  'dist.tarball': 'https://registry.npmjs.org/coc-yaml/-/coc-yaml-1.8.0.tgz',
  'engines.coc': '^0.0.80',
  version: '1.8.0',
  name: 'coc-yaml'
}
2022-10-28T15:27:00.447 INFO (pid:71528) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-yaml/-/coc-yaml-1.8.0.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-yaml/-/coc-yaml-1.8.0.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-10-28T15:27:00.447 INFO (pid:71528) [model-download] - Downloaded https://registry.npmjs.org/coc-yaml/-/coc-yaml-1.8.0.tgz => /Users/paul/.config/coc/extensions/node_modules/coc-yaml-f1f20358-9e55-4a3e-b22f-6e7c3eee48ff
2022-10-28T15:27:15.525 INFO (pid:71528) [attach] - receive notification: updateConfig [ 'suggest', { snippetsSupport: false } ]
2022-10-28T15:27:15.552 INFO (pid:71528) [attach] - receive notification: updateConfig [ 'suggest', { snippetsSupport: false } ]
2022-10-28T15:27:15.699 INFO (pid:71528) [coc-clojure] - Starting up coc-clojure
2022-10-28T15:27:15.701 INFO (pid:71528) [coc-clojure] - Creating client
2022-10-28T15:27:15.706 INFO (pid:71528) [services] - registered service "clojure"
2022-10-28T15:27:15.706 INFO (pid:71528) [services] - LanguageClient Clojure Language Client state change: stopped => starting
2022-10-28T15:27:15.721 INFO (pid:71528) [language-client-index] - Language server "clojure" started with 71558
2022-10-28T15:27:15.773 ERROR (pid:71528) [language-client-client] - Server clojure initialization failed. ResponseError2: Internal error
    at handleResponse (/Users/paul/.dotfiles/.vim/plugged/coc.nvim/build/index.js:12216:40)
    at processMessageQueue (/Users/paul/.dotfiles/.vim/plugged/coc.nvim/build/index.js:12039:13)
    at Immediate.<anonymous> (/Users/paul/.dotfiles/.vim/plugged/coc.nvim/build/index.js:12025:11)
    at process.processImmediate (node:internal/timers:471:21) {
  code: -32603,
  data: { id: 0, method: 'initialize' }
}
2022-10-28T15:27:15.774 INFO (pid:71528) [services] - LanguageClient Clojure Language Client state change: starting => stopped
2022-10-28T15:27:15.775 ERROR (pid:71528) [services] - Server clojure failed to start: ResponseError2: Internal error
    at handleResponse (/Users/paul/.dotfiles/.vim/plugged/coc.nvim/build/index.js:12216:40)
    at processMessageQueue (/Users/paul/.dotfiles/.vim/plugged/coc.nvim/build/index.js:12039:13)
    at Immediate.<anonymous> (/Users/paul/.dotfiles/.vim/plugged/coc.nvim/build/index.js:12025:11)
    at process.processImmediate (node:internal/timers:471:21) {
  code: -32603,
  data: { id: 0, method: 'initialize' }
}
2022-10-28T15:27:15.775 ERROR (pid:71528) [extensions-manager] - Error on active extension coc-clojure: ResponseError2: Internal error
    at handleResponse (/Users/paul/.dotfiles/.vim/plugged/coc.nvim/build/index.js:12216:40)
    at processMessageQueue (/Users/paul/.dotfiles/.vim/plugged/coc.nvim/build/index.js:12039:13)
    at Immediate.<anonymous> (/Users/paul/.dotfiles/.vim/plugged/coc.nvim/build/index.js:12025:11)
    at process.processImmediate (node:internal/timers:471:21) {
  code: -32603,
  data: { id: 0, method: 'initialize' }
}
2022-10-28T15:27:15.776 ERROR (pid:71528) [server] - unhandledRejection  Promise {
  <rejected> ResponseError2: Internal error
      at handleResponse (/Users/paul/.dotfiles/.vim/plugged/coc.nvim/build/index.js:12216:40)
      at processMessageQueue (/Users/paul/.dotfiles/.vim/plugged/coc.nvim/build/index.js:12039:13)
      at Immediate.<anonymous> (/Users/paul/.dotfiles/.vim/plugged/coc.nvim/build/index.js:12025:11)
      at process.processImmediate (node:internal/timers:471:21) {
    code: -32603,
    data: { id: 0, method: 'initialize' }
  }
} ResponseError2: Internal error
    at handleResponse (/Users/paul/.dotfiles/.vim/plugged/coc.nvim/build/index.js:12216:40)
    at processMessageQueue (/Users/paul/.dotfiles/.vim/plugged/coc.nvim/build/index.js:12039:13)
    at Immediate.<anonymous> (/Users/paul/.dotfiles/.vim/plugged/coc.nvim/build/index.js:12025:11)
    at process.processImmediate (node:internal/timers:471:21) {
  code: -32603,
  data: { id: 0, method: 'initialize' }
}
2022-10-28T15:27:20.253 INFO (pid:71528) [attach] - receive notification: showInfo []

## Describe the bug

https://github.com/neoclide/coc.nvim/commit/b3e5f091bb997422005cfe5b7f6a147f39ab73fd is the last commit that works with clojure-lsp. I use it with https://github.com/NoahTheDuke/coc-clojure.

## Reproduce the bug

This is with regular Vim in MacOS Monterey 12.6.1.

```sh
 brew install clojure-lsp/brew/clojure-lsp-native
```

With `a3d271d`, open a .clj file and observe the error.
With `b3e5f09`, open a .clj file and observe that it does not error.

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

Sorry but CoC is not loaded when using mini.vim.

**Comment by chemzqm** [comment]
Coc.nvim changed to set default values for configuration without value like VSCode does, but the server failed with
```
    "initializationOptions": {
        "source-paths": "",
        "source-aliases": [],
        "use-source-paths-from-classpath": false,
        "linters": {},
        "additional-snippets": [],
        "ignore-classpath-directories": false,
        "lint-project-files-after-startup?": false,
        "notify-references-on-file-change": false,
        "use-metadata-for-privacy?": false,
        "clean": {},
        "semantic-tokens?": false,
        "hover": {},
        "auto-add-ns-to-new-files?": false,
        "keep-parens-when-threading?": false,
        "document-formatting?": false,
        "document-range-formatting?": false,
        "cljfmt": {},
        "project-specs": [],
        "code-lens": {},
        "stubs": {},
        "classpath-config-paths": [],
        "copy-kond-configs?": false,
        "cache-path": "",
        "log-path": "",
        "api": {},
        "show-docs-arity-on-same-line?": false,
        "lens-segregate-test-references": false
    },
```
in initialize request, passed by coc-clojure

**Comment by chemzqm** [comment]
The error happens when the user specifies those value as well, the extensions or language server need to fix this issue.

**Comment by pfernandez** [comment]
Awesome, thanks for looking into this.
