### ISSUE TITLE
UnhandledRejection: Invalid method: nvim_exec

### ISSUE THREAD

**Issue by natemurthy** [neoclide/coc.nvim#4374]
### versions
```
vim version: NVIM v0.4.4
node version: v14.17.0
coc.nvim version: 0.0.82-0083083d 2022-11-19 00:09:32 +0800
coc.nvim directory: /Users/nate/.config/nvim/plugged/coc.nvim
term: Apple_Terminal
platform: darwin
```
### Log of coc.nvim
```
2022-11-18T15:27:25.488 INFO (pid:62170) [plugin] - coc.nvim initialized with node: v14.17.0 after 274
2022-11-18T15:27:25.500 ERROR (pid:62170) [node-client] - request error on "nvim_exec" [
  '\n' +
    'augroup coc_dynamic_autocmd\n' +
    '  autocmd!\n' +
    "  autocmd BufReadCmd,FileReadCmd,SourceCmd output:/* call coc#rpc#request('CocAutocmd', ['BufReadCmd','output', expand('<afile>')])\n" +
    "  autocmd OptionSet runtimepath call coc#rpc#notify('OptionSet',[expand('<amatch>'), v:option_old, v:option_new])\n" +
    'augroup end',
  false
] Error: request error on nvim_exec - Invalid method: nvim_exec
    at vg.setupDynamicAutocmd (/Users/nate/.config/nvim/plugged/coc.nvim/build/index.js:150:44)
    at Pm.init (/Users/nate/.config/nvim/plugged/coc.nvim/build/index.js:280:42056)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async rD.<anonymous> (/Users/nate/.config/nvim/plugged/coc.nvim/build/index.js:280:43609)
2022-11-18T15:27:25.501 ERROR (pid:62170) [server] - unhandledRejection  Promise {
  <rejected> Error: request error on nvim_exec - Invalid method: nvim_exec
      at vg.setupDynamicAutocmd (/Users/nate/.config/nvim/plugged/coc.nvim/build/index.js:150:44)
      at Pm.init (/Users/nate/.config/nvim/plugged/coc.nvim/build/index.js:280:42056)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async rD.<anonymous> (/Users/nate/.config/nvim/plugged/coc.nvim/build/index.js:280:43609)
} Error: request error on nvim_exec - Invalid method: nvim_exec
    at vg.setupDynamicAutocmd (/Users/nate/.config/nvim/plugged/coc.nvim/build/index.js:150:44)
    at Pm.init (/Users/nate/.config/nvim/plugged/coc.nvim/build/index.js:280:42056)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async rD.<anonymous> (/Users/nate/.config/nvim/plugged/coc.nvim/build/index.js:280:43609)
2022-11-18T15:36:58.738 INFO (pid:62170) [attach] - receive notification: showInfo []
```

## Describe the bug

After installing coc.vim, when I open any file with neovim I get this error described in the logs above and in the screenshot below.

## Reproduce the bug

- Here's my `.vimrc` which can be incorporated into `mini.vim`: https://github.com/natemurthy/dotfiles/blob/master/dot-vimrc
- Start (neo)vim with command: `vim -u mini.vim`
- Operate vim.

## Screenshots 

![image](https://user-images.githubusercontent.com/1788878/202821005-0941fcbe-6d58-493e-84ec-b09b47a9dde9.png)

**Comment by fannheyward** [comment]
> NVIM v0.4.4

Upgrade your nvim and try again, the latest release is 0.8.1.

**Comment by chemzqm** [comment]
It's expected to have some issues with nvim < 0.5.0

See https://github.com/neoclide/coc.nvim/blob/0083083d25a89654edf496daa04525afc29b8586/plugin/coc.vim#L26
