### ISSUE TITLE
Error reading .clang-format: Invalid argument (use -style=google to generate .clang-foramt)

### ISSUE THREAD

**Issue by wing-anemone** [neoclide/coc.nvim#4397]
## Result from CocInfo

 ```
## versions

vim version: NVIM v0.7.2
node version: v18.9.1
coc.nvim version: 0.0.82-bdd0b267 2022-10-21 03:01:15 +0800
coc.nvim directory: /root/.local/share/nvim/site/pack/packer/start/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2022-11-28T16:09:06.884 WARN (pid:866) [attach] - Plugin not ready when received "registerNotification" [ 'cquery', '$cquery/publishSemanticHighlighting' ]
2022-11-28T16:09:06.887 WARN (pid:866) [attach] - Plugin not ready when received "registerNotification" [ 'cquery', '$cquery/setInactiveRegions' ]
2022-11-28T16:09:06.887 WARN (pid:866) [attach] - Plugin not ready when received "registerNotification" [ 'ccls', '$ccls/publishSemanticHighlight' ]
2022-11-28T16:09:06.887 WARN (pid:866) [attach] - Plugin not ready when received "registerNotification" [ 'ccls', '$ccls/publishSkippedRanges' ]
2022-11-28T16:09:07.024 INFO (pid:866) [services] - registered service "languageserver.ccls"
2022-11-28T16:09:07.029 INFO (pid:866) [services] - LanguageClient ccls state change: stopped => starting
2022-11-28T16:09:07.583 INFO (pid:866) [services] - registered service "diagnostic-languageserver"
2022-11-28T16:09:07.605 INFO (pid:866) [coc-git] - Looking for git in: git
2022-11-28T16:09:07.653 INFO (pid:866) [plugin] - coc.nvim initialized with node: v18.9.1 after 756ms
2022-11-28T16:09:07.663 INFO (pid:866) [attach] - receive notification: registerNotification [ 'cquery', '$cquery/publishSemanticHighlighting' ]
2022-11-28T16:09:07.664 INFO (pid:866) [attach] - receive notification: registerNotification [ 'cquery', '$cquery/setInactiveRegions' ]
2022-11-28T16:09:07.664 INFO (pid:866) [attach] - receive notification: registerNotification [ 'ccls', '$ccls/publishSemanticHighlight' ]
2022-11-28T16:09:07.664 INFO (pid:866) [attach] - receive notification: registerNotification [ 'ccls', '$ccls/publishSkippedRanges' ]
2022-11-28T16:09:07.681 INFO (pid:866) [language-client-index] - Language server "languageserver.ccls" started with 885
2022-11-28T16:09:07.881 INFO (pid:866) [services] - registered service "pyright"
2022-11-28T16:09:07.899 INFO (pid:866) [services] - LanguageClient ccls state change: starting => running
2022-11-28T16:09:07.930 INFO (pid:866) [services] - service languageserver.ccls started
2022-11-28T16:09:18.527 INFO (pid:866) [attach] - Request action: format []
2022-11-28T16:09:18.550 ERROR (pid:866) [Handler] - Error on request format pg [Error]: Error reading /workspace/.clang-format: Invalid argument
    at Le (/root/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:25:233)
    at Wi (/root/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:24:6872)
    at Immediate.<anonymous> (/root/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:24:6719)
    at process.processImmediate (node:internal/timers:471:21) {
  code: -32001,
  data: undefined
}
 ```

## Describe the bug

**ccls --version**
Ubuntu ccls version 0.20220729-1-g8a93950
clang version 12.0.1-19ubuntu3

**clang-format --version** 
Ubuntu clang-format version 16.0.0-++20220928042258+eb53416d0f4a-1~exp1~20220928042408.449

I use " clang-format -style=google -dump-config > .clang-format" to generate a format file. 
But when I call "<Plug>(coc-format-selected)<cr>", cocinfo appeares: Error on Format range: Error: Error reading .clang-format: Invalid argument
![image](https://user-images.githubusercontent.com/26762566/204230953-a2adfe55-cbab-4436-bbb6-87221c966165.png)

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim

" mini.vim
set nocompatible
syntax on
set hidden
lua require 'whichkey'
  
```

```lua

-- whichkey.lua
local wk = require("which-key")

wk.setup({
  plugins = {
    marks = false, -- shows a list of your marks on ' and `
    registers = true, -- shows your registers on " in NORMAL or <C-r> in INSERT mo
  }
})

wk.register({
  ["<space>"] = {
    ["l"] = {
      ["f"] = { "<Plug>(coc-format-selected)<cr>", "format selected code" },
    }
  }
}, { mode = "v" })
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
Can't reproduce, I use `clang-format -style=google -dump-config > .clang-format` to generate an `.clang-format` file, works as expected.

> Error reading /workspace/.clang-format

The error is came from clangd, do you set the path to `.clang-format` that invalid?

**Comment by chemzqm** [comment]
Seems the `/workspace/.clang-format` is not inside your workspace fodler, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
应该是你设置或者 ccls 的问题，你得找 ccls 开发
