### ISSUE TITLE
coc-ccls fail to install

### ISSUE THREAD

**Issue by jlmxyz** [neoclide/coc.nvim#4443]
## versions

vim version: VIM - Vi IMproved 9.0 9001000
node version: v18.12.1
coc.nvim version: 0.0.82-7190104d 2022-11-12 03:16:52 +0800
coc.nvim directory: /home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2022-12-13T22:30:19.063 INFO (pid:10786) [plugin] - coc.nvim initialized with node: v18.12.1 after 141ms
2022-12-13T22:30:19.079 INFO (pid:10786) [services] - LanguageClient clangd state change: stopped => starting
2022-12-13T22:30:19.101 INFO (pid:10786) [language-client-index] - Language server "clangd" started with 10799
2022-12-13T22:30:19.110 INFO (pid:10786) [services] - LanguageClient clangd state change: starting => running
2022-12-13T22:30:19.125 INFO (pid:10786) [services] - service clangd started
2022-12-13T22:30:19.134 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-13T22:30:19.137 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-13T22:30:35.969 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-13T22:30:35.974 INFO (pid:10786) [attach] - receive notification: highlight []
....
2022-12-13T22:37:19.080 INFO (pid:10786) [attach] - receive notification: jumpDefinition []
2022-12-13T22:37:27.948 ERROR (pid:10786) [node-client] - request error on "nvim_call_function" [
  'coc#util#jump',
  [
    'split +res',
    '/home/jlm/crypt/Devel/projets/synctegrity/Conf.hpp',
    [ 10, 7 ]
  ]
] Vim(split):E325: ATTENTION on api "call_function" ["coc#util#jump",["split +res","/home/jlm/crypt/Devel/projets/synctegrity/Conf.hpp",[10,7]]] Error
    at ID.request (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:1:29672)
    at ID.call (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:6:3815)
    at Wg.jumpTo (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:178:2398)
    at O0.jumpTo (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:192:4812)
    at Gm.handleLocations (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:266:6404)
    at Gm.gotoDefinition (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:266:4184)
    at async bb.cocAction (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:280:20891)
    at async ID.<anonymous> (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:280:22378)
2022-12-13T22:37:27.951 ERROR (pid:10786) [node-client] - Error on notification "jumpDefinition": Vim(split):E325: ATTENTION on api "call_function" ["coc#util#jump",["split +res","/home/jlm/crypt/Devel/projets/synctegrity/Conf.hpp",[10,7]]] Error
    at ID.echoError (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:7:1869)
    at ID.<anonymous> (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:280:22415)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-12-13T22:37:27.952 ERROR (pid:10786) [attach] - Error on notification jumpDefinition Error: request error on nvim_call_function - Vim(split):E325: ATTENTION on api "call_function" ["coc#util#jump",["split +res","/home/jlm/crypt/Devel/projets/synctegrity/Conf.hpp",[10,7]]]
    at Wg.jumpTo (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:178:2398)
    at O0.jumpTo (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:192:4812)
    at Gm.handleLocations (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:266:6404)
    at Gm.gotoDefinition (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:266:4184)
    at async bb.cocAction (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:280:20891)
    at async ID.<anonymous> (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:280:22378)
2022-12-13T22:37:28.271 INFO (pid:10786) [attach] - receive notification: highlight []
...
2022-12-15T22:11:51.873 WARN (pid:10786) [plugin] - Slow action "highlight" cost 4045ms
2022-12-15T22:11:51.874 WARN (pid:10786) [plugin] - Slow action "highlight" cost 4046ms
2022-12-15T22:11:51.875 WARN (pid:10786) [plugin] - Slow action "highlight" cost 4048ms
2022-12-15T22:11:51.875 WARN (pid:10786) [plugin] - Slow action "highlight" cost 4049ms
2022-12-15T22:11:51.876 WARN (pid:10786) [plugin] - Slow action "highlight" cost 4048ms
2022-12-15T22:11:51.876 WARN (pid:10786) [plugin] - Slow action "highlight" cost 4049ms
2022-12-15T22:11:51.877 WARN (pid:10786) [plugin] - Slow action "highlight" cost 4051ms
2022-12-15T22:11:51.877 WARN (pid:10786) [plugin] - Slow action "highlight" cost 4051ms
2022-12-15T22:11:51.878 WARN (pid:10786) [plugin] - Slow action "highlight" cost 4052ms
2022-12-15T22:11:51.878 WARN (pid:10786) [plugin] - Slow action "highlight" cost 4053ms
2022-12-15T22:11:51.879 WARN (pid:10786) [plugin] - Slow action "highlight" cost 4047ms
2022-12-15T22:11:51.879 WARN (pid:10786) [plugin] - Slow action "highlight" cost 4048ms
....
2022-12-16T00:01:06.195 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:06.196 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:14.883 INFO (pid:10786) [attach] - receive notification: checkJsonExtension []
2022-12-16T00:01:15.297 INFO (pid:10786) [services] - LanguageClient Json language server state change: stopped => starting
2022-12-16T00:01:15.495 INFO (pid:10786) [language-client-index] - Language server "json" started with 19060
2022-12-16T00:01:15.496 INFO (pid:10786) [attach] - receive notification: highlight []
...
2022-12-16T00:01:15.526 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:15.527 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:15.528 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:15.529 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:15.530 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:16.155 INFO (pid:10786) [services] - LanguageClient Json language server state change: starting => running
2022-12-16T00:01:16.217 INFO (pid:10786) [services] - service json started
2022-12-16T00:01:22.549 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:22.551 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:22.619 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:22.620 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:44.472 INFO (pid:10786) [attach] - receive notification: installExtensions [ 'ccls' ]
2022-12-16T00:01:45.072 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:45.080 INFO (pid:10786) [attach] - receive notification: highlight []
.....
2022-12-16T00:01:45.158 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:45.255 ERROR (pid:10786) [extensions-index] - Error on install ccls TypeError: Cannot read properties of undefined (reading 'latest')
    at Ax.getInfo (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:236:9457)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Ax.install (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:236:10478)
    at async /home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:254:5268
2022-12-16T00:01:45.281 WARN (pid:10786) [plugin] - Slow action "installExtensions" cost 782ms
2022-12-16T00:01:53.614 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:53.623 INFO (pid:10786) [attach] - receive notification: highlight []
...
2022-12-16T00:01:53.774 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:53.775 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:53.776 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:01:53.776 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:03:04.007 INFO (pid:10786) [attach] - receive notification: installExtensions [ 'coc-ccls' ]
2022-12-16T00:03:04.515 INFO (pid:10786) [attach] - receive notification: highlight []
....
2022-12-16T00:03:04.746 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:03:04.746 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:03:04.750 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:03:04.871 INFO (pid:10786) [extension-installer] - Fetched info of coc-ccls {
  'dist.tarball': 'https://registry.npmjs.org/coc-ccls/-/coc-ccls-0.0.5.tgz',
  'engines.coc': '>=0.0.28',
  version: '0.0.5',
  name: 'coc-ccls'
}
2022-12-16T00:03:05.596 INFO (pid:10786) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-ccls/-/coc-ccls-0.0.5.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-ccls/-/coc-ccls-0.0.5.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-12-16T00:03:05.618 INFO (pid:10786) [model-download] - Downloaded https://registry.npmjs.org/coc-ccls/-/coc-ccls-0.0.5.tgz => /home/jlm/.config/coc/extensions/node_modules/coc-ccls-76272c28-5064-4850-a118-268b9f4f3fa1
2022-12-16T00:03:29.425 ERROR (pid:10786) [extensions-index] - Error on install coc-ccls Error: main file ./lib/extension.js not found, you may need to build the project.
    at cS.loadExtension (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:253:58722)
    at /home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:254:5450
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-12-16T00:03:29.428 WARN (pid:10786) [plugin] - Slow action "installExtensions" cost 25415ms
2022-12-16T00:05:37.964 INFO (pid:10786) [attach] - receive notification: highlight []
....
2022-12-16T00:05:39.931 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:05:39.933 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:05:39.934 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:05:42.152 INFO (pid:10786) [attach] - receive notification: installExtensions [ 'coc-ccls' ]
2022-12-16T00:05:42.640 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:05:42.649 INFO (pid:10786) [attach] - receive notification: highlight []
....

2022-12-16T00:05:42.720 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:05:42.720 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:05:42.721 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:05:42.721 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:05:42.723 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:05:43.054 INFO (pid:10786) [extension-installer] - Fetched info of coc-ccls {
  'dist.tarball': 'https://registry.npmjs.org/coc-ccls/-/coc-ccls-0.0.5.tgz',
  'engines.coc': '>=0.0.28',
  version: '0.0.5',
  name: 'coc-ccls'
}
2022-12-16T00:05:43.336 INFO (pid:10786) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-ccls/-/coc-ccls-0.0.5.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-ccls/-/coc-ccls-0.0.5.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-12-16T00:05:43.340 INFO (pid:10786) [model-download] - Downloaded https://registry.npmjs.org/coc-ccls/-/coc-ccls-0.0.5.tgz => /home/jlm/.config/coc/extensions/node_modules/coc-ccls-4f1baaa8-607f-4cf0-b39b-3439a583a6e2
2022-12-16T00:05:54.828 ERROR (pid:10786) [extensions-index] - Error on install coc-ccls Error: main file ./lib/extension.js not found, you may need to build the project.
    at cS.loadExtension (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:253:58722)
    at /home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:254:5450
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-12-16T00:05:54.842 WARN (pid:10786) [plugin] - Slow action "installExtensions" cost 12677ms
2022-12-16T00:15:20.105 INFO (pid:10786) [attach] - receive notification: highlight []
...
2022-12-16T00:15:22.609 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:15:22.616 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:15:22.636 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:15:49.014 INFO (pid:10786) [attach] - receive notification: openList []
2022-12-16T00:16:05.662 INFO (pid:10786) [attach] - receive notification: openList [ 'extensions' ]
2022-12-16T00:16:20.519 ERROR (pid:10786) [node-client] - Extension coc-ccls not registered! Error: Extension coc-ccls not registered!
    at cS.activate (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:253:58216)
    at addAction.persist [as execute] (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:253:14214)
    at /home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:253:3325
    at Array.map (<anonymous>)
    at nm.doItemAction (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:253:3300)
    at nm.doAction (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:248:348)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async XL.doAction (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:253:33526)
    at async /home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:246:12259
    at async Vf.doAction (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:246:18222)
2022-12-16T00:16:43.631 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:16:43.643 INFO (pid:10786) [attach] - receive notification: highlight []
....
2022-12-16T00:18:34.199 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:18:34.199 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:18:34.200 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:18:34.200 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:18:34.201 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:18:34.201 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:19:09.830 INFO (pid:10786) [attach] - receive notification: updateExtensions []
2022-12-16T00:19:10.462 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:19:10.478 INFO (pid:10786) [attach] - receive notification: highlight []
....
2022-12-16T00:19:10.523 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:19:10.524 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:19:10.527 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:19:10.528 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:19:11.238 INFO (pid:10786) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-json/-/coc-json-1.8.0.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-json/-/coc-json-1.8.0.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-12-16T00:19:11.245 INFO (pid:10786) [model-download] - Downloaded https://registry.npmjs.org/coc-json/-/coc-json-1.8.0.tgz => /home/jlm/.config/coc/extensions/node_modules/coc-json-ac5d0ef1-2bb0-43d1-9b88-4eccfb1a87fd
2022-12-16T00:19:11.284 INFO (pid:10786) [model-download] - Download completed: URL {
  href: 'https://registry.npmjs.org/coc-clangd/-/coc-clangd-0.27.0.tgz',
  origin: 'https://registry.npmjs.org',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  port: '',
  pathname: '/coc-clangd/-/coc-clangd-0.27.0.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-12-16T00:19:11.289 INFO (pid:10786) [model-download] - Downloaded https://registry.npmjs.org/coc-clangd/-/coc-clangd-0.27.0.tgz => /home/jlm/.config/coc/extensions/node_modules/coc-clangd-cd20f9e5-1c18-47b2-b7dc-3c0eb4234fb8
2022-12-16T00:19:11.910 INFO (pid:10786) [services] - LanguageClient clangd state change: stopped => starting
2022-12-16T00:19:12.066 INFO (pid:10786) [language-client-index] - Language server "clangd" started with 20953
2022-12-16T00:19:12.382 INFO (pid:10786) [services] - LanguageClient clangd state change: starting => running
2022-12-16T00:19:12.434 INFO (pid:10786) [services] - service clangd started
2022-12-16T00:19:13.237 WARN (pid:10786) [plugin] - Slow action "updateExtensions" cost 3406ms
2022-12-16T00:19:38.011 INFO (pid:10786) [attach] - receive notification: highlight []
....
2022-12-16T00:22:11.163 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:22:11.164 INFO (pid:10786) [attach] - receive notification: highlight []
2022-12-16T00:22:14.164 INFO (pid:10786) [attach] - receive notification: showInfo []

## Describe the bug

:CocInstall coc-ccls 
fail to install 
- ✗ coc-ccls main file ./lib/extension.js not found, you may need to build the project.

I need coc-ccls because clangd don't support gcc and I need some C++23 features not supported by clang

## Reproduce the bug

: cocInstall coc-ccls

**Comment by fannheyward** [comment]
It's coc-ccls's issue because it's not stable to use https://github.com/Maxattax97/coc-ccls/issues/1.

You can setup ccls in your coc-settings.json https://github.com/neoclide/coc.nvim/wiki/Language-servers#ccobjective-c, or install coc-ccls with your plugin manager https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#use-vims-plugin-manager-for-coc-extension.

**Comment by jlmxyz** [comment]
sorry if my question is dumb... but don't ```:CocInstall coc-ccls``` install a stable one? 
and in  https://github.com/neoclide/coc.nvim/wiki/Language-servers#ccobjective-c I only see settings to ccls but no settings to set a coc-ccls version...

**Comment by chemzqm** [comment]
The package of coc-ccls on npm is borken, seems it's not well maintained.

**Comment by jlmxyz** [comment]
so I installed coc-ccls by adding in .vimrc
```
Plug 'Maxattax97/coc-ccls', {'do': 'yarn install --frozen-lockfile'}
```
then done a ``` :PlugInstall ``` in vim, evrything succeed.

in coc-settings.json (:CocConfig )
```
{
...."coc.preferences.jumpCommand":."split.+res",
...."languageserver":.{
......"ccls":.{
........"command":."ccls",
........"filetypes":.["c",."cc",."cpp",."c++",."objc",."objcpp"],
........"rootPatterns":.[".ccls",."compile_commands.json",.".git/",.".hg/"],
........"initializationOptions":.{
............"cache":.{
.............."directory":."/tmp/ccls"
............}
..........}
......}
....}
}
```
then restarted vim... but it says at startup : 
```
[services] - Server languageserver.ccls failed to start: Error: Launching server "languageserver.ccls" using command ccls failed.
    at /home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:245:6582
    at async _d.createConnection (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:241:10649)

```

**Comment by jlmxyz** [comment]
ok, replying to myself for others

ccls need to be installed aside :  https://github.com/MaskRay/ccls/wiki/Build
in my case ```emerge dev-lang/ccls```

**Comment by jlmxyz** [comment]
but something is wrong....
```ps aexf ``` show ccls is laucnhed
/tmp/ccls is populated with some ccls data
but
no highlighting, no jump to definition/implementation... and errors in CocInfo
```
2022-12-24T11:50:22.394 ERROR (pid:27179) [provider-manager] - Provider error on provideDefinition: ph [Error]: not indexed
    at je (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:10:233)
    at Ji (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:9:6874)
    at Immediate.<anonymous> (/home/jlm/crypt/conf/vim/.vim/plugged/coc.nvim/build/index.js:9:6721)
    at process.processImmediate (node:internal/timers:471:21) {
  code: -32600,
  data: undefined
}

```

seems ccls didn't indexed
