### ISSUE TITLE
Initial install throws 404

### ISSUE THREAD

**Issue by jneidel** [neoclide/coc.nvim#4463]
## Result from CocInfo

```
## versions

vim version: NVIM v0.9.0-dev-503+ga442c9f556
node version: v19.2.0
coc.nvim version: 0.0.82-b11a93ba 2022-12-25 15:19:13 +0800
coc.nvim directory: /home/jneidel/.local/share/nvim/site/pack/paqs/start/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2023-01-02T10:26:10.996 INFO (pid:1047330) [plugin] - coc.nvim initialized with node: v19.2.0 after 451
2023-01-02T10:26:12.052 ERROR (pid:1047330) [model-fetch] - Fetch error for https://registry.npmjs.org/coc-tsserver%20coc-json%20coc-html%20coc-css%20coc-highlight%20coc-yank: {
  method: 'GET',
  hostname: 'registry.npmjs.org',
  port: 443,
  path: '/coc-tsserver%20coc-json%20coc-html%20coc-css%20coc-highlight%20coc-yank',
  agent: null,
  rejectUnauthorized: true,
  maxRedirects: 3,
  headers: {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64)',
    'Accept-Encoding': 'gzip, deflate'
  },
  timeout: 10000,
  buffer: true
} Error: Bad response from https://registry.npmjs.org/coc-tsserver%20coc-json%20coc-html%20coc-css%20coc-highlight%20coc-yank: 404
    at Qn.<anonymous> (/home/jneidel/.local/share/nvim/site/pack/paqs/start/coc.nvim/build/index.js:225:4377)
    at Qn.emit (node:events:525:35)
    at Qn._processResponse (/home/jneidel/.local/share/nvim/site/pack/paqs/start/coc.nvim/build/index.js:214:4694)
    at Qn._onNativeResponse (/home/jneidel/.local/share/nvim/site/pack/paqs/start/coc.nvim/build/index.js:214:1356)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:688:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:530:22)
    at TLSSocket.emit (node:events:513:28)
```

## Describe the bug

Upon install (branch="release") I get this Installing error every time I open vim.

![screenshot_23-01-02_10:12:00](https://user-images.githubusercontent.com/25589715/210213127-99ef593a-0a67-4267-84be-a86a4a798d89.png)

```
[coc.nvim] Error on install coc-tsserver coc-json coc-html coc-css coc-highlight coc-yank: Error: Bad response from https://registry.npmjs.org/coc-tsserver%20coc-json%20coc-html%20coc-css%20coc-highlight%20coc-yank: 404   
```

How can I disable this broken initial install? Everything else works fine, but with this thing popping up everytime I open vim it's unusable.

## Reproduce the bug

Open [https://registry.npmjs.org/coc-tsserver%20coc-json%20coc-html%20coc-css%20coc-highlight%20coc-yank](https://registry.npmjs.org/coc-tsserver%20coc-json%20coc-html%20coc-css%20coc-highlight%20coc-yank) for a 404.

**Comment by chemzqm** [comment]
You have unexpected global variable.

**Comment by jneidel** [comment]
Thanks.

It turns out I had `let g:coc_global_extensions = "coc-tsserver coc-json coc-html coc-css coc-highlight coc-yank"` declared in some config file.

The correct syntax that works fine is: `let g:coc_global_extensions = [ "coc-tsserver", "coc-json", "coc-html", "coc-css", "coc-highlight", "coc-yank" ]`
