### ISSUE TITLE
Uncaught exception: Unexpected token '<' <!DOCTYPE is not valid JSON

### ISSUE THREAD

**Issue by KoBruhh** [neoclide/coc.nvim#4476]
## versions

vim version: NVIM v0.8.2
node version: v19.4.0
coc.nvim version: 0.0.82-b11a93ba 2022-12-25 15:19:13 +0800
coc.nvim directory: /home/kobruh/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim
```
2023-01-15T09:23:49.207 ERROR (pid:9964) [extensions-index] - Error on load package.json of coc-ccls Error: main file ./lib/extension.js not found, you may need to build the project.
    at z4 (/home/kobruh/.vim/plugged/coc.nvim/build/index.js:250:21037)
    at async j0.globalExtensions (/home/kobruh/.vim/plugged/coc.nvim/build/index.js:251:7124)
    at async j0.init (/home/kobruh/.vim/plugged/coc.nvim/build/index.js:251:3671)
    at async cb.init (/home/kobruh/.vim/plugged/coc.nvim/build/index.js:276:45734)
    at async EventEmitter.<anonymous> (/home/kobruh/.vim/plugged/coc.nvim/build/index.js:276:47625)
2023-01-15T09:23:49.380 WARN (pid:9964) [workspace] - Extension "coc-lists" registered synchronized autocmd "VimLeavePre", which could be slow.
2023-01-15T09:23:49.597 WARN (pid:9964) [workspace] - workspace.createOutputChannel is deprecated, please use window.createOutputChannel instead. 
    at Object.<anonymous> (/home/kobruh/.config/coc/extensions/node_modules/coc-tailwindcss/out/index.js:14:7870)
    at Generator.next (<anonymous>)
2023-01-15T09:23:49.622 INFO (pid:9964) [extension:coc-git] - Looking for git in: git
2023-01-15T09:23:49.651 WARN (pid:9964) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at new t.Actions (/home/kobruh/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:8301)
    at t.activate (/home/kobruh/.config/coc/extensions/node_modules/coc-actions/out/index.js:1:15288)
2023-01-15T09:23:50.202 INFO (pid:9964) [plugin] - coc.nvim initialized with node: v19.4.0 after 1166
2023-01-15T09:23:50.203 INFO (pid:9964) [services] - LanguageClient ESLint state change: stopped => starting
2023-01-15T09:23:50.263 INFO (pid:9964) [language-client-index] - Language server "eslint" started with 9997
2023-01-15T09:23:50.277 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 3 ]
2023-01-15T09:23:50.284 WARN (pid:9964) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at t.initStatusBar (/home/kobruh/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:156009)
    at t.activate (/home/kobruh/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23162)
2023-01-15T09:23:50.298 INFO (pid:9964) [language-client-index] - Language server "cSpell" started with 9998
2023-01-15T09:23:50.518 INFO (pid:9964) [services] - LanguageClient ESLint state change: starting => running
2023-01-15T09:23:50.523 INFO (pid:9964) [services] - service eslint started
2023-01-15T09:23:50.800 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 12 ]
2023-01-15T09:23:51.837 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 3 ]
2023-01-15T09:23:52.717 ERROR (pid:9964) [server] - uncaughtException SyntaxError: Unexpected token '<', "






<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at getCandidates (/home/kobruh/.config/coc/extensions/node_modules/coc-github/lib/index.js:71:21)
    at Request._callback (/home/kobruh/.config/coc/extensions/node_modules/coc-github/lib/index.js:57:30)
    at self.callback (/home/kobruh/.config/coc/extensions/node_modules/coc-github/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.<anonymous> (/home/kobruh/.config/coc/extensions/node_modules/coc-github/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:513:28)
    at IncomingMessage.<anonymous> (/home/kobruh/.config/coc/extensions/node_modules/coc-github/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
2023-01-15T09:23:56.849 WARN (pid:9964) [completion-complete] - Completion timeout after 5000ms [ 'github' ]
2023-01-15T09:24:22.707 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 3 ]
2023-01-15T09:24:22.708 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 3 ]
2023-01-15T09:24:22.800 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 11 ]
2023-01-15T09:26:13.747 INFO (pid:9964) [attach] - receive notification: showInfo []
2023-01-15T09:26:13.794 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 3 ]
2023-01-15T09:26:13.797 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 6 ]
2023-01-15T09:26:13.806 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 7, 3 ]
2023-01-15T09:26:13.807 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 3 ]
2023-01-15T09:26:13.837 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 12 ]
2023-01-15T09:26:13.837 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 3 ]
2023-01-15T09:26:16.131 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 8, 3 ]
2023-01-15T09:26:16.132 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 3 ]
2023-01-15T09:26:16.134 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 6 ]
2023-01-15T09:26:16.238 INFO (pid:9964) [attach] - receive notification: doAutocmd [ 12 ]
2023-01-15T09:26:17.738 INFO (pid:9964) [attach] - receive notification: showInfo []
```

## Describe the bug

Everytime when I hit a key on keyboard, an error accurs at the bottom as shown in image:

![Screenshot_20230115_092357](https://user-images.githubusercontent.com/101834410/212526359-cb5c248d-17a3-481b-bbc5-8211decddb2f.png)

```[coc.nvim]: Uncaught exception: Unexpected token '<', "
<!DOCTYPE "... is not valid JSON
```

## Reproduce the bug
with this init.vim:
```vim
call plug#begin(".vim/plugged")
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```
I get the same error which is:

![Screenshot_20230115_094341](https://user-images.githubusercontent.com/101834410/212526945-1289f04e-fc41-4478-8004-43e8f9099f23.png)

**Comment by fannheyward** [comment]
Looks like coc-github was requesting from GitHub but got invalid response, it's not coc.nvim's issue.

**Comment by KoBruhh** [comment]
could you describe where is the error so I can solve it!?

**Comment by KoBruhh** [comment]
bcz it is obvious that it is not a source code bug

**Comment by fannheyward** [comment]
You're using coc-github that'll request to GitHub for some completions, but requests failed.  You can disable or uninstall coc-github and try again.

**Comment by KoBruhh** [comment]
I have tried to reinstall coc.nvim plugin several times. but that didn't work

**Comment by KoBruhh** [comment]
any difference between coc-github and coc.nvim?

**Comment by fannheyward** [comment]
`coc-github` is an extension of coc.nvim.

**Comment by fannheyward** [comment]
Run `:CocUninstall coc-github` and try again.

**Comment by KoBruhh** [comment]
thank you for your help. apriciate it.

btw best completion plugin out there thx to build it :D

my mood came out today
