### ISSUE TITLE
Can't scroll pum using `coc#float#scroll(1)`

### ISSUE THREAD

**Issue by timsu92** [neoclide/coc.nvim#4536]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.2 8024919
node version: v18.12.1
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /home/tim/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2023-02-27T21:24:42.460 INFO (pid:41827) [plugin] - coc.nvim initialized with node: v18.12.1 after 217
2023-02-27T21:24:42.469 WARN (pid:41827) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at t.initStatusBar (/home/tim/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:156009)
    at t.activate (/home/tim/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23162)
2023-02-27T21:24:42.472 INFO (pid:41827) [services] - LanguageClient clangd state change: stopped => starting
2023-02-27T21:24:42.478 INFO (pid:41827) [language-client-index] - Language server "cSpell" started with 41844
2023-02-27T21:24:42.487 INFO (pid:41827) [language-client-index] - Language server "clangd" started with 41850
2023-02-27T21:24:42.575 INFO (pid:41827) [services] - LanguageClient clangd state change: starting => running
2023-02-27T21:24:42.589 INFO (pid:41827) [services] - service clangd started
2023-02-27T21:24:42.721 INFO (pid:41827) [core-watchman] - watchman watching project: /home/tim/.cache
2023-02-27T21:24:46.421 INFO (pid:41827) [attach] - receive notification: highlight []
2023-02-27T21:24:47.853 INFO (pid:41827) [attach] - receive notification: highlight []
2023-02-27T21:24:59.932 INFO (pid:41827) [attach] - receive notification: showInfo []


```

## Describe the bug

I have the followings in `.vimrc`:
```vim
function! EchoWarn(text)
	echohl WarningMsg
	echo a:text
	echohl None
	return ""
endfunction
```
```vim
if has('nvim-0.4.0') || has('patch-8.2.0750')
	inoremap <silent><nowait><expr> <c-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : EchoWarn("[coc] Scroll not exist")
	inoremap <silent><nowait><expr> <c-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : EchoWarn("[coc] Scroll not exist")
	nnoremap <silent><nowait><expr> <c-f> coc#float#has_scroll() ? coc#float#scroll(1) : EchoWarn("[coc] Scroll not exist")
	nnoremap <silent><nowait><expr> <c-b> coc#float#has_scroll() ? coc#float#scroll(0) : EchoWarn("[coc] Scroll not exist")
	vnoremap <silent><nowait><expr> <c-f> coc#float#has_scroll() ? coc#float#scroll(1) : EchoWarn("[coc] Scroll not exist")
	vnoremap <silent><nowait><expr> <c-b> coc#float#has_scroll() ? coc#float#scroll(0) : EchoWarn("[coc] Scroll not exist")
endif
```
I type something to show autocompletes with enough items to make the pum scrollable, and then press <kbd>ctrl</kbd><kbd>F</kbd>, and nothing happened.
I've checked that `coc#float#has_scroll()` is `1` and `EchoWarn()` wasn't executed.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

1. Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=~/.vim/plugged/coc.nvi
  filetype plugin indent on
  syntax on
  set hidden

  if has('nvim-0.4.0') || has('patch-8.2.0750')
	  inoremap <silent><nowait><expr> <c-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : EchoWarn("[coc] Scroll not exist")
	  inoremap <silent><nowait><expr> <c-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : EchoWarn("[coc] Scroll not exist")
	  nnoremap <silent><nowait><expr> <c-f> coc#float#has_scroll() ? coc#float#scroll(1) : EchoWarn("[coc] Scroll not exist")
	  nnoremap <silent><nowait><expr> <c-b> coc#float#has_scroll() ? coc#float#scroll(0) : EchoWarn("[coc] Scroll not exist")
	  vnoremap <silent><nowait><expr> <c-f> coc#float#has_scroll() ? coc#float#scroll(1) : EchoWarn("[coc] Scroll not exist")
	  vnoremap <silent><nowait><expr> <c-b> coc#float#has_scroll() ? coc#float#scroll(0) : EchoWarn("[coc] Scroll not exist")
  endif
  ```

2. Start (neo)vim with command: `vim -u mini.vim`

4. Type `c` in the end of `mini.vim` to see a suitable pum
5. Press <kbd>ctrl</kbd><kbd>F</kbd> or <kbd>ctrl</kbd><kbd>B</kbd>

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/33785401/221579535-28ef07f6-74a5-42c3-9806-6850a14991eb.png)

**Comment by timsu92** [comment]
Sorry, I mistaken this pum with another. Not a bug.
