### ISSUE TITLE
Gleam language  support 

### ISSUE THREAD

**Issue by carlotm** [neoclide/coc.nvim#4565]
Hi all,
The [Gleam programming language](https://gleam.run/) has a [built-in language server](https://gleam.run/news/v0.21-introducing-the-gleam-language-server/) that can be run with the command `gleam lsp`.

I added this section to the coc config:

```
"languageserver": {
  "gleam": {
    "command": "gleam lsp",
    "filetypes": ["gleam"]
  },
  ...
```

But I got an error when opening gleam files.
This is the coc log I get:

```
2023-03-13T08:59:11.547 INFO (pid:4714) [plugin] - coc.nvim initialized with node: v17.5.0 after ^[[33m161^[[39m
2023-03-13T08:59:11.548 INFO (pid:4714) [services] - LanguageClient gleam state change: stopped => starting
2023-03-13T08:59:11.555 INFO (pid:4714) [services] - LanguageClient gleam state change: starting => stopped
2023-03-13T08:59:11.557 ERROR (pid:4714) [services] - Server languageserver.gleam failed to start: Error: Launching server
"languageserver.gleam" using command gleam lsp failed.
    at /home/carloratm/dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:248:6419
    at async Nd.createConnection (/home/carloratm/dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:244:15252)
    at async Nd._start (/home/carloratm/dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:244:7748)
    at async Object.start (/home/carloratm/dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:249:5338)
2023-03-13T08:59:23.119 INFO (pid:4714) [attach] - receive notification: openLog []
```

Is there anything I am missing in the coc config?
How can I further debug this?

Thank you

**Comment by fannheyward** [comment]
Try `command gleam` and `args lsp `.

**Comment by carlotm** [comment]
I am sorry, should I try those ad commands in my shell, or as vim commands?

**Comment by fannheyward** [comment]
I mean `"command": "gleam"` and `"args": ["lsp"]` in your coc-settings.json.

**Comment by carlotm** [comment]
@fannheyward Thanks a lot! It's working great.
