### ISSUE TITLE
(non-reproducible) uncaughtException TypeError: Cannot read properties of undefined (reading 'length') 

### ISSUE THREAD

**Issue by promisedlandt** [neoclide/coc.nvim#4573]
## versions

vim version: VIM - Vi IMproved 9.0 9001384
node version: v18.15.0
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /home/nl/.vim/bundle/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2023-03-18T08:49:02.956 INFO (pid:34223) [plugin] - coc.nvim initialized with node: v18.15.0 after 141
2023-03-18T08:50:03.067 ERROR (pid:34223) [server] - uncaughtException TypeError: Cannot read properties of undefined (reading 'length')
    at Lce (/home/nl/.vim/bundle/coc.nvim/build/index.js:169:4384)
    at Jc.getLineOffsets (/home/nl/.vim/bundle/coc.nvim/build/index.js:171:1264)
    at Jc.offsetAt (/home/nl/.vim/bundle/coc.nvim/build/index.js:171:995)
    at Jc.getText (/home/nl/.vim/bundle/coc.nvim/build/index.js:171:479)
    at mp._fireContentChanges (/home/nl/.vim/bundle/coc.nvim/build/index.js:173:2301)
    at mp.<anonymous> (/home/nl/.vim/bundle/coc.nvim/build/index.js:171:2226)
    at Timeout.l [as _onTimeout] (/home/nl/.vim/bundle/coc.nvim/build/index.js:4:2881)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
2023-03-18T08:50:16.610 INFO (pid:34223) [attach] - receive notification: showInfo []

## Describe the bug

Sometimes, I get the error mentioned in the log. It happens when changing the buffer (by pasting or deleting), and when entering insert mode.
Other operations like movement and searching do not trigger the error. 

The error is limited to a buffer. Other buffers work fine. But of course it can happen with multiple buffers separately in the same vim session.

After `:CocRestart`, the error does not appear for the same buffer.

It happens with `[No Name]` buffers that are not saved to a file, and it happens with buffers that are read from a file.
Filetype seems to not matter, I had it at least on empty filetype, javascript, ruby, scheme, rust.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

:+1:  That's okay, maybe someone else will have the same problem and can find the issue :smiley:

**Comment by fannheyward** [comment]
non-reproducible issue is hard to debug and fix, I've made this test:

1. `cat test.js | vim -`
2. `:set ft=javascript`
3. do deleting / editing

But I can't reproduce this. From the error stacks, maybe something broken in https://github.com/neoclide/coc.nvim/blob/94dc1051415eed1f0ffa39446ed22c63e3d8eb14/src/model/textdocument.ts#L122-L127

**Comment by jiangtianli91** [comment]
I have this bug too, when I am editing wiki.vim's markdown files. I am also not sure about how to reproduce it...

**Comment by jiangtianli91** [comment]
```
2023-06-08T00:01:00.087 INFO (pid:77143) [plugin] - coc.nvim initialized with node: v19.4.0 after [33m140[39m
2023-06-08T00:03:32.721 ERROR (pid:77143) [server] - uncaughtException TypeError: Cannot read properties of undefined (reading 'length')
    at Lce (/Users/x/.vim/plugged/coc.nvim/build/index.js:169:4384)
    at Jc.getLineOffsets (/Users/x/.vim/plugged/coc.nvim/build/index.js:171:1264)
    at Jc.offsetAt (/Users/x/.vim/plugged/coc.nvim/build/index.js:171:995)
    at Jc.getText (/Users/x/.vim/plugged/coc.nvim/build/index.js:171:479)
    at mp._fireContentChanges (/Users/x/.vim/plugged/coc.nvim/build/index.js:173:2301)
    at mp.<anonymous> (/Users/x/.vim/plugged/coc.nvim/build/index.js:171:2226)
    at Timeout.l [as _onTimeout] (/Users/x/.vim/plugged/coc.nvim/build/index.js:4:2881)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
2023-06-08T00:03:32.875 ERROR (pid:77143) [server] - uncaughtException TypeError: Cannot read properties of undefined (reading 'length')
    at Lce (/Users/x/.vim/plugged/coc.nvim/build/index.js:169:4384)
    at Jc.getLineOffsets (/Users/x/.vim/plugged/coc.nvim/build/index.js:171:1264)
    at Jc.offsetAt (/Users/x/.vim/plugged/coc.nvim/build/index.js:171:995)
    at Jc.getText (/Users/x/.vim/plugged/coc.nvim/build/index.js:171:479)
    at mp._fireContentChanges (/Users/x/.vim/plugged/coc.nvim/build/index.js:173:2301)
    at mp.<anonymous> (/Users/x/.vim/plugged/coc.nvim/build/index.js:171:2226)
    at Timeout.l [as _onTimeout] (/Users/x/.vim/plugged/coc.nvim/build/index.js:4:2881)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
2023-06-08T00:03:33.078 ERROR (pid:77143) [server] - uncaughtException TypeError: Cannot read properties of undefined (reading 'length')
    at Lce (/Users/x/.vim/plugged/coc.nvim/build/index.js:169:4384)
    at Jc.getLineOffsets (/Users/x/.vim/plugged/coc.nvim/build/index.js:171:1264)
    at Jc.offsetAt (/Users/x/.vim/plugged/coc.nvim/build/index.js:171:995)
    at Jc.getText (/Users/x/.vim/plugged/coc.nvim/build/index.js:171:479)
    at mp._fireContentChanges (/Users/x/.vim/plugged/coc.nvim/build/index.js:173:2301)
    at mp.<anonymous> (/Users/x/.vim/plugged/coc.nvim/build/index.js:171:2226)
    at Timeout.l [as _onTimeout] (/Users/x/.vim/plugged/coc.nvim/build/index.js:4:2881)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
```

**Comment by mezuzza** [comment]
I have a dozen of these as well:
```
 2023-07-27T17:18:43.456 ERROR (pid:111136) [server] - uncaughtException TypeError: Cannot read properties of undefined (reading 'length')
   28     at Lce (/home/prasanth/.vim/plugged/coc.nvim/build/index.js:169:4384)
   29     at Jc.getLineOffsets (/home/prasanth/.vim/plugged/coc.nvim/build/index.js:171:1264)
   30     at Jc.offsetAt (/home/prasanth/.vim/plugged/coc.nvim/build/index.js:171:995)
   31     at Jc.getText (/home/prasanth/.vim/plugged/coc.nvim/build/index.js:171:479)
   32     at mp._fireContentChanges (/home/prasanth/.vim/plugged/coc.nvim/build/index.js:173:2301)
   33     at mp.<anonymous> (/home/prasanth/.vim/plugged/coc.nvim/build/index.js:171:2226)
   34     at Timeout.l [as _onTimeout] (/home/prasanth/.vim/plugged/coc.nvim/build/index.js:4:2881)
   35     at listOnTimeout (node:internal/timers:559:17)
   36     at processTimers (node:internal/timers:502:7)
   37 2023-07-27T17:18:44.073 ERROR (pid:111136) [server] - uncaughtException TypeError: Cannot read properties of undefined (reading 'length')
   38     at Lce (/home/prasanth/.vim/plugged/coc.nvim/build/index.js:169:4384)
   39     at Jc.getLineOffsets (/home/prasanth/.vim/plugged/coc.nvim/build/index.js:171:1264)
   40     at Jc.offsetAt (/home/prasanth/.vim/plugged/coc.nvim/build/index.js:171:995)
   41     at Jc.getText (/home/prasanth/.vim/plugged/coc.nvim/build/index.js:171:479)
   42     at mp._fireContentChanges (/home/prasanth/.vim/plugged/coc.nvim/build/index.js:173:2301)
   43     at mp.<anonymous> (/home/prasanth/.vim/plugged/coc.nvim/build/index.js:171:2226)
   44     at Timeout.l [as _onTimeout] (/home/prasanth/.vim/plugged/coc.nvim/build/index.js:4:2881)
   45     at listOnTimeout (node:internal/timers:559:17)
   46     at processTimers (node:internal/timers:502:7)
```

**Comment by mkdior** [comment]
Also running in to this, nothing to add, not sure how to repro. This only happens on unnamed buffers.
