### ISSUE TITLE
Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" 

### ISSUE THREAD

**Issue by pinggit** [neoclide/coc.nvim#4596]
this is a new installation on vim9 macOS.

it looks like same as https://github.com/neoclide/coc.nvim/issues/4368, but I see this in latest version.

```
## versions

vim version: VIM - Vi IMproved 9.0 9001400
node version: v19.8.1
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /Users/pings/.vim/bundle/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2023-04-06T22:52:15.219 INFO (pid:90385) [plugin] - coc.nvim initialized with node: v19.8.1 after 231
2023-04-06T22:52:20.894 INFO (pid:90385) [attach] - receive notification: checkJsonExtension []
2023-04-06T22:52:20.928 INFO (pid:90385) [services] - LanguageClient Json language server state change: stopped => starting
2023-04-06T22:52:20.931 INFO (pid:90385) [language-client-index] - Language server "json" started with 90421
2023-04-06T22:52:21.003 INFO (pid:90385) [services] - LanguageClient Json language server state change: starting => running
2023-04-06T22:52:21.006 INFO (pid:90385) [services] - service json started
2023-04-06T22:52:28.618 INFO (pid:90385) [attach] - receive notification: openList []
2023-04-06T22:52:28.663 ERROR (pid:90385) [node-client] - request error on "nvim_call_function" [ 'coc#list#create', [ 'bottom', 10, 'lists', false ] ] Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" ["coc#list#create",["bottom",10,"lists",false]]
    at lm.drawItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:119129)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:232:115025
    at rC.run (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:113015)
    at lm.onDidChangeItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:114781)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:233:7680
    at yT.invoke (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:14460)
    at lc.fire (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:15230)
    at cm.filterItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:233:5570)
2023-04-06T22:52:28.664 ERROR (pid:90385) [server] - unhandledRejection  Promise {
  <rejected> Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" ["coc#list#create",["bottom",10,"lists",false]]
      at lm.drawItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:119129)
      at /Users/pings/.vim/bundle/coc.nvim/build/index.js:232:115025
      at rC.run (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:113015)
      at lm.onDidChangeItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:114781)
      at /Users/pings/.vim/bundle/coc.nvim/build/index.js:233:7680
      at yT.invoke (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:14460)
      at lc.fire (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:15230)
      at cm.filterItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:233:5570)
} Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" ["coc#list#create",["bottom",10,"lists",false]]
    at lm.drawItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:119129)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:232:115025
    at rC.run (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:113015)
    at lm.onDidChangeItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:114781)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:233:7680
    at yT.invoke (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:14460)
    at lc.fire (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:15230)
    at cm.filterItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:233:5570)
2023-04-06T22:52:30.904 ERROR (pid:90385) [node-client] - request error on "nvim_call_function" [ 'coc#list#create', [ 'bottom', 10, 'lists', false ] ] Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" ["coc#list#create",["bottom",10,"lists",false]]
    at lm.drawItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:119129)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:232:115025
    at rC.run (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:113015)
    at lm.onDidChangeItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:114781)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:233:7680
    at yT.invoke (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:14460)
    at lc.fire (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:15230)
    at a (/Users/pings/.vim/bundle/coc.nvim/build/index.js:233:5775)
2023-04-06T22:52:30.904 ERROR (pid:90385) [server] - unhandledRejection  Promise {
  <rejected> Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" ["coc#list#create",["bottom",10,"lists",false]]
      at lm.drawItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:119129)
      at /Users/pings/.vim/bundle/coc.nvim/build/index.js:232:115025
      at rC.run (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:113015)
      at lm.onDidChangeItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:114781)
      at /Users/pings/.vim/bundle/coc.nvim/build/index.js:233:7680
      at yT.invoke (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:14460)
      at lc.fire (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:15230)
      at a (/Users/pings/.vim/bundle/coc.nvim/build/index.js:233:5775)
} Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" ["coc#list#create",["bottom",10,"lists",false]]
    at lm.drawItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:119129)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:232:115025
    at rC.run (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:113015)
    at lm.onDidChangeItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:114781)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:233:7680
    at yT.invoke (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:14460)
    at lc.fire (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:15230)
    at a (/Users/pings/.vim/bundle/coc.nvim/build/index.js:233:5775)
2023-04-06T22:52:31.391 ERROR (pid:90385) [node-client] - request error on "nvim_call_function" [ 'coc#list#create', [ 'bottom', 10, 'lists', false ] ] Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" ["coc#list#create",["bottom",10,"lists",false]]
    at lm.drawItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:119129)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:232:115025
    at rC.run (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:113015)
    at lm.onDidChangeItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:114781)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:233:7680
    at yT.invoke (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:14460)
    at lc.fire (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:15230)
    at a (/Users/pings/.vim/bundle/coc.nvim/build/index.js:233:5775)
2023-04-06T22:52:31.391 ERROR (pid:90385) [server] - unhandledRejection  Promise {
  <rejected> Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" ["coc#list#create",["bottom",10,"lists",false]]
      at lm.drawItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:119129)
      at /Users/pings/.vim/bundle/coc.nvim/build/index.js:232:115025
      at rC.run (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:113015)
      at lm.onDidChangeItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:114781)
      at /Users/pings/.vim/bundle/coc.nvim/build/index.js:233:7680
      at yT.invoke (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:14460)
      at lc.fire (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:15230)
      at a (/Users/pings/.vim/bundle/coc.nvim/build/index.js:233:5775)
} Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" ["coc#list#create",["bottom",10,"lists",false]]
    at lm.drawItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:119129)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:232:115025
    at rC.run (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:113015)
    at lm.onDidChangeItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:114781)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:233:7680
    at yT.invoke (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:14460)
    at lc.fire (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:15230)
    at a (/Users/pings/.vim/bundle/coc.nvim/build/index.js:233:5775)
2023-04-06T22:52:32.010 ERROR (pid:90385) [node-client] - request error on "nvim_call_function" [ 'coc#list#create', [ 'bottom', 10, 'lists', false ] ] Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" ["coc#list#create",["bottom",10,"lists",false]]
    at lm.drawItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:119129)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:232:115025
    at rC.run (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:113015)
    at lm.onDidChangeItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:114781)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:233:7680
    at yT.invoke (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:14460)
    at lc.fire (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:15230)
    at a (/Users/pings/.vim/bundle/coc.nvim/build/index.js:233:5775)
2023-04-06T22:52:32.010 ERROR (pid:90385) [server] - unhandledRejection  Promise {
  <rejected> Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" ["coc#list#create",["bottom",10,"lists",false]]
      at lm.drawItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:119129)
      at /Users/pings/.vim/bundle/coc.nvim/build/index.js:232:115025
      at rC.run (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:113015)
      at lm.onDidChangeItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:114781)
      at /Users/pings/.vim/bundle/coc.nvim/build/index.js:233:7680
      at yT.invoke (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:14460)
      at lc.fire (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:15230)
      at a (/Users/pings/.vim/bundle/coc.nvim/build/index.js:233:5775)
} Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" ["coc#list#create",["bottom",10,"lists",false]]
    at lm.drawItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:119129)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:232:115025
    at rC.run (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:113015)
    at lm.onDidChangeItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:114781)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:233:7680
    at yT.invoke (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:14460)
    at lc.fire (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:15230)
    at a (/Users/pings/.vim/bundle/coc.nvim/build/index.js:233:5775)
2023-04-06T22:52:32.587 ERROR (pid:90385) [node-client] - request error on "nvim_call_function" [ 'coc#list#create', [ 'bottom', 10, 'lists', false ] ] Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" ["coc#list#create",["bottom",10,"lists",false]]
    at lm.drawItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:119129)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:232:115025
    at rC.run (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:113015)
    at lm.onDidChangeItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:114781)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:233:7680
    at yT.invoke (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:14460)
    at lc.fire (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:15230)
    at a (/Users/pings/.vim/bundle/coc.nvim/build/index.js:233:5775)
2023-04-06T22:52:32.588 ERROR (pid:90385) [server] - unhandledRejection  Promise {
  <rejected> Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" ["coc#list#create",["bottom",10,"lists",false]]
      at lm.drawItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:119129)
      at /Users/pings/.vim/bundle/coc.nvim/build/index.js:232:115025
      at rC.run (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:113015)
      at lm.onDidChangeItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:114781)
      at /Users/pings/.vim/bundle/coc.nvim/build/index.js:233:7680
      at yT.invoke (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:14460)
      at lc.fire (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:15230)
      at a (/Users/pings/.vim/bundle/coc.nvim/build/index.js:233:5775)
} Error: request error on "nvim_call_function" - Vim(throw):E608: Cannot :throw exceptions with 'Vim' prefix on api "call_function" ["coc#list#create",["bottom",10,"lists",false]]
    at lm.drawItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:119129)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:232:115025
    at rC.run (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:113015)
    at lm.onDidChangeItems (/Users/pings/.vim/bundle/coc.nvim/build/index.js:232:114781)
    at /Users/pings/.vim/bundle/coc.nvim/build/index.js:233:7680
    at yT.invoke (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:14460)
    at lc.fire (/Users/pings/.vim/bundle/coc.nvim/build/index.js:24:15230)
    at a (/Users/pings/.vim/bundle/coc.nvim/build/index.js:233:5775)
2023-04-06T22:56:45.333 INFO (pid:90385) [attach] - receive notification: showInfo []

```

**Comment by pinggit** [comment]
tested in linux. same exact issue...

https://gist.github.com/pinggit/3f84f9123f55aaf07c96dc6480872c4f

**Comment by fannheyward** [comment]
Tested with same vim 9.0.1400 on macOS with tmux, can't reproduce this...

**Comment by pinggit** [comment]
this is so weird. I simply could not make it work, in my macOS, and in my ubuntu...

**Comment by pinggit** [comment]
I tried with the mini config, and the error disappeared!
so this looks to be related to my configs. or maybe conflicting with some other plugins I have.
how can I narrow it down? is there any debug options to provide more clue?

**Comment by pinggit** [comment]
binary search turns out this config broke it.

```
"autocmd BufEnter * if ! StartsWith(expand('%:p'), "!") | lcd %:p:h | endif
augroup mybufenter
    autocmd!
    autocmd BufEnter * if
                \ (stridx(expand('%:p'), "!") < 0) &&
                \ (stridx(expand('%:p'), "scp://") < 0) &&
                \ (stridx(expand('%:p'), "gist:") < 0) &&
                \ (stridx(expand('%:p'), "fugitive") < 0)
                \ | lcd %:p:h | endif
augroup END
```

but why? how to modify this config to make it work with coc?

**Comment by fannheyward** [comment]
Looks like you use this augroup to `lcd` change working directory, have no idea about this.

**Comment by pinggit** [comment]
Hi, the config that I am using is common and useful.
it means once you open a file, it will set cwd to the folder of the file, which is most of the time good to do.
why will that break the coc plugin?
it is easy to reproduce...

**Comment by chemzqm** [comment]
Use 
```
"autocmd BufEnter * if ! StartsWith(expand('%:p'), "!") | lcd %:p:h | endif
augroup mybufenter
    autocmd!
    autocmd BufEnter * if
                \ (stridx(expand('%:p'), "!") < 0) &&
                \ (stridx(expand('%:p'), "list://") < 0) &&
                \ (stridx(expand('%:p'), "scp://") < 0) &&
                \ (stridx(expand('%:p'), "gist:") < 0) &&
                \ (stridx(expand('%:p'), "fugitive") < 0)
                \ | lcd %:p:h | endif
augroup END
```
Instead, or check for general url scheme.
