### ISSUE TITLE
coc-rename not working

### ISSUE THREAD

**Issue by Joonsey** [neoclide/coc.nvim#4680]
## versions

vim version: NVIM v0.9.0
node version: v19.9.0
coc.nvim version: 0.0.81-2522eee5 2022-06-14 19:03:29 +0800
coc.nvim directory: /home/johannesr/.local/share/nvim/plugged/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2023-06-21T03:06:37.569 INFO (pid:26199) [services] - registered service "languageserver.ccls"
2023-06-21T03:06:37.571 INFO (pid:26199) [services] - registered service "languageserver.csharp-ls"
2023-06-21T03:06:37.741 INFO (pid:26199) [services] - registered service "pyright"
2023-06-21T03:06:37.742 INFO (pid:26199) [services] - Pyright Server state change: stopped => starting
2023-06-21T03:06:37.744 INFO (pid:26199) [plugin] - coc.nvim initialized with node: v19.9.0 after 256ms
2023-06-21T03:06:37.746 INFO (pid:26199) [attach] - receive notification: highlight []
2023-06-21T03:06:38.085 INFO (pid:26199) [services] - Pyright Server state change: starting => running
2023-06-21T03:06:38.093 INFO (pid:26199) [services] - service pyright started
2023-06-21T03:06:38.182 INFO (pid:26199) [attach] - receive notification: highlight []
2023-06-21T03:06:38.622 INFO (pid:26199) [attach] - receive notification: highlight []
2023-06-21T03:06:43.164 WARN (pid:26199) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2023-06-21T03:06:44.164 WARN (pid:26199) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2023-06-21T03:06:44.388 WARN (pid:26199) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2023-06-21T03:06:44.691 WARN (pid:26199) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2023-06-21T03:06:45.069 WARN (pid:26199) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2023-06-21T03:06:45.324 WARN (pid:26199) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2023-06-21T03:06:45.563 WARN (pid:26199) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2023-06-21T03:06:45.851 WARN (pid:26199) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2023-06-21T03:06:46.148 WARN (pid:26199) [completion] - Suggest not triggered with input "", minimal trigger input length: 1
2023-06-21T03:06:47.867 INFO (pid:26199) [attach] - receive notification: highlight []
2023-06-21T03:06:48.269 INFO (pid:26199) [attach] - receive notification: highlight []
2023-06-21T03:06:48.949 INFO (pid:26199) [attach] - receive notification: highlight []
2023-06-21T03:06:53.654 INFO (pid:26199) [attach] - receive notification: highlight []
2023-06-21T03:07:01.670 INFO (pid:26199) [attach] - receive notification: highlight []
2023-06-21T03:07:02.063 INFO (pid:26199) [attach] - receive notification: highlight []
2023-06-21T03:07:02.861 INFO (pid:26199) [attach] - receive notification: highlight []
2023-06-21T03:07:04.387 INFO (pid:26199) [attach] - receive notification: codeAction [ 'V' ]
2023-06-21T03:07:04.509 WARN (pid:26199) [model-menu] - Ignored key press: c
2023-06-21T03:07:08.114 INFO (pid:26199) [attach] - receive notification: highlight []
2023-06-21T03:07:08.602 WARN (pid:26199) [plugin] - Slow action "codeAction" cost 4212ms
2023-06-21T03:07:08.903 INFO (pid:26199) [attach] - receive notification: highlight []
2023-06-21T03:07:12.456 INFO (pid:26199) [attach] - receive notification: highlight []
2023-06-21T03:07:12.963 INFO (pid:26199) [attach] - receive notification: rename []
2023-06-21T03:07:12.989 ERROR (pid:26199) [node-client] - request error on "nvim_call_function" [
  'coc#dialog#create_prompt_win',
  [
    'New name',
    'newmethod138',
    {
      rounded: true,
      maxWidth: 80,
      highlight: undefined,
      borderhighlight: undefined
    }
  ]
] function coc#dialog#create_prompt_win[16]..coc#float#create_float_win, line 81: Vim(call):E5248: Invalid character in group name Error
    at HM.request (/home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:29:43425)
    at HM.call (/home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:34:3815)
    at ru.show (/home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:274:18659)
    at /home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:275:12482
    at /home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:146:1282
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Uee.requestInput (/home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:275:12407)
    at async ox.rename (/home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:297:8711)
    at async Cx.cocAction (/home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:301:17532)
    at async HM.<anonymous> (/home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:301:19103)
2023-06-21T03:07:12.992 ERROR (pid:26199) [node-client] - Error on notification "rename": function coc#dialog#create_prompt_win[16]..coc#float#create_float_win, line 81: Vim(call):E5248: Invalid character in group name Error
    at HM.echoError (/home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:35:1869)
    at HM.<anonymous> (/home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:301:19140)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-06-21T03:07:12.993 ERROR (pid:26199) [attach] - Error: request error on nvim_call_function - function coc#dialog#create_prompt_win[16]..coc#float#create_float_win, line 81: Vim(call):E5248: Invalid character in group name
    at ru.show (/home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:274:18659)
    at /home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:275:12482
    at /home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:146:1282
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Uee.requestInput (/home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:275:12407)
    at async ox.rename (/home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:297:8711)
    at async Cx.cocAction (/home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:301:17532)
    at async HM.<anonymous> (/home/johannesr/.local/share/nvim/plugged/coc.nvim/build/index.js:301:19103)
2023-06-21T03:08:57.729 INFO (pid:26199) [attach] - receive notification: highlight []
2023-06-21T03:08:59.808 INFO (pid:26199) [attach] - receive notification: showInfo []

## Describe the bug

When i call the coc-rename function i get two errors and it breaks my neovim.

## Reproduce the bug

  ```vim
call plug#begin()
Plug 'editorconfig/editorconfig-vim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.0' }
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-fugitive'
Plug 'mattn/emmet-vim'
Plug 'pangloss/vim-javascript'
Plug 'leafgarland/typescript-vim'
Plug 'morhetz/gruvbox'
Plug 'peitalin/vim-jsx-typescript'
Plug 'styled-components/vim-styled-components', { 'branch': 'main' }
Plug 'jiangmiao/auto-pairs'
Plug 'drewtempelmeyer/palenight.vim'
Plug 'vim-airline/vim-airline'
Plug 'wlangstroth/vim-racket'
Plug 'sheerun/vim-polyglot'
Plug 'rust-lang/rust.vim'
Plug 'preservim/tagbar'
Plug 'universal-ctags/ctags'
Plug 'luochen1990/rainbow'
Plug 'itchyny/lightline.vim'
Plug 'tpope/vim-surround'
Plug 'neoclide/coc.nvim', { 'branch': 'release' }
Plug 'tommcdo/vim-lion'
Plug 'Shirk/vim-gas'
Plug 'ntpeters/vim-better-whitespace'
Plug 'puremourning/vimspector'
Plug 'jlcrochet/vim-razor'
call plug#end()

" Get syntax files from config folder
set runtimepath+=~/.config/nvim/syntax

" Theme
set background=dark
colorscheme gruvbox

" Disable C-z from job-controlling neovim
nnoremap <c-z> <nop>

" Remap C-c to <esc>
nmap <c-c> <esc>
imap <c-c> <esc>
vmap <c-c> <esc>
omap <c-c> <esc>

" netrw config
let g:netrw_keepdir = 0
let g:netrw_banner = 0
let g:netrw_liststyle = 3

" Syntax highlighting
syntax on

" Position in code
set number
set relativenumber
set ruler

" vimspector mappings
let g:vimspector_enable_mappings = 'HUMAN'

nnoremap <leader>ff <cmd>lua require('telescope.builtin').find_files()<cr>
nnoremap <leader>fg <cmd>lua require('telescope.builtin').live_grep()<cr>
nnoremap <leader>fb <cmd>lua require('telescope.builtin').buffers()<cr>
nnoremap <leader>fh <cmd>lua require('telescope.builtin').help_tags()<cr>

" fugitive git bindings
nnoremap <leader>gg :G<CR><CR>
nnoremap <leader>ga :Git add %:p<CR><CR>
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>gc :Gcommit -v -q<CR>
nnoremap <leader>gt :Gcommit -v -q %:p<CR>
nnoremap <leader>gd :Gdiff<CR>
nnoremap <leader>ge :Gedit<CR>
nnoremap <leader>gr :Gread<CR>
nnoremap <leader>gw :Gwrite<CR><CR>
nnoremap <leader>gl :silent! Glog<CR>:bot copen<CR>
nnoremap <leader>gp :Ggrep<Space>
nnoremap <leader>gm :Gmove<Space>
nnoremap <leader>gb :Git branch<Space>
nnoremap <leader>go :Git checkout<Space>
nnoremap <leader>gps :Git push<CR>
nnoremap <leader>gpl :Git pull<CR>

" Don't make noise
set visualbell

" default file encoding
set encoding=utf-8

" Line wrap
set wrap linebreak
" set wrap
set tabstop=4
set softtabstop=4
set shiftwidth=4
" Function to set tab width to n spaces
function! SetTab(n)
    let &l:tabstop=a:n
    let &l:softtabstop=a:n
    let &l:shiftwidth=a:n
    set expandtab
endfunction
command! -nargs=1 SetTab call SetTab(<f-args>)

" Function to trim extra whitespace in whole file
function! Trim()
    let l:save = winsaveview()
    keeppatterns %s/\s\+$//e
    call winrestview(l:save)
endfun

command! -nargs=0 Trim call Trim()

set laststatus=2

" Highlight search results
set hlsearch
set incsearch

" auto + smart indent for code
set autoindent
set smartindent

set t_Co=256

" ASM == JDH8
augroup jdh8_ft
  au!
  autocmd BufNewFile,BufRead *.asm    set filetype=jdh8
augroup END

" SQL++ == SQL
augroup sqlpp_ft
  au!
  autocmd BufNewFile,BufRead *.sqlp   set syntax=sql
augroup END

" .S == gas
augroup gas_ft
  au!
  autocmd BufNewFile,BufRead *.S      set syntax=gas
augroup END

" JFlex syntax highlighting
 augroup jfft
   au BufRead,BufNewFile *.flex,*.jflex    set filetype=jflex
 augroup END
 au Syntax jflex    so ~/.vim/syntax/jflex.vim

 " Mouse support
 set mouse=a

 " Map F8 to Tagbar
 nmap <F8> :TagbarToggle<CR>

 " CTags config
 let g:Tlist_Ctags_Cmd='/usr/local/Cellar/ctags/5.8_1/bin/ctags'

 " disable backup files
 set nobackup
 set nowritebackup

 " no delays!
 set updatetime=300

 set cmdheight=1
 set shortmess+=c

 set signcolumn=yes

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion.
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" Make <CR> auto-select the first completion item and notify coc.nvim to
" format on enter, <cr> could be remapped by other vim plugin
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" Formatting selected code.
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)

" Remap keys for applying codeAction to the current buffer.
nmap <leader>ac  <Plug>(coc-codeaction)
" Apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)

" Map function and class text objects
" NOTE: Requires 'textDocument.documentSymbol' support from the language server.
xmap if <Plug>(coc-funcobj-i)
omap if <Plug>(coc-funcobj-i)
xmap af <Plug>(coc-funcobj-a)
omap af <Plug>(coc-funcobj-a)
xmap ic <Plug>(coc-classobj-i)
omap ic <Plug>(coc-classobj-i)
xmap ac <Plug>(coc-classobj-a)
omap ac <Plug>(coc-classobj-a)

" Remap <C-f> and <C-b> for scroll float windows/popups.
if has('nvim-0.4.0') || has('patch-8.2.0750')
  nnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
  nnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
  inoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : "\<Right>"
  inoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : "\<Left>"
  vnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
  vnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
endif

" Use CTRL-S for selections ranges.
" Requires 'textDocument/selectionRange' support of language server.
nmap <silent> <C-s> <Plug>(coc-range-select)
xmap <silent> <C-s> <Plug>(coc-range-select)

" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocAction('format')

" Add `:Fold` command to fold current buffer.
command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

" Add (Neo)Vim's native statusline support.
" NOTE: Please see `:h coc-status` for integrations with external plugins that
" provide custom statusline: lightline.vim, vim-airline.
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

" Mappings for CoCList
" Show all diagnostics.
nnoremap <silent><nowait> <space>a  :<C-u>CocList diagnostics<cr>
" Manage extensions.
nnoremap <silent><nowait> <space>e  :<C-u>CocList extensions<cr>
" Show commands.
nnoremap <silent><nowait> <space>c  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>
" Do default action for next item.
nnoremap <silent><nowait> <space>j  :<C-u>CocNext<CR>
" Do default action for previous item.
nnoremap <silent><nowait> <space>k  :<C-u>CocPrev<CR>
" Resume latest coc list.
nnoremap <silent><nowait> <space>p  :<C-u>CocListResume<CR>

" add cocstatus into lightline
let g:lightline = {
	\ 'colorscheme': 'wombat',
	\ 'active': {
	\   'left': [ [ 'mode', 'paste' ],
	\             [ 'cocstatus', 'readonly', 'filename', 'modified' ] ]
	\ },
	\ 'component_function': {
	\   'cocstatus': 'coc#status'
	\ },
	\ }

autocmd User CocStatusChange,CocDiagnosticChange call lightline#update()

  ```

**Comment by fannheyward** [comment]
> coc.nvim version: 0.0.81-2522eee5 2022-06-14 19:03:29 +0800

Upgrade your coc.nvim to latest release, this has already been fixed.
