### ISSUE TITLE
Coc Error when renaming a symbol 

### ISSUE THREAD

**Issue by lzl19971215** [neoclide/coc.nvim#4751]
## Result from CocInfo

   vim version: NVIM v0.9.1                                                                                                                                            
    node version: v16.18.0                                                                                                                                            
    coc.nvim version: 0.0.82-7a50d4d9 2022-08-01 01:37:29 +0800                                                                                                      
    coc.nvim directory: /home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim                                                                               
    term: xterm                                                                                                                                                       
    platform: linux  
## Describe the bug
coc throw a error when trying to rename a symbol (the example is in a .ts file, but the error is not specified to certain language server)
![image](https://github.com/neoclide/coc.nvim/assets/63151530/85ad86e1-5a7d-4b55-874f-3e7dd3a0ac5b)

## Log of coc.nvim
  2023-09-08T20:49:10.388 INFO (pid:315051) [attach] - receive notification: rename []
  2023-09-08T20:49:10.397 ERROR (pid:315051) [node-client] - request error on "nvim_call_function" [
    'coc#dialog#create_prompt_win',
    [
      'New name',
      'a',
      {
        rounded: true,
        maxWidth: 80,
        highlight: undefined,
        borderhighlight: undefined
      }
    ]
  ] function coc#dialog#create_prompt_win[16]..coc#float#create_float_win[92]..<SNR>33_set_float_defaults, line 3: Vim(call):E5248: Invalid character in group name Error
      at HM.request (/home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:29:43425)
      at HM.call (/home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:34:3815)
      at nu.show (/home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:275:18593)
      at /home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:276:12482
      at /home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:146:1282
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Uee.requestInput (/home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:276:12407)
      at async sC.rename (/home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:298:8711)
      at async SC.cocAction (/home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:302:17434)
  2023-09-08T20:49:10.398 ERROR (pid:315051) [node-client] - Error on notification "rename": function coc#dialog#create_prompt_win[16]..coc#float#create_float_win[92]..<SNR>33_set_float_defaults, line 3: Vim(call):E5248: Invalid character in group name Error
      at HM.echoError (/home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:35:1869)
      at HM.<anonymous> (/home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:302:19061)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
  2023-09-08T20:49:10.398 ERROR (pid:315051) [attach] - Error: request error on nvim_call_function - function coc#dialog#create_prompt_win[16]..coc#float#create_float_win[92]..<SNR>33_set_float_defaults, line 3: Vim(call):E5248: Invalid character in group name
      at nu.show (/home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:275:18593)
      at /home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:276:12482
      at /home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:146:1282
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Uee.requestInput (/home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:276:12407)
      at async sC.rename (/home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:298:8711)
      at async SC.cocAction (/home/liziliang/.local/share/nvim/site/pack/coc/start/coc.nvim/build/index.js:302:17434)

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- I can produce the with following `init.vim` nvim config

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  nmap <leader>rn <Plug>(coc-rename)
  ```
These are the coc extensions I have installed:
![image](https://github.com/neoclide/coc.nvim/assets/63151530/0755855a-a63a-426a-85aa-10205253de0f)

I am new to nvim and coc, would be very appreciate if  someone can help me. Thanks!

**Comment by fannheyward** [comment]
> 0.0.82-7a50d4d9 2022-08-01 01:37:29 +0800

Upgrade to latest release and try again.

**Comment by lzl19971215** [comment]
It works, thanks a lot!
