### ISSUE TITLE
Ctrl+c no longer closes :CocList outline

### ISSUE THREAD

**Issue by ben-wall** [neoclide/coc.nvim#4754]
## versions

vim version: NVIM v0.9.1
node version: v18.15.0
coc.nvim version: 0.0.82-6e4e6eaf 2023-09-08 01:05:35 +0800
coc.nvim directory: /home/ben/.local/share/nvim/site/pack/packer/start/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2023-09-11T10:10:06.353 INFO (pid:29823) [plugin] - coc.nvim initialized with node: v18.15.0 after 295
2023-09-11T10:10:06.362 WARN (pid:29823) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at t.initStatusBar (/home/ben/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:156009)
    at t.activate (/home/ben/.config/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23162)
2023-09-11T10:10:06.374 INFO (pid:29823) [services] - LanguageClient lua state change: stopped => starting
2023-09-11T10:10:06.379 INFO (pid:29823) [language-client-index] - Language server "cSpell" started with 29840
2023-09-11T10:10:06.386 INFO (pid:29823) [language-client-index] - Language server "lua" started with 29846
2023-09-11T10:10:06.436 INFO (pid:29823) [services] - LanguageClient lua state change: starting => running
2023-09-11T10:10:06.441 INFO (pid:29823) [services] - service lua started
2023-09-11T10:10:29.183 INFO (pid:29823) [attach] - receive notification: doAutocmd [ 6 ]
2023-09-11T10:10:29.651 INFO (pid:29823) [attach] - receive notification: doAutocmd [ 6 ]
2023-09-11T10:10:30.075 INFO (pid:29823) [attach] - receive notification: doAutocmd [ 1 ]
2023-09-11T10:10:30.794 INFO (pid:29823) [attach] - receive notification: doAutocmd [ 6 ]
2023-09-11T10:11:17.037 INFO (pid:29823) [attach] - receive notification: doAutocmd [ 1 ]

## Describe the bug

:CocList outline no longer can be closed with ctrl+c, you have to use esc

## Reproduce the bug

open CocList outilne and try and close it with ctrl+c

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by fannheyward** [comment]
```json
  "list.normalMappings": {
    "<C-c>": "do:exit"
  },
  "list.insertMappings": {
    "<C-c>": "do:exit"
  },
```

**Comment by ben-wall** [comment]
thank you
