### ISSUE TITLE
The range of popup message and the range of underline is not same

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc.nvim#4781]
## Reproduce the bug

Install language server, then open a file:

## Screenshots (optional)

![Screenshot from 2023-10-17 02-05-43](https://github.com/neoclide/coc.nvim/assets/32936898/d0ff31da-82df-49f1-9e31-b0a30456d6cb)

The popup message have a range of 1-8.

![Screenshot from 2023-10-17 02-05-46](https://github.com/neoclide/coc.nvim/assets/32936898/f550a766-c1e4-45b0-b806-8cf57c3bd3f8)

The underline have a range of 1-7.

## versions

vim version: NVIM v0.9.4
node version: v18.18.0
coc.nvim version: 0.0.82-3dc6153a 2023-07-21 00:22:17 -0500
coc.nvim directory: /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release
term: tmux
platform: linux

## Log of coc.nvim

2023-10-17T02:02:13.688 INFO (pid:687831) [extension:coc-git] - Looking for git in: git
2023-10-17T02:02:14.061 INFO (pid:687831) [extension:coc-tabnine] - Using tabnine from /home/wzy/.config/coc/extensions/coc-tabnine-data/binaries/4.24.0/x86_64-unknown-linux-musl/TabNine
2023-10-17T02:02:14.130 INFO (pid:687831) [plugin] - coc.nvim initialized with node: v18.18.0 after 3005
2023-10-17T02:02:14.136 INFO (pid:687831) [services] - LanguageClient requirements state change: stopped => starting
2023-10-17T02:02:14.766 INFO (pid:687831) [language-client-index] - Language server "languageserver.requirements" started with 687995
2023-10-17T02:02:14.920 INFO (pid:687831) [language-client-index] - Language server "cSpell" started with 687996
2023-10-17T02:02:16.693 INFO (pid:687831) [services] - LanguageClient requirements state change: starting => running
2023-10-17T02:02:16.700 INFO (pid:687831) [services] - service languageserver.requirements started
2023-10-17T02:03:19.784 INFO (pid:687831) [attach] - receive notification: openList [ 'diagnostics' ]
2023-10-17T02:03:19.883 INFO (pid:687831) [attach] - receive notification: doAutocmd [ 2 ]
2023-10-17T02:03:20.239 ERROR (pid:687831) [events] - Error on event: CursorHold Error: Buffer 4 not attached, not a normal buffer, buftype "nofile"
    at lR.getAttachedDocument (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:195:3409)
    at Tb.getCurrentState (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:278:34115)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ub.getLinks (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:2809)
    at async ub.getCurrentLink (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:2945)
    at async ub.showTooltip (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:2598)
    at async /home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:266:2041
2023-10-17T02:03:27.744 INFO (pid:687831) [attach] - receive notification: doAutocmd [ 2 ]
2023-10-17T02:04:30.576 ERROR (pid:687831) [completion-complete] - Complete error: coc-dot-complete TypeError: e.words is not iterable
    at /home/wzy/.config/coc/extensions/node_modules/coc-dot-complete/lib/index.js:1:1261
    at Array.forEach (<anonymous>)
    at i.gatherWords (/home/wzy/.config/coc/extensions/node_modules/coc-dot-complete/lib/index.js:1:1215)
    at i.provideCompletionItems (/home/wzy/.config/coc/extensions/node_modules/coc-dot-complete/lib/index.js:1:1027)
    at Mm.doComplete (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:254:6493)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:447:9)
2023-10-17T02:04:30.578 ERROR (pid:687831) [completion-complete] - Complete error: coc-dash-complete TypeError: t.words is not iterable
    at /home/wzy/.config/coc/extensions/node_modules/coc-dash-complete/lib/index.js:1:1264
    at Array.forEach (<anonymous>)
    at i.gatherWords (/home/wzy/.config/coc/extensions/node_modules/coc-dash-complete/lib/index.js:1:1218)
    at i.provideCompletionItems (/home/wzy/.config/coc/extensions/node_modules/coc-dash-complete/lib/index.js:1:1030)
    at Mm.doComplete (/home/wzy/.local/share/nvim/repos/github.com/neoclide/coc.nvim_release/build/index.js:254:6493)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:447:9)
2023-10-17T02:09:10.729 INFO (pid:687831) [attach] - receive notification: showInfo []

**Comment by fannheyward** [comment]
Two issues:

1. how to reproduce this? Tested with `requirements-language-server`, no diagnostic reported on `autopep7`
2. the range is returned from LS, what's the server returns?

<img width="298" alt="image" src="https://github.com/neoclide/coc.nvim/assets/345274/f952424a-e48a-4193-964f-66a5bb006ff1">

**Comment by Freed-Wu** [comment]
> 1. how to reproduce this

Sorry for my unclear representation.

```sh
pip install 'requirements-language-server==0.0.6'
# to get all package names in PYPI
pip-cache update
echo autopep7 >> requirments.txt
vi requirments.txt
```

> what's the server returns

```python
Diagnostic(range=11:0-11:7, message='autopep7: no such package', severity=<DiagnosticSeverity.Error: 1>, code=None, code_description=None, source=None, tags=None, related_information=None, data=None)
```

**Comment by fannheyward** [comment]
The diagnostic range is returned by server, reproduced with other editor too.

> If you want to specify a range that contains a line including the line ending character(s) then use an end position denoting the start of the next line

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#range

**Comment by Freed-Wu** [comment]
If we use `autopep7 == 1.0.0`:

When we move cursor to `7`, message is popped up:

![Screenshot from 2023-10-17 15-56-15](https://github.com/neoclide/coc.nvim/assets/32936898/72b9411f-ef56-4883-90a3-7d3a3df0369e)

However, the underline region doesn't contain `7`:

![Screenshot from 2023-10-17 15-56-19](https://github.com/neoclide/coc.nvim/assets/32936898/bb7450b9-ab37-4008-99d0-8984f220ef06)

**Comment by Freed-Wu** [comment]
If we use `autopep7 == 1.0.0`:

When we move cursor to `7`, message is popped up:

![Screenshot from 2023-10-17 15-56-15](https://github.com/neoclide/coc.nvim/assets/32936898/72b9411f-ef56-4883-90a3-7d3a3df0369e)

However, the underline region doesn't contain `7`:

![Screenshot from 2023-10-17 15-56-19](https://github.com/neoclide/coc.nvim/assets/32936898/bb7450b9-ab37-4008-99d0-8984f220ef06)

@fannheyward Is it a bug?

**Comment by fannheyward** [comment]
Didn't debug on this, but I still think it's server's issue that reported wrong range, because we can't reproduce with other language server.

**Comment by Freed-Wu** [comment]
> Is it a bug?

Should the range of popup message and underline be a same range? If so, I doubt it should be a bug?

> reported wrong range

For this situation, which range is correct? Should be `range=11:0-11:7`? (Assume current line is 11)

**Comment by Freed-Wu** [comment]
No offense, I just think the underline region is smaller than the range of popup message is very weird.

**Comment by fannheyward** [comment]
Reopening this and will check the underline and hover range.

**Comment by fannheyward** [comment]
I think the range should be `0, 8`, for example `autopep7` in python file:

<img width="311" alt="image" src="https://github.com/neoclide/coc.nvim/assets/345274/97160a9e-283d-4763-af90-3eb0204619d0">


```
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 8
                }
            },
            "message": "\"autopep7\" is not defined",
```

**Comment by Freed-Wu** [comment]
That is because there is not any character after `autopep7`. It we add some character after it, we can see this weird behaviour. Let me change an example, it is about coc-clangd:

For example, underline scope in `EXIT_SUCCESS`, popup scope is `EXIT_SUCCESS;`. Why popup scope is larger than underline scope?

```c
int main(int argc, char *argv[]) {
  return EXIT_SUCCESS; // underline scope in `EXIT_SUCCESS`, popup scope is `EXIT_SUCCESS;`
}
```

![Screenshot from 2023-11-22 00-54-46](https://github.com/neoclide/coc.nvim/assets/32936898/41e0a4dd-660b-485c-9016-2bf5774715e3)

![Screenshot from 2023-11-22 00-54-42](https://github.com/neoclide/coc.nvim/assets/32936898/470086be-7600-4ac3-8a37-ca203fa1e1de)

**Comment by fannheyward** [comment]
> popup scope is EXIT_SUCCESS;

After some debugging, here's the why popup scope larger:

https://github.com/neoclide/coc.nvim/blob/ae1c5fcb3213227de8ccd3930758fe4c7c16454b/src/model/document.ts#L545-L550

coc will `byteSlice` the line content to find position, in this example `EXIT_SUCCESS;` to `EXIT_SUCCESS`, position.character is last S, not `;`, then uses this position to find diagnostic to display.

**Comment by Freed-Wu** [comment]
So is it a bug? :bug:
