### ISSUE TITLE
Server sh failed to start: Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by listenerri** [neoclide/coc.nvim#4797]
## Result from CocInfo
```
## versions

vim version: VIM - Vi IMproved 9.0 9002087
node version: v18.16.1
coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800
coc.nvim directory: C:\Users\**\plugged\coc.nvim
term: tmux
platform: win32

## Log of coc.nvim

2023-11-04T00:35:03.845 INFO (pid:41712) [plugin] - coc.nvim initialized with node: v18.16.1 after 288
2023-11-04T00:35:03.845 INFO (pid:41712) [services] - LanguageClient bash-language-server state change: stopped => starting
2023-11-04T00:35:03.859 INFO (pid:41712) [services] - LanguageClient bash-language-server state change: starting => stopped
2023-11-04T00:35:03.860 ERROR (pid:41712) [services] - Server sh failed to start: Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at C:\Users\**\plugged\coc.nvim\build\index.js:244:6310
    at async Md.createConnection (C:\Users\**\plugged\coc.nvim\build\index.js:240:15149)
    at async Md._start (C:\Users\**\plugged\coc.nvim\build\index.js:240:7683)
    at async Object.start (C:\Users\**\plugged\coc.nvim\build\index.js:245:5336) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}
2023-11-04T00:35:07.129 INFO (pid:41712) [attach] - receive notification: openLog []
2023-11-04T00:36:16.028 INFO (pid:41712) [attach] - receive notification: showInfo []


```

## Describe the bug

coc-sh start failed

Windows doesn't support shebang:
https://stackoverflow.com/questions/43419893/how-do-i-fix-error-spawn-unknown-with-node-js-v7-8-0-on-windows-10

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

Just to edit a *.sh file using vim with coc-sh plugin enabled (on windows or msys2)

**Comment by listenerri** [comment]
Related: https://github.com/josa42/coc-sh/issues/75

**Comment by fannheyward** [comment]
Needs a fix in coc-sh.
