### ISSUE TITLE
Is it possible to disable some checkers for certain languages?

### ISSUE THREAD

**Issue by marslo** [neoclide/coc.nvim#4858]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I'm using both LSP and COC in vim, and most of time they're shows same options in drop-down list, is it possible to disable some of checkers in certain languages ?

i.e.:
```vim
let g:coc_checker_disable = {
   'python': { 'JD', ... }
}

" or something similar in `CocConfig` 
```

here are details in my status:
<img width="1407" alt="coc-disable-jd" src="https://github.com/neoclide/coc.nvim/assets/5822057/ac743279-3a07-4a92-8623-d621c672d972">

**environment**
```bash
$ vim --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info
```

**CocInfo**
```vim
## versions

vim version: NVIM v0.9.5
node version: v21.5.0
coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800
coc.nvim directory: /Users/marslo/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2024-01-14T02:35:04.233 INFO (pid:48386) [extension:coc-git] - Looking for git in: git
2024-01-14T02:35:05.131 WARN (pid:48386) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at Object.activate (/Users/marslo/.config/coc/extensions/node_modules/coc-python/lib/index.js:154:43)
    at /Users/marslo/.vim/plugged/coc.nvim/build/index.js:251:33352
2024-01-14T02:35:05.132 WARN (pid:48386) [workspace] - workspace.createOutputChannel is deprecated, please use window.createOutputChannel instead. 
    at registerServices (/Users/marslo/.config/coc/extensions/node_modules/coc-python/lib/index.js:247:56)
    at activateUnsafe (/Users/marslo/.config/coc/extensions/node_modules/coc-python/lib/index.js:177:5)
2024-01-14T02:35:05.136 WARN (pid:48386) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at new ApplicationShell (/Users/marslo/.config/coc/extensions/node_modules/coc-python/lib/index.js:113523:48)
    at Object.resolveInstance (/Users/marslo/.config/coc/extensions/node_modules/coc-python/lib/index.js:2948:18)
2024-01-14T02:35:05.145 WARN (pid:48386) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at InterpreterLocatorProgressStatubarHandler.register (/Users/marslo/.config/coc/extensions/node_modules/coc-python/lib/index.js:118455:42)
    at initializeServices (/Users/marslo/.config/coc/extensions/node_modules/coc-python/lib/index.js:282:73)
2024-01-14T02:35:05.149 WARN (pid:48386) [workspace] - workspace.onDidOpenTerminal is deprecated, please use window.onDidOpenTerminal instead. 
    at get onDidOpenTerminal [as onDidOpenTerminal] (/Users/marslo/.config/coc/extensions/node_modules/coc-python/lib/index.js:113754:37)
    at TerminalAutoActivation.register (/Users/marslo/.config/coc/extensions/node_modules/coc-python/lib/index.js:124194:45)
2024-01-14T02:35:05.149 WARN (pid:48386) [commands] - Command python.refactorExtractVariable already registered
2024-01-14T02:35:05.149 WARN (pid:48386) [commands] - Command python.refactorExtractMethod already registered
2024-01-14T02:35:05.149 WARN (pid:48386) [commands] - Command python.sortImports already registered
2024-01-14T02:35:05.150 WARN (pid:48386) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at ApplicationShell.createStatusBarItem (/Users/marslo/.config/coc/extensions/node_modules/coc-python/lib/index.js:113550:37)
    at new InterpreterDisplay (/Users/marslo/.config/coc/extensions/node_modules/coc-python/lib/index.js:118368:38)
2024-01-14T02:35:05.156 WARN (pid:48386) [commands] - Command python.runLinting already registered
2024-01-14T02:35:05.160 INFO (pid:48386) [extension:coc-python] - Python Extension: Display locator refreshing progress, Class name = InterpreterLocatorProgressStatubarHandler, , Return Value: undefined
2024-01-14T02:35:05.160 INFO (pid:48386) [extension:coc-python] - Python Extension: Notify locators are locating, Class name = InterpreterLocatorProgressService, , Return Value: undefined
2024-01-14T02:35:05.160 INFO (pid:48386) [extension:coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
2024-01-14T02:35:05.160 INFO (pid:48386) [extension:coc-python] - Python Extension: Detected refreshing of Interpreters, Class name = InterpreterLocatorProgressService, Arg 1: {}, Return Value: undefined
2024-01-14T02:35:05.164 INFO (pid:48386) [extension:coc-python] - Python Extension: Display locator refreshing progress, Class name = InterpreterLocatorProgressStatubarHandler, , Return Value: undefined
2024-01-14T02:35:05.164 INFO (pid:48386) [extension:coc-python] - Python Extension: Notify locators are locating, Class name = InterpreterLocatorProgressService, , Return Value: undefined
2024-01-14T02:35:05.164 INFO (pid:48386) [extension:coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
2024-01-14T02:35:05.164 INFO (pid:48386) [extension:coc-python] - Python Extension: Detected refreshing of Interpreters, Class name = InterpreterLocatorProgressService, Arg 1: {}, Return Value: undefined
2024-01-14T02:35:05.167 INFO (pid:48386) [extension:coc-python] - Python Extension: Display locator refreshing progress, Class name = InterpreterLocatorProgressStatubarHandler, , Return Value: undefined
2024-01-14T02:35:05.167 INFO (pid:48386) [extension:coc-python] - Python Extension: Notify locators are locating, Class name = InterpreterLocatorProgressService, , Return Value: undefined
2024-01-14T02:35:05.167 INFO (pid:48386) [extension:coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
2024-01-14T02:35:05.167 INFO (pid:48386) [extension:coc-python] - Python Extension: Detected refreshing of Interpreters, Class name = InterpreterLocatorProgressService, Arg 1: {}, Return Value: undefined
2024-01-14T02:35:05.170 INFO (pid:48386) [extension:coc-python] - Python Extension: Display locator refreshing progress, Class name = InterpreterLocatorProgressStatubarHandler, , Return Value: undefined
2024-01-14T02:35:05.170 INFO (pid:48386) [extension:coc-python] - Python Extension: Notify locators are locating, Class name = InterpreterLocatorProgressService, , Return Value: undefined
2024-01-14T02:35:05.170 INFO (pid:48386) [extension:coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
2024-01-14T02:35:05.170 INFO (pid:48386) [extension:coc-python] - Python Extension: Detected refreshing of Interpreters, Class name = InterpreterLocatorProgressService, Arg 1: {}, Return Value: undefined
2024-01-14T02:35:05.173 INFO (pid:48386) [extension:coc-python] - Python Extension: Create file systemwatcher with pattern */python
2024-01-14T02:35:05.173 INFO (pid:48386) [extension:coc-python] - Python Extension: Create file systemwatcher with pattern */*/python
2024-01-14T02:35:05.173 INFO (pid:48386) [extension:coc-python] - Python Extension: Display locator refreshing progress, Class name = InterpreterLocatorProgressStatubarHandler, , Return Value: undefined
2024-01-14T02:35:05.173 INFO (pid:48386) [extension:coc-python] - Python Extension: Notify locators are locating, Class name = InterpreterLocatorProgressService, , Return Value: undefined
2024-01-14T02:35:05.173 INFO (pid:48386) [extension:coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
2024-01-14T02:35:05.173 INFO (pid:48386) [extension:coc-python] - Python Extension: Detected refreshing of Interpreters, Class name = InterpreterLocatorProgressService, Arg 1: {}, Return Value: undefined
2024-01-14T02:35:05.177 INFO (pid:48386) [extension:coc-python] - Python Extension: Display locator refreshing progress, Class name = InterpreterLocatorProgressStatubarHandler, , Return Value: undefined
2024-01-14T02:35:05.177 INFO (pid:48386) [extension:coc-python] - Python Extension: Notify locators are locating, Class name = InterpreterLocatorProgressService, , Return Value: undefined
2024-01-14T02:35:05.177 INFO (pid:48386) [extension:coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
2024-01-14T02:35:05.177 INFO (pid:48386) [extension:coc-python] - Python Extension: Detected refreshing of Interpreters, Class name = InterpreterLocatorProgressService, Arg 1: {}, Return Value: undefined
2024-01-14T02:35:05.180 INFO (pid:48386) [extension:coc-python] - Python Extension: Display locator refreshing progress, Class name = InterpreterLocatorProgressStatubarHandler, , Return Value: undefined
2024-01-14T02:35:05.180 INFO (pid:48386) [extension:coc-python] - Python Extension: Notify locators are locating, Class name = InterpreterLocatorProgressService, , Return Value: undefined
2024-01-14T02:35:05.180 INFO (pid:48386) [extension:coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
2024-01-14T02:35:05.180 INFO (pid:48386) [extension:coc-python] - Python Extension: Detected refreshing of Interpreters, Class name = InterpreterLocatorProgressService, Arg 1: {}, Return Value: undefined
2024-01-14T02:35:05.184 INFO (pid:48386) [plugin] - coc.nvim initialized with node: v21.5.0 after 1400
2024-01-14T02:35:05.185 INFO (pid:48386) [services] - LanguageClient Pyright Server state change: stopped => starting
2024-01-14T02:35:05.185 INFO (pid:48386) [extension:coc-python] - Python Extension: Register Intepreter Watcher, Class name = WorkspaceVirtualEnvWatcherService, Arg 1: <Uri:/Users/marslo/a.py>, Return Value: undefined
2024-01-14T02:35:05.186 INFO (pid:48386) [extension:coc-python] - Python Extension: Build the workspace interpreter watcher, Class name = InterpreterWatcherBuilder, Arg 1: <Uri:/Users/marslo/a.py>, Return Value: <Return value cannot be serialized for logging>
2024-01-14T02:35:05.205 INFO (pid:48386) [extension:coc-python] - Python Extension: Interpreters returned by WorkspaceVirtualEnvService are of count 0
2024-01-14T02:35:05.218 INFO (pid:48386) [extension:coc-python] - Python Extension: Executing next rule from environment
2024-01-14T02:35:05.219 INFO (pid:48386) [extension:coc-python] - Python Extension: Executing next rule from workspaceEnvs
2024-01-14T02:35:05.230 INFO (pid:48386) [extension:coc-python] - Python Extension: Interpreters returned by CondaEnvFileService are of count 0
2024-01-14T02:35:05.232 INFO (pid:48386) [extension:coc-python] - Python Extension: Interpreters returned by PipEnvService are of count 0
2024-01-14T02:35:05.237 INFO (pid:48386) [extension:coc-python] - Python Extension: Detection of Python Interpreter for Command python3.7 and args  failed
2024-01-14T02:35:05.240 INFO (pid:48386) [extension:coc-python] - Python Extension: Detection of Python Interpreter for Command python3.6 and args  failed
2024-01-14T02:35:05.246 INFO (pid:48386) [extension:coc-python] - Python Extension: Detection of Python Interpreter for Command python2 and args  failed
2024-01-14T02:35:05.253 INFO (pid:48386) [language-client-index] - Language server "pyright" started with 48760
2024-01-14T02:35:05.260 INFO (pid:48386) [extension:coc-python] - Python Extension: Interpreters returned by VirtualEnvService are of count 0
2024-01-14T02:35:05.283 INFO (pid:48386) [extension:coc-python] - Python Extension: Current value for rule system is {"architecture":3,"path":"/usr/local/opt/python@3.12/bin/python3.12","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.12.1-final","major":3,"minor":12,"patch":1,"prerelease":["final"],"build":[],"version":"3.12.1-final"},"sysPrefix":"/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12","fileHash":"50ca1e19fda5e6d5051e02f758eb1aa511deff0f68824afe169171b76f8cf15944e98fd91a22e8596651d7be0156e994ca42f10c06cb0cb646bf1d3b20b3e1b9","type":"Unknown","cachedEntry":true,"displayName":"Python 3.12.1 64-bit"}
2024-01-14T02:35:05.284 INFO (pid:48386) [extension:coc-python] - Python Extension: Current value for rule windowsRegistry is nothing
2024-01-14T02:35:05.284 INFO (pid:48386) [extension:coc-python] - Python Extension: Selected Interpreter from cachedInterpreters, {"architecture":3,"path":"/usr/local/opt/python@3.12/bin/python3.12","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.12.1-final","major":3,"minor":12,"patch":1,"prerelease":["final"],"build":[],"version":"3.12.1-final"},"sysPrefix":"/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12","fileHash":"50ca1e19fda5e6d5051e02f758eb1aa511deff0f68824afe169171b76f8cf15944e98fd91a22e8596651d7be0156e994ca42f10c06cb0cb646bf1d3b20b3e1b9","type":"Unknown","cachedEntry":true,"displayName":"Python 3.12.1 64-bit"}
2024-01-14T02:35:05.287 INFO (pid:48386) [extension:coc-python] - Python Extension: setGlobalInterpreter, Class name = BaseRuleService, Arg 1: {"architecture":3,"path":"/usr/local/opt/python@3.12/bin/python3.12","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.12.1-final","major":3,"minor":12,"patch":1,"prerelease":["final"],"build":[],"version":"3.12.1-final"},"sysPrefix":"/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12","fileHash":"50ca1e19fda5e6d5051e02f758eb1aa511deff0f68824afe169171b76f8cf15944e98fd91a22e8596651d7be0156e994ca42f10c06cb0cb646bf1d3b20b3e1b9","type":"Unknown","cachedEntry":true,"displayName":"Python 3.12.1 64-bit"}, Arg 2: <argument cannot be serialized for logging>, Return Value: true
2024-01-14T02:35:05.287 INFO (pid:48386) [extension:coc-python] - Python Extension: autoSelectInterpreter, Class name = BaseRuleService, Arg 1: <Uri:/Users/marslo/.marslo/vimrc.d>, Arg 2: <argument cannot be serialized for logging>, Return Value: undefined
2024-01-14T02:35:05.287 INFO (pid:48386) [extension:coc-python] - Python Extension: autoSelectInterpreter, Class name = BaseRuleService, Arg 1: <Uri:/Users/marslo/.marslo/vimrc.d>, Arg 2: <argument cannot be serialized for logging>, Return Value: undefined
2024-01-14T02:35:05.287 INFO (pid:48386) [extension:coc-python] - Python Extension: autoSelectInterpreter, Class name = BaseRuleService, Arg 1: <Uri:/Users/marslo/.marslo/vimrc.d>, Arg 2: <argument cannot be serialized for logging>, Return Value: undefined
2024-01-14T02:35:05.337 INFO (pid:48386) [extension:coc-python] - Python Extension: Executing next rule from windowsRegistry
2024-01-14T02:35:05.337 INFO (pid:48386) [extension:coc-python] - Python Extension: Executing next rule from settings
2024-01-14T02:35:05.337 INFO (pid:48386) [extension:coc-python] - Python Extension: Executing next rule from workspaceEnvs
2024-01-14T02:35:05.337 INFO (pid:48386) [extension:coc-python] - Python Extension: Executing next rule from environment
2024-01-14T02:35:05.339 INFO (pid:48386) [extension:coc-python] - Python Extension: Cached data exists getEnvironmentVariables, /Users/marslo/.marslo/vimrc.d
2024-01-14T02:35:05.339 INFO (pid:48386) [extension:coc-python] - Python Extension: autoSelectInterpreter, Class name = BaseRuleService, Arg 1: <Uri:/Users/marslo/.marslo/vimrc.d>, Return Value: undefined
2024-01-14T02:35:05.339 INFO (pid:48386) [extension:coc-python] - Python Extension: autoSelectInterpreter, Class name = BaseRuleService, Arg 1: <Uri:/Users/marslo/.marslo/vimrc.d>, Return Value: undefined
2024-01-14T02:35:05.339 INFO (pid:48386) [extension:coc-python] - Python Extension: autoSelectInterpreter, Class name = BaseRuleService, Arg 1: <Uri:/Users/marslo/.marslo/vimrc.d>, Return Value: undefined
2024-01-14T02:35:05.339 INFO (pid:48386) [extension:coc-python] - Python Extension: autoSelectInterpreter, Class name = BaseRuleService, Arg 1: <Uri:/Users/marslo/.marslo/vimrc.d>, Return Value: undefined
2024-01-14T02:35:05.341 INFO (pid:48386) [extension:coc-python] - Python Extension: Cached data exists getEnvironmentVariables, /Users/marslo/a.py
2024-01-14T02:35:05.342 INFO (pid:48386) [extension:coc-python] - Python Extension: Cached data exists getEnvironmentVariables, <No Resource>
2024-01-14T02:35:05.347 INFO (pid:48386) [extension:coc-python] - Python Extension: Interpreters returned by CondaEnvService are of count 0
2024-01-14T02:35:05.347 INFO (pid:48386) [extension:coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
2024-01-14T02:35:05.347 INFO (pid:48386) [extension:coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
2024-01-14T02:35:05.347 INFO (pid:48386) [extension:coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
2024-01-14T02:35:05.347 INFO (pid:48386) [extension:coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
2024-01-14T02:35:05.347 INFO (pid:48386) [extension:coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
2024-01-14T02:35:05.374 INFO (pid:48386) [extension:coc-python] - Python Extension: Selected Interpreter from currentPath, {"architecture":3,"path":"/usr/local/opt/python@3.12/bin/python3.12","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.12.1-final","major":3,"minor":12,"patch":1,"prerelease":["final"],"build":[],"version":"3.12.1-final"},"sysPrefix":"/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12","fileHash":"50ca1e19fda5e6d5051e02f758eb1aa511deff0f68824afe169171b76f8cf15944e98fd91a22e8596651d7be0156e994ca42f10c06cb0cb646bf1d3b20b3e1b9","type":"Unknown","cachedEntry":true}
2024-01-14T02:35:05.375 INFO (pid:48386) [extension:coc-python] - Python Extension: setGlobalInterpreter, Class name = BaseRuleService, Arg 1: {"architecture":3,"path":"/usr/local/opt/python@3.12/bin/python3.12","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.12.1-final","major":3,"minor":12,"patch":1,"prerelease":["final"],"build":[],"version":"3.12.1-final"},"sysPrefix":"/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12","fileHash":"50ca1e19fda5e6d5051e02f758eb1aa511deff0f68824afe169171b76f8cf15944e98fd91a22e8596651d7be0156e994ca42f10c06cb0cb646bf1d3b20b3e1b9","type":"Unknown","cachedEntry":true}, Arg 2: undefined, Return Value: false
2024-01-14T02:35:05.375 INFO (pid:48386) [extension:coc-python] - Python Extension: Executing next rule from currentPath
2024-01-14T02:35:05.375 INFO (pid:48386) [extension:coc-python] - Python Extension: autoSelectInterpreter, Class name = BaseRuleService, Arg 1: <Uri:/Users/marslo/.marslo/vimrc.d>, Return Value: undefined
2024-01-14T02:35:05.384 INFO (pid:48386) [extension:coc-python] - Python Extension: Current value for rule system is {"architecture":3,"path":"/usr/local/opt/python@3.12/bin/python3.12","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.12.1-final","major":3,"minor":12,"patch":1,"prerelease":["final"],"build":[],"version":"3.12.1-final"},"sysPrefix":"/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12","fileHash":"50ca1e19fda5e6d5051e02f758eb1aa511deff0f68824afe169171b76f8cf15944e98fd91a22e8596651d7be0156e994ca42f10c06cb0cb646bf1d3b20b3e1b9","type":"Unknown","cachedEntry":true,"displayName":"Python 3.12.1 64-bit"}
2024-01-14T02:35:05.385 INFO (pid:48386) [extension:coc-python] - Python Extension: Current value for rule windowsRegistry is nothing
2024-01-14T02:35:05.385 INFO (pid:48386) [extension:coc-python] - Python Extension: Selected Interpreter from cachedInterpreters, {"architecture":3,"path":"/usr/local/opt/python@3.12/bin/python3.12","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.12.1-final","major":3,"minor":12,"patch":1,"prerelease":["final"],"build":[],"version":"3.12.1-final"},"sysPrefix":"/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12","fileHash":"50ca1e19fda5e6d5051e02f758eb1aa511deff0f68824afe169171b76f8cf15944e98fd91a22e8596651d7be0156e994ca42f10c06cb0cb646bf1d3b20b3e1b9","type":"Unknown","cachedEntry":true,"displayName":"Python 3.12.1 64-bit"}
2024-01-14T02:35:05.386 INFO (pid:48386) [extension:coc-python] - Python Extension: setGlobalInterpreter, Class name = BaseRuleService, Arg 1: {"architecture":3,"path":"/usr/local/opt/python@3.12/bin/python3.12","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.12.1-final","major":3,"minor":12,"patch":1,"prerelease":["final"],"build":[],"version":"3.12.1-final"},"sysPrefix":"/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12","fileHash":"50ca1e19fda5e6d5051e02f758eb1aa511deff0f68824afe169171b76f8cf15944e98fd91a22e8596651d7be0156e994ca42f10c06cb0cb646bf1d3b20b3e1b9","type":"Unknown","cachedEntry":true,"displayName":"Python 3.12.1 64-bit"}, Arg 2: undefined, Return Value: false
2024-01-14T02:35:05.386 INFO (pid:48386) [extension:coc-python] - Python Extension: Executing next rule from cachedInterpreters
2024-01-14T02:35:05.386 INFO (pid:48386) [extension:coc-python] - Python Extension: autoSelectInterpreter, Class name = BaseRuleService, Arg 1: <Uri:/Users/marslo/.marslo/vimrc.d>, Return Value: undefined
2024-01-14T02:35:05.423 INFO (pid:48386) [extension:coc-python] - Python Extension: Interpreters returned by KnownPathsService are of count 16
2024-01-14T02:35:05.423 INFO (pid:48386) [extension:coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: false
2024-01-14T02:35:05.440 INFO (pid:48386) [extension:coc-python] - Python Extension: Selected Interpreter from system, {"architecture":3,"path":"/usr/local/opt/python@3.12/bin/python3.12","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.12.1-final","major":3,"minor":12,"patch":1,"prerelease":["final"],"build":[],"version":"3.12.1-final"},"sysPrefix":"/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12","fileHash":"50ca1e19fda5e6d5051e02f758eb1aa511deff0f68824afe169171b76f8cf15944e98fd91a22e8596651d7be0156e994ca42f10c06cb0cb646bf1d3b20b3e1b9","type":"Unknown","cachedEntry":true,"displayName":"Python 3.12.1 64-bit"}
2024-01-14T02:35:05.441 INFO (pid:48386) [extension:coc-python] - Python Extension: setGlobalInterpreter, Class name = BaseRuleService, Arg 1: {"architecture":3,"path":"/usr/local/opt/python@3.12/bin/python3.12","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.12.1-final","major":3,"minor":12,"patch":1,"prerelease":["final"],"build":[],"version":"3.12.1-final"},"sysPrefix":"/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12","fileHash":"50ca1e19fda5e6d5051e02f758eb1aa511deff0f68824afe169171b76f8cf15944e98fd91a22e8596651d7be0156e994ca42f10c06cb0cb646bf1d3b20b3e1b9","type":"Unknown","cachedEntry":true,"displayName":"Python 3.12.1 64-bit"}, Arg 2: undefined, Return Value: false
2024-01-14T02:35:05.441 INFO (pid:48386) [extension:coc-python] - Python Extension: Executing next rule from system
2024-01-14T02:35:05.441 INFO (pid:48386) [extension:coc-python] - Python Extension: autoSelectInterpreter, Class name = BaseRuleService, Arg 1: <Uri:/Users/marslo/.marslo/vimrc.d>, Return Value: undefined
2024-01-14T02:35:05.449 INFO (pid:48386) [extension:coc-python] - Python Extension: Cached data exists getEnvironmentVariables, /Users/marslo/a.py
2024-01-14T02:35:05.453 INFO (pid:48386) [extension:coc-python] - Python Extension: Cached data exists getEnvironmentVariables, /Users/marslo/a.py
2024-01-14T02:35:05.472 INFO (pid:48386) [extension:coc-python] - Python Extension: Interpreters returned by CurrentPathService are of count 3
2024-01-14T02:35:05.473 INFO (pid:48386) [extension:coc-python] - Python Extension: Checking whether locactors have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: true
2024-01-14T02:35:05.473 INFO (pid:48386) [extension:coc-python] - Python Extension: Hide locator refreshing progress, Class name = InterpreterLocatorProgressStatubarHandler, , Return Value: undefined
2024-01-14T02:35:05.473 INFO (pid:48386) [extension:coc-python] - Python Extension: All locators have completed locating, Class name = InterpreterLocatorProgressService, , Return Value: undefined
2024-01-14T02:35:05.496 INFO (pid:48386) [extension:coc-python] - Python Extension: Cached data exists getEnvironmentVariables, /Users/marslo/a.py
2024-01-14T02:35:05.525 INFO (pid:48386) [services] - LanguageClient Pyright Server state change: starting => running
2024-01-14T02:35:05.529 INFO (pid:48386) [services] - service pyright started
2024-01-14T02:35:05.779 INFO (pid:48386) [core-watchman] - watchman watching project: /Users/marslo/Library/Python/3.12/lib/python/site-packages
2024-01-14T02:35:05.784 INFO (pid:48386) [core-watchman] - watchman watching project: /usr/local/lib/python3.12/site-packages
2024-01-14T02:35:05.785 INFO (pid:48386) [core-watchman] - watchman watching project: /usr/local/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12
2024-01-14T02:35:06.041 INFO (pid:48386) [extension:coc-python] - Python Extension: Cached data exists getEnvironmentVariables, /Users/marslo/a.py
2024-01-14T02:35:06.089 INFO (pid:48386) [extension:coc-python] - Python Extension: Cached data exists getEnvironmentVariables, /Users/marslo/a.py
2024-01-14T02:35:07.502 INFO (pid:48386) [attach] - receive notification: showInfo []
```

**CocConfig**
```json
{
  "diagnostic.displayByAle": false,
  "codeLens.enable": true,
  "java.referencesCodeLens.enabled": true
}
```

**Comment by fannheyward** [comment]
Looks like you're using Jedi and another language server at same time, how do you setup Jedi? If you're using coc-jedi, you can disable it by `jedi.enable`.
