### ISSUE TITLE
Action CompleteStop not exist

### ISSUE THREAD

**Issue by simplycode07** [neoclide/coc.nvim#4871]
## Result from CocInfo
```
vim version: NVIM v0.10.0-dev
node version: v20.11.0
coc.nvim version: 0.0.82-fe66892 2023-09-15 15:12:28 +0800
coc.nvim directory: /home/dhruv/.local/share/nvim/plugged/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2024-01-27T20:26:34.465 INFO (pid:51746) [plugin] - coc.nvim initialized with node: v20.11.0 after 833
2024-01-27T20:26:34.468 INFO (pid:51746) [services] - LanguageClient Pyright Server state change: stopped => starting
2024-01-27T20:26:34.482 INFO (pid:51746) [language-client-index] - Language server "pyright" started with 51773
2024-01-27T20:26:34.978 INFO (pid:51746) [services] - LanguageClient Pyright Server state change: starting => running
2024-01-27T20:26:34.991 INFO (pid:51746) [services] - service pyright started
2024-01-27T20:26:42.397 INFO (pid:51746) [attach] - Request action: CompleteStop [ 'confirm' ]
2024-01-27T20:26:42.402 ERROR (pid:51746) [attach] - Request error: CompleteStop [ 'confirm' ] Error: Action "CompleteStop" not exist
    at Plugin.cocAction (/home/dhruv/.local/share/nvim/plugged/coc.nvim/build/index.js:90935:17)
    at EventEmitter.<anonymous> (/home/dhruv/.local/share/nvim/plugged/coc.nvim/build/index.js:91070:38)
    at EventEmitter.emit (node:events:518:28)
    at EventEmitter.handleRequest (/home/dhruv/.local/share/nvim/plugged/coc.nvim/build/index.js:18051:14)
    at NvimTransport.emit (node:events:518:28)
    at NvimTransport.parseMessage (/home/dhruv/.local/share/nvim/plugged/coc.nvim/build/index.js:17058:16)
    at DecodeStream.<anonymous> (/home/dhruv/.local/share/nvim/plugged/coc.nvim/build/index.js:17046:16)
    at DecodeStream.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
2024-01-27T20:26:55.796 INFO (pid:51746) [attach] - Request action: CompleteStop [ 'confirm' ]
2024-01-27T20:26:55.797 ERROR (pid:51746) [attach] - Request error: CompleteStop [ 'confirm' ] Error: Action "CompleteStop" not exist
    at Plugin.cocAction (/home/dhruv/.local/share/nvim/plugged/coc.nvim/build/index.js:90935:17)
    at EventEmitter.<anonymous> (/home/dhruv/.local/share/nvim/plugged/coc.nvim/build/index.js:91070:38)
    at EventEmitter.emit (node:events:518:28)
    at EventEmitter.handleRequest (/home/dhruv/.local/share/nvim/plugged/coc.nvim/build/index.js:18051:14)
    at NvimTransport.emit (node:events:518:28)
    at NvimTransport.parseMessage (/home/dhruv/.local/share/nvim/plugged/coc.nvim/build/index.js:17058:16)
    at DecodeStream.<anonymous> (/home/dhruv/.local/share/nvim/plugged/coc.nvim/build/index.js:17046:16)
    at DecodeStream.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
2024-01-27T20:27:26.379 INFO (pid:51746) [attach] - receive notification: showInfo []
```

## Describe the bug

Using autocompletion triggers 
```
Error detected while processing function coc#pum#select_confirm[6]..coc#pum#clo
se[21]..coc#rpc#request[4]..<SNR>16_request[34]..function coc#pum#select_confir
m[6]..coc#pum#close[21]..coc#rpc#request[4]..<SNR>16_request:                  
line   31:                                                                     
E605: Exception not caught: Error on request: Vim(return):Error invoking 'Compl
eteStop' on channel 3 (coc):^@Action "CompleteStop" not exist
```

## Reproduce the bug
pressing esc after suggestions appear

## Screenshots
![image](https://github.com/neoclide/coc.nvim/assets/72332741/6b1c080a-9f8a-4063-82e6-5e6373b9a17e)
by suggestions I meant this, now pressing esc gives me
![image](https://github.com/neoclide/coc.nvim/assets/72332741/0d15afd5-4149-49c0-840a-2a8d70bc7c47)

**Comment by fannheyward** [comment]
You're using `master` branch that needs to build with `npm run build` in coc.nvim folder.

**Comment by ianchanning** [comment]
I get the same error. @fannheyward when you say `master` branch - are you talking about Neovim? Because I just installed the default instructions of coc.nvim, so I don't understand how I would be on a `master` branch of coc.

Here is what I have for other people with this problem:

```
## versions

vim version: NVIM v0.10.0-dev
node version: v20.13.1
coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800
coc.nvim directory: /home/ian/.vim/bundle/coc.nvim
term: xterm-256color
platform: linux

## Log of coc.nvim

2024-05-18T22:16:13.742 WARN (pid:2237273) [workspace] - workspace.createOutputChannel is deprecated, please use window.createOutputChannel instead. 
    at Object.<anonymous> (/home/ian/.config/coc/extensions/node_modules/coc-tailwindcss/out/index.js:14:7870)
    at Generator.next (<anonymous>)
2024-05-18T22:16:13.748 INFO (pid:2237273) [plugin] - coc.nvim initialized with node: v20.13.1 after 244
2024-05-18T22:18:48.078 INFO (pid:2237273) [attach] - Request action: CompleteStop [ '' ]
2024-05-18T22:18:48.081 ERROR (pid:2237273) [attach] - Request error: CompleteStop [ '' ] Error: Action "CompleteStop" not exist
    at Gy.cocAction (/home/ian/.vim/bundle/coc.nvim/build/index.js:277:46115)
    at EventEmitter.<anonymous> (/home/ian/.vim/bundle/coc.nvim/build/index.js:277:48269)
    at EventEmitter.emit (node:events:519:28)
    at EventEmitter.handleRequest (/home/ian/.vim/bundle/coc.nvim/build/index.js:20:4692)
    at Fk.emit (node:events:519:28)
    at Fk.parseMessage (/home/ian/.vim/bundle/coc.nvim/build/index.js:17:3258)
    at Hp.<anonymous> (/home/ian/.vim/bundle/coc.nvim/build/index.js:17:3087)
    at Hp.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)

```

**Comment by ianchanning** [comment]
I have no `build` script in the `coc.nvim/package.json` file:

```sh
~/.vim/bundle/coc.nvim$ cat package.json 
{
  "name": "coc.nvim-release",
  "version": "0.0.82",
  "description": "LSP based intellisense engine for neovim & vim8.",
  "engines": {
    "node": ">=12.12.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/neoclide/coc.nvim.git"
  },
  "author": "Qiming Zhao <chemzqm@gmail.com>",
  "bugs": {
    "url": "https://github.com/neoclide/coc.nvim/issues"
  },
  "homepage": "https://github.com/neoclide/coc.nvim#readme"
}
```

**Comment by fannheyward** [comment]
＞ 0.0.82-d1568d56 2023-09-29

@ianchanning your coc.nvim was outdated, upgraded your coc.nvim please.
