### ISSUE TITLE
jumpdefinition buffer 1 not created

### ISSUE THREAD

**Issue by laoshaw** [neoclide/coc.nvim#4973]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.0 9000749
node version: v20.12.0
coc.nvim version: 0.0.82-00bd79e0 2024-02-28 12:40:55 +0800
coc.nvim directory: /home/userx/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2024-04-09T18:21:02.178 INFO (pid:31373) [configurations] - Add folder configuration from file: /home/userx/tmp/frontend/webui/.vim/coc-settings.json
2024-04-09T18:21:02.655 INFO (pid:31373) [plugin] - coc.nvim initialized with node: v20.12.0 after 1746
2024-04-09T18:21:02.700 INFO (pid:31373) [services] - LanguageClient clangd state change: stopped => starting
2024-04-09T18:21:02.706 INFO (pid:31373) [language-client-index] - Language server "clangd" started with 31456
2024-04-09T18:21:03.073 INFO (pid:31373) [services] - LanguageClient clangd state change: starting => running
2024-04-09T18:21:03.082 INFO (pid:31373) [services] - service clangd started
2024-04-09T18:21:03.110 INFO (pid:31373) [core-watchman] - watchman watching project: /home/userx/tmp/frontend/webui
2024-04-09T18:24:30.571 INFO (pid:31373) [attach] - receive notification: jumpDefinition []
2024-04-09T18:25:00.883 INFO (pid:31373) [attach] - receive notification: detach []
2024-04-09T18:25:13.571 INFO (pid:31373) [attach] - receive notification: jumpDefinition []
2024-04-09T18:25:13.576 ERROR (pid:31373) [attach] - Error on notification jumpDefinition Error: Buffer 1 not created.
    at x1.getAttachedDocument (/home/userx/.vim/plugged/coc.nvim/build/index.js:198:3344)
    at Oy.getCurrentState (/home/userx/.vim/plugged/coc.nvim/build/index.js:281:34170)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async xy.request (/home/userx/.vim/plugged/coc.nvim/build/index.js:269:5498)
    at async xy.gotoDefinition (/home/userx/.vim/plugged/coc.nvim/build/index.js:269:6966)
    at async Ay.cocAction (/home/userx/.vim/plugged/coc.nvim/build/index.js:281:46295)
    at async EventEmitter.<anonymous> (/home/userx/.vim/plugged/coc.nvim/build/index.js:281:47916)
2024-04-09T18:25:24.155 INFO (pid:31373) [attach] - receive notification: jumpDefinition []
2024-04-09T18:25:24.159 ERROR (pid:31373) [attach] - Error on notification jumpDefinition Error: Buffer 1 not created.
    at x1.getAttachedDocument (/home/userx/.vim/plugged/coc.nvim/build/index.js:198:3344)
    at Oy.getCurrentState (/home/userx/.vim/plugged/coc.nvim/build/index.js:281:34170)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async xy.request (/home/userx/.vim/plugged/coc.nvim/build/index.js:269:5498)
    at async xy.gotoDefinition (/home/userx/.vim/plugged/coc.nvim/build/index.js:269:6966)
    at async Ay.cocAction (/home/userx/.vim/plugged/coc.nvim/build/index.js:281:46295)
    at async EventEmitter.<anonymous> (/home/userx/.vim/plugged/coc.nvim/build/index.js:281:47916)
2024-04-09T18:29:39.844 INFO (pid:31373) [attach] - receive notification: showInfo []
```
## Describe the bug

using with c file and a working compile_commands.json with clangd for coc.nvim.

I use 'gd' to jump to definition which worked fine initially, then I ctrl-o jump back and try gd on a different function then it reports "buffer 1 not create" and refuse to jump

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

it works well but jump to declaration instead of definition,  is the default gd jump to declarations?

**Comment by fannheyward** [comment]
> I use 'gd' to jump to definition which worked fine initially, then I ctrl-o jump back and try gd on a different function then it reports "buffer 1 not create" and refuse to jump

Tested with vim 9.1 and latest coc.nvim with clangd, can't reproduce.

> it works well but jump to declaration instead of definition, is the default gd jump to declarations?

How do you set your `gd` mapping? coc.nvim didn't set default `gd`.

coc.nvim requests to language server, handle the jumping with locations, before jumping to the document buffer that created and attached. The `buffer 1 not created` means the buffer is not created.

> [attach] - receive notification: detach

It's strange that coc.nvim received `detach` event to detach the buffer.

**Comment by fannheyward** [comment]
What's the language server?

**Comment by fannheyward** [comment]
Needs a way to reproduce to debug the issue.

**Comment by fannheyward** [comment]
Try to bisect your vimrc
