### ISSUE TITLE
Just updated and got the following error coc abnormal exit

### ISSUE THREAD

**Issue by ssmithstone** [neoclide/coc.nvim#50]
Just done a PlugUpdate , all seems fine then a restart of nvim produced thee message
[coc.nvim] Abnormal exit 

with the following window contents.

pkg/prelude/bootstrap.js:1
SyntaxError: Invalid or unexpected token
    at readPrelude (bootstrap_node.js:133:17)
    at bootstrap_node.js:140:22
    at bootstrap_node.js:147:8
    at startup (bootstrap_node.js:148:6)
    at bootstrap_node.js:648:3

Nvim 0.3.1 , OSX 10.13.4

Was working fine before the update

**Comment by ssmithstone** [comment]
I removed the plugin and reinstalled, no error now.
