### ISSUE TITLE
organizeImport stopped working for months

### ISSUE THREAD

**Issue by GopherJ** [neoclide/coc.nvim#5035]
## Result from CocInfo

```
## versions

vim version: NVIM v0.11.0-dev
node version: v18.20.2
coc.nvim version: 0.0.82-c3ae5c3b 2024-05-23 20:39:40 +0800
coc.nvim directory: /home/cj/.vim/plugged/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2024-06-10T23:50:46.397 WARN (pid:3566621) [attach] - Plugin not ready on request "documentSymbols" []
2024-06-10T23:50:46.403 ERROR (pid:3566621) [extensions-index] - Error on load package.json of coc-flutter [Error: ENOENT: no such file or directory, open '/home/cj/.config/coc/extensions/node_modules/coc-flutter/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/cj/.config/coc/extensions/node_modules/coc-flutter/package.json'
}
2024-06-10T23:50:46.404 ERROR (pid:3566621) [extensions-index] - Error on load package.json of coc-java [Error: ENOENT: no such file or directory, open '/home/cj/.config/coc/extensions/node_modules/coc-java/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/cj/.config/coc/extensions/node_modules/coc-java/package.json'
}
2024-06-10T23:50:46.404 ERROR (pid:3566621) [extensions-index] - Error on load package.json of coc-jest [Error: ENOENT: no such file or directory, open '/home/cj/.config/coc/extensions/node_modules/coc-jest/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/cj/.config/coc/extensions/node_modules/coc-jest/package.json'
}
2024-06-10T23:50:46.404 ERROR (pid:3566621) [extensions-index] - Error on load package.json of coc-kotlin [Error: ENOENT: no such file or directory, open '/home/cj/.config/coc/extensions/node_modules/coc-kotlin/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/cj/.config/coc/extensions/node_modules/coc-kotlin/package.json'
}
2024-06-10T23:50:46.405 ERROR (pid:3566621) [extensions-index] - Error on load package.json of coc-tasks [Error: ENOENT: no such file or directory, open '/home/cj/.config/coc/extensions/node_modules/coc-tasks/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/cj/.config/coc/extensions/node_modules/coc-tasks/package.json'
}
2024-06-10T23:50:46.406 ERROR (pid:3566621) [extensions-index] - Error on load package.json of coc-translator [Error: ENOENT: no such file or directory, open '/home/cj/.config/coc/extensions/node_modules/coc-translator/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/cj/.config/coc/extensions/node_modules/coc-translator/package.json'
}
2024-06-10T23:50:46.499 INFO (pid:3566621) [extension:coc-git] - Looking for git in: git
2024-06-10T23:50:46.508 WARN (pid:3566621) [workspace] - Extension "coc-lists" registered synchronized autocmd "VimLeavePre", which could be slow.
2024-06-10T23:50:46.529 INFO (pid:3566621) [extension:coc-tabnine] - Using tabnine from /home/cj/.config/coc/extensions/coc-tabnine-data/binaries/4.165.0/x86_64-unknown-linux-musl/TabNine
2024-06-10T23:50:46.616 INFO (pid:3566621) [plugin] - coc.nvim initialized with node: v18.20.2 after 263
2024-06-10T23:50:46.618 INFO (pid:3566621) [services] - LanguageClient go state change: stopped => starting
2024-06-10T23:50:46.632 INFO (pid:3566621) [language-client-index] - Language server "languageserver.go" started with 3566757
2024-06-10T23:50:46.651 INFO (pid:3566621) [services] - LanguageClient go state change: starting => running
2024-06-10T23:50:46.654 INFO (pid:3566621) [services] - service languageserver.go started
2024-06-10T23:50:46.775 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:47.075 INFO (pid:3566621) [attach] - receive notification: highlight []
2024-06-10T23:50:48.321 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:48.672 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:48.673 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:48.721 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 8 ]
2024-06-10T23:50:48.972 INFO (pid:3566621) [attach] - receive notification: highlight []
2024-06-10T23:50:51.486 INFO (pid:3566621) [attach] - receive notification: format []
2024-06-10T23:50:51.494 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:51.516 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 8 ]
2024-06-10T23:50:51.795 INFO (pid:3566621) [attach] - receive notification: highlight []
2024-06-10T23:50:52.146 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:52.445 INFO (pid:3566621) [attach] - receive notification: highlight []
2024-06-10T23:50:52.481 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:52.781 INFO (pid:3566621) [attach] - receive notification: highlight []
2024-06-10T23:50:53.138 INFO (pid:3566621) [attach] - Request action: documentSymbols []
2024-06-10T23:50:53.154 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 8 ]
2024-06-10T23:50:54.885 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:55.105 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:55.110 ERROR (pid:3566621) [provider-manager] - Provider error on provideSelectionRanges: _ResponseError: start: pos 0 is not in range [10754:10790] of file /home/cj/Downloads/test-go/main.go
    at handleResponse (/home/cj/.vim/plugged/coc.nvim/build/index.js:20190:40)
    at handleMessage (/home/cj/.vim/plugged/coc.nvim/build/index.js:20000:11)
    at processMessageQueue (/home/cj/.vim/plugged/coc.nvim/build/index.js:20015:13)
    at Immediate.<anonymous> (/home/cj/.vim/plugged/coc.nvim/build/index.js:19991:11)
    at process.processImmediate (node:internal/timers:476:21) {
  code: 0,
  data: undefined
}
2024-06-10T23:50:55.208 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:56.027 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:56.199 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:56.201 ERROR (pid:3566621) [provider-manager] - Provider error on provideSelectionRanges: _ResponseError: start: pos 0 is not in range [13982:14021] of file /home/cj/Downloads/test-go/main.go
    at handleResponse (/home/cj/.vim/plugged/coc.nvim/build/index.js:20190:40)
    at handleMessage (/home/cj/.vim/plugged/coc.nvim/build/index.js:20000:11)
    at processMessageQueue (/home/cj/.vim/plugged/coc.nvim/build/index.js:20015:13)
    at Immediate.<anonymous> (/home/cj/.vim/plugged/coc.nvim/build/index.js:19991:11)
    at process.processImmediate (node:internal/timers:476:21) {
  code: 0,
  data: undefined
}
2024-06-10T23:50:57.910 INFO (pid:3566621) [attach] - Request action: doKeymap [ 'i-PGJzPg==' ]
2024-06-10T23:50:57.916 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:58.205 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:58.209 ERROR (pid:3566621) [provider-manager] - Provider error on provideSelectionRanges: _ResponseError: start: pos 0 is not in range [20450:20489] of file /home/cj/Downloads/test-go/main.go
    at handleResponse (/home/cj/.vim/plugged/coc.nvim/build/index.js:20190:40)
    at handleMessage (/home/cj/.vim/plugged/coc.nvim/build/index.js:20000:11)
    at processMessageQueue (/home/cj/.vim/plugged/coc.nvim/build/index.js:20015:13)
    at Immediate.<anonymous> (/home/cj/.vim/plugged/coc.nvim/build/index.js:19991:11)
    at process.processImmediate (node:internal/timers:476:21) {
  code: 0,
  data: undefined
}
2024-06-10T23:50:59.524 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:59.884 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:59.885 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:50:59.932 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 8 ]
2024-06-10T23:51:00.091 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:00.193 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:00.533 INFO (pid:3566621) [attach] - receive notification: doAutocmd [
  3,
  {
    regcontents: [ '  fmt.Println(2)' ],
    visual: false,
    inclusive: false,
    regname: '',
    operator: 'd',
    regtype: 'V'
  },
  1,
  1000
]
2024-06-10T23:51:00.535 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:00.596 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 8 ]
2024-06-10T23:51:00.655 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:00.956 INFO (pid:3566621) [attach] - receive notification: highlight []
2024-06-10T23:51:01.669 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:02.273 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:02.274 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:02.476 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 8 ]
2024-06-10T23:51:02.575 INFO (pid:3566621) [attach] - receive notification: highlight []
2024-06-10T23:51:03.843 INFO (pid:3566621) [attach] - receive notification: runCommand [ 'editor.action.organizeImport' ]
2024-06-10T23:51:05.402 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:05.604 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 8 ]
2024-06-10T23:51:05.702 INFO (pid:3566621) [attach] - receive notification: highlight []
2024-06-10T23:51:10.672 INFO (pid:3566621) [attach] - receive notification: installExtensions [ 'coc-go' ]
2024-06-10T23:51:10.692 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 4, 3 ]
2024-06-10T23:51:10.715 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:10.794 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:10.894 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:10.994 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:11.099 INFO (pid:3566621) [extension-installer] - Fetched info of coc-go {
  'dist.tarball': 'https://registry.npmmirror.com/coc-go/-/coc-go-1.3.33.tgz',
  'engines.coc': '^0.0.82',
  version: '1.3.33',
  name: 'coc-go'
}
2024-06-10T23:51:11.102 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:11.182 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:11.197 INFO (pid:3566621) [attach] - Request action: documentSymbols []
2024-06-10T23:51:11.458 INFO (pid:3566621) [model-download] - Download completed: URL {
  href: 'https://registry.npmmirror.com/coc-go/-/coc-go-1.3.33.tgz',
  origin: 'https://registry.npmmirror.com',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'registry.npmmirror.com',
  hostname: 'registry.npmmirror.com',
  port: '',
  pathname: '/coc-go/-/coc-go-1.3.33.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2024-06-10T23:51:11.458 INFO (pid:3566621) [model-download] - Downloaded https://registry.npmmirror.com/coc-go/-/coc-go-1.3.33.tgz => /home/cj/.config/coc/extensions/node_modules/coc-go-c7b54694-799c-4ac8-80e8-5c0ce53c189d
2024-06-10T23:51:11.468 INFO (pid:3566621) [attach] - receive notification: highlight []
2024-06-10T23:51:15.635 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:15.936 INFO (pid:3566621) [attach] - receive notification: highlight []
2024-06-10T23:51:16.399 INFO (pid:3566621) [services] - LanguageClient gopls state change: stopped => starting
2024-06-10T23:51:16.468 INFO (pid:3566621) [services] - LanguageClient gopls state change: starting => running
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.add_dependency already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.add_import already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.apply_fix already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.check_upgrades already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.edit_go_directive already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.fetch_vulncheck_result already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.gc_details already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.generate already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.go_get_package already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.list_imports already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.list_known_packages already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.mem_stats already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.regenerate_cgo already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.remove_dependency already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.reset_go_mod_diagnostics already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.run_go_work_command already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.run_govulncheck already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.run_tests already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.start_debugging already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.start_profile already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.stop_profile already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.test already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.tidy already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.toggle_gc_details already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.update_go_sum already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.upgrade_dependency already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.vendor already registered
2024-06-10T23:51:16.468 WARN (pid:3566621) [commands] - Command gopls.workspace_stats already registered
2024-06-10T23:51:16.469 INFO (pid:3566621) [services] - service go started
2024-06-10T23:51:16.847 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 8 ]
2024-06-10T23:51:17.393 INFO (pid:3566621) [attach] - receive notification: runCommand [ 'explorer', '--preset', 'default' ]
2024-06-10T23:51:17.463 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 4, 4 ]
2024-06-10T23:51:17.467 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:17.482 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:17.782 INFO (pid:3566621) [attach] - receive notification: highlight []
2024-06-10T23:51:17.988 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:18.289 INFO (pid:3566621) [attach] - receive notification: highlight []
2024-06-10T23:51:18.781 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:51:19.081 INFO (pid:3566621) [attach] - receive notification: highlight []
2024-06-10T23:52:10.441 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 5, 3 ]
2024-06-10T23:52:10.486 INFO (pid:3566621) [attach] - receive notification: doAutocmd [ 1 ]
2024-06-10T23:52:10.488 INFO (pid:3566621) [attach] - Request action: documentSymbols []
2024-06-10T23:52:10.770 INFO (pid:3566621) [attach] - receive notification: highlight []

```

## Describe the bug

I haven't used this features for months because it seems broken for months OR I misconfigured something, this feature stopped working for:

- rust via coc-rust-analyzer
- go via coc-go
- typescript via coc-tsserver

## Reproduce the bug

https://github.com/GopherJ/dotfiles/blob/cb8ac4fc333890a779bbb7223a9f2b4e85c3357f/coc/.vimrc#L602

- Create file `main.go` with：

```go
func main() {
fmt.Println(1) // try to import fmt
}
```

- Create file `main.go` with：
```rust
fn main() {
    fs // try to import std::fs
    println!("Hello, world!");
}
```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by GopherJ** [comment]
the error message that I got is:

```
[coc.nvim] Organize import action not found

```

**Comment by fannheyward** [comment]
Can't reproduce, the `editor.action.organizeImport` command works as expected.

Enable the `verbose` trace logs, search `organizeImports` request and response to check the logs from the server.

**Comment by GopherJ** [comment]
@fannheyward I turned on verbose and when I trigger 

```
command! -nargs=0 OR   :call     CocActionAsync('runCommand', 'editor.action.organizeImport')
```

there doesn't seem to be any trace related to organizeimports

**Comment by fannheyward** [comment]
Your logs didn't contain the `organizeImports` codeAction request, make sure you've triggered it correctly.

**Comment by GopherJ** [comment]
@fannheyward as I said I triggered it but somehow nothing sent to the server and nothing happened

**Comment by fannheyward** [comment]
After you trigger `editor.action.organizeImport` command, coc.nvim will request codeActions from language server, with `source.organizeImports` kind to find organizedImport codeAction.

The rust-analyzer didn't provide `source.organizeImports` support, you can search `codeActionProvider` in the trace logs and rust-analyzer didn't provide `source.organizeImports` kind , coc.nvim couldn't find any codeAction, didn't send request and notify you with `Organize import action not found`.

You can also test `gopls` and you will find gopls provided `source.organizeImports` kind codeAction.

**Comment by GopherJ** [comment]
gopls didn't work either, do you use coc-go or gopls directly?

**Comment by GopherJ** [comment]
Lol I just didn't a different test and gopls worked! so maybe it just didn't work in simple  main.go case

**Comment by GopherJ** [comment]
ok it will work if I add:

```
package main
```

so I think it's rust-analyzer which caused confusion, I had memories its organize import works

**Comment by GopherJ** [comment]
ok rust-analyzer still didn't implement it
