### ISSUE TITLE
[!BUG] Error while triggering completion: Action "CompleteStop" not exist

### ISSUE THREAD

**Issue by Debajyati** [neoclide/coc.nvim#5145]
## Result from CocInfo
```log
### versions

vim version: VIM - Vi IMproved 9.0 9002018
node version: v21.7.3
coc.nvim version: 0.0.82-e108777 2023-11-27 04:48:08 +0100
coc.nvim directory: /home/debajyati/.vim/plugged/coc.nvim
term: dumb
platform: linux

### Log of coc.nvim

2024-09-20T19:49:01.064 INFO (pid:30059) [plugin] - coc.nvim initialized with node: v21.7.3 after 369
2024-09-20T19:49:01.067 ERROR (pid:30059) [node-client] - request error on "nvim_call_function" [ 'pyxeval', [ '1' ] ] Error: request error on "nvim_call_function" - Vim(return):E117: Unknown function: pyxeval on api "call_function" ["pyxeval",["1"]]
    at UltiSnippetsProvider.init (/home/debajyati/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:3335:18)
    at /home/debajyati/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:1671:23
    at Array.map (<anonymous>)
    at ProviderManager.init (/home/debajyati/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:1670:33)
    at Object.activate (/home/debajyati/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:3921:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-09-20T19:49:01.089 INFO (pid:30059) [services] - LanguageClient clangd state change: stopped => starting
2024-09-20T19:49:01.094 INFO (pid:30059) [language-client-index] - Language server "clangd" started with 30093
2024-09-20T19:49:01.203 INFO (pid:30059) [services] - LanguageClient clangd state change: starting => running
2024-09-20T19:49:01.213 INFO (pid:30059) [services] - service clangd started
2024-09-20T19:49:01.604 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:49:02.887 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:49:03.932 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:49:05.317 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:49:05.758 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:49:07.261 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:03.655 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:05.183 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:08.097 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:08.624 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:09.705 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:13.673 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:14.861 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:23.035 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:25.912 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:29.875 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:30.275 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:31.426 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:38.769 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:40.146 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:41.181 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:41.958 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:43.084 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:45.287 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:46.307 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:48.284 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:51:59.817 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:52:06.534 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:52:11.801 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:52:12.886 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:52:14.197 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:52:15.101 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:52:17.051 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:52:19.801 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:52:24.037 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:52:25.489 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:53:08.184 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:53:12.875 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:53:13.578 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:53:15.150 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:53:16.236 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:53:16.915 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:53:23.988 INFO (pid:30059) [services] - LanguageClient vim language server state change: stopped => starting
2024-09-20T19:53:23.992 INFO (pid:30059) [language-client-index] - Language server "vimlsp" started with 31288
2024-09-20T19:53:24.194 INFO (pid:30059) [services] - LanguageClient vim language server state change: starting => running
2024-09-20T19:53:24.196 INFO (pid:30059) [services] - service vimlsp started
2024-09-20T19:53:24.264 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:53:28.377 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:53:34.236 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:53:36.044 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:53:44.208 INFO (pid:30059) [attach] - Request action: CompleteStop [ 'confirm' ]
2024-09-20T19:53:44.209 ERROR (pid:30059) [attach] - Request error: CompleteStop [ 'confirm' ] Error: Action "CompleteStop" not exist
    at Plugin.cocAction (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:90922:17)
    at EventEmitter.<anonymous> (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:91057:38)
    at EventEmitter.emit (node:events:519:28)
    at EventEmitter.handleRequest (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:17159:14)
    at VimTransport.emit (node:events:519:28)
    at Connection2.<anonymous> (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:16483:16)
    at Connection2.emit (node:events:519:28)
    at Connection2.parseData (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:16358:16)
    at Socket.onData (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:16325:22)
    at Socket.emit (node:events:519:28)
2024-09-20T19:54:04.165 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:54:08.653 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:54:12.094 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:54:22.234 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:54:25.307 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:54:25.794 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:54:28.829 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:54:29.585 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:54:30.028 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:54:29.798 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:54:37.185 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:54:38.607 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:54:39.483 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:54:40.495 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:54:43.717 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:56:17.750 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:56:18.763 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:56:19.684 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:56:31.724 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:58:14.763 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:58:15.949 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:58:19.039 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T19:58:23.545 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:02:40.507 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:02:41.787 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:02:40.848 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:02:42.325 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:02:54.418 INFO (pid:30059) [attach] - Request action: CompleteStop [ 'confirm' ]
2024-09-20T20:02:54.419 ERROR (pid:30059) [attach] - Request error: CompleteStop [ 'confirm' ] Error: Action "CompleteStop" not exist
    at Plugin.cocAction (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:90922:17)
    at EventEmitter.<anonymous> (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:91057:38)
    at EventEmitter.emit (node:events:519:28)
    at EventEmitter.handleRequest (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:17159:14)
    at VimTransport.emit (node:events:519:28)
    at Connection2.<anonymous> (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:16483:16)
    at Connection2.emit (node:events:519:28)
    at Connection2.parseData (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:16358:16)
    at Socket.onData (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:16325:22)
    at Socket.emit (node:events:519:28)
2024-09-20T20:06:26.568 INFO (pid:30059) [attach] - Request action: CompleteStop [ 'confirm' ]
2024-09-20T20:06:26.569 ERROR (pid:30059) [attach] - Request error: CompleteStop [ 'confirm' ] Error: Action "CompleteStop" not exist
    at Plugin.cocAction (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:90922:17)
    at EventEmitter.<anonymous> (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:91057:38)
    at EventEmitter.emit (node:events:519:28)
    at EventEmitter.handleRequest (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:17159:14)
    at VimTransport.emit (node:events:519:28)
    at Connection2.<anonymous> (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:16483:16)
    at Connection2.emit (node:events:519:28)
    at Connection2.parseData (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:16358:16)
    at Socket.onData (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:16325:22)
    at Socket.emit (node:events:519:28)
2024-09-20T20:08:09.903 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:08:10.974 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:08:11.369 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:08:12.614 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:08:13.431 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:08:14.105 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:08:14.622 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:08:15.311 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:08:15.783 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:08:16.542 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:08:17.168 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:08:17.802 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:10:00.461 INFO (pid:30059) [attach] - Request action: CompleteStop [ 'confirm' ]
2024-09-20T20:10:00.462 ERROR (pid:30059) [attach] - Request error: CompleteStop [ 'confirm' ] Error: Action "CompleteStop" not exist
    at Plugin.cocAction (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:90922:17)
    at EventEmitter.<anonymous> (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:91057:38)
    at EventEmitter.emit (node:events:519:28)
    at EventEmitter.handleRequest (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:17159:14)
    at VimTransport.emit (node:events:519:28)
    at Connection2.<anonymous> (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:16483:16)
    at Connection2.emit (node:events:519:28)
    at Connection2.parseData (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:16358:16)
    at Socket.onData (/home/debajyati/.vim/plugged/coc.nvim/build/index.js:16325:22)
    at Socket.emit (node:events:519:28)
2024-09-20T20:11:20.902 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:11:22.889 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:17:45.987 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:17:46.756 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:17:49.593 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:17:50.640 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:17:52.279 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:17:52.653 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:17:54.663 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:17:55.335 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:17:56.930 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:17:57.910 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:17:58.733 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:17:59.236 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:01.668 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:02.124 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:03.169 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:03.677 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:11.451 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:13.118 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:13.829 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:14.549 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:15.851 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:17.350 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:17.864 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:18.664 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:20.623 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:22.230 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:24.330 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:25.976 INFO (pid:30059) [attach] - receive notification: highlight []
2024-09-20T20:18:58.491 INFO (pid:30059) [attach] - receive notification: showInfo []
```

## Describe the bug
I use the snippet provided in the README to trigger completion by clicking ENTER
```vim
" Make <CR> to accept selected completion item or notify coc.nvim to format
" <C-g>u breaks current undo, please make your own choice
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
```
After updating coc.nvim whenever triggering autocomplete using any lsp by clicking ENTER, I get this ERROR MESSAGE - 
```vim
Error detected while processing function coc#pum#close[21]..coc#rpc#request[4]..<SNR>22_request[34]..function coc#pum#close[21]..coc#rpc#request[4]..<SNR>22_request:
E605: Exception not caught: Error on "CompleteStop" request: Action "CompleteStop" not exist
```
I think this part of the source code is creating the problem - 
![scrrenshot of the function in the source code creating the problem](https://github.com/user-attachments/assets/7dc7ad06-1f7e-41f8-b5d9-9a3f377c539b)

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  filetype plugin indent on
  syntax on
  set wildmenu
  call plug#begin('~/.vim/plugged')
  Plug 'neoclide/coc.nvim'
  call plug#end()
  inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
  ```

- Start vim with command: `vim -u mini.vim`

- Open a file of which lsp is installed. Suppose clangd is installed. (`:CocInstall coc-clangd`)
- Try to get suggestions (such as type `#include` to get some autosuggestions and then press **Enter** for completion.
![Screenshot 2024-09-20 211950](https://github.com/user-attachments/assets/135dce5b-a856-4406-9621-778ada791b18)
- You will notice an blocking error message at the cmdline ( I have provided scrrenshot at the end ). Press **Enter** to continue.
- However now you do get the autocomplete but get an `-1` written in the same line of the file just after the completion.![image](https://github.com/user-attachments/assets/c8c8dba5-0949-46af-ba23-69f6e9178b88)

## Screenshot
![Errormessage when trying to get autocomplete by pressing return (<CR>) key](https://github.com/user-attachments/assets/4443b29c-91b6-45ec-8295-7d2c7051d544)

**Comment by fannheyward** [comment]
> coc.nvim version: 0.0.82-e108777 2023-11-27 04:48:08 +0100

You're using an outdated release, please upgrade your coc.nvim.
