### ISSUE TITLE
compile_commands.json with false errors

### ISSUE THREAD

**Issue by mvrozanti** [neoclide/coc.nvim#516]
**Result from CocInfo**
```
## versions

vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.49
term: screen-256color
platform: linux

## Error messages
UnhandledRejection: Can't save the database
DatabaseError: Can't save the database
    at JsonDB.save (/snapshot/coc.nvim/node_modules/node-json-db/dist/JsonDB.js:336:19)
    at JsonDB.push (/snapshot/coc.nvim/node_modules/node-json-db/dist/JsonDB.js:251:12)
    at Extensions.checkUpdate (/snapshot/coc.nvim/lib/extensions.js:98:16)
    at __dirname.init.nvim.onDidActiveExtension (/snapshot/coc.nvim/lib/extensions.js:69:37)
    at CallbackList.invoke (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/snapshot/coc.nvim/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at __dirname.activate.extension.activate.then (/snapshot/coc.nvim/lib/extensions.js:367:44)
    at <anonymous>

```

**Describe the bug**
I get `[json] [W] Incorrect type. Expected "object".` on every line when editing the following `compile_commands.json`:

```
[
{
  "directory": "/home/nexor/mackenzie/tcc1/test/openacc/build",
  "command": "/home/nexor/.local/bin/pgc++     -I/opt/pgi/linux86-64/18.10/include/ -o CMakeFiles/openacc.dir/vecAdd.c.o   -c /home/nexor/mackenzie/tcc1/test/openacc/vecAdd.c",
  "file": "/home/nexor/mackenzie/tcc1/test/openacc/vecAdd.c"
},
{
  "directory": "/home/nexor/mackenzie/tcc1/test/openacc/build",
  "command": "/home/nexor/.local/bin/pgc++     -I/opt/pgi/linux86-64/18.10/include/ -o CMakeFiles/openacctest.dir/vecAdd.c.o   -c /home/nexor/mackenzie/tcc1/test/openacc/vecAdd.c",
  "file": "/home/nexor/mackenzie/tcc1/test/openacc/vecAdd.c"
}
]
```

**To Reproduce**
1:
```
cat > CMakeLists.txt <<<EOL 
cmake_minimum_required(VERSION 3.13)
project(openacctest)
set(CMAKE_CXX_COMPILER /home/nexor/.local/bin/pgc++)
set(HEADER_FILES "/opt/pgi/linux86-64/18.10/include/openacc.h")
set(SOURCE_FILES vecAdd.cpp)
add_library(openacc vecAdd.cpp ${HEADER_FILES})
add_executable(openacctest ${SOURCE_FILES})
target_link_libraries(openacctest m)
EOL
cmake .
```

![image](https://user-images.githubusercontent.com/11381662/54247707-b9306900-4518-11e9-987b-4c910a741223.png)

**Comment by chemzqm** [comment]
> coc.nvim version: 0.0.49

You're using a quite old coc.nvim version.

**Comment by mvrozanti** [comment]
```
## versions

vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.59
term: screen-256color
platform: linux

## Error messages
```

@chemzqm
Update didn't work either though

**Comment by chemzqm** [comment]
Your build should be failed, vim-plug doesn't populate error messges for you, try `:call coc#util#build()` to rebuild the module.

**Comment by chemzqm** [comment]
The error message is expected since it doesn't match schema provided http://schemastore.org.
You can rewrite it by provide setting `"json.schemas"`

**Comment by mvrozanti** [comment]
There's no `compile_commands.json` on that link. I'm not sure what a json schema means, I'm gonna look it up.

**Comment by mvrozanti** [comment]
This seems extremely unnecessary for me, is there any way to disable it?
