### ISSUE TITLE
clipboard: error: no buffers, and something about warnings

### ISSUE THREAD

**Issue by mihaelartz** [neoclide/coc.nvim#518]
Hello!

- I have a problem, when select completion from CocConfig - json i get error message: clipboard: error: no buffers. Can you add an option to disable warnings? For many things I get a lot of warnings, but still everything works properly, e.g.: Code: -32001 (clangd - cpp) but i still get completions

- Sorry for my bad English. Thanks!

**Comment by mihaelartz** [comment]
@chemzqm 

- With coc (html, json, I have not noticed in others) extensions i get clipboard error, when use clangd. intelephense langauge servers then get a error like Code: some number but i still get completions, I'm annoyed that I always get some messages in cmd!!!

My Neovim configuration
```vim
" ========== Plugins ==========
if !empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
    call plug#begin('~/.config/nvim/plugged')

    " Completion
    if executable('yarn')
        Plug 'neoclide/coc.nvim', { 'tag': '*', 'do': 'yarn install' }
    endif

    Plug 'jiangmiao/auto-pairs'
    Plug 'Shougo/echodoc.vim'
    Plug 'mattn/emmet-vim'

    " Navigation
    Plug 'scrooloose/nerdtree'
    Plug 'ctrlpvim/ctrlp.vim'

    " Languages
    Plug 'HerringtonDarkholme/yats.vim'
    Plug 'pangloss/vim-javascript'
    Plug 'bfrg/vim-cpp-modern'
    Plug 'othree/html5.vim'
    Plug 'elzr/vim-json'

    " Interface
    Plug 'vim-airline/vim-airline'
    Plug 'morhetz/gruvbox'
    
    " Tools
    Plug 'majutsushi/tagbar'
    Plug 'mbbill/undotree'
    Plug 'w0rp/ale'

    call plug#end()
endif

" ========== Autocommands ==========
augroup Indenting
    autocmd!
    autocmd FileType json,cpp,c
        \ setlocal softtabstop=2 shiftwidth=2 tabstop=2
augroup END

" ========== Settings ==========
set completeopt=noinsert,noselect,menuone
set completeopt-=preview

set background=dark
set shortmess+=Ic
set shell=bash

set updatetime=200
set laststatus=0
set pumheight=15

set softtabstop=4
set shiftwidth=4
set tabstop=4

set nocursorcolumn
set nocursorline
set smartindent
set autoindent
set noshowmode
set lazyredraw
set nohlsearch
set noswapfile
set noreadonly
set ignorecase
set noshowcmd
set expandtab
set autowrite
set autoread
set nobackup
set hidden
set nowrap
set number

" ========== Maps ==========
imap <expr><cr> pumvisible() ? '<c-y>' : '<cr>'

nmap <silent><c-q> :bp<cr>:bd#<cr>
nmap <silent><c-s> :w<cr>

nmap <c-right> <c-w>l
nmap <c-down> <c-w>j
nmap <c-left> <c-w>h
nmap <c-up> <c-w>k

nmap <s-right> dw
nmap <s-left> dvb

" ========== NerdTree ==========
if globpath(&runtimepath, 'autoload/nerdtree.vim') !=# ''
    nmap <silent><c-n> :NERDTreeToggle<cr>

    let NERDTreeAutoDeleteBuffer = 1
    let NERDTreeMinimalUI = 1
endif

" ========== UndoTree ==========
if globpath(&runtimepath, 'autoload/undotree.vim') !=# ''
    nmap <silent><f5> :UndotreeToggle<cr>

    if has('persistent_undo')
        set undodir=$HOME/.undodir
        set undofile
    endif

    let g:undotree_SetFocusWhenToggle = 1
    let g:undotree_WindowLayout = 3
endif

" ========== Echodoc ==========
if globpath(&runtimepath, 'autoload/echodoc.vim') !=# ''
    augroup Echodoc
        autocmd!
        autocmd BufEnter *
            \ if index(['javascript', 'typescript', 'cpp', 'c'], &filetype) < 0
            \|   if echodoc#is_enabled()
            \|       call echodoc#disable()
            \|   endif
            \| else
            \|   if !echodoc#is_enabled()
            \|       call echodoc#enable()
            \|   endif
            \| endif
    augroup END
endif

" ========== Gruvbox ==========
if globpath(&runtimepath, 'colors/gruvbox.vim') !=# ''
    let g:gruvbox_contrast_dark = 'hard'

    colorscheme gruvbox
    syntax enable
endif

" ========== AirLine ==========
if globpath(&runtimepath, 'autoload/airline.vim') !=# ''
    let g:airline_powerline_fonts = 1
endif

" ========== Tagbar ==========
if globpath(&runtimepath, 'autoload/tagbar.vim') !=# ''
    nmap <silent><f9> :TagbarToggle<cr>
endif

" ========== Emmet ==========
if globpath(&runtimepath, 'autoload/emmet.vim') !=# ''
    augroup Emmet
        autocmd!
        autocmd FileType html,css EmmetInstall
    augroup END

    let g:user_emmet_install_global = 0
    let g:user_emmet_mode = 'i'
endif

" ========== CtrlP ==========
if globpath(&runtimepath, 'autoload/ctrlp.vim') !=# ''
    let g:ctrlp_custom_ignore = {
        \ 'file': '\v\.(tar.gz|tar.xz|tar.bz2|tar|zip|rar|iso|jar|dll|exe|so)$',
        \ 'dir': '\v[\/](node_modules|vendor|build)|(\.(vscode|idea|git))$'
        \ }
endif

" ========== Ale ==========
if globpath(&runtimepath, 'autoload/ale.vim') !=# ''
    nmap <silent><c-j> <Plug>(ale_previous_wrap)
    nmap <silent><c-k> <Plug>(ale_next_wrap)

    let g:ale_javascript_eslint_suppress_missing_config = 1
    let g:ale_javascript_eslint_suppress_eslintignore = 1

    let g:ale_virtualtext_cursor = 1
    let g:ale_echo_cursor = 0

    let g:ale_sign_warning = '⚠'
    let g:ale_sign_error = '✖'

    let g:ale_linters = {
        \ 'javascript': ['eslint'],
        \ 'typescript': ['tslint'],
        \ 'cpp': ['gcc'],
        \ 'c': ['gcc']
        \ }
endif

" ========== Coc ==========
if globpath(&runtimepath, 'autoload/coc.vim') !=# ''
    nmap <silent><leader>de <Plug>(coc-definition)
    nmap <silent><leader>re <Plug>(coc-rename)

    let g:coc_snippet_prev = '<s-tab>'
    let g:coc_snippet_next = '<tab>'

    let g:coc_global_extensions = [
        \ 'coc-tsserver',
        \ 'coc-json',
        \ 'coc-html',
        \ 'coc-css'
        \ ]
    let g:coc_user_config = {
        \ 'coc.preferences.diagnostic.enable': v:false,
        \ 'suggest.minTriggerInputLength': 2,
        \ 'suggest.timeout': 5000
        \ }
endif
```

**Comment by chemzqm** [comment]
Please provide result from `:CocInfo`

**Comment by chemzqm** [comment]
Seems the error is not from coc.nvim.

**Comment by mihaelartz** [comment]
@chemzqm 

## versions

vim version: NVIM v0.4.0-372-g9312e2d06
node version: v10.15.3
coc.nvim version: 0.0.59
term: screen-256color
platform: linux

## Error messages

## Output channel: languageserver.intelephense
[Info  - 12:44:04 PM] Initialising
[Info  - 12:44:04 PM] Reading state from /tmp/2b321f2b.
[Info  - 12:44:05 PM] Initialised in 531 ms
[Info  - 12:44:05 PM] Indexing started.
[Info  - 12:44:10 PM] Indexing ended. 98 files indexed in 4s.
[Info  - 12:44:10 PM] Writing state to /tmp/2b321f2b.
[Info  - 12:44:10 PM] Wrote state in 0.5s.
[Error  - 12:44:21 PM] TypeError: Cannot read property 'insertUseDeclaration' of undefined
    at T._toCompletionItem (/home/zlianon/.npm-global/lib/node_modules/intelephense/lib/intelephense.js:39:170195)
    at T.completions (/home/zlianon/.npm-global/lib/node_modules/intelephense/lib/intelephense.js:39:169172)
    at T.completions (/home/zlianon/.npm-global/lib/node_modules/intelephense/lib/intelephense.js:39:177062)
    at t.CompletionProvider.provideCompletionItems (/home/zlianon/.npm-global/lib/node_modules/intelephense/lib/intelephense.js:39:166614)
    at t.Intelephense.<anonymous> (/home/zlianon/.npm-global/lib/node_modules/intelephense/lib/intelephense.js:39:160318)
    at Generator.next (<anonymous>)
    at /home/zlianon/.npm-global/lib/node_modules/intelephense/lib/intelephense.js:39:155701
    at new Promise (<anonymous>)
    at i (/home/zlianon/.npm-global/lib/node_modules/intelephense/lib/intelephense.js:39:155478)
    at t.Intelephense.provideCompletions (/home/zlianon/.npm-global/lib/node_modules/intelephense/lib/intelephense.js:39:160227)
[Error  - 12:44:21 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'insertUseDeclaration' of undefined
  Code: -32603

**Comment by mihaelartz** [comment]
@chemzqm Error with clipboard i fixed

**Comment by chemzqm** [comment]
The error is from your language server: intelephense.
You need contact the author for help.

**Comment by mihaelartz** [comment]
Resolved in new version of intelephense.
