### ISSUE TITLE
Server languageserver.bash failed to start: Error: spawn EFTYPE

### ISSUE THREAD

**Issue by lsq** [neoclide/coc.nvim#5223]
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.1 9010931
node version: v23.1.0
coc.nvim version: 0.0.82-aacbbcad 2024-11-23 13:34:02 +0800
coc.nvim directory: C:\msys64\home\Administrator\.vim\plugged\coc.nvim
term: xterm-256color
platform: win32

## Log of coc.nvim

2024-12-17T16:02:27.186 INFO (pid:1844) [extension:coc-git] - Looking for git in: git
2024-12-17T16:02:27.385 INFO (pid:1844) [plugin] - coc.nvim initialized with node: v23.1.0 after 730
2024-12-17T16:02:27.387 INFO (pid:1844) [services] - LanguageClient bash state change: stopped => starting
2024-12-17T16:02:27.387 INFO (pid:1844) [services] - LanguageClient bash-language-server state change: stopped => starting
2024-12-17T16:02:27.403 INFO (pid:1844) [services] - LanguageClient bash state change: starting => stopped
2024-12-17T16:02:27.404 ERROR (pid:1844) [services] - Server languageserver.bash failed to start: Error: spawn EFTYPE
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:753:9)
    at C:\msys64\home\Administrator\.vim\plugged\coc.nvim\build\index.js:75221:47
    at async LanguageClient.createConnection (C:\msys64\home\Administrator\.vim\plugged\coc.nvim\build\index.js:74591:28)
    at async LanguageClient._start (C:\msys64\home\Administrator\.vim\plugged\coc.nvim\build\index.js:74222:30)
    at async Object.start (C:\msys64\home\Administrator\.vim\plugged\coc.nvim\build\index.js:75720:17) {
  errno: -4028,
  code: 'EFTYPE',
  syscall: 'spawn'
}
2024-12-17T16:02:27.408 INFO (pid:1844) [services] - LanguageClient bash-language-server state change: starting => stopped
2024-12-17T16:02:27.408 ERROR (pid:1844) [services] - Server sh failed to start: Error: spawn EFTYPE
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:753:9)
    at C:\msys64\home\Administrator\.vim\plugged\coc.nvim\build\index.js:75221:47
    at async LanguageClient.createConnection (C:\msys64\home\Administrator\.vim\plugged\coc.nvim\build\index.js:74591:28)
    at async LanguageClient._start (C:\msys64\home\Administrator\.vim\plugged\coc.nvim\build\index.js:74222:30)
    at async Object.start (C:\msys64\home\Administrator\.vim\plugged\coc.nvim\build\index.js:75720:17) {
  errno: -4028,
  code: 'EFTYPE',
  syscall: 'spawn'
}
2024-12-17T16:02:27.409 INFO (pid:1844) [attach] - receive notification: highlight []
2024-12-17T16:02:34.135 INFO (pid:1844) [attach] - receive notification: showInfo []

```

## Describe the bug

`Server languageserver.bash failed to start: Error: spawn EFTYPE`

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim
set nocompatible
set runtimepath^=~/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
let g:coc_global_extension = ['coc-sh']
let g:coc_data_home="~/.config/coc"
```
- Set `coc-settings.json`

```json
{
  "languageserver": {
    "bash": {
      "command": "C:\\msys64\\ucrt64\\bin\\bash-language-server.ps1",
      "args": ["start"],
      "filetypes": ["sh"],
      "trace.server": "verbose"
    }
  }
}
```
- Start (neo)vim with command: `vim -u mini.vim  checkNet.sh`

- Operate vim.

## Screenshots (optional)
![image](https://github.com/user-attachments/assets/efdecfd2-e80b-415e-a3d5-26aa5ff3d257)
![image](https://github.com/user-attachments/assets/54ac0b2a-0a81-49b1-8b90-a2f514d23222)

**Comment by fannheyward** [comment]
Does `C:\\msys64\\ucrt64\\bin\\bash-language-server.ps1 start` work?

> let g:coc_global_extension = ['coc-sh']

You're using coc-sh, you don't need to setup `bash` in coc-settings.json's language server anymore.

**Comment by lsq** [comment]
![image](https://github.com/user-attachments/assets/3a5b809d-8b3a-4030-b2ea-5d73fa581fc7)
`C:\\msys64\\ucrt64\\bin\\bash-language-server.ps1` start work.  Delete `bash` setting, the error no disappeared.

**Comment by fannheyward** [comment]
Have no idea about this, the `EFTYPE` error means `inappropriate file type or format`, that Node.js can't start it in your env.

**Comment by lsq** [comment]
I search the result, Windows doesn't support shebang:
https://stackoverflow.com/questions/37459717/error-spawn-enoent-on-windows
https://github.com/moxystudio/node-cross-spawn

Above the `build\index.js` line 75221, I add:

```
options2.shell = process.platform === "win32";
```
And use shell script with
`"command": "C:\\msys64\\ucrt64\\bin\\bash-language-server"`, not PowerShell script, language server works.
But with `.ps1` or `.cmd`, there is another problem. I'm not very familiar with javascript and typescript, cannot firgure out how to fix it. Any help appreciated.

**Comment by lsq** [comment]
@fannheyward I learned to commit a PR to `coc-git`  with same issue, and support bash in windows platform;
