### ISSUE TITLE
Codelens can't open file on ruby-lsp

### ISSUE THREAD

**Issue by casprwang** [neoclide/coc.nvim#5229]
## Result from CocInfo

```
2024-12-18T19:26:26.082 ERROR (pid:20712) [attach] - Error on notification codeLensAction Error: Command: rubyLsp.openFile not found
    at CommandManager.executeCommand (/Users/songwang/.local/share/nvim/lazy/coc.nvim/build/index.js:27285:25)
    at CommandManager.execute (/Users/songwang/.local/share/nvim/lazy/coc.nvim/build/index.js:27233:21)
    at CodeLensBuffer.doAction (/Users/songwang/.local/share/nvim/lazy/coc.nvim/build/index.js:83986:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async CodeLensManager2.doAction (/Users/songwang/.local/share/nvim/lazy/coc.nvim/build/index.js:84095:18)
    at async Plugin.cocAction (/Users/songwang/.local/share/nvim/lazy/coc.nvim/build/index.js:89804:16)
    at async EventEmitter.<anonymous> (/Users/songwang/.local/share/nvim/lazy/coc.nvim/build/index.js:89915:15)

```

```
[Trace - 7:10:04 PM] Received response 'textDocument/codeLens - (7)' in 0ms.
Result: [
    {
        "range": {
            "start": {
                "line": 3,
                "character": 2
            },
            "end": {
                "line": 5,
                "character": 5
            }
        },
        "command": {
            "title": "Jump to view",
            "command": "rubyLsp.openFile",
            "arguments": [
                [
                    "file:///Users/songwang/dev/rails/store/app/views/products/index.html.erb"
                ]
            ]
        },
        "data": {
            "type": "file"
        }
    },
    {
        "range": {
            "start": {
                "line": 7,
                "character": 2
            },
            "end": {
                "line": 9,
                "character": 5
            }
        },
        "command": {
            "title": "Jump to view",
            "command": "rubyLsp.openFile",
            "arguments": [
                [
                    "file:///Users/songwang/dev/rails/store/app/views/products/show.html.erb"
                ]
            ]
        },
        "data": {
            "type": "file"
        }
    },
    {
        "range": {
            "start": {
                "line": 11,
                "character": 2
            },
            "end": {
                "line": 13,
                "character": 5
            }
        },
        "command": {
            "title": "Jump to view",
            "command": "rubyLsp.openFile",
            "arguments": [
                [
                    "file:///Users/songwang/dev/rails/store/app/views/products/new.html.erb"
                ]
            ]
        },
        "data": {
            "type": "file"
        }
    },
    {
        "range": {
            "start": {
                "line": 24,
                "character": 2
            },
            "end": {
                "line": 25,
                "character": 5
            }
        },
        "command": {
            "title": "Jump to view",
            "command": "rubyLsp.openFile",
            "arguments": [
                [
                    "file:///Users/songwang/dev/rails/store/app/views/products/edit.html.erb"
                ]
            ]
        },
        "data": {
            "type": "file"
        }
    }
]

```

## Describe the bug

The codelen in ruby-lsp should be called to open files. It works in VSCode but not coc.

It looks like coc is not properly calling this [openFile function](https://github.com/Shopify/ruby-lsp/blob/b005fbcfb53a9202e939a4c72bdc348a110d9874/vscode/src/commands.ts#L15)?

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.lua` with：

```lua
-- Lazy.vim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
-- End of lazy.vim

require("lazy").setup("plugins", {
  change_detection = {
    -- automatically check for config file changes and reload the ui
    enabled = false,
    notify = false, -- get a notification when changes are found
  },
  {
    "neoclide/coc.nvim",
    enabled = true,
    branch = "master",
    build = "npm ci",
    config = function()
      vim.opt.backup = false
      vim.opt.writebackup = false
      vim.opt.updatetime = 300
      vim.opt.signcolumn = "yes"
      local keyset = vim.keymap.set
      local opts = { silent = true, noremap = true, expr = true, replace_keycodes = false }
      keyset("n", "<leader>l", "<Plug>(coc-codelens-action)", opts)
    end,
  }
})
```

```json
{
  "codeLens.enable": true,
  "codeLens.position": "eol",
  "languageserver": {
    "ruby-lsp": {
      "command": "ruby-lsp",
      "initializationOptions": {
        "enabledFeatures": {
          "codeActions": true,
          "codeLens": true,
          "completion": true,
          "definition": true,
          "diagnostics": true,
          "documentHighlights": true,
          "documentLink": true,
          "documentSymbols": true,
          "foldingRanges": true,
          "formatting": true,
          "hover": true,
          "inlayHint": true,
          "onTypeFormatting": true,
          "selectionRanges": true,
          "semanticHighlighting": true,
          "signatureHelp": true,
          "typeHierarchy": true,
          "workspaceSymbol": true
        }
      },
      "filetypes": ["ruby", "erb"],
      "featuresConfiguration": {
        "inlayHint": {
          "implicitHashValue": true,
          "implicitRescue": true
        }
      },
      "indexing": {
        "excludedPatterns": ["path/to/excluded/file.rb"],
        "includedPatterns": ["path/to/included/file.rb"],
        "excludedGems": ["gem1", "gem2", "etc."],
        "excludedMagicComments": ["compiled:true"]
      },
      "formatter": "auto",
      "linters": [],
      "experimentalFeaturesEnabled": true
    }
  },
  "inlayHint.enable": false,
  "inlayHint.enableParameter": false,

}
```

- Start (neo)vim with command: `nvim -u mini.lua`

- Operate vim.

## Screenshots (optional)

Expected:

https://github.com/user-attachments/assets/499bd082-d37c-4305-a00d-6676f9fe6c6b

Currently

https://github.com/user-attachments/assets/f2edf841-b989-4fb7-8be8-a4dbcef38e12

**Comment by fannheyward** [comment]
The `rubyLsp.openFile` is a custom command, you need an extension to support this.

**Comment by chemzqm** [comment]
You can create a coc.nvim extension which add support for that command, see `:h coc-api-single`
