### ISSUE TITLE
Unable to use `coc-rename` with `vim`

### ISSUE THREAD

**Issue by st0nie** [neoclide/coc.nvim#5234]
## Result from CocInfo

```
2024-12-30T20:45:36.264 INFO (pid:122749) [attach] - receive notification: doAutocmd [ 1, 4 ]
2024-12-30T20:45:44.866 INFO (pid:122749) [attach] - receive notification: doAutocmd [ 2, 4 ]
2024-12-30T20:45:46.380 INFO (pid:122749) [attach] - receive notification: showInfo []
2024-12-30T20:45:46.381 INFO (pid:122749) [attach] - receive notification: doAutocmd [ 1, 5 ]
2024-12-30T20:46:10.942 INFO (pid:122749) [attach] - Request action: rename []
2024-12-30T20:46:10.946 ERROR (pid:122749) [node-client-root] - request error on "nvim_call_function" [
  'coc#dialog#create_prompt_win',                                                          
  [ 
    'New name',                                                                            
    'test',                                                                                
    { 
      rounded: true,                                                                       
      maxWidth: 80,
      highlight: 'CocFloating',
      borderhighlight: 'CocFloating'                                                       
    }                                                                                      
  ]
] Error: request error on "nvim_call_function" - Vim(let):E117: 未知的函数: term_start on api "call_function" ["coc#dialog#create_prompt_win",["New name","test",{"highlight":"CocFloating","maxWidth":80,"rounded":true,"borderhighlight":"CocFloating"}]]                      
    at InputBox.show (/home/ston/.vim/plugged/coc.nvim/build/index.js:27679:35)            
    at /home/ston/.vim/plugged/coc.nvim/build/index.js:37187:25                            
    at /home/ston/.vim/plugged/coc.nvim/build/index.js:29099:49                            
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)          
    at async Dialogs.requestInput (/home/ston/.vim/plugged/coc.nvim/build/index.js:37185:18)
    at async Window2.requestInput (/home/ston/.vim/plugged/coc.nvim/build/index.js:49624:16)
    at async Rename.rename (/home/ston/.vim/plugged/coc.nvim/build/index.js:87094:21)
    at async Plugin.cocAction (/home/ston/.vim/plugged/coc.nvim/build/index.js:89805:16)   
2024-12-30T20:46:10.946 ERROR (pid:122749) [attach] - Request error: rename [] Error: request error on "nvim_call_function" - Vim(let):E117: 未知的函数: term_start on api "call_function" ["coc#dialog#create_prompt_win",["New name","test",{"highlight":"CocFloating","maxWidth":80,"rounded":true,"borderhighlight":"CocFloating"}]]
    at InputBox.show (/home/ston/.vim/plugged/coc.nvim/build/index.js:27679:35)
    at /home/ston/.vim/plugged/coc.nvim/build/index.js:37187:25
    at /home/ston/.vim/plugged/coc.nvim/build/index.js:29099:49
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)          
    at async Dialogs.requestInput (/home/ston/.vim/plugged/coc.nvim/build/index.js:37185:18)
    at async Window2.requestInput (/home/ston/.vim/plugged/coc.nvim/build/index.js:49624:16)
    at async Rename.rename (/home/ston/.vim/plugged/coc.nvim/build/index.js:87094:21)      
    at async Plugin.cocAction (/home/ston/.vim/plugged/coc.nvim/build/index.js:89805:16)   
2024-12-30T20:46:33.549 INFO (pid:122749) [attach] - receive notification: showInfo []
2024-12-30T20:46:33.550 INFO (pid:122749) [attach] - receive notification: doAutocmd [ 1, 6 ]
2024-12-30T20:46:35.070 INFO (pid:122749) [attach] - receive notification: doAutocmd [ 2, 6 ]
2024-12-30T20:46:37.967 INFO (pid:122749) [attach] - receive notification: doAutocmd [ 2, 5 ]
    

```

## Describe the bug

When run `coc-rename` function, the prompt not show and there are errors in `:CocInfo`

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim
set nocompatible
set runtimepath^=/home/ston/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
```

- Start vim with command: `vim -u mini.vim`

- Operate vim.
- `:echo CocAction('rename')`

## Screenshots (optional)

![image](https://github.com/user-attachments/assets/6cacbf33-4067-422a-b410-4aaa288c2128)

**Comment by st0nie** [comment]
Also, after testing, only `vim` triggers this issue, and `neovim` displays the rename hover window correctly

**Comment by fannheyward** [comment]
What's your vim version and coc.nvim release ?

**Comment by st0nie** [comment]
Ok I made a stupid mistake, vim needs +terminal

**Comment by chemzqm** [comment]
Need support vim without terminal.
