### ISSUE TITLE
CocAction('doHover') floating windows are not always closed

### ISSUE THREAD

**Issue by Synray** [neoclide/coc.nvim#531]
**Result from CocInfo**
<details>
<summary>:CocInfo</summary>
<p>

versions

vim version: NVIM v0.4.0-391-gb90256e6c
node version: v8.9.0
coc.nvim version: 0.0.60
term: xterm-kitty
platform: linux

</p>
</details>

**Description**
Normally, floating windows are closed when the cursor moves. Calling CocAction('doHover') many times can create floating windows that are not automatically closed. The only way that I've found to close these windows is to click on them and manually close them.

**To Reproduce**
The most consistent way to reproduce this is to map 'doHover' to a key and hold the key down.
1. Open a test file. I'm using the ccls language server for C/C++.
```bash
nvim test.c
```
2. Write some code.
```c
int main(void)
{
    int i = 0;
    int j = 0;

}
```
3. Map `CocAction('doHover')` to a key:
```vim
:nmap <silent> <M-i> :<C-U>call CocAction('doHover')<CR>
```
4. Put the cursor on an identifier, then hold the key down.
5. When you move the cursor, the floating window will stay open.

**Screenshots**
The floating window is created by holding down the mapped key:
![test1](https://user-images.githubusercontent.com/31429825/54471514-686a7b80-4777-11e9-95dc-259f19984340.png)
The floating window stays open when the cursor is moved, even when another floating window is created.
![test3](https://user-images.githubusercontent.com/31429825/54471526-86d07700-4777-11e9-9b79-ceb3cb1d7280.png)

**Comment by chemzqm** [comment]
You can press `<C-w>o` to close other windows.
I will fix this issue.

**Comment by Synray** [comment]
Thanks for addressing this so quickly. I can still make the bug happen, if I hold the key down for 5-10 seconds or more.

Could it possibly be a bug with neovim? I opened a few floating windows on top of each other, and when I closed one, neovim segfaulted.

**Comment by chemzqm** [comment]
@Synray No new release, need pull latest master and build from source code, instead of use `"tag":"*"` in `Plug` command.

**Comment by Synray** [comment]
Ohhh I forgot about that. I had removed the `"tag":"*"` but I also needed to change the `"do"` command to `'yarn install'`. It works now, thanks.

**Comment by perrupa** [comment]
This is still happening for me pretty consistently, would love to reopen the issue if possible.

```
vim version: NVIM v0.4.3
node version: v10.16.3
coc.nvim version: 0.0.74-d83536aa4e
term: iTerm.app
platform: darwin
```

> You can press <C-w>o to close other windows.
This is not _really_ an appropriate workaround or fix. It will close all windows (which includes splits) and is really a bandaid for the symptom, not a cure for the cause.

If there's anything I can do to help with reproducing the error, please let me know. It's frequent, but not consistent so it's hard to replicate.

Thanks so much for all the work so far, coc.nvim is such a game changer that I'm super happy to help out as best I can 😅

**Comment by chemzqm** [comment]
@perrupa try latest neovim.

**Comment by perrupa** [comment]
> @perrupa try latest neovim.

I'm already on the latest stable version of neovim. Do you know if this issue been resolved in the nightly? I'll give it a try and report back if it the floating windows continue to remain open.

**Comment by SamHH** [comment]
I'm still having this issue intermittently and having to hit `<C-w>o`. It _seems_ to be random so unfortunately no repro at this stage.

**Comment by reergymerej** [comment]
<C-w>o closes all others, right?  Is there a way to just close the floating window?  I'm getting this pretty frequently.

**Comment by chemzqm** [comment]
Use `:call coc#util#float_hide()`

**Comment by comatory** [comment]
Hey I hate to comment on closed issue. This is what `:CocInfo` gets me

```
vim version: NVIM v0.5.0-1f56f9a4b
node version: v12.14.0
coc.nvim version: 0.0.78-fc983ce6dd
term: screen-256color
platform: darwin
```
Sometimes the float window will be kept open. The trick with `<C-w>o` works but happens randomly so just reporting here.

**Comment by SamHH** [comment]
Adding onto the above, here's my `:CocInfo` where this sometimes happens:

```
vim version: NVIM v0.4.3
node version: v13.12.0
coc.nvim version: 0.0.78-fc983ce6dd
term: alacritty
platform: linux
```

It also happens to me on macOS and with older Node versions, and has been happening for a while (i.e. with old `coc.nvim` versions as well).

**Comment by reergymerej** [comment]
I've got the latest, too, otherwise I wouldn't have said anything.

**Comment by chemzqm** [comment]
We need debug log of coc.nvim to address this issue, please follow these steps:

* Add `let g:node_client_debug = 1` to your vimrc.
* Restart your vim/neovim to make the issue happen.
* Open the log file by command `:call coc#client#open_log()`.
* Attach the log file or paste content from the log.

**Comment by chemzqm** [comment]
@reergymerej could be problem of your neovim or other plugin, can't reproduce

**Comment by reergymerej** [comment]
I've added the debug switch.  I'll try and capture a log the next time it happens.  Thanks!

**Comment by reergymerej** [comment]
![Screen Shot 2020-04-21 at 14 28 33](https://user-images.githubusercontent.com/1720010/79915760-66dc9f80-83dc-11ea-9203-67ed09e9f06b.png)

`:call coc#client#open_log()` opens an empty file.  `:CocOpenLog` doesn't seem to work (though it did before this happened.  🤷‍♂️

**Comment by yannham** [comment]
I have the same problem, editing Rust with coc-rust-analyzer. I get
```
E121: Undefined variable: g:node_client_debug
```
If I try to add
```
let g:node_client_debug = 1
```
To my vimrc. 

The problematic window seems to appear during auto-completion (showing the doc of an entry), and then stays. If I trigger the auto-completion list again, it seems to get rid of it.

```
vim version: NVIM v0.4.3
node version: v10.20.1
coc.nvim version: 0.0.78-9d846734a2
term: xterm-256color
platform: linux
```

**Comment by qubies** [comment]
This issue started for me after I moved from coc-rls to coc-rust-analyzer. 
I was able to get the floating window to disappear normally by uninstalling coc via plug, and reinstalling from source. 
`Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}`

**Comment by chemzqm** [comment]
Read doc of vim-plug for update your vim exrension.

**Comment by qubies** [comment]
Update did not seem to fix it for me, had to be removed.

**Comment by rudolfs** [comment]
Can reliably reproduce it when hitting `ctrl + c` instead of `esc` when a second floating window is open:

![repro](https://user-images.githubusercontent.com/158411/86481537-8420d900-bd50-11ea-820c-1efe7e0fe3be.gif)

coc-rust-analyzer 0.7.9

```
vim version: NVIM v0.4.3
node version: v12.17.0
coc.nvim version: 0.0.78-551353208d
term: iTerm.app
platform: darwin
```

**Comment by reergymerej** [comment]
You may be onto something. I use <C-c> instead of esc.

**Comment by chemzqm** [comment]
It's not possible for plugin to detect ctrl+c, you can remap it

**Comment by a-torgovitsky** [comment]
I also use C-c to exit insert mode and was having this same problem.
What I didn't realize (and what is alluded to by @chemzqm in his recent post) is that C-c and Esc are different commands.
This [StackExchange post](https://unix.stackexchange.com/questions/53633/does-using-ctrlc-instead-of-esc-to-exit-insert-mode-break-anything-in-vi) explains the difference well.
The solution (for me at least) was to just remap C-c to Esc via
```vimscript
inoremap <C-c> <Esc>
```

**Comment by a-torgovitsky** [comment]
> I also use C-c to exit insert mode and was having this same problem.
> What I didn't realize (and what is alluded to by @chemzqm in his recent post) is that C-c and Esc are different commands.
> This [StackExchange post](https://unix.stackexchange.com/questions/53633/does-using-ctrlc-instead-of-esc-to-exit-insert-mode-break-anything-in-vi) explains the difference well.
> The solution (for me at least) was to just remap C-c to Esc via
> 
> ```
> inoremap <C-c> <Esc>
> ```

The solution above stopped reliably working for me. I am not sure why. New workaround that I found suggested [in related issue #1940](https://github.com/neoclide/coc.nvim/issues/1940) is to bind escape to manually close floating windows:
```vim
nmap <Esc> :call coc#util#float_hide() <CR>
```
If I encounter a ghosting window that won't go away I just hit escape and it disappears. Not perfect, but ok for now.

**Comment by javiertury** [comment]
The workaround has worked reliably for me, but lately I the following warning appeared.

```
coc#util#float_hide is deprecated, use coc#float#close_all instead
```

So now escape has to be binded to

```
nmap <Esc> :call coc#util#close_all() <CR>
```

**Comment by daGrevis** [comment]
Seems that this has been renamed again.

New name is `coc#util#close_floats()`.

**Comment by chemzqm** [comment]
> Seems that this has been renamed again.
> 
> New name is `coc#util#close_floats()`.

You have old coc.nvim in your `&rtp`, that function was removed.

**Comment by kaka-ruto** [comment]
Updating to `0.5.1` fixed it for me

**Comment by tankorsmash** [comment]
I'm running 
```
vim version: NVIM v0.9.1
node version: v16.17.0
coc.nvim version: 0.0.81-bacd91d7 2022-06-03 10:34:52 +0800
coc.nvim directory: C:\Users\fiveb\.vim\plugged\coc.nvim
term: undefined
platform: win32
```

and I've got a floating window still, and this is the error in the logs:

```
2023-10-03T16:56:43.445 ERROR (pid:23376) [node-client] - request error on "nvim_call_function" [
  'coc#dialog#create_pum_float',
  [
    0,
    165,
    [ '(method) Tile.toTuple(): [number, number]' ],
    {
      codes: [Array],
      highlights: [],
      maxWidth: 80,
      pumbounding: [Object],
      focusable: 0
    }
  ]
] Keyboard interrupt Error
    at BM.request (C:\Users\USERNAME\.vim\plugged\coc.nvim\build\index.js:29:43425)
    at BM.call (C:\Users\USERNAME\.vim\plugged\coc.nvim\build\index.js:34:3815)
    at MD.show (C:\Users\USERNAME\.vim\plugged\coc.nvim\build\index.js:277:37260)
    at pte.onPumChange (C:\Users\USERNAME\.vim\plugged\coc.nvim\build\index.js:277:49369)
    at async C:\Users\USERNAME\.vim\plugged\coc.nvim\build\index.js:277:40991
2023-10-03T16:56:43.446 ERROR (pid:23376) [events] - Error on event: MenuPopupChanged Error: request error on nvim_call_function - Keyboard interrupt
    at MD.show (C:\Users\USERNAME\.vim\plugged\coc.nvim\build\index.js:277:37260)
    at pte.onPumChange (C:\Users\USERNAME\.vim\plugged\coc.nvim\build\index.js:277:49369)
    at async C:\Users\USERNAME\.vim\plugged\coc.nvim\build\index.js:277:40991
```

I also have Ctrl-C remapped to Esc, and often mash CtrlC to leave insert mode.
