### ISSUE TITLE
Error on create float window

### ISSUE THREAD

**Issue by kozer** [neoclide/coc.nvim#539]
I build neovim from source (distro: arch, using aur package neovim-git),
and when in logs I get the following error:

```
2019-03-17T13:02:40.846 ERROR (pid:15685) [model-float] - Error on create float window: Error: request nvim_open_win - Wrong number of arguments: expecting 3 but got 5
    at transport.request (/home/kozer/.config/nvim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:33:28)
    at Transport.parseMessage (/home/kozer/.config/nvim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:137:17)
    at DecodeStream.Transport.decodeStream.on (/home/kozer/.config/nvim/plugged/coc.nvim/node_modules/@chemzqm/neovim/lib/utils/transport.js:43:18)
    at emitOne (events.js:116:13)
    at DecodeStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at DecodeStream.Readable.push (_stream_readable.js:208:10)
    at DecodeStream.Transform.push (_stream_transform.js:147:32)
    at DecodeBuffer.DecodeStream.decoder.push (/home/kozer/.config/nvim/plugged/coc.nvim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)
```
```node version: 8.14.1```

**Comment by chemzqm** [comment]
Your neovim have incompatible API with current neovim master.
`nvim_open_win()` should require 5 params.

**Comment by kozer** [comment]
Shouldn't I build from master?
Running ```git describe --long``` I get the following:
```
warning: tag 'v0.3.4' is really 'stable' here
v0.3.4-413-g9ef8d0d6b
```
Do I miss something here?

**Comment by kozer** [comment]
I closed it by mistake, sorry

**Comment by kozer** [comment]
https://github.com/neovim/neovim/commit/9ef8d0d6b0a8a607b2ee3fe3ca38395e470a2223
This one seems to change some things

**Comment by chemzqm** [comment]
Get it, the api changed.

**Comment by kozer** [comment]
I think this should be done it:
https://github.com/neoclide/coc.nvim/pull/541

**Comment by kozer** [comment]
This should fix it
https://github.com/neoclide/coc.nvim/pull/543/files
