### ISSUE TITLE
Type error when ChildProcess exit

### ISSUE THREAD

**Issue by huiyiqun** [neoclide/coc.nvim#583]
**Result from CocInfo**

```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 23 2019 03:19:33)
node version: v11.8.0
coc.nvim version: 0.0.61
term: dumb
platform: linux

## Error messages
Uncaught exception: TypeError: Cannot convert object to primitive value
    at ChildProcess.serverProcess.on.code (/home/huiyiqun/.vim/bundle/coc.nvim/lib/language-client/index.js:348:39)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
Uncaught exception: TypeError: Cannot convert object to primitive value
    at ChildProcess.serverProcess.on.code (/home/huiyiqun/.vim/bundle/coc.nvim/lib/language-client/index.js:348:39)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
Uncaught exception: TypeError: Cannot convert object to primitive value
    at ChildProcess.serverProcess.on.code (/home/huiyiqun/.vim/bundle/coc.nvim/lib/language-client/index.js:348:39)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
Uncaught exception: TypeError: Cannot convert object to primitive value
    at ChildProcess.serverProcess.on.code (/home/huiyiqun/.vim/bundle/coc.nvim/lib/language-client/index.js:348:39)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
Uncaught exception: TypeError: Cannot convert object to primitive value
    at ChildProcess.serverProcess.on.code (/home/huiyiqun/.vim/bundle/coc.nvim/lib/language-client/index.js:348:39)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
## Output channel: highlight
[Info  - 03:42:21 GMT+0000 (-00)] Highlight server running in node v11.8.0

## Output channel: java
[Info  - 03:43:27 GMT+0000 (-00)] Connection to server got closed. Server will restart.
[Info  - 03:43:27 GMT+0000 (-00)] Connection to server got closed. Server will restart.
[Info  - 03:43:27 GMT+0000 (-00)] Connection to server got closed. Server will restart.
[Info  - 03:43:27 GMT+0000 (-00)] Connection to server got closed. Server will restart.
[Error  - 03:43:27 GMT+0000 (-00)] Connection to server got closed. Server will not be restarted.
```

**Describe the bug**
Seems a problem of coc-java but the coc.nvim also failed to handle the exception.

**To Reproduce**
1. install coc.nvim
2. install coc-java
3. open a java file
4. type `instance.`, there is no completion at all
5. see the error in CocInfo

**Comment by chemzqm** [comment]
It's fixed on master, it happens when you open file no exists on disk.
