### ISSUE TITLE
js-langserver does not start

### ISSUE THREAD

**Issue by threkk** [neoclide/coc.nvim#630]
**Result from CocInfo**
```
## versions

vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.64
term: screen-256color
platform: darwin

## Error messages
(node:49396) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:49396) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
## Output channel: prettier

## Output channel: tsserver
[Info  - 11:02:43] Forking TSServer
PATH: /Users/threkk/.bin:/Users/threkk/.cargo/bin:/Users/threkk/.npm-packages/bin:/Users/threkk/Documents/projects/bin:/usr/local/opt/python/libexec/bin:/usr/local/opt/python@2/bin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/sqlite/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/threkk/.bin:/
```

```
{
    // coc-tsserver
    "tsserver.enableJavascript": false,
    "tsserver.orgnizeImportOnSave": true,
    "typescript.preferences.noSemicolons": true,
    "typescript.preferences.quoteStyle": "single",
    "javascript.preferences.noSemicolons": true,
    "javascript.preferences.quoteStyle": "single",

    // coc-python
    "python.jediEnabled": true,
    "python.jediMemoryLimit": -1,

    // coc-prettier
    "prettier.singleQuote": true,
    "prettier.semi": false,

    "languageserver": {
        // go-langserver
        "golang": {
            "command": "go-langserver",
            "filetypes": ["go"],
            "initializationOptions": {
                "gocodeCompletionEnabled": true,
                "diagnosticsEnabled": true,
                "lintTool": "golint"
            }
        },
        // javascript
        "js": {
            "command": "js-langserver",
            "args": ["--stdio"],
            "filetypes": ["javascript.jsx", "javascript", "jsx"]
        },
        // docker-langserver
        "dockerfile": {
            "command": "docker-langserver",
            "filetypes": ["dockerfile"],
            "args": ["--stdio"]
        },
        // bash-language-server
        "bash": {
            "command": "bash-language-server",
            "args": ["start"],
            "filetypes": ["sh"],
            "ignoredRootPaths": ["~"]
        }
    }
}
```

**Describe the bug**
I am trying to use https://github.com/tbodt/js-langserver instead of the tsserver for better JavaScript support. However, the server will not start whatsoever. I have checked the logs and the `langservice.js` is registered but it does not start. `js-langserver` is installed globally and is in the path of neovim.

**Comment by iamcco** [comment]
> I am trying to use https://github.com/tbodt/js-langserver instead of the tsserver for better JavaScript support.

really? I have not notice `js-langserver` before.

**Comment by chemzqm** [comment]
```
{ Error: Cannot find module 'eslint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at resolveFileName (/usr/local/lib/node_modules/js-langserver/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/usr/local/lib/node_modules/js-langserver/node_modules/resolve-from/index.js:43:9)
    at module.exports (/usr/local/lib/node_modules/js-langserver/node_modules/resolve-from/index.js:46:41)
    at getLinter (/usr/local/lib/node_modules/js-langserver/lint.js:14:28)
    at lintDocument (/usr/local/lib/node_modules/js-langserver/lint.js:21:20)
    at CallbackList.invoke (/usr/local/lib/node_modules/js-langserver/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/usr/local/lib/node_modules/js-langserver/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at connection.onDidOpenTextDocument (/usr/local/lib/node_modules/js-langserver/node_modules/vscode-languageserver/lib/main.js:180:29)
    at handleNotification (/usr/local/lib/node_modules/js-langserver/node_modules/vscode-jsonrpc/lib/main.js:489:43) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module 'eslint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at resolveFileName (/usr/local/lib/node_modules/js-langserver/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/usr/local/lib/node_modules/js-langserver/node_modules/resolve-from/index.js:43:9)
    at module.exports (/usr/local/lib/node_modules/js-langserver/node_modules/resolve-from/index.js:46:41)
    at getLinter (/usr/local/lib/node_modules/js-langserver/lint.js:14:28)
    at lintDocument (/usr/local/lib/node_modules/js-langserver/lint.js:21:20)
    at CallbackList.invoke (/usr/local/lib/node_modules/js-langserver/node_modules/vscode-jsonrpc/lib/events.js:62:39)
    at Emitter.fire (/usr/local/lib/node_modules/js-langserver/node_modules/vscode-jsonrpc/lib/events.js:120:36)
    at connection.onDidOpenTextDocument (/usr/local/lib/node_modules/js-langserver/node_modules/vscode-languageserver/lib/main.js:181:38)
    at handleNotification (/usr/local/lib/node_modules/js-langserver/node_modules/vscode-jsonrpc/lib/main.js:489:43) code: 'MODULE_NOT_FOUND' }
```
I don't think js-langserver better than tsserver, tsserver has more featrues, it just need types installled. Configure `tsserver.npm` to your global npm path to make sure you can use global types installed by tsserver.

**Comment by threkk** [comment]
@iamcco You should give it a try, in my experience the completions are better.
@chemzqm Maybe it is better, but for me `js-langserver` works better in my experience. The error you mention does not happen to me, maybe because I have it installed globally. The more I look into the error, the more it looks like it does not attempt to start the lang server.

**Comment by chemzqm** [comment]
It's started for me after fix eslint issues, you can checkout verbose output https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by tbodt** [comment]
FYI js-langserver is much better if you don't have types, because it uses tern to infer the types.
