### ISSUE TITLE
the last commit brreaks resolving command paths beginning with ~

### ISSUE THREAD

**Issue by dementor5** [neoclide/coc.nvim#685]
this c1b9332094c03027d0fd40c6170f889db0622771
on that 8c1dbb786b00a4c3f4368c7d509ad7b13b321f6e

error message is :
`at process._tickCallback (internal/process/next_tick.js:63:19)`

cocinfo command result is:
```
## versions

vim version: NVIM v0.4.0-dev
node version: v10.15.3
coc.nvim version: 0.0.64
term: screen-256color
platform: linux

## Error messages
Uncaught exception: Error: spawn ~/.vim/plugged/diagnostic-languageserver/bin/index.js ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
## Output channel: languageserver.dls
[Error  - 12:26:23 PM] Starting client failed: 
Error: Launching server using command ~/.vim/plugged/diagnostic-languageserver/bin/index.js failed.
    at LanguageClient.createMessageTransports (/home/user/.vim/plugged/coc.nvim/lib/language-client/index.js:348:23)
```

**Comment by dementor5** [comment]
Still does not work :)
```
## versions

vim version: NVIM v0.4.0-dev
node version: v10.15.3
coc.nvim version: 0.0.64-c1b9332094
term: screen-256color
platform: linux

## Error messages
Uncaught exception: Error: spawn ~/.vim/plugged/diagnostic-languageserver/bin/index.js ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
## Output channel: languageserver.dls
[Error  - 12:43:29 PM] Starting client failed: 
Error: Launching server using command ~/.vim/plugged/diagnostic-languageserver/bin/index.js failed.
    at LanguageClient.createMessageTransports (/home/devpa/.vim/plugged/coc.nvim/build/index.js:63828:23)
```

**Comment by chemzqm** [comment]
Just published a new bundle.

**Comment by dementor5** [comment]
Now all ok, thanks!
