### ISSUE TITLE
Cannot load extensions with node v12

### ISSUE THREAD

**Issue by heftig** [neoclide/coc.nvim#727]
Updating `nodejs` from v11.14.0 to v12.0.0 breaks all extensions.

**Result from CocInfo**

## versions

vim version: NVIM v0.3.4
node version: v12.0.0
coc.nvim version: 0.0.65
term: xterm-256color
platform: linux

## Error messages

**Result from CocOpenLog**

```
2019-04-25T18:45:59.675 INFO (pid:22205) [services] - registed service "languageserver.bash"
2019-04-25T18:45:59.676 INFO (pid:22205) [services] - registed service "languageserver.ccls"
2019-04-25T18:45:59.676 INFO (pid:22205) [services] - registed service "languageserver.flow"
2019-04-25T18:45:59.685 ERROR (pid:22205) [util-factoroy] - ReferenceError: Buffer is not defined
    at Object.<anonymous> (/home/jan/.zsh/node_modules/vscode-jsonrpc/lib/messageReader.js:10:10)
    at Module._compile (/home/jan/.zsh/nvimpack/coc.nvim/lib/util/factory.js:57:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at req (/home/jan/.zsh/nvimpack/coc.nvim/lib/util/factory.js:36:21)
    at Object.<anonymous> (/home/jan/.zsh/node_modules/vscode-jsonrpc/lib/main.js:37:25)
    at Module._compile (/home/jan/.zsh/nvimpack/coc.nvim/lib/util/factory.js:57:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
2019-04-25T18:45:59.685 ERROR (pid:22205) [extensions] - TypeError: Cannot read property 'activate' of null
    at Object.activate (/home/jan/.zsh/nvimpack/coc.nvim/lib/extensions.js:698:57)
    at Extensions.activate (/home/jan/.zsh/nvimpack/coc.nvim/lib/extensions.js:428:19)
    at Extensions.setupActiveEvents (/home/jan/.zsh/nvimpack/coc.nvim/lib/extensions.js:598:18)
    at Extensions.activateExtensions (/home/jan/.zsh/nvimpack/coc.nvim/lib/extensions.js:96:18)
    at Plugin.init (/home/jan/.zsh/nvimpack/coc.nvim/lib/plugin.js:142:34)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
    at async /home/jan/.zsh/nvimpack/coc.nvim/lib/attach.js:79:13
2019-04-25T18:45:59.691 ERROR (pid:22205) [util-factoroy] - ReferenceError: Buffer is not defined
    at Object.<anonymous> (/home/jan/.zsh/cocfiles/extensions/node_modules/vscode-jsonrpc/lib/messageReader.js:10:10)
    at Module._compile (/home/jan/.zsh/nvimpack/coc.nvim/lib/util/factory.js:57:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at req (/home/jan/.zsh/nvimpack/coc.nvim/lib/util/factory.js:36:21)
    at Object.<anonymous> (/home/jan/.zsh/cocfiles/extensions/node_modules/vscode-jsonrpc/lib/main.js:37:25)
    at Module._compile (/home/jan/.zsh/nvimpack/coc.nvim/lib/util/factory.js:57:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
2019-04-25T18:45:59.692 ERROR (pid:22205) [extensions] - TypeError: Cannot read property 'activate' of null
    at Object.activate (/home/jan/.zsh/nvimpack/coc.nvim/lib/extensions.js:698:57)
    at Extensions.activate (/home/jan/.zsh/nvimpack/coc.nvim/lib/extensions.js:428:19)
    at Extensions.setupActiveEvents (/home/jan/.zsh/nvimpack/coc.nvim/lib/extensions.js:598:18)
    at Extensions.activateExtensions (/home/jan/.zsh/nvimpack/coc.nvim/lib/extensions.js:96:18)
    at Plugin.init (/home/jan/.zsh/nvimpack/coc.nvim/lib/plugin.js:142:34)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
    at async /home/jan/.zsh/nvimpack/coc.nvim/lib/attach.js:79:13
2019-04-25T18:45:59.693 INFO (pid:22205) [plugin] - coc 0.0.65 initialized with node: v12.0.0
```

**Comment by heftig** [comment]
Ah, I see this got recently fixed in master. Thanks; sorry about the noise.
