### ISSUE TITLE
$TERM can't read correctly

### ISSUE THREAD

**Issue by NihilityT** [neoclide/coc.nvim#763]
**Result from CocInfo**

```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled May 07 2019 09:49:41)
node version: v8.10.0
coc.nvim version: 0.0.66-f8fe934f6b
term: iTerm.app
platform: linux

## Error messages
Uncaught exception: Error: spawn osascript ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Describe the bug**
The COC reads `iTerm.app` but mine is `xterm`.
This caused the following error:
```
Uncaught exception: Error: spawn osascript ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**To Reproduce**

- Create a minimal mini.vim with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start vim with command: `vim -u mini.vim`

**Screenshots**
![Screenshot from 2019-05-07 21-26-59](https://user-images.githubusercontent.com/21163191/57305316-6b4c7180-7113-11e9-94b0-9fa53c0d9296.png)
![image](https://user-images.githubusercontent.com/21163191/57305488-c3837380-7113-11e9-8e2c-88012aa85203.png)

**Comment by NihilityT** [comment]
The reason for reading into `iTerm.app` is that I installed `coc-imselect`. After I uninstalled it, I didn't have the above error, but the reading is still incorrect.
```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled May 07 2019 09:49:41)
node version: v8.10.0
coc.nvim version: 0.0.67-8741e930c9
term: dumb
platform: linux
```

**Comment by chemzqm** [comment]
Unfortunatly, coc-imselect only works for iTerm2 on mac and neovim, just fixed the check for term.
