### ISSUE TITLE
server connection lost

### ISSUE THREAD

**Issue by FelipeMarcelino** [neoclide/coc.nvim#787]
Today I made update with my plugins in neovim using PlugUpdate, and then coc.nvim stop working 

[coc] server connection lost
[coc.nvim] error: fs.js:119
    throw err;
    ^
Error: ENOENT: no such file or directory, unlink '/tmp/coc-nvim.log'
    at Object.unlinkSync (fs.js:972:3)
    at Object.<anonymous> (/home/felipemarcelino/.local/share/nvim/plugged/coc.nvim/build/index.js:43474:18)
    at __webpack_require__ (/home/felipemarcelino/.local/share/nvim/plugged/coc.nvim/build/index.js:20:30)
    at Object.<anonymous> (/home/felipemarcelino/.local/share/nvim/plugged/coc.nvim/build/index.js:41986:16)
    at __webpack_require__ (/home/felipemarcelino/.local/share/nvim/plugged/coc.nvim/build/index.js:20:30)
    at Object.<anonymous> (/home/felipemarcelino/.local/share/nvim/plugged/coc.nvim/build/index.js:37047:16)
    at __webpack_require__ (/home/felipemarcelino/.local/share/nvim/plugged/coc.nvim/build/index.js:20:30)
    at Object.<anonymous> (/home/felipemarcelino/.local/share/nvim/plugged/coc.nvim/build/index.js:1644:42)
    at __webpack_require__ (/home/felipemarcelino/.local/share/nvim/plugged/coc.nvim/build/index.js:20:30)
    at Object.<anonymous> (/home/felipemarcelino/.local/share/nvim/plugged/coc.nvim/build/index.js:100:16)

So, I thougth is a problem with my env, so I made the same upgrade in other pc and the error persists.

**Comment by arrufat** [comment]
Hi, have you tried this: https://github.com/neoclide/coc.nvim/issues/376#issuecomment-457156440

**Comment by bigardone** [comment]
@FelipeMarcelino Same error here. I have tried what @arrufat is suggesting, and it makes it work again. I wonder if this is just a random error or something else is broken in the latest version.

**Comment by chemzqm** [comment]
Fixed now, forget to upgrade the build.

**Comment by bigardone** [comment]
@chemzqm works like a charm, thanks! 🙌

**Comment by FelipeMarcelino** [comment]
Thanks, @arrufat, and @chemzqm. Everything is working now!
