### ISSUE TITLE
Error: ENOENT: no such file or directory (node-client.log)

### ISSUE THREAD

**Issue by mnrce** [neoclide/coc.nvim#842]
## Result from CocInfo
When I run `:CocInfo`, I got this:
`coc.nvim service not started, checking environment...`
and then nothing else happened.

## Describe the bug

I just installed neovim and coc.nvim for my work laptop (Ubuntu 16.04), but coc.nvim service refused to run. I get this error:
```
[coc.nvim] error: fs.js:114
    throw err;
    ^
Error: ENOENT: no such file or directory, open '/run/user/1000/snap.node/node-client.log'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at Object.<anonymous> (/home/nghialm/.config/nvim/plugged/coc.nvim/build/index.js:6065:18)
    at __webpack_require__ (/home/nghialm/.config/nvim/plugged/coc.nvim/build/index.js:20:30)
    at Object.__importDefault (/home/nghialm/.config/nvim/plugged/coc.nvim/build/index.js:5983:18)
    at __webpack_require__ (/home/nghialm/.config/nvim/plugged/coc.nvim/build/index.js:20:30)
    at Object.<anonymous> (/home/nghialm/.config/nvim/plugged/coc.nvim/build/index.js:2341:32)
    at __webpack_require__ (/home/nghialm/.config/nvim/plugged/coc.nvim/build/index.js:20:30)
    at Object.__importStar (/home/nghialm/.config/nvim/plugged/coc.nvim/build/index.js:2033:16)
    at __webpack_require__ (/home/nghialm/.config/nvim/plugged/coc.nvim/build/index.js:20:30)
client coc abnormal exit with: 1
```

## Reproduce the bug
I can reproduce the bug with this minimal `mini.vim`
  ```vim
  set nocompatible
  set runtimepath^=~/.config/nvim/plugged/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

When I start neovim with command: `nvim -u mini.vim`, I got the error as in the screenshot below.

I'm using neovim 0.3.7, nodejs v10.16.0 and yarn 1.16.0 (installed using [snap](https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions-2): `sudo snap install node --classic --channel=10`)

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/13317164/58899430-1eb28100-8727-11e9-9490-54906c0bca88.png)

`:CocInfo`
![image](https://user-images.githubusercontent.com/13317164/58899511-53bed380-8727-11e9-8d59-e11e670806cb.png)

`:checkhealth`
![image](https://user-images.githubusercontent.com/13317164/58899975-65ed4180-8728-11e9-9164-e152745718cd.png)

**Comment by chemzqm** [comment]
It's fixed on master, use nightly build instead.

**Comment by mnrce** [comment]
> It's fixed on master, use nightly build instead.

I'm using nightly build, just update using `:PlugUpdate` but doesn't fix for me.

**Comment by chemzqm** [comment]
@mnrce you're not, checkout version by `:CocInfo`

**Comment by chemzqm** [comment]
@mnrce can you check if the folder `/run/user/1000/snap.node` exists?

**Comment by mnrce** [comment]
132c099 fixes the problem for me. Thanks.
