### ISSUE TITLE
 at processTicksAndRejections (internal/process/task_queues.js:81:17)

### ISSUE THREAD

**Issue by Ja-rek** [neoclide/coc.nvim#871]
## versions

vim version: NVIM v0.4.0-999-g6c96c3b3f
node version: v11.15.0
coc.nvim version: 0.0.69
term: st-256color
platform: linux

## Messages
[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

1 line less; before #5  3 seconds ago
[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

[coc.nvim] error: Uncaught exception: Error: spawn nvim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

E492: Not an editor command: ^YCocInfo
E492: Not an editor command: nonu
97 lines yanked

E471: Argument required
## Output channel: tsserver

[Info  - 07:05:29] TSServer log file :
/tmp/coc-nvim-tsc.log
[Info  - 07:05:29] Forking TSServer
PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/jk/.fzf/bin:/home/jk/.dotnet/tools:/home/jk/.dotnet/tools:/home/jk/.dotnet/tools:/home/jk/.dotnet/tools:/home/jk/.dotnet/tools:/home/jk/.dotnet/tools:/home/jk/.dotnet/tools:/home/jk/.dotnet/tools:/home/jk/.dotnet/tools:/home/jk/.dotnet/tools:/home/jk/.dotnet/tools:/home/jk/.dotnet/tools:/home/jk/.dotnet/tools:/home/jk/.dotnet/tools:/home/jk/.dotnet/tools
[Info  - 07:05:29] Started TSServer
{
  "path": "/home/jk/.config/coc/extensions/node_modules/typescript/lib",
  "_pathLabel": "",
  "_api": {
    "versionString": "3.5.1",
    "version": "3.5.1"
  }
}

## Describe the bug

Auto completion does not work correctly.
On down of windows i see red text: 
 ``at processTicksAndRejections (internal/process/task_queues.js:81:17)``

**Comment by chemzqm** [comment]
What's result of `which nvim` in your terminal?

**Comment by Ja-rek** [comment]
I did alias in .zshrc for AppImage .

``nvim: aliased to /home/jk/.local/bin/./nvim.appimage``

**Comment by Ja-rek** [comment]
Wow, so fast. You've got the skills. Thank you mate.
