### ISSUE TITLE
Logging not working if neovim was used previously with different user rights (e.g. root) because coc-vim.log cannot be overwritten

### ISSUE THREAD

**Issue by Philipp-M** [neoclide/coc.nvim#915]
### versions

vim version: NVIM v0.4.0-1145-g10c983fab
node version: v11.15.0
coc.nvim version: 0.0.71
term: xterm-kitty
platform: linux

### Messages
```
[coc.nvim] error: log4js.fileAppender - Writing to file /run/user/1000/coc-nvim.log, error happened  { [Error: EACCES: permission denied, open '/run/user/1000/coc-nvim.log']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/run/user/1000/coc-nvim.log' }
[coc.nvim] error: log4js.fileAppender - Writing to file /run/user/1000/coc-nvim.log, error happened  Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at WriteStream.Writable.write (_stream_writable.js:299:11)
    at _shouldRoll (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:141:30)
    at RollingFileStream._shouldRoll (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:131:7)
    at RollingFileStream._write (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:135:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at RollingFileStream.Writable.write (_stream_writable.js:299:11)
    at app (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/log4js/lib/appenders/file.js:55:12)
[coc.nvim] error: log4js.fileAppender - Writing to file /run/user/1000/coc-nvim.log, error happened  Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at WriteStream.Writable.write (_stream_writable.js:299:11)
    at _shouldRoll (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:141:30)
    at RollingFileStream._shouldRoll (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:131:7)
    at RollingFileStream._write (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:135:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at RollingFileStream.Writable.write (_stream_writable.js:299:11)
    at app (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/log4js/lib/appenders/file.js:55:12)
[coc.nvim] error: log4js.fileAppender - Writing to file /run/user/1000/coc-nvim.log, error happened  Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at WriteStream.Writable.write (_stream_writable.js:299:11)
    at _shouldRoll (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:141:30)
    at RollingFileStream._shouldRoll (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:131:7)
    at RollingFileStream._write (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:135:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at RollingFileStream.Writable.write (_stream_writable.js:299:11)
    at app (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/log4js/lib/appenders/file.js:55:12)
log4js.fileAppender - Writing to file /run/user/1000/coc-nvim.log, error happened  Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at WriteStream.Writable.write (_stream_writable.js:299:11)
    at _shouldRoll (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:141:30)
    at RollingFileStream._shouldRoll (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:131:7)
    at RollingFileStream._write (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:135:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at RollingFileStream.Writable.write (_stream_writable.js:299:11)
    at app (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/log4js/lib/appenders/file.js:55:12)
[coc.nvim] error: log4js.fileAppender - Writing to file /run/user/1000/coc-nvim.log, error happened  Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at WriteStream.Writable.write (_stream_writable.js:299:11)
    at _shouldRoll (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:141:30)
    at RollingFileStream._shouldRoll (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:131:7)
    at RollingFileStream._write (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:135:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at RollingFileStream.Writable.write (_stream_writable.js:299:11)
    at app (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/log4js/lib/appenders/file.js:55:12)
[coc.nvim] error: log4js.fileAppender - Writing to file /run/user/1000/coc-nvim.log, error happened  Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at WriteStream.Writable.write (_stream_writable.js:299:11)
    at _shouldRoll (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:141:30)
    at RollingFileStream._shouldRoll (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:131:7)
    at RollingFileStream._write (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/streamroller/lib/RollingFileWriteStream.js:135:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at RollingFileStream.Writable.write (_stream_writable.js:299:11)
    at app (/home/philm/.local/share/nvim/plugged/coc.nvim/node_modules/log4js/lib/appenders/file.js:55:12)
```
### Output channel: highlight

```
[Info  - 12:26:43 AM] Highlight server running in node v11.15.0
```

## Describe the bug

Title mostly says it already.
Log has errors, and although I haven't tested most features, the least that is not working is logging, as the file cannot be written too.

## Reproduce the bug

Edit a file with e.g. root rights (e.g. `sudo -E nvim /etc/fstab`) close nvim, and reopen it.

## Suggestions

One suggestion to fix this bug might be to just create new log files with an incrementing number (like coc-nvim-1.log)
One thing I see in my case as well, the log is stored in: `/run/user/1000/coc-nvim.log`
Wouldn't it make more sense to store the log in `~/.local/share/nvim/coc-nvim.log` where nvim stores its logs?

**Comment by chemzqm** [comment]
It's fixed, you're using old version of coc.nvim.

**Comment by chemzqm** [comment]
https://github.com/neoclide/coc.nvim/blob/master/src/util/logger.ts#L7
Make sure you have different `$NVIM_COC_LOG_FILE` or `$XDG_RUNTIME_DIR` for different user.
