### ISSUE TITLE
Error on initialize: Error: EEXIST

### ISSUE THREAD

**Issue by Leeshe** [neoclide/coc.nvim#921]
Worked when I installed with `Plug 'neoclide/coc.nvim', {'./install.sh nightly'}`,
doesn't work after `:PlugUpdate`.

## Result from CocInfo

No output from `:CocInfo`.

## Describe the bug

When running Neovim, I immediately get the following error:

```vim
[coc.nvim] error: Error on initialize: Error: EEXIST: file already exists, mkdir '/home/vim/.config/coc/extensions/.cache'
    at Object.fs.mkdirSync (fs.js:885:18)
    at new ExtensionManager (/home/vim/.local/share/nvim/plugged/coc.nvim/lib/model/extension.js:24:22)
    at Extensions.init (/home/vim/.local/share/nvim/plugged/coc.nvim/lib/extensions.js:59:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

When running `:CocInstall`:

```vim
[coc.nvim] error: error on notification 'installExtensions': TypeError: Cannot read property 'install' of undefined
```

When running `Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}`:

```sh
yarn install v1.16.0
info No lockfile found.
[1/4] Resolving packages...
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ npm-run-all clean build
yarn run v1.16.0
$ rimraf lib build
Done in 0.52s.
yarn run v1.16.0
$ tsc -p tsconfig.json
error TS5058: The specified path does not exist: 'tsconfig.json'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

## Reproduce the bug

Same things happen with the given minimal configuration:

```vim
set nocompatible
set runtimepath^=~/.local/share/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
```

## Settings

Installed with `Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}`.
NVIM v0.4.0-762-g9420a2127
Ubuntu 18.04
nodejs v8.10.0
yarn 1.16.0

Checkhealth output:
```vim
health#coc#check
========================================================================
  - OK: Environment check passed
  - WARNING: pyx command not work, some extensions may fail to work, checkout ":help |pythonx|"
  - OK: Build javascript found
  - OK: Service started

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5202'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
    - ADVICE:
      - :help |clipboard|

## Python 2 provider (optional)
  - INFO: Disabled (g:loaded_python_provider=1).  This might be due to some previous error.
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.6.8
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v8.10.0
  - INFO: Neovim node.js host: /home/vim/.config/yarn/global//node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.5.0
```

**Comment by chemzqm** [comment]
problem of incompatable nodejs api

**Comment by Leeshe** [comment]
Is there a specific version that coc.nvim works with?

**Comment by chemzqm** [comment]
Nodejs >= 10.14 doesn't have this problem, I will fix this soon.
