### ISSUE TITLE
Best replacement for `vscode.window.activeTextEditor`?

### ISSUE THREAD

**Issue by TylerLeonhardt** [neoclide/coc.nvim#933]
Something that’s done in the PowerShell extension is:

```ts
                // v THIS
                const editor = vscode.window.activeTextEditor;
                // ^ THIS
                let selectionRange: vscode.Range;

                if (!editor.selection.isEmpty) {
                    selectionRange =
                        new vscode.Range(
                            editor.selection.start,
                            editor.selection.end);
                } else {
                    selectionRange = editor.document.lineAt(editor.selection.start.line).range;
                }
```
So that we can get the selected range _or_ the range of the full line if nothing is highlighted. We take this selection and run it in the terminal below.

Is there any good replacement API for this in coc?

**Comment by chemzqm** [comment]
Use `await workspace.document` to get current document.
Use `workspace.getSelectedRange` to get selected range.

**Comment by TylerLeonhardt** [comment]
@chemzqm I might be using it wrong… but I get `[coc.nvim] Command error: document.getPosition is not a function`.

My code:

```ts
const doc = await workspace.document;
const range = await workspace.getSelectedRange('v', doc.textDocument);
```

**Comment by chemzqm** [comment]
The error is not from the code you pasted.

**Comment by TylerLeonhardt** [comment]
Where can I find that function?

**Comment by TylerLeonhardt** [comment]
I found this:
```ts
const editMode = (await workspace.nvim.mode).mode
```

but it doesn’t seem to work right:
```ts
const doc = await workspace.document;
const editMode = (await workspace.nvim.mode).mode
const range = await workspace.getSelectedRange(editMode, doc.textDocument);

// OUTPUT: [coc.nvim] Mode 'n' is not supported
```

**Comment by chemzqm** [comment]
Checkout `:h visualmode()` and https://github.com/neoclide/coc.nvim/blob/master/src/handler/index.ts#L694

**Comment by chemzqm** [comment]
The command can take argument, you can pass `visualmode()` by `:CocAction('runCommand', 'id', visualmode())`

**Comment by TylerLeonhardt** [comment]
Ok so that gives me this:

```
[coc.nvim] error: TypeError: Cannot read property 'client' of undefined
    at Object.ActionsList.addAction [as execute] (/Users/tyler/.local/share/nvim/plugged/coc.nvim/build/index.js:69304:33)
    at ListManager.doItemAction (/Users/tyler/.local/share/nvim/plugged/coc.nvim/build/index.js:66877:50)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

What I ran:
```
:CocAction("runCommand", "powershell.evaluateSelection", visualmode())
```

My code:
```ts
let doEval = async function(mode: string) {
            let document = await workspace.document
            if (!document || document.filetype !== 'ps1') {
                return
            }
            
            const doc = await workspace.document;
            const range = await workspace.getSelectedRange(mode, doc.textDocument);

            client.sendRequest(EvaluateRequestType, {
                expression: content,
            });

            await proc.scrollToBottom()
        }

let cmdEvalSelection = commands.registerCommand("powershell.evaluateSelection", async (mode) => doEval(mode));

```

**Comment by chemzqm** [comment]
Don't know why you invoke action list, it's better to build coc.nvim from source code so you can debug it by Chrome, instead of ask me https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim
