### ISSUE TITLE
Getting an error message when installing coc Extension

### ISSUE THREAD

**Issue by Sammyalhashe** [neoclide/coc.nvim#976]
I can no longer install any new coc extensions. I get the following error upon installing (from `:cocOpenLog`):
```
2019-07-11T16:55:16.895 DEBUG (pid:8299) [workspace] - buffer created 1
2019-07-11T16:55:16.896 DEBUG (pid:8299) [events] - Event: BufEnter [ 1 ]
2019-07-11T16:55:16.902 DEBUG (pid:8299) [events] - Event: BufWinEnter [ 1, 1000 ]
2019-07-11T16:55:16.945 INFO (pid:8299) [services] - registed service "highlight"
2019-07-11T16:55:16.973 DEBUG (pid:8299) [languages] - created service source snippets
2019-07-11T16:55:16.974 DEBUG (pid:8299) [languages] - created service source snippets-source
2019-07-11T16:55:16.983 INFO (pid:8299) [language-client-index] - highlight started with 8311
2019-07-11T16:55:17.032 INFO (pid:8299) [plugin] - coc 0.0.73-0a0c6cc788 initialized with node: v9.0.0
2019-07-11T16:55:17.081 INFO (pid:8299) [services] - highlight server state change: starting => running
2019-07-11T16:55:22.108 INFO (pid:8299) [model-extension] - Using npm from: /Users/sammyalhashemi/.nvm/versions/node/v9.0.0/bin/npm
2019-07-11T16:55:22.108 INFO (pid:8299) [model-extension] - Loading info of coc-python.
2019-07-11T16:55:22.897 INFO (pid:8299) [model-extension] - Downloading from https://registry.npmjs.org/coc-python/-/coc-python-1.2.2.tgz
2019-07-11T16:55:23.334 ERROR (pid:8299) [server] - uncaughtException ZlibError: zlib: Cannot read property 'length' of null
    at Unzip.Zlib.(anonymous function) (/Users/sammyalhashemi/.config/nvim/plugged/coc.nvim/build/index.js:67805:21)
    at Unzip.write (/Users/sammyalhashemi/.config/nvim/plugged/coc.nvim/build/index.js:67926:21)
    at Unzip.flush (/Users/sammyalhashemi/.config/nvim/plugged/coc.nvim/build/index.js:67885:10)
    at Unzip.end (/Users/sammyalhashemi/.config/nvim/plugged/coc.nvim/build/index.js:67892:10)
    at Unpack.end (/Users/sammyalhashemi/.config/nvim/plugged/coc.nvim/build/index.js:70225:21)
    at IncomingMessage.onend (_stream_readable.js:598:10)
    at Object.onceWrapper (events.js:322:30)
    at emitNone (events.js:120:20)
    at IncomingMessage.emit (events.js:218:7)
    at endReadableNT (_stream_readable.js:1054:12)
2019-07-11T16:55:26.602 DEBUG (pid:8299) [events] - Event: BufWinLeave [ 1, 1000 ]
2019-07-11T16:55:26.603 DEBUG (pid:8299) [events] - Event: BufUnload [ 1 ]
2019-07-11T16:55:26.607 DEBUG (pid:8299) [workspace] - buffer unload 1
```

## Result from CocInfo

```
## versions

vim version: NVIM v0.4.0-760-g94f78ccf8
node version: v9.0.0
coc.nvim version: 0.0.73-0a0c6cc788
term: iTerm.app
platform: darwin

## Messages
[coc.nvim] error: Uncaught exception: ZlibError: zlib: Cannot read property 'length' of null
    at Unzip.Zlib.(anonymous function) (/Users/sammyalhashemi/.config/nvim/plugged/coc.nvim/build/index.js:67805:21)
    at Unzip.write (/Users/sammyalhashemi/.config/nvim/plugged/coc.nvim/build/index.js:67926:21)
    at Unzip.flush (/Users/sammyalhashemi/.config/nvim/plugged/coc.nvim/build/index.js:67885:10)
    at Unzip.end (/Users/sammyalhashemi/.config/nvim/plugged/coc.nvim/build/index.js:67892:10)
    at Unpack.end (/Users/sammyalhashemi/.config/nvim/plugged/coc.nvim/build/index.js:70225:21)
    at IncomingMessage.onend (_stream_readable.js:598:10)
    at Object.onceWrapper (events.js:322:30)
    at emitNone (events.js:120:20)
    at IncomingMessage.emit (events.js:218:7)
    at endReadableNT (_stream_readable.js:1054:12)
26 lines yanked
## Output channel: snippets


## Output channel: highlight

[Info  - 4:55:17 PM] Highlight server running in node v9.0.0

```

## Describe the bug
See above.

## Reproduce the bug

I don't think this requires my `init.vim`, but I can provide if you think it does.

## Screenshots (optional)

<img width="408" alt="Screen Shot 2019-07-11 at 4 59 23 PM" src="https://user-images.githubusercontent.com/20797997/61085032-4d460a80-a3fd-11e9-8138-7e952ccd3a96.png">

**Comment by Sammyalhashe** [comment]
So I did a little more investigating, and it turns out that it's failing when I use iTerm2. I switched over to Kitty and it worked. This is weird, but I switched back to iTerm2 and I got this error again. Does coc.nvim behave differently for different terminals?

**Comment by chemzqm** [comment]
Should be problem of your proxy, checkout your `$HTTP_PROXY` and `$HTTPS_PROXY`

**Comment by Sammyalhashe** [comment]
What should they be set to? I checked and they are not set

**Comment by chemzqm** [comment]
Then could be bug with your node v9.0.0

**Comment by Sammyalhashe** [comment]
Thanks, I'll look into it

**Comment by rok-povsic** [comment]
Updating node from 9 to 10 did the trick for me.
